### ISSUE TITLE
EAC3 Audio not working

### ISSUE THREAD

**Issue by heyheyitsdan** [jellyfin/jellyfin-androidtv#102]
Have tested with several different files from different sources and all play with no audio.
Files all work correctly on Emby, Plex etc... and have the same audio info details as below. 

Audio info
TitleEng Dolby Digital+ 6 ch Default
Languageeng
CodecEAC3
Channels6 ch
Sample rate48000 Hz
DefaultYes

**Comment by nextlooper42** [comment]
Tested with multiple sources (2.0 / 5.1) and E-AC3 is working on Android app (on Android TV 8) & Chromecast Gen 2 without problems.

**Comment by anthonylavado** [comment]
@heyheyitsdan Have you tried the down mix option in the settings? Does your TV or other hardware support E-AC3?

**Comment by heyheyitsdan** [comment]
All plays fine in Emby and Plex.  Downmix doesn’t make any difference.

**Comment by tekmad** [comment]
I have found the same issue, with AndroidTV app (v0.10.1g) on Shield TV. Plays fine direct in Kodi, on same hardware.

**Comment by grravity** [comment]
Seem to be having the same issue

**Comment by cruzr9038** [comment]
I'm seeing this issue on the old v0.11 and today's v0.12. EAC3 plays fine on Kodi and Emby on AndroidTV. Won't play on Jellyfin AndroidTV though.

**Comment by erbmur** [comment]
I'm having the same issue with the latest version on google TV as well.  EAC3 audio won't play.

**Comment by jessanros** [comment]
Same issue here. No AC3 audio plays on Google TV

**Comment by jeroen79** [comment]
Also the same here, doesn't play on android tv jellyfin app, does work in vlc on android tv

**Comment by Siress** [comment]
Shield TV Pro 2017 running Jellyfin v0.12.3. No audio for files with EAC3. Works fine in VLC.

**Comment by Siress** [comment]
Reddit user created a fix for this: https://www.reddit.com/r/jellyfin/comments/qm32jo/androidtv_eac3_audio_problem/

**Comment by marapavelka** [comment]
The fix doesn't work form me :(

**Comment by jessanros** [comment]
@marapavelka I wish someone had told me this a few months ago:

Just get TDARR and make all your videos mp4, audio aac, and h265 (h264 if you don't wanna wait).
Optionally remove all image based subtitles. Subtitles should be external .srt files only.

By doing this your videos will be compatible with everything, and your server won't need to transcode. My CPU doesn't budge when multiple people watch stuff. And videos load immediately, faster than youtube. Scrolling is also immediate.

**Comment by upchui** [comment]
https://github.com/upchui/Jellyfin-DirectPlayForce
I built the plugin to solve this problem.
