### ISSUE TITLE
Inconsistent forward and back skip/seek in latest dev builds on 2017 Nvidia Shield

### ISSUE THREAD

**Issue by djmandell** [jellyfin/jellyfin-androidtv#1024]
**Describe the bug**

I downloaded the July 14th build to try out the latest version of Jellyfin for Android TV.  There are some great improvements (thanks!) but one thing I notice is that skipping forward 30 seconds or back 5 seconds works inconsistently.  On Jellyfin 0.11 if I hit the left button on the remote it would skip back 5 seconds, and if I hit the left button 3 times it would skip back 5 seconds each time (15 seconds total).  If I hit the right button it would skip forward 30 seconds for however many times I hit it.  This is more or less the typical behavior in most of the apps I use on the Shield.

In the latest version of the app if I hit the left button once it will skip back 10 seconds, but then it seems the search bar gets focus and the next time I hit the left button it will move backwards to the next 30 second increment.  For example if my video is at 2:35 and I hit left once it will skip back to 2:25, if I hit left again the video will pause, it will skip back to 2:00, and any further left button presses will move back in 30 second increments.  Furthermore, the first button press will move the video back by 10 seconds, but subsequent button presses will move backwards in time on the seek bar, but not actual skip the video backwards unless you press the middle button, which will then change where you are in the video.  If you wait until the seek bar disappears or you hit the back button to dismiss the seek bar you can once again hit the left button to skip backwards by 10 seconds.  The same thing is true in the forward direction (right button press) as well.  

**To Reproduce**

1. Open any video in a 0.12 nightly build of the app
2. Allow the video to play for 1.5 minutes.
3. Hit the left button one time.  Note it skips backwards 10 seconds.
4. Hit the left button again, before the seek bar disappears.  Note the seek bar moves backwards to 1:00 the video pauses, but remains at 1:20.
5. Hit the middle button to skip back to 1 minute and resume play..

**Expected behavior**

Behavior should be consistent. Each left button press should skip back by 10 seconds without having to hit the middle button or pausing the vide, each right button press should skip forward by 30.  I can understand the value in being able to move back and forth on the seek bar, but I'd argue that a different button press should trigger it.  Perhaps long-pressing left/right?

**System (please complete the following information):**
 - Android TV 8.0.2
 - Device manufacturer: Nvidia
 - Device model: Shield 2017
 - Jellyfin server version: 10.7.6

**Comment by djmandell** [comment]
I meant to add a little bit more to the "expected behavior" section.  At a minimum even if you keep the behavior where it moves up and down the video while the video is paused (similar to YouTube's behavior) I'd still expect to seek backwards in 10 second increments, e.g 1:35 back to 1:25, back again to 1:15, then back to 1:05 and so on (or forward to 2:05, then 2:35 and so on).  The current behavior, where it goes back to 1:25 and then back to 1:00 and then backwards in 30 second increments doesn't feel like expected behavior to me.

**Comment by ManuLinares** [comment]
Related #863

Seeking is borked
