### ISSUE TITLE
French translation My Media

### ISSUE THREAD

**Issue by Nico83500** [jellyfin/jellyfin-androidtv#1028]
Hi,
There is a just a French translation missing on the home screen : My Media should be Mes Médias.
I don't know if I can modify it anywhere ? There are some others translation to make.
Thank you !

**Comment by nielsvanvelzen** [comment]
## Translating

Translations can be improved very easily from our [Weblate](https://translate.jellyfin.org/projects/jellyfin-android/jellyfin-androidtv) instance.
Look through the following graphic to see if your native language could use some work!

<a href="https://translate.jellyfin.org/engage/jellyfin-android/">
<img alt="Detailed Translation Status" src="https://translate.jellyfin.org/widgets/jellyfin-android/-/jellyfin-androidtv/multi-auto.svg"/>
</a>
