### ISSUE TITLE
0.12.x beta : notif bar still visible during playback

### ISSUE THREAD

**Issue by Salamandar** [jellyfin/jellyfin-androidtv#1034]
The notif/clock/battery bar is still visible during playback.

It should hide when video is playing or when the pause overlay hides itself.

The bug was not present on 0.11.x.

**Comment by nielsvanvelzen** [comment]
Hi, I noticed this issue does not use one of our issue templates. We provide these templates to get the information necessary in order to help. I will close this issue but I encourage you to recreate it using the template so we can help.
