### ISSUE TITLE
Playback data in android TV app

### ISSUE THREAD

**Issue by TheRealTechWiz** [jellyfin/jellyfin-androidtv#1038]
**Describe the feature you'd like**	
I am having the following issue with android TV app. 
My issue :
I am playing 5 GB h264 1080p 1 hour long video from windows 10 laptop with jellyfin 10.7.6 on local network to android TV. The video plays for 5-10 seconds and then pauses, this keeps on happening. This kind of buffering really spoils the mood to watch something. The video is not transcoding as I have disabled video transcoding for that user and everything is normal in task manager.
I can't figure out where the problem is network/container or anything else. It will be really helpful to figure out my problem if there were playback data like in jellyfin web and windows jellyfin media player.
**Additional context**	

[redit post of my issue](https://www.reddit.com/r/jellyfin/comments/opzi5c/need_help_buffering_while_playing_on_android_tv/)

**Comment by nielsvanvelzen** [comment]
Please keep the troubleshooting in the reddit thread or one of our other troubleshooting channels. Your problem could be caused by a lot of things. Feel free to re-open if the issue is in the app and needs fixing from our side.

**Comment by TheRealTechWiz** [comment]
I do understand that the issue is from my side and not from the app itself. This was a feature request for "Playback data" while playing the video similar to one found in jellyfin web. pfa the image for the same
![image](https://user-images.githubusercontent.com/42109004/127022054-d0fd68aa-6be9-4b1d-b812-8ce9b6aaa95c.png)
