### ISSUE TITLE
[bug] episode thumbnails missing in Android TV

### ISSUE THREAD

**Issue by joebckFeg8** [jellyfin/jellyfin-androidtv#1039]
**Describe the bug**
All episode thumbnails are blank when using Jellyfin for Android TV. This is the same for current version and beta 2.

**Expected behavior**
I expect to see the actual episode thumbnail, or alternatively a picture of the show cover art, except it shows a blue rectangle with white tv icon inside instead

**Screenshots**
![PXL_20210726_182722802](https://user-images.githubusercontent.com/87999209/127039807-3b45a1c5-fe62-4a20-8ae4-05ff89bbe714.jpg)

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 8.0.0, kernel 3.10.79, build BRAVIA_ATV2
 - Device manufacturer: Sony
 - Device model: KD75X8000E
 - Jellyfin server version: 10.7.5
 - Jellyfin version: org.jellyfin.androidtv 0.12.0-beta2

**Additional information**
I've tried fresh installs, testing beta, different device see screenshot below
![Screenshot_20210727-023504](https://user-images.githubusercontent.com/87999209/127040756-c6b03300-ae67-452a-820a-ba5645389bbe.png)

**Comment by nielsvanvelzen** [comment]
Do you have chapter thumbnails or backdrops?

**Comment by joebckFeg8** [comment]
Hey @nielsvanvelzen I think I may have fixed it. I didn't have episode fetcher ticked in my scraper!
