### ISSUE TITLE
sexier navigation screens for Android TV beta

### ISSUE THREAD

**Issue by joebckFeg8** [jellyfin/jellyfin-androidtv#1041]
**Describe the feature you'd like**	
Was so excited to see that we have a beta Android TV app for Jellyfin after using Jellyfin Server for so long, put struggling to have a good client on my TV.

Unfortunately the beta 2 looks exactly the same as the previous app. Would be great to see at least similar visuals to the server client or Android app please! 	

**Additional context**

**Comment by newton181** [comment]
Currently discussed here:

https://github.com/jellyfin/jellyfin-androidtv/discussions/807

**Comment by thornbill** [comment]
Saying that the 0.12 betas look exactly like 0.11 is ridiculous and frankly dismissive of all the work contributors have put into improving the appearance of the app.

As mentioned there is a discussion for future improvements.
