### ISSUE TITLE
continue watching/completed stats not refreshing

### ISSUE THREAD

**Issue by mueslimak3r** [jellyfin/jellyfin-androidtv#1043]
**Describe the bug**

Device: Chromecast w/ google TV
Issue: continue watching, completed type stats do not appear to be retrieved regularly. The result is that the partial progress bar, and "completed" checkboxes do not reflect the current state unless the app is closed or I navigate to a different page within the app to force it to talk to the server and refresh the data.

This is also true and especially annoying for putting the chromecast to sleep, playing media on another device, and waking up the chromecast and having it not reflect the playback progress on the other device without reboot the app or navigating to a different page.

**To Reproduce not refreshing properly**

1. Go to Jellyfin for Android TV
2. Play something partially
3. Press 'back' until on homepage of app and confirm that the media is in the 'continue watching' section with it's partial progress bar.
4. Go to the media and complete watching it (fully, all the way to the end)
5. When it's done go back to the app's home screen and it will still be under "continue watching" with a partial progress bar.

**Expected behavior**
The app's home screen should always reflect the current stats

**To Reproduce sleep/wake issue**

1. Go to Jellyfin for Android TV
2. Put the chromecast to sleep
3. Play media on a nother device (same account)
4. Wake up Chromecast
5. App will show the outdated stats (didn't refresh with server when woken up)

**Expected behavior**
The app's home screen should always reflect the current stats

**System (please complete the following information):**
 - Android TV or Fire TV version:  210311.008 7350836
 - Device manufacturer: Google
 - Device model: Google Chromecast with Google TV
 - Jellyfin server version: 10.7.6

**Comment by okan35** [comment]
I also have the same issue but on my xiaomi mi box the episode I just watched little bit doesn't even show up on continue watching.

**Comment by nielsvanvelzen** [comment]
This issue is not new in 0.12 and can be reproduced on 0.11.

**Comment by mueslimak3r** [comment]
fixed by #1320

**Comment by waynepaulward** [comment]
Hi I have this problem on Jellyfin client on webos 
If I watch a tv show I press play over it on the Home Screen so then when I look at what’s up next for tv the page hasn’t refreshed to I have to go into the tv show and back out to refresh the page it could be good to have a page refresh and either show refresh button option or assign a key so you could like assign say the zero key and it will refresh home page. Is this possible
