### ISSUE TITLE
0.12.x beta : notif bar still visible during playback

### ISSUE THREAD

**Issue by Salamandar** [jellyfin/jellyfin-androidtv#1044]
**Describe the bug**
The notif/clock/battery bar is still visible during playback.

The bug was not present on 0.11.x.

**To Reproduce**
1. Play a video

**Expected behavior**
It should hide when video is playing or when the pause overlay hides itself.

**Screenshots**
Can't take screenshot on this machine.

**System (please complete the following information):**
 - Android TV 9
 - no-brand android tv
 - Jellyfin server version: 10.7.x

**Comment by nielsvanvelzen** [comment]
We don't support mobile Android devices right now. The app targets televisions using Android TV or Fire TV which don't have a notification bar.

**Comment by Salamandar** [comment]
I just found back the ROM i'm using and it's Project Slimbox. It is an AndroidTV rom and it has a status bar.

**Comment by nielsvanvelzen** [comment]
Ok thanks for the info. Will be fixed in the next beta.
