### ISSUE TITLE
[Feature Request] Buffer progress in video seeker

### ISSUE THREAD

**Issue by crlssn** [jellyfin/jellyfin-androidtv#1049]
**Describe the feature you'd like**	
I sometimes have to pause and let the video buffer for a few minutes before I can play it without any interruptions and it would be handy if I could see in the seeker how much it has successfully buffered.

**Comment by okan35** [comment]
This is a feature in mpv player, it would be amazing to see it like that.

**Comment by mueslimak3r** [comment]
this feature was added by #1435
