### ISSUE TITLE
subtitle font size and drop shadow

### ISSUE THREAD

**Issue by baburam0007** [jellyfin/jellyfin-androidtv#1055]
**Checks**
- [x] Issue does not happen in the browser (jellyfin-web)

**Media Info of the file**

**Logs**

**FFmpeg Logs**

**System (please complete the following information):**
 - Android TV : Android 9 and above
 - Device manufacturer: Sony
 
 - Jellyfin server version: 10.7.5

**Additional context**
There is no option to disable the drop shadow in the subtitle section and select the font size. The font size is too big.

**Comment by thornbill** [comment]
Can you please provide the version of the app you are using? Thanks!

**Comment by baburam0007** [comment]
Currently, I'm testing on 0.12.0 beta 2. Thanks!

**Comment by thornbill** [comment]
Can you provide a screenshot/image of what the subtitles look like?

**Comment by baburam0007** [comment]
![Jellyfin dropdown shadow and font size](https://user-images.githubusercontent.com/70329150/127888918-419f36aa-c207-4cf8-8785-1f867a9ad9ce.jpg)
In the android tv app, there is no option to change to dropdown and font size

**Comment by ManuLinares** [comment]
There is not, but you can change them in these places and compile it (for now I assume)

_app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java_

line 1478: change **R.color.black_opaque** to **R.color.transparent**

_app/src/main/res/layout/vlc_player_interface.xml_

line 55: change **android:textSize="28sp"** to whatever you like, I use **android:textSize="20sp"** (and I also change android:layout_marginBottom="20dp")

**Comment by zilexa** [comment]
Can the default size please be changed?

Subtitle font size is really HUGE. 
It's one of the main reasons I'm still using Kodi with the add-on on AndroidTV. Default font size in Kodi is of normal size.

**Comment by DemirG** [comment]
> Can the default size please be changed?
> 
> Subtitle font size is really HUGE.
> It's one of the main reasons I'm still using Kodi with the add-on on AndroidTV. Default font size in Kodi is of normal size.

They have been made smaller in the first beta. Which is way better then it was before.✌️

Imo they are still a bit to big. As an European I use subtitles for everything so it a bit of a nuisance. If it's possible an option with say 10 different sizes to pick from would be great.👌

As TVs a getting bigger its looks a bit comically with large subtitles on a 77"+ TV 😁

**Comment by magounet** [comment]
Still no option to disable dropdown shadow and change the font size ?

**Comment by zilexa** [comment]
This is still a major issue, with version 12.
Subtitles are 25% of my TV! 

Why is this not solved in V12? Just change the size from megahuge to normal?

I don't even care the AndroidTV client ignores the subtitles size setting from Jellyfin server. 

This is the single reason I still use Kodi with Jellyfin add-on: the subtitle size is just abnormal and disturbing.

**Comment by ivooc** [comment]
> I got this problem too
> 
> On my android settings i got subtitles with this style:
> 
> ![20211026_223919](https://user-images.githubusercontent.com/5363187/139296126-a80403fe-8bc6-46e0-9444-b1ba0c3b7297.jpg)
> 
> On jellyfin my subtitles appear like this
> 
> ![20211026_223825](https://user-images.githubusercontent.com/5363187/139296187-edb9ade3-42b7-4da6-bc95-14213930fd20.jpg)
> 
>     * With background
> 
>     * Big ones
> 
>     * And not centered

I second this. Not being able to change font size, remove background and center text is very annoying.

**Comment by ManuLinares** [comment]
[My pull was denied](https://github.com/jellyfin/jellyfin-androidtv/pull/889), they prefered a preferences menu but I don't know how to implement it.

Here is my [patch ](https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92.patch)

https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92

**Comment by Collabeta** [comment]
> > Can the default size please be changed?
> > 
> > Subtitle font size is really HUGE.
> > It's one of the main reasons I'm still using Kodi with the add-on on AndroidTV. Default font size in Kodi is of normal size.
> 
> They have been made smaller in the first beta. Which is way better then it was before.✌️
> 
> Imo they are still a bit to big. As an European I use subtitles for everything so it a bit of a nuisance. If it's possible an option with say 10 different sizes to pick from would be great.👌
> 
> As TVs a getting bigger its looks a bit comically with large subtitles on a 77"+ TV 😁

And when watching on an even larger screen with a projector, it's so distracting.

**Comment by Collabeta** [comment]
> [My pull was denied](https://github.com/jellyfin/jellyfin-androidtv/pull/889), they prefered a preferences menu but I don't know how to implement it.
> 
> Here is my [patch ](https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92.patch)
> 
> https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92
> 

Patch link doesn't appear to show anything.

**Comment by ManuLinares** [comment]
> > [My pull was denied](https://github.com/jellyfin/jellyfin-androidtv/pull/889), they prefered a preferences menu but I don't know how to implement it.
> > Here is my [patch ](https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92.patch)
> > [ManuLinares@eae60de](https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92)
> 
> Patch link doesn't appear to show anything.

eh, is there something wrong in your end?

[Here is my patch ](https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92.patch) again... same link to my forked commit, and added .patch to the end of the url as always.

try:

`curl -L https://github.com/ManuLinares/jellyfin-androidtv/commit/eae60de5eee2caaa4cd3efb74e0707658ce5af92.patch`

**Comment by zilexa** [comment]
They don't even need to patch V12 if they are planning to add this in V13. 

All they would need to do is change the default subtitles to SANE settings. That is all dear developers. I really like and appreciate their efforts, but giving us such a completely ridiculous default sub size and colour makes me think they are just mocking their users!

**Comment by nielsvanvelzen** [comment]
> They don't even need to patch V12 if they are planning to add their own solution in V13.

There are no changes in 0.13 for subtitles at this moment and I don't think anyone is working on it.

**Comment by a1ad** [comment]
The background is terrible. Bought an android Chromecast with Google TV specialy for Jellyfin but its just unuseable. Using plex in the meantime.

**Comment by Dulox24** [comment]
Anyone knows if any option will be added in the future? I think the black background is pretty annoying on my external subtitles...
