### ISSUE TITLE
unable to play 4k media

### ISSUE THREAD

**Issue by baburam0007** [jellyfin/jellyfin-androidtv#1056]
**Checks**
- [x] Issue does not happen in the browser (jellyfin-web)

**Media Info of the file**

**Logs**

**FFmpeg Logs**

**System (please complete the following information):**
 - Android TV version: android 9 and above
 - Device manufacturer: Sony
 
 - Jellyfin server version: 10.7.5
**Additional context**
Unable to play 4k media smoothly. sometimes it plays, but the picture quality is too bad.

**Comment by thornbill** [comment]
Can you please provide the version of the app you are using? Thanks!

**Comment by baburam0007** [comment]
Currently, I'm testing on 0.12.0 beta 2. Thanks!
