### ISSUE TITLE
AI Upscaling not available (NVIDIA Shield PRO 2019)

### ISSUE THREAD

**Issue by amadeuscode10** [jellyfin/jellyfin-androidtv#1060]
NVIDIA Shileld PRO 2019 

**Additional context**

I recently added the latest beta build to my NVIDIA Shield PRO. The device can no longer apply the AI upscaling to the Jellyfin App. The AI upscaling is currently working on the public release of the app right now.

**Comment by Eisoniq** [comment]
Can confirm that playing a 1080p video on the Nvidia Shield using LibVLC or ExoPlayer the Shield's upscaling menu shows "Active: No (upscaling not required) for all 3 options, AI-Enhanced, Enhanced and Basic
