### ISSUE TITLE
Grouping episodes together

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#1063]
**Describe the feature you'd like**	
On the "dashboard" (front screen) under the section Continue Watching / Next Up, please group the episodes together. 	

**Additional context**	
I have my TV Shows directory  (with its shows and episodes as should be) and then also a symbolic links directory back to the some directories in TV Shows (only for all cooking shows for the misses - bash script auto creates it when Genre=Food). Both directories (TV Shows & Symbolic Links Directory) were added under libraries in Jellyfin (Ex TV Shows, Food Series). If a user belongs to only one of the two, then no problem. But in case you belong to both and there is an episode that was stopped half way through, it show twice under Continue Watching

Ex :
'/TVShows/Giada in Italy' -> '/FoodNetwork/Giada in Italy/' (symbolic Link)

**Comment by nielsvanvelzen** [comment]
This change would need to be made on the server side, not in the client.

**Comment by tomerh2001** [comment]
+1
