### ISSUE TITLE
(master) Unable to access user/server selection screens with automatic sign in enabled

### ISSUE THREAD

**Issue by linetrimmer** [jellyfin/jellyfin-androidtv#1065]
**Describe the bug**
The user selection button in the home screen toolbar causes the splash/home screen to load instead of the user selection screen. This issue occurs only when automatic sign in is enabled.

**To Reproduce**
1. Enable automatic sign in
2. Go to the app home screen
2. Select the user icon in the toolbar
3. The user selection screen appears for a quarter of a second before the splash screen appears and loads back into the app home screen

**Expected behavior**
The user selection toolbar button loads the user selection screen.

**System (please complete the following information):**
 - Android TV or Fire TV version: API 28 emulator, Android 10
 - Device manufacturer: Emulator, Google
 - Device model: Emulator, Chromecast with Google TV
 - Jellyfin server version: 10.7.6

**Additional context**
Reverting #1059 fixes the issue.

**Comment by nielsvanvelzen** [comment]
Thanks, didn't test the change enough :p
