### ISSUE TITLE
v12.0 Beta 3 does not load shield tv 

### ISSUE THREAD

**Issue by Dnkhatri** [jellyfin/jellyfin-androidtv#1077]
I installed v12.0 Beta 3 on my shield tv it does not go pass the loading screen. Is it working for anyone

**Comment by nielsvanvelzen** [comment]
We're aware of this issue and fixed it. A new beta version (https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.12.0-beta.4) is publishing right now and should be up on the Google Play Store later today.

**Comment by nielsvanvelzen** [comment]
Update is live now!
