### ISSUE TITLE
Jellyfin For AndroidTV is crashing when the video is paused for more than 8 to 10 mins

### ISSUE THREAD

**Issue by novojitdas** [jellyfin/jellyfin-androidtv#1090]
**Checks**
issue does not happen in the browser, checked

**Logs**
https://pastebin.com/iD0G32Mi

**FFmpeg Logs**
https://pastebin.com/zDstYPqB
System:
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: Xiaomi
 - Device model: Mi BOX S
 - Jellyfin server version: 10.6.4

**Comment by nielsvanvelzen** [comment]
We do not support server version 10.6.4. Also there already are issues for this problem.
