### ISSUE TITLE
Live TV Guide should default to sort by channel number

### ISSUE THREAD

**Issue by eqpaisley** [jellyfin/jellyfin-androidtv#1116]
**Describe the bug**
Live TV Guide appears to default to "sort by last played" and "keep favorites on top"  this results in a wild mishmash of channels rather than the traditional setup of a guide listing channels in order by channel number.

**To Reproduce**
Check the live tv guide.

**Expected behavior**
App should default to the traditional view of channels in order by number.  While it's possible to select for this, it shouldn't take a series of settings changes to get to the most used and most expected view of the guide.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Android TV
 - Device manufacturer: Nvidia
 - Device model: Shield TV Pro
 - Jellyfin server version: 10.7.6

**Additional context**

**Comment by UserModel** [comment]
Is this a valid bug? If so, I'd like to work on it.
