### ISSUE TITLE
Support for Android 7, please

### ISSUE THREAD

**Issue by mailbyms** [jellyfin/jellyfin-androidtv#1117]
**Describe the feature you'd like**	
Need support on Android 7

**Additional context**	
0.11.5 can install on my Sony x8000C, which runs Android 7  
but failed to install new version begin from 0.12.x  

Please tell me how to get a latest version for android 7, thanks.

**Comment by nielsvanvelzen** [comment]
The app supports API 21 (Android 5.0) and newer. Use our troubleshooting channels if you have issues installing or using the app.

**Comment by hwadong860** [comment]
same problem
