### ISSUE TITLE
Fail to install on Sony KD-55X8000C , which runs Android 7

### ISSUE THREAD

**Issue by mailbyms** [jellyfin/jellyfin-androidtv#1118]
**Describe the bug**
Installer crashes right after clicking on 0.12.0-beta.5 apk

**To Reproduce**

1. Go to file manager'
2. Click on 'jellyfin-androidtv-v0.12.0-beta.5-release.apk'
3. Installer crashes

**Expected behavior**
v0.11.5 is OK, v0.12.0 (beta 1~ beta5) is NOT OK

**Logs**
Don't know how to achieve install log, any ideas?

**Screenshots**

**System (please complete the following information):**
 - Android 7
 - Sony
 -  KD-55X8000C

**Comment by mailbyms** [comment]
Does it need google play?
This model of SONY TV may not have google related services.
And I'm in China.

**Comment by nielsvanvelzen** [comment]
If the installer crashes that's a fault of your OS. Provide logs so we can fix a potential issue or use our support channels.

Closing as duplicate #1117.

**Comment by mailbyms** [comment]
> If the installer crashes that's a fault of your OS. Provide logs so we can fix a potential issue or use our support channels.
> 
> Closing as duplicate #1117.

How to use " support channels " ? @nielsvanvelzen
