### ISSUE TITLE
Transcoding not working

### ISSUE THREAD

**Issue by kinv** [jellyfin/jellyfin-androidtv#112]
Hi,
 
using the amazon android tv apk via https://repo.jellyfin.org/releases/client/androidtv/.

Transcoding is not enforced on this player. Setting trainscode max bitrate has no effect, even if setting globally for user.
This works on android mobile apk and web however not android tv.

also there is no playback correction. I have the setting to down mix to stereo however the file just direct plays with no sound. Transcoding isn't kicked off to transcode audio.

created new issue as advised, link to this issue https://github.com/jellyfin/jellyfin-androidtv/issues/43

Thanks.

**Comment by ddurdle** [comment]
https://github.com/jellyfin/jellyfin-androidtv/issues/43

**Comment by wuast94** [comment]
Have this issue too and there seems no update on this? Can't watch content that needs to be transcoded
