### ISSUE TITLE
Ignore SSL trust errors

### ISSUE THREAD

**Issue by SamuelBartik** [jellyfin/jellyfin-androidtv#1127]
**Describe the feature you'd like**	
Hello, I am running Jellyfin on HTTPS via cert signed by my own CA.

It is virtually impossible to add my CA cert to AndroidTV OS trust store.

It would be awesome to ignore SSL trust errors and let me add jellyfin with self signed cert to the app. Even better would be to recognise untrusted certificates and offer user to save it in jellyfin client app as trusted certificate for next connections.

**Comment by nielsvanvelzen** [comment]
There are no plans to allow such a feature at this moment. You can get free certificates from services like Let's Encrypt without any trouble so using self-signed certificates shouldn't be necessary.

**Comment by SamuelBartik** [comment]
@nielsvanvelzen Unfortunately I can't get certificates for non-public IP ranges. 😐 I had all my services put behind a reverse proxy with SSL enabled because of my reasons that are not relevant here. Eventually I gave up and put standalone jellyfin on HTTP proxy.
