### ISSUE TITLE
Resume from doesn't work

### ISSUE THREAD

**Issue by okan35** [jellyfin/jellyfin-androidtv#1128]
**Describe the bug**

Resume from doesn't start from the timestamp it shows on automatically chosen player.

**To Reproduce**
Choose preferred player "automatically choose"
Watch a show and it won't start from stated time.
**Expected behavior**
It should start from the minute it shows
**Logs**

**Screenshots**

**System (please complete the following information):**
 - 
Jellyfin is latest beta version on Android tv and latest server version on stable , xiaomi mi box 

**Additional context**

**Comment by mueslimak3r** [comment]
Can you provide some examples of the time it should have resumed from, and the time it actually resumed from?

**Comment by okan35** [comment]
I dont have jellyfin currently installed but at the time of using it, if you followed the steps I wrote you would have got the result I got which was wrong start of media. Have you tried this yourself ?
