### ISSUE TITLE
Playback stuttering with any movie files

### ISSUE THREAD

**Issue by huudafakk** [jellyfin/jellyfin-androidtv#113]
Setup: jellyfin-androidtv_google_beta5.apk on the Sony KD-55xf9005

Almost on every movie-file I play with the default player there is a light continue stuttering/no smooth playback. Using an external player (mx player, vlc) I don't face the problem and all movies run smoothly and without problems. It happens with avi, mkv files, 720p and also 1080p.
is this a known issue?

**Comment by choakem** [comment]
I'm not experiencing this issue...
Ubuntu Docker Server - AndroidTV plays great!

**Comment by thornbill** [comment]
If you check the server dashboard is the media being transcoded?

**Comment by huudafakk** [comment]
the H.264 transcoding is set as auto, using the Version: 10.3.6.

**Comment by thornbill** [comment]
Okay. When you are playing media the admin dashboard will show if it is transcoding. I am curious if it is transcoding when you experience the stuttering. I have not noticed this but the majority of my media direct plays.

**Comment by huudafakk** [comment]
yes, media is transcoded as I can see from the logfile. Strange thing about that using MX Player or VLC (setting "use external player" on "ON") it works like charm without any problems even its transcoded too.
Could it be the audio codec which creates problems?

**Comment by huudafakk** [comment]
turning off all the transcoding options in the user/playback settings solves the issue, now runs smooth as it should be. Thanks for the input for the "direct play", it took me on the right way.

**Comment by thornbill** [comment]
I’m glad you were able to work out something that works for you. I still think this is a bug though since the app _should_ be able to playback transcoded streams without stuttering. I’m going to reopen this so we can track it.

**Comment by nielsvanvelzen** [comment]
Might be related to #238 and possibly fixed in #244

**Comment by Florianisme** [comment]
Yep, this is exactly my TV! :D
It's fixed for me now so yes, should be fixed

**Comment by huudafakk** [comment]
Nice, I'll try to create an APK out of the branch as requested in https://github.com/jellyfin/jellyfin-androidtv/issues/238 and lets see how it works :-) 
Even with transoding enabled the picture is flawless and smooth?

**Comment by Florianisme** [comment]
I prevented my user from transcoding videos so it was using direct play all the time. Even then, the video was stuttering like you explained before. But after the PR by Niels, the issue was gone.

**Comment by huudafakk** [comment]
I tried to build the APK from latest branch and sideloaded it to the TV. It starts correctly but playing a video file is worse than before (stuttering all the time), maybe something went wrong building the APK. I'll wait for the next release, it will not take long I think.

**Comment by nielsvanvelzen** [comment]
Hi there! We've recently released a new version of Jellyfin and we think this issue is solved. Can you try it with the new version?

**Comment by huudafakk** [comment]
with upgraded exo player the files play smooth and without major problems, we can close this issue.
