### ISSUE TITLE
"Show next video info during playback" setting does not apply

### ISSUE THREAD

**Issue by LucasCrowe** [jellyfin/jellyfin-androidtv#1130]
**Describe the bug**
When unchecked, the "Show next video info during playback" option for user playback does not apply during Android TV playback. This is particularly disruptive when the individual episodes do not have credits. SpongeBob is a good example.

**To Reproduce**
1. Navigate to user playback settings in the admin web console.
2. Set "Show next video info during playback" to be unchecked.
3. Play a video on the Android TV client.
4. During the last portion of the video, the next video's info will show.

**Expected behavior**
I expected the video info to not appear on Android TV after setting the users setting in the admin console.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: Sony
 - Device model: Z9F
 - Jellyfin server version: 10.7.6

**Additional context**

**Comment by nielsvanvelzen** [comment]
The settings for the web client are (mostly) independent from the android tv app. This particular setting is not used in the app so this is not a bug.
