### ISSUE TITLE
No Audio on Fire TV

### ISSUE THREAD

**Issue by uchagani** [jellyfin/jellyfin-androidtv#114]
I'm not getting any audio on my Fire TV.  Using version 1.1.90a on a Fire TV.  The Jellyfin server is telling me that it is Direct Playing.  The stats for the movie are (I got the stats by playing in the browser hence the Html Video player): 

```
Playback Info
Player: Html Video Player
Play method: DirectStream
Protocol: http
Stream type:HLS

Video Info
Player dimensions:1440x728
Video resolution:1920x800

Direct Stream Info
Video codec:H264 (direct)
Audio codec:MP3

Original Media Info
Container:mkv
Bitrate:11.4 Mbps
Video codec:H264 High
Video bitrate:9.9 Mbps
Audio codec:DTS DTS
Audio bitrate:1.5 Mbps
Audio channels:6
Audio sample rate:48000 Hz
```

I can hear audio just fine on other machines just not through fire tv.

**Comment by ddurdle** [comment]
duplicate https://github.com/jellyfin/jellyfin-androidtv/issues/43
