### ISSUE TITLE
Unable to connect to the jellyfin server

### ISSUE THREAD

**Issue by CoderMaurice** [jellyfin/jellyfin-androidtv#1148]
jellyfin moblile app and web is all ok  
but failed on TV

i tryed 
192.168.50.11
192.168.50.11:8096  (worked with web
192.168.50.11:8096/jellyfin (worked with mobile app

**Comment by nielsvanvelzen** [comment]
Hi, I noticed this issue does not use one of our issue templates. We provide these templates to get the information necessary in order to help. I will close this issue but I encourage you to recreate it using the template so we can help.

**Comment by CoderMaurice** [comment]
thanks , I solved this problem by upgrade jellyfin version from 10.5.5 to 10.7.7
