### ISSUE TITLE
UI Styling same as Web Interface & Android Mobile App

### ISSUE THREAD

**Issue by Thursty24** [jellyfin/jellyfin-androidtv#1151]
Hi Guys

Another suggestion:

UI styling as the Web Interface and Android App shows.

**Comment by nielsvanvelzen** [comment]
No.

There are no plans to do this.

**Comment by pikesthefish** [comment]
Hello 👋 

Is it due to the way Jellyfin on ATV is built? Would porting the Android (non-tv) version be possible?
