### ISSUE TITLE
Jellyfin crashes everytime you back out from a playing movie

### ISSUE THREAD

**Issue by junkmasters21** [jellyfin/jellyfin-androidtv#1152]
As the subject says, every time I press on the back/return button on the remote control from a playing movie, the application crashes and exits out to the home screen. You have to run Jellyfin again to play another movie. This cycle continues if you want to switch to another movie regardless where the movie is played from any library you added.

Android TV 10.1 (kernel 4.4.55)
Jellyfin 0.11.5

[https://ibb.co/gm0C3yc](url)

**Comment by nielsvanvelzen** [comment]
Use the template. We're missing a bunch of information now:

- **Logs**
- Device manufacturer: [e.g. Amazon, Nvidia, Sony]
- Device model: [e.g. Fire TV Stick (2nd Gen) or Shield TV]
 - Jellyfin server version: [e.g. 10.5.4]

**Comment by junkmasters21** [comment]
- not sure how to pull out the logs from the tv box but the prompt says that the crash report has been sent to tracepot.com
- Device manufacturer: not known
- Device model: MXQ Pro 4K TV Box (Android 10.1 kernel 4.4.55)
- Jellyfin server version 10.7.7

Sorry but this is as much information as I can provide

Thanks!

**Comment by sambartik** [comment]
I have experienced so much crashes lately after testing an issue which is tracked here on GitHub: #1160. Essentially the whole app crashes if you back out of playback while the video is stuttering.

**Comment by junkmasters21** [comment]
> I have experienced so much crashes lately after testing an issue which is tracked here on GitHub: #1160. Essentially the whole app crashes if you back out of playback while the video is stuttering. Can't say I can replicate that every time, though.

well playback for me is smooth and without stuttering. It's just that when you want to exit out from a playback it crashes. You can't switch movies. I hope it gets fixed. I can't afford to pay for other players.

**Comment by sambartik** [comment]
> > I have experienced so much crashes lately after testing an issue which is tracked here on GitHub: #1160. Essentially the whole app crashes if you back out of playback while the video is stuttering. Can't say I can replicate that every time, though.
> 
> 
> 
> well playback for me is smooth and without stuttering. It's just that when you want to exit out from a playback it crashes. You can't switch movies. I hope it gets fixed. I can't afford to pay for other players.

Does it crash for you if you pause playback beforehand?
