### ISSUE TITLE
forward or backward 

### ISSUE THREAD

**Issue by baburam0007** [jellyfin/jellyfin-androidtv#1154]
**Describe the feature you'd like**	
Display the time or progress on the seek bar while pressing the forward or backward button.

**Additional context**

**Comment by Devansh-gaur-1611** [comment]
Can I work on it .Can u assign me this issue plz

**Comment by nielsvanvelzen** [comment]
You can just work on this issue and open a pull request, no need to assign you to the issue for that.

**Comment by ManuLinares** [comment]
> Can I work on it .Can u assign me this issue plz

Did you work on this?

**Comment by ManuLinares** [comment]
This has been fixed on [latest commit](https://github.com/jellyfin/jellyfin-androidtv/commit/8001196183f769699b0c36f5025f3f02320ac71d)

**Comment by nielsvanvelzen** [comment]
This should be fixed now, let us know if the issue still persists in the latest version (0.14).
