### ISSUE TITLE
Username is case-sensitive

### ISSUE THREAD

**Issue by MayeulC** [jellyfin/jellyfin-androidtv#1156]
**Describe the bug**
Only lowercase usernames worked for me while logging in.

**To Reproduce**
1. add a user
2. Fill the user as "Joe" instead of "joe"
3. Type in password and login
4. Invalid username or password

**Expected behavior**
Username should be case-insensitive, "Joe" should work as well as "joe". This is the case on jellyfin-web.

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: nvidia
 - Device model: Shield P2897
 - Jellyfin server version: 10.7.7

**Additional context**
These are LDAP users, but a corresponding user exists in Jellyfin CP.

**Comment by nielsvanvelzen** [comment]
I don't see the issue here. We send the username you enter to the server and the server tells us if you're logged in or not.
The client doesn't change the capitalization or anything. This is true for both jellyfin-web and jellyfin-androidtv.

**Comment by MayeulC** [comment]
I just confirmed again that *this is also an issue* on jellyfin-web, sorry for the false report.
