### ISSUE TITLE
Can't connect to server anymore 0.12.0 release

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin-androidtv#1158]
**Describe the bug**
Hey guys good job. You done the same thing as the android developers. I downloaded the 0.12.0 release version for my chromecast with Google TV and can now also can't connect to my server anymore :(

These is the depending issue on the android version. 
https://github.com/jellyfin/jellyfin-android/issues/533

In short, I have a jellyfin instance behind a cloudflare reverse proxy with nginx bevor my server and I can connect to the server with my browser.

**Comment by Xyz00777** [comment]
*bevor somebody is asking, yes the 0.11.5 version is working fine. And sorry im a little bit annoyed of these bug because I hoped I can finally get a new version and have less bugs....
(beside of that great work guys! I love your app :), beside of that bug :D )

**Comment by nielsvanvelzen** [comment]
Good job filling in the bug template. Without logs we can't help.

**Comment by Xyz00777** [comment]
Hi, i dont know what the bug layout should bring because its an device undepending bug, yes i forgot to add a picture with the error, comes in the next moments. I cant provide Logs becuase the app cant connect/find the server and because of that the server cant log anything, yes i tried it out. Can you say me where i can find the log of the debugging verison of the application? than i could provide these log as far as i can reach the logs without root permissions on the chromecast.

**Comment by Xyz00777** [comment]
![IMG_20210930_094249__01.jpg](https://user-images.githubusercontent.com/52142054/135409421-06064db0-729d-49a5-b317-1b524c89d78c.jpg)

**Comment by nielsvanvelzen** [comment]
The screenshot says it all - the address you provides is invalid because the app can't connect to it. This can be caused by a lot of things; misspelled names, missing port mappings, firewalls, invalid ssl certificates etc. etc.

**Comment by Xyz00777** [comment]
Sorry but no, all is set up more or less correct. With exactly these url I can connect to my server over the browser on any device, I can connect to my server with these URL in the android TV app in version 0.11.5, I can connect to the server with these URL with the android app in version 2.2.3 (not newer it also got the new lib), because you updated/changed the connection lib (when i know it correct) and the old lib was fully compatible with the setup.
Im using jellyfin with default port (8920) on a Ubuntu server. Bevor these server is an pfsense firewall with nginx who only allow incoming traffic on port 443 (like in my URL above). Nginx is set up with an reverse proxy to cloudflare who manages my url subdomains so I can map all my sites to port 443 because I don't want to think about what port I have to use to can connect to my servers...
I think the problem is that the new lib only wants and allow to connect to the server with port 8920 or 8096 (default ports) or something like that. Because even when I type in the complete url AND ":443" it says it can't connect (on the browser these is working wonderful and with the old app version too).
OH and I would like to apologize by the way if the other messages and these sound bold/aggressive or something like that, I'm just a little bit badly annoyed by this bug :(
Hope you guys can help me

**Comment by nielsvanvelzen** [comment]
Can you share the response you get when you open `https://[yourserver]/system/info/public` in the browser?

**Comment by Xyz00777** [comment]
I dont Know what these bringt you but okay here for you 🤷‍♂️:
{"ServerName":"media","Version":"10.6.4","ProductName":"Jellyfin Server","OperatingSystem":"Linux","Id":"5fda1a1e51fb49b785599ad6c58c23e8"}

That's all

**Comment by nielsvanvelzen** [comment]
You're running 10.6.4, both Android apps only support 10.7 or newer.

**Comment by Xyz00777** [comment]
Woooooow I had an outdated apt key 🙈 thanks very much for your help.... That was a stupid big on my side... Updated and now it's working... But now I can't login with my admin user anymore 🙃🙃 other problem...

**Comment by nielsvanvelzen** [comment]
Does this also fix https://github.com/jellyfin/jellyfin-android/issues/533 for you?
