### ISSUE TITLE
Next Up button missing in new update

### ISSUE THREAD

**Issue by nikhil96widhani** [jellyfin/jellyfin-androidtv#1163]
**Describe the bug**
Our beloved "Next Up" button which allowed us to play next episode when episode was >1 minute close to end is no more with us in the new update. I hope this was non intentional and will be added back. I see a play next button after episode ends but that is not helpful as the previous one was. 

**To Reproduce**

1. Go to 'episode you want to play and slip to end 3 minutes'
3. Wait
4. See error : No play next button while episode is going to end. Instead a new button comes when episode has ended.

**Expected behavior**
I loved the ability to skip end part of the episode with the previous version and it has been removed in this version.

**System (please complete the following information):**
 - Android TV or Fire TV version: [e.g. Android 9]
 - Device manufacturer: [e.g. Hisense]
 - Device model: [e.g. inbuilt android tv]
 - Jellyfin server version: [e.g. 10.7.7]

**Comment by nielsvanvelzen** [comment]
This is not a bug. Closing as duplicate of #357.
