### ISSUE TITLE
The play bar does not mark the elapsed minutes.

### ISSUE THREAD

**Issue by JulioNahum** [jellyfin/jellyfin-androidtv#1170]
**Describe the bug**
The play bar does not mark the minutes elapsed when watching a series or movie.

**Screenshots**
![5100683460170852786_121](https://user-images.githubusercontent.com/30002132/135731171-23d7c639-0ae9-45c2-9b01-3849ce9dcd9e.jpg)

**System:**
 - Android TV [Android TV 10 Q]
 - App version: [Jellyfin for Android TV 0.12.0]
 - Device manufacturer: [Google]
 - Device model: [Google Chromecast with Google TV]
 - Jellyfin server version: [10.7.7]

**Comment by thornbill** [comment]
You are 13 seconds into a show… this seems pretty accurate. 

![A10B010A-494B-491D-8736-657967804FCA](https://user-images.githubusercontent.com/3450688/135732421-8764f0ec-a158-4f32-b713-14d931c193f6.jpeg)

**Comment by JulioNahum** [comment]
No. I'm looking for more than 1/2 hour and it was still in the 13 second. I invite you to take the test.
