### ISSUE TITLE
Exoplayer: cannot change audio or subtitle tracks

### ISSUE THREAD

**Issue by Rihan9** [jellyfin/jellyfin-androidtv#1175]
### Describe the bug

Hi,
 I cannot able to change audio or subtitles tracks using exoplayer.

I can't use libVLC or external player because the are other issues so currently I don't have any workaround.

I:
- play the tracks
- go to aproximately 2:30 minute
- change subtitles track and wait for reload
- change audio track and wait for reload

the voice on the menus are updated but don' t match the one being played.
Subtitles codec: HDMV PGS
Audio codec: EAC3

### Logs

```shell
1 minute log is 5000+ row and over 545K so I can't use pastebin either. Please, if you need the log, suggest me a way to send it.
```

### Application version

0.12.0

### Where did you install the app from?

Google Play

### Device information

Philips 7500 series

### Android version

Android 9

### Jellyfin server version

10.7.7

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [X] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by Rihan9** [comment]
@Maxr1998 I'm sorry for the mistake and thank you!

**Comment by alexdelprete** [comment]
I have the same problem on NVIDIA SHield Pro. Can't select audio track nor subtitles, it doesn't even update the UI: when I select the track the select window disappears, but when I reopen it the original track played is still checked.

**Comment by mueslimak3r** [comment]
can someone with this issue report whether it is fixed in 0.13?

**Comment by Rihan9** [comment]
Hi @mueslimak3r,
in 0.13 the selector for subtitles and audio track works. But the subtitles don't load (format: "subt" or "pdpg")

**Comment by Rihan9** [comment]
@alexdelprete , @mueslimak3r if you agree, I'm going to close this issue and open a some new, 1 for every point:
- Exoplayer: audio and video desync
- Exoplayer: cannot load subtitles

**Comment by mueslimak3r** [comment]
For logging, `adb logcat` supports filtering by application so you can capture logs just for jellyfin. I assume the majority or the lines in the log you recorded are from other applications or system services. 

> * Exoplayer: audio and video desync

Yes, open a new issue for this

> * Exoplayer: cannot load subtitles

I think subtitles not loading would be a duplicate of #145
