### ISSUE TITLE
Show HDR and bit depth identifiers on info page for show/movie

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-androidtv#1177]
**Describe the feature you'd like**	
Show icon for HDR and bit depth just below the title. Currently, this area only shows resolution, CC availability, audio codecs.

**Comment by j-insan3** [comment]
I noticed this still isn't the case in the latest version. I would be really nice to see some more metadata like HDR (DV/HDR10), resolution, audio track including atmos/dts-x information.

**Comment by sudiptosarkar** [comment]
I'm facing the same issue. Adding this comment so that this issue doesn't get marked as stale.

**Comment by nielsvanvelzen** [comment]
Should be fixed by #2893
