### ISSUE TITLE
play or resume button not the default selection when arriving at a media view

### ISSUE THREAD

**Issue by kinghat** [jellyfin/jellyfin-androidtv#1179]
### Describe the bug

1. enter into a media view like a movie
2. main text is selected

imo it should be the play/resume button that is the default selection. this looks like it has been fixed once here https://github.com/jellyfin/jellyfin-androidtv/issues/126. this could also be related https://github.com/jellyfin/jellyfin-androidtv/issues/1101.

### Application version

0.12.0

### Where did you install the app from?

Google Play

### Device information

Google Chromecast with ATV

### Android version

Android 10

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Do you still have this issue using the latest version from google play?

**Comment by kinghat** [comment]
> Do you still have this issue using the latest version from google play?

looks fixed to me. i will reopen if that changes.
