### ISSUE TITLE
Use left/right buttons to seek backward/forward

### ISSUE THREAD

**Issue by xtrandom** [jellyfin/jellyfin-androidtv#1185]
### Describe the feature you'd like

- When media is playing without any controls/menu on the screen, pressing left/right should seek backward/forward respectively
- When controls/menu is up and the focus is on the scrubber, then pressing left/right should seek backward/forward respectively. I don't think we can currently skip backward/forward when media is paused, so this would apply when media is playing and focus is on the scrubber.

Note: This is for FireTv remote. It has actual buttons to skip backward/forward. I'm referring to left/right buttons next to the middle/main button.

**Comment by aramazhari** [comment]
> I agree. Drives me crazy that Netflix, Disney, Prime all use the same keys but Jellyfin uses something else

Sorry to ask, if not the dpad buttons then how do we currently seek on fire TV stick?

**Comment by xtrandom** [comment]
> Sorry to ask, if not the dpad buttons then how do we currently seek on fire TV stick?

Using 'Fast Forward' and 'Rewind' buttons. Desired behavior would be to also be able to do it using left/right 'Directional Navigation' buttons (which most/all streaming services use)

![image](https://user-images.githubusercontent.com/68791912/141791667-882a777f-27d6-4b12-8b66-aa0b255823f7.png)

**Comment by aramazhari** [comment]
Thanks! I never thought to try those!

I see that for firetv the dpad peft and right are disabled so i was just wondering directional navigation are that

https://github.com/jellyfin/jellyfin-androidtv/pull/478/files

**Comment by ManuLinares** [comment]
This should be closed.

**Comment by nielsvanvelzen** [comment]
This should be fixed now, let us know if the issue still persists in the latest version (0.14).
