### ISSUE TITLE
Play with external player after automatically chosen players fail to play content

### ISSUE THREAD

**Issue by okan35** [jellyfin/jellyfin-androidtv#1187]
So I have a show that automatically chosen player option fails to play and a toast comes after failure which says "Too many errors giving up".

Instead of this I believe app should try to play with external players. So user doesn't have to go to options and change default player to external app. When user clicks play button, it should just play.

**Comment by hrvylein** [comment]
@nielsvanvelzen i really think this is a bug as i am encountering the same problem. current version is unusable for me.

**Comment by okan35** [comment]
For now I come over playback problems by playing with VLC by default Of course this is in my own fork. Currently have no problems regarding subtitle or playback this way.
