### ISSUE TITLE
090 amazon - Firestick - "The package appears to be corrupt"

### ISSUE THREAD

**Issue by bartekd123** [jellyfin/jellyfin-androidtv#119]
When I try to install the newest version (jellyfin-androidtv_amazon_0.9.0) of the compiled androidtv amazon version, it doesn't install. Shows the error "app not installed" "The package appears to be corrupt". Are others getting the same issue?

I am using the firestick 4k if that makes any difference.

**Comment by groenator** [comment]
I get this issue on Shield as well.

**Comment by anthonylavado** [comment]
@bartekd123 What method are you using to install it?

**Comment by anthonylavado** [comment]
@groenator Be sure you’re using the regular Google version, not the Amazon version.

**Comment by thornbill** [comment]
If you previously had Jellyfin installed, you may need to uninstall the old version first since we reset the version number to a lower version.

**Comment by bartekd123** [comment]
@anthonylavado I am using downloader to download the apk which allows me to install it as well. I can try uninstalling the old version if you think that will work.

**Comment by groenator** [comment]
I'm pretty sure thats the Google version. Method to install, download the
apk, move it to AndroidTV and then install it.

**Comment by bartekd123** [comment]
@groenator I am using downloader on my fire stick as that is the easiest way to load apk’s. I am using the amazon version. It just downloads it locally (like you mentioned move it to androidtv)

**Comment by bartekd123** [comment]
Thanks @thornbill. After removing the old version, it allowed me to install 0.90. You can mark this as closed. 
@Groenator I would try removing the old version and see if that works for you too

**Comment by groenator** [comment]
Good idea, I will do that.

**Comment by thornbill** [comment]
@groenator did uninstalling the app and reinstalling work for you?

**Comment by groenator** [comment]
Everything works well, I did what you said and it worked. Thanks!

You can close the issue.

**Comment by thornbill** [comment]
Closing since this was due to the version number reset.
