### ISSUE TITLE
Aspect ratio feature/button missing from v0.12.x

### ISSUE THREAD

**Issue by xtrandom** [jellyfin/jellyfin-androidtv#1190]
### Describe the bug

1. Play media
2. Bring up the controls/menu
3. There's no option to change the aspect ratio

Instead, I expected the button to change the aspect ratio

### Logs

```shell
Just wondering why the button to change aspect ratio was removed from 0.12.x? Using the 'Vertical stretch' option was really useful to view content in full screen.

Are there any plans to add it back? Also, if there's an option to always set aspect ratio to desired one, that'll be useful.

Thank you
```

### Application version

0.12.x

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Tv Stick

### Android version

Latest

### Jellyfin server version

10.7.1

**Comment by nielsvanvelzen** [comment]
This option is only available when using ExoPlayer. It is not currently implemented for the LibVLC backend. This behavior is the same as 0,11
