### ISSUE TITLE
Fire TV: login not working anymore

### ISSUE THREAD

**Issue by TheHellSite** [jellyfin/jellyfin-androidtv#1195]
### Describe the bug

Already stopped the app, cleared app data and cache.

Entering the server URL "https://jellyfin.mydomain.tld/" works fine. It also displays the available users. 

1. Select the User 
2. Login mask appears 
3. Type in password 
4. Press "OK" 
5. Nothing happens

The App doesn't freeze. It is still responsive. 

Jellyfin Server shows that the user is connected, also in the server logs. But I can't get past the Login screen. With none of the user accounts.

Other clients don't have an issue. (iOS, Android, Browser) 

### Application version

0.12.1

### Where did you install the app from?

Amazon Appstore

### Device information

Fire TV Stick 2nd Generation

### Android version

Fire OS 5.2.8.0

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Can you try re-adding your server without a slash at the end? So `https://jellyfin.mydomain.tld` instead of `https://jellyfin.mydomain.tld/`

**Comment by TheHellSite** [comment]
> Can you try re-adding your server without a slash at the end? So `https://jellyfin.mydomain.tld` instead of `https://jellyfin.mydomain.tld/`

This is the solution! Thank your very much.
