### ISSUE TITLE
Vlc player resume does not work

### ISSUE THREAD

**Issue by okan35** [jellyfin/jellyfin-androidtv#1208]
Reason is mpv and mx use "position" on activity result while vlc is using "extra_position". 

I made this work and have been using this on my fork, will make a pull request soon.

**Comment by luxzg** [comment]
Unsure how is this closed issue when it does not work. On my TV - Just Player will report back where the viewing was paused and report to server. If using VLC this does not happen.

Also, though this is probably separate issue, if "always ask" is set inside Jellyfin video player options, then playback is never remembered, even if we pick internal player.

@okan35 I know this is graveyard issue, but when you mentioned fork, did you mean VLC fork or Jellyfin fork? It would be most helpful for this issue to actually get resolved, as VLC is only player that plays all files I throw at it, even .ISO (DVD VIDEO_TS structure)

**Comment by hellez** [comment]
Can we reopen this bug? Since libvlc has been removed I have to use the external player. Some videos won‘t run smoothly (I have a Sony xh90 Android TV) and the missing resume feature is annoying.

**Comment by hellez** [comment]
Seems like it is implemented since https://github.com/jellyfin/jellyfin-androidtv/pull/1719, maybe it has not been moved to the new replay code @nielsvanvelzen?
