### ISSUE TITLE
Android TV app crash

### ISSUE THREAD

**Issue by baburam0007** [jellyfin/jellyfin-androidtv#1236]
### Describe the bug

Android TV app crashed. we need to clear the application cache and data to able to use it again.

### Application version

0.12.2

### Where did you install the app from?

Google Play

### Device information

Sony Android TV

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Without logs we can't reproduce this issue.
