### ISSUE TITLE
Select TV Series/Films by letter.

### ISSUE THREAD

**Issue by Akirainblack** [jellyfin/jellyfin-androidtv#1245]
### Describe the bug

1. Open TV Series or Films
2. Only a wall of Series/Films.

Previously (before the update to 12).
You could select by letter of the alphabet.
This is no longer available.

### Logs

```shell
N/A
```

### Application version

0.12.2

### Where did you install the app from?

Google Play

### Device information

Multiple different devices

### Android version

Multiple versions

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
There is a giant button called "By Letter" with an icon showing "abc". Press that to browse by letter, or in the item view when sorting by "Name" there is another "abc" icon to skip to a certain letter.

Closing as not-a-bug.

**Comment by Akirainblack** [comment]
Actually that wasn't working for me prior to 12.3 it just went to a blank screen. I was only offered 12.3 last night which appears to have resolved the issue. Also... terming it a "giant button" really isn't the case. A "small button in the middle of multiple other buttons" would be more appropriate.
