### ISSUE TITLE
[Bug] Not showing Latest TV Shows

### ISSUE THREAD

**Issue by emnaudin** [jellyfin/jellyfin-androidtv#125]
Using this on an Nvidia Shield, I've noticed that the home screen shows only Latest Movies and Next Up Shows Only, is there a way to show the Latest TV Shows or is it a bug?

Device: Nvidia Shield, jellyfin version 0.9

Thanks

**Comment by thornbill** [comment]
Thanks for the feedback! This is a known issue on Android TV. 

Closing as a duplicate of https://github.com/jellyfin/jellyfin-androidtv/issues/81
