### ISSUE TITLE
PGS subtitles not working when direct playing

### ISSUE THREAD

**Issue by afraazali** [jellyfin/jellyfin-androidtv#1254]
### Describe the bug

1. Play a file with pgs subtitles
2. Ensure the file is being direct played
3. Select a subtitle to display
4. Verify the subtitles do not display

This works fine when transcoding. Using a shield pro and using a user that has transcoding enabled, I'm able to see the subtitles. The reason for transcoding shown is incompatible subtitle codec. It's odd since exoplayer does have support for pgs (https://github.com/google/ExoPlayer/issues/3008).

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro

### Android version

Android

### Jellyfin server version

10.7.7

**Comment by tydog98** [comment]
Exoplayer is also not playing PGS subs for me too.

**Comment by Ky-0** [comment]
Yep same issue here (direct streaming). It also does not respect the forced/default flag and leaves them disabled, not a major issue in itself but annoying on the forced part as you tend to forget to enable these :)

**Comment by cirdanmiriel** [comment]
Same problem here, and also with SRT subtitles.
PGS: not loaded (and sometimes crashing the player
SRT: "loading subtitles..." for some times and then displays "subtitles can not be loaded"

Anyone here also has the problem with SRT too during direct play?

**Comment by reacocard** [comment]
i took a quick poke around and it looks like jellyfin-androidtv requests that PGS be burned in here: https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/util/profile/ExoPlayerProfile.kt#L225

I *think* if the method was changed from `ENCODE` to `EMBED` then it would try to direct-play it instead of transcode. I don't have enough experience with android stuff to easily test building the change myself unfortunately.

**Comment by mueslimak3r** [comment]
We currently don't use exoplayer to render subtitles. Currently with exoplayer, graphical subtitles need to be burned in via transcoding. Text based subtitles are displayed using our own handler. This may change in the future for formats like PGS though ASS/SSA subs will likely require burn in indefinitely unless exoplayer adds more comprehensive support or we find a way to incorporate libass into our handler

For libVLC we do use its internal renderer for some formats. LibVLC uses libass so it works quite well.
