### ISSUE TITLE
When Image Type is Thumbnail, shows poster whenever a thumbnail is missing rather than a backdrop.

### ISSUE THREAD

**Issue by lednerg** [jellyfin/jellyfin-androidtv#1259]
### Describe the bug

1) While browsing a movie or TV show library, open Display Preferences and set the Image Type to Thumbnail.
2) Whenever a thumbnail image is missing for a video, it will display the movie poster rather than a backdrop, resulting in a weirdly cropped and blurry image.

The Android and Web versions will display a backdrop image whenever a thumbnail is missing. This makes sense since they share the same 16:9 aspect ratio as a thumbnail. With Android TV, we end up with cropped posters as shown below.

Android TV:
![Jellyfin_AndroidTV](https://user-images.githubusercontent.com/42688498/142683993-5f833a0a-bace-451b-83b7-109b7bf5d752.png)

Web:
![Jellyfin_Desktop](https://user-images.githubusercontent.com/42688498/142684019-7da9e8cc-cb68-42e8-8022-5ccf35ada36e.png)

To be clear, all of the films shown here do not have thumbnail images, they only have posters and backdrops.

[I'm not sure if this is technically a "bug" or what. This is my first time posting on github, and I don't know how to change it to something else.]

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

NVidia Shield TV Pro

### Android version

SHIELD Android TV 8.2.3 (32.6.518.0)

### Jellyfin server version

10.7.7, 10.8.0

**Comment by HadesCN2025** [comment]
I too am having this same issue. When I look at the main home page where it shows all my recently added, Only 1 of my libraries shows in a portrait format, but the others show in a poster format. I have not been able to fix this

<img width="3047" height="1243" alt="Image" src="https://github.com/user-attachments/assets/c0c8f793-d609-44a1-9147-649c9a288589" />
