### ISSUE TITLE
After update 1.12.3, the playback has drastically worsened.

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-androidtv#1260]
Basically as the title says.
I'm using android tv and the player used to work normally.

But after updating, it can't resume where I left off. It says "Can't search" (at least, that's the best translation I can think of right now).

Anyway, when I start playing something, the app will suddenly freeze after around 30min of watching. No idea why. I have to reboot my TV to fix this.

And sometimes, when it doesn't freeze, it just randomly jumps back to the beginning of the video for no reason. 

And lastly, the subtitles used to load in very smoothly. No freezing of the movie I'm watching. The movie would just play normally and subtitles would appear as soon as it was done loading. It was great.
Now, after the update, the movie freezes for a couple of seconds while loading the subtitles, which is kind of annoying. Though it isn't as annoying as any of the other issues I mentioned.

I hope the devs will fix this soon, because it's really annoying to use the android tv app right now. 

Extra info: I use a Philip's Smart TV with Android 8.0.0 and an Android kernel with version 3.10.79. My Jellyfin server is version 10.7.7

**Comment by JVT038** [comment]
So in the log files, I see this a lot:
`[2021-11-19 21:18:34.051 +00:00] [WRN] [69] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "https://jellyfin.mydomain.com/Sessions/Playing/Progress" to "myipaddress" in 0:00:00.9589688 with Status Code 204`
What's 204? Perhaps this has something to do with it?

**Comment by nielsvanvelzen** [comment]
Are you using ExoPlayer, LibVLC or Auto as preferred video player?

**Comment by JVT038** [comment]
> Are you using ExoPlayer, LibVLC or Auto as preferred video player?

I'm using Auto

**Comment by mueslimak3r** [comment]
> > Are you using ExoPlayer, LibVLC or Auto as preferred video player?
> 
> I'm using Auto

Can you test using exoplayer and libVLC selected as preferred and see if one or both have these issues?

Another way to tell which one it's using when this issue happens is to look for the resize/zoom icon. It's only in exoplayer:

![20211119_230901.jpg](https://user-images.githubusercontent.com/28824542/142717979-e07f2b40-d59b-4ba3-a6e1-73d39ef0d716.jpg)

**Comment by JVT038** [comment]
The bugs appear in both Exoplayer and libvlc

**Comment by layanto** [comment]
Previously I was using the inbuilt player on Android TV. Because of issues with new Jellyfin player, now I use MX Player as external player. No issue with video playback, seek etc but I noticed that subtitle file (srt) not appearing in MX Player. Not sure why but this is working fine on my Android phone using MX Player as external player.

**Comment by mueslimak3r** [comment]
If someone experiencing this issue can collect app logs using `adb logcat` then I can try to troubleshoot it. you'll need to enable 'debug mode' in the app or sideload the debug apk
