### ISSUE TITLE
App crashes if you change the port on the server

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-androidtv#1269]
### Describe the bug

If you successfully connect the app to your JF server and then change the port your server listens on, the app will continue to try to use the old port and crash when it cannot connect.

When it fails to connect on the old port, it ought to go back to server selection like it does before it's ever made a successful connection.

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

?

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
We can't help with this issue without client logs. The app already checks the server connections and returns to the login screen when the connection fails.

**Comment by brianjmurrell** [comment]
> We can't help with this issue without client logs. The app already checks the server connections and returns to the login screen when the connection fails.

It's not doing that here.

How do I get client logs from a Chromecast with Google TV?

**Comment by nielsvanvelzen** [comment]
From the issue template:

> Please paste your client logs (logcat) here, NOT server logs (in most cases).
> Learn how to capture those logcats [here](https://wiki.lineageos.org/logcat.html).
> Make sure that they don't contain any sensitive information like server URL, auth tokens or passwords.

**Comment by brianjmurrell** [comment]
Not stale.  Still on my TODO list to get logs.  Only have one CCGTV device though so need to coordinate debugging with regular use.

**Comment by brianjmurrell** [comment]
Need to collect logs still.
