### ISSUE TITLE
Doesn't work with SSL

### ISSUE THREAD

**Issue by brianjmurrell** [jellyfin/jellyfin-androidtv#1270]
### Describe the bug

When I configure my JF server with an HTTPS port and certificate, the app fails to connect to the server.  It connects to the port, exchanges a few packets and then disconnects and reports that it cannot connect to the server.

If I disable HTTPS the app successfully connects to the JF server.

This means that if your JF server is set to HTTPS-only, the app doesn't work.  Even if you don't have HTTPS-only configured, the app will still fail to connect until you disable HTTPS and then connect the app to JF.  Once done, you can re-enable HTTPS but not HTTPS-only.

`http://<my-jf-server>/system/info/public`:
```
{
LocalAddress: "https://10.75.22.2:443",
ServerName: "pvr",
Version: "10.7.7",
ProductName: "Jellyfin Server",
OperatingSystem: "Linux",
Id: "9be14d61c64b452eb0fe38a39d2022a8",
StartupWizardCompleted: true
}
```

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

?

### Jellyfin server version

10.7.7

**Comment by brianjmurrell** [comment]
There is no reverse proxy.  The app is connecting to JF directly.  JF is in HTTPs mode on port 443 and providing the certificate directly.

Certificate chain works perfectly fine in a browser.

**Comment by nielsvanvelzen** [comment]
In that case we'll need client logs so we can see what goes wrong.

**Comment by brianjmurrell** [comment]
Not stale.  Still on my TODO list to get logs.  Only have one CCGTV device though so need to coordinate debugging with regular use.

**Comment by brianjmurrell** [comment]
Have a second CCGTV now but am not in a position to be able to test and get logs yet.  Hopefully soon.
