### ISSUE TITLE
0.12.3 crashes after a few minutes when playing some HD content

### ISSUE THREAD

**Issue by SimplifyAndAddCoffee** [jellyfin/jellyfin-androidtv#1281]
So far I've had it happen mostly with movies and TV episodes over 1.2 GB using the MP4 container at 1080p or higher.

The crashes happen intermittently after about 3-4 minutes of playback. This is a new issue as of a recent update, as these same files played fine previously.

**Comment by Sim0nW0lf** [comment]
I am having the same issue on my fire tv stick...
Fire OS v7.2.4.2  and jellyfin v0.12.3 client and jellyfin 10.7.7 Server.

**Comment by nielsvanvelzen** [comment]
Closing as the issue does not use our provided template and thus we lack information. It's also likely a duplicate of #1061.
