### ISSUE TITLE
Multiple version of the movies not appearing

### ISSUE THREAD

**Issue by swarupsengupta2007** [jellyfin/jellyfin-androidtv#1283]
### Describe the bug

I have two versions of a movie [4k and 1080p]. But only the 1080p is getting picked up by the FireStick 4k client. If I remove the 1080p version, the client picks the 4K one, but it doesn't allow me to switch/select between the two versions, if both are available, it just autoselects the 1080p.

### Application version

0.12.3

### Device information

Amazon Fire Stick

### Android version

Android OS 6.2.8.1

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Multiple versions are supported starting from 0.13 (unreleased). Changes were added in #1155.
