### ISSUE TITLE
Solved: App still don't remember login

### ISSUE THREAD

**Issue by jitheshkt** [jellyfin/jellyfin-androidtv#129]
I can see that this issue is reported earlier here #95 and fixed it at #97. But it is still not fixed I think. I tried the release 0.9.0 on fire TV and it is same. Asking for login again if I close the app. I also tried to clone the repo and build myself, it also has the same issue. Any clue?

**Comment by choakem** [comment]
Did you cluck settings and choose default login as current user??

**Comment by jitheshkt** [comment]
Got it. Sorry for the confusion. It is indeed fixed. I missed the settings.
