### ISSUE TITLE
ASS subtitle not display when directstream

### ISSUE THREAD

**Issue by smcdl** [jellyfin/jellyfin-androidtv#1292]
### Describe the bug

ASS subtitle not display when directstream no matter any media file.

### Logs

```shell
I do not prepare the log. Because I think it is a function defect. But emby android tv can do that.
```

### Application version

0.12.3

### Device information

Ugoos am6b plus

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by smcdl** [comment]
Also the movie can not resuming playback. It always play from the beginning when it use ASS subtitle.

**Comment by nielsvanvelzen** [comment]
Enable transcoding for ASS
