### ISSUE TITLE
Playback Problem

### ISSUE THREAD

**Issue by aztm22** [jellyfin/jellyfin-androidtv#130]
Android TV Box Shield TV
Jellyfin The Newest Version
Playback is bad, when using the player inside jellyfin videos at the start of videos for about 2 mins will freeze none stop then work fine for the rest of the video.

if i choose to use vlc it will work without freezing but when i press back it will just go to the next episode 

would like this to be fix the jellyfin player needs a lot of work

**Comment by fagervan** [comment]
> Android TV Box Shield TV
> Jellyfin The Newest Version
> Playback is bad, when using the player inside jellyfin videos at the start of videos for about 2 mins will freeze none stop then work fine for the rest of the video.
> 
> if i choose to use vlc it will work without freezing but when i press back it will just go to the next episode
> 
> would like this to be fix the jellyfin player needs a lot of work

are you playing an mkv file are subtitles inside? that will make the server have to transcode the video.

**Comment by anthonylavado** [comment]
@aztm22 Would you please let us know a little bit more about your issue?
What type of media file are you playing? Are there subtitles?

We know that there's progress we can make but it takes time and effort to do that.

**Comment by thornbill** [comment]
@aztm22 could you provide the information requested above by @anthonylavado?

We don't have enough information currently to try to replicate and fix this issue. If you are unable to provide additional information, we may need to close this issue.

**Comment by callingshotgun** [comment]
I'm encountering the same issue and can provide examples.
I have an 88 minute long MKV file, no subtitles.  I also have 2 androidTV devices in my house, and this issue occurs on both of them.
-Device #1: JBL Link Bar - Transcodes Audio (downmixes to stereo), does not transcode video.  Skipping occurs for first couple minutes, but most of movie is fine.
-Device #2: NVidia Shield Pro - No transcoding happens at all - When I go to web admin interface on my laptop and click admin -> dashboard, I see this device and the phrase "Direct Play".

In my setup, both devices are connected by gigabit ethernet to the device running the Jellyfin server.  I've also tried pausing about 2 seconds in for a few minutes to give some time to buffer (and saw the red line a little further than the blue line in the admin -> dashboard web view, which I assume means buffering happened?) but the odd playback behavior still occurred.

**Comment by nielsvanvelzen** [comment]
Can you try it with the current master branch? It might be fixed already

**Comment by callingshotgun** [comment]
Sure.  Is there a build server somewhere where I can grab a nightly APK? Or should I bulid it myself?

**Comment by nielsvanvelzen** [comment]
We don't provide automated builds at the moment, so you need to build it yourself.

**Comment by callingshotgun** [comment]
Not a problem.  Will try sometime over the next day or two (popular hardware, need to wait for window of opportunity :D )

**Comment by callingshotgun** [comment]
Built and tested, issue persists.  (I bumped the version number on my build to verify in-app I was looking at master)

Debug output doesn't show crashes or anything, but every time the movie hangs for a second, this line pops up in logcat (obv with different timestamps etc):

2020-01-23 21:08:08.860 15601-16011/org.jellyfin.androidtv.debug I/AudioTrack: calling pause

I filtered by "calling pause" and did a playthrough to confirm that the line shows up when & only when the movie hangs.

FWIW  on the device I'm using for testing (JBL link bar) I have "downmix to stereo" selected in client settings.  Interestingly, when I switch audio output from "downmix to stereo" to "direct", the stuttering issue disappears.  Alas, I can't leave it that way, because then I get no audio through my speakers :D

Hope this helps!

**Comment by nielsvanvelzen** [comment]
Can you make a new issue and include the mediainfo for the movie you are trying to watch together with system info (device, android version etc.)?

**Comment by callingshotgun** [comment]
Can do.  Is "mediainfo" the name for a specific format or blob of data that jellyfin will export?  Sorry, relatively unfamiliar with Jellyfin from the code side.

**Comment by nielsvanvelzen** [comment]
No it's not, with mediainfo we just mean the information like video/audio codes etc. You can view it with ffmpeg (command line) or in VLC.

**Comment by callingshotgun** [comment]
Done!

https://github.com/jellyfin/jellyfin-androidtv/issues/277
