### ISSUE TITLE
Opus Support Not Detected Properly

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin-androidtv#1300]
### Describe the bug

I just reinstalled Jellyfin 10.7.7 on Docker and it is not properly detecting the capabilities of the Amazon Firestick 4K. It reports that it needs to transcode the audio when it is Opus. That is incorrect. The Amazon Firestick 4K supports Opus up to 8 channels. It gets this error when the Exoplayer is used but not the LibVLC player.

https://developer.amazon.com/docs/fire-tv/device-specifications-fire-tv-streaming-media-player.html?v=ftvstick4k

Android by default does support Opus audio.

https://developer.android.com/guide/topics/media/media-formats

I should mention that it is also transcoding HEVC to H.264 which it shouldn't need to do either. Also the MKV container is supported as well, even though it is outputting a MP4 file instead.

### Application version

v0.12.3

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Firestick 4K

### Android version

Stock Firestick OS

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Please use the "Media playback bug report" issue template for playback issues.
