### ISSUE TITLE
AV1 not playing with libVLC player

### ISSUE THREAD

**Issue by Protektor-Desura** [jellyfin/jellyfin-androidtv#1301]
### Describe the bug

I also want to report that that when libLVC is used as the player it reports to Jellyfin that it can play AV1 video codec but all I get is a black screen like it can't actually play AV1 video. I hear the audio and see the subtitles but get a black/blank screen for video.

Is AV1 support not compiled in the libVLC player?

### Application version

v0.12.3

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Firestick 4K

### Android version

Stock Firestick OS

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Please use the "Media playback bug report" issue template for playback issues.
