### ISSUE TITLE
request: Home screen section customization

### ISSUE THREAD

**Issue by henriklb** [jellyfin/jellyfin-androidtv#1318]
### Describe the feature you'd like

Home screen customization. Like dividing the Home screen to different sections and reorder them as the user wish. Similar to how the web-based client works. Combo boxes selecting `Home screen section 1`, `Home screen section 2` etc.

**Comment by henriklb** [comment]
Never mind. I was dumb. Looks like the settings are global and therefore also changes in the android tv client. Closing.

**Comment by nielsvanvelzen** [comment]
It's a bit confusing because you couldn't change these sections from within the app. The next update adds options for that to make it easier.
