### ISSUE TITLE
App crashes after playback is paused and resumed

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [jellyfin/jellyfin-androidtv#1319]
### Describe the bug

1. Play something
2. Pause
3. Resume
4. Wait until it crashes (2-5mins)

Only happens when you pause. If you restart it and watch something without pausing it doesn't crash
Video player is set to ExoPlayer

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield

### Android version

Android 10

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Would you be willing to collect some logs using adb logcat?
I'm not sure if you can just turn on debug mode in the play store release and capture useful logs that way or if you have to sideload the debug apk from github.

Also, if you can clone the repo and build/install the latest version from this repo's main branch it would be useful to see if the crash still occurs. There's been some work on the playback code so that would tell us if this bug will still be present in the next release.

**Comment by Cookie-Monster-Coder** [comment]
Yeah, I'll try to do both of those this weekend or early next week and report back.

**Comment by waddoo123** [comment]
I am seeing some similar behavior when playing HEVC movies. Consistently I am able to play a movie, allow it to play for 5 minutes and then the stream will end abruptly. 

Jellyfin version 10.7.7, it is able to transcode correctly etc. it does not crash when using the web browser, and iOS app as data points. Using Linuxserver/Jellyfin as my docker container for Jellyfin. 

Looking through the logs I have, consistently I see the following: 
2022-01-07 17:41:05.003 -06:00] [INF] [27] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 5000000, RemoteIp: "192.168.1.1", IsInLocalNetwork: True
[2022-01-07 17:41:05.003 -06:00] [INF] [27] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/movies/MEDIA/MEDIA.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True


`[2022-01-07 18:53:21.280 -06:00] [INF] [21] Jellyfin.Api.Controllers.MediaInfoController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mov", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "main", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "120", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
[2022-01-07 18:53:21.281 -06:00] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "Adam". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[2022-01-07 18:53:21.281 -06:00] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/movies/MEDIA/MEDIA.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-01-07 18:53:21.281 -06:00] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 5000000, RemoteIp: "192.168.1.1", IsInLocalNetwork: True
[2022-01-07 18:53:21.281 -06:00] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/movies/MEDIA/MEDIA.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-01-07 18:53:21.281 -06:00] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: RemoteClientBitrateLimit: 5000000, RemoteIp: "192.168.1.1", IsInLocalNetwork: True
[2022-01-07 18:53:21.281 -06:00] [INF] [21] Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "Unknown Profile", Path: "/movies/MEDIA/MEDIA.mp4", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
[2022-01-07 18:53:36.275 -06:00] [INF] [102] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" closed
[2022-01-07 18:55:26.632 -06:00] [WRN] [66] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.1.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2022-01-07 18:55:26.645 -06:00] [INF] [66] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" closed
[2022-01-07 18:55:31.935 -06:00] [INF] [102] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "192.168.1.1" request
[2022-01-07 18:56:19.950 -06:00] [INF] [21] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
[2022-01-07 18:56:31.951 -06:00] [INF] [21] Emby.Server.Implementations.Session.SessionWebSocketListener: Lost 1 WebSockets.
[2022-01-07 19:01:00.351 -06:00] [INF] [76] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.12.3" playing "MEDIA". Stopped at "2241335" ms
[2022-01-07 19:03:54.177 -06:00] [INF] [36] Emby.Server.Implementations.IO.LibraryMonitor:  will be refreshed.
[2022-01-07 19:33:39.009 -06:00] [WRN] [88] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "192.168.1.1" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake." `
