### ISSUE TITLE
Pause state not reported when paused from remote control.

### ISSUE THREAD

**Issue by GiviMAD** [jellyfin/jellyfin-androidtv#1328]
### Describe the bug

When controlling the client remotely, I sent a pause command, the client pauses the playback correctly but the paused state is not reported and its session keeps saying it's playing.
When controlling remotely the web client everything works fine so I think the error is this client not reporting the state change to the server.
Hope I explained it correctly.

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

MiTV-MSSP2, Amazon Fire TV Stick 4K Max (from store)

### Android version

Android 9, Fire OS 7.2.5.5

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Possibly fixed by #1273.

**Comment by GiviMAD** [comment]
I have tested it and is fixed on the main branch. Thanks
