### ISSUE TITLE
Recommended/trailers/genre tabs missing

### ISSUE THREAD

**Issue by DemirG** [jellyfin/jellyfin-androidtv#1329]
So I have movies named "Filmer" in My media. Up until a week or two ago there used to be tabs for recommended (based on what I've watched recently), trailers, genre, etc. But now these tabs are missing. They are still there on web version and normal Android version, but gone from the AndroidTV. 

When I go into "Filmer" under My media I just get a long side scrolling list of all my media, and it says that it is "_Showing All Items from 'Filmer' sorted by Unknown_". 

[Screenshot](https://bayimg.com/2b380e298b90440dbf65655839f7fa4791c5e98a.jpg)

Is there some setting to change or have there been changes to the app? I've also noticed a lot of crashes when starting to play new media since this change appeared. 

Edit: I think the issue is with the "Smart screen" setting. It's off right now and I can't turn it on. I mark the checkbox, but nothing happens. If I leave the menu and go back it's will stay unmarked. The same with the vertical position.
https://github.com/jellyfin/jellyfin-androidtv/pull/824
https://github.com/jellyfin/jellyfin-androidtv/pull/1099

**Comment by DavidFair** [comment]
> Edit: I think the issue is with the "Smart screen" setting. It's off right now and I can't turn it on. I mark the checkbox, but nothing happens. If I leave the menu and go back it's will stay unmarked. The same with the vertical position.

So I've had a poke around, and these settings (Image size / smart screen ...etc.) are stored on the server as custom preferences and saved when the menu is closed. Whilst the menu is open they act as simply "dumb toggles" so I just wanted to double check some things:

- When you say you mark the tickbox, does that mean the box actually visibly toggles state in the menu?
- If you toggle the other settings do they save when you close / re-open the menu?

**Comment by DemirG** [comment]
> > Edit: I think the issue is with the "Smart screen" setting. It's off right now and I can't turn it on. I mark the checkbox, but nothing happens. If I leave the menu and go back it's will stay unmarked. The same with the vertical position.
> 
> So I've had a poke around, and these settings (Image size / smart screen ...etc.) are stored on the server as custom preferences and saved when the menu is closed. Whilst the menu is open they act as simply "dumb toggles" so I just wanted to double check some things:
> 
> * When you say you mark the tickbox, does that mean the box actually visibly toggles state in the menu?
> * If you toggle the other settings do they save when you close / re-open the menu?

Thank you for the answer. 

- The box was visibly toggled to the different state.
- The same was with the other options. None of them would save as intended even if they visibly were changed.

I don't have this issue anymore. Was on server firmware 10.7.6 (docker on Synology). So I updated to 10.7.7 but all my settings didn't stick as the settings were saved in docker and not outside. Now it work fine though. 

Issue can be closed if no one else has this issue.
