### ISSUE TITLE
photos activity crashes app when opening folder containing more than one photo

### ISSUE THREAD

**Issue by tauchvogel** [jellyfin/jellyfin-androidtv#1330]
### Describe the bug

I installed the Jellyfin App via Fire TV Stick Appstore. I connect to my local server.  Then I go to my Pictures. When I am open one picture, then it will streamed on the screen. 

But after I open a folder with two or more pictures, then the App crashes again and again. It put me to the FireTV Homescreen. 

My Movies do not crash the App. This seems to work.

Please help. 

### Media info of 
Jpg 

### Application version

0.12.3

### Device information

Amazon Fire TV Stick 4K

### Android version

Fire TV

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
I'm unable to reproduce this issue by recreating the situation you described with folders containing single images, and folders containing two or more.

Can you provide some more info about the photos you're viewing?
* the format of the photos (.jpg, .png, etc)
* the directory layout/hierarchy
* are there any non-photo files in those same folders?
* verify that the jellyfin server has the correct permissions to access the folders containing the photos
* can you access those photos using other jellyfin clients like the web interface?

Server logs, and client logs (if possible), would be helpful too

**Comment by tauchvogel** [comment]
**the format of the photos (.jpg, .png, etc):** .jpg and .png

**the directory layout/hierarchy:** main folders and subfolders

**are there any non-photo files in those same folders?:** yes, mgeg1, mpeg2 and mpeg3 files

**verify that the jellyfin server has the correct permissions to access the folders containing the photos:** Need help for this to verify! But I think it has permissions, because I can see the single pictures in the gallery with no problems.

**can you access those photos using other jellyfin clients like the web interface?** Yes, I can access via web browser or app.

**Here are some log files of my server at the time I wanted to open the picture directories in the app on FireTV Stick. Hope that helps:**
[ffmpeg_Log.txt](https://github.com/jellyfin/jellyfin-androidtv/files/7810175/ffmpeg_Log.txt)
[Log-01.txt](https://github.com/jellyfin/jellyfin-androidtv/files/7810180/Log-01.txt)

**Comment by LasseKrache** [comment]
Sorry to "jump in" here, but I found this page as I am looking for a solution for my problem:

Installed today a Jellyfin server via docker on my Synology NAS and everything works perfect - except the Fire TV Stick 4K: every time I am watching a movie via the stick, the docker container grabs more and more RAM until the app crashes. I don't encounter this issue with other clients (app for Windows, Android mobile, Mac) ...

**Comment by mueslimak3r** [comment]
> Sorry to "jump in" here, but I found this page as I am looking for a solution for my problem:
> 
> Installed today a Jellyfin server via docker on my Synology NAS and everything works perfect - except the Fire TV Stick 4K: every time I am watching a movie via the stick, the docker container grabs more and more RAM until the app crashes. I don't encounter this issue with other clients (app for Windows, Android mobile, Mac) ...

Please open a new issue for this so we can dedicate a discussion specifically to your issue.
https://github.com/jellyfin/jellyfin-androidtv/issues/new?assignees=&labels=bug%2Cplayback&template=bug-report-playback.yaml

**Comment by tauchvogel** [comment]
Any new information on this issue?

**Comment by mueslimak3r** [comment]
Can you collect some logs from the app using `adb logcat`?
You'll need to enable debug mode in the app or install the debug build from this repository (in the releases page)

Those logs do show an error server-side. However, the app crashing is still an issue even if the cause is server-side.

**Comment by tauchvogel** [comment]
> Can you collect some logs from the app using `adb logcat`? You'll need to enable debug mode in the app or install the debug build from this repository (in the releases page)
> 
> Those logs do show an error server-side. However, the app crashing is still an issue even if the cause is server-side.

Hi, I am not able to use ADB logical. I do not know how to do it with the FireTV Stick. Where can I find more information about it?
