### ISSUE TITLE
unable to select movie version, client always picking disc stub which it can't play

### ISSUE THREAD

**Issue by da-anda** [jellyfin/jellyfin-androidtv#1333]
### Describe the bug

Since the latest update, I am no longer able to play any of the movies that also have a stub/offline/disc version, since the UI will only ever show the "offline version" without any possibility to choose the version to play

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

9

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Duplicate of #1283
Fixed in #1155

**Comment by da-anda** [comment]
btw, not sure if the referenced PR also addresses this, but it would be nice if for movies that have a disc stub and a regular version, if the regular version would become the default and in the overviews the "offline version" overlay thingy would disappear as it's not offline only

**Comment by nielsvanvelzen** [comment]
Can you make a separate issue for that (possibly with screenshots)? I honestly have no idea how that part of the app works. I know there's resources for an "offline" overlay but never managed to get it to show.

**Comment by da-anda** [comment]
sure, will do. If you feel like testing it for yourself, all you need to do is to create an empty file like `Dune (2021).disc` in one of your movie sources and scan it - it'll show up as regular movie with the "offline" flag thingy.
