### ISSUE TITLE
Downmix to stereo not working

### ISSUE THREAD

**Issue by LauH1987** [jellyfin/jellyfin-androidtv#1338]
### Describe the bug

I am using a 'Chromecast with Google TV' connected to my projector. I have a set of stereo speakers connected. When watching some movies (especially action movies) it can be very hard to hear the dialogue while not blowing the speakers from gunshots etc.
I tried enabling "Downmix to Stereo", but it doesn't seem to work on most movies. It simply direct plays them anyways.
I think this mostly happens with 5.1 AAC format.

Here is a screenshot from the web interface when I was was playing a movie on my CCwGTV with 'Downmix to Stereo' enabled:
![Screenshot_20220108_090841](https://user-images.githubusercontent.com/22587888/148651878-accf69db-2a1f-4e36-9fbd-952edf052a54.png)

### Media info of the file

```shell
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Movie.1080p.WEBRip.x264.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    creation_time   : 2021-11-09T07:11:49.000000Z
    title           : Movie.1080p.WEBRip.x264
    encoder         : Lavf58.20.100
    comment         : Movie.1080p.WEBRip.x264
  Duration: 02:43:23.85, start: 0.000000, bitrate: 2727 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1920x800 [SAR 1:1 DAR 12:5], 2497 kb/s, 23.98 fps, 23.98 tbr, 11988 tbn, 47.95 tbc (default)
    Metadata:
      creation_time   : 2021-11-09T07:11:49.000000Z
      handler_name    : L-SMASH Video Media Handler
    Stream #0:1(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, 5.1, fltp, 224 kb/s (default)
    Metadata:
      creation_time   : 2021-11-09T07:11:49.000000Z
      handler_name    : SoundHandler
```

### Application version

0.12.3

### Device information

Chromecast with Google TV

### Android version

Android TV OS 10

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Can you try the latest beta and see if that fixes it?
It can be installed by enrolling in the beta via google play or you can just grab the debug apk from the releases page on this repo.
