### ISSUE TITLE
libVLC seekbar timer skips when playing transcoded media (after a seek).

### ISSUE THREAD

**Issue by ManuLinares** [jellyfin/jellyfin-androidtv#1347]
### Describe the bug

Description: When playing videos, the seekbar timer skips 1sec every few seconds. Ex: goes from 00:00:05 to 00:00:07. (sometimes skips larger amounts of secs)

It only happens **after you manually seek** or starting a video with "Resume from x:xx".
Transcoded videos only, using libVLC backend.

This causes subtitles to skip lines (don't show lines in that skipped second)

---
It seems that if I don't seek (let the video play from beginning), or is "video direct" it works without skipping secs in the timer.
Also worth mentioning that video image plays fine, it's only the timer, and subsequently the subtitles.

---
**Application version:** Latest dev App Build 933
**Device information:** Firestick v1 AFTM
**Android version:** Fire OS 5 (API level 22)
**Jellyfin server version:** 10.7.7

**Comment by mueslimak3r** [comment]
Can you rebuild the app with this code added at the line I linked to? Then capture logs with `logcat`


`Timber.d("vlc got time [%s] meta start time [%s]", time, getMetaVLCStreamStartPosition());`


https://github.com/jellyfin/jellyfin-androidtv/blob/91c4629d207f07df377a1aa06d4fdb3e9a36e707/app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java#L223

**Comment by ManuLinares** [comment]
> I can't reproduce this issue on my end. Can you rebuild the app with this code added at the line I linked to? Then capture logs with `logcat`
> 
> `Timber.d("vlc got time [%s] meta start time [%s]", time, getMetaVLCStreamStartPosition());`
> 
> https://github.com/jellyfin/jellyfin-androidtv/blob/91c4629d207f07df377a1aa06d4fdb3e9a36e707/app/src/main/java/org/jellyfin/androidtv/ui/playback/VideoManager.java#L223

Of course

[logcat20220117_directplay.txt.tar.gz](https://github.com/jellyfin/jellyfin-androidtv/files/7884783/logcat20220117_directplay.txt.tar.gz)
[logcat20220117_transcoding.txt.tar.gz](https://github.com/jellyfin/jellyfin-androidtv/files/7884784/logcat20220117_transcoding.txt.tar.gz)
[logcat20220117_transcoding2.txt.tar.gz](https://github.com/jellyfin/jellyfin-androidtv/files/7884785/logcat20220117_transcoding2.txt.tar.gz)

**Comment by mueslimak3r** [comment]
I can see the issue in the logs. Unfortunately, this looks like an issue with libVLC since the number it's providing is false is is sometimes jumping by 2 or 3 seconds. You could try adding `mForcedTime` to that log output and see if it's ever being set.

One possibility is that all this log output is slowing down the main thread and causing issues with libVLC.

**Comment by ManuLinares** [comment]
mForcedTime is always "-1", I've built in release mode (and self signed) thinking it would be "less taxing" on the system to no avail. Example logs after:
```
...
01-18 20:02:50.040 11224 11224 D VideoManager: vlc got time [72470] meta start time [1170000] mForcedTime: [-1]
01-18 20:02:50.296 11224 11224 D VideoManager: vlc got time [72727] meta start time [1170000] mForcedTime: [-1]
01-18 20:02:50.552 11224 11224 D VideoManager: vlc got time [72982] meta start time [1170000] mForcedTime: [-1]
...
```

Where can I change log level to "info"?

**Comment by mueslimak3r** [comment]
Im not sure about changing the log level.
You could try bumping the version of libvlc to the latest pre-release version, or even try it with older versions.
We were using 3.3.14 until about a month ago, so you could try that again. And there's the pre-release version to try too.

Here's the line to change:
https://github.com/jellyfin/jellyfin-androidtv/blob/395d3849085335fb5eb0344c34dcde3c32a1df52/gradle/libs.versions.toml#L33

Here's a list of libvlc versions:
https://search.maven.org/artifact/org.videolan.android/libvlc-all

**Comment by mueslimak3r** [comment]
If you do mess around with the libVLC version make sure you gradle sync after the change

**Comment by ManuLinares** [comment]
Same issue, I've tried libVLC 3.5.0-eap1, 3.3.14, 3.3.0.
Irrelevant but older 3.2.x fails to build with 
```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class org.jellyfin.androidtv.ui.playback.VideoManager, unresolved supertypes: OnNewVideoLayoutListener
Adding -Xextended-compiler-checks argument might provide additional information.

```

Question: 
The only way the seek time is updated is on libVLC callback? 
Shouldn't jellyfin maintain its own timer, and sync every so often (or on desync)?

**Comment by mueslimak3r** [comment]
> Question: 
> The only way the seek time is updated is on libVLC callback? 
> Shouldn't jellyfin maintain its own timer, and sync every so often (or on desync)?

If you look in PlaybackController the getRealtimeProgress thing does just that, but only for live tv.

For the type of stream libVLC is getting when transcoding, it actually thinks it's a live stream instead of VOD, which is likely part of the problem. That's why I switched exoplayer over to HLS (for newer devices than yours unfortunately).

**Comment by ManuLinares** [comment]
Playback has a very convoluted logic for my brain, if you think of a way to force this (for testing only) I'll be glad to test. As of now, I'm hacking away code and testing.

PS: If freaking scrcpy worked in a device as old as firestick v1 I'd already have made an automated testing environment. 
I'm using a combination of adb shell commands ("input keyevent x", "uninstall", "install", "am start -n org.jellyfin.androidtv.debug/org.jellyfin.androidtv.ui.startup.StartupActivity", etc)

**Comment by mueslimak3r** [comment]
A good place to start might be to try out an old version of the code and see if this always happened, or if it's something new.

As far as automating it goes, you should be able to write a bash script for your tests, run it in a separate terminal, and have the commands sent to the tty running adb shell

**Comment by mueslimak3r** [comment]
But really I think the solution to this issue is to get HLS working with libVLC.
I've tried a few times and no luck so far.

**Comment by ManuLinares** [comment]
> A good place to start might be to try out an old version of the code and see if this always happened, or if it's something new.
> 

good call, tested app v0.11.5, same issue

**Comment by mueslimak3r** [comment]
I was looking into the vlc player "options" that can be supplied when the player is created. The current ones are in `VideoManager`. It looks like there are option you could add which change how vlc's internal clock works. Those may be worth messing around with.

**Comment by ManuLinares** [comment]
although adding options.add("--clock-synchro"); options.add("0"); made the timer work, it made the video frameskip all the frames, so no video, audio choppy and no subtitles. Will keep messing with it.

**Comment by mueslimak3r** [comment]
If you have time, could you test this branch on your fire stick v1 and confirm that HLS for trancoding is working for exoplayer?
This hopefully enabled HLS support for older devices

it's working if:
* in the dashboard the session info shows it's transcoding and MP4 is the container
* the server logs will show something like: `Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" ... -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 ...`
* when you seek the app debug log will show: `D/PlaybackController: Seek method - native`
`I/VideoManager: Exo length in seek is: 3472030`

https://github.com/mueslimak3r/jellyfin-androidtv/tree/exoplayer-base-and-enhanced-profiles

**Comment by ManuLinares** [comment]
> If you have time, could you test this branch on your fire stick v1 and confirm that HLS for trancoding is working for exoplayer? This hopefully enabled HLS support for older devices
> 
> it's working if:
> 
>     * in the dashboard the session info shows it's transcoding and MP4 is the container
> 
>     * the server logs will show something like: `Jellyfin.Api.Helpers.TranscodingJobHelper: "/usr/lib/jellyfin-ffmpeg/ffmpeg" ... -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 ...`
> 
>     * when you seek the app debug log will show: `D/PlaybackController: Seek method - native`
>       `I/VideoManager: Exo length in seek is: 3472030`
> 
> 
> https://github.com/mueslimak3r/jellyfin-androidtv/tree/exoplayer-base-and-enhanced-profiles

HLS is working fine on exoplayer with the branch provided. I had to try different media until I found one that uses that profile.

`
/usr/bin/ffmpeg -init_hw_device opencl=ocl:0.0 -filter_hw_device ocl -i file:"/mnt/nasdata2/Library/Marvel Extended Universe/Captain America - The First Avenger (2011)/Captain.America.The.First.Avenger.2011.2160p.UHD.HDR.BluRay.(x265 10bit DD5.1).[WMAN-LorD].mkv" -map_metadata -1 -map_chapters -1 -threads 0 -map 0:0 -map 0:1 -map -0:s -codec:v:0 h264_nvenc -pix_fmt nv12 -preset medium -b:v 10130975 -maxrate 10130975 -bufsize 20261950 -profile:v:0 high -g:v:0 72 -keyint_min:v:0 72 -sc_threshold:v:0 0 -vf "zscale=s=3840x2160,format=p010,hwupload,tonemap_opencl=format=nv12:primaries=bt709:transfer=bt709:matrix=bt709:tonemap=hable:desat=0:threshold=0.8:peak=100,hwdownload,format=nv12" -start_at_zero -vsync -1 -codec:a:0 libfdk_aac -ac 6 -ab 640000 -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type fmp4 -hls_fmp4_init_filename "382d8b6ff3814e385270cb962362069e-1.mp4" -start_number 0 -hls_segment_filename "/var/lib/jellyfin/transcodes/382d8b6ff3814e385270cb962362069e%d.mp4" -hls_playlist_type vod -hls_list_size 0 -y "/var/lib/jellyfin/transcodes/382d8b6ff3814e385270cb962362069e.m3u8"
`

I also have a ffmpeg wrapper that changes the zscale to 1080 as there is another bug that the app doesn't send the correct max width to the server. Without the wrapper I see burgled output. But well, that's another bug.

**Comment by mueslimak3r** [comment]
Thanks for testing!
