### ISSUE TITLE
latest changes broke seeking in exoplayer

### ISSUE THREAD

**Issue by ManuLinares** [jellyfin/jellyfin-androidtv#1353]
### Describe the bug

Latest changes broke seeking in exoplayer.

After a seek, player starts from zero.

sad 😢

### Application version

latest dev build

### Device information

fire stick v1

### Android version

FireOS 5

### Jellyfin server version

10.7.7

**Comment by siankatabg** [comment]
You should probably give some more info like what you're playing, transcoding/not, default player, logs...

Anyway, I've just tried it on my firestick 4k (not max) and the latest changes actually fixed the seeking with libVLC (thanks for that). Tried both exo/libVLC with both transcoding/not transcoding media with both the rewind and the round buttons 👍

**Comment by nielsvanvelzen** [comment]
> You should probably give some more info like what you're playing, transcoding/not, default player, logs...

Definitely. Without that information we can't help. I don't understand why the sections were edited out after posting the issue either.

> Anyway, I've just tried it on my firestick 4k (not max) and the latest changes actually fixed the seeking with libVLC (thanks for that). Tried both exo/libVLC with both transcoding/not transcoding media with both the rewind and the round buttons 👍

Playback works perfectly for me too, it's way better then it was in 0.12.

**Comment by mueslimak3r** [comment]
> fire stick v1
It's possible that since the v1 firestick runs android 5.1 (from all the way back in 2014, api level 22), some new features or changes aren't compatible.

**Comment by ManuLinares** [comment]
> > You should probably give some more info like what you're playing, transcoding/not, default player, logs...
> 
> Definitely. Without that information we can't help. I don't understand why the sections were edited out after posting the issue either.

Edited out fluff as I was going to bed and didn't have time for logs, sorry.

[logcat20220117_tryingToSeekWithExoplayer_directplay.txt.tar.gz](https://github.com/jellyfin/jellyfin-androidtv/files/7884836/logcat20220117_tryingToSeekWithExoplayer_directplay.txt.tar.gz)
[logcat20220117_tryingToSeekWithExoplayer_transcoded.txt.tar.gz](https://github.com/jellyfin/jellyfin-androidtv/files/7884838/logcat20220117_tryingToSeekWithExoplayer_transcoded.txt.tar.gz)

Jellyfin Server: 10.7.7
App built with latest master
Device: Firestick v1 (FireOS 5), api 22
Description: with Exoplayer, I cannot manually seek with any remote keys. After a seek, it goes back to start. If video is started with "Resume from xx:xx", after a seek is goes back to that time.

**Comment by mueslimak3r** [comment]
* the logs you provided are mixed up. The one labelled directplay.txt is all transcoded. The one labeled transcoded.txt is a mix of direct and transcoded.

* It looks like your device isn't using the new HLS profile. That explains why things broke. It's unclear why this is happening, but I went ahead and added some conditions to detect a situation like this. Can you test this build and report back (download the build artifacts to get the apk):

https://github.com/jellyfin/jellyfin-androidtv/actions/runs/1711073338

**Comment by ManuLinares** [comment]
> * the logs you provided are mixed up. The one labelled directplay.txt is all transcoded. The one labeled transcoded.txt is a mix of direct and transcoded.
> 
>     * also in the future please just upload the .txt files and dont bother archiving them unless you put them all in the same archive :)
> 
>     * It looks like your device isn't using the new HLS profile. That explains why things broke. It's unclear why this is happening, but I went ahead and added some conditions to detect a situation like this. Can you test this build and report back (download the build artifacts to get the apk):
> 
> 
> https://github.com/jellyfin/jellyfin-androidtv/actions/runs/1711073338

No problem. logs with provided build:

[logcat20220118_020000_tryingToSeekWithExoplayer.txt](https://github.com/jellyfin/jellyfin-androidtv/files/7886279/logcat20220118_020000_tryingToSeekWithExoplayer.txt)
[logcat20220118_020000_tryingToSeekWithlibVLC.txt](https://github.com/jellyfin/jellyfin-androidtv/files/7886281/logcat20220118_020000_tryingToSeekWithlibVLC.txt)

**Comment by mueslimak3r** [comment]
No problem as in this build fixes the issue with exoplayer on your device?

**Comment by mueslimak3r** [comment]
I made a few changes. Here's a new build. It may take a few minutes for the artifacts to show up:
https://github.com/jellyfin/jellyfin-androidtv/actions/runs/1711199156

**Comment by ManuLinares** [comment]
https://github.com/jellyfin/jellyfin-androidtv/pull/1362

**Comment by nielsvanvelzen** [comment]
Keeping the issue open until the pull request is merged.
