### ISSUE TITLE
Tipo in source translation file

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin-androidtv#1358]
### Describe the bug

The key `pref_direct_stream_live_off` in the source translation file (English US) is writed as `Transcoding is used when neccesary`, it should be `Transcoding is used when necessary` i.e. with `double c` and `single s` instead `single c` and `double s`.

### Application version

any

### Device information

any

### Android version

Android TV

### Jellyfin server version

any

**Comment by nielsvanvelzen** [comment]
Thanks, this was my mistake. Made a pull request #1359.
