### ISSUE TITLE
Transcoding issues

### ISSUE THREAD

**Issue by LegendaryB** [jellyfin/jellyfin-androidtv#136]
Hey guys,

thank you for developing this amazing piece of software!
I have a problem with playback of my media. I have mostly HEVC (h265) 10bit files with subtitles. Playing through the web UI seems fine. Also the transcoding is working fine I think.

But I also have a Amazon Fire TV Stick (the newest). Playing the same file works. Until I enable subtitles. Then its stuttering and in the admin dashboard I see my client switching between direct play and transcode (changes every 1-2 seconds). Video on FTV is not playing and repeated all the time.

My setup:
CPU: AMD Ryzen 2200G
RAM: 16GB DDR4
Runtime: Docker
No additional GPU.

Does anybody have a tip for me how I can fix this issue?

Kind Regards,
Daniel

**Comment by thornbill** [comment]
Did you happen to check the server logs to see if there is an error? This sounds similar to https://github.com/jellyfin/jellyfin/issues/1388.

**Comment by LegendaryB** [comment]
Have also added a issue there: https://github.com/jellyfin/jellyfin/issues/1609

Because I thought that it maybe is more a server / docker problem,

**Comment by thornbill** [comment]
Closing as this seems to have been a server issue and appears to have been resolved in https://github.com/jellyfin/jellyfin/issues/1609.
