### ISSUE TITLE
Crashes when server IP is changed

### ISSUE THREAD

**Issue by danielbr14** [jellyfin/jellyfin-androidtv#1396]
### Describe the bug

When the server IP changes the app prompts you to send a crash report but after pressing ok it crashes again causing an endless cycle.

Only workaround I found was to uninstall and reinstall the app again.

### Application version

0.12.3

### Where did you install the app from?

Google Play

### Device information

Sony KD75XF8596

### Android version

Android 8.0.0

### Jellyfin server version

10.7.7

**Comment by DavidFair** [comment]
Just to clarify, is this using a DNS name or an IP address for the server field?
I haven't had a chance to test if this is happening locally yet though

**Comment by danielbr14** [comment]
Using IP, and the server was automatically discovered by the app.

**Comment by sourpatched** [comment]
I too have found this, when the app can't connect to the server the app would crash and close, when you open the app again the Jellyfin logo will show then it will crash again and again.  Settings --> Apps --> Jellyfin  Force close then clear data fixes this and as long as the server is online the app will connect to it.

**Comment by nielsvanvelzen** [comment]
I tried reproducing this bug with the following steps:

1. Adding a server and signing in
2. Turn off the application
3. Turn off the server
4. Open the app

After I opened the app the loading screen shows (which admittedly shows for too long) and then it goes back to the login screen because it couldn't connect. There was no crash.

Please provide steps to reproduce the issue and/or logs from the app or we can't help out.

**Comment by sourpatched** [comment]
1. login to server
2. change server IP or close the port of the Jellyfin server
3. go back to android home screen (use back button) 
4. open the app again

**Comment by sourpatched** [comment]
@nielsvanvelzen Have you been able to test this?

**Comment by nielsvanvelzen** [comment]
No, I was unable to reproduce the issue. It might have been fixed after 0.12.3. Can you try again with the latest 0.13 beta?

**Comment by sourpatched** [comment]
Your android app is my go to Jellyfin app each time I use Jellyfin (99.9% of the time) it's one of the reasons I don't use beta, i suppose if side loading was made easier it could be done that way and have two apps in case something goers wrong. 

I'll look into side loading, maybe more people would try beta  if they could get the app a better way. without losing non beta

**Comment by sourpatched** [comment]
Used FX web to upload beta file to AndroidTV but on install says Do you want to install an update to this existing application? 

We're not able to have both app side by side?

**Comment by nielsvanvelzen** [comment]
The debug version uses a separate app id and can be installed together with the release version (it will show up with an orange logo instead of our usual purple).

**Comment by sourpatched** [comment]
Done, installed. Any errors I'll open an issue. As for this issue I'm not sure if I'll get round to testing it.

**Comment by sourpatched** [comment]
@nielsvanvelzen This issues has been fixed however, the login page doesn't say offline just says incorrect username and or password.

**Comment by nielsvanvelzen** [comment]
There is an open PR to add offline detection (#1309) which is likely to go into 0.14.
