### ISSUE TITLE
Turkish subtitle problems

### ISSUE THREAD

**Issue by uguryavas** [jellyfin/jellyfin-androidtv#140]
![image](https://user-images.githubusercontent.com/16846504/63436774-f4bd5080-c431-11e9-8582-a94f16808b61.png)
Turkish subtitles have such problems
I've tried other subtitles all the same problem.
examples
ğ = ð
ı = ý
s = y

**Comment by thornbill** [comment]
Hi @uguryavas, did you mean to close this issue? We’re you able to find a solution?

**Comment by mehmetfazil** [comment]
Solution?
