### ISSUE TITLE
Refresh rate switching problem

### ISSUE THREAD

**Issue by robmcc1983** [jellyfin/jellyfin-androidtv#1402]
### Describe the bug

Hi,
When I enable refresh rate switching some videos do not play.
I enabled this setting on the jf app for firetv cube as I thought it would improve stuttering during moving scenes.

Watching movies my tv will default to matching resolution and change to 24p and everything is perfect.

The problem is with some tv series. I have some that work perfect and switch as they should and others that don't. 

Some still play at the fire tv cube default resolution of 4k 60hz even though they are 720p videos.

Others just show a black screen briefly and then return back to jellyfin without even playing the video.

I must add that these videos do play fine with refresh switching off but I would like it on for the purpose of movies looking smother.

One other thing to add, my live TV also works fine, tv will switch to 720p 50hz when playing a tv channel from the jellyfin tv guide.

Any help would be appreciated 
Thank you

### Application version

0.12.3

### Device information

Amazon fire tv cube

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Can you side load the beta APK and see if it's still an issue?

**Comment by robmcc1983** [comment]
I can do if I know where I can obtain the beta apk from.
Thanks

**Comment by mueslimak3r** [comment]
> I can do if I know where I can obtain the beta apk from. Thanks

https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.13.0-beta.1

**Comment by robmcc1983** [comment]
Perfect, I'm just watching a movie at the moment but once it's finished I'll give it a try and report back.
Thank you

**Comment by mueslimak3r** [comment]
Thanks. Another thing to test is setting "preferred video player" to exoplayer.

It's useful to know if setting it to auto, libVLC, or exoplayer fix or cause the issue.

**Comment by robmcc1983** [comment]
OK so more finding here.
Firstly I always use exoplayer because if I use libVLC I always get out of sync audio so I've always stuck with exoplayer since using jellyfin.
The problem is present on both libVLC and exoplayer I've just tried this.

So using the beta I still have the same problem although this time a couple of videos that didn't play now do but when they first start playing I get a message on screen saying "playback error encountered. Will re-try...."  but my tv does change resolution and refresh rate to match.

The same videos that played in 4k 60hz still do even though these are 720p videos.

Not sure what is happening here, I would just disable the refresh rate thing but after seeing how smooth it plays movies I would like to try and solve this.

Thank you
Rob

**Comment by mueslimak3r** [comment]
Can you side load the debug build of the beta and collect some logs using `adb logcat`?
This will help identify the cause of the player error and/or crash


I don't have a screen that supports switching refresh rates
