### ISSUE TITLE
Subtitle size does not work 

### ISSUE THREAD

**Issue by DemirG** [jellyfin/jellyfin-androidtv#1404]
### Describe the bug

The newly implemented subtitle size function does not work properly. Doesn't matter which value is set, it's always the same size. 

### Application version

0.13.0-beta1

### Where did you install the app from?

Google Play

### Device information

Sony Android TV 

### Android version

Android 10

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Without the media information we definitely can't help with this one. I'm guessing your using image subtitles or something which obviously isn't resizable by the client.

**Comment by DemirG** [comment]
> Without the media information we definitely can't help with this one. I'm guessing your using image subtitles or something which obviously isn't resizable by the client.

Here is the media info from JF.

![image](https://user-images.githubusercontent.com/76853250/152116296-497b66f5-368c-4d0d-9dd5-64e2a550344e.png)

**Comment by nielsvanvelzen** [comment]
The subrip subtitles should support resizing, the (english) ass subtitles won't.

**Comment by DemirG** [comment]
Size and black bar behind subtitle work as intended for .srt, does not work for .ass / .dvdsub.

**Comment by nielsvanvelzen** [comment]
Yes. ass subtitles are complex and our video player is unable to show them so they are baked into the video serverside. vobsub/dvdsub are literally images so they can't be resized either.

**Comment by DemirG** [comment]
> Yes. ass subtitles are complex and our video player is unable to show them so they are baked into the video serverside. vobsub/dvdsub are literally images so they can't be resized either.

Okay, then this change is working as intended and issue can be closed? I thought every subtitles would be able to be resized 😄
