### ISSUE TITLE
Change place of playback speed 

### ISSUE THREAD

**Issue by DemirG** [jellyfin/jellyfin-androidtv#1405]
### Describe the feature you'd like

Hi I would request to set the newly implemented playback speed button during playback to a different place. Most preferably to the most right position, or under the seek bar.

CC and audio buttons should be near each other and playback speed moved.

**Comment by DavidFair** [comment]
This is a fairly easy fix, and I agree that from a UX point of view buttons should be grouped together in a hierarchy of use (more people are probably using CC / audio than playback speed). 

Good shout, I'll throw up a PR today to do this and see what people think
