### ISSUE TITLE
0.13beta1 track transcoding bug

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-androidtv#1410]
### Describe the bug

1.Select exoPlayer to play
2.Audio selection pass through
Then, On devices that support AC3 and DTS, track transcoding is AAC and silent.
If mixed stereo is selected, the track is transcoded to AAC and works is OK.
The old version will be transcoded to AC3 according to the option, and it works well.
We hope to add the option of forced AC3 / DTS transcoding to make more devices work.This is very important.Android devices are difficult to set up multi-channel, and the transcoding of the old version of AC3 / DTS is a miracle.
Thanks.

### Application version

0.13 beta1

### Device information

android TV

### Android version

Android 7,Android 9

### Jellyfin server version

10.8.0 alpha5

**Comment by mueslimak3r** [comment]
Do you still have this issue with 0.13 beta2?

**Comment by shaino** [comment]
Yes.This issue still occurs in 0.13 beta 2.
And
I hope users can choose to force transcoding to AC3, which will be a great function.

**Comment by mueslimak3r** [comment]
Switching from fmp4 in HLS to ts in HLS would allow supporting ac3 in the transcoded stream again

**Comment by shaino** [comment]
Yes, I noticed that the transcoding format of the new version is 264/265 MP4 format. But I didn't find an option to choose TS or MP4.
