### ISSUE TITLE
Color bar at the bottom of transcoding H264 video picture.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-androidtv#1411]
### Describe the bug

1.Select exoPlayer to play.
2.Transcoding video.
A color bar appears at the bottom of each frame.If you burn PGS/SUP subtitles, the color bar will be more obvious.
Just like when copying in memory, there are several lines missing and several lines of invalid data left blank.
The latest 0.13beta1 default hevc transcoding does not have this problem.
If the 0.13beta1 server turns off hevc coding and adopts H264 coding, the problem will appear.

### Application version

0.12.3,0.13.0.beta.1

### Device information

android TV

### Android version

Android 7,Android 9

### Jellyfin server version

10.7.7,10.8.0alpha5

**Comment by nielsvanvelzen** [comment]
Use the playback template and fill in the requested questions (like media info!!).

I'm guessing this might be a server issue though.
