### ISSUE TITLE
[FR] Volume normalisation / night mode

### ISSUE THREAD

**Issue by mrx23dot** [jellyfin/jellyfin-androidtv#1434]
### Describe the feature you'd like

Is anyone else annoyed by explosions in movies at night while family is asleep?

Expensive audio receivers have movie mode, where it compresses the dynamic range and applies volume normalization, so whispering would be almost the same level as shouting in an explosion.

Same goes for intro in series.

A feature like this in settings would be great.
Please vote up.

**Comment by Goblinlordx** [comment]
I would really love this but I do think this would probably be best implemented on the server? I expect this could be implemented using ffmpeg and audio transcoding. I think the more complicated part would be settling on reasonable settings which would accomplish this appropriately. Either way, would really like to see this no matter how it is done 👍 .

**Comment by mrx23dot** [comment]
Server side would require transcoding to be always enabled I guess, but it's better than nothing.
ffmpeg has already built in modules:

[loudnorm](http://ffmpeg.org/ffmpeg-all.html#loudnorm): loudness normalization according to EBU R128. You can set an integrated loudness target, a loudness range target, or maximum true peak. This is recommended for publishing audio and video and it is used by broadcasters all over the world.
single pass for livestreams

looks great
`ffmpeg -i file_example_MP3_5MG.mp3 -filter:a loudnorm=i=-24:tp=-2:lra=7,volume=5dB file_example_MP3_5MG_proc0.mp3`
![comp](https://user-images.githubusercontent.com/4163396/155109496-81de10b7-f583-41dd-bc0b-e33f1c452d71.jpg)

**Comment by Goblinlordx** [comment]
Well I don't think it would necessarily need to be on 100%. Though, if it is used often then it essentially would be. Either way, I don't think that is necessarily problematic but something that the person running the server should probably be aware of and maybe optionally allow users to use or not.

I expect a combination of both `acompressor` and `loudnorm` might be best but this is definitely out of my area of expertise. The wave form changes you show above definitely look pretty good to me.

I do think it would take a lot more effort to implement on a client-side basis though anyways. Doing it server-side would allow it to be enabled regardless of client. There are also already transcoding support for the stream implemented on the server-side. Maybe we can open up this issue on the `jellyfin/jellyfin` project. I would love to see this implemented and will help where I can (I am not a C# dev so the codebase is a bit foreign to me though).

**Comment by mrx23dot** [comment]
Sure, it should be an option in server config.
loudnorm should be enough, this is what's being used in broadcast TV, as a standard.
Do you have rights to transfer this ticket over to jellyfin/jellyfin?
Cheers

**Comment by Goblinlordx** [comment]
I don't, but you can file an issue on the project same as this one. Reference this one in it (just paste the URL for this one somewhere in the description).

`jellyfin/jellyfin` feature request: [URL](https://github.com/jellyfin/jellyfin/issues/new?assignees=&labels=feature-request&template=feature_request.md&title=)

**Comment by Goblinlordx** [comment]
Here seems to be a similar request: https://features.jellyfin.org/posts/1112/a-night-mode-basically-sound-compressor-to-lower-sound-dynamic
