### ISSUE TITLE
Fast forwarding response very slow or restarts video (Beta 2)

### ISSUE THREAD

**Issue by bigdav1178** [jellyfin/jellyfin-androidtv#1443]
I tested out the latest beta of the new app (beta 2, at the time), and noticed the response to fast forwarding (or forward seeking) after starting a video is very slow - it would take a few seconds before the app would respond to my key press, beyond pausing the video at the point of they key press. I did find that this behavior seemed to improve after the video had been playing for some time. This is what I would experience with exoplayer selected.

If libvlc was selected in settings, however; it would not fast forward at all. In fact, it would restart the video at the beginning. I did not leave the video play long enough to determine if the same behavior would occur after the video had been running for some time.

I just wanted to relay my experiences to help with the improvement of the beta.

**Comment by nielsvanvelzen** [comment]
Use the bug report template to report bugs please.
