### ISSUE TITLE
Playback from cloud service

### ISSUE THREAD

**Issue by fmchris10** [jellyfin/jellyfin-androidtv#1444]
### Describe the bug

I have a cloud service setup with remote use via RClone, via the webplayer everything is fine but within the Android TV app (Jellyfin).  Playback can be a little iffy.

I can watch videos perfectly fine.

Skipping/fast-forwarding/rewinding isn't smooth.

Often it closes the media and, this forces the app to go back onto the title screen.

The transcoding works perfectly fine with the webplayer, however, its no joy to use with a remote control. Where would I find error logs? I searched my device for Jellyfin and found nothing. I have also looked in the android part for any folders with it in the name.

### Application version

0.12.3

### Device information

T9 Android Box 32GB model

### Android version

8.1.0

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
If the server needs to read the media from a remote server the latency can cause dramatic delays when seeking. This is not something we can do much about, especially on the app side.

**Comment by fmchris10** [comment]
Testing once again if I can reply.
