### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by fmchris10** [jellyfin/jellyfin-androidtv#1445]
### Describe the bug

Movies which have long titles, such as Pirates of the Caribbean: The Curse of the Black Pearl.

70% of Pirates of the Caribbean: is only readable, as the other 30% is off-screen.

The Add to Queue button suffers a similar fate.

I would say only 50/50 of the "queue" can be made out visable, the rest is cut off.

[More a request] There's no trailer button? - I was a bit surprised by this.
Cloud streaming doesn't seem to generate chapters, possibly due to some form of transcoding issue but on the webplayer this isn't an issue (albeit I don't see chapters there, but you can fast-forward/rewind without issue).

Early days I know, just very eager to report back and let the devs know.

Thank you for releasing a TV version of Jellyfin, it's needed.

### Application version

0.12.3

### Device information

T9 Android Box 32GB model

### Android version

8.1.0

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Create a separate issue for each bug please. For questions and troubleshooting use our troubleshooting channels.
