### ISSUE TITLE
Issue with Android TV app cloud service

### ISSUE THREAD

**Issue by fmchris10** [jellyfin/jellyfin-androidtv#1447]
### Describe the bug

I have a cloud service setup with remote use via RClone, via the webplayer, Everything is fine (No playback issues whatsoever) but within the Android TV app (Jellyfin). Playback can be a little iffy.

I can watch videos perfectly fine.

Skipping/fast-forwarding/rewinding isn't smooth.

Often it closes the media and, this forces the app to go back onto the title screen.

The transcoding works perfectly fine with the webplayer, however, it is no joy to use with a remote control.  I don't understand how its not an issue with the app, when the web player works fine, as does a third-party app as mentioned below. Unfortunately, this is the only real solution for  a TV's.

https://github.com/jellyfin/jellyfin-androidtv/issues/1444 <-- Please allow the community to respond.

VVVVVV
#There's a huge difference between the webapp and, the Jellyfin Android TV app.

The webview app is flawless with its playback, whereas I explained the issues are only with the app itself. I actually tried the Findroid app and the playback on it was fine. 🤷🏻‍♂️

Neither the web app or Findroid is a good experience on a TV though, despite the none playback issues. Navigating and using those options are terrible on a TV.

### Application version

0.12.3

### Where did you install the app from?

Sideloaded APK

### Device information

T9 Android Box 32GB model

### Android version

8.1.0

### Jellyfin server version

10.7.7

**Comment by fmchris10** [comment]
Well, weirdly as it seems it's started working better since I forced closed the app and restarted.

Picking up the playback doesn't resume to where I was though, it seems very random. I'll try to see if I can get some reports of what's happening at my end. It does seem to app related.

**Comment by thornbill** [comment]
Do not open duplicate issues. You can continue to comment on the previous issue and it can be reopened if enough information is found to determine that the issue is with the app itself.

**Comment by fmchris10** [comment]
I tried to reply, it said I wasn't allowed. 🤷🏻‍♂️
