### ISSUE TITLE
Put track language and type label ahead of file name

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-androidtv#1448]
### Describe the feature you'd like

Clicking on the audio icon, I get a scrolling "Movie.Name.2004.2160p.US.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.Atmos-RLS - Eng - Dolby" .  Of course all of this is useless except the very last part of it.

Can we swap the order of the labels to show the audio format and type BEFORE the file name (or eliminate the file name entirely, or abbreviate it).  With long file names, and lots of tracks (ie: multiple languages in one file) it makes it very challenging to find the right track as you have to wait for each one to scroll to figure out which it even is.

This is the same on JellyFin-web, so if this is in the jellyfin server, let me know and I can go through those channels.,

**Comment by newton181** [comment]
File a bug in Jellyfin Server repository:

[New isuue](https://github.com/jellyfin/jellyfin/issues/new/choose)

**Comment by michaelkrieger** [comment]
I've opened jellyfin/jellyfin#7330 on this issue, as it appears to be the same on jellyfin-web. Moreover, it seems to not be an ordering issue, but a bug which is causing the filename to not be properly stripped from the audio/video selector.

This can be closed here.
