### ISSUE TITLE
[Feature Request] Better Seeking & GUI

### ISSUE THREAD

**Issue by grravity** [jellyfin/jellyfin-androidtv#146]
The seeking controls are quite bad imo. Using left or right on the controller is not very smooth and holding it down I'd expect it to seek faster the longer you hold it. 

The gui for seeking is also quite poor imo, I feel something similar to Youtube's seek bar, where you press up on the controller, and a dot appears on the seekbar and you can scroll through and pick your exact time. This would be ideal imo.

Would also love to see seek previews (Similar to youtube, a box above where you are seeking that displays a frame of the film)

**Comment by Florianisme** [comment]
I'm currently working out a redesign and implementation of a more modern and intuitive player UI

**Comment by nielsvanvelzen** [comment]
The new overlay was added in #251 and seeking was slightly improved in #581.
