### ISSUE TITLE
More customization options to subtitles (colors, fonts, placement)

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-androidtv#1461]
### Describe the feature you'd like

Since we now (finally!) are able to set the font size and disable the background, I'd also like to request the options to customize the color, font and placement on screen, similar to what's available in Kodi.

**Comment by sparky3387** [comment]
Was thinking of having a look at this, ill submit a pull request having a color picker, really i would like some opinions of colors, maybe using the Netflix subtitle colors as suggestions, what do people think? 
These are what i get:
ffffff,000000,c80000,00c800,0000c8,eedc00,d60080,009fda

You can already change (background) color by just changing the line:

https://github.com/jellyfin/jellyfin-androidtv/blob/4c2ce100045af654a4d4217558f2315b0e55bf75/app/src/main/java/org/jellyfin/androidtv/ui/playback/CustomPlaybackOverlayFragment.java#L1487

Here is an example by changing this line to:
`                span.setSpan(new PaddedLineBackgroundSpan(ContextCompat.getColor(requireContext(), R.color.grey_transparent), SUBTITLE_PADDING, horizontalGravity), 0, span.length(), Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
`
![image](https://user-images.githubusercontent.com/1683850/179387349-523b0957-5c86-4483-b94d-a656eb4382f2.png)

**Comment by sparky3387** [comment]
So here is a preview of the work ive done, I will submit this today at some point after I double check all the code
![image](https://user-images.githubusercontent.com/1683850/181134767-f5f3bd62-71f4-4e62-ba4b-bfcbb6c75991.png)
![image](https://user-images.githubusercontent.com/1683850/181134911-3dd98d44-e704-4152-aa90-b7669a8cfff2.png)
![image](https://user-images.githubusercontent.com/1683850/181134937-0f83b221-309f-4723-a2f2-01c843f9b3b1.png)

**Comment by sparky3387** [comment]
Have now created a [pull](https://github.com/jellyfin/jellyfin-androidtv/pull/1900) request for this, hopefully havent made any mistakes

**Comment by nielsvanvelzen** [comment]
We've had subtitle customization for a while now and it will be revamped in 0.18 in a major overhaul of subtitle handling. Closing as fixed.
