### ISSUE TITLE
Jellyfin uses directplay of HDR content on SDR-only display

### ISSUE THREAD

**Issue by ringus1** [jellyfin/jellyfin-androidtv#1467]
### Describe the bug

Application doesn't make server transcode HDR content to SDR when used on SDR-only display (chosen also in Android system manually). This causes massive stuttering and non-watchable experience.

### Logs

```shell
https://gist.github.com/ringus1/cd09395f00533902b2e0cf5357e69fb1
```

### Application version

050affa0a8a6d28668060c41b467fd0565f4b601

### Device information

Chromecast with Google TV

### Android version

Android 10

### Jellyfin server version

10.8.0 installed on 13-Jan-2022 from unstable repo

**Comment by glenskie16** [comment]
Ive noticed Chromecast with Google TV has significant issues with any 4k content in my experience.
