### ISSUE TITLE
Favourites on home screen

### ISSUE THREAD

**Issue by fmchris10** [jellyfin/jellyfin-androidtv#1468]
### Describe the feature you'd like

Next to the search and cog icon within the home screen, can we have a link to our favourites? Yet instead of listing just one category, it lists them all.

For example, I have three categories - Films, TV and Kids.

It would be nice to see the favourites within each area.

Films
1, 2, 3, 4, 5, etc

TV
1, 2, 3, 4, 5, etc

Kids
1, 2, 3, 4, 5, etc

I realise that you can check the favourites of each category within its own section, but a general view of them all would be a nice touch.

**Comment by nielsvanvelzen** [comment]
Duplicate #1232
