### ISSUE TITLE
[Feature Request] Show Film's Technical Details At Bottom of Page

### ISSUE THREAD

**Issue by grravity** [jellyfin/jellyfin-androidtv#147]
Similar to the WEB GUI, I'd love to see the ability to view technical details about the film at the bottom of the films page (Codec, bitrate, etc.)

Screenshot of Web Example:
https://b.catgirlsare.sexy/HsPi.png

**Comment by nextlooper42** [comment]
Make this optional, for example i dont want that to be shown... useless stats that clutter screen.

**Comment by nielsvanvelzen** [comment]
This is already available when enabling the "Debug options" toggle in the app settings.
