### ISSUE TITLE
No Version selection on Movies

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin-androidtv#1471]
### Describe the feature you'd like

1. Open any movie that has more then one version e.g (The Martian 4K.mkv, The Martian 1080p.mkv)
2. No selection of version instead uses "the first one"

Expected to allow user to select the version he wants to start playback of.

As my upload speed, as well as the current 4K HDR transcoding of jellyfin is limited, its rather important to allow my external clients to select a pre-transcoded version of a movie, as they are otherwise not able to view any movies.

**Comment by nielsvanvelzen** [comment]
This is already implemented for the next version (0.13)!
