### ISSUE TITLE
0.13 beta4: Silent when the audio is pass-through as AAC 5.1.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-androidtv#1472]
### Describe the bug

The TV client audio option is pass-through.

Thank you very much for fixing TS/AC3, what a great improvement.
After re-encoding and mixing down to AC3, playback works fine on TV devices that support AC3.

But:
The device remains silent when playing video with an AAC5.1 audio track that does not require transcoding.
It is also normal if the audio track is AAC 2.0. This means that AAC 5.1 does not play back properly on my device that supports AC3. 

### Application version

0.13 beta4

### Device information

android TV

### Android version

Android 7,Android 9

### Jellyfin server version

10.8.0 alpha5

**Comment by shaino** [comment]
Video
Title1080p HEVC SDR
CodecHEVC
ProfileMain
Level120
Resolution1920x816
Aspect ratio2.35:1
InterlacedNo
Framerate23.976025
Bitrate3437 kbps
Bit depth8 bit
Video rangeSDR
Pixel formatyuv420p
Ref frames1

Audio
Title Eng AAC5.1 - English - AAC - Default
Languageeng
CodecAAC
ProfileLC
Layout5.1
Channels6 ch
Bitrate384 kbps
Sample rate48000 Hz
DefaultYes

**Comment by shaino** [comment]
Sorry, I guess the problem should be with me.
My home theater uses HDMI's ARC.
When the movie without transcoding contains an AAC5.1 audio track, the client determines that the device supports and directly transmits the AAC5.1 audio track. ARC can only transmit AC3/DTS/LPCM2.0, and cannot transmit LPCM multichannel.

If so, shuld the development team add the option to force the server to transcode?
THX.

**Comment by mueslimak3r** [comment]
I've found a few resources describing how to change how an app handles audio passthrough.
To work on those I'll need some more information.

It would help to properly identify what's going on with your device when it attempts to play the AAC-LC 5.1 audio over HDMI-ARC. To do that, client logs are needed. Please collect them with `adb logcat`.

**Comment by shaino** [comment]
Okay, I'll try.
