### ISSUE TITLE
fad effect text (in ass subtitles) is not clear during video playback

### ISSUE THREAD

**Issue by yuhua18** [jellyfin/jellyfin-androidtv#1474]
### Describe the bug

 fad effect text (in ass subtitles) is not clear during video playback
for example
the following subtitle snippet
Subtitle link:  https://mega.nz/file/YMNznIbJ#DhjrJKrX7n5d1M8s_ItLpHMXH5k_d9n-yq1sezE4Soo
video link:  https://mega.nz/file/ZUkgCTaZ#hD1Xg3gwDWNLvAV_kjv_qwKC5r1QImig-gM6uo31mOs
BUG time: 22:10

Dialogue: 0,0:22:10.64,0:22:17.26,ED2-JP,,0,0,0,,{\fad(360,360)}透明な夢を　そっと抱き寄せた
Dialogue: 0,0:22:17.68,0:22:23.76,ED2-JP,,0,0,0,,{\fad(360,360)}いつか崩れゆく星の上
Dialogue: 0,0:22:24.83,0:22:31.00,ED2-JP,,0,0,0,,{\fad(360,360)}生まれ落ちては　消えていくみたい
Dialogue: 0,0:22:31.84,0:22:37.96,ED2-JP,,0,0,0,,{\fad(360,360)}いのちの行方を考えていた
Dialogue: 0,0:22:38.67,0:22:45.47,ED2-JP,,0,0,0,,{\fad(360,360)}何度も砕けて欠けた心を集める
Dialogue: 0,0:22:45.47,0:22:55.06,ED2-JP,,0,0,0,,{\fad(360,360)}小さな光を探すように　まだ空を見て
Dialogue: 0,0:22:55.93,0:23:02.56,ED2-JP,,0,0,0,,{\fad(360,360)}息をすることも　忘れてしまうほどの
Dialogue: 0,0:23:03.09,0:23:09.68,ED2-JP,,0,0,0,,{\fad(360,360)}記憶に焼けつく　悲しみさえもすべて
Dialogue: 0,0:23:10.02,0:23:14.70,ED2-JP,,0,0,0,,{\fad(360,360)}美しい音楽になって
Dialogue: 0,0:23:14.70,0:23:27.18,ED2-JP,,0,0,0,,{\fad(360,360)}意味を失うたびに僕を見つけてくれるいつでも
Dialogue: 0,0:22:10.64,0:22:17.26,ED2-CH,,0,0,0,,{\fad(360,360)}将透明的梦  轻轻拥入怀中
Dialogue: 0,0:22:17.68,0:22:23.76,ED2-CH,,0,0,0,,{\fad(360,360)}总会在瓦解的星辰上再见
Dialogue: 0,0:22:24.83,0:22:31.00,ED2-CH,,0,0,0,,{\fad(360,360)}降生于世间  就如同逐渐消逝
Dialogue: 0,0:22:31.84,0:22:37.96,ED2-CH,,0,0,0,,{\fad(360,360)}我思考着生命的去向
Dialogue: 0,0:22:38.67,0:22:45.47,ED2-CH,,0,0,0,,{\fad(360,360)}将无数次破碎的心收集起来
Dialogue: 0,0:22:45.47,0:22:55.06,ED2-CH,,0,0,0,,{\fad(360,360)}为了寻找微弱的光芒  依然仰望天空
Dialogue: 0,0:22:55.93,0:23:02.56,ED2-CH,,0,0,0,,{\fad(360,360)}让人伤心  甚至忘记呼吸
Dialogue: 0,0:23:03.09,0:23:09.68,ED2-CH,,0,0,0,,{\fad(360,360)}这份悲怆  烙印在记忆之中
Dialogue: 0,0:23:10.02,0:23:14.70,ED2-CH,,0,0,0,,{\fad(360,360)}将其化作美丽的音乐
Dialogue: 0,0:23:14.70,0:23:27.18,ED2-CH,,0,0,0,,{\fad(360,360)}每当失去意义  它总会帮我找回自己

### Application version

0.13 b4

### Where did you install the app from?

Sideloaded APK

### Device information

sony tv x90j

### Android version

android 10

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
The app does not support ASS/SSA. Make sure to enable transcoding so ffmpeg bakes in the subtitles.
