### ISSUE TITLE
Using libVLC to play crashes when the server video transcoding was complete.

### ISSUE THREAD

**Issue by shaino** [jellyfin/jellyfin-androidtv#1478]
### Describe the bug

I'm sure the crash happened when the server video transcoding was complete.

A similar issue already exists. The ver 0.13 update explicitly reproduces this issue.
I downgraded to 0.12.3 to reproduce issue. Although the Ver 0.12.3 of libVLC does not accurately display the progress, it can be seen from the server transcoding working time that the crash also occurs when the transcoding is complete.

Server logs and ffmpeg logs do not have reliable information. Playback with exoPlayer does not trigger such issues. Mobile clients also don't trigger such issues. But the mobile client does not have the libVLC option and can only be tested with a Web player.

### Application version

0.12.3,0.13

### Device information

android TV

### Android version

Android 5.1.1,Android 7,Android 9

### Jellyfin server version

10.8.0 alpha5

**Comment by mueslimak3r** [comment]
relevant server-side issue:
https://github.com/jellyfin/jellyfin/issues/6957

**Comment by shaino** [comment]
thx
