### ISSUE TITLE
while hearing music in the android app, opening another app and the sound gets distorsion.

### ISSUE THREAD

**Issue by linuxitomio** [jellyfin/jellyfin-androidtv#1481]
### Describe the bug

opening jellyfin app
play some music
sounds awesome
opening another time at the same time or the phone locks
sound becomes distorsioned and slower

### Application version

2,4,2

### Where did you install the app from?

Sideloaded APK

### Device information

sony xz2c

### Android version

android 11

### Jellyfin server version

last one stable

**Comment by linuxitomio** [comment]
The app is download from Fdroid

**Comment by nielsvanvelzen** [comment]
The TV app is not available on F-Droid and the version doesn't match. I think you intended to create a bug report for the mobile app. In which case this issue would be a duplicate of jellyfin/jellyfin-android#39.
