### ISSUE TITLE
refresh rate switching also change resolution

### ISSUE THREAD

**Issue by Arial-Z** [jellyfin/jellyfin-androidtv#1482]
### Describe the bug

Using the refresh rate switch on 4K display when playing 720p/1080p media, the refresh rate is switched to match the video as intended, but the display resolution also switch to 1080p which will block the needed upscale from the nvidia shield.

Tested 4K media working as intended (4K resolution and 23.976Hz)

Tested with both exoplayer and libVLC.

### Application version

0.13.0-beta.4

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Can you provide some details about the display you're using?

**Comment by mueslimak3r** [comment]
can you try side loading this build from #1484  (the apk is in the build artifacts after it finishes)
https://github.com/jellyfin/jellyfin-androidtv/actions/runs/1926392404

**Comment by Arial-Z** [comment]
Display is a LG55C1
Will test the APK today

**Comment by Arial-Z** [comment]
Build fixed the issue 23,976 FPS 1080p files play at 23.976Hz 4K

Don't know if i should create a new issue but i tested  some other files 24FPS and 25 FPS
25 FPS play at 50Hz whick is fine 1080p in beta4 and 4K in dev build
Vut 24 FPS play at 60Hz 1080p in beta4 and 4K in dev build

**Comment by mueslimak3r** [comment]
> 25 FPS play at 50Hz whick is fine 1080p in beta4 and 4K in dev build

Is that good (I'm not too familiar with what's ideal for variable refresh rate displays but 50Hz being 2x 25Hz is even frame pacing

>  24 FPS play at 60Hz 1080p in beta4 and 4K in dev build

Is the problem it being 60Hz or it being 4K? If the problem is it being 60Hz that's due to the logic that's supposed to handle 2:3 pull down (https://en.wikipedia.org/wiki/Three-two_pull_down#2:3) but idk if that's working as expected.

> Don't know if i should create a new issue

nope, I think this is all relevant to this issue.

**Comment by Arial-Z** [comment]
25 FPS at 50Hz is good yes it's a round multiple 1:2, for 24 FPS i would have expected the same, display at 24Hz or 48Hz because if it's playing at 60Hz with a pull down what the point of using the option to sync the display refresh rate with the video, 60Hz pull down is the normal behavior.

**Comment by mueslimak3r** [comment]
I'll adjust the logic for filtering the available display modes so that it prefers modes closest to the refresh rate of the video, and I'll reply with another test build.

Currently it looks like when the modes are given a score/rating, the higher the Hz the higher the score, which definitely isn't always right.

**Comment by mueslimak3r** [comment]
can you try this new build with those changes?
https://github.com/jellyfin/jellyfin-androidtv/actions/runs/1944245536

**Comment by Arial-Z** [comment]
I will test the build tonight.

I tested the Plex android TV app and they have 2 settings, refresh rate switching which sync refresh rate of the display with the max resolution and  "Resolution Switching" which match the display resolution to the media, likely to let the TV do the upscaling in case of using a android box bad at upscaling (or worst than your TV).

In future build it may be best to create a new option and let the choice to the user regarding resolution switching or not.

**Comment by Arial-Z** [comment]
Done some testing :
23.976FPS playing at 23.976Hz 4K => OK
24FPS playing at 24Hz 4K => OK
25FPS playing at 25Hz 4K => OK
Don't have 30Hz file so don't know but niche usage
50FPS playing at 50Hz 1080p but niche usage so don't know if you should change anything
Don't have 60Hz file so don't know but also niche

**Comment by mueslimak3r** [comment]
> 50FPS playing at 50Hz 1080p

If you look at the app logs with `adb logcat` or look up the specs for your TV you could check if your TV supports 50Hz at 4K. It's possible that it only supports 50Hz at 1080p

**Comment by Arial-Z** [comment]
TV support up to 4K 120Hz (HDMI 2.1) but shield only 4K 60Hz (HDMI 2.0b)

**Comment by mueslimak3r** [comment]
Can you collect some logs with `adb logcat` when playing the 50 fps video?

The logs will list all the display modes available to the app, and give information about which one is chosen, and the process that resulted in it being chosen.

It would be useful to make sure nothing weird is happening before moving forward with getting my changes reviewed.

**Comment by Arial-Z** [comment]
Related start at line 2380 i think
[adb.log](https://github.com/jellyfin/jellyfin-androidtv/files/8216965/adb.log)

**Comment by Arial-Z** [comment]
Fixed in 0.13.1

**Comment by KyleSanderson** [comment]
@Arial-Z this is a huge regression as I can't use my TV upscaler anymore. @mueslimak3r can you please revert.

**Comment by Arial-Z** [comment]
Yes as i said it might be a regression if you rely on the TV upscale instead of the atv box.
Maybe implement a new option without upscale for all content below 2160p or the other way around.
I have reopened the issue for better visibility

**Comment by mueslimak3r** [comment]
HI Arial-Z,
Would you be able to test this PR that updates the refresh rate switching logic?
For testing we need to make sure the new two options for refresh rate switching work: `scale on tv` and `scale on device`.
For `scale on TV`, it should behave similar to how it did when you opened your issue. The refresh rate should change and the resolution should match the media.

For `scale on device` it should behave as it did when you tested the previous PR. The refresh rate should change to match the media but the resolution should match your display.

PR:
https://github.com/jellyfin/jellyfin-androidtv/pull/1647

build artifacts:
https://github.com/jellyfin/jellyfin-androidtv/actions/runs/2232165464

**Comment by Arial-Z** [comment]
done some testing
Using scale on tv
4K 23.976 Hz > 4K 23.976 Hz
1080p 23.976 Hz > 1080p 23.976 Hz
1080p 50 Hz > 1080p 50 Hz
720p 23.976 Hz > 1080p 23.976 Hz
480p 23.976 Hz > 1080p 23.976 Hz
Likely okay as my TV support 720p but can't go lower than 50Hz on this resolution and don't support 480p at all i can't really test 720p and 480p

Using scale on device
4K 23.976 Hz > 4K 23.976 Hz
1080p 23.976 Hz > 4K 23.976 Hz
1080p 50 Hz > 1080p 50 Hz missmatch here
720p 23.976 Hz > 4K 23.976 Hz
480p 23.976 Hz > 4K 23.976 Hz
Appart from 1080p 50 Hz working as intended
