### ISSUE TITLE
Crash when Live TV playback starts

### ISSUE THREAD

**Issue by jelofsson** [jellyfin/jellyfin-androidtv#1488]
### Describe the bug

Recently started to crash when I try to view any channel in Live TV. Picture and sound is present just for an instant then the app crashes. I got beta version from playstore and guess it occured now with the latest beta release.

Didn't change any settings what I can remember, updated my jellyfin server aswell to see if that would fix it, without success.

1. Go to Live TV
2. Play any channel

### Application version

0.13.0-beta.4

### Device information

Nvidia Shield TV 2019

### Android version

Android 11

### Jellyfin server version

10.8.0

**Comment by mueslimak3r** [comment]
Does this happen with the app setting "preferred video player for live tv" set to auto, exoplayer, libVLC, or all of them?

**Comment by jelofsson** [comment]
> Does this happen with the app setting "preferred video player for live tv" set to auto, exoplayer, libVLC, or all of them?

It happens for auto and exoplayer, libVLC seems to work fine.
