### ISSUE TITLE
Image not smooth

### ISSUE THREAD

**Issue by alculete** [jellyfin/jellyfin-androidtv#149]
When playing videos images are not smooth, It is possible to see small pixel squares. On the web version, it doesn't happen

**Comment by alculete** [comment]
this is my transcoding configuration, running on docker 
![image](https://user-images.githubusercontent.com/2129497/64858370-71091500-d627-11e9-9a13-77e2d1d4ccb4.png)

**Comment by nielsvanvelzen** [comment]
Hi there! We've recently released a new version of Jellyfin and we think this issue is solved. Can you try it with the new version?

**Comment by alculete** [comment]
> Hi there! We've recently released a new version of Jellyfin and we think this issue is solved. Can you try it with the new version?

It is working fine now, thank you
