### ISSUE TITLE
Allow subtitles to be even smaller than size 18?

### ISSUE THREAD

**Issue by levihb** [jellyfin/jellyfin-androidtv#1492]
### Describe the feature you'd like

So the current limit on text size seems to be a minimum of 18? Is there a way we can change this much lower, as in <10? The subtitles are still very large on size 18, e.g. I think the normal size setting on Netflix is actually smaller, and the smallest size Netflix does is something I'm looking at.

Would this be a simple limit removal, or is there more at play here? I really think much smaller subs would be a good feature, especially on larger TVs.

**Comment by levihb** [comment]
Oh also what about the ability to change the colour of subtitles, or better yet make them semi-transparent? On Netflix etc we have them all set to be 50%+ transparent, because I've seen a few cases of burn-in from people with OLEDs who used white subtitles. Plus with some scenes (especially HDR) the subtitles are blinding.

**Comment by nielsvanvelzen** [comment]
I've lowered the minimum size to 10 in #1493. This already looks tiny so I'm not convinced to make it <10.

![image](https://user-images.githubusercontent.com/2305178/156878441-45b4f234-2205-4e61-b2b1-e4ae70593482.png)
_subtitle size 10_

**Comment by levihb** [comment]
> I've lowered the minimum size to 10 in #1493. This already looks tiny so I'm not convinced to make it <10.
> 
> ![image](https://user-images.githubusercontent.com/2305178/156878441-45b4f234-2205-4e61-b2b1-e4ae70593482.png) _subtitle size 10_

Thanks, that's at least a lot better. Why limit it to 10 though? If the users want to drop it lower, why not?

And honestly, that doesn't even look *that* small on my computer. It certainly wouldn't on a 65"+ TV.

**Comment by nielsvanvelzen** [comment]
This is on a 1080p emulator, if your device is bigger the size might be different because the subtitle size uses display pixels, which are scaled based on the physical size of a device and the size preferences from the system.
