### ISSUE TITLE
 TV shows seasons tab.

### ISSUE THREAD

**Issue by baburam0007** [jellyfin/jellyfin-androidtv#1498]
### Describe the feature you'd like

There are multiple seasons of the single tv show. Please show the season tab of those shows. Allow deleting the seasons from those tabs.

**Comment by sourpatched** [comment]
You'll like to be able to delete whole seasons from the server?

**Comment by baburam0007** [comment]
Yes. exactly.

**Comment by sourpatched** [comment]
I think it would probably be best to open the suggest on the Jellyfin server hub as I'm not sure if it's possible to add to ATV if it's not part of the server.

https://github.com/jellyfin/jellyfin

**Comment by sourpatched** [comment]
@nielsvanvelzen Can you please move this to Jellyfin or Jellyfin web?

**Comment by nielsvanvelzen** [comment]
Library management is not in the scope of the app. Closing as not planned.
