### ISSUE TITLE
Home section My Media (small) no effect

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#1499]
### Describe the feature you'd like

When changing the Home section setting from My Media to My Media (small), does not change anything on the home screen.

Reproduce:
Go into settings, select customization, scrolling down and select Home. Changing Home section 1 from My media to My Media (small). Close settings and home screen My Media icons still the same size. Restarted Jellyfin-TV, icons still same size.

Android-TV version 0.13-4

**Comment by nielsvanvelzen** [comment]
The Android TV app doesn't implement the small media tiles, it will show the normal ones instead. This works as intended.

**Comment by justinbyoung** [comment]
Does the option in preferences serve a purpose? Maybe it should be removed.

**Comment by nielsvanvelzen** [comment]
The home sections are synced across multiple clients. Some of them do implement the small media tiles and for those we need to keep the option.
