### ISSUE TITLE
Time when playing music not counting properly

### ISSUE THREAD

**Issue by alculete** [jellyfin/jellyfin-androidtv#150]
When playing music it appears the total time of a track and the time that its is taking at that moment but the time doesn't count the seconds. Sometimes the timer goes faster and some times it slows down but never counts a second properly

**Comment by thornbill** [comment]
We need to use an implementation similar to what is used in [ExoPlayer](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/PlayerControlView.java#L974) where the progress updates at scheduled based on the time until the next full second.
