### ISSUE TITLE
Play Store Data Safety Section

### ISSUE THREAD

**Issue by vaibhavantil1** [jellyfin/jellyfin-androidtv#1505]
### Describe the feature you'd like

Hi Team

In the recent Play Store policy, it will become mandatory for you to fill out the Data Safety Section. Since this is an OSS Android app, it will make sense to have it as a part of the repository as well.

I have run the scan using [my tool here](https://github.com/Privado-Inc/privado) on your repo, attached are
the scan results. I found the following:

5 data types
0 SDK.

If this is helpful, do use our free tool to generate Play Store Data Safety report: https://github.com/Privado-Inc/privado

Also, do share your feedback & thanks for the OSS app 😄

![image](https://user-images.githubusercontent.com/87804852/157164080-4ae70502-d243-4f42-904f-7663634d0818.png)
![image](https://user-images.githubusercontent.com/87804852/157164113-6d97a1a8-5e31-4ed4-a1e6-aa5120fd91e4.png)

**Comment by nielsvanvelzen** [comment]
We've now added the data safety information to the Google Play store for both apps.

**Comment by vaibhavantil2** [comment]
@nielsvanvelzen - did the screenshots help? Let me know if you would like to try the tool as well. Thanks for your revert.

**Comment by nielsvanvelzen** [comment]
We did not use your screenshots. The data was submitted by @anthonylavado manually. Coincidentally he was working on that when this issue was made.
