### ISSUE TITLE
Crashing During Playback

### ISSUE THREAD

**Issue by NickSica** [jellyfin/jellyfin-androidtv#1506]
### Describe the bug

1. Try to watch movie with subtitles using ExoPlayer
2. Crashes without fail
I have tried every version of the v1.3.0 beta without any success

### Logs

[tv_logs.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8212755/tv_logs.txt)

### Media info of the file

[media_info.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8212764/media_info.txt)

### Application version

0.13.0-beta.5

### Device information

Sony Bravia Google TV

### Android version

Android 10

### Jellyfin server version

10.8.0

**Comment by mueslimak3r** [comment]
Thanks for the logs. I'll look into this

**Comment by mueslimak3r** [comment]
do you have transcoding disabled for the user you experience this issue with?

**Comment by NickSica** [comment]
I haven't disabled transcoding, it's actually direct playing, I believe. All of the subtitles that I download are external and srt. Are pgs subtitles burned into the mkv?   

 The player kind of broke for awhile on me so I'm unsure which version but there was a version where it wasn't consistently crashing.

**Comment by mueslimak3r** [comment]
Can you take a screenshot of the media info in jellyfin web for that video? That will show all the external tracks too.

**Comment by NickSica** [comment]
Oh bazarr downloaded pgs subtitles for this movie. Where would I check for subtitle transcoding options?

**Comment by NickSica** [comment]
I might have found part of the issue jellyfin says PGSSUB while my folder on the server has a .srt extension.
![image](https://user-images.githubusercontent.com/26910401/157592493-f470ddc8-8868-43f1-9dbb-5016c1424605.png)
![image](https://user-images.githubusercontent.com/26910401/157592510-58792b97-e6b5-4683-b439-7d659fdfdb5c.png)

**Comment by mueslimak3r** [comment]
> Oh you're right, bazarr downloaded pgs subtitles for this movie. Where would I check for subtitle transcoding options?

afaik there isn't a setting to adjust.
In the past I thought the playback setting "allow subtitles extraction on the fly" could be disabled to force burn in for incompatible subs, but apparently that setting doesn't do anything.

I don't think this issue is caused by any misconfiguration on your end. It does look like a big in the app.

A screenshot of the media info in jellyfin web will help

**Comment by mueslimak3r** [comment]
It looks like your screenshot cut off part of the bottom row

**Comment by NickSica** [comment]
Should be fixed, looks like the PGSSUBS are the internal ones.

**Comment by mueslimak3r** [comment]
So the crash is happening because your TV/Android runs out of memory and kills the app. It's not clear whether this is due to the subtitles (and possible a memory leak related to displaying them) or maybe something else like the video bitrate being high.

Can you try this:
* open that same video in the web player and disable subtitles. You may need to play it, disable subs, close it, then play again to verify that subs are disabled by default.
* not that subtitles won't auto enable, try "force quitting" the android tv app to make sure it syncs with the server when it starts up, and then try to play the video again. Please capture adb logs for this too.

Hopefully that will result in the video playing on android tv without subs turning on, and we'll find out if it still crashes.

**Comment by NickSica** [comment]
It still crashed with no subtitles after force quitting the app.
[tv_logs.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8220653/tv_logs.txt)

**Comment by mueslimak3r** [comment]
can you provide the model # of your TV (I assume it has google tv built in) so I can look up the specs sheet?

Do you have any smaller videos/videos with a lower bitrate you can test with?

I see that when it's killed by the system to reclaim memory, it's using around 1.9GB

**Comment by NickSica** [comment]
Sony Bravia 4K VH2
I'm unsure if I have any lower bitrate videos, possibly since this hasn't been an issue with all of them. Would limiting the bitrate help?

**Comment by mueslimak3r** [comment]
Yeah try lowering the bitrate in the app settings to something like 10Mb/s and see if that changes anything. If it still crashes but just takes longer, that could be a memory leak

**Comment by NickSica** [comment]
I had it set to auto would that not automatically configure it so it uses the best setting to not crash? I'll try 10Mb/s and report back.

**Comment by NickSica** [comment]
It keeps crashing before I can even start the movie.

**Comment by mueslimak3r** [comment]
> It keeps crashing before I can even start the movie.

like it crashes before you click play?

Is this a different movie?

Try clearing the app's data in android settings

**Comment by NickSica** [comment]
Yeah it crashes when loading the movie details. It's the same movie.

**Comment by mueslimak3r** [comment]
> Yeah it crashes when loading the movie details. It's the same movie.

can you get some logs for that before you clear the app data?

**Comment by NickSica** [comment]
> > Yeah it crashes when loading the movie details. It's the same movie.
> 
> can you get some logs for that before you clear the app data?

I was going to say too late but it happened again after clearing the app data.

[tv_logs.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8220950/tv_logs.txt)

**Comment by mueslimak3r** [comment]
Can you try reinstalling the app and set the bitrate lower?

**Comment by NickSica** [comment]
It says that the player encountered too many errors and then exits back to the movie screen, if left on the movie screen for too long it crashes(maybe just open for too long since there may be a memory leak?).

**Comment by NickSica** [comment]
I looked through the logs and it seems like ffmpeg was throwing errors when the low power transcoding was turned on yesterday. Turning it off allows me to play videos and has the google tv app responding a little quicker. I'll see if it still crashes.

**Comment by NickSica** [comment]
It glitched out and froze the playback then while rewinding/fixing subtitles it crashed although I was able to watch for a bit beforehand.

[tv_logs_4.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8227732/tv_logs_4.txt)

**Comment by mueslimak3r** [comment]
Try rebooting your device, and then instead of `adb logcat` use `adb shell` and then run `top` from the shell. Run this before opening the jellyfin app, and take note of the memory use while you navigate the home screen of android and then maybe watch a YouTube video.

One you have a baseline of what's normal usage for your device open up the jellyfin app and see what the usage looks like in the menus, and then try playing something.

**Comment by NickSica** [comment]
Youtube and the main menu stayed around 30-60% CPU and about 15% RAM usage and while streaming youtube the CPU was usually around 75%. Jellyfin used a lot of CPU not really a consistent range, but it went higher than 200% and regularly used about 40% RAM in the menus. While streaming the CPU stayed around 30% and the RAM around 60%, I'll report back with more numbers if it crashes.

**Comment by NickSica** [comment]
It isn't crashing but it does skip back after a few minutes and the audio/video become out of sync. I think if I try to navigate the player too quickly it will crash.

**Comment by DavidFair** [comment]
I have the same TV, I'll try seeing if I can get the same video to test here too....

**Comment by DavidFair** [comment]
Sorry about the delay in testing this, got caught up in personal commitments 

So I've just tried the film, left it playing in the background and cycles through all the available subtitles (I have the same ones as NickSlca) but no crashes.
This means I can't reproduce it locally, looking at your logs there is something weird going on on your TV. You keep having the `sonysystemservice` start then die which isn't happening on my TV:

```
03-09 01:50:51.420  8651  8651 E AndroidRuntime: FATAL EXCEPTION: main
03-09 01:50:51.420  8651  8651 E AndroidRuntime: Process: com.sony.dtv.sonysystemservice, PID: 8651
03-09 01:50:51.420  8651  8651 E AndroidRuntime: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:932)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	... 1 more
03-09 01:50:51.420  8651  8651 E AndroidRuntime: Caused by: android.os.DeadObjectException
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:510)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at com.sony.dtv.sensingfusionservice.ISensingFusion$Stub$Proxy.removeAvailableListener(ISensingFusion.java:512)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at com.sony.dtv.sfslib.SensingFusionServiceImpl.removeAvailableListener(SensingFusionServiceImpl.kt:59)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at com.sony.dtv.sfslib.SensingFusionServiceImpl$serviceConnection$1.onServiceDisconnected(SensingFusionServiceImpl.kt:48)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1967)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1982)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
03-09 01:50:51.420  8651  8651 E AndroidRuntime: 	... 3 more
```

I wonder if there is a problem with a system service / component. It's probably a painful suggestion but if you're having general weirdness it might be worth factory resetting it. This might also explain the OOM if system processes keep starting and dying over and over again
