### ISSUE TITLE
Ends at time is not recalculated when playing the video at faster or slower speed

### ISSUE THREAD

**Issue by Dnkhatri** [jellyfin/jellyfin-androidtv#1509]
### Describe the bug

Ends at time is not recalculated when playing the video at faster or slower speed. 

### Application version

0.13 Beta 5

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield  2015

### Android version

Android 11

### Jellyfin server version

10.8 latest nightly

**Comment by nielsvanvelzen** [comment]
If anyone wants to work on this issue, there are two changes that need to happen to fix this issue:

1. Divide msLeft with the current playback speed in https://github.com/jellyfin/jellyfin-androidtv/blob/490f17019b9fb2c705c27e2988f6dc121e0b1be9/app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomPlaybackTransportControlGlue.java#L322-L329

2. Call setEndTime() when the playback speed changes

**Comment by DavidFair** [comment]
Whilst looking at an unrelated issue I found this, which should be very helpful: https://github.com/google/ExoPlayer/issues/9134
