### ISSUE TITLE
Grey screen

### ISSUE THREAD

**Issue by whity** [jellyfin/jellyfin-androidtv#151]
When I try to play any movie I always get an grey screen, but can hear the sound.
Already looked at the logs and nothing.
Any clue what could be the problem?

Thanks.

**Comment by arantes555** [comment]
Kinda the same thing here. For me, it actually kills the HDMI output somehow. The sound does play fine on Bluetooth headphones at the same time, but I got nothing on screen and my TV starts displaying the "No Input signal" warning.

Device: Freebox Mini v2

**Comment by nielsvanvelzen** [comment]
This might be fixed in the next version which will (hopefully) be released in the next week (no promises though). If you are familiar with Android development you can build the master branch yourself to try it out.

**Comment by nielsvanvelzen** [comment]
Hi there! We've recently released a new version of Jellyfin and we think this issue is solved. Can you try it with the new version?

**Comment by arantes555** [comment]
Hi there. I actually managed to work-around the issue with the previous version, by disabling the "auto refresh rate" option. Sorry I forgot to report it here

**Comment by nielsvanvelzen** [comment]
I'm glad you were able to fix it but this is not the behavior we expect. When auto refresh rate is enabled a black or grey screen should not happen.

Would you mind trying it again with the latest version and report if it's fixed or still broken?

**Comment by arantes555** [comment]
@nielsvanvelzen Just got around to testing it. When I re-enable the "auto refresh rate" option in the new version, I still get the disabled HDMI output whenever I start a video.. :( Sorry, it's still broken (but it's not really a big deal for me with the workaround)

**Comment by nielsvanvelzen** [comment]
Thanks for testing it. I will leave the issue open for now.

**Comment by whity** [comment]
Hello,

I can confirm that problem still persists, and that the work-around also works for me.
Thanks.
