### ISSUE TITLE
Add episode information icon to playback controls

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin-androidtv#1513]
### Describe the feature you'd like

We used to have this a few updates ago, I think it would be handy to have back. to read what the episode is about, you have to stop playback instead of checking the info icon and having the info pop up below.

**Comment by baburam0007** [comment]
I agree.

**Comment by sourpatched** [comment]
@mueslimak3r is this something that can be readded in the next update?

**Comment by nielsvanvelzen** [comment]
We did not have this feature in a previous release and it's unlikely to get added to the current playback code. Media information is still available in the details screen like it was before.

**Comment by sourpatched** [comment]
I remember there is was a information icon that gives episode overview, once press the info would display under the player controls. Maybe it's been missing for awhile.

Are you sure it's never been a feature?
