### ISSUE TITLE
Wrong aspect ratio on FireTV

### ISSUE THREAD

**Issue by zehnerGIT** [jellyfin/jellyfin-androidtv#152]
If I play anamorphic videos on my FireTV (2nd generation, the box not the stick), it ignores the aspect ratio and doesn't stretch the video, so all people are shown with eggheads.

Sample 1 (https://samples.ffmpeg.org/Matroska/anamorphic/starwars10MB-1.mkv) plays OK, but Sample 2 (https://samples.ffmpeg.org/Matroska/anamorphic/starwars10MB-2.mkv) shows the egg heads.

Both files play OK with the web client or an installation of the client on my tablet and jellyfin reports for both files an aspect ratio of 2.35:1 (but I have the same problem for all my DVD rips, where jellyfin reports an aspect ratio of 16:9).

The manual setting in the OSD works, but this setting has to be done again for every movie or episode

Two smaller things: 
- I can see a refresh rate setting on my tablet, but not on my FireTV, so all videos are played with the default refresh rate (I think only 3rd generation onwards supports refresh rate switching officially, but at least with MrMC it's possible on my box)
- The Home screen on my tablet doesn't rotate, it's always in landscape mode. I've to enter a library or another submenu point to switch to portrait mode.

Apart from that, the client looks very promising, it's really usable for a first version

**Comment by anthonylavado** [comment]
@ZehnerGIT A quick question - does the VLC option in the settings make any difference?

**Comment by zehnerGIT** [comment]
The aspect ratio is correct with VLC as external player, without further configuration.

**Comment by onemico** [comment]
Nothing to add except I am seeing the same bug and I thought it was my video source at first and spent a long time re-encoding it only to find it doing the same again, but external playing worked fine. What a waste of time :)

**Comment by jtambasco** [comment]
I experience the same issue: 4K firestick does not display the correct aspect ratio.

Actually using the latest version of VLC doesn't _always_ work (depends on the encoding, x265 seems to suffer more)...  Incidentally, the [bug](https://code.videolan.org/videolan/vlc-android/issues/772) has been reported.

Sideloading Mx Player works perfectly though.

**Comment by zehnerGIT** [comment]
Bug can be closed from my side. I've checked version 11.1 and the aspect ratio is correct with the new exo version.
Still no refresh rate switching, but that should be a limitation of my 2nd generation device

**Comment by nielsvanvelzen** [comment]
Thanks for letting us know. I will close this issue, if anyone else still experiences this problem please leave a comment and we will re-open it.
