### ISSUE TITLE
Playback sound crashed

### ISSUE THREAD

**Issue by TheBarzFR** [jellyfin/jellyfin-androidtv#1526]
### Describe the bug

Hello
I have a problem with the latest stable version of Jellyfin running on windows 10 (latest patches included).
After about 5 minutes playing list of aac files, sound going down. But the playback continues nonetheless.
When stopping/resuming playback, still no sound. If I quit Jellfin and start playing again, the sound works. But after a few minutes sound going down again.
Any idea ?

### Logs

```shell
No crash log reported
```

### FFmpeg logs

```shell
None
```

### Media info of the file

```shell
aac files
```

### Application version

None

### Device information

Shuttle DH410

### Android version

Windows 10

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
Your issue is missing information that is needed for it to be triaged (we need to know the app version).

**Comment by TheBarzFR** [comment]
Hi
I’m using the package included the server.
So I’m don’t using external app. Only the web app.
Do I need to put the same version in this case ?

**Comment by nielsvanvelzen** [comment]
This is the repository for the Android TV app. I'm closing the issue since your issue is not about the app.
