### ISSUE TITLE
Connection Issue: SSL Handshake Failure

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin-androidtv#1530]
### Describe the bug

Jellyfin running on HTTPS, the app can not connect to it.
0.13

### Logs

```shell
I don't have access to the logs.
```

### Application version

0.13

### Where did you install the app from?

Sideloaded APK

### Device information

Shield

### Android version

Android 10

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Did you encounter the same issue with 0.12?

**Comment by sourpatched** [comment]
Was never logged out, so I am unsure. I'm using port 8096 (http) for the app to connect.
I've also check the android phone app and it doesn't connect on port 8920 as well.

I've got a watch on this so any alpha/beta and I'll side load to test.

**Comment by nielsvanvelzen** [comment]
What reverse proxy are you using? And is the certificate chain correctly configured in your reverse proxy?

**Comment by sourpatched** [comment]
No reverse proxy, Jellyfin web works well with HTTPS.

Details: TLS_AES_256_GCM_SHA384,256 bit keys

Does the app support V3 SSL and TLS 1.3?

**Comment by nielsvanvelzen** [comment]
HTTPS support is handled by the system. Android 12 supports TLS 1.3 as far as I'm aware.
I'll need to see the SSL error from the client logs to help any further.

**Comment by sourpatched** [comment]
Could take a week to get the logs, as getting the logs over WIFI isn't as easy as I though and have to get a male USB.

**Comment by nielsvanvelzen** [comment]
> I am my own CA, could that be the issues?

Yes, definitely. Did you add the certificate to the system trust store?

**Comment by sourpatched** [comment]
Trying to upload it now. I believe it has to be the pem file. I thought I could upload it then install it that way but I think it has to be install with the abt command?

**Comment by sourpatched** [comment]
I have installed the root ca to android phone and Jellyfin app connected, ATV isn't as easy to install so that can wait.

Would this be something to note in the docs?

**Comment by nielsvanvelzen** [comment]
It's well known that a self signed certificate is not trusted by default so I don't think we need to update the documentation.

Closing the issue as fixed.
