### ISSUE TITLE
 v0.13.0-release Playback Error using Live TV

### ISSUE THREAD

**Issue by gdthomas** [jellyfin/jellyfin-androidtv#1538]
### Describe the bug

1. Using Onn w/ latest fw/sw
2. Installed jellyfin-androidtv-v0.13.0-beta.4-release.apk
3. Connect to JF server v10.7.7 configured to use M3U Tuner
4. Play a Live TV channel and it works fine
5. Upgrade Onn to Installed jellyfin-androidtv-v0.13.0-beta.5-release.apk
6. Connect to same JF server
7. Play a Live TV channel and it says playback error and keeps retrying w/o success
8. Upgrade to v0.13.0-release and have the same problem
9. Revert back to v0.13.0-beta.4 and everything works fine

### Application version

0.13.0

### Where did you install the app from?

Sideloaded APK

### Device information

Onn 4K TV

### Android version

Android 10

### Jellyfin server version

10.7.7

**Comment by sourpatched** [comment]
There are a few settings to change for it to work,  LibVLC as the player and changing audio output made it work before 0.13 release. The new update "disabled" transcoding live tv.

**Comment by mueslimak3r** [comment]
Can you provide logs from jellyfin (server) and ffmpeg logs when you attempt to transcode live tv? make sure to redact sensitive info before uploading them.

Can you try disabling "Allow encoding in HEVC format" in the Playback settings in the Jellyfin dashboard?

**Comment by sourpatched** [comment]
No encoding, audio out of sync and without direct tv ticked in settings I can not play live tv.
FFMPEG log (server running 10.8.0) 

/videos/06a557cd-9ab5-ddcd-dd99-35e361b24257/stream.mkv

{"Protocol":1,"Id":"a9239a0423012282b76b031ede2a2344","Path":"Link to Live tv","EncoderPath":null,"EncoderProtocol":null,"Type":0,"Container":"hls","Size":1407,"Name":null,"IsRemote":true,"ETag":null,"RunTimeTicks":null,"ReadAtNativeFramerate":false,"IgnoreDts":true,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":true,"RequiresOpening":true,"OpenToken":null,"RequiresClosing":true,"LiveStreamId":"a17c75760a04e99b68cf766e11316e1c_09efa0d56b934a82adec00a87b837fb0_a9239a0423012282b76b031ede2a2344","BufferMs":null,"RequiresLooping":false,"SupportsProbing":true,"VideoType":null,"IsoType":null,"Video3DFormat":null,"MediaStreams":[{"Codec":"h264","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":null,"Title":null,"VideoRange":"SDR","LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"720p H264 SDR","NalLengthSize":"0","IsInterlaced":false,"IsAVC":null,"ChannelLayout":null,"BitRate":2000000,"BitDepth":8,"RefFrames":1,"PacketLength":null,"Channels":null,"SampleRate":null,"IsDefault":false,"IsForced":false,"Height":576,"Width":1024,"AverageFrameRate":25,"RealFrameRate":25,"Profile":"Main","Type":1,"AspectRatio":"16:9","Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":"yuv420p","Level":31,"IsAnamorphic":false},{"Codec":"aac","CodecTag":null,"Language":null,"ColorRange":null,"ColorSpace":null,"ColorTransfer":null,"ColorPrimaries":null,"Comment":null,"TimeBase":"1/90000","CodecTimeBase":null,"Title":null,"VideoRange":null,"LocalizedUndefined":null,"LocalizedDefault":null,"LocalizedForced":null,"LocalizedExternal":null,"DisplayTitle":"AAC - Stereo","NalLengthSize":null,"IsInterlaced":false,"IsAVC":null,"ChannelLayout":"stereo","BitRate":192000,"BitDepth":null,"RefFrames":null,"PacketLength":null,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Height":null,"Width":null,"AverageFrameRate":null,"RealFrameRate":null,"Profile":"LC","Type":0,"AspectRatio":null,"Index":-1,"Score":null,"IsExternal":false,"DeliveryMethod":null,"DeliveryUrl":null,"IsExternalUrl":null,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Path":null,"PixelFormat":null,"Level":0,"IsAnamorphic":null}],"MediaAttachments":[],"Formats":[],"Bitrate":2192000,"Timestamp":null,"RequiredHttpHeaders":{"User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.3538.77 Safari/537.36"},"TranscodingUrl":null,"TranscodingSubProtocol":null,"TranscodingContainer":null,"AnalyzeDurationMs":3000,"DefaultAudioStreamIndex":null,"DefaultSubtitleStreamIndex":null}

/usr/lib/jellyfin-ffmpeg/ffmpeg -analyzeduration 3000000 -user_agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.3538.77 Safari/537.36" -fflags +igndts+genpts  -i "Link to Live tv" -sn -codec:v:0 copy -fflags +genpts -map_metadata -1 -map_chapters -1 -threads 0 -codec:a:0 copy -y "/var/lib/jellyfin/transcodes/793a9de39b7da71e0b17715396311382.mkv"


ffmpeg version 4.4.1-Jellyfin Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --arch=amd64 --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-vdpau --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[hls @ 0x564dbdb06500] Skip ('#EXT-X-VERSION:3')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-INDEPENDENT-SEGMENTS')
[hls @ 0x564dbdb06500] Can't support the subtitle(uri: hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_7_0.m3u8)
[hls @ 0x564dbdb06500] Opening 'Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_44.m3u8' for reading
[hls @ 0x564dbdb06500] Skip ('#EXT-X-VERSION:3')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:52.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:58.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:04.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:10.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:16.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:22.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:28.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:34.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:40.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:46.440Z')
[https @ 0x564dbddfc880] Opening 'Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_45.m3u8' for reading
[hls @ 0x564dbdb06500] Skip ('#EXT-X-VERSION:3')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:52.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:58.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:04.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:10.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:16.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:22.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:28.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:34.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:40.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:46.440Z')
[https @ 0x564dbddfc880] Opening 'Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_46.m3u8' for reading
[hls @ 0x564dbdb06500] Skip ('#EXT-X-VERSION:3')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:52.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:58.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:04.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:10.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:16.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:22.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:28.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:34.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:40.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:46.440Z')
[https @ 0x564dbddfc880] Opening 'Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_47.m3u8' for reading
[hls @ 0x564dbdb06500] Skip ('#EXT-X-VERSION:3')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:52.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:58.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:04.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:10.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:16.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:22.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:28.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:34.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:40.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:46.440Z')
[hls @ 0x564dbdb06500] Opening 'https://gvqzylrx77.execute-api.ap-southeast-2.amazonaws.com/EkeStage/client/EHLS/25e9a7c1-641e-41f6-8840-27af4c8026f4' for reading
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_44_12391621.ts?m=1615428791' for reading
[hls @ 0x564dbdb06500] Opening 'https://gvqzylrx77.execute-api.ap-southeast-2.amazonaws.com/EkeStage/client/EHLS/25e9a7c1-641e-41f6-8840-27af4c8026f4' for reading
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_45_12391621.ts?m=1615428791' for reading
[hls @ 0x564dbdb06500] Opening 'https://gvqzylrx77.execute-api.ap-southeast-2.amazonaws.com/EkeStage/client/EHLS/25e9a7c1-641e-41f6-8840-27af4c8026f4' for reading
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_46_12391621.ts?m=1615428791' for reading
[hls @ 0x564dbdb06500] Opening 'https://gvqzylrx77.execute-api.ap-southeast-2.amazonaws.com/EkeStage/client/EHLS/25e9a7c1-641e-41f6-8840-27af4c8026f4' for reading
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_47_12391621.ts?m=1615428791' for reading
Input #0, hls, from 'Link to Live tv':
  Duration: N/A, start: 15295.017600, bitrate: N/A
  Program 0 
    Metadata:
      variant_bitrate : 1910620
  Stream #0:0: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1024x576 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 1910620
  Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 1910620
  Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 1910620
  Stream #0:3: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 1910620
  Program 1 
    Metadata:
      variant_bitrate : 994254
  Stream #0:4: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 994254
  Stream #0:5: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 994254
  Stream #0:6: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 994254
  Stream #0:7: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 994254
  Program 2 
    Metadata:
      variant_bitrate : 737286
  Stream #0:8: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 512x288 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 737286
  Stream #0:9: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 737286
  Stream #0:10: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 737286
  Stream #0:11: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 737286
  Program 3 
    Metadata:
      variant_bitrate : 4806436
  Stream #0:12: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 4806436
  Stream #0:13: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 4806436
  Stream #0:14: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 4806436
  Stream #0:15: Data: timed_id3 (ID3  / 0x20334449)
    Metadata:
      variant_bitrate : 4806436
Output #0, matroska, to '/var/lib/jellyfin/transcodes/793a9de39b7da71e0b17715396311382.mkv':
  Metadata:
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (Main) (H264 / 0x34363248), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 25 tbr, 1k tbn, 90k tbc
  Stream #0:1: Audio: aac (LC) ([255][0][0][0] / 0x00FF), 48000 Hz, stereo, fltp
Stream mapping:
  Stream #0:12 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=    1 fps=0.0 q=-1.0 size=       1kB time=00:00:00.00 bitrate=N/A speed=N/A    
frame=   91 fps=0.0 q=-1.0 size=       1kB time=00:00:03.55 bitrate=   2.3kbits/s speed=6.71x    
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_44_12391622.ts?m=1615428791' for reading
frame=  148 fps=129 q=-1.0 size=     768kB time=00:00:05.99 bitrate=1049.5kbits/s speed=5.21x    
[hls @ 0x564dbdb06500] No longer receiving playlist 1 ('Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_45.m3u8')
[hls @ 0x564dbdb06500] No longer receiving playlist 2 ('Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_46.m3u8')
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_47_12391622.ts?m=1615428791' for reading
frame=  150 fps= 86 q=-1.0 size=     768kB time=00:00:05.99 bitrate=1049.5kbits/s speed=3.43x    
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_44_12391623.ts?m=1615428791' for reading
frame=  298 fps=118 q=-1.0 size=    2048kB time=00:00:11.98 bitrate=1399.4kbits/s speed=4.76x    
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_47_12391623.ts?m=1615428791' for reading
frame=  300 fps= 91 q=-1.0 size=    2048kB time=00:00:12.33 bitrate=1360.6kbits/s speed=3.74x    
[https @ 0x564dbddfc880] Opening 'Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_44.m3u8' for reading
[hls @ 0x564dbdb06500] Skip ('#EXT-X-VERSION:3')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:58.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:04.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:10.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:16.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:22.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:28.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:34.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:40.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:46.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:52.440Z')
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_44_12391624.ts?m=1615428791' for reading
frame=  448 fps=107 q=-1.0 size=    3072kB time=00:00:17.98 bitrate=1399.3kbits/s speed= 4.3x    
[https @ 0x564dbddfc880] Opening 'Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_47.m3u8' for reading
[hls @ 0x564dbdb06500] Skip ('#EXT-X-VERSION:3')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:32:58.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:04.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:10.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:16.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:22.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:28.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:34.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:40.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:46.440Z')
[hls @ 0x564dbdb06500] Skip ('#EXT-X-PROGRAM-DATE-TIME:2022-03-27T21:33:52.440Z')
[hls @ 0x564dbdb06500] Opening 'crypto+Link to Live tv/hdntl=exp=1648503244~acl=%2f*~data=hdntl~hmac=28d06d408475b5f682fd2117badafbffd391b79e2d89d2fed590d063085b8d4c/index_47_12391624.ts?m=1615428791' for reading

**Comment by sourpatched** [comment]
@mueslimak3r @gdthomas 
I believe that v0.14.0 fixes this
