### ISSUE TITLE
User is forced to log in each time when using Nightly

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin-androidtv#155]
The user is forced to log in every time the ATV app is open when using the latest nightly release even when option to always login as that user is selected.  Expected behavior is to ask for password the first time and not prompt the user to login in if the always login as that user option is enabled.

@thornbill has confirmed this to be an issue on his system as well.

**Comment by ddurdle** [comment]
Same issue here.  But the notes for the nightly build indicates the Android TV is broken on nightly -- playback generally works.

**Comment by dinki** [comment]
Seems that https://github.com/jellyfin/jellyfin/pull/1785 has fixed this issue for me.  Closing the issue.  Thanks @dkanada !

**Comment by ddurdle** [comment]
Working great on Firestick 4k.  Great work guys!  @dkanada
