### ISSUE TITLE
Issues with the flows involving Next Up 

### ISSUE THREAD

**Issue by zilexa** [jellyfin/jellyfin-androidtv#1558]
### Describe the bug

Device: ShieldTV Pro 2019 fully up to date. 
Jellyfin 13.

Several issues with "Next up":
A.
1. Play an episode 
2. After a few seconds or minutes, hit Back button to stop playback. 

**Expected: to see the "continue from ..." screen, to allow you to continue watching.**

**Actual: shows "Play Next". When you click this, it says it cannot find next episode.** 

Workaround: go down to the episode list, select the episode, now the "continue from..." _is_ shown.

Logically, after you stop playback, the main option you expect is start playback again. 
It does not make sense your main option does not work and you have to navigate a little to continue playback. 
The only issue here is that the wrong screen is shown when you leave/interrupt playback. 

B.
1. Open an unwatched TV show season.
2. Watch episode 1.
3. (Probably not necessary) Repeat 1 and 2 for multiple shows.
4. Go watch something else or close Jellyfin.
5. Open Jellyfin.
6. Notice for some shows you will see Next Up showing ep2, ep4, ep5... 
Issue: episode 3 is missing. 
Workaround: This episode is shown when you go to the TV show season, listing all episodes. Clearly the issue is with Next Up. 

Proof, in this case Next Up shows ep6 and ep11 while ep7-10 also never have been watched: https://ibb.co/YhyDzBS
But if you scroll down and open the season, you see 6,7,8,9,10,11 correctly, unwatched: https://ibb.co/bbT8gY2

C.
1. Go to "Shows"
2. Set filter to only list Unwatched items. 
3. Select a show but remember the # that is shown, for example 3 unwatched items.
4. Watch an unwatched episode. 
5. After it's finished and you are automatically back in Jellyfin next up screen, hit back button to go back to "Shows.
6. Notice the show you just watched still shows "3" instead of "2". 

Workaround: go back further, leaving Shows. Now go back to Shows. The number is correct, 2. 

### Application version

0.13.0

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019 

### Android version

Android 11

### Jellyfin server version

10.7.7

**Comment by mueslimak3r** [comment]
By any chance are the episodes skipped by "next up" combo episodes? eg: The Office Season 04 Episode 01-02, Episode 03-04, etc where one video file is actually 2 episodes

**Comment by zilexa** [comment]
Nope, all separate files. It also happens for well known series like Chicago Fire, Chicago Med etc.

**Comment by zilexa** [comment]
Jellyfin still shows "Play Next" instead of "Continue Watching" when you interrupt playback :( 
It's such a trivial thing, easy to reproduce and fix, since it just needs to show the other window.. thats all.

**Comment by zilexa** [comment]
This is just unbelievable. Such an obvious bug or issue in flow design.
