### ISSUE TITLE
External subtitles (.srt) display as left-aligned instead of centered

### ISSUE THREAD

**Issue by Nocifer** [jellyfin/jellyfin-androidtv#1565]
### Describe the bug

As per title, when using external subtitles (.srt) they are displayed as left-aligned instead of centered. Neither the browser client nor Jellyfin Media Player have this issue. Case in point:

Android TV:
![PXL_20220326_144457597](https://user-images.githubusercontent.com/6195422/160245020-1521d7cb-2273-4194-a2d9-b7c144873a15.jpg)

Jellyfin Media Player:
![2022-03-26_16:43:31_Jellyfin Media Player](https://user-images.githubusercontent.com/6195422/160245048-cb42702d-cb5a-4963-b056-99ebc7fecd50.png)

Browser (Firefox):
![2022-03-26_16:43:42_Westworld — Mozilla Firefox](https://user-images.githubusercontent.com/6195422/160245064-460b6306-fddd-4294-9755-74039e3aa85d.png)

Also, the subtitles are displayed with a slight (~500ms) delay; none of the other clients exhibit this behavior. This may be an entirely different issue, but it also may hint at some common cause underlying both issues, so I'm including it here.

### Application version

0.13.0

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire TV Stick 4K

### Android version

Fire OS 6

### Jellyfin server version

10.7.7

**Comment by mikewesten** [comment]
So someone wrote a fix for this issue, but the 'black background behind subtitles' feature remained left-aligned, so the fix was then revoked in favor of restoring alignment compatibility with the left-aligned black background? Why not center-align both the subtitle text and the subtitle black background. This is possible to do, no?

**Comment by nielsvanvelzen** [comment]
It should be possible but nobody attempted to do that yet.
