### ISSUE TITLE
Please add category to manifest for launcher sorting

### ISSUE THREAD

**Issue by Quackdoc** [jellyfin/jellyfin-androidtv#1578]
### Describe the feature you'd like

Add `android:appCategory="video"`

adding `android:appCategory="video"` to android manifest will allow launchers to sort it into the Video category in supported launchers, currently it get's added to other apps depending on the launcher, one such example is leanback launcher fork by tsynik (https://github.com/tsynik/LeanbackLauncher). 

it would be nice to have this sorted by default for launchers that do not allow sorting, or even as a mild convenience.

**Comment by nielsvanvelzen** [comment]
Fixed for 0.13.3
