### ISSUE TITLE
Media Details [Embedded Image]

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin-androidtv#1580]
### Describe the feature you'd like

0.13 bring us media details at the bottom of each episode, is it possible to show what the embedded image is?

**Comment by nielsvanvelzen** [comment]
I'm not sure what your request is. Can you explain it more detailed?

**Comment by sourpatched** [comment]
In the media details there are 4 cards, Video, audio,subtitles and imbedded image. These cards tell you about the media file such as codec, profile level, bitrate but the imbedded image card is always blank. Could the imbedded image card show the image?

**Comment by sourpatched** [comment]
I should have asked if the embedded image info area is suppose to be blank before I asked if it could be filled by the image?

At the bottom of the episode is details about the file, embedded image is blank.

**Comment by nielsvanvelzen** [comment]
The media details are a developer feature, only shown when debug options (under the advanced preferences section) is enabled. They are incomplete, not translated and buggy. It should not display images.

**Comment by sourpatched** [comment]
Thanks for clearing that up.
