### ISSUE TITLE
banners still miss parts after update to 0.13.2

### ISSUE THREAD

**Issue by zehnerGIT** [jellyfin/jellyfin-androidtv#1589]
### Describe the bug

Now that 0.13.2 is back in the amazon store, I've updated to 0.13.2. 

I've to reopen issue #1548 , because the view is unchanged (compared to 0.13.0), even after deleting the cache and reinstallation of the client, banners are still cut off. As a sidenote I use the vertical view for banners, not the horizontal.

Perhaps the problem is not the aspect ratio (as mentioned in #1551)? 
Since 0.13 the banner view uses less width. Before it uses about 95% of the width, now the margins on the left and right screen side are wider, it uses only 90% of the width (in vertical view). And to be honest, it looked way better with 95%

### Application version

0.13.2

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireTV Cube V2

### Android version

FireOS 7.2.4.2

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Thanks for reporting back. Maybe the aspect ratio wasn't the issue indeed. I don't have any banners in my library so it's a bit difficult to fix. Can you share one of your banners so I can test with that? Also, which plugin did you use to get the banners?

**Comment by zehnerGIT** [comment]
Problematic are banners with text on the left or the right 
https://images.fanart.tv/fanart/reacher-61f57d263c408.jpg

Jellyfin-web shows everything, but on my firetv the leading "R" is almost completely cut off
