### ISSUE TITLE
App's suddenly turned bright red

### ISSUE THREAD

**Issue by fmchris10** [jellyfin/jellyfin-androidtv#1592]
### Describe the bug

Suddenly, the background of the latest release from Google Play has turned s bright red. I have cleared my cache, re-installed, turned off my device.

It seems something at the remote end to me.

Here's s picture
https://i.imgur.com/bF7E63H.jpg

### Application version

0.13.2

### Where did you install the app from?

Google Play

### Device information

T9 Android Box (generic Chinese model)

### Android version

Android 8.1

### Jellyfin server version

10.7.7

**Comment by fmchris10** [comment]
I should note the background remains red everywhere that doesn't contain a backdrop image.

Text for: Next Up, Latest Categories is shown as black.

The indicator that shows the amount of episodes is also red, with with text - instead of blue.

**Comment by mueslimak3r** [comment]
It's a seasonal theme for April fool's day. It's inspired by the Windows Hot Dog Stand color scheme. You can disable seasonal themes in the app settings

https://blog.codinghorror.com/a-tribute-to-the-windows-31-hot-dog-stand-color-scheme/

**Comment by fmchris10** [comment]
🤣🤣🤣 oh dear, Jellyfin has caught me early it seems.

**Comment by mueslimak3r** [comment]
I'm gonna keep this open since there will probably be more people wondering what's going on

**Comment by sourpatched** [comment]
I thought I broke something this morning. I do like the red controls and playback bar. Could add colour theming to the app?

**Comment by jerry-ch-issue** [comment]
> It's a seasonal theme for April fool's day. It's inspired by the Windows Hot Dog Stand color scheme. You can disable seasonal themes in the app settings
> 
> https://blog.codinghorror.com/a-tribute-to-the-windows-31-hot-dog-stand-color-scheme/

lol, you guys got me. googled a lot. why didn't I come here first.

**Comment by chicungunya** [comment]
OMG I was like WTF my server has been hacked. You got me! 🤣🤣

**Comment by crobibero** [comment]
I knew it was coming and was still surprised at the theme!

Jeff is love, Jeff is life.

**Comment by KoboDev** [comment]
> It's a seasonal theme for April fool's day. It's inspired by the Windows Hot Dog Stand color scheme. You can disable seasonal themes in the app settings
> 
> https://blog.codinghorror.com/a-tribute-to-the-windows-31-hot-dog-stand-color-scheme/

Jump off a cliff, disabling it requires more than just toggling it.
You also need to change the normal theme, and sometimes restart the client itself.
Again, im more pissed than getting pranked.
Especially since people had this happen since a couple days back.

**Comment by nielsvanvelzen** [comment]
I hope everyone had a great April fools day! With the day being over in most time zones I'll close this issue. See you again next year 😉.
