### ISSUE TITLE
[Feature request] Quick Connect

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [jellyfin/jellyfin-androidtv#1612]
### Describe the feature you'd like

Have quick connect option on the android tv, instead of using user/password. Provide a pin on the android tv and enter it in the web portal on the browser.

**Comment by sourpatched** [comment]
I think it is on the to-do list.

**Comment by nielsvanvelzen** [comment]
Yes this is on my list for 0.14. I wanted to add this before but the API in 10.7 wasn't that great so I had to wait for 10.8 (which revamps the API and makes Quick Connect much simpler).

**Comment by sourpatched** [comment]
@Cookie-Monster-Coder 0.14.0 supports Quick Connect but needs Jellyfin 10.8.1.

**Comment by Cookie-Monster-Coder** [comment]
Thank you so much! ❤
