### ISSUE TITLE
removing the client from the list of 'devices' authenticated with the server causes the app to always crash on launch

### ISSUE THREAD

**Issue by mueslimak3r** [jellyfin/jellyfin-androidtv#1621]
### Describe the bug

**Steps to reproduce**
2) install the latest build off master (commit: 0d12a149f84fc31148d39a04f665421850b389c8)
1) sign into a jellyfin server and keep the app open
2) in the web client find the android tv client in the dashboard under 'devices' and delete it
3) back out of the android tv app and then click on it again
4) the app will crash

**Context for the logs**
1) the app is force stopped
2) start logging
3) open the app and let it crash back to the launcher
4) stop logging

### Logs

```shell
client logs:
https://pastebin.com/dAJACb15
```

### Application version

dev build off master

### Where did you install the app from?

Sideloaded APK

### Device information

Chromecast w/ Google TV

### Android version

10

### Jellyfin server version

10.8 beta 1

**Comment by nielsvanvelzen** [comment]
I suspect this issue also applies for 0.13.z. We don't check if the token is still "active" when the app starts. When the server sends a 401 we don't really handle it right now.
I guess adding a check during startup (sessionrepository/apibinder) should "fix" it.

**Comment by nielsvanvelzen** [comment]
Can confirm this issue does not happen to 0.13.z.

**Comment by mikewesten** [comment]
I think I may be experiencing the same issue. I can't definitively confirm if it's directly related to removal of client from the device list, though it might well be.
Periodically an account will become inoperable on the Fire Stick client, meaning the app just crashes and closes after I enter it's (correct login credentials) and click login. This occurs after a period of time on accounts which are set up to login automatically. The only workaround I've found so far is to create a brand new user account when this happens. And the new user account cannot be a username that was used previously. It has to be brand new credentials or it won't work. I'm on my 5 or 6th new user account after months of this ongoing issue. I don't know how to track the issue since I'm not skilled enough to do so.

**Comment by mueslimak3r** [comment]
> I think I may be experiencing the same issue. I can't definitively confirm if it's directly related to removal of client from the device list, though it might well be.
> Periodically an account will become inoperable on the Fire Stick client, meaning the app just crashes and closes after I enter it's (correct login credentials) and click login. This occurs after a period of time on accounts which are set up to login automatically. The only workaround I've found so far is to create a brand new user account when this happens. And the new user account cannot be a username that was used previously. It has to be brand new credentials or it won't work. I'm on my 5 or 6th new user account after months of this ongoing issue. I don't know how to track the issue since I'm not skilled enough to do so.

Instead of making a new account, what worked for me was just clearing the "app data" in my android system settings or reinstalling the app.

**Comment by nielsvanvelzen** [comment]
@mikewesten I don't recommend running our master branch on your device, especially right now with a bunch of refactors getting merged which can cause a bunch of new bugs.

**Comment by mikewesten** [comment]
> > I think I may be experiencing the same issue. I can't definitively confirm if it's directly related to removal of client from the device list, though it might well be.
> > Periodically an account will become inoperable on the Fire Stick client, meaning the app just crashes and closes after I enter it's (correct login credentials) and click login. This occurs after a period of time on accounts which are set up to login automatically. The only workaround I've found so far is to create a brand new user account when this happens. And the new user account cannot be a username that was used previously. It has to be brand new credentials or it won't work. I'm on my 5 or 6th new user account after months of this ongoing issue. I don't know how to track the issue since I'm not skilled enough to do so.
> 
> Instead of making a new account, what worked for me was just clearing the "app data" in my android system settings. This basically resets the app as if you've reinstalled it

Unfortunately this does not fix it, and neither does a fresh install.



> @mikewesten I don't recommend running our master branch on your device, especially right now with a bunch of refactors getting merged which can cause a bunch of new bugs.

This has been occurring since version 12.3 and up, and it has persisted regardless of which release I'm using. I mainly stick with stable releases.
