### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by robingroppe** [jellyfin/jellyfin-androidtv#1627]
### Describe the bug

Upgraded a TV to 0.13.3 from 0.13beta5, I believe.
I am unable to connect to my otherwise working server, is there any issue related to this problem?
The new #1340 suggests that the server isnt responding at all, but it definetly is in a browser. 
I am running nginx-proxy-manager and my dns record is pointing to a cname which finally leads to a A record. 

### Application version

0.13.3

### Where did you install the app from?

Google Play

### Device information

Phillips Smart TV

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
Can you explain how your SSL configuration works, what happens when you connect to the server from our mobile Android app, the browser on an Android phone etc.
Perhaps you could share the logs from the app, which should indicate a more specific error.

**Comment by robingroppe** [comment]
nginx-proxy-manager is handling the ssl setup. Its a valid letencrypt cert for media.* and emby.*. Inside the local network npm forwards to 8096. Cant test android mobile app but both browser on pc and iOS and app on iOS work flawlessly.
I will look into getting logs from the tv app.

**Comment by robingroppe** [comment]
Update: All of that what I just said may be nonsense. 
The Browser on both TVs now tells me "requests to the server have been blocked by an extension" even though the second TV is a nearly fresh install. I have to figure that out.

**Comment by robingroppe** [comment]
So, its solved with a workaround.
It was due to a DNS issue, or the failure of the app to fall back to IPv4.
I use the integrated DynDNS System of my Home-Router which sets a A and a AAAA record.
The AAAA record points to the IPv6 of the Router itself, which isnt useful at all when port forwarding stuff.
Long story short, i disabled IPv6 entirely and it works.
I highly suggest to investigate the fallback mechanism in case of a IPv6 connection failure.
