### ISSUE TITLE
Background subtitles left align

### ISSUE THREAD

**Issue by chipotledonut** [jellyfin/jellyfin-androidtv#1633]
### Describe the bug

External or internal subtitles using exoplayer.

[Maybe beacuse of this ](https://github.com/jellyfin/jellyfin-androidtv/pull/1572)

Text is centered but the subtitles background is clearly left align. It's as long as the text but left align.

![sdsdds](https://user-images.githubusercontent.com/67786790/163812164-ec203e62-6e57-4158-9ebf-4a83a6ee1c00.jpg)

### Application version

0.13.3

### Where did you install the app from?

Google Play

### Device information

Xiaomi TV 4S

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by Arecsu** [comment]
Experiencing same bug here!
