### ISSUE TITLE
Subtitles not sent to external players

### ISSUE THREAD

**Issue by m33ts4k0z** [jellyfin/jellyfin-androidtv#1638]
### Describe the bug

When choosing to open the video to an external player (i.e. mx player), the subtitles are not sent to that player if they are not embedded.

Sideloading the Android mobile app to the Android Box and setting to the same external player, makes the subtitles work with that external player. 

### Application version

0.13.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield TV Pro 2019

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by nielsvanvelzen** [comment]
There is no standard for sending subtitles to an external player and thus we can't implement this without hacks. There is no plans to extend the external player functionality in the app right now.
