### ISSUE TITLE
F-Droid reproduceable build failed

### ISSUE THREAD

**Issue by linsui** [jellyfin/jellyfin-androidtv#1639]
### Describe the bug

https://monitor.f-droid.org/builds/log/org.jellyfin.androidtv/130399#site-footer It built fine in the CI. Not sure why it failed on the build server. Could you please take a look? Thanks!

### Logs

```shell
https://monitor.f-droid.org/builds/log/org.jellyfin.androidtv/130399#site-footer
```

### Application version

130399

### Device information

None

### Android version

None

### Jellyfin server version

None

**Comment by sourpatched** [comment]
Seems like it could be due to APK Signature that's causing a mismatch?

F-Drod is more for mobile then ATV but in saying that, it's best to have an app be more accessible.

**Comment by nielsvanvelzen** [comment]
Issue might be fixed in the [v0.13.4](https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.13.4) release.

**Comment by linsui** [comment]
Still not verified.

**Comment by linsui** [comment]
There are two different files.

```
Unexpected diff output:
Binary files /tmp/tmpn4i7qii7/unsigned_binaries_org.jellyfin.androidtv_130699.binary/content/assets/dexopt/baseline.prof and /tmp/tmpn4i7qii7/_tmp_tmpn4i7qii7_sigcp_org.jellyfin.androidtv_130699/content/assets/dexopt/baseline.prof differ
Binary files /tmp/tmpn4i7qii7/unsigned_binaries_org.jellyfin.androidtv_130699.binary/content/classes3.dex and /tmp/tmpn4i7qii7/_tmp_tmpn4i7qii7_sigcp_org.jellyfin.androidtv_130699/content/classes3.dex differ
```

**Comment by licaon-kter** [comment]
Still an issue :( https://gitlab.com/fdroid/fdroiddata/-/jobs/2806346970#L636

Disabled autoupdate for now: https://gitlab.com/fdroid/fdroiddata/-/commit/34bd6224241835aa3e761e02c1db0f00c3aca955

**Comment by nielsvanvelzen** [comment]
Thanks for linking the job, I think I know why it fails now. The AboutLibraries plugin we use generates a JSON file with all licenses and adds a timestamp from when it generated the file. That timestamp obviously differs between our build and F-Droid's build. Will see what I can do to fix.

**Comment by nielsvanvelzen** [comment]
Issue should be fixed in the next release (0.14.1)

**Comment by nielsvanvelzen** [comment]
I'm quite sure that disabling ART will give us a performance penalty, so we shouldn't disable it. If that's the problem in creating a reproducible build I think our only choice is to not use reproducible builds for now.

**Comment by obfusk** [comment]
> I'm quite sure that disabling ART will give us a performance penalty, so we shouldn't disable it.

It doesn't disable the Android Runtime (ART), just baseline profiles.

According to [the docs](https://developer.android.com/topic/performance/baselineprofiles/overview):

> Baseline Profiles improve code execution speed by around 30% from the first launch by avoiding interpretation and just-in-time (JIT) compilation steps for included code paths.

So it may very well indeed result in a performance penalty, but I have found no real-world data on whether 30% is accurate or not. And all the docs say that developers need to *define* these profiles, but I don't see e.g. a `baseline-prof.txt` in your repo, so I have no idea what the `baseline.prof{,m}` is currently based on and whether it's actually doing anything useful. Do you have any info on that?

**Comment by linsui** [comment]
Could you please test the apk build without the profile?

**Comment by linsui** [comment]
Every time it produces a different apk so the profile part is not reproducible at all.

**Comment by linsui** [comment]
@licaon-kter got the 1.14.3 version build reproduciblly by limiting it to use only 1 core. Do you use more cores for newer versions? Could you please build the latest version with 1 core?

**Comment by nielsvanvelzen** [comment]
All releases are build with GitHub actions. According to the [documentation](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) these are the specs:
- 2-core CPU (x86_64)
- 7 GB of RAM
- 14 GB of SSD space
I believe they used two cores from the start. Our 0.14 release salso used this release pipeline.

**Comment by linsui** [comment]
@obfusk's https://github.com/obfusk/reproducible-apk-tools#sort-baselinepy can fix the profm problem. You also need to run the script before sign the apk.

**Comment by obfusk** [comment]
You can also sort the `baseline.profm` file by adding something like this to `build.gradle`:

```gradle
import com.android.tools.profgen.ArtProfileKt
import com.android.tools.profgen.ArtProfileSerializer
import com.android.tools.profgen.DexFile

project.afterEvaluate {
    tasks.compileReleaseArtProfile.doLast {
        outputs.files.each { file ->
            if (file.toString().endsWith(".profm")) {
                println("Sorting ${file} ...")
                def version = ArtProfileSerializer.valueOf("METADATA_0_0_2")
                def profile = ArtProfileKt.ArtProfile(file)
                def keys = new ArrayList(profile.profileData.keySet())
                def sortedData = new LinkedHashMap()
                Collections.sort keys, new DexFile.Companion()
                keys.each { key -> sortedData[key] = profile.profileData[key] }
                new FileOutputStream(file).with {
                    write(version.magicBytes$profgen)
                    write(version.versionBytes$profgen)
                    version.write$profgen(it, sortedData, "")
                }
            }
        }
    }
}
```

**Comment by nielsvanvelzen** [comment]
Our Gradle build files use Kotlin and it looks like the compiler is slightly more strict. We can't use the properties/functions on ArtProfileSerializer because their visibility is internal.

**Comment by obfusk** [comment]
> We can't use the properties/functions on ArtProfileSerializer because their visibility is internal.

I was afraid it would not work with `build.gradle.kts` because of the visibility, but thanks for confirming :sweat_smile:

You might be able to put it in a separate `.gradle` file (e.g. `fix-profm.grade`) and use `applyFrom("fix-profm.gradle")` from `build.gradle.kts`, but I haven't tested this.

**Comment by obfusk** [comment]
A quick test suggest it will fail to find the required imports via `apply(from = ...)`; but perhaps you can make it work?

FWIW, using the [python script to sort](https://gist.github.com/obfusk/61046e09cee352ae6dd109911534b12e#calling-sort-baselinepy-from-buildgradle) instead of `com.android.tools.profgen` should work with Kotlin.

**Comment by obfusk** [comment]
You can also wait for a new AGP version with [the fix](https://android.googlesource.com/platform/tools/base/+/2f2c6b30b55e18e2672edf5ee8e8e583be759d3e), but that might take a while.

**Comment by obfusk** [comment]
You can put this in `app/fix-profm.gradle`:

```gradle
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // NB: use this with gradle/libs.versions.toml (and modify as needed):
        classpath "com.android.tools.build:gradle:${libs.versions.android.gradle.get()}"
    }
}

import com.android.tools.profgen.ArtProfileKt
import com.android.tools.profgen.ArtProfileSerializer
import com.android.tools.profgen.DexFile

project.afterEvaluate {
    tasks.compileReleaseArtProfile.doLast {
        outputs.files.each { file ->
            if (file.toString().endsWith(".profm")) {
                println("Sorting ${file} ...")
                def version = ArtProfileSerializer.valueOf("METADATA_0_0_2")
                def profile = ArtProfileKt.ArtProfile(file)
                def keys = new ArrayList(profile.profileData.keySet())
                def sortedData = new LinkedHashMap()
                Collections.sort keys, new DexFile.Companion()
                keys.each { key -> sortedData[key] = profile.profileData[key] }
                new FileOutputStream(file).with {
                    write(version.magicBytes$profgen)
                    write(version.versionBytes$profgen)
                    version.write$profgen(it, sortedData, "")
                }
            }
        }
    }
}
```

And add this to `app/build.gradle.kts`:

```kts
apply(from = "fix-profm.gradle")
```

And it should work.

**Comment by nielsvanvelzen** [comment]
Thanks @obfusk, I've applied this workaround in #2558 and will backport it to our next patch release which will likely be on the 12th. @linsui do I need to make changes to f-droid data after the release or will you deal with that part?

**Comment by linsui** [comment]
You can open an MR or ping me when it's ready.

**Comment by nielsvanvelzen** [comment]
@linsui https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.15.5 includes the workaround for reproducible builds. Let me know if this issue persists or something else comes up. Thanks for the report!

**Comment by licaon-kter** [comment]
A quick test did fail to Repro :(

**Comment by nielsvanvelzen** [comment]
Hmm weird, I tested it by creating multiple builds locally and using `diff -r` to see if there were binary differences and it worked after the pull request. I guess I'll need to do some more testing later. Was the issue still in the baseline files in your quick test?

**Comment by licaon-kter** [comment]
It's the "number of CPUs" issue, will test 1/2/4/etc cores and adapt the recipe.

**Comment by licaon-kter** [comment]
Ok, builds fine, I've missed that it needs Java17 now :partying_face:

**Comment by licaon-kter** [comment]
Done https://gitlab.com/fdroid/fdroiddata/-/commit/260ab2dd85fe5739476f756b6233ae556d36344e

Thanks for sticking with it :)
