### ISSUE TITLE
Can't Stop Playback or Send messages on the Android TV app

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [jellyfin/jellyfin-androidtv#1644]
### Describe the bug

Can't Stop Playback or Send messages on the Android TV app. Websockets are enabled and working fine for browsers. Seems like the app don't allow websockets.

### Application version

0.13.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield

### Android version

Android 9

### Jellyfin server version

10.8.0-Beta 2

**Comment by nielsvanvelzen** [comment]
Without client logs we can only guess what might go wrong. Can you explain your networking setup? Are you perhaps using a reverse proxy like nginx that might block the WebSocket connection?

**Comment by mueslimak3r** [comment]
> Can't Stop Playback or Send messages

Is this via remote control?
If so, try doing a "force stop" on the app the Android settings, and open the app again.
When the app is suspended long enough the socket times out and breaks remote control features even after resuming. For now, completely closing the app and reopening it is how you can make remote control work.
