### ISSUE TITLE
Resolution Switching doesn't work anymore

### ISSUE THREAD

**Issue by KyleSanderson** [jellyfin/jellyfin-androidtv#1646]
### Describe the bug

1. Playback was excellent(?).
2. User asked for option to not resolution switch because their device is attempting to be a better upscaler: https://github.com/jellyfin/jellyfin-androidtv/issues/1482
3. Proposal outright removing resolution switching by @mueslimak3r: https://github.com/jellyfin/jellyfin-androidtv/pull/1484
4. Resolution switching doesn't work anymore.
5. @nielsvanvelzen asked for me to create a new issue.

Can we please revert this commit? See the log below for the behaviour that doesn't make sense. It looks like there's an issue with selecting the proper refresh rate as well.

### Logs

```shell
04-25 00:04:44.678 10445 10445 D PlaybackController: trying to find display mode for video: 1920x1080 @29.97003fps
04-25 00:04:44.679 10445 10445 D PlaybackController: qualifying display mode: 1920x1080 @59.94fps
04-25 00:04:44.680 10445 10445 D PlaybackController: preferring mode: 1920x1080 @59.94fps
04-25 00:04:44.680 10445 10445 D PlaybackController: qualifying display mode: 3840x2160 @59.94fps
04-25 00:04:44.680 10445 10445 D PlaybackController: qualifying display mode: 3840x2160 @29.97fps
04-25 00:04:44.681 10445 10445 D PlaybackController: preferring mode: 3840x2160 @29.97fps
04-25 00:04:44.681 10445 10445 D PlaybackController: qualifying display mode: 1920x1080 @29.97fps
04-25 00:04:44.682 10445 10445 I PlaybackController: *** Best refresh mode is: 8 - 3840x2160/29.969999
04-25 00:04:44.682 10445 10445 I PlaybackController: *** Attempting to change refresh rate from 3/59.94
```

### Application version

v0.13.3

### Where did you install the app from?

Amazon Appstore

### Device information

Firestock Max

### Android version

AMZN

### Jellyfin server version

unstable

**Comment by KyleSanderson** [comment]
FYI these are the modes that the Firestick sees. My panel supports a lot more than these.

`04-24 20:16:21.149 545 571 I DisplayManagerService: Display device changed: DisplayDeviceInfo{"Built-in Screen": uniqueId="local:0", 3840 x 2160, modeId 11, defaultModeId 1, supportedModes [{id=1, width=1920, height=1080, fps=60.000004}, {id=2, width=1920, height=1080, fps=59.94}, {id=3, width=3840, height=2160, fps=59.94}, {id=4, width=1280, height=720, fps=59.94}, {id=5, width=3840, height=2160, fps=50.0}, {id=6, width=3840, height=2160, fps=60.000004}, {id=7, width=3840, height=2160, fps=30.0}, {id=8, width=3840, height=2160, fps=29.97}, {id=9, width=3840, height=2160, fps=25.0}, {id=10, width=3840, height=2160, fps=24.0}, {id=11, width=3840, height=2160, fps=23.976}, {id=12, width=1920, height=1080, fps=50.0}, {id=13, width=1920, height=1080, fps=29.97}, {id=14, width=1920, height=1080, fps=23.976}, {id=15, width=1920, height=1080, fps=24.0}, {id=16, width=1920, height=1080, fps=30.0}, {id=17, width=1280, height=720, fps=50.0}, {id=18, width=1280, height=720, fps=60.000004}, {id=19, width=720, height=576, fps=50.0}, {id=20, width=720, height=480, fps=60.000004}], colorMode 0, supportedColorModes [0], HdrCapabilities android.view.Display$HdrCapabilities@bf1c8d68, density 320, 314.632 x 322.729 dpi, appVsyncOff 1000000, presDeadline 41708375, touch INTERNAL, rotation 0, type BUILT_IN, state ON, FLAG_DEFAULT_DISPLAY, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS}`

**Comment by mueslimak3r** [comment]
> It looks like there's an issue with selecting the proper refresh rate as well.
> 
> ```
> 04-25 00:04:44.678 10445 10445 D PlaybackController: trying to find display mode for video: 1920x1080 @29.97003fps
> ...
> ...
> 04-25 00:04:44.682 10445 10445 I PlaybackController: *** Best refresh mode is: 8 - 3840x2160/29.969999
> ```

That looks correct. The difference between 29.97003 and 29.969999 should just be due to them being logged differently (logged with %s vs %f). I'll change them all to %f.


> Can we please revert this commit?

You make a good point that there are probably far fewer people who want to scale on their device.

I'm going to make a PR that changes the refresh rate setting from a toggle to a multi-choice setting similar to the photo below. The options would be `disabled`, `scale on tv`, and `scale on device`. For users with refresh rate switching enabled, updating the app to a version including these changes would convert the `enabled` setting to `scale on tv`.

![20220424_235016](https://user-images.githubusercontent.com/28824542/165042408-a30910c4-9a55-4f95-adac-f81e8456f5af.jpeg)

**Comment by KyleSanderson** [comment]
As long as it's an option that defaults to the majority I'm OK with that.

**Comment by mueslimak3r** [comment]
Can you test the PR linked above and see if it fixes your issue?

**Comment by KyleSanderson** [comment]
> Can you test the PR linked above and see if it fixes your issue?

I can sideload an apk if that helps? unfortunately I'm not setup to build android on nix at this time.

**Comment by mueslimak3r** [comment]
If you go to the PR -> checks -> app build -> summary. There's a "build artifacts" zip that has the APK

**Comment by KyleSanderson** [comment]
> If you go to the PR -> checks -> app build -> summary. There's a "build artifacts" zip that has the APK

`Server uses 10.7.7 which is not supported.`

**Comment by mueslimak3r** [comment]
Yeah master uses the latest sdk which is 10.8+ only. If you want to test with 10.7.7 you'll have to cherry pick and build it yourself off 0.13.3
