### ISSUE TITLE
This client not support Android 4.4.2

### ISSUE THREAD

**Issue by yfdoor** [jellyfin/jellyfin-androidtv#166]
This client not support Android 4.4.2, package could not install on this android device.

**Comment by TiraelSedai** [comment]
Yep, it does not. It explicitly says so in Google Play store.

**Comment by anthonylavado** [comment]
This project already uses some features that require newer API levels, so only 5.0 and above are supported right now. Even Emby's own Android TV app has the same requirements, and I can imagine that we probably inherited that part.

**Comment by herigrosir** [comment]
tentu saja sangat mudah 

anda cukup install vlc for kitkat 
1 open vlc 
2 conekted to LAN 
3 pilih shered folder yang di server anda atau SMB 
4 putar saja , agar berjalan lancar , file movie di utamakan MKV 

kamu tidak perlu metadata , tidak perlu gambar gambar , cukup simple 
hanya judul dan folder , selesai 

karna pada dasarnya mesin jellfin juga isinya menggunkan coding vlc 
demikian semoga bisa menjawab 

by : indonesia
