### ISSUE TITLE
User not identified + can't enter user manually

### ISSUE THREAD

**Issue by ygaeon** [jellyfin/jellyfin-androidtv#167]
Jellyfin server: 10.4.0.
nVidia Shield AndroidTV Jellyfin version: 0.9.1g
I only have nVidia remote to navigate.

1) When I open up Jellyfin I'm presented with a "Select a user", that doesn't display any users. The server seems to be correctly identified.
2) Under "Other options" I select "Enter Manually".
3) I get a "Enter user name" and a keyboard. I enter the user I've created in the server.
4) When pressing next it still reads "Enter user name" on the top but the "blue line" becomes same 
color as the text. Also the keyboard change to something containing all characters (including special characters, numbers etc.). I'm assuming I'm going to enter a password here, which I do, and then click the Enter sign.
5) The app wraps back to state 1 above, and I'm not logged in or anything.

![2019-10-14_21-38-18_screenshot](https://user-images.githubusercontent.com/7010726/66778361-b8571f80-eecb-11e9-9f7a-fd1421a82dc7.jpg)

**Comment by thornbill** [comment]
New users are no longer publicly viewable by default in 10.4.0 which is likely why the users are not listed under "Select a user".

It looks like when you press "next" the cancel button has focus. I'm not sure why that would bring up a keyboard though. It will need some additional investigation.

**Comment by ygaeon** [comment]
If I, from the first keyboard (middle image), move cursor up, I can't come to the "Cancel" nor "OK" buttons .. instead it's "wrapped" directly to the 3rd image.
If I do the same (moving cursor up) in the 3rd image, it's wraps back to 1st image.

**Comment by flashkiller999** [comment]
Hello,

I can report the same problem an Xiaomi Mi Box 3 (AndroidTV) with Jellyfin 0.10.2 version. (Server is 10.4.2)
With only a Remote it is not possible to enter a Username and confirm the input, as the Enter-Button on the OSD keyboard default to Cancel.
I was able to work around this issue with an USB keyboard an Tab'ing through to get to the OK button.

Cheers

**Comment by 0rsa** [comment]
I have same issue using a Mi Box 3 or a Mi Box S or a Xiaomi Batman projector (I guess all xiaomi android TV are concerned)

**Comment by nielsvanvelzen** [comment]
We are working on this. A workaround for now is by using the [Android TV Remote Control
 app](https://play.google.com/store/apps/details?id=com.google.android.tv.remote&hl=en_US) to navigate in the login screen. All other parts of the app should work.

**Comment by basso** [comment]
Same problem on my Nvidia Shield TV

**Comment by razor1973** [comment]
Same.

**Comment by 0rsa** [comment]
How Jelly team cannot fix this incredible bug reported months ago which makes crazy all people? Unbelievable...

**Comment by nielsvanvelzen** [comment]
@0rsa we're all working on Jellyfin in our spare time as volunteers. This issue is indeed annoying and we're already working on it but it takes time.

**Comment by lrlf** [comment]
im having the same problem using the android tv remote app thus nothing

**Comment by majox7** [comment]
Same problem on Nvidia Shield TV

**Comment by cynicalsoul** [comment]
Hi,

I'm just testing Jellyfin for the first time and had the same problem with sony bravia TV which is frustrating.

After about half an hour of messing about, there was actually an obvious fix.

Problem:
Keyboard pops up, you enter your username and then press enter. Then a second keyboard appears (also the cancel button is now highlighted) but it wont let you go any further, it just closes.

Simple fix:
When the second keyboard appears, just press back on the remote to close the keyboard. You can now move the cursor over to ok.

I did change the keyboard from Gboard to standard, but i don't think that made a difference.

Looking at the screenshots, this is the same problem you guys are having.

**Comment by vnidens** [comment]
Hi @nielsvanvelzen, @thornbill , Is anyone working on it right now?
If not I can take this one. If you already have some concept maybe you could share it with me (probably in the Matrix chat)?

**Comment by nielsvanvelzen** [comment]
Hi @vnidens.

@thornbill is slowly working on this issue but he shifted his focus to the ios app for a while.

We have a dedicated Matrix channel for [Android (TV) development](https://matrix.to/#/#jellyfin-dev-android:matrix.org). Feel free to join it for these kinds of questions! :)

**Comment by liberodark** [comment]
Have issue on 0.11.4 is not saving my user / password. is very long to re login all the time.
Have any possibility to fix that ?

**Comment by nielsvanvelzen** [comment]
After logging in open the settings and you can then choose to stay logged in.
