### ISSUE TITLE
[Shield TV Pro 2019] Cant play Dolby Vision P4/5/8 if video transcode is disabled?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1685]
### Describe the bug

If i just disable video transcode on the Shield user, but leave all other transcode options enabled. The AndroidTV player will simple reject playing any DV content, except P7?

Yet if i enable the transcode option, it plays all P5/8/8.1 just fine, without any transcoding via direct-play, with player set to Auto?

### Logs

```shell
[INF] [4] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for andy. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: True
[INF] [4] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=AndroidTV-libVLC, Path=\\192.168.1.101\media\_testFiles\calibration2\multi pattern DV P8.mp4, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=AudioCodecNotSupported ) media:/videos/cbc9902d-04f2-852a-2ebd-b2ee11e51625/stream?MediaSourceId=cbc9902d04f2852a2ebdb2ee11e51625&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=315c25202d0dcad7a81e3af3dbc5f3ee&TranscodeReasons=AudioCodecNotSupported
```

### Application version

0.13.3

### Where did you install the app from?

Google Play

### Device information

Shield TV Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8.0-beta2

**Comment by mueslimak3r** [comment]
Possibly related to the failure to generate urls thing mentioned in #1679

@Andy2244 are you able to collect a log from the app using `adb logcat`? If so please record a log while you reproduce the issue, remove your identify info from the log, and upload it to pastebin. Thanks!

**Comment by Andy2244** [comment]
@mueslimak3r Just did a full reset and only installed JellyfinTV fresh, same error.
Here is the log with the last couple of seconds: https://pastebin.com/Z3xaascJ

> You can confirm this by looking at the jellyfin web dashboard and clicking on the "i" button for the session. It will say if it's direct playing or transcoding

I did and it notes direct playing, while also having no extra cpu/gpu use on the server.

**Comment by Andy2244** [comment]
Just did test the normal Android client and there the files play fine using exoplayer using direct play, with video transcoding disabled in the user settings.
