### ISSUE TITLE
0.13.14 got "no playable items" in couple minutes after Play media

### ISSUE THREAD

**Issue by shirou93** [jellyfin/jellyfin-androidtv#1700]
### Describe the bug

1. Play any media and wait while.
2. Jellyfin show error and stop media.

### Logs

```shell
No logs
```

### Application version

0.13.14

### Where did you install the app from?

Google Play

### Device information

TCL A12TV

### Android version

ATV11

### Jellyfin server version

10.0.7.7

**Comment by sourpatched** [comment]
Does this happen on Jellyfin 10.8.3 and ATV 0.14.0?
