### ISSUE TITLE
Homescreen "media (small)" not working

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1708]
### Describe the bug

"media small" looks the same as "media" for home-screen customization.

### Application version

0.13.5

### Where did you install the app from?

Sideloaded APK

### Device information

Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8-unstable

**Comment by nielsvanvelzen** [comment]
Not a bug. We don't implement the small media tiles.
