### ISSUE TITLE
"Shuffle All" and "Play From Here" not working

### ISSUE THREAD

**Issue by screening4ashes** [jellyfin/jellyfin-androidtv#1712]
### Describe the bug

1. Create a playlist (I had to do this on my computer in the web interface, because I see no quick and easy way to turn an entire library into a playlist in the AndroidTV client, nor a way to play an entire library from the AndroidTV client).  I made a music video playlist of all my MV collection, only 261 items.
2. Load the playlist on a TV running the AndroidTV client
3. select "Shuffle All" option, and watch as the player proceeds to begin at the beginning of the playlist and play in order without any shuffling.
4. This is 3-Alternate, select any song in the list and choose "Play From Here" and watch as it proceeds to start again with the first song in the play list in the playlist's original order.

I expect the "Shuffle All" option to select a song at (semi-)random and continue playing all videos in the playlist as random.
I expect "Play From Here" to start playing the playlist in order from the song selected, but instead both options start at the beginning of the list in order.

### Application version

0.13.5

### Device information

Onn UHD Streaming Device (Onn 4K TV / askey sti6140d360)

### Android version

Android 10

### Jellyfin server version

10.7.7

**Comment by tomnehek** [comment]
I've seen this same behavior. Shuffling outside of a playlist works - seems exclusive to playlists.

**Comment by therealgorgan** [comment]
Playlist shuffling also plays the first item

**Comment by kevgrig** [comment]
Also experienced this. Created a fix here: https://github.com/jellyfin/jellyfin-androidtv/pull/1910
