### ISSUE TITLE
Add more playlist/queue controls in the play controls

### ISSUE THREAD

**Issue by screening4ashes** [jellyfin/jellyfin-androidtv#1713]
### Describe the feature you'd like

As it is now, you only get controls for the currently playing video file when you play a playlist or set/queue of files.

When multiple files are loaded, control options should be added for the entire playlist/set/queue - such as "shuffle/unshuffle", "repeat once/infinitely".

Additionally, mapping should be added for channel up and down buttons to control playlist next and previous file, so if you are watching TV shows or Music Videos on random shuffle, you can easily and quickly advance to the next song/episode if you are not in the mood for the one which came next, or so you can go back if you were skipping forward to fast and passed one you actually wanted to watch/listen to.

Add an option to turn any library or subset of a library into a playlist, and give all the above control options for any and all playlists.... once or infinite repeat on/off toggling, forward/backward advancement with channel buttons, shuffle and in-order ordering options.

Also, in a playlist, there's a "Play From Here" option which currently does not work for me at all, that should of course be fixed, but another button could be added for "Shuffle From Here", however, if the player adds the above list/queue control options while playing, then you can turn on shuffle after you start playing.  It would however be nice to save shuffling preferences for playlists in the playlist, such that the default will always be to shuffle if you turn shuffle on once.  Then to unshuffle in the future, you would need to turn it off... in other words, give shuffling and repeat options a persistent state in playlists, so that you don't have to reconfigure every time you play the same playlist.

Shuffle All is currently working as expected in TV Shows, by the way, maybe the TV Show code could just get copied over to playlists 🤔

**Comment by mueslimak3r** [comment]
There are some great ideas here. We like to stick to individual bugs or enhancements per issue. This way when a pull request is opened that resolved it, the issue can be closed by the pull request being merged.

Could you separate your thoughts into individual issues for:
* Bugs - something is broken/not working as advertised
* Enhancements - you have an idea about how something might work better than it does now, or for a feature that could be nice

There's a lot here so it's okay if you group a couple things together as long as they are closely related and all fit into the same category of either bug or enhancement.
