### ISSUE TITLE
Android TV client does not respect options chosen in 'Version' menu

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-androidtv#1716]
### Describe the bug

Browse to a movie that has multiple versions. In my case, I have a movie with a 1080p version and another version in 4k.

I choose the 4k version and click play, but I can verify with
`lsof` on my Linux machine that Jellyfin has opened the file for the 1080p version. (I didn't trust my eyes to know which was which.)

![20220513_224945](https://user-images.githubusercontent.com/3911507/168406726-9b096596-3643-447c-9b8b-47e736004cb7.jpg)

```
root@thor:/srv# lsof -p 4851 |grep -i mkv
jellyfin 4851 root  382rR  REG  9,0 7590229387 186025134 /media/Movies/The Two Towers/The Two Towers - Extended Edition 1080p.mkv
```

### Logs

```shell
I'm unable to get the client logs of my CCwGTV :(
```

### Application version

0.13.5

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

Android 10,  Android TV OS build QTS1.210311.036.7814738

### Jellyfin server version

10.7.7

**Comment by mikewesten** [comment]
#1521
