### ISSUE TITLE
Jellyfin starting ZDMC as external player

### ISSUE THREAD

**Issue by sat4all1** [jellyfin/jellyfin-androidtv#1718]
### Describe the bug

1. Go to Jellyfin playback settings
2. Set external player as default player
3. Select a media 
4. Start playback
5. Jellyfin is starting the playback using ZDMC "Kodi fork" instead of zidoo standalone internal player
6. Using emby: i can choose between zmdc or zidoo internal player at first run, and select if it should always ask or always use the selection.

### Media info of the file

```shell
All kind of media mkv.mp4...
```

### Application version

0.13.5

### Device information

Zidoo Z9X

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by Andy2244** [comment]
> You should be able to reset the default video app somewhere in the system preferences.

Yes, go to the zdmc app info screen than via "clear defaults".

**Comment by sat4all1** [comment]
Thanks for the quick replies and sorry for the delay.
No i didn't set any other default video app in my zidoo system, and as i mentioned before with emby and tivimate i don't have this problem both can launch zidoo default video player.
Just for testing i've uninstalled zdmc. now jellyfin is showing No player message "it doesn't appear you have a video capable app installed...". while all other apps still able to launch external video player.

**Comment by Andy2244** [comment]
> while all other apps still able to launch external video player.

What other apps?

If you don't get the selection window for the internal player, than the internal player did not properly register a Android Intent for this URI/type/class. That's also why most players wont be listed if you try open a "smb://" URI.

Kodi/ZDMC correctly registers itself for most URI's thats why it gets used.

From what i gathered on Emby it seem that they added direct support to use the internal player on Zidoo players. You can check the .apk of the internal player and check the manifest.xml which Intents/Action the player actually registers.

**Comment by Andy2244** [comment]
Ok i now also own a z9x and can not confirm this error. The normal "video player" is listed in the open dialog at play and can be selected/used. I also confirmed and external network paths also work and are registered for SMB/NFS URI's.

**Comment by sat4all1** [comment]
Still doesn't work unless i uncheck "enable direct path  playback" in jellyfin settings.
Could you plz check using direct path playback enabled?

**Comment by Andy2244** [comment]
I'm working on this in general see here: http://forum.zidoo.tv/index.php?threads/api-android-api-feature-proposal-and-wishlist.93692/

**Comment by sat4all1** [comment]
Sounds great, best of luck!

**Comment by Andy2244** [comment]
> But unfortunately the patched version is no longer maintained.

@sat4all1 Just released my beta2, you can check it [here](https://github.com/Andy2244/jellyfin-androidtv-zidoo)
