### ISSUE TITLE
Investigate transcoding EAC-3 in 10.8.0

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#1723]
### Describe the bug

There have been a couple reports on Reddit that EAC-3 is being transcoded (or not playing at all?) when it should direct play when using a 0.13.x release of the app and a 10.8.0 alpha/beta server release.

**References:**
* https://www.reddit.com/r/jellyfin/comments/sbiovm/android_tv_app_and_shield_transcoding_eac3_audio/
* https://www.reddit.com/r/jellyfin/comments/urj1fa/regression_all_video_files_with_eac3_fail_to/

### Media info of the file

![media info](https://user-images.githubusercontent.com/3450688/169092420-50a0678e-52a3-48f3-84cb-e085d8cfdedc.png)

### Application version

N/A, 0.13.5

### Device information

Nvidia Shield Pro, Sony Bravia TV

### Android version

N/A, Android 9

### Jellyfin server version

N/A, 10.8.0 beta 3

**Comment by raven-au** [comment]
It appears that anything with more than 6 channels is getting transcoded.
For example I see a 1080p video with TrueHD 7.1 being transcoded.
I'll need to try some DTS based shows.

**Comment by raven-au** [comment]
Also happens for DTS-HD MA 7.1.
Once it does happen the app often seems to get confused and HDR playback no longer works when an audio track with fewer channels is selected so it direct plays.

**Comment by Fallenbagel** [comment]
I have a file that is `EAC3` Dolby Digital+ 5.1 with 6 channels and its getting transcoded as well. And when I force direct play, it does not play at all. 

> It appears that anything with more than 6 channels is getting transcoded.

So I'm guessing it happens with ≥ 6 audio channels. 
![Screenshot_20220609-151114_Jellyfin](https://user-images.githubusercontent.com/98979876/172823740-1586ac01-5797-4c98-a403-31679a77e673.jpg)

**Comment by raven-au** [comment]
> > It appears that anything with more than 6 channels is getting transcoded.
> 
> So I'm guessing it's ≥ 6 audio channels. 

That equals appears to be related the other request.

What's worse is I think I am seeing inconsistent behaviours.
I suspect this is due to using both ExoPlayer and libVLC and they each exhibit different behaviour.

If and when the cases become clear to me I'll post an update.
