### ISSUE TITLE
does jellyfin tv support Android 4.4?

### ISSUE THREAD

**Issue by Evan-tc** [jellyfin/jellyfin-androidtv#1747]
### Describe the feature you'd like

does jellyfin tv support Android 4.4?

**Comment by Dnkhatri** [comment]
Install it and find out it works on Android 6 at least.

**Comment by nielsvanvelzen** [comment]
Android 4.4 is not supported by any of our apps. The app supports all Android TV versions. And the first Android TV version used Android 5.0 (API level 21).

**Comment by herigrosir** [comment]
tentu saja sangat mudah 

anda cukup install vlc for kitkat 
1 open vlc 
2 conekted to LAN 
3 pilih shered folder yang di server anda atau SMB 
4 putar saja , agar berjalan lancar , file movie di utamakan MKV 

kamu tidak perlu metadata , tidak perlu gambar gambar , cukup simple 
hanya judul dan folder , selesai 

karna pada dasarnya mesin jellfin juga isinya menggunkan coding vlc 
demikian semoga bisa menjawab 

by : indonesia
