### ISSUE TITLE
Remove server

### ISSUE THREAD

**Issue by moreje** [jellyfin/jellyfin-androidtv#175]
There is no way to remove server from the app.
the only solution is to clean app data

**Comment by anthonylavado** [comment]
I was pretty sure you could press the Menu button, and that would let you remove a server. What device are you using?

**Comment by moreje** [comment]
I did not test the menu button.. I've try long press..I'll test it after the weekend ;) 
I am on Philips Android Oled TV

**Comment by dkanada** [comment]
@moreje were you able to test this?

**Comment by thornbill** [comment]
Menu buttons are not universal in Android TV devices. We need to provide an alternative method for removing servers that does not depend on a hardware button.

**Comment by nielsvanvelzen** [comment]
This is now possible in the (upcoming) 0.12 release.
