### ISSUE TITLE
easy Authentification is not working

### ISSUE THREAD

**Issue by moreje** [jellyfin/jellyfin-androidtv#176]
I have no PIN defined and Easy authentification is activated.
but the app continues to ask for a password for my user when I connect from my local LAN

**Comment by anthonylavado** [comment]
>I have no PIN defined and Easy authentification is activated. ...

@moreje Easy authentication requires a PIN, otherwise it will ask for your password. The only way around that is to have no password set.

Right now, PINs are not working in 10.4.0, we’re trying to get it fixed.

**Comment by moreje** [comment]
Hum, so the help phrase in settings section is not really clear "Si le code PIN n'est pas défini, vous n'aurez pas besoin de mot de passe depuis l'intérieur de votre réseau local." i.e.: if the PIN is not defined, you will not need password from LAN

**Comment by thornbill** [comment]
There is an open issue for this on the server repository now. It also mentions a workaround that may let you use a blank password locally. https://github.com/jellyfin/jellyfin/issues/2125

I’m going to close this issue since it doesn’t seem specific to Android TV.
