### ISSUE TITLE
srt subtitle code in exoplayer

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-androidtv#1763]
### Describe the feature you'd like

Is it not possible to get the code for srt subtitles to work like in libvlc
or mpch on windows pc ? if i want to outline the text in some parts of the video this only works
in libvlc with srt not in exoplayer in exoplayer i have to use ass for this
but then i get the transcode problem because exoplayer dont recognise the ass type
without transcoding i just tested it on jellyfin mediaplayer and on  jellyfin android phone there it works with srt
but not in exoplayer jellyfin android tv

**Comment by nielsvanvelzen** [comment]
Sorry I don't understand your question. Both our ExoPlayer and LibVLC implementations support srt files and require transcoding to burn in ssa/ass files.

**Comment by satstarter** [comment]
Yes i know altough libvlc require no transcoding i think for ssa/ass
exoplayer does
but the thing i meant is the outlining so if i make my subtitles in subedit i can
make the subtitles on the top of the screen for a little time and the rest of the time they are default on the bottom
this works with srt and ssa/ass the only thing is if i play the video in jellyfin android tv with srt only libvlc does it right
exoplayer keeps the outlining on the bottom exoplayer only excepts this if its ssa/ass subs but then
it must transcode witch i dont have to do with libvlc
android an windows player both works with srt to achief this

ps sorry for my maybe bad english ;)
i am dutch speaking )p

**Comment by satstarter** [comment]
jup like i tought, thanx for the sugestion but i dont want to pay for it
thats why i askt this on the jellyfin boys if its possible to get this done in exoplayer

**Comment by satstarter** [comment]
Ok thats all true
but the reason i ask this is to avoid all that external stuff
and again i do appreciate your sugestion ;)
but with all the free external players we create other problems like
not auto play the next episode without asking something or comercials and stuff
also kodi is free and works except for srt not doing the outlining
libvlc works great only one thing i miss is the aspect ratio button like in exoplayer

**Comment by nielsvanvelzen** [comment]
ExoPlayer does not properly support ASS and probably never will. So no, you still need to transcode for SSA/ASS for now.

**Comment by Andy2244** [comment]
Just wondering what about the ffmpeg extensions for exoplayer?
Vimu is also exoplayer based, yet displays ass/ssa correctly?

**Comment by nielsvanvelzen** [comment]
We already use the ffmpeg extension (See https://github.com/jellyfin/jellyfin-exoplayer-ffmpeg-extension) but it's only for audio, it does not do video/subtitles (https://github.com/google/ExoPlayer/tree/release-v2/extensions/ffmpeg).

**Comment by Andy2244** [comment]
> it does not do video/subtitles

Ok, than vimu does some special ass sub handling.

**Comment by nielsvanvelzen** [comment]
Yeah that's likely the case. One thing I want to look into at some point is to use libass directly from the app to render subtitles. That's a thing I'll play with after the playback rewrite. So not anytime soon.

**Comment by satstarter** [comment]
to comeback on this issue i have on more thing to mention ssa/ass is almost unpossible to do with exoplayer
i have tested a little and it seems playing a video with ssa/ass in exoplayer puts my cpu to 80 a 85 procent
its an old i7-2600 and using vaapi hardware accelaration then file wont play it does with srt
playing with libvlc proccesor stays at 0 procent but then i miss the resolution button

**Comment by BotBlake** [comment]
Hello there.
Since Jellyfin Android TV 0.18.x, the app has been using subtitle rendering from ExoPlayer, which supports a wide range of SSA tags for SRT files.
Therefore this issue should be resolved.
