### ISSUE TITLE
Lag on 1080p

### ISSUE THREAD

**Issue by batmanatorul** [jellyfin/jellyfin-androidtv#1766]
### Describe the bug

I don't know why when I play 1080p movies on my Android TV i get a lot of frame drops, I tried playing it from a usb to see if its from the TV and it worked fine.

### Application version

latest

### Device information

idk

### Android version

Android 9

### Jellyfin server version

10.7.7

**Comment by jkhsjdhjs** [comment]
I also see framedrops when playing 1080p media. Doesn't matter if I play via libVLC or ExoPlayer, both drop frames. Only workaround I found so far was to install the VLC app and play the files via the "external app" option.
