### ISSUE TITLE
Crash when adding server

### ISSUE THREAD

**Issue by moreje** [jellyfin/jellyfin-androidtv#177]
I installed the 0.10 apk for Android TV on my Philips Android TV.
The app crash and exit when adding a server...

**Comment by tomkriz** [comment]
Same here. Recently got the newest Nvidia Shield Pro, Android SHIELD TV 9.1.0 which should be latest updates.

JellyFin 0.9.1 works. Since this was a new install, I thought maybe installing v0.10 after configuring on 0.9.1 would work, but it didn't. I wasn't even able to add a server, it just crashed on open after trying that.

**Comment by anthonylavado** [comment]
Just to confirm, what version of Jellyfin server are you running? Is it the most recent, 10.4.0?

**Comment by rdissertori** [comment]
same here using docker
```
Version: 10.4.0
Operating System: Linux
Architecture: X64
```

**Comment by moreje** [comment]
same here: 10.4.0 inside a container

**Comment by rdissertori** [comment]
just reporting back: that hotfix did it for me

**Comment by anthonylavado** [comment]
@cludch Following up here from https://github.com/jellyfin/jellyfin-androidtv/issues/186#issuecomment-549970414.

You mentioned you're using a reverse proxy. Are you on version 10.4.1? There's a note about the baseurl path having to be changed: https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1

**Comment by bwaddington** [comment]
Version: 10.4.1
Operating System: Linux
Architecture: X64

jellyfin-androidtv:  v0.10.1

i had a problem adding the server keep cashing out with address 
****.duckdns.org    
but when i put the port on it connected

****.duckdns.org:8096

**Comment by spoolr** [comment]
> i had a problem adding the server keep cashing out with address
> ****.duckdns.org
> but when i put the port on it connected
> 
> ****.duckdns.org:8096

I don't know why, but they removed the default port with "Merge pull request #172 from thornbill/default-port"

**Comment by thornbill** [comment]
Well it was poorly implemented and we are going the route of “what you enter in a client should match what you enter in a browser” to make things more consistent. It definitely should not crash when it tries to connect using an invalid port though.

**Comment by Cludch** [comment]
@anthonylavado 
Yes I am on 10.4.1 on the server-side. I use a subdomain for jellyfin, so I simply enter `https://jellyfin.domain.com` within the client. I also tried leaving the `https://` part out. Still crashing.
I could try to use the internal hostname and port `8096` to see if it's an issue with the reverse proxy.

**Comment by rdissertori** [comment]
I think this should be discussed on another ticket @Cludch btw having the exact same issue because I'm proxy forwarding my container instance via nginx. using the actual hostname+port works (bypassing the nginx) works.

**Comment by Cludch** [comment]
For me it does not work when bypassing the reverse proxy.
The app still crashes when I use the ip:port combination.

**Comment by jbmorgado** [comment]
I am having the same issue, also running the Jellyfin server inside a docker container. The previous version of the Android TV Jellyfin app worked fine, since the update it just crashes when I try to login.

**Comment by Cludch** [comment]
I found a solution on the Jellyfin forum:
https://forum.jellyfin.org/t/jellyfin-app-cant-login/932
It seems like you have to add the new base url, if one is set.

**Comment by thornbill** [comment]
As noted above and in the [release notes](https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1) please verify the base url has been removed from the server’s network settings. We have fixed the issues we could identify with adding an invalid url in the app in 0.10.2. Let us know if you are still experiencing issues!

**Comment by juliashelton** [comment]
Add

**Comment by juliashelton** [comment]
`add

**Comment by thornbill** [comment]
Closing since no additional information has been provided. Let us know if you still have issues!
