### ISSUE TITLE
Swap tall posters for square for channel logos

### ISSUE THREAD

**Issue by MischievousMet** [jellyfin/jellyfin-androidtv#1773]
### Describe the feature you'd like

Web UI and mobile use square logo posters. Android TV uses tall. When using logos for web and mobile, they get cutoff on Android TV and vice versa. The attached photo shows the logos in squares. When going with tall posters the sides get cut off and it doesn't look good.

![Screenshot_20220610-182110](https://user-images.githubusercontent.com/24836719/173231325-3c43465c-c44e-4937-9ddb-0e0c8f3bc654.png)

**Comment by nielsvanvelzen** [comment]
From my experience the logo's are shown as squares in the Live TV guide. I'm not aware of any other places they are shown.

**Comment by MischievousMet** [comment]
![image](https://user-images.githubusercontent.com/24836719/174674230-8a8acb99-7203-4302-96a1-b340875c42d6.png)

The cards are a little more vertical than they are wide. So it extends the image to match the vertical size which extends wider logos past it's border.

**Comment by bato42059** [comment]
Hey MischievousMet, i have the same problem with live-tv logos getting cut off on android tv app while its working flawlessly on chrome browser have you ever found a solution?

what resolution are your channel logos?
