### ISSUE TITLE
Video titles under thumbnail view

### ISSUE THREAD

**Issue by jimdwyerdev** [jellyfin/jellyfin-androidtv#1778]
**Describe the feature you'd like**
All of the views for the current Jellyfin app only show titles in the header when they are highlighted. 
It would be great to have a view where titles are located underneath the thumbnails for easy navigation (similar to the Poster view on the Jellyfin Web UI)

**Comment by TotoCon** [comment]
I would like to see this too. Would make navigation much easyer.

**Comment by ktdt00** [comment]
I would love to see this too. I like the "All Items" view, sorted by release date, but without the Title my brain has to decipher the pictures. For some posters/thumbs this is pretty easy but for others it's a bit harder. I guess my brain just processes words better than pictures. The experience in the Android (not Fire TV) client is EXCELLENT!

**Comment by desynergy** [comment]
Add me to this list.   I'm trying Jellyfin for the first time and I've been Googling on how to bring the titles up under the thumbnails.

**Comment by TotoCon** [comment]
I really love the app and JF in general. But titles under pictures is a must have thing imo.
Also show the year of release instead of the pg rating.

**Comment by xenio** [comment]
I would love this feature to be included. I tried by myself to edit the source code but i am not able to :(

**Comment by alexhuot1** [comment]
I'm adding my voice to this ticket. It's really hard to navigate when you have a big library.

I got not android dev experience, but if anyone have some pointers in the code I might take a look and open a PR.

**Comment by lionking102** [comment]
I just installed JF on my Shield TV und was a bit shocked, that this is not possible. I really hope this is a feature that will be added soon.

**Comment by arknano** [comment]
Feels like an oversight, given the Web UI shows this by default!

**Comment by nielsvanvelzen** [comment]
Closing as duplicate of #654
