### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by protik77** [jellyfin/jellyfin-androidtv#178]
I have been running jellyfin in docker for couple of weeks. Recently I restarted my docker container and the playback suddenly stopped working. From the logs it seems it's a `ffmpeg` error. The same file that was working is not working anymore. Here's the `ffmpeg` [log](https://pastebin.com/EdQEwU1E). Also [log](https://pastebin.com/UcJUNwBB) from the server. This happens only when running from Android TV app. Plays fine from the browser.

My jellyfin server version is 10.4.0 and Android TV version is 0.10.0g .

**Comment by thornbill** [comment]
Fixed by https://github.com/jellyfin/jellyfin-androidtv/pull/184
