### ISSUE TITLE
Don't show Next Up when no TV has been watched yet

### ISSUE THREAD

**Issue by branches78** [jellyfin/jellyfin-androidtv#1780]
### Describe the feature you'd like

It's annoying that it gets added automatically every time I exit the app after I previously removed them from there.

The only content added automatically to that channel should be the one in the "Continue Watching" row, nothing else.

Thank you.

**Comment by nielsvanvelzen** [comment]
You can change which apps show up in Android's Play Next in the system settings (the category should be named something like "home" or "channels").

**Comment by branches78** [comment]
> You can change which apps show up in Android's Play Next in the system settings (the category should be named something like "home" or "channels").

No!, I don't want to turn it off because the "continue watching" content won't be added automatically...

**Comment by branches78** [comment]
> You can change which apps show up in Android's Play Next in the system settings (the category should be named something like "home" or "channels").

I don't want to turn it off because the "continue watching" content won't be added automatically anymore 😭

Please add an option to turn it off inside Jellyfin or remove that functionality altogether.

Thank you.

**Comment by branches78** [comment]
Now that I remember, there is something you can do to the "Next Up" row which is something I requested to Emby devs as well and it was implemented before they decided to merge it with the "continue watching row:

The "Next Up" row should remain hidden until an episode of any TV show is played, then the "Next Up" row appears automatically with that TV show and once I exit the app the content can be added to the "Play Next" channel automatically as it currently does.

Can you do that please?????

Thank you.

**Comment by branches78** [comment]
The above is something that needs to be implemented in the server of course.

Thank you.

**Comment by nielsvanvelzen** [comment]
I believe this feature should be implemented in the server, not the client.

**Comment by branches78** [comment]
> I believe this feature should be implemented in the server, not the client.

Yes, you are right, should I create a new issue there or you are going to move this one?

**Comment by nielsvanvelzen** [comment]
Feature requests for the server should be posted to https://features.jellyfin.org

**Comment by branches78** [comment]
This seem to be implemented in recent versions of the Jellyfin server which reflects in all apps, is that correct?

**Comment by branches78** [comment]
The feature request related to this topic has so far 9 upvotes, how many do you need to implement this?

It's really annoying to say the least.

https://features.jellyfin.org/posts/1665/dont-show-next-up-when-no-tv-has-been-watched-yet
