### ISSUE TITLE
server discovery broken in master?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1789]
### Describe the bug

If i compile from `release-0.13.z` server discovery works against 10.8.
If i compile from `master` server discovery don't work.

### Application version

master

### Where did you install the app from?

Sideloaded APK

### Device information

Z9X

### Android version

Android 9

### Jellyfin server version

10.8

**Comment by nielsvanvelzen** [comment]
Only 10.8 is supported on the master branch

**Comment by Andy2244** [comment]
> Only 10.8 is supported on the master branch, so it might not find a 10.7 server.

```
Jellyfin server version

10.8
```

I'm talking about 10.8, as noted the official release will find the server, if i build from master it wont?

**Comment by nielsvanvelzen** [comment]
Ok weird, do you see anything strange in the app logs? Also, did you try it from a physical device or emulator?

> Btw what do i have to change if i wanted to build a versions thats still 10.7 compatible?

Build the release branch

**Comment by Andy2244** [comment]
> Ok weird, do you see anything strange in the app logs? Also, did you try it from a physical device or emulator?

physical device, need to check logs, trying to build via wsl/debian atm and see if that helps

> Build the release branch

i assumed this is just some gradle properties setting i can change?

**Comment by nielsvanvelzen** [comment]
No the release branch is a git branch. release-0.13.z is current.

**Comment by Andy2244** [comment]
> No the release branch is a git branch. release-0.13.z is current.

So i would have to backport any changes to the release-0.13.z branch, if i wanted to build for 10.7?

So for the upcoming 0.14 will you drop 10.7 support or also have to backport stuff from master?

**Comment by nielsvanvelzen** [comment]
0.14 will only support 10.8.1 and newer. We plan to release it near the end of July. We might push one final update to 0.13 with some changes before that.

**Comment by Andy2244** [comment]
ah ok i understand, so you drop backward compatibility

**Comment by Andy2244** [comment]
@nielsvanvelzen ok did just retest with fresh checkouts of works `release-0.13.z` and `master`, without any modifications. 
0.13 = works
master = broken

Any ideas, i don't see any obvious discovery related change?
