### ISSUE TITLE
Duplicate user. can’t be deleted (blank property page).

### ISSUE THREAD

**Issue by michaelkrieger** [jellyfin/jellyfin-androidtv#1790]
### Describe the bug

On androidtv latest version. I have two identically named users. Clicking on the current user (last login 2022) shows the option to remove it. Clicking on the second user (last login 2021) just displays a blank property page. As such, I can’t delete the duplicate user.

I assume I can delete the server and login again, but it’s still a bug that I can’t remove this second user entry.

list of users
![C2417DED-E36F-4261-9F6C-E7E41A8B4218](https://user-images.githubusercontent.com/7321259/174461970-abb485ff-780f-456c-b809-6717333356e7.jpeg)

property page of 2021 user
![B5915926-E4E7-4373-AE62-C5FA4AF43C0B](https://user-images.githubusercontent.com/7321259/174461980-84059924-72a1-4b6d-87af-9583eff9ca86.jpeg)

 

### Application version

0.13.6

### Where did you install the app from?

Google Play

### Device information

Nvidia shield

### Android version

?

### Jellyfin server version

10.8.0

**Comment by nielsvanvelzen** [comment]
I'm not sure how this can happen. Do you have a list of steps so I can reproduce?

**Comment by atjbramley** [comment]
I also have this.

I believe it'll happen if you add a Jellyfin server, add the user on the TV, remove the server, reinstall the server at the same IP, then connect again via the TV.

https://user-images.githubusercontent.com/71517198/182026346-5dbfd57c-80c2-438e-a096-098d901bcb98.mp4

![DSC_2448](https://user-images.githubusercontent.com/71517198/182026363-a2e5f5f5-4d21-4fd5-8202-4e0aa1997f1d.JPG)

Please see attached media!

**Comment by nielsvanvelzen** [comment]
I've made some changes that should help debug this problem. They should be included in 0.14. when updated, sign in to your server once (e.g. open the home screen) and then follow the same steps as in your video. The app should now crash instead of showing an empty preferences screen. A crash log should now be available in your server that contains information to debug the problem.

**Comment by atjbramley** [comment]
I'm afraid that I'm unable to perform any more testing, as I noticed this at my parents' house!
Hopefully the pic and video and the thought of what might have caused it help though.
