### ISSUE TITLE
Exoplayer transcoding 7.1 audio "audio channels not supported"

### ISSUE THREAD

**Issue by morkyy** [jellyfin/jellyfin-androidtv#1792]
### Describe the bug

I believe this used to work, unsure when it broke but currently any 7.1 file of any audio format (eac3, Dolby truehd etc) will always transcode when using exoplayer with "audio channels not supported" as the transcoded reason on the server.

Libvlc works as expected, direct playing all 7.1 audio. 
Tested on Nvidia shield pro with latest app and 10.7 server.

### Application version

0.13.x

### Device information

Nvidia shield pro

### Android version

Latest

### Jellyfin server version

10.7.7

**Comment by exterrestris** [comment]
Same issue with 10.8.1 server

**Comment by michaelkrieger** [comment]
See #1400 for the same issue with a lot more detail.

**Comment by mueslimak3r** [comment]
resolved by #1869
