### ISSUE TITLE
Adding Intro Skip button

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#1800]
### Describe the feature you'd like

ConfusedPolarBear wrote an plugin to fingerprint episodes and also have an API that could be called to return the info. It would be great if we could have a "Skip Intro" button when playing episodes.

Plugin : [Github](https://github.com/ConfusedPolarBear/intro-skipper)
API Info : [API Info](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/api.md)

**Comment by nielsvanvelzen** [comment]
We have no intention to add plugin specific api's. We can add this feature when the API is a part of the server, which is something that might happen with 10.9.
