### ISSUE TITLE
Playback speed does not work when using ExoPlayer

### ISSUE THREAD

**Issue by xtrandom** [jellyfin/jellyfin-androidtv#1803]
### Describe the bug

1. Select ExoPlayer as preferred media player
2. Play media
3. Update playback speed to something obvious (e.g. to 0.25 or 2.0)
4. Playing speed does not change (continued to play at 1.0 regardless of selected playback speed)

Playing speed works when LibVLC is selected as media player (even though it has lagging issues; and I prefer using ExoPlayer because aspect ratio feature is not available/implemented when using LibVLC)

### Application version

0.13.6

### Device information

Amazon Fire TV Stick (3rd Gen)

### Android version

Fire OS 7.2.8.5

### Jellyfin server version

10.7.7

**Comment by sourpatched** [comment]
Update your Jellyfin server to 10.8.1 and try again.

**Comment by xtrandom** [comment]
> Update your Jellyfin server to 10.8.1 and try again.
> 
> If you have the web gui login and post the logs, that'll make things easier.

I would like to wait a bit longer before upgrading to 10.8.x

Wouldn't this issue be with the ExoPlayer rather than the server since it works with LibVLC?

I'll try to post logs when I get a chance.

**Comment by sourpatched** [comment]
I use exoplayer and I don't have this issues, I am running the latest of everything.

**Comment by xtrandom** [comment]
> I use exoplayer and I don't have this issues, I am running the latest of everything.

Thank you for that! Perhaps I will try and upgrade to 10.8.x. I'll try and check logs.

**Comment by sourpatched** [comment]
It's why I suggest an upgrade, Just tested 0.25x and 2.00x again and it works for me.

Have you tried other media?

**Comment by tohn** [comment]
I'm having the same issue even with everything updated.
