### ISSUE TITLE
{\an8} tag support for srt

### ISSUE THREAD

**Issue by Dnkhatri** [jellyfin/jellyfin-androidtv#1804]
### Describe the bug

Although {\an8}  not in srt specifications but it has been adopted by most video players and works with them. Even if positioning support is not added atleast the {\an8}  tag should be hidden though in my opinion {\an8} tags have sort of become part of the spec due to adoption by most of the major video players like vlc, mpv, mpc etc. 

### Application version

0.14

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield  2015

### Android version

Android 11

### Jellyfin server version

10.8

**Comment by liimee** [comment]
any updates here? or workarounds?

**Comment by nielsvanvelzen** [comment]
From my understanding the SRT format does not have tags like `{\an8}` in it's format, it feels like something from the SSA format. So that's why we likely won't support this. I'd recommend using a subtitle format that does support these kinds of tags.

**Comment by Dnkhatri** [comment]
> From my understanding the SRT format does not have tags like `{\an8}` in it's format, it feels like something from the SSA format. So that's why we likely won't support this. I'd recommend using a subtitle format that does support these kinds of tags.

The tags are not part of the official specs but as most players support these tags they have become part of the spec by default. They even work correctly in the jellyfin android app if you use exoplayer instead of webplayer but with the same exoplayer in android tv it does not work. Please add the support in the app for these tags though I am using kodi addon on my android tv and jellyfin-mpv-shim on my pc so its not that important to me but I still think this should be fixed in the app.

**Comment by nielsvanvelzen** [comment]
Ok thanks for explaining. Properly implementing those tags is not easy with the current subtitle rendering code so I've made a change that will hide the tags instead. We'll leave the issue open to potentially implement the positional tags.

**Comment by nielsvanvelzen** [comment]
A subset of SSA tags, including the `\an8` tag, will now work in SRT starting with 0.18.
