### ISSUE TITLE
No way to update UserConfiguration via java/kotlin api?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1806]
```
    public void UpdateUserConfiguration(String userId, UserConfiguration configuration, EmptyResponse response) {
        response.onError(new UnsupportedOperationException());
    }
```
I'm trying to implement the missing UserConfiguration stuff, since its kinda weird that a user has to use the webclient just to setup audio/subtitle preferences. Yet i can't seem to find a way to actually update those settings on the server?

Is there maybe a direct "command" way to-do this, just for the specific settings fields `(AudioLanguagePreference, SubtitleLanguagePreference, PlayDefaultAudioTrack, SubtitleMode)` instead of the whole UserConfiguration class.

**Comment by nielsvanvelzen** [comment]
You can use the `api.userApi.updateUserConfiguration()` function in the SDK.

https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/master/jellyfin-api/src/commonMain/kotlin-generated/org/jellyfin/sdk/api/operations/UserApi.kt#L206

**Comment by nielsvanvelzen** [comment]
Closing as this is not an Android TV issue. For further questions about the SDK (not the apiclient which is unsupported) you can use our SDK repository (https://github.com/jellyfin/jellyfin-sdk-kotlin) or ask in chat (https://matrix.to/#/#jellyfin-dev-android:matrix.org).
