### ISSUE TITLE
Can we develop a compatible version client of Android 4 or lower?

### ISSUE THREAD

**Issue by HolmesLiu** [jellyfin/jellyfin-androidtv#1811]
### Describe the feature you'd like

Jellyfin service suite is a very good open source project. It provides us with a great movie viewing experience. It can process high bit rate videos to the corresponding devices at any time. However, I think that with the continuous iterative update of the devices, the new devices have lower requirements for the decoding and integration of the server. There are enough software for such devices to replace most of jellyfin's functions, such as Kodi. On the contrary, many old devices require the server to decode and integrate data. Their functions are limited, so they cannot decode high bit rate resources, and they must not install too much software. It happens that jellyfin does not provide sufficient support for such devices, and the system versions of the vast majority of old devices are also below Android 5.0. Therefore, it is hoped that more clients supporting such devices can be added, In this way, the value of jellyfin can be brought into full play, and more users can use it and promote it.

**Comment by nielsvanvelzen** [comment]
The first version of Android TV is based on Android 5. Also, a lot of our used libraries require Android 5 or newer. So we won't be lowering our minimun version requirenent.
