### ISSUE TITLE
 jellyfin-androidtv 0.13.6 compatible with Jellyfin 10.8.1 ?

### ISSUE THREAD

**Issue by 3zmana** [jellyfin/jellyfin-androidtv#1817]
### Describe the bug

Hello,

Since I installed jellyfin 10.8.1 I can't connect to it with the application for android TV.
The application doesn't detect the server on the network and when I manually enter the server IP it doesn't work either. However, if I use a web browser on my android TV and enter the local IP address of the jellyfin server it works without any problem.

I wonder if the android TV application is compatible with jellyfin 10.8.1 ?

### Application version

0.13.6

### Where did you install the app from?

Google Play

### Device information

Xiaomi Mi TV P1 32

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
Version 0.13.6 is compatible with Jellyfin 10.7.0 and newer. This includes the most recent 10.8.1 release.

**Comment by 3zmana** [comment]
Thank you for your answer. After multiple tests with jellyfin 10.7.7 and 10.8.1 the problem was the network configuration of the jellyfin server.

**Comment by jpdmostwanted** [comment]
Can you explain what was the configuration issue at the server? I am facing same issue.
