### ISSUE TITLE
Some embedded subtitles in mkv make lag or image drop when appears after language changed

### ISSUE THREAD

**Issue by Skuair** [jellyfin/jellyfin-androidtv#1823]
### Describe the bug

Some of my 1080 mkv with embedded subtitles (SUBRIP format), not all, have problem with subtitles when changing audio language.

First, and this could be another bug, when i play a media (not sure if it is all), the media starts with the first language but in the audio menu, the second language is selected.
For example, in my media i have french (first position) and english. I start the movie, the audio is french but the selector is set on english. So i have to switch to french again, and then, to switch to english to have really english.
But, when i switch to language the first time (so, french to french in fact because of the bug), it seems the player restart and returns to the the current position but from this moment, subtitles are problematics.
They look like a little bit blurry or stacked, and for each new text appearing, the video drops few images by freezing maybe 200-300ms.

Not all mkv with embedded SUBRIP make that behaviour. Maybe my other movies don't have the bug because of the available audio in the media, i dont' know. I don't have a lot of medias with several audio tracks, most of the time it is english only.

You can see attached 2 screenshots.
The first one is when i start the media, so the first audio track is running (but the wrong selected in the menu) : subtitles are correct, and respect my settings of the app (like size and alignment is left).
The second one is when i just switched to french again (first language in menu) to have the ability to switch after to the right language. You can see the kind of blurry/stacked fonts if you zoom in, and size is not respected, alignment is centered.

I hope I am clear in this description, it is quite hard to explain with writting.

Setup: jellyfin server on a Synology NAS DS220+ in docker, the jellyfin client is on Android TV Sony Bravia KD-49XD8005.
For these files, streaming is direct play and media player is defined on auto on the app, so I suppose it is using exoplayer.
![GoodSubtitles](https://user-images.githubusercontent.com/49756503/177847956-3b532c0d-d05d-47eb-aeca-939bf3616322.jpg)
![BadSubtitles](https://user-images.githubusercontent.com/49756503/177848002-9ef2db6d-c940-4c0d-86c2-feb57d665513.jpg)

### FFmpeg logs

```shell
No ffmpeg logs, maybe because of direct play ?
```

### Media info of the file

```shell
The Title
Conteneur: mkv
Chemin: /media/XXX.mkv
Taille: 4327 MB

Vidéo
Titre: 1080p H264 SDR
Codec: H264
AVC: Yes
Profil: High
Niveau: 40
Résolution: 1920x1080
Ratio d'aspect original: 16:9
Entrelacé: No
Images par seconde: 23.976025
Débit: 8277 kbps
Profondeur en Bit: 8 bit
Plage vidéo: SDR
Video range type: SDR
Format de pixel: yuv420p
Images de référence: 1
NAL: 4

Audio
Titre: French - Dolby Digital+ - 5.1 - Default
Langue: fre
Codec: EAC3
Répartition: 5.1
Chaînes: 6 ch
Débit: 640 kbps
Débit échantillon: 48000 Hz
Défaut: Yes
Forcé: No
Externe: No

Audio
Titre: English - Dolby Digital+ - 5.1
Langue: eng
Codec: EAC3
Répartition: 5.1
Chaînes: 6 ch
Débit: 768 kbps
Débit échantillon: 48000 Hz
Défaut: No
Forcé: No
Externe: No

Sous-titre
Titre: Forced - Fre - Par défaut - Forcé - SUBRIP
Langue: fre
Codec: SUBRIP
Défaut: Yes
Forcé: Yes
Externe: No

Sous-titre
Titre: French - SUBRIP
Langue: fre
Codec: SUBRIP
Défaut: No
Forcé: No
Externe: No
```

### Application version

0.13.6

### Device information

Sony Bravia KD-49XD8005

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by Skuair** [comment]
I noticed that sometimes there is the same behavior of lag video and exactly same blurry/stacked subtitles in VLC app. So maybe something related to libvlc ?

**Comment by Skuair** [comment]
Sometimes, it happens a double subtitles: one correct and the one blurry that make slutters.
![Uploading PXL_20220722_192049953.jpg…]()

**Comment by Debouelesmorts** [comment]
"the video drops few images by freezing maybe 200-300ms." Same problem here on Android TV (Box android) with Lib/Vlc. I will try in a few days with another box (Nvidia Shield), but I think I will encounter the same problem. It's very annoying because Lib/Vlc is the only player inside the application that can read all formats without encoding.

**Comment by Skuair** [comment]
For information, i switched weeks ago the setting "favorite media player" in the app from "auto" to "exoplayer", and it seems I don't have the problem anymore. So i suppose that the auto mode was taking LibVLC i don't know.

**Comment by Debouelesmorts** [comment]
Yes, the problem is only with Lib/Vlc, which is the only one of the two internal players that can play most formats directly. I have many different formats for videos and subtitles that Exoplayer cannot read directly. It's a pity, because without this problem, the Jellyfin application would be able to play everything (unlike the Plex application) without having to jump from an internal player to an external one or from one application to another (I think of Kodi)...

**Comment by Skuair** [comment]
Just for my curiosity, what kind of video formats are not readable by exoplayer in your case ?

**Comment by Debouelesmorts** [comment]
In all cases, i480, any DVD Remux, worse if they have Vobsub subtitles (which is almost always the case) will require transcoding. And it takes a lot of resources.

**Comment by Codex-** [comment]
Have been encountering this and was hoping it'd go away in 10.9, this issue should be re-opened as it's still occurring
