### ISSUE TITLE
No APP icon and name on Android 5.0 TV

### ISSUE THREAD

**Issue by sxs08** [jellyfin/jellyfin-androidtv#1836]
### Describe the bug

I tried to install several versions of APP for my TV, it seems that only the version below 0.11.5 can show the APP icon and name on TV.

### Application version

0.13.7

### Where did you install the app from?

Sideloaded APK

### Device information

WHALEY TV

### Android version

Android 5 

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
I can't find much results searching for "WHALEY TV". Is the device actually running Android TV as operating system?

**Comment by sxs08** [comment]
Right now, 0.11.5 can work on the TV, but often crash.

**Comment by nielsvanvelzen** [comment]
The app uses a vector drawable on Android 5. This is supported by the platform and default app launcher in AOSP. Your manufacturer probably modified the launcher/created a custom one with no support for this way of rendering app icons. Not much we can do about. You should contact the manufacturer to report an issue with their product.

Also, I don't recommend using older versions of the app as they are unstable and unsupported.

**Comment by sxs08** [comment]
> The app uses a vector drawable on Android 5. This is supported by the platform and default app launcher in AOSP. Your manufacturer probably modified the launcher/created a custom one with no support for this way of rendering app icons. Not much we can do about. You should contact the manufacturer to report an issue with their product.
> 
> Also, I don't recommend using older versions of the app as they are unstable and unsupported.

Thanks for your help. I use the Kodi with Jellyfin addons on my TV, it seems work well.
