### ISSUE TITLE
Connection speed auto-detection is off by a lot, resulting in transcodes.

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1851]
### Describe the bug

The "auto" speed detection logic is off by a factor of 200 on my system.
My system has a wired gigabit connection, that can actually deliver ~700Mbit. Yet the auto detection logic logs ~3.5Mbit via "Auto".
This results in unnecessary transcodes at "Auto" settings, so i had to turn this logic off in my fork, given how unreliable it is.

So not sure whats the issue here, but i recommend to set the default to 100Mbit and just remove/disable the auto detection logic.

### Logs

`Auto bitrate set to: 3534349`

### Application version

0.13

### Where did you install the app from?

Sideloaded APK

### Device information

Z9x

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by jamesmurphy746** [comment]
I fear this isn't a bug in the android tv app but rather some difference in version 10.8 server.. has this started happening since you updated the server?

**Comment by Andy2244** [comment]
Its happening in every server version i tried 10.8, 10.8.1,2,3,4. The detection code is fundamentally flawed on Android and should not be used at all.
