### ISSUE TITLE
Crash on same user, different servers.

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1872]
### Describe the bug

Just handing this down from a user report, he reports crashes if he setup a identical server and than tries to use it or switch.

"Good news found the issue: In Authentication > Automatic Sign In - if set as a user to auto login and the same user exists for other server, this causes this crash issue"

### Application version

0.14.0

### Where did you install the app from?

Sideloaded APK

### Device information

Zidoo

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by Andy2244** [comment]
Not really, was hoping you have a idea whats going wrong there?
Can try to reproduce the crash, if you have no idea?

**Comment by nielsvanvelzen** [comment]
I have no idea why this happens, that's why I'd appreciate the logs. With the recent crash reporting changes they should be auto-uploaded to the latest used Jellyfin server or the first one connected to after the crash.

**Comment by sourpatched** [comment]
> Not really, was hoping you have a idea whats going wrong there? Can try to reproduce the crash, if you have no idea?

@Andy2244 The logs help more then anything as it has more info in what went wrong, If your server isn't local you can replace the the IP address in the logs with "IP" 

To view the ATV logs go to Jellyfin web --> Dashboard --> Logs (web/index.html#!/log.html) and there should be something named  upload_org.jellyfin.androidtv_0.14.0-beta.1 click on this to view the log.
