### ISSUE TITLE
Problem with 5.3K 60fps HEVC video

### ISSUE THREAD

**Issue by SuperMitic** [jellyfin/jellyfin-androidtv#1905]
### Describe the bug

1. Amazon FireStick 4K. I am able to decode 4K 60fps video without any issues, but when I open 5.3K 60fps videos recorded on Gopro, the FireStick isn't able to decode them. 
2. If I set maximum bandwith in setting up to 30Mbit then it transcode the video and it works (i Suppose in 1080p or 2160p), but if i set 40Mbit or higher it doesn't work. It is not a network bandwith problem, because i am able to decode the 4K 60Mbit videos fine. 
3. Jellyfin with video larger than 4k should ask the server to transcode the video to a supported resolution (4K) even with higher bitrate. So that even if I set the bitrate bandwidth to 100Mbit the video must be transcoded from 5.3K to 4K.

### Media info of the file

```shell
General
Complete name                            : I:\DCIM\100GOPRO\GX010005.MP4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 1
Codec ID                                 : mp41 (mp41)
File size                                : 380 MiB
Duration                                 : 53 s 370 ms
Overall bit rate                         : 59.8 Mb/s
Encoded date                             : UTC 2022-03-07 16:08:14
Tagged date                              : UTC 2022-03-07 16:08:14
xyz                                      : +44.4286+011.2662/

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L6@Main
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 53 s 370 ms
Bit rate                                 : 59.5 Mb/s
Width                                    : 5 312 pixels
Height                                   : 2 988 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 59.940 (60000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Bits/(Pixel*Frame)                       : 0.063
Stream size                              : 378 MiB (100%)
Title                                    : GoPro H.265
Language                                 : English
Encoded date                             : UTC 2022-03-07 16:08:14
Tagged date                              : UTC 2022-03-07 16:08:14
Color range                              : Full
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : hvcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 53 s 355 ms
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Nominal bit rate                         : 48.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 1.21 MiB (0%)
Title                                    : GoPro AAC  
Language                                 : English
Encoded date                             : UTC 2022-03-07 16:08:14
Tagged date                              : UTC 2022-03-07 16:08:14

Other #1
ID                                       : 3
Type                                     : Time code
Format                                   : QuickTime TC
Duration                                 : 53 s 370 ms
Bit rate mode                            : Constant
Frame rate                               : 59.940 (60000/1001) FPS
Time code of first frame                 : 16:23:39:51
Time code of last frame                  : 16:24:33:13
Time code, striped                       : Yes
Title                                    : GoPro TCD  
Language                                 : English
Encoded date                             : UTC 2022-03-07 16:08:14
Tagged date                              : UTC 2022-03-07 16:08:14

Other #2
Type                                     : meta
Duration                                 : 53 s 369 ms
Bit rate mode                            : Variable
Duration_LastFrame                       : -685
```

### Application version

0.13.7

### Device information

Amazon Fire TV Stick 4K

### Android version

FireOS 6.2.8.9

### Jellyfin server version

10.8.1

**Comment by themegaphoenix** [comment]
Is the firestick able to play the video from another player i.e. kodi?
How is the CPU usage when transcoding to 40Mbit in the same file?

The reason I am asking is because CPU.SOC usually have a dedicated chip to decode video files, and they might not be able to handle 5k. Depending in your answer we might be able to rule out something.

I disagree with your third point. Some devices have odd resolutions, limiting it to a set ones is not a good idea, specially if the content you are watching also has odd resolutions or diffrent from what we typically assume (https://en.wikipedia.org/wiki/1080p). 
Imagine now your 4k tv broke and the only tv on hand you had is 720p. Do you want the Jellyfin to transcode to 720p or do you want the firestick to handle the conversion from 4k to 720p? I would like the latter

**Comment by SuperMitic** [comment]
> Is the firestick able to play the video from another player i.e. kodi? How is the CPU usage when transcoding to 40Mbit in the same file?
> 
> The reason I am asking is because CPU/SOC usually have a dedicated chip to decode video files, and they might not be able to handle 5k. Depending in your answer we might be able to rule out something.
> 
> I disagree with your third point. Some devices have odd resolutions, limiting it to a set ones is not a good idea, specially if the content you are watching also has odd resolutions or different from what we typically assume (https://en.wikipedia.org/wiki/1080p). Imagine now your 4k tv broke and the only tv on hand you had is 720p. Do you want the Jellyfin to transcode to 720p or do you want the firestick to handle the conversion from 4k to 720p? I would like the latter

No, the firestick is not able to decode the 5.3k HEVC because its chip is created to decode up  to 4K 60fps HEVC. In fact with the 4K 60fps it doesn’t have any problem. Jellyfin should detect that the firestick is not able to decode video larger than 4K and ask the server the video up to 4K so that the firestick is able to decode it.

**Comment by Andy2244** [comment]
ok will pickup this issue, since i'm already working on some other FireStick fixes.

**Comment by SuperMitic** [comment]
> ok will pickup this issue, since i'm already working on some other FireStick fixes.

Do you have any news? I have this problem even with the 0.14.1 version. My firestick is not able to reproduce the 5.3k HEVC video and it doesn't ask the server to transcode the video to a supported resolution (4K HEVC).

**Comment by Andy2244** [comment]
> Do you have any news?

Still working on some other stuff, but yes its a client issue. The code currently wrongly assumes if the device has 4k support it can also play higher resolutions. Which is wrong for most devices, so we need to add a explicit 8k check for those and trigger transcodes for >4k.
