### ISSUE TITLE
season count not right in view

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-androidtv#1911]
### Describe the bug

there's something wrong with the seasons count view above 10 seasons
every thing under 10 is ok but from season 11 the count starts again from 1
example if i have 11 seasons season 11 starts after season 1
so you got season 1-11-2-3-4-5-6-7-8-9-10 in the view
this was also in version 13 and further

### Application version

0.14.3

### Where did you install the app from?

Sideloaded APK

### Device information

xsarius q8 tv box

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
Do you mean the seasons are not in the correct order?

**Comment by satstarter** [comment]
yes if you go to series select a serie with more then 10 seasons
the first season is season 1 but the season after season 9 stands beside season 1
so you get season 1-10-11-12-2-3-4

**Comment by sourpatched** [comment]
I find no such issue on 0.14.0 beta2, Everything is in order for me.

**Comment by satstarter** [comment]
oke then where is my problem?
i have my series setup this way on the server directory season name under that directory's season 1 and so on
and it gives me the problem after season 10 is this then maybe because i use space between season and number?

**Comment by sourpatched** [comment]
Best practice would be Tv show -> season # -> title S01E01.mp4

What does Jellyfin Web GUI say?

**Comment by satstarter** [comment]
ok lookt at it its a server problem or setting?
have tried it and web gui also wind mediaplayer give me the same result
set up is tv show ->season # -> title SE01E01.mkv

**Comment by sourpatched** [comment]
Since it also shows up the same in Web GUI, it's not an issue with ATV app.

I am thinking wrong setting in Jellyfin?

**Comment by satstarter** [comment]
yes it must be i think
gone see if i can find what it is
but dont know where to look because can't think wich setting is responyble for this
thanx for your reply's

**Comment by sourpatched** [comment]
Check season meta settings under edit metadata

**Comment by satstarter** [comment]
its the metadata not comming in like it must be
if i go to change metadata there is nothing in season nr if i fill in this myself
the count is right ?

**Comment by sourpatched** [comment]
Screenshot would help if you're able too.

**Comment by satstarter** [comment]
![view1](https://user-images.githubusercontent.com/91093114/181914853-80e5ca04-a5b8-48d8-b40a-69412b2b65bf.jpg)
![view2](https://user-images.githubusercontent.com/91093114/181914863-afe6562c-862e-4418-b0a6-5c99ec0747df.jpg)
view 1 is how it looks like
view 2 is season empty after scan and title is season #

**Comment by satstarter** [comment]
for some reason season # stays empty in metadata

**Comment by sourpatched** [comment]
Wonder if there is an issue with the Dutch language string?
@nielsvanvelzen Does this make any sense to you?

**Comment by sourpatched** [comment]
> for some reason season # stays empty in metadata

@satstarter Does season 10 have metadata links to IMDB, TV Maze?

**Comment by satstarter** [comment]
@sourpatched episodes yes imdb and tvdb
the whole season itself no

**Comment by sourpatched** [comment]
TV Maze ID for season 10 is 97371 once entered and saved refresh metadata

**Comment by satstarter** [comment]
i did this and also tried to set language in english and land uk
but the season nr stays empty whit or without language change

**Comment by nielsvanvelzen** [comment]
I think the problem is just that you don't have a sortname (sorteer titel) or season numbers (seizoensnummer) set so the server can't properly sort the seasons. You've also said the issue happens in the web ui so this isn't an issue with the app.

> Wonder if there is an issue with the Dutch language string?
> @nielsvanvelzen Does this make any sense to you?

Unlikely, translation strings should not change behavior

**Comment by satstarter** [comment]
@nielsvanvelzen  yes your wright but i cant figure out which setting is responsyble
my setup in the server is tv show -> season # -> title S01E01
so the seasons directory's have a number and the # 1->9 or given ok
in the view (not in metatdata) in metadata season # stays empty so what's causes this?
thanx in advance

**Comment by satstarter** [comment]
the metadata of a season give's as title season nr and not the actually title !n this case hawaii five-0
and the season nr stays empty verry strange i do a little more tests later today
@sourpatched  is your server setup a directory name tvshow -> a directory season# -> files S01E01.mp4 and so on??
and is the view alright??

**Comment by satstarter** [comment]
oke figured it out the numbering of the seasons 1 -> 9
has to be 01 -> 09 then everything is alright so no bug thanx for the help guys ;)
