### ISSUE TITLE
can't add server

### ISSUE THREAD

**Issue by moreje** [jellyfin/jellyfin-androidtv#192]
I upgraded to the latest app (0.10.2), latest server running on linux docker, but I can't add my server.
I always get unavailable server message (while login is OK on Web App)
other question: is the discover servers on LAN feature available, because it does not work for me and enter server settings with my remote is long when you have to do it multiple times...
thanks

**Comment by thornbill** [comment]
Have you removed the base url in the network config for the server as outlined in the [release notes](https://github.com/jellyfin/jellyfin/releases/tag/v10.4.1)?

The autodiscovery feature should work, but it requires host networking mode to be enabled for the container.

**Comment by moreje** [comment]
I've enabled Host networking instead of bridge...but still not shows up :(
concerning the base url? should I remove it in my server settings? or add it to the address in android app? the release notes are not clear to me... I understand that removing it is a workaroud...but can't I have a normal way?

**Comment by anthonylavado** [comment]
@moreje You can either add it to every client, like `http://example.com:8096/jellyfin`

**Comment by dkanada** [comment]
@moreje did you get it working?

**Comment by thornbill** [comment]
Closing since no additional information has been provided. Let us know if you still have issues!
