### ISSUE TITLE
LiveTV - in the 'Other channels' section 'null' word shows up under every channel's name in the top of the screen.

### ISSUE THREAD

**Issue by osscombat** [jellyfin/jellyfin-androidtv#1922]
### Describe the bug

LiveTV - in the 'Other channels' section 'null' word shows up under every channel's name in the top of the screen. 

![null_sign](https://user-images.githubusercontent.com/30649369/182387144-55f5411b-fb7a-45d2-86bb-184db8b5356e.jpg)

### Application version

0.13.7

### Where did you install the app from?

Google Play

### Device information

Mibox 4

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
I believe this was fixed in 0.14. Can you test that?

**Comment by osscombat** [comment]
No, that was similar, but on the pop-up channels list. Later I've found out the same when simply hovering over Other channels.

**Comment by osscombat** [comment]
> I believe this was fixed in 0.14. Can you test that?

sure, but no offer to update to 0.14 from google play yet

**Comment by osscombat** [comment]
yep, this is fixed in v0.14, thanks!
