### ISSUE TITLE
Add change log to app menu under About

### ISSUE THREAD

**Issue by sourpatched** [jellyfin/jellyfin-androidtv#1927]
### Describe the feature you'd like

Under about, click on Jellyfin app Version and a popup box shows the change log or What's new in this update.
Also after upgrade, a what's new box should pops up with some info about the new update?

**Comment by nielsvanvelzen** [comment]
This is unlikely to happen because the changelog is not in the source (and with the current build logic it won't be possible to add it easily). The average user also doesn't really care about the updates, so I think the current approach (blog post for major releases, changelogs on github) is fine.
