### ISSUE TITLE
audio not selectable if 2 movie versions are present

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-androidtv#1928]
### Describe the bug

if i got 2 movie versions movie - 4k hdr
                                       movie - 1080p
movie 4 k has only 5.1 sound
movie 1080p has 5.1 or 2.0 sound
in both exoplayer or libvlc the audio of movie 1080p is not selectable
while testing a single movie gives the select button
but not with 2 versions of the same movie

### Application version

0.14

### Device information

tv box

### Android version

Android 9

### Jellyfin server version

10.8.3

**Comment by VampiricAlien** [comment]
When you select the movie vision, once playing can you select the audio track?

**Comment by satstarter** [comment]
yes this seems to be ok now thanx
