### ISSUE TITLE
Crash Reporting for Android TV

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#193]
## Reasoning

* Providing logs on Android TV devices can be challenging for users (requires Android developer tools `adb`)
* Issues can be challenging to replicate
* Hardware specific issues can be impossible to replicate
* Stack traces can make finding issues much easier

## Concerns

* Relies on a centralized service
* Collects user data
* Uses a third-party service (https://www.tracepot.com)
* Crash reports may contain sensitive or identifiable data
* Will require a privacy policy update for App Stores

## Implementation Details

* Uses a common open-source Android library [ACRA](https://github.com/ACRA/acra).
* ~Crash reporting will be **OPT-IN** and disabled by default in the App Settings~ Due to concerns over crashes on application startup not being captured, the crash reporting dialog will be enabled by default.
* ~After opting-in,~ A dialog prompting the user to submit a crash report will be displayed by default. The user can then choose to send or not send the individual crash.
  * An additional option to always submit crash reports without prompting will be present in App Settings
  * The dialog will clearly indicate that the collected data is submitted to tracepot.com and that crash reporting can be disabled in the App Settings.
* https://github.com/ACRA/acra/wiki/AdvancedUsage#letting-your-users-control-acra
* Reports will be sent to tracepot.com for developer review
* Crash reports are retained for 30 days

## Sample Dialog

![screen](https://user-images.githubusercontent.com/3450688/70590971-7207ff00-1ba2-11ea-89c3-f7f28fa263e8.png)

## Sample Report

https://gist.github.com/thornbill/e778c0d0dc7b7452d9ceca8fb69aa902

**Comment by protik77** [comment]
I agree that to make the app better, this is required. And I like the fact that developers approach towards this. I am all in for this.

Question, is this a temporary thing or it is here to stay if included?

I have two concerns,

- When a third party used, do they own the data? Or the Jellyfin developers? We have to make sure that Jellyfin developers own the data.
- Can we make sure the sensitive or identifiable data is being purged and not stored anywhere?

**Comment by anthonylavado** [comment]
@protik77 It’s possible that it could be removed at a later date. Right now, the variety of devices this application has to support means there’s a bit of uncertainty all over the place.

Regarding your first point:
“You retain any and all of your rights to any Content you submit, post or display on or through the Service and you are responsible for protecting those rights.” - [Tracepot Terms of Service](https://www.tracepot.com/terms.html) (In this case the “you” is us, as the Jellyfin project)

I don’t know enough to comment on the second one.

**Comment by KeepBotting** [comment]
Opt-in is fine by me. Would be nice if we can examine the data before it is sent, as well. I deployed DokuWiki recently and their opt-in [popularity contest](https://www.dokuwiki.org/_media/plugin:popularity-plugin.png) was very well-presented.

**Comment by gerroon** [comment]
Opt in is fine  but I would not opt in myself as long as a third party is used, given that one's collection is actualyl a quite personal.

**Comment by sparky8251** [comment]
@gerroon and that is why we want to allow for opt in. Unfortunately, I don't think we can handle collecting this data ourselves in the era of the GDPR. Would be burdensome for us as a group of volunteers.

**Comment by AndreasGB** [comment]
I agree that users should always be in control of whether they want to submit a particular report and anything auto-submitting by default would be a no-go, but completely disabling by default seems too agressive in the other direction. 

I would per default let users decide once a crash happened whether they would like to report it, and have permanently disabling this question as a preference.

**Comment by thornbill** [comment]
There were concerns over not being able to collect crash reports if the reporting is disabled by default and the app crashes on launch. I have updated the description above to reflect that the reporting dialog will now be **OPT-OUT** but will include a notice that the data is submitted to tracepot.com and that the dialog can be disabled via App Settings.

Please let us know if you have objections to this approach!

I agree that it might be nice to be able to view the report details before submitting them, but it doesn't seem to be supported by ACRA's default interfaces. It may be something we can implement in the future via a custom integration.

**Comment by thornbill** [comment]
Thanks for all the feedback! Crash reporting will be included in the next release! :shipit:
