### ISSUE TITLE
Direct Play not working anymore since 10.8.x on FireTV stick and ROKU

### ISSUE THREAD

**Issue by halictuz** [jellyfin/jellyfin-androidtv#1948]
### Describe the bug

**Describe the bug**

Direct Play not working anymore, it worked before Jellyfin 10.8.x though. Same for the ROKU, same issue there. 

**To Reproduce**
Use FireTV Stick with latest server version of Jellyfin (mp4, mkv, h264, h265, AC3, DTS) etc. nothing works anymore without transcoding it. Which wasn't the case before the latest version. Same issue for ROKU too. Workaround for FireTV stick currently is  by using an external player like VLC for example, because Exo Player and libvlc just doesn't play anything anymore without transcoding enabled on Server side. Some files with xvid/divx run, but no sound etc. Which is weird because EVERYTHING ran perfectly fine before Jellyfin updated to 10.8.x since then Direct Play is pretty much completly broken. 

**Expected behavior**
Video files play with Direct Play and no transcoding like they did before Jellyfin 10.8.x

**Dietpi Raspberry Pi4 Server**
As I said, nothing changed at the server or client side, only Jellyfin was updated and now, Direct Play doesn't work anymore, anywhere. Expect when you use third party clients like VLC. Then it works perfectly fine. 

**Error message is always the same**

"Video format can not be played" 

### Logs

ffmpeg version 5.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --toolchain=hardened --enable-cross-compile --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu-
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100

### Application version

latest

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire TV Stick

### Android version

latest

### Jellyfin server version

10.8.3 (latest)

**Comment by nielsvanvelzen** [comment]
You're saying this issue applies to both the Android TV app and the Roku one. That implies the issue lies within the server and not the client. Also, we don't have a version called "latest".

**Comment by Andy2244** [comment]
If you play a file, check the server logs and copy&paste the lines containing the "ffmpeg" command-lines, this way we can check what the client did request and what the server send as result.

**Comment by PickleMasterDX** [comment]
I am having the same issue. Running JellyFin 0.13.7 (jellyfin-androidtv) and JellyFin server version 10.8.3 on a Windows 10. 
I can no longer play any videos on my FireTV Stick (Fire OS 5.2.8.9).
I did attempt to update the app on the firetv stick, I succesfully updated the server itself.
See Log for FFmpeg.
[FFmpeg.Remux-2022-08-10_22-17-58_21f2164495c3e5385df1ce22af5e8fd2_b849f1d0.log](https://github.com/jellyfin/jellyfin-androidtv/files/9300006/FFmpeg.Remux-2022-08-10_22-17-58_21f2164495c3e5385df1ce22af5e8fd2_b849f1d0.log)
1

**Comment by Andy2244** [comment]
@PickleMasterDX does this only happen for 10bit HEVC files or also for normal 8bit/h264 ?

**Comment by PickleMasterDX** [comment]
@Andy2244 
I am not 100% sure if it only happens with 10bit HEVC or 8bit/h264.
You are right that it is a 1st Gen FireTV stick. Is there any way to manually change the encoder?
I have swapped between the inbuild options to see if that made a difference. Sadly not. (I dont know the technical names, i think it was exolib and libVLC, I also tried installing VLC and swapping to external app but that played only a part of the audio and froze the image).
Its just weird that it was working less than a month ago now it doesnt, I cant only assume the fireTV stick updated at some point or the jellyfin app updated.
Thank you for your help!

**Comment by PickleMasterDX** [comment]
UPDATE:
It just started working again!
Super weird, I didnt touch any of the settings. I tried the media that I was having trouble with again. No issue.
I will keep you posted if there is an issue again.
Thank you!

**Comment by Ansjuh** [comment]
I am experiencing the same on a Kindle Fire with the jellyfin-androidtv 0.13.7 app. The server side is running Jellyfin 10.8.2 and 10.8.3 in Docker. The same video works when I use Jellyfin 10.8.1 on the server.

**Comment by RkcCorian** [comment]
I also have trouble playing any video. Server is 10.8.3-6 on Synology NAS. Client is 0.13.7 on Fire TV Cube.

**Comment by RkcCorian** [comment]
I also have trouble playing some videos, not all. Server is 10.8.3-6 on Synology NAS. Client is 0.13.7 on Fire TV Cube.

**Comment by chr-zz** [comment]
> I am experiencing the same on a Kindle Fire with the jellyfin-androidtv 0.13.7 app. The server side is running Jellyfin 10.8.2 and 10.8.3 in Docker. The same video works when I use Jellyfin 10.8.1 on the server.


> I also have trouble playing some videos, not all. Server is 10.8.3-6 on Synology NAS. Client is 0.13.7 on Fire TV Cube.


> The FireTV version is 0.13.7. The latest version on the repo here is 0.14.1.
>
>I uninstalled the Amazon FireTV version and downloaded the latest .apk version from github and installed it. This works. Who >would've thought that the latest version works?
>
>I'm not sure why the FireTV amazon version is so crazy outdated and not being updated though.
>
>But I guess, that would be a good idea otherwise other people will run into the same issues, too.
>
>So no server issue, the issue is that the amazon FireTV app wasn't updated for a long time.
>
>The ROKU version still doesn't seem to work correctly with Direct Play though. But there it's using the latest version of the >github repo at least.

Interesting topic, which I can't really say for myself.

I'm still waiting for the update via amazon. Currently still 0.13.7
But I would say that apart from a few exceptions, everything works as usual in direct play.
here are the last 2 days from the playback recording plugin..

BTW.. Fire TV Stick 4k

![Unbenannt-1](https://user-images.githubusercontent.com/110332945/185740543-5fd19220-e8f6-48fe-a762-8c21a6f82c26.jpg)
