### ISSUE TITLE
Support installing to external storage

### ISSUE THREAD

**Issue by aloop** [jellyfin/jellyfin-androidtv#1955]
### Describe the feature you'd like

My Sony TV has a pretty paltry amount of internal storage available, it would be nice if this app could support installing to external storage.

Reading through https://developer.android.com/guide/topics/data/install-location seems to indicate it would be a fairly simple change to a manifest file (should just require adding `android:installLocation="auto"` to the right spot from what I can tell), but I'm not familiar with Android development at all so there may be some other gotchas. Compatibility looks like it should be fine, seems to date back to Android 2.2 (API level 8).

**Comment by nielsvanvelzen** [comment]
I think allowing the installation on external storage should be fine but we do use some system features that are on the "Applications that should NOT install on external storage" list in the linked documentation, specifically the account manager used for authentication in the app and I believe there are some services but those aren't long running.
Considering the account manager is only used by the app, not externally, everything should behave as expected though.
