### ISSUE TITLE
"back" key inside change/user activity ends app, instead of going back to home?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1960]
### Describe the bug

- start app -> home-screen
- navigate to change user
- in the user selection screen, just hit "back"
- app closes instead of returning to home

### Application version

0.14

### Where did you install the app from?

Sideloaded APK

### Device information

Z9X

### Android version

Android 9

### Jellyfin server version

10.8.3

**Comment by nielsvanvelzen** [comment]
This js intensed behavior

**Comment by Andy2244** [comment]
> This is intended behavior

What? Any activity that has its root at the homescreen should ideally return to the homescreen if possible, so how can this be intended?
I did enter the user selection by error, its just one more "up" key after all and than since i don't wanted to change the user i expected the "back" action to take me well back, not exiting the app.

**Comment by nielsvanvelzen** [comment]
When you choose to switch the user you are no longer signed in. If you want to go back to the home screen you need to select the user you want to use and sign in (depending on your settings like auto login and the remember function).

**Comment by Andy2244** [comment]
ok thanks this explains why.
I already use a "double back to exit" logic in my version, since this makes sense for a main mediacenter app.
Need to setup PR for it, but atm bogged down with cleaning up all the other upcoming PR's.
Will try to add a special info toast that explains the back-> exit or select user action in this activity.
