### ISSUE TITLE
Specials naming is inconsistent with web client

### ISSUE THREAD

**Issue by tydog98** [jellyfin/jellyfin-androidtv#1961]
### Describe the bug

When looking at specials the AndroidTV client says "S00EXX", while the web client just says "Special". It would be nice if these were consistent.

### Application version

0.14.0

### Where did you install the app from?

Google Play

### Device information

Tivo Stream 4k

### Android version

AndroidTV 10

### Jellyfin server version

10.8.3

**Comment by nielsvanvelzen** [comment]
Do you have a screenshot of both the app and the web client so I can pinpoint the location where this happens?

**Comment by tydog98** [comment]
Specials Folder:
![IMG_20220813_150632](https://user-images.githubusercontent.com/45440255/184507542-79586c32-2dae-4252-b048-ff5d2156c463.jpg)
vs
![Screenshot from 2022-08-13 15-07-27](https://user-images.githubusercontent.com/45440255/184507548-3ecd7bc1-9e08-4679-941b-94657015ce56.png)

In Season 1:
![IMG_20220813_150653](https://user-images.githubusercontent.com/45440255/184507555-809403f5-9fcf-4c61-b7d2-37545654763a.jpg)
vs
![Screenshot from 2022-08-13 15-07-36](https://user-images.githubusercontent.com/45440255/184507559-91ec8105-3722-4bf3-ab07-b88a44cdcc58.png)

**Comment by nielsvanvelzen** [comment]
Thanks, issue is fixed with #1972. It will then show "[seriesname] special" as title and the episode name as subtitle.

**Comment by tydog98** [comment]
Well that was quick, awesome.
