### ISSUE TITLE
use of AsyncImageView without a compatible Theme.AppCompat?

### ISSUE THREAD

**Issue by Andy2244** [jellyfin/jellyfin-androidtv#1969]
### Describe the bug

We use AsyncImageView and some other AppCompat widget's, yet we don't derive from Theme.AppCompat?

So instead of `Theme.Leanback`, we should use `Theme.AppCompat.Leanback`?
Than instead of `FragmentActivity`, we should derive from `AppCompatActivity`?

This combination should give the best compatibility and we still can use support fragments?

### Application version

0.14

### Where did you install the app from?

Sideloaded APK

### Device information

Z9X

### Android version

Android 9

### Jellyfin server version

10.8.3

**Comment by nielsvanvelzen** [comment]
AFAIK we don't really benefit much from AppCompat right now so I didn't bother migrating stuff over. I try to use it for new stuff though.

**Comment by Andy2244** [comment]
Sure, but the new stuff uses `AppCompatImageView`, so why are we not using `Theme.AppCompat.Leanback`?
The log gets flooded with the related error on every image.load call.
