### ISSUE TITLE
Settings visibility and aspect ratio for Live TV tiles

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin-androidtv#197]
The settings menu within the libraries and the guide are not well readable:
![image](https://user-images.githubusercontent.com/14938497/68860966-de4e2a80-06ea-11ea-8281-b2cff4b992a7.png)
![image](https://user-images.githubusercontent.com/14938497/68860973-e1e1b180-06ea-11ea-8935-35a8e3c62a13.png)

Also the aspect ratio for the Live TV and Recordings tiles are incorrect
![image](https://user-images.githubusercontent.com/14938497/68861213-616f8080-06eb-11ea-87d3-3ff7d9151353.png)

**Comment by Nickbert7** [comment]
The menue is fixed, but the tiles are still not correct.
Should I create a separate issue?

**Comment by nielsvanvelzen** [comment]
A new issue for the tile issues is preferred (if there's none yet), thanks.
