### ISSUE TITLE
"Server needs to be updated" even though server is up to date

### ISSUE THREAD

**Issue by JohnnyDeeee** [jellyfin/jellyfin-androidtv#1974]
### Describe the bug

Upon logging in through my Android TV i get the following error:
![image](https://user-images.githubusercontent.com/9005496/184527620-6356e47a-94b6-4bd5-8b95-de709cfe5b95.png)

even though my server is up to date:
![image](https://user-images.githubusercontent.com/9005496/184527638-c687bdff-c6b1-408d-8adc-87de1f04f685.png)

here is some more info from my tv app:
![image](https://user-images.githubusercontent.com/9005496/184527662-0d5ff75c-b2da-4926-b4ff-f41d6f7b33a4.png)

I have recently updated the docker image (jellyfin runs in a docker container) and restarted the container, maybe i'm missing additional steps?

### Application version

0.14.1

### Where did you install the app from?

Google Play

### Device information

Philips TPM191E

### Android version

Android 9

### Jellyfin server version

10.8.3

**Comment by nielsvanvelzen** [comment]
The client caches server information for about 10 minutes. So after updating the server it can take a few minutes to be able to connect again.

**Comment by justbendev** [comment]
**This is such a bad design...**
Jellyfin should have a minimum of backward compatibility.
Denying access because of a slightly outdated server version is ridiculous. 

_Especially when it's not a serious security update_
