### ISSUE TITLE
SSL-Handshake fails on Firetv OS6 with self-signed-certificate including intermediate

### ISSUE THREAD

**Issue by spammads** [jellyfin/jellyfin-androidtv#1977]
### Describe the bug

1. Open Jellyfin on FireTv
2. Add Server
3. Put https://jellyfin.example.local as url

I installed a root certificate on the stick.
My reverse proxy serves a 3-staged-certificate including the intermediate.
Problem occurs only with the Firestick-App from the App-Store. If I visit the Jellyfin-Url in Silk-Browser TLS works. If i sideload the android-app TLS also works.

With Firetv OS 6 the structure of the app has to tweaked to respect a self-signed-user-cert (via manifest and security.xml)

### Application version

0.13

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Firestick 4K

### Android version

Fire Os 6

### Jellyfin server version

10.8.4.0

**Comment by MWI-JP** [comment]
Seeing the same issue on my Fire TV Cube, latest OS (7.x.x). Also side loaded multiple versions of the Android TV app, which returned the same error message on all attempts.

I am able to access the same server from my Roku, phone, and PCs, all on the same network.

**Comment by garfunkel** [comment]
I have the same issue on the Android TV app (LetsEncrypt HTTPS).

**Comment by MadKillerChicken** [comment]
IMO there should be an option to ignore certificate validation exceptions. Defaulting to disabled and with a warning when enabled. It's bad enough that there's no way to install custom certificates on Android TV.

**Comment by thornbill** [comment]
No official clients include baked in support for self signed certificates. It is too easy to get valid certificates through services like let's encrypt these days.

**Comment by nielsvanvelzen** [comment]
Like said in a previous comment by @thornbill, we will not support self-signed certificates in the app itself. You should add it to the certificate store in the OS when possible or use a "proper" certificate.

Closing as wontfix

**Comment by MadKillerChicken** [comment]
> I am open for suggestions as I am somewhat not a heavy expert on this topic

AFAIK your only options are to use something like letsecrypt or to switch client OS. Everything except AndroidTV (and maybe Apple stuff?) works. I have my custom CA installed on Windows and on Android (not TV), both work.

**Comment by gclawes** [comment]
Android TV doesn't work because it specifically forbids the installation of user-installed CA certificates at the system level (unlike regular android).   Probably to avoid content piracy, but it's a huge drawback for Chromecast and other Android TV devices.

> No official clients include baked in support for self signed certificates. It is too easy to get valid certificates through services like let's encrypt these days.

@thornbill this isn't the case for internal networks with private DNS, that use case is effectively dead in the water with the Jellyfin Android TV app because of the above restriction.
