### ISSUE TITLE
Windows Defender Detect Trojan in 0.14.1

### ISSUE THREAD

**Issue by EVOTk** [jellyfin/jellyfin-androidtv#1982]
### Describe the bug

Hello,
i'm in Windows 10, and Windows Defender detect a trojan in "[jellyfin-androidtv-v0.14.1-release.apk](https://github.com/jellyfin/jellyfin-androidtv/releases/download/v0.14.1/jellyfin-androidtv-v0.14.1-release.apk)"

I re-downloaded it, but the problem is back.

![screenshot-2](https://user-images.githubusercontent.com/45015615/184880883-ff192885-6079-4e10-92c1-5492b014539d.png)

### Application version

0.14.1

### Device information

Xiaomi Box 3

### Android version

Adnroid 10

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment]
This is not an issue with the app.
