### ISSUE TITLE
Amazon Appstore version (Jellyfin for Fire TV) is still at 0.13.7

### ISSUE THREAD

**Issue by jivanpal** [jellyfin/jellyfin-androidtv#2001]
### Describe the bug

Not sure whether "bug" is the right label for this.

The version of "Jellyfin for Fire TV" in the Amazon Appstore appears to still be 0.13.7. I don't know if you are already aware of this and/or if Amazon is still reviewing 0.14.0, but I have been checking for the last few weeks since the release of 0.14.0 to see if an update is available, and it has still not been published.

Thanks for all the hard work! 😊

### Application version

0.13.7

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire TV Stick (3rd Gen)

### Android version

Fire OS 7.2.9.2 (PS7292/2982)

### Jellyfin server version

N/A

**Comment by nielsvanvelzen** [comment]
We're aware of this. Amazon is really slow with the review process, nothing we can do about it but wait.

**Comment by nielsvanvelzen** [comment]
0.14.2 is now live on Amazon
