### ISSUE TITLE
Remember multiple users credentials without having to sign in

### ISSUE THREAD

**Issue by madjam002** [jellyfin/jellyfin-androidtv#2004]
### Describe the feature you'd like

I've added multiple users to the Jellyfin Android TV app and set "Automatic Sign In" to "Disabled" so that every time we open the app it prompts us for who's watching.

I'm trying to replicate the Netflix who's watching screen, but with Jellyfin the credentials are only remembered for the last used user. If I click on another user / profile, it prompts me to do quick connect again.

It would be great if there was an option to remember the credentials / access token of all users added to the app to enable a quick user / profile switching experience, or maybe recently used users (e.g so if a user hasn't been used in a significant period of time, it would prompt for quick connect, else it would work without authentication).

**Comment by nielsvanvelzen** [comment]
The "Automatic Sign In" feature is meant to not save credentials. If you don't want to re-enter credentials for users you should enable auto sign in. To quickly switch between users just press the profile picture on the top right to show the user selection screen.

**Comment by madjam002** [comment]
@nielsvanvelzen Thanks for your reply.

>  If you don't want to re-enter credentials for users you should enable auto sign in.

To clarify, is this separate from the "Automatic Sign In" option in the Android TV app settings menu? As like you mention this doesn't save credentials.

> To quickly switch between users just press the profile picture on the top right to show the user selection screen.

I can click on the profile picture in the top right like you suggest to see the user selection screen, but if I press on any user other than the currently selected one, it prompts for quick connect authentication even if I've logged in with those users in the past. This feature request is about adding the ability to remember those user sessions for multiple users so that you can switch between users without needing to re-authenticate with quick connect (unless I've misunderstood and this feature already exists!)

**Comment by nielsvanvelzen** [comment]
So what you want is to:
1) Always select a user when you start the app
2) Remember the login (so no need to password/quickconnect)

To do that you should make sure this checkbox is disabled:
![image](https://user-images.githubusercontent.com/2305178/185998365-1ad591ff-0ba7-41a9-8a64-67f6497f1fb6.png)

And set automatic sign in to disabled like so:
![image](https://user-images.githubusercontent.com/2305178/185998429-519e84ce-53cf-44a9-9e74-77cbd9c34875.png)

That should give that behavior, if you need to re-enter a password that is a bug and we'll need to fix that.

**Comment by madjam002** [comment]
Perhaps this is a bug then, as I need to login every time I switch between users.

Here's a bit more detail:
0.14.2 app version
10.8.4 Jellyfin version
Automatic sign in - disabled
Always ask for credentials - off

- Open Jellyfin app
- See "Who's watching" screen with two users, both on the same server
- Click on user 1 (who was last logged in)
- Logged in automatically (expected behaviour)
- Click on profile picture in top right
- See "Who's watching" screen again
- Click on user 2
- Not logged in, asked to log in with quick connect
- Complete authentication with quick connect
- Click on profile picture in top right
- See "Who's watching"
- Click on user 1 again
- Not logged in, asked to log in with quick connect (not expected behaviour as I was previously logged in as this user)

So yes it doesn't seem possible to switch between two or more accounts without having to log in every time you switch.

**Comment by nielsvanvelzen** [comment]
That doesn't seem right. You should not have to sign in again. Few questions:

1) What device are you using and what Android version is it running?
2) Did you change the "Maximum number of simultaneous user sessions" options for any of the users? (you can find it when modifying the user in the server dashboard, default is 0)

**Comment by madjam002** [comment]
Chromecast with Google TV
Android TV OS 10 (latest updates installed)

All users are set to maximum number of simultaneous user sessions 0 / disabled

**Comment by nielsvanvelzen** [comment]
When you open the system settings and go to "accounts & sign-in", do you see both the accounts you've signed in with in the Jellyfin app? Can you try removing both, sign in again in the app and see if the issue is fixed?

**Comment by steelersfan7** [comment]
> Perhaps this is a bug then, as I need to login every time I switch between users.
> 
> Here's a bit more detail: 0.14.2 app version 10.8.4 Jellyfin version Automatic sign in - disabled Always ask for credentials - off
> 
>     * Open Jellyfin app
> 
>     * See "Who's watching" screen with two users, both on the same server
> 
>     * Click on user 1 (who was last logged in)
> 
>     * Logged in automatically (expected behaviour)
> 
>     * Click on profile picture in top right
> 
>     * See "Who's watching" screen again
> 
>     * Click on user 2
> 
>     * Not logged in, asked to log in with quick connect
> 
>     * Complete authentication with quick connect
> 
>     * Click on profile picture in top right
> 
>     * See "Who's watching"
> 
>     * Click on user 1 again
> 
>     * Not logged in, asked to log in with quick connect (not expected behaviour as I was previously logged in as this user)
> 
> 
> So yes it doesn't seem possible to switch between two or more accounts without having to log in every time you switch.

just to add here, I did set the settings as shown above and it does ask me to quick connnect for all users that were not the last signed in user.

**Comment by nielsvanvelzen** [comment]
After looking at the code multiple times I think I found the issue. When using Quick Connect to sign in, all other sessions of the same device will be deleted by the server. Using password login doesn't have this problem.
I'm looking into a fix.

**Comment by madjam002** [comment]
Just side loaded the latest version and it works an absolute treat, thanks so much!
