### ISSUE TITLE
Covers can't display when connet to an IPV6 server.

### ISSUE THREAD

**Issue by yzhEric** [jellyfin/jellyfin-androidtv#2018]
### Describe the bug

The covers of the movies can't display properly when connet to an **IPV6** server.
However, it works properly when on the LAN.
![Screenshot_20220827-081746](https://user-images.githubusercontent.com/52406665/187112940-956a47b0-0d3a-4dc2-b9e1-14385eebbd46.jpg)

### Application version

0.14.2

### Where did you install the app from?

Google Play

### Device information

Oneplus 7 Pro; SonyTV

### Android version

Android 11; Android 9

### Jellyfin server version

10.8.4

**Comment by yzhEric** [comment]
for all images

**Comment by nielsvanvelzen** [comment]
Do you use the IPv6 address directly (and if so, in which notation?) or use DNS?

**Comment by nielsvanvelzen** [comment]
Ah, found the issue. This appears to be a limitation of the image library we use: https://github.com/bumptech/glide/issues/4369
I'm planning to switch to something else so it might be fixed in the next release. In the meantime you should use IPv4 or DNS.

**Comment by yzhEric** [comment]
Thanks!
I tried DNS and it works good.
