### ISSUE TITLE
HEVC playback: black screen on Fire TV 

### ISSUE THREAD

**Issue by daniel1v** [jellyfin/jellyfin-androidtv#2024]
### Describe the bug

I have issues playing my HEVC media files on my FireTV Gen 1 device. The sound plays, but the screen stays black. Also the app gets unresponsive after some time.

I am forcing Exoplayer for playback, because libVLC does not passthrough 5.1 Dolby Digital and Dolby Digital Plus. (Maybe I should create a separate issue on this.). Also I do use direct streaming, without transcoding.

On my Android TV everything works fine with the exact same setup, it is only my FireTV device having this issue.

### Media info of the file

```shell
Container: mkv
Größe: 2231 MB

Audio
Titel: Surround 5.1 - Ger - Dolby Digital+ - Default
Sprache: ger
Codec: EAC3
Darstellung: 5.1
Kanäle: 6 ch
Bitrate: 480 kbps
Abtastrate: 48000 Hz
Standard: Yes
Erzwungen: No
Extern: No

Untertitel
Titel: Ger - Standard - PGSSUB
Sprache: ger
Codec: PGSSUB
Standard: Yes
Erzwungen: No
Extern: No

Video
Titel: 1080p HEVC SDR
Codec: HEVC
Profil: Main
Level: 120
Auflösung: 1920x800
Seitenverhältnis: 2.40:1
Zeilensprungverfahren: No
Bildrate: 23.976025
Bitrate: 3025 kbps
Videobereich: SDR
Video range type: SDR
Pixelformat: yuv420p
Referenz-Frames: 1

Audio
Titel: Surround 5.1 - Eng - Dolby Digital+
Sprache: eng
Codec: EAC3
Darstellung: 5.1
Kanäle: 6 ch
Bitrate: 480 kbps
Abtastrate: 48000 Hz
Standard: No
Erzwungen: No
Extern: No

Untertitel
Titel: Ger - PGSSUB
Sprache: ger
Codec: PGSSUB
Standard: No
Erzwungen: No
Extern: No
```

### Application version

0.14.2

### Device information

Amazon FireTV Gen. 1

### Android version

FireOS 5

### Jellyfin server version

10.8.4

**Comment by VampiricAlien** [comment]
https://www.amazon.com/Amazon-Fire-TV-Previous-Generation/dp/B00CX5P8FC
Content Formats Supported:
Video: H.263, H.264, MPEG4-SP, VC1
Audio: AAC, AC-3, E-AC-3, HE-A, PCM, MP3
Photo: JPG, PNG

HEVC (h.265) is not support on this Fire TV

**Comment by daniel1v** [comment]
That might be true for the native player, but has nothing to do with my issue.

I am able to play these videos with kodi on this device, so Jellyfin should also be able to play it.
