### ISSUE TITLE
Can't Direct Play FLAC Audio Track On ExoPlayer

### ISSUE THREAD

**Issue by S3KiR0** [jellyfin/jellyfin-androidtv#2039]
### Describe the bug

When i Try To Play A Movie With a FLAC Audio Track, But It Transcodes it instead of direct play it, i have no issues with Plex with that 

### Application version

0.14.2

### Device information

Hisense 60A53FUA

### Android version

Android 9

### Jellyfin server version

10.8.1

**Comment by VampiricAlien** [comment]
"The video stream is compatible with the device, but has an incompatible audio format (DTS, Dolby TrueHD, etc.) or number of audio channels. The video stream will be repackaged losslessly on the fly before being sent to the device. Only the audio stream will be transcoded."

TranscodeReason=AudioCodecNotSupported 
https://jellyfin.org/docs/general/clients/codec-support.html Listed as supported

Android 11
