### ISSUE TITLE
HTML login message shows OBJ 

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-androidtv#2051]
So I set an HTML img element with a width CSS property as a login message, to show my own logo, and on Android TV it shows a little square with OBJ.

Could you add support for HTML rendering in the login message?

Jellyfin server version 10.8.4
Jellyfin Android TV app version 0.14.3

**Comment by nielsvanvelzen** [comment]
The server description supports Markdown & HTML with exceptions, no links or images are supported. This is intended.
