### ISSUE TITLE
Global back button

### ISSUE THREAD

**Issue by Phoenix-004** [jellyfin/jellyfin-androidtv#2053]
### Describe the feature you'd like

Currently, the back button on the remote is kinda broken.

If watching a show with say 8 episodes back to back (more than one episode really), upon completion, pressing the back button on your remote will not take you back to the home screen. There is basically no way to go back to the home screen unless you quit the app and restart it.

So what happens is that you will have to keep pressing back on the remote repeatedly, which will just scroll you through all the watched episodes of that series until you get back to the home screen.

A better solution would be to allow a long press back button that will just take you straight back to the Jelyfin home page. And this long pressback should work regardless of where in the app you are in.

**Comment by nielsvanvelzen** [comment]
When you keep watching a series, the back button should just close the player and you don't need to press back 8 times. This feels like a bug, can you explain each step your taking while watching so I can try to reproduce the problem?

**Comment by Phoenix-004** [comment]
1. Start Jellyfin App.
2. navigate to the show, usually from the next up/recently added list
3. watch an episode, at the end of the episode, press back to go back to the Episode info page (the one that has the play/resume...etc, icons).
4. select the next episode from that page, next episode list appears under the episode info page. Selecting the next episode takes you to the episode info page of the selected next episode.
5. Rinse and repeat.

An easier way to reproduce this.....  You do not even have to actually play anything.

Just pick any show, watched or unwatched. Navigate to a season, and select episode one. Once on the episode main page, you should see the next-up list at the bottom of the screen. Just select the net episode, that takes you to the landing page of that episode, ten select the net episode there too....and keep going.

Then now try and press back on your remote, it won't take you back to the home screen. You will be going back through every page you had opened.

If by close he player you mean pressing back when actually playing a video, yes that works. It closes the player and takes you back to the Play/resume info page for whatever you are playing. That is not what I am talking about.

**Comment by nielsvanvelzen** [comment]
Ok I understand your issue now. Normally when watching multiple episodes you'd use the autoplay feature or the skip button in the player. When you use those going back works as expected.

Going back, browsing to another page and then playing again will keep adding to the history. This will eventually be solved when we add a sidebar for quick navigation.

**Comment by Phoenix-004** [comment]
Thanks for the update. And yes, that is exactly the issue. Thing with the autoplay feature is that even if you use the timer to start earlier, there are a lot of shows that have petty long credits. So it's generally quicker to just back out of what you are playing and select the next episode.

Would be eager to get a sidebar :).

As I do have your attention, indulge me in asking a few other things as opposed to creating another report.

Content landing page customization; would it be possible to allow an option to darken, or brighten up the background fan art image t the specific media landing page? Eg. if you select a movie, it takes you to the landing page where you can choose play/resume....etc. There is a background image there and media info. Could a toggle be added in settings to allow us to change the brightness of that background image? Say in 20% increments.

And/or an option to maybe press up to remove the info on that landing page only leaving the background image or a timer where if let idle for a set amount of time, all that info fades out only leaving the background image.

In app volume control: Now this one I have mentioned years ago lol.... and i think its a big deal. We should b able to control volume in the jellyfin android app, independently of the Global TV volume settings. A good example f this is if using an app like Kodi.

Why this is important, is that if using your TV connected to ay a PC or games console, and also for the Youtube app, Netflix, HBO....etc. Using global volume settings tends to always result in a situation where stuff is either always too loud or not loud enough. It would be great if we could kinda just set the volume at say 30% on our TVs, but ten within the Jelyin app increase and reduce volume for just the app.

As I mentioned earlier, Kodi does this and has always done this. It could simply be mapped to the up and down arrows in the remote control and only active when playing media. And then pressing right or left or OK would instead bring up the on-screen display during media playback.

**Comment by nielsvanvelzen** [comment]
>  there are a lot of shows that have pretty long credits

You can skip to the next episode with the player controls, no need to exit the player or wait for the credits to end
