### ISSUE TITLE
Ambient mode is not supported

### ISSUE THREAD

**Issue by alkolome** [jellyfin/jellyfin-androidtv#2054]
### Describe the bug

If player is paused then ambient mode is activated to avoid displaying static images for extended periods. This is important for display technologies, such as OLED, which may be susceptible to screen burn.

Jellyfin Android TV player doesn't support this and keeps displaying home screen or paused video for hours.

All other media players and most Android applications such as Plex or Youtube do support ambient mode

Could you please add support for it? It'd be a small change and Google has all details explained here: https://developer.android.com/training/tv/playback/ambient-mode.

### Application version

0.14.3

### Where did you install the app from?

Google Play

### Device information

Sony Bravia 4K VH2

### Android version

Android 10

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment]
Screensaver support in the video player will be available in 0.16.
