### ISSUE TITLE
Auto max bitrate seems too low

### ISSUE THREAD

**Issue by TastyPi** [jellyfin/jellyfin-androidtv#2055]
### Describe the bug

When streaming on my local network 4K HDR video is being transcoded to lower the bitrate, despite it working perfectly now I've set the max bitrate explicitly. It was even transcoded to SDR.

i.e. with the max bitrate set to "Auto", high bitrate videos are transcoded. Setting the max bitrate explicitly fixes the issue.

I'm curious how "Auto" decides which bitrate to use, it's possible the client isn't realising it's connected to a local server (I have it behind an nginx reverse proxy). If setting the max bitrate exp

### Application version

0.14.3

### Device information

Sony Bravia KD-55X8509C

### Android version

Android 7

### Jellyfin server version

10.8.4

**Comment by TastyPi** [comment]
Not sure if it's related to the Chromecast app issue https://github.com/jellyfin/jellyfin-chromecast/issues/11

**Comment by nielsvanvelzen** [comment]
I don't recommend using the auto option. It works by doing a few speed tests to your server when the app starts, at that same time the app tries to load other stuff from the server which skews with the speed test results, causing the "detected bitrate" to be too low.

**Comment by TastyPi** [comment]
@nielsvanvelzen Would it be worth adding some text in the UI to make that clearer, like "Auto (not recommended)" or maybe even defaulting to 120 Mbits/s instead of Auto?

**Comment by nielsvanvelzen** [comment]
The default value is 100 Mbit/s since 0.12.

**Comment by TastyPi** [comment]
Oh interesting, I must have changed it to Auto in the past and forgot. How would you feel about having "Auto (not recommended)" or even just removing the Auto option completely?

Or I'm happy to just have this issue closed, since it sounds like my issue is I shouldn't have fiddled with that setting.

**Comment by nielsvanvelzen** [comment]
I hope to fix the auto setting eventually with #1057 so I think leaving it like it is right now is fine for now.
