### ISSUE TITLE
[Issue]: Library disabled from showing in home sections, still shows in Amazon TV app

### ISSUE THREAD

**Issue by cxen** [jellyfin/jellyfin-androidtv#2077]
### Please describe your bug

I have set certain libraries to not appear in the 'Latest Media' and 'Continue Watching' sections of the home screen. The setting is respected in the web ui and iOS apps but not on the Amazon Fire TV app.

### Jellyfin Version

Other

### if other:

10.8.4

### Environment

```markdown
- OS: Windows 10
- Clients: Amazon Fire TV
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by nielsvanvelzen** [comment]
What steps did you take to hide libraries? When I uncheck the "Display in home screen sections such as 'Latest Media' and 'Continue Watching'" checkbox for a library in my home display settings it works like expected.

**Comment by cxen** [comment]
The specific libraries have that option unchecked. It works as expected everywhere else except the Fire TV app home.

**Comment by james7132** [comment]
I'm also seeing the same thing for on a Sony Bravia TV with the app as well. Unchecked the aforementioned boxes and it is still showing suggestions from the hidden libraries.

**Comment by cxen** [comment]
This still happens with Jellyfin server 10.8.9 and the amazon fire tv app 0.15.3

**Comment by vortex91** [comment]
issue happening for me on 10.8.9 and firestick
