### ISSUE TITLE
Program Guide takes long time to load

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin-androidtv#21]
Program guide takes an awful long time to load on my Amazon Fire Stick Gen 1 over wifi and it takes a noticeable amount of time to load on my Android TV.  This may be something to look at the future with some sorts of optimizations or perhaps a smaller query for data based on less time.  I've got about 30 channels.  I can only imagine what it would be like for someone with many more than this.

**Comment by sourpatched** [comment]
@dinki v0.14.0 has a lot of support for live TV https://jellyfin.org/posts/android-tv-14/

**Comment by dinki** [comment]
Thanks @sourpatched  for the link.  I've switched to ChannelsDVR since but will take a look at the improvements.
