### ISSUE TITLE
Embedded subtitles cause stuttering

### ISSUE THREAD

**Issue by DemirG** [jellyfin/jellyfin-androidtv#2101]
### Describe the bug

One of the latest updates broke internal/embedded subtitles. Everyone they show up on screen there is micro stuttering. Ive tries the same video file with external srt subtitles and then it works fine.
Its a HEVC/x265 file.

Will return with logs.

### Logs

https://pastecode.io/s/8ud1nfy4

> `[2022-10-10 15:40:26.517 +00:00] [INF] [63] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2022-10-10 15:40:53.365 +00:00] [INF] [63] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "jelly". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2022-10-10 15:40:53.365 +00:00] [INF] [63] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-libVLC", Path="/media/serier/House of the Dragon (2022) [tvdb-371572]/Season 01/House of the Dragon - S01E05 - We Light the Way WEBRip-1080p.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) "media:/videos/3442e3d4-ff19-4a99-ade9-d3e4580e9556/stream.mkv?MediaSourceId=3442e3d4ff194a99ade9d3e4580e9556&Static=true&VideoCodec=hevc&AudioCodec=eac3&AudioStreamIndex=2&api_key=<token>&Tag=d9e9c252c376a32b150431d4c31556a1"
> [2022-10-10 15:40:53.581 +00:00] [INF] [16] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "jelly". EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
> [2022-10-10 15:40:53.582 +00:00] [INF] [16] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile="AndroidTV-ExoPlayer", Path="/media/serier/House of the Dragon (2022) [tvdb-371572]/Season 01/House of the Dragon - S01E05 - We Light the Way WEBRip-1080p.mkv", AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=AudioCodecNotSupported ) "media:/videos/3442e3d4-ff19-4a99-ade9-d3e4580e9556/master.m3u8?MediaSourceId=3442e3d4ff194a99ade9d3e4580e9556&VideoCodec=hevc,h264,hevc&AudioCodec=ac3,aac,mp3&AudioStreamIndex=2&VideoBitrate=8950889&AudioBitrate=384000&MaxFramerate=23.809525&api_key=<token>&RequireAvc=false&Tag=d9e9c252c376a32b150431d4c31556a1&SegmentContainer=ts&BreakOnNonKeyFrames=False&hevc-level=120&hevc-videobitdepth=10&hevc-profile=main10&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-maxrefframes=4&ac3-audiochannels=2&TranscodeReasons=AudioCodecNotSupported"
> [2022-10-10 15:40:54.694 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing" to "172.17.0.1" in 0:00:00.5895425 with Status Code 204
> [2022-10-10 15:40:58.073 +00:00] [WRN] [36] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.5491072 with Status Code 204
> [2022-10-10 15:41:06.102 +00:00] [WRN] [43] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.6581533 with Status Code 204
> [2022-10-10 15:41:15.368 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.7993467 with Status Code 204
> [2022-10-10 15:41:16.074 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.521425 with Status Code 204
> [2022-10-10 15:41:26.521 +00:00] [INF] [16] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2022-10-10 15:41:43.092 +00:00] [WRN] [63] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.5061256 with Status Code 204
> [2022-10-10 15:41:55.109 +00:00] [WRN] [37] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.5051869 with Status Code 204
> [2022-10-10 15:42:26.525 +00:00] [INF] [16] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.
> [2022-10-10 15:42:40.394 +00:00] [WRN] [46] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.7399475 with Status Code 204
> [2022-10-10 15:42:50.592 +00:00] [WRN] [16] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.8902413 with Status Code 204
> [2022-10-10 15:42:53.223 +00:00] [WRN] [43] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.5301447 with Status Code 204
> [2022-10-10 15:43:20.257 +00:00] [WRN] [53] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.5340038 with Status Code 204
> [2022-10-10 15:43:21.080 +00:00] [WRN] [53] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from "http://192.168.0.3:8096/Sessions/Playing/Progress" to "172.17.0.1" in 0:00:00.53366 with Status Code 204
> [2022-10-10 15:43:25.060 +00:00] [INF] [46] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app "Android TV" "0.14.4" playing "We Light the Way". Stopped at "421614" ms
> [2022-10-10 15:43:25.504 +00:00] [INF] [53] Trakt.ServerMediator: Playback stopped
> [2022-10-10 15:43:26.619 +00:00] [INF] [46] Emby.Server.Implementations.Session.SessionWebSocketListener: Sending ForceKeepAlive message to 1 inactive WebSockets.`

### Media info of the file

Video
Titel: 1080p HEVC SDR
Kodningsformat: HEVC
Profil: Main 10
Nivå: 120
Upplösning: 1920x1080
Bildförhållande: 16:9
Sammanflätad: No
Bildfrekvens: 23.809525
Bithastighet: 5413 kbps
Bitdjup: 10 bit
Video-omfång: SDR
Video range type: SDR
Pixelformat: yuv420p10le
Referensbildrutor: 1

Suttering:
Undertext
Titel: SDH - Eng - Default - SUBRIP
Språk: eng
Kodningsformat: SUBRIP
Förvald: Yes
Tvingade: No
Externa: No

Working:
Undertext
Titel: Undefined - SUBRIP - External
Kodningsformat: SUBRIP
Förvald: No
Tvingade: No
Externa: Yes

### Application version

0.14.4

### Device information

Sony Android TV 

### Android version

Android 10

### Jellyfin server version

10.8.1

**Comment by mueslimak3r** [comment]
In the log it shows that the `LibVLC` video player backend is being used. When it is used, it handles rendering embedded subtitles.

Can you try setting the app to use `Exoplayer` instead? You can find this in the app settings -> playback -> preferred video player.

Can you also test, with the preferred video player set back to 'LibVLC', changing the "refresh rate switching" setting? This can also be found in the app's playback settings. Please test for stuttering with this set to "disabled" and "scale on TV".

**Comment by DemirG** [comment]
Hi @mueslimak3r ,

I've upgraded to JF 10.8.4, problem is still there.


Genereal logfile of JF:
https://pastebin.com/F3ALtrL6

Exo Transcode, failed to start the video, retried a couple of times. 
https://pastebin.com/vrHfZPFi

LibVLC: As before, microstutter when playing with embedded subtitle, no problem with external subtitle.

LivVLC Resfresh rate switching set to "scale on TV": Hard to see if there were microstutters during play as the whole video seemed to run through mud. I would describe it as a lot of stutters/low FPS. This is with embedded subtitles. With external it ran better but not as god as when refresh rate switching was set to disabled. 

Did not get transcode logfiles when palying with LibVLC.

**Comment by DemirG** [comment]
@mueslimak3r is this issue being worked at? I've since I've opened this issue bought a new TV, a Sony X90K. But the same issue persists on the new TV. Embedded subtitles are stuttering, but as long as I have external subtites it's smooth as it should be.

**Comment by lrduncan** [comment]
I can confirm that this is also happening on my "onn. Android TV 4K UHD" box. I have the DietPi Jellyfin 10.8.8 installed and there is very subtle stuttering when a new subtitle line is displayed. Usually if it is a single line it is not very noticeable but is very noticeable if it is 3+ lines for that particular subtitle frame. External subtitles do not have this issue, only embedded. I can post logs if more are needed past what @DemirG has posted. x264 files are being used.

**Comment by gitrosers** [comment]
> I can confirm that this is also happening on my "onn. Android TV 4K UHD" box using Jellyfin Android TV app version 0.15.2. I have the DietPi Jellyfin 10.8.8 installed and there is very subtle stuttering when a new subtitle line is displayed. Usually if it is a single line it is not very noticeable but is very noticeable if it is 3+ lines for that particular subtitle frame. External subtitles do not have this issue, only embedded. I can post logs if more are needed past what @DemirG has posted. x264 files are being used.

For me exoplayer did not have much stuttering but libvlc always stuttered.  I was thinking of trying jellyfin again but it looks like the issue still persists.  It was the only major reason why I could not switch to jellyfin from emby.  I use android based TVs and properly working subtitles without stuttering on Android TV clients is a must.  Hopefully this can be resolved soon as Emby does not have this issue on their android tv clients.

**Comment by Burgess101** [comment]
Same behaviour was observed on my Shield TV.

**Comment by DemirG** [comment]
This issue is still present in latest JF server/Client.

**Comment by coldshouldermedia** [comment]
I just observed this issue on a "Chromecast with Google TV".

**Comment by matsnake86** [comment]
Hello, 

I am also observing this problem from amazon firetv app. However, the problem only shows up on 4k videos with embedded subtitles.

Could it be because the media is on a mechanical drive connected via usb3 ?

**Comment by hlarsen** [comment]
> Could it be because the media is on a mechanical drive connected via usb3 ?

I doubt it; I'm seeing the same stuttering on a Shield TV over NFS on a gigabit network. The same file (4K x265) in Kodi does not stutter at all on the same Shield TV, nor when played on a PC via VLC. The web client doesn't have this issue, thought I believe it is transcoding the file while the others are direct playing.

**Comment by DemirG** [comment]
Not USB media, media over LAN from Synology NAS.

**Comment by Shreyas-R** [comment]
I'm also facing this issue with LibVLC enabled in Jellyfin and I had faced a similar issue in the past with VLC Media Player as well on Android TV. It's been fixed recently according to the following git issue thread,
https://code.videolan.org/videolan/vlc/-/issues/27130

and not yet released to production I guess. Jellyfin should merge the latest LibVLC as soon as it is released and should release an update.

**Comment by DemirG** [comment]
@Shreyas-R that's a great find! Hopefully this issue can be fixed soon then. :)

**Comment by lrduncan** [comment]
Adding a comment to confirm this issue still persists using LibVLC for playback. Exoplayer does not seem to have the same issue but it has issues loading the subtitles sometimes so I would prefer to use LibVLC once this is fixed. Currently using arm64 10.8.13 server and latest v0.16.6 androidtv client.

**Comment by Beagon** [comment]
I still encounter this issue.

**Comment by AshotN** [comment]
Still an issue
