### ISSUE TITLE
can i choose picture quality on jellyfin-androidtv?

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin-androidtv#2106]
### Describe the feature you'd like

can i choose picture quality on jellyfin-androidtv?

**Comment by nielsvanvelzen** [comment]
Closing as this is not a feature request.

**Comment by Karmylr** [comment]
> Closing as this is not a feature request.

Where should I create that issue?

**Comment by nielsvanvelzen** [comment]
https://jellyfin.org/contact/
