### ISSUE TITLE
Adjust Subtitle Position

### ISSUE THREAD

**Issue by KSodR** [jellyfin/jellyfin-androidtv#2111]
### Describe the feature you'd like

There is currently no way to adjust subtitle position in the app or in exoplayer. As far as I understand this feature is supported in exoplayer.

This makes watching movies with subtitles in cinemascope/2.35 impossible since the lower subtitle will be off screen.

See example here:

![20220926_004304](https://user-images.githubusercontent.com/34838288/192743862-cffda32d-8a47-44a6-8200-2f1a47a2361a.jpg)

Thanks.

**Comment by ndonkersloot** [comment]
+1

An option to change subtitle position would be great!
