### ISSUE TITLE
crash on TMALL_magicBox

### ISSUE THREAD

**Issue by skyshino** [jellyfin/jellyfin-androidtv#2129]
### Describe the bug

1. open jellyfin client on TMALL_magicBox.
2. go to any film.
3. click the play.
4. crash

### Logs

[upload_org.jellyfin.androidtv_0.14.3_20221001133150_4efe2fce7a35430199c1ec15ab3f0142.log](https://github.com/jellyfin/jellyfin-androidtv/files/9690433/upload_org.jellyfin.androidtv_0.14.3_20221001133150_4efe2fce7a35430199c1ec15ab3f0142.log)
[upload_org.jellyfin.androidtv_0.14.3_20221001133214_f840bfa2468546318fe247b74fdc4456.log](https://github.com/jellyfin/jellyfin-androidtv/files/9690434/upload_org.jellyfin.androidtv_0.14.3_20221001133214_f840bfa2468546318fe247b74fdc4456.log)

### Application version

0.14.3

### Device information

TMALL_magicBOX_M13

### Android version

TMALL_magicBOX_M13_6.1.0

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment]
Duplicate of #2125. Downgrade to 10.8.4.

**Comment by skyshino** [comment]
This is first happen at 10.8.4. I report the issue when i find it also happen at 10.8.5.
Can I reopen this issue?

**Comment by nielsvanvelzen** [comment]
I guess I was a bit too quick, this might be a different issue.

**Comment by skyshino** [comment]
Thanks a lot.
I add the 0.14.0(debug version) and 0.14.3(release version) log with 10.8.4 server. 
Hope this can help.

[upload_org.jellyfin.androidtv.debug_0.14.0_20221001125917_6eebdb8ed99541fdafeeea33d4f3de3f.log](https://github.com/jellyfin/jellyfin-androidtv/files/9690476/upload_org.jellyfin.androidtv.debug_0.14.0_20221001125917_6eebdb8ed99541fdafeeea33d4f3de3f.log)
[upload_org.jellyfin.androidtv_0.14.3_20221001130631_8ec0559b757246a1b6724b325339c594.log](https://github.com/jellyfin/jellyfin-androidtv/files/9690477/upload_org.jellyfin.androidtv_0.14.3_20221001130631_8ec0559b757246a1b6724b325339c594.log)
[upload_org.jellyfin.androidtv_0.14.3_20221001130653_200088659fc44afd95bb9dba00965250.log](https://github.com/jellyfin/jellyfin-androidtv/files/9690478/upload_org.jellyfin.androidtv_0.14.3_20221001130653_200088659fc44afd95bb9dba00965250.log)
[upload_org.jellyfin.androidtv.debug_0.14.0_20221001125902_b8058585c2e6438092e66ef780445fc3.log](https://github.com/jellyfin/jellyfin-androidtv/files/9690479/upload_org.jellyfin.androidtv.debug_0.14.0_20221001125902_b8058585c2e6438092e66ef780445fc3.log)
