### ISSUE TITLE
“Direct stream Live TV”doesn't work

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin-androidtv#2130]
### Describe the bug

Except for one video with a higher bitrate, other videos can be transcoded on the client instead of the server

### Application version

0.14.3

### Where did you install the app from?

Amazon Appstore

### Device information

fire tv

### Android version

fire os 7

### Jellyfin server version

10.8.4

**Comment by eudojosegonzalez** [comment]
i have same trouble
