### ISSUE TITLE
Confirmation question before closing the app

### ISSUE THREAD

**Issue by SamJongenelen** [jellyfin/jellyfin-androidtv#2133]
### Describe the feature you'd like

My Android TV is slow at times. 
When i press the back button of the remote too many times, i accidentally close the Jellyfin app.
As opening the app on my tv is slow too, i would love to have an (opt in via settings?) confirmation dialog to confirm closing of the app.

**Comment by nielsvanvelzen** [comment]
> Right now, if you're on the homescreen, the back button leads to leaving the app. Would be nice if it just leads you to the loginscreen instead. Maybe with button to leave the app from there.

Closing the app is intentional. The authentication screen only shows when you're not signed in or switching user/server.

**Comment by SamJongenelen** [comment]
Yeah i personally do not use multiple logins for the TV

**Comment by NeuroDawg** [comment]
Please don't do this. I hate it when apps ask for confirmation before closing. 99% of the time I am intentionally closing the app. If I do so inadvertently, I'll just re-open. Being asked constantly is an annoyance.

**Comment by SamJongenelen** [comment]
Yes, so make it opt in is a good approach for both

**Comment by BotBlake** [comment]
When pressing the `back` button, the app should still be running in the Background though.
You can see when playing music, that Jellyfin is staying open and continuing playback.

Personally I also dislike the Idea of a confirmation message before closing - since worst case is you just open it again.

**Comment by SamJongenelen** [comment]
Of course it is personal. My tv is a bit slow so starting the app again isn't preferred for me.

**Comment by nielsvanvelzen** [comment]
We won't add this.

> We don't have any reason to trap people in our app. If you are on the homepage without any previous page, pressing back will close the app. That's how Android is supposed to work.

From https://github.com/jellyfin/jellyfin-androidtv/issues/4333#issuecomment-2558588944
