### ISSUE TITLE
Can't see content in media library for shows type

### ISSUE THREAD

**Issue by Karmylr** [jellyfin/jellyfin-androidtv#2137]
### Describe the bug

If the media library's type is shows, tv's jellyfin won't be able to see anything inside this media library.

### Application version

0.14.3

### Device information

fire tv 4k stick max

### Android version

fire os 7

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment]
I can't reproduce this issue. Please explain it more clearly with reproducible steps.

**Comment by Karmylr** [comment]
Add the media library, select the shows type; upload the video; then open the jellyfin on the TV stick, enter the created media library, and find that it is blank and cannot select the type

**Comment by Karmylr** [comment]
android mobile client enters the created media library and needs to select "Episodes" to see the video.but i cant select Episodes on TV stick
