### ISSUE TITLE
AndroidTV - Multiple audio streams with same language code wont play good.

### ISSUE THREAD

**Issue by DarkMarkus88** [jellyfin/jellyfin-androidtv#2143]
### Describe the bug

Whenever I got a file with multiple audio streams, like 2 dutch and 2 english, it only plays the first of said language. If you then select the second, it reverts to the first while keeping the second selected. If I give them different language codes, like ENG, DUT, FIN, GER for example, then they play as is.

### Media info of the file

```shell
Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2022-08-05T12:57:17.000000Z
  Duration: 01:49:37.96, start: 0.000000, bitrate: 6981 kb/s
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 1k tbn (default)
    Metadata:
      BPS             : 5997102
      DURATION        : 01:49:37.940000000
      NUMBER_OF_FRAMES: 328897
      NUMBER_OF_BYTES : 4931072195
      _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-05 12:57:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Sky Sports
      BPS             : 189375
      DURATION        : 01:49:37.920000000
      NUMBER_OF_FRAMES: 308340
      NUMBER_OF_BYTES : 155711911
      _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-05 12:57:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(dut): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Viaplay
      BPS             : 189375
      DURATION        : 01:49:37.920000000
      NUMBER_OF_FRAMES: 308340
      NUMBER_OF_BYTES : 155711872
      _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-05 12:57:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3: Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : F1TV Pro - FX
      BPS             : 189375
      DURATION        : 01:49:37.920000000
      NUMBER_OF_FRAMES: 308340
      NUMBER_OF_BYTES : 155711944
      _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-05 12:57:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(dut): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Grand Prix Radio
      BPS             : 433389
      DURATION        : 01:43:40.045000000
      NUMBER_OF_FRAMES: 267875
      NUMBER_OF_BYTES : 336962869
      _STATISTICS_WRITING_APP: mkvmerge v69.0.0 ('Day And Age') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-05 12:57:17
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

### Application version

0.14.3

### Device information

Bravia KD55X85J (and all other Android TV models)

### Android version

?

### Jellyfin server version

10.8.5

**Comment by VampiricAlien** [comment]
What's the ffprobe output of a file that has this issue?

**Comment by DarkMarkus88** [comment]
`ffprobe version n5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 12.2.0 (GCC)
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-opencl --enable-opengl --enable-shared --enable-version3 --enable-vulkan
  libavutil      57. 28.100 / 57. 28.100
  libavcodec     59. 37.100 / 59. 37.100
  libavformat    59. 27.100 / 59. 27.100
  libavdevice    59.  7.100 / 59.  7.100
  libavfilter     8. 44.100 /  8. 44.100
  libswscale      6.  7.100 /  6.  7.100
  libswresample   4.  7.100 /  4.  7.100
  libpostproc    56.  6.100 / 56.  6.100
Input #0, matroska,webm, from '/data/docker/storage/plex/movies-2/oldseries/h264/Formule 1/Season 2022/F1.S2022E73.Belgian.Grand.Prix.Race.mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2022-08-30T11:40:48.000000Z
  Duration: 01:56:15.38, start: 0.000000, bitrate: 6898 kb/s
  Stream #0:0: Video: h264 (Main), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 50 fps, 50 tbr, 1k tbn (default)
    Metadata:
      BPS             : 5997115
      DURATION        : 01:56:15.360000000
      NUMBER_OF_FRAMES: 348768
      NUMBER_OF_BYTES : 5229004638
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-30 11:40:48
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Sky Sports
      BPS             : 189375
      DURATION        : 01:56:15.360000000
      NUMBER_OF_FRAMES: 326970
      NUMBER_OF_BYTES : 165119850
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-30 11:40:48
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(dut): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : Viaplay
      BPS             : 189375
      DURATION        : 01:56:15.360000000
      NUMBER_OF_FRAMES: 326970
      NUMBER_OF_BYTES : 165119850
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-30 11:40:48
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
    Metadata:
      title           : F1TV Pro - FX
      BPS             : 189375
      DURATION        : 01:56:15.360000000
      NUMBER_OF_FRAMES: 326970
      NUMBER_OF_BYTES : 165119850
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-30 11:40:48
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(dut): Audio: aac (LC), 44100 Hz, stereo, fltp (default)
    Metadata:
      title           : Grand Prix Radio
      BPS             : 368660
      DURATION        : 01:43:15.827000000
      NUMBER_OF_FRAMES: 266832
      NUMBER_OF_BYTES : 285519972
      _STATISTICS_WRITING_APP: mkvmerge v70.0.0 ('Caught A Lite Sneeze') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-30 11:40:48
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
`

**Comment by VampiricAlien** [comment]
This one file has 4 audio tracks?
Stream #0:1(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default) 
Stream #0:2(dut): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream #0:3(eng): Audio: aac (LC), 48000 Hz, stereo, fltp (default)
Stream #0:4(dut): Audio: aac (LC), 44100 Hz, stereo, fltp (default)

I ran the same command on one of my files but only have English.
   ENCODER         : Lavf59.27.100
  Duration: 00:02:06.62, start: -0.007000, bitrate: 6663 kb/s
  Stream #0:0: Video: hevc (Main 10), yuv420p10le(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 59.94 fps, 59.94 tbr, 1k tbn (default)
    Metadata:
      ENCODER         : Lavc59.37.100 libx265
      DURATION        : 00:02:06.534000000
  Stream #0:1(eng): Audio: flac, 48000 Hz, 5.1, s32 (24 bit) (default)
    Metadata:
      ENCODER         : Lavc59.37.100 flac
      DURATION        : 00:02:06.620000000
  Stream #0:2(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
    Metadata:
      ENCODER         : Lavc59.37.100 libopus
      DURATION        : 00:02:06.621000000

Was trying to reproduce this in the app but unable too, does this happen on Jellyfin web?

**Comment by mikewesten** [comment]
@DarkMarkus88 Both tracks are flagged as default. What happens if you remux the video with only one track flagged as default?
