### ISSUE TITLE
"Play First Unwatched" menu option does not work correctly from main menu.

### ISSUE THREAD

**Issue by Stylo101** [jellyfin/jellyfin-androidtv#2165]
### Describe the bug

This bug presents itself on a TV series where unwatched episodes exist in in later seasons with watched episodes in earlier seasons/specials.
![20221011_170448](https://user-images.githubusercontent.com/16506473/195204222-b5ea5709-6670-46a0-a660-bb0293261b29.jpg)

1. On main menu go to "Latest Shows" section and select a show as described above (example, season 1 fully watched, season 2 partially watched with multiple unwatched episodes
2. Long press button on show to reveal popup menu ![20221011_170528](https://user-images.githubusercontent.com/16506473/195203837-f8a01503-3fea-4d1f-9557-3a9a294f61ef.jpg)
3. Select "Play First Unwatched"
4. The app will play the first episode of Specials or of Season 1 if Specials aren't available.
![20221011_170537](https://user-images.githubusercontent.com/16506473/195204270-54366a1e-d094-4fdb-a8eb-a78955558d68.jpg)
![20221011_170551](https://user-images.githubusercontent.com/16506473/195204287-c52c8865-b200-44c0-9dcb-f785d47ae347.jpg)

Expected results
Play first available unwatched episode, instead of the first episode. If you select a show and then select the season with the unwatched episode, long press, and select "Play First Unwatched" from there it will play the first unwatched episode of that season correctly.

### Application version

0.14.4

### Where did you install the app from?

Google Play

### Device information

Sony BRAVIA 4k VH2 TV and Chromecast with Google TV (happens on multiple devices)

### Android version

Android 10

### Jellyfin server version

10.8.5

**Comment by Stylo101** [comment]
I can confirm this issue still exists.

**Comment by trumblejoe** [comment]
Issue still exists. Play first unwatched should calculate by episode number starting with Season 01E01 unless air date for the special is earlier then air date of Episode S0XE0X then it should play the special, if air date of the special is NULL it should go fully by episode number so it appears last (S00 aka Specials should be 'last' compared to numerical seasons).  I believe this logic will correctly allow between season specials to play if they have proper air dates. 

Not all episodes should go by air date as shows like Firefly, Batman TAS, etc would be messed up.
