### ISSUE TITLE
Jellyfin disappeared from TV launcher

### ISSUE THREAD

**Issue by Janhouse** [jellyfin/jellyfin-androidtv#2173]
### Describe the bug

Today I noticed that Jellyfin launcher icon disappeared from Android TV (version 10).
It is still installed nand can be opened from Play Store or installed apps list in settings, but doesn't appear in launcher or recently used apps menu. There were no Android TV or Jellyfin server updates installed recently, but maybe Jellyfin was updated from Play Store.

### Application version

0.14.4

### Where did you install the app from?

Play Store

### Device information

Sony Bravia

### Android version

Android TV 10

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment]
I've experiences the same issue with a different app a while ago. The only way I was able to fix it was to reinstall the app. My best guess is that this is a bug in the launcher.

**Comment by Janhouse** [comment]
After rebooting the TV Jellyfin and other apps appeared in the launcher
again, though on the bottom of the list.
I guess this issue can be closed.
