### ISSUE TITLE
Marking episode as watched, doesn't refresh next up at home page

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-androidtv#2175]
Like the title says.

When I mark an item as watched and return to the homepage, it doesn't refresh the next up row. Instead, it removes the item from the currently watching row, but doesn't add anything to next up. This happens with both libvlc and exoplayer
Only when I switch users or restart the app, the homepage is refreshed.

Android version: 8.0
Jellyfin app version: 1.14.4
Jellyfin server version: 10.8.5

**Comment by nielsvanvelzen** [comment]
Please use the issue template when creating issues. Closing as incomplete.
