### ISSUE TITLE
Resuming 4K HEVC SDR 10 video doesn't work with Exoplayer

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-androidtv#2176]
When I resume playing an item that is 4K SDR HEVC 10 bit with Exoplayer, it shows and error message "player got errors, will try again" a couple of times, then it quits the video player entirely and says 'Player got too many errors, quitting..."

My TV has a 4K resolution with support for SDR. It supports direct play HEVC with other media that isn't 4K SDR, but it can't resume playing an item, nor can it fast forward while watching something, as it gives the error messages, with no debugging info at all.

BTW, when using libvlc, it can resume a 4K SDR HEVC 10 Bit item, but not with Exoplayer

Android version: 8.0
Jellyfin app version: 0.14.4
Jellyfin server version: 10.8.5

**Comment by nielsvanvelzen** [comment]
Please use the issue template when creating issues. Closing as incomplete.
