### ISSUE TITLE
 Resuming 4K HEVC SDR 10 video doesn't work with Exoplayer

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-androidtv#2179]
### Describe the bug

1. Start watching an item which is `4K SDR HEVC Main 10`
2. Quit watching, so it appears on the homepage in the 'Continue Watching' row
3. Resume watching the item
4. See error "Player got errors, will try again" appear a couple of times
5. Witness player quitting entirely, prompting the error "Got too many errors, quitting.."

### Logs

So for some reason there are no logs sent to the server, which is why I can't put anything here

### Media info of the file

```shell
Video
Title: 4K HEVC SDR
Codec: HEVC
Profile: Main 10
Level: 150
Resolution: 3840x1632
Aspect ratio: 2.35:1
Interlaced: No
Framerate: 23.976025
Bitrate: 4249 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1


Audio
Title: Eng - AAC - 5.1
Language: eng
Codec: AAC
Profile: LC
Layout: 5.1
Channels: 6 ch
Bitrate: 245 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No


Subtitle
Title: Eng - SUBRIP
Language: eng
Codec: SUBRIP
Default: No
Forced: No
External: No
```

### Application version

0.14.4

### Device information

Philips QM163E

### Android version

Android 8

### Jellyfin server version

10.8.5

**Comment by SuperCatss** [comment]
I have the same problem, it only appears on TV, when I play through chrome it works fine.

**Comment by JVT038** [comment]
So I don't know why or how, but this issue suddenly doesn't occur anymore?
I can suddenly resume the same items that used to crash the player and I haven't done anything.
