### ISSUE TITLE
 Marking episode as watched, doesn't refresh next up at home page

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-androidtv#2180]
### Describe the bug

1. Mark an episode as watched
2. Return to home page
3. The episode disappears from the continue watching / next up row
4. The next up row completely doesn't refresh, so the next episode doesn't appear
5. To fix this, switch users and the home page is refreshed

### Application version

0.14.4

### Where did you install the app from?

Google Play

### Device information

Philips QM163E

### Android version

Android 8.0

### Jellyfin server version

10.8.5

**Comment by Bandid0** [comment]
That happens to me too

**Comment by VampiricAlien** [comment]
I think this is a known bug, same thing happens on android 11
