### ISSUE TITLE
auto-continue or next media playback hangs after previous media finishes

### ISSUE THREAD

**Issue by systemcrash** [jellyfin/jellyfin-androidtv#2189]
### Describe the bug

description:
play any media
let it finish or leave playback early
let auto-next play the next episode
or
choose new media (here hang is already evident, because the info screen will not load for any item other than the one just played)

in both scenarios, the TV app hangs, waiting for something. The only way to accelerate the process is to kill the TV app (very inconvenient) or wait what seems like 4-5 minutes.

This is logged as a *client* bug, whether or not it is dependent on *server* behaviour, because it is the client that hangs. The logs are from server side. 

Captured in the logs is one instance where I waited for the hang to finish. All other instances, I killed the TV app. All playback instances are roughly 1 hour chunks.

### Logs

[Log.txt.zip](https://github.com/jellyfin/jellyfin-androidtv/files/9810890/Log.txt.zip)

### Application version

0.14.4

### Device information

BRAVIA 4K VH2

### Android version

10

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment]
I can't reproduce this. Autoplay works perfectly fine for me.

**Comment by systemcrash** [comment]
Welp, this is the extent of the infrastructure that I can test on. And the
behavior is consistent.

The logs do have some interesting messages.

**Comment by alexs20** [comment]
The same problem. Also if i stop playing one move and try to open another one it hangs for 5 mins with empty screen instead of showing movie details

**Comment by systemcrash** [comment]
Having used the android-tv app over a longer period, there have been moments when things work without delay as they should, but sometimes it just hangs there. Cannot find any clear correlation or problem root (client, server, etc)

**Comment by systemcrash** [comment]
After further investigation, it appears as though "playlists" entry in the jellyfin server is responsible for the hang, and LOTS of crashes which mention `Socket timeout` or `Socket timed out`

Go to metadata manager, and open the arrow on playlists, and it "loads" forever. This is the only server side thing which I can see which is still going once you have opened it. The only explicit way to exclude playlists from the logged in user, is to uncheck `Enable access to all libraries` under the users `Access` tab (and enable individual libraries).  For me anyway. 

There may be some other combination of settings in there which help. 

See https://github.com/jellyfin/jellyfin/issues/6514

**Comment by johnthq** [comment]
i seem to be having the same issue. sometimes the episode queue after waiting enough at the black screen other times nothing. having to kill the instance of player. ive used both jellyfin-web/jellyfin-android only thing in the log is. 

[2023-09-03 19:52:21.452 -05:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-09-03 19:54:21.470 -05:00] [INF] Sending ForceKeepAlive message to 1 inactive WebSockets.
[2023-09-03 19:54:33.473 -05:00] [INF] Lost 1 WebSockets.

**Comment by systemcrash** [comment]
Yeah, I could never track down what it was. On certain versions it was consistently there. So it seemed to depend on websockets (lib?) which was included with the build. Just guessing.

**Comment by johnthq** [comment]
i feel its gotten to be chronic problem now. updated to the latest docker image after i had made the last post in here two weeks ago.  after say 5 hours its guaranteed to happen.
