### ISSUE TITLE
Some media information showing 'null'

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin-androidtv#22]
I am seeing some 'null' values in some of the program descriptions that I do not see in the web interface.  I'm uncertain how to describe this other than to type it out and perhaps someone can identify what variable is not being populated.  Here's and example:

```
CBS Evening News with Jeff Glor
null - 5:30PM-6:00PM
The latest world and national news
```

**Comment by dinki** [comment]
In scrolling through the guide, most of these are nulls but I did see one that was populated and it was 'LPBHD' which is my local PBS station.  I'm guessing these are station IDs?

**Comment by JustAMan** [comment]
I think a screenshot (or a photo if the former is impossible) would be good to clarity the issue.

**Comment by dinki** [comment]
![img_20190112_155756](https://user-images.githubusercontent.com/2521542/51078924-2348a100-1683-11e9-96ec-09253bb35584.jpg)

**Comment by dinki** [comment]
Notice null at the top right near the time on the second line.  'null -3:00PM - 4:00PM'

**Comment by hrast01** [comment]
I'm seeing the same thing, even after I updated to the most recent APK.

**Comment by thornbill** [comment]
This will need verified once a new apk is published.

**Comment by thornbill** [comment]
@dinki or @hrast01 are you still seeing this in the latest apk?

**Comment by dinki** [comment]
Yes. This fixes the problem. Thanks again
