### ISSUE TITLE
Subtitle offset doesn't work on libvlc playback

### ISSUE THREAD

**Issue by flonou** [jellyfin/jellyfin-androidtv#2200]
### Describe the bug

I'm using Jellyfin for android TV 0.14.4 and enabled libvlc player
When playing a video with subtitles (in my case .srt files), offseting the subtitles throught the GUI has no effect (even though it seems like the playback is frozen for a fraction of second when changing the value so something seems to happen, but no subtitle offset

### Logs

```shell
I tried adb but did not find anything. I'm not sure how to use it correctly to extract jellyfin logs
```

### Application version

0.14.4

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireTV

### Android version

fireos 5.2.9.1

### Jellyfin server version

10.8.1

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by sparky3387** [comment]
Was this in the compiled app? As you mentioned you could see the offset from bottom setting?

**Comment by flonou** [comment]
Hi,
I'm not sure what you mean by compiled app, what would be the other options ?
I could see the subtitle offset setting at the bottom in the same menu as audio offset

**Comment by sparky3387** [comment]
You mean subtitle offset as compared to audio right? Sorry had recently had a patch merged that allows subtitle to be offset (from the bottom of the screen)

**Comment by flonou** [comment]
Yes I mean subtitles offset. I have both (subtitles and audio offset) available in the same menu when libvlc is selected, but subtitle offset doesn't offset subtitles as it should

**Comment by satstarter** [comment]
In the normal release app 14.4 or 14.5 there's no offset only background and size for subtitles
and this effects only exoplayer subtitles not libvlc or external player subs
when i compile the app with the master branch this is not a release yet 
i get the allow subtitle offset (from the bottom of the screen) also color of the subtitle but this is also exoplayer only.

**Comment by flonou** [comment]
You can find 3 pictures showing : 
libvlc is selected
![20221103_112732](https://user-images.githubusercontent.com/10209267/199698337-2ebf650c-db55-40c8-997a-c0e39f38ed01.jpg)
version 14.5 is used
![20221103_112748](https://user-images.githubusercontent.com/10209267/199698341-60c04af9-b47e-408d-9aa3-f2326a84fbab.jpg)
subtitles offset menu
![20221103_112816](https://user-images.githubusercontent.com/10209267/199698344-58bb8216-f031-4168-9856-c2d5d747b367.jpg)

**Comment by DenizenB** [comment]
I'm experiencing the exact same issue as @flonou. Using libVLC player, Jellyfin 0.14.5.

Adjusting the subtitle offset changes the playback position. So for example, adding a 1,000 ms offset fast-forwards the video by the same amount. However, it has no effect on the timing of the subtitles.
