### ISSUE TITLE
[BUG] No preview on the slidder when Fastforward/Rewind

### ISSUE THREAD

**Issue by butts136** [jellyfin/jellyfin-androidtv#2214]
### Describe the bug

Problem seen on Firestick 4K (AndroidTV app)

Didn't fint other open issue for that. If yes, Sorry for that.

On both player (LibVLC and Exoplayer), Most of the time, close to every time. There's no slidder preview when we are Fast-forwarding or Rewinding. I'm not talking about Chapter preview. Im talking about where's the slidder is for when the film gonna start. So i'm fast-forwarding blind, i need to guess where gonna be the slidder, wait for the downloding. Need to fast-forward more, wait for loading, oops, too far, need to rewind a little.

That's just a little annoying

I'm on version 0.14.4 (server 10.8.5)

Thanks

### Application version

0.14.4

### Where did you install the app from?

Amazon Appstore

### Device information

FireStick 4K (V2 i think - Remote with LiveTV and 4 App button)

### Android version

Fire Os 6.2.9.2

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment]
This is not a bug, we don't have scrubbing preview thumbnails.

**Comment by butts136** [comment]
Like I said, I'm not talking about the image. I'm talking about the Slider position when I'm fast-forwarding. When i click for fast-forward, I don't see the slider moving. I need to go approxativly.

Reaaly not talking about preview like Youtube, not thumbnails no image.

Only talking about the slider itself.

**Comment by nielsvanvelzen** [comment]
Sorry that wasn't clear for me. So you mean that this bullet doesn't go to the correct place when seeking?

![image](https://user-images.githubusercontent.com/2305178/198386016-55f978e8-94df-4b26-8675-d3fd266d7b54.png)

**Comment by butts136** [comment]
Yes, exactly. I was trying to upload a video but 5 secondes is already too large to put here :P

Exactly, When i click Fast forward, i can't visalize where is the "bullet" until the movie have loaded and played

Thanks
