### ISSUE TITLE
android TV 10 jellyfin app playlist

### ISSUE THREAD

**Issue by No1perfectv** [jellyfin/jellyfin-androidtv#2219]
### Describe the bug

If you play individually in a playlist, number 1 in the list overlaps. And the last one disappears.

![20221029_151147](https://user-images.githubusercontent.com/106219968/198817227-c25cfc53-d212-488a-a9c9-ae9ef2905db8.jpg)

### Application version

0.14.4

### Device information

robotics tivo stream 4k

### Android version

android 10

### Jellyfin server version

10.8.3

**Comment by VampiricAlien** [comment]
This can be reproduced by clicking on the top item in the playlist then going back to the playlist, the order have changed too
1
1
2
leaving the playlist screen and going back, the playlist will show
1
2
3
After that I can't reproduce the bug unless I play the first item again.
