### ISSUE TITLE
Screensaver not started when paused

### ISSUE THREAD

**Issue by AndrewBreyen** [jellyfin/jellyfin-androidtv#2225]
### Describe the bug

1. Pause playback on an item
2. Screensaver does not start 

Screensaver starts on Home Screen, but not when paused. 

I have my screensaver settings set to after 5 mins, turn screen off, after 30 sleep. 

### Application version

0.14.4

### Where did you install the app from?

Google Play

### Device information

Hisense HiSmart A4

### Android version

Android 9

### Jellyfin server version

10.8.5

**Comment by mueslimak3r** [comment]
This feature, allowing the system screensaver to start when a video is paused, was intentionally disabled around 0.12.x-0.13.x due to some bugs. The most practical solution at the time was to disable the screensaver.


I'm relabeling this issue as a feature since the current behavior is intended.

**Comment by VampiricAlien** [comment]
@mueslimak3r Disabled? I have a screensaver on as i type this message to you.

**Comment by urbanrider** [comment]
I have this issue as well. Not ideal for an OLED.

**Comment by nielsvanvelzen** [comment]
Our next (big) release will now show the screensaver when a video is paused.
