### ISSUE TITLE
On Android TV 10, when fast forwarding, rewinding or resuming playback, there's a still image and audio on some files.

### ISSUE THREAD

**Issue by MaestroEngineering** [jellyfin/jellyfin-androidtv#2227]
### Describe the bug

Hi. I'm not sure how to solve this. I've tried all the usual options.

1. Direct streaming an MKV file.
2. Rewind or fast forward or stop and resume where you left off.
3. You get a still image and audio

Rebooting TV Box does not work.
Restarting the TV Box does not work.
Playing same file from a browser works fine.

If there's any information I can still give. Or anything I can add. Let me know.
If this is already been reported. I'm sorry. I tried looking for it but couldn't find it anywhere.

Thank you!

### Media info of the file

```shell
Video
Title: 1080p H264 SDR
Codec: H264
AVC: Yes
Profile: Main
Level: 41
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 25
Bitrate: 4006 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1
NAL: 4


Audio
Title: Dolby Digital - 5.1 - Default
Codec: AC3
Layout: 5.1
Channels: 6 ch
Bitrate: 448 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No
```

### Application version

0.14.4

### Device information

Mecer KM9PRO Media Player

### Android version

Stock Android TV 10

### Jellyfin server version

10.8.4

**Comment by VampiricAlien** [comment]
No video playback, only audio?

**Comment by MaestroEngineering** [comment]
> No video playback, only audio?

Thats correct. Just a still image of the frame you was at last.

**Comment by VampiricAlien** [comment]
This is will be hard to reproduce.

**Comment by MaestroEngineering** [comment]
Is there any way I can figure out what's causing it?

**Comment by VampiricAlien** [comment]
You can try to compare files that work to those that don't and post the results here?
