### ISSUE TITLE
Switching languages changes aspect ratio

### ISSUE THREAD

**Issue by cdthomo** [jellyfin/jellyfin-androidtv#224]
**Describe the bug**
I have a few 21:9 media files which have a primary foreign language track. Switching the language to English changes the video's aspect ratio to "stretch" and fills the 16:9 screen.

**To Reproduce**
1. Load a video file with two language tracks.
2. Switch to the second language track while the video plays.
3. See the video change from letterbox to stretched aspect ratio.

**Expected behavior**
The language track should change with no impact on the video.

**Logs**
No obvious log errors.

**Screenshots**
Description should be clear.

**System (please complete the following information):**
 - OS: Jellyfin server running in Docker on Unraid
 - Browser: Client is jellyfin for amazon fire stick
 - Jellyfin Version: 10.4.1
 - Reverse proxy: internal network, none used

**Comment by Muzzygizmo** [comment]
I confirm that I have the same problem with 
- Jellyfin server 10.4.3
- Android tv client v0.11.1
- Amazon Fire TV stick 4k
