### ISSUE TITLE
[beta v0.15.0] Audio selection tick box is missing from player

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2253]
### Describe the bug

As titile says. When playing a video with two audio tracks, clicking on select, you're unable to see what is selected because the tick box is cut off on exo player.

Showing Stereo English AAC default and not Stereo English AAC default [  ]

### Application version

0.15.0

### Where did you install the app from?
Side Loaded
_No response_

### Device information

NS Pro

### Android version

Android 10

### Jellyfin server version

10.8.7

**Comment by nielsvanvelzen** [comment]
Thanks for the report, will be fixed in the next beta.
