### ISSUE TITLE
Audio night mode doesn't respect system volume when using AC3 or EAC3

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2255]
### Describe the bug

System volume is on mute but app still plays audio, unticked the night mode setting and tried again this time no audio is playing while on mute.

### Application version

0.15.0

### Where did you install the app from?

Sideloaded APK

### Device information

NS Pro

### Android version

Android 10

### Jellyfin server version

10.8.7

**Comment by VampiricAlien** [comment]
Looking into this more, anything with 5.1 (EAC3) doesn't doesn't respect system volume

**Comment by VampiricAlien** [comment]
@nielsvanvelzen I know this wasn't your feature request and had to finished it yourself. Is it possible to have this looked at before beta ends?

**Comment by nielsvanvelzen** [comment]
I have no idea why that happens, my recommendation is to disable the feature so the bug doesn't trigger.

**Comment by VampiricAlien** [comment]
I don't think AC3 or EAC3 is included within this feature as those audio codes are very loud while others are not.
It'll be sad to disable it but things will be watchable.
