### ISSUE TITLE
Search button/icon momentarily becomes highlighted when loading an item

### ISSUE THREAD

**Issue by krutburken** [jellyfin/jellyfin-androidtv#2257]
### Describe the bug

Small aesthetic thing I noticed when testing the beta. The search button in top right always become momentarily highlighted when entering an item. Doesn't do anything, just looks a bit weird.

1: Open app, enter homescreen
2: Click on an Item (movie for example)
3: Before item loads, you'll see the search button in the top right momentarily become selected/highlighted before the item is displayed

### Application version

0.15.0-beta1

### Where did you install the app from?

Google Play

### Device information

Shield TV

### Android version

11

### Jellyfin server version

10.8.7

**Comment by nielsvanvelzen** [comment]
I'm aware of this behavior and unfortunately have no been able to find a fix for it after spending hours on it, so it's probably going to stay for a while until someone finds a way to fix this.
