### ISSUE TITLE
Hash out server IP/domain in logs

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2268]
### Describe the feature you'd like

I think it's best that within the logs the server IP address is removed or partly covered or displayed by name and not address  by default.

**Comment by BotBlake** [comment]
> I've decided that we do not want to add this additional filtering to the logs because we can never make it work for all edge-cases. The user is responsible for removing any sensitive data when posting it publicly and we also accept private submissions for logs (via private chat/mail/etc).

https://github.com/jellyfin/jellyfin-androidtv/pull/2550#issuecomment-1598890398
~ Niels
