### ISSUE TITLE
Texts are not showing when using Japanese system language.

### ISSUE THREAD

**Issue by studioai** [jellyfin/jellyfin-androidtv#227]
I installed jellyfin on my fireTV stick.
and there was no text on the app.
I changed the device's system language to English. all the texts are shown properly.

After I set server login information, I set the system language to  Japanese again.
The only text I can see was "設定" which means settings.

I guess this is caused by missing text data. So, It would be better to show English text when there is no local language data.

Thank you.

**Comment by dkanada** [comment]
It looks like most of the strings exist [here](https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/res/values-ja/strings.xml), could you give a specific example of a missing string?

**Comment by studioai** [comment]
@dkanada 
Thank you for your reply.
Currently `<string name="settings_title">設定</string>` is the only text I can see on the app while using Japanese system language settings.

**Comment by AndreasGB** [comment]
@dkanada Can be reproduced in Emulator, changing language is a bit difficult there. You need to open a root shell via `adb shell` and `su`, then:
```
setprop persist.sys.locale ja-JP
setprop ctl.restart zygote
```

**Comment by AndreasGB** [comment]
Okay, the cause are empty strings in the japanese resource file, like 
```
<string name="lbl_sideline_color"/>
```

if they are deleted, the fallback to the english resources happens again.

**Comment by AndreasGB** [comment]
This appears to be a misconfiguration of weblate and happened to other projects as well, see https://github.com/WeblateOrg/weblate/issues/1893

**Comment by nielsvanvelzen** [comment]
I can confirm this is the case for multiple languages, for example indonesion is empty, korean is missing some strings (but contains empty xml elements).

I suspect that #229 might fix it as the svedish strings.xml only contains translated elements:

https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/res/values-sv/strings.xml

**Comment by AndreasGB** [comment]
@thornbill has the default in weblate been changed as well? If not, this should be reopened.

**Comment by thornbill** [comment]
@AndreasGB yes it should be fixed in weblate now. @anthonylavado updated the settings there thanks to the information you provided above!

**Comment by AndreasGB** [comment]
Okay, great :)
