### ISSUE TITLE
when using vaapi hardware acceleration not able to play ass/ssa subtitels exoplayer

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-androidtv#2274]
### Describe the bug

when using vaapi hardware acceleration not able to play ssa/ass subtitles using exoplayer
to many errors wil try again then the app takes the srt subs again

with no acceleration the subtitles play but with exoplayer cpu usage is 80 procent
i know exoplayer needs transcoding for ssa/ass subs but only for subs 80 procent cpu is ridiculous in my opinion

### FFmpeg logs
[FFmpeg.Transcode-2022-11-18_19-08-10_259d634d13e1ab9792564e6531c616f7_937f1c0f.log](https://github.com/jellyfin/jellyfin-androidtv/files/10043872/FFmpeg.Transcode-2022-11-18_19-08-10_259d634d13e1ab9792564e6531c616f7_937f1c0f.log)

_No response_

### Application version

0.15.1.beta

### Device information

formuler z8 xsarius q8

### Android version

Android 9

### Jellyfin server version

10.8.7

**Comment by VampiricAlien** [comment]
Can you post some logs?

**Comment by satstarter** [comment]
> Can you post some logs?

FFmpeg log file is attached

**Comment by VampiricAlien** [comment]
It was the server logs I was after but found this in your other log

**Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height**

Check your playback settings in Jellyfin Web

**Comment by satstarter** [comment]
Thank you it was indeed HEVC transcoding that was the problem now it plays ass/ssa with vaapi accelaration
transcoding stays under 40 procent cpu usage ;)

thanx

**Comment by VampiricAlien** [comment]
Good to know it's fixed for you. Close the issue when you're ready.
