### ISSUE TITLE
Continue Watching doesn't appear in "Smart Screen" for TV/SHOWS Libraries

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-androidtv#2275]
### Describe the bug

Apparently this only happens for Shows and TV library. 
Movie Libraries are **not affected** and it shows Continue Watching on Smart Screen 

1. Enable Smart screen on TV/Shows
2. Playback an episode and stop halfway
3. Continue Watching **appears** on MAIN SCREEN
4. Click on TV/Shows Smart Screen 
5. No Continue Watching

### Application version

v0.14.5/v0.15.0-beta.1

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield

### Android version

Latest

### Jellyfin server version

Latest

**Comment by nielsvanvelzen** [comment]
This is not a bug. The resume row is not implemented for series.
