### ISSUE TITLE
(0.15.0-beta2) Incorrect time in tv guide program description

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#2279]
### Describe the bug

The time in the tv guide program description does not match the correct time. The issue was not present in the last stable release. Screenshots from stable build (.14.5) vs the latest beta build (.15b2). 

Correct (.14.5)
![14 5](https://user-images.githubusercontent.com/78215956/203095243-0d4f0c5a-e0fe-476c-9a58-db08eb0d3561.jpg)

Incorrect (.15b2)
![15beta2](https://user-images.githubusercontent.com/78215956/203095249-a5a24db5-bc91-427a-90a4-31782783fab5.jpg)

### Application version

0.15.0 beta2

### Where did you install the app from?

Sideloaded APK

### Device information

Sony Bravia 4k VH2

### Android version

Android TV OS 10

### Jellyfin server version

10.8.7

**Comment by nielsvanvelzen** [comment]
Thanks for the report, should be fixed in the next beta.
