### ISSUE TITLE
Chinese ASS subtitles will display square on TV.

### ISSUE THREAD

**Issue by Mr-win7** [jellyfin/jellyfin-androidtv#2292]
### Describe the bug

Reproduce procedure:
1. On server side, scan any videos with a Chinese subtitle with ASS format.
2. On server side, enable fallback font with a valid Chinese font(no need to use the type defined in ASS, others will also work).
3. Play the video with the caption on TV client.

You will find all the characters will be displayed as a square, while it will be proper characters on HTML5/iOS/Android mobile client.

It is not correlated with the font type we use (whether the one assigned in the ASS file or not assigned one will not be well).

The reasons I guess list below.
1. both Jellyfin server and TV(In fact maybe all the Jellyfin products) support badly on non-latin subtitle. they didn't contain Chinese fonts for subtitle rendering, which force users to use the fallback font feature.
2. TV client now could not process the fallback font correctly. It may ignore the font provided by the server.

Maybe we can add support to fallback font and it will correct the problem.

Thank you for your great work and volunteering spirit. I'm not familiar with Android developing so I don't know how to fix it. I'm appreciate for your help.

### Logs

Sorry for no log. It is difficult for me to get the log. This question is quite common on Chinese users and maybe other users may have the log with their rooted device.

### Application version

v0.15.0-beta.2

### Where did you install the app from?

Sideloaded APK

### Device information

FFALCON 55S365C   (And I think it is not related with device)

### Android version

Android 11

### Jellyfin server version

10.8.7

**Comment by iere** [comment]
I had the same problem.We're looking forward to fixing this.

**Comment by vianchiel** [comment]
I'm having the same issue.
This mostly happens with MKV movies/anime with embedded .ass subtitles for CJK letters.

At first I encountered this issue on the web-client end, I fixed it by adding Noto_Sans_CJK to the fallback font.
However the AndroidTV client doesn't seem to utilise the fallback font at the current moment.
Jellyfin for iOS and Android also has this problem, surprisingly the third-party application Findroid on Android successfully renders the subtitle and handles playback very well.

If needed I'll try to provide some logs/screenshots if requested.

**Comment by Jingru** [comment]
I'm having the same issue with 0.15.12.

**Comment by tabjy** [comment]
Can we somehow reopen this issue as it's still relevant in recent versions?

**Comment by TheLonelinessOfHS** [comment]
> The issue description mentions SSA/ASS. Those subtitles are not rendered by the app but are baked in using a transcode by the server. So the issue report should be made at the server repository.

No. The Android TV app is the only one that doesn't work.

**Comment by xiNeRoar** [comment]
will this ever be considered to fix?

**Comment by TheLonelinessOfHS** [comment]
> will this ever be considered to fix?

Obviously not. I have switched to Emby after trying out the new release. The developer has been denying the presence of the issue. They claimed that they had removed LibVLC so that there is no such problem related to the LibVLC implementation. Actually, the new release once worked but stopped working after a while for some reason that I don't know. It seems that this problem isn't only associated with LibVLC. As a user I don't care about the implementation details and all I know is that the subtitles are still not working and the Android TV version is the only one that doesn't work apart from the Web and the Android. They simply denied that issue without further investigation.

**Comment by zhongkechen** [comment]
Still seeing this issue on my Google TV projector.
