### ISSUE TITLE
Cannot dismiss the home screen banner that says "thank you for participating in beta ..."

### ISSUE THREAD

**Issue by MovieWiz** [jellyfin/jellyfin-androidtv#2298]
### Describe the bug

For my FireStick Lite (Fire OS 7), the thank you banner is dismissed when I press the remote's enter/select button while focus is on the banner.

However, on my FireStick 4K (Fire OS 6), it appears to be impossible to dismiss the thank you banner on the home screen.

I assume the difference in behaviour is due to the difference in the Fire OS versions or the difference in the underlying versions of the Android OS.

### Application version

v0.15.0-beta.2

### Where did you install the app from?

Sideloaded APK

### Device information

Fire TV Stick 4K

### Android version

Fire OS 6

### Jellyfin server version

10.8.7

**Comment by nielsvanvelzen** [comment]
Thanks for the report, this will be fixed in the next beta release.
