### ISSUE TITLE
STOP LibVLC and Exoplayer prerequisite from reading mediainfo.

### ISSUE THREAD

**Issue by vegedb** [jellyfin/jellyfin-androidtv#2302]
### Describe the bug

Seems like both LibVLC and Exoplayer reads from jellyfin's metadata/MediaInfo and uses it for playback length.

If there's no MediaInfo or **mismatch** MediaInfo on a video, LibVLC and Exoplayer refuses to play since it doesn't see any playback length from jellyfin.

Steps to recreate:

1. Replace existing video with re-encoded version without scanning jellyfin
2. At first boot, it won't playback video since it doesn't see any video length
3. Stop said video
4. NOW it will playback as it now reads the new video LENGTH

Currently the only solution is [3-4] OR use External Players. Hope you can treat the video plays as video players and not use any metadata from jellyfin server.

### Application version

Latest Beta

### Device information

Nvidia Shield

### Android version

Latest

### Jellyfin server version

Latest

**Comment by FerronN** [comment]
Wouldn't refreshing the metadata work?

**Comment by vegedb** [comment]
> Wouldn't refreshing the metadata work?

Yes it would. But I'd like to keep refreshing metadata at a minimum. 

As long the filename matches, jellyfin will playback even if you change the file.
