### ISSUE TITLE
Enable TLS x25519 ecdh curve

### ISSUE THREAD

**Issue by fgnix** [jellyfin/jellyfin-androidtv#2307]
### Describe the feature you'd like

It seems that this app restrict the TLS ecdh curve it can use. At the moment only secp256r1, secp384r1 and secp512r1.
x25519 is already supported by Android and it would be great if you can enable it in this app

**Comment by nielsvanvelzen** [comment]
This is not an app issue. All SSL code is managed by the system. If something is not supported that's because of your operating system, not the app.
