### ISSUE TITLE
(0.15.0-beta3) Incorrect ending time in program description (LiveTV)

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#2311]
### Describe the bug

The ending time in the program descriptions for On Now or Coming Soon is incorrect.

In this example, the description should state 10:00 am - 12.00 pm
![image](https://user-images.githubusercontent.com/78215956/205684625-15412303-87ed-40b1-b8d5-3f4fb5a74d15.jpeg)

### Application version

(0.15.0-beta3

### Where did you install the app from?

Sideloaded APK

### Device information

Sony Bravia 4k VH2

### Android version

Sony Bravia 4k VH2

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
This issue should be fixed in the next beta.
