### ISSUE TITLE
Implement Shuffle similarly to Android/Web

### ISSUE THREAD

**Issue by nwprince** [jellyfin/jellyfin-androidtv#2321]
### Describe the feature you'd like

Shuffling shows and seasons within Jellyfin was a feature added and documented in this pull request: https://github.com/jellyfin/jellyfin-web/pull/3627

Please implement the same feature for Android TV. We would love the ability to shuffle irrelevant TV shows like Rick & Morty, Bob's Burgers, The Office, Friends, etc. Some shows have no continuous or connected plot (outside a few small exceptions) and these shows are great for having on in the background. Having a shuffle feature would give a good mix of old and new episodes without the need to setup a playlist or handle the shuffle manually by starting in one season then switching to another later. 

See attachment for Android mobile implementation.
![Screenshot_20221206_191306_Jellyfin](https://user-images.githubusercontent.com/17996032/206063336-1bf4e8db-6e57-4ac6-bdb1-94e02b0f032f.jpg)
![Screenshot_20221206_191333_Jellyfin](https://user-images.githubusercontent.com/17996032/206063390-5a0f9cb9-8221-42d6-bd7d-aa482f219fbf.jpg)

**Comment by tim-vk** [comment]
As far as I'm aware this is already implemented. Just go into the show you want to shuffle and it should be available. Could you verify that the button is not there for you? And if it's not: Can you check your folder structure for your show? (as far as I can see this is more-or-less the only thing that determines if shuffle is available or not).

![image](https://user-images.githubusercontent.com/9055206/215603319-c526b923-e23d-4062-97e1-11257e811062.png)

**Comment by nwprince** [comment]
So I have two streaming devices that are running Jellyfin for Android TV. The first is a Chromecast with Google TV, the other is a NVIDIA Shield (tube version). Neither of them render a Shuffle All link. 

Here are some screenshots of what I see and the web client. I also included Metadata and filesystem structures for the show. 
![chromecast](https://user-images.githubusercontent.com/17996032/215618047-9a2217bd-7d51-499c-9227-b51c595ad11c.jpg)
![shield](https://user-images.githubusercontent.com/17996032/215618049-94f3f3d6-c580-4401-8190-69b294e3846a.jpg)
![web_version](https://user-images.githubusercontent.com/17996032/215618050-ba55b523-31b1-4aff-9c02-f733f03a0289.png)
![file_structure](https://user-images.githubusercontent.com/17996032/215618269-089cfc77-ebb6-4324-94aa-95130367b96b.png)
![metadata_struct](https://user-images.githubusercontent.com/17996032/215618270-5642c637-7408-4376-8073-01080564cff3.png)

**Comment by tim-vk** [comment]
Ok, so i've got the "issue" reproduced:

I see that you have your default player set as "always ask". (hence the button labled "play with"). If you set the default player to any other option then the "shuffle" button should appear. Can you confirm that for me?

Checking the code: `FullDetailsFragment.java` contains the construction of these buttons. My guess the reason this is not implemented (yet) is that you'd need a "shuffle with" button since the player is not selected yet. 

To clarify the feature request a bit more. it should be:

"Implement shuffle when default player is set to "always ask"".

I might be wrong but other features are also not working when set to always ask, such as"resume" "instant mix" and "add to queue"

**Comment by tim-vk** [comment]
Whelp, appears that this is way easier to implement than I would have expected. I've created a PR.

Note that I am in no way a java or kotlin developer so it might take a while before everything is reviewed and implemented in a way that makes the code owner happy :).
