### ISSUE TITLE
(0.15.0-beta-3) Keyboard not centred

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2327]
### Describe the bug

0.14.0 Keyboard is centred with beta 0.15.0 it's hard right.

It's only a little bug.

### Application version

0.15.0-beta3

### Where did you install the app from?

Sideloaded APK

### Device information

NS Pro

### Android version

Android 10

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
This is intentional, the keyboard aligns to a side that makes the relevant content more visible (e.g. on the right when login is on the left).

**Comment by VampiricAlien** [comment]
Maybe on smaller screens? I can see a gab between the keyboard edge and there is content that has been cut off due to the keyboard placing also at the top my keyboard is cut off then turning lettings into words so you don't have to type them.

Could this be an option to have it left, right and centred?

**Comment by nielsvanvelzen** [comment]
We're not adding preferences for that no, if you want a fullscreen keyboard you should switch from gboard to another keyboard app.
