### ISSUE TITLE
Google tv android 12 bug

### ISSUE THREAD

**Issue by genylee** [jellyfin/jellyfin-androidtv#2332]
### Describe the bug

many files can't play and display format not supported ，but in kodi is normal , and in firestick  is normal

### Application version

0.14.5   0.15-beta3

### Where did you install the app from?

Google Play

### Device information

Google tv

### Android version

Andorid 12

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment]
Without proper details we can't do much about this.
