### ISSUE TITLE
Exoplayer: No video sounds, with libvlc if they sound

### ISSUE THREAD

**Issue by bich30** [jellyfin/jellyfin-androidtv#2337]
### Describe the bug

The videos don't play. I have tested with videos whose audio is EAC3 5.1 and Dolby 5.1.

### Application version

0.15.0-beta 3

### Device information

X96 X4

### Android version

Android TV 11

### Jellyfin server version

10.8

**Comment by nielsvanvelzen** [comment]
Without media info/ffmpeg logs/client logs we can't help. Closing as incomplete.
