### ISSUE TITLE
Failed to switch tracks

### ISSUE THREAD

**Issue by qianshun1** [jellyfin/jellyfin-androidtv#2347]
### Describe the bug

The audio file embedded in the video cannot be switched, only the default audio can be played

### Application version

0.15.0-beta4

### Where did you install the app from?

None

### Device information

Xiaomi MITV 4A

### Android version

Android 6.1

### Jellyfin server version

10.8.4

**Comment by nielsvanvelzen** [comment]
There really is not much information here to find out what goes wrong. Please provide all asked details and report as a playback issue instead.
