### ISSUE TITLE
Remove the seasonal greetings

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-androidtv#235]
There is a feature called "Seasonal Themes" that is enabled by default that will display a message to the user on halloween and christmas. In addition to that it will add a new row on the home screen with recommendations for things to watch.

The PR for home sections (#210) removes the second feature and therefore the only thing the seasonal "themes" will do is show a message. Personally I don't think it's a feature that fits Jellyfin at all.

My suggestion here is to remove the feature entirely.

**Screenshots**

The option can be toggled in settings:
![image](https://user-images.githubusercontent.com/2305178/71319842-dfba0200-24a3-11ea-93f4-9145e7839843.png)

The notifications look like this:
![image](https://user-images.githubusercontent.com/2305178/71319851-f19ba500-24a3-11ea-89f1-926b7758ba68.png)

I can't show the home row because I don't have any media tagged with holiday, holidays or christmas.

**Comment by dkanada** [comment]
That sounds good to me.

**Comment by thornbill** [comment]
Hmm I’m actually opposed to removing the seasonal suggestions. I think it’s a nice feature on par with the how services like Netflix promote seasonal content at the relevant times.

**Comment by nielsvanvelzen** [comment]
As far as I know the TV app is the only client that contains this feature. Where would you suggest putting the recommendations? Add a new type of section for the home screen the user can choose? In that case it should be implemented in web because we can't change the sections on TV (yet).

**Comment by nextlooper42** [comment]
I kinda like it. Tho, it is pain to translate. "Happy Holidays" in majority of european languages means summer holiday, not winter as i guess is right based on screen with snowflake in @nielsvanvelzen post. So my translation is wrong, or is it? Add more specific terms to this seasonal greeting, "Happy Holidays" mean christmas only in US and Canada, based on wiki https://en.wiktionary.org/wiki/Happy_Holidays
