### ISSUE TITLE
Move Enter Manually for User Name

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-androidtv#236]
Similar to #167, a user on Reddit reported they weren't able to log in. It turns out that having "Enter manually" down by the "Select server" button caused some confusion. They weren't aware that was the button needed to enter a username for a hidden user.

I see where the confusion could happen: the same button, with the same appearance and location, is used on the previous screen to enter a manual server address.

Perhaps we can move it up on the user screen to the list of users? If users are visible, it should be at the end of the list. If there are not, it would be the only option.

**Comment by Nautigsam** [comment]
I'm interested in working on it. I think we want something simple like 
![this](https://user-images.githubusercontent.com/7353930/71573732-9f7f0300-2ae5-11ea-9dca-dd31a85523b1.png)

**Comment by nielsvanvelzen** [comment]
Maybe show the manual input by default when no users are publicly visible too
