### ISSUE TITLE
Release date of the movie defaults to 1 January when only year of release date is available

### ISSUE THREAD

**Issue by linux2good** [jellyfin/jellyfin-androidtv#2360]
### Describe the bug

The app should not show misleading release date when there is no exact release date. Show only year instead. 
![jellyfin](https://user-images.githubusercontent.com/110234273/209395509-d00cbe7d-051e-4558-a126-4fd0efc64a27.png)
This movie was released in March 1972, not in January 1972

### Application version

0.14.5

### Where did you install the app from?

None

### Device information

Android TV

### Android version

Android 8

### Jellyfin server version

10.8.8

**Comment by mikewesten** [comment]
I think this is expected behavior. It's definitely customary on TMDB for editors to choose Jan 1st if the exact day and month of release is unknown.

**Comment by tukilo** [comment]
I tried myself and it shows the correct date. Trying to force refresh metadata may fix it?

![image](https://user-images.githubusercontent.com/7614098/222918288-5a18a780-dbd5-4b79-801e-c98755f707ce.png)

**Comment by nielsvanvelzen** [comment]
The API always sends a full date, it doesn't have support for only sending a year or month+day combo. So the app will always show the day, month and year, even if it's the 1st of January 1970. If we want to only show a year the served needs to be updated, nothing we can do on the client side.
