### ISSUE TITLE
Leaving an item puts the "cursor" back to the first item of the library

### ISSUE THREAD

**Issue by wolfiiy** [jellyfin/jellyfin-androidtv#2363]
### Describe the bug

1. Enter a library (TV, Movies and Playlists all seem to be affected);
2. Select any item (say series xyz) that is not the first (let's call it series abc) and click it to open the detailed view with the summary and seasons;
3. Click the back button on the remote;
4. The cursor will not be over xyz anymore, but over the first item (abc).

I could notice that when entering a library or leaving an item as I previously described, the avatar and AZ button on the top right seem to always be briefly selected.

### Application version

0.15.0

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro (2019)

### Android version

Android 11

### Jellyfin server version

10.8.8

**Comment by Drakonas** [comment]
Wanted to mention that this does also affect Photo libraries, which is increasingly more irritating.

**Comment by DemirG** [comment]
I've notice the same bug. Irritating when browsing the entire mobie library and you just want to check the description for say the first Rocky movie, and then it takes you back to the first movie in the list when going back.

**Comment by Soizzer** [comment]
The new version still has the same problem!
Jellyfin version: 0.15.1

**Comment by EliasGagnef** [comment]
Same here on the latest release, on Chromecast with Google TV

**Comment by nielsvanvelzen** [comment]
Sorry for the delay, I looked at this bug a few times but couldn't find the issue. I just found it and made a fix which will be in the next release (0.15.2).

**Comment by akesher123** [comment]
While state is preserved on the main menu (e.g. Recently Added), the issue persists while browsing All Items for me on 0.15.2 (Nvidia Shield).

**Comment by wolfiiy** [comment]
Exact same behavior on version 0.15.5, Shield TV Pro 2019, Android 11, JF 10.8.9. Clearing the cache fixes the issue until any piece of media is played, then the issue persists.
