### ISSUE TITLE
Delete TV Item

### ISSUE THREAD

**Issue by BB-Forrest** [jellyfin/jellyfin-androidtv#2364]
### Describe the bug

Upon watching an episode of a TV series the delete item is not available.

This is on 0.15.0, on 0.14.x releases the delete option appeared after watching the episode.

### Application version

0.15.0

### Where did you install the app from?

Google Play

### Device information

Sony Bravia TV - KD-49XG9005

### Android version

Latest Firmware for TV

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
The delete option was removed in 0.15 so this is not a bug. For more information see the relevant pull request (#1936).
