### ISSUE TITLE
Current Version of Jellyfin App on Amazon Fire TV says it works with my server version (10.7.6) when it doesn't

### ISSUE THREAD

**Issue by HardHero** [jellyfin/jellyfin-androidtv#2369]
### Describe the bug

1. Install App on Amazon Fire TV.
2. Open App to setup server connection.
      a. Server: 192.168.X.X -> Connect

Connection fails with the error being "Server uses version 10.7.6 which is not supported"

Do I just need to upgrade to the latest jellyfin server version? 

### Application version

2.4.4

### Where did you install the app from?

Amazon Appstore

### Device information

Toshiba Amazon Fire TV

### Android version

Fire OS Latest

### Jellyfin server version

10.7.6

**Comment by nielsvanvelzen** [comment]
Like the message says, we don't support 10.7.6. You'll need to upgrade the server to at least 10.8.1.
