### ISSUE TITLE
the "delete" icon does not appear in the episode or movie

### ISSUE THREAD

**Issue by jozemanue** [jellyfin/jellyfin-androidtv#2372]
### Describe the bug

Since the last update to 0.15.0, the icon to delete the episode or movie does not appear. in ios app and windows if it works fine.

### Application version

0.15.0

### Where did you install the app from?

Google Play

### Device information

Sony Bravia 65XH9096

### Android version

Android TV 10

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
Duplicate of #2364
