### ISSUE TITLE
App not installable from Amazon App store

### ISSUE THREAD

**Issue by RealGreenDragon** [jellyfin/jellyfin-androidtv#2377]
### Describe the bug

Hi,

I see on following link that Amazon finally publish Jellyfin for Fire TV v0.15:
https://www.amazon.it/Jellyfin-for-Fire-TV/dp/B07TX7Z725

But I cannot find the app in Fire TV appstore, so I'm unable to install it.
I check with Amazon account in the URL above and seems the app is marked as incompatible with all my Fire TVs (I have the following models: standard, 4K, and 4K Max), and it does not happens with v0.14.5.
I tried to change Fire TVs language to english but still I cannot find the app in the appstore.

Can you confirm the issue?

EDIT: I managed to install the app via Downloader app and v0.15 APK and it seems works, but the icon does not appear in the menu: maybe the app icon is not compatible?

Regards

### Application version

0.15

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire TV Stick 4K Max

### Android version

Fire OS 7.6.1.4

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
Unfortunately Amazon rejected out 0.15 update today and disabled our app. It's therefor **not possible to install the app via the store** until they approve the app. Quoting @anthonylavado from a [Reddit post](https://www.reddit.com/r/jellyfin/comments/zz46bs/comment/j29psoo/) about the same problem:

> Amazon app review sucks and if something goes wrong they just remove you until you update it again
>
> ---
>
> Some more context: A reasonable App Store would review your app quickly, and if there's an issue discovered, they keep the previous version available and just don't release the new one. Amazon is the complete opposite. We just got the email saying something failed, and at the same time, they pull the previous version of the app. Their app review is a horribly broken system and is even worse than Roku (and that's saying something)

**Comment by thornbill** [comment]
You would think if it failed on some devices they just wouldn't publish the update but NO making it unavailable is clearly better... 🙄

**Comment by anthonylavado** [comment]
The app should now be available.

**Comment by michaelkrieger** [comment]
Still not installable in the Canadian App Store :/

**Comment by nielsvanvelzen** [comment]
Amazon approved it today but it can take up to 48 hours to process... we can only wait unfortunately.

**Comment by michaelkrieger** [comment]
Appreciate the followup. Thank you.

**Comment by RealGreenDragon** [comment]
Now the app appear in appstore but the v0.14.5 is installed.
So the v0.15 has not be re-released yet?

**Comment by anthonylavado** [comment]
> Now the app appear in appstore but the v0.14.5 is installed.
> So the v0.15 has not be re-released yet?

It should only be v0.15. Did you manually install/sideload the app? If so, the store won't install newer versions to your device.

**Comment by theomajigga** [comment]
Still not available in US, CST, FireTV 4k. Just giving a data point.

**Comment by michaelkrieger** [comment]
v0.15 shows at [Amazon Store](https://www.amazon.ca/Jellyfin-for-Fire-TV/dp/B07TX7Z725) but says that it's incompatible with all Fire Sticks.  It as a result does not show up in the App Store from the Fire Stick.

![F811ACF1-B6CA-433B-AF5C-67C4B62601A0](https://user-images.githubusercontent.com/7321259/210303782-80cfcd64-acd2-4451-9c81-2f7560bb40c5.jpeg)

**Comment by anthonylavado** [comment]
Ugh. Stupid Amazon. They told us everything passed, but it seems they didn't update the compatibility listing.

I've escalated a support case, *again*.

Thanks for the heads up.

**Comment by anthonylavado** [comment]
Okay, Amazon says they've re-evaluated things. I'll check the compatibility listing, and as usual, they say up to 48 hours to see changes worldwide.

**Comment by anthonylavado** [comment]
Okay, apparently it's still not available despite them saying it would be.

We're going to go ahead and issue a .1 update, and push this out to Google and Amazon. It's probably the only way to fix it now.

**Comment by nielsvanvelzen** [comment]
I've just released version 0.15.1. We'll push it to the Amazon store soon and hopefully when it's approved the app will be available again. It can take up to a week though.

**Comment by nielsvanvelzen** [comment]
The app is visible in the store for me. It might take some more hours for all Amazon regions.

**Comment by RealGreenDragon** [comment]
Also for me it is visible on web browser appstore and marked as compatible with all my Fire TVs.
However the automatic update not works on any Fire TV, so I force the app delivery on all Fire TVs from web browser appstore and now It is installed on all devices (also on device where I manually installed the APK).

**Comment by glennpm** [comment]
I ordered through Amazon Prime. It said that the order was successful but it was not sent to my Firestick. I just spent a half hour with Amazon tech support and they eventually told me that the app is no longer available from them.

Does anyone have a source to get through Downloader?

**Comment by glennpm** [comment]
I found it via f-droid which I installed and then searching within F-droid for jellyfin and installed it.

[https://f-droid.org/en/packages/org.jellyfin.mobile/](url)

**Comment by nielsvanvelzen** [comment]
I've just checked it (again, 2 years later) and we're still available on Amazon Appstore. Please use our forum/chat (listed at https://jellyfin.org/contact) to get help with installing Jellyfin.

**Comment by glennpm** [comment]
Hi, it shows that it is available and I ordered it. The problem is Amazon didn't deliver it and told me this morning that it is no longer available. I installed it successfully with my link above.

[https://github.com/jellyfin/jellyfin-androidtv/issues/url](url)

**Comment by glennpm** [comment]
![Image](https://github.com/user-attachments/assets/1152b38e-a618-44e0-80a3-02d4424ca009)

The cost is 0.

**Comment by bozzio83** [comment]
Still cannot find this app on firestick app store
