### ISSUE TITLE
Shuffle play will eventually starting repeating episodes endlessly

### ISSUE THREAD

**Issue by makotech222** [jellyfin/jellyfin-androidtv#2378]
### Describe the bug

With a TV series of sufficient size, run shuffle over a long period of time, ~ 8 hours. Eventually, the player will repeat the same episode over and over.

I usually run a tv series on shuffle and let it play overnight. When i wake up, I'll notice that an episode ends and then plays over again immediately after. This is new behavior, probably within the last few weeks.

### Application version

0.15.0

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield 2017

### Android version

Android 9

### Jellyfin server version

10.8.3

**Comment by caseymtimm** [comment]
I am experiencing the same issue only it takes 3ish hours for it to start. Also version 0.15.0. Also started in the last week or so.

**Comment by wjbridge** [comment]
I can also confirm this behavior too. It starts after 2-3 hours. Using the version `0.15.0` with `10.8.8` server version.

**Comment by not-eric** [comment]
Confirming this with multiple series on two Firesticks, also running 0.15.0+ with Jellyfin 10.8.8

Series end up looping the same 3-4 episodes infinitely after a few hours of playback.

**Comment by mikezila** [comment]
I'm having the same issue even when not using shuffle. Just starting a show playing will eventually see it hung up on one episode, just playing it over and over. Using the Android TV client on a Chromecast.

At first I thought maybe it was because a show/season had a mix of played/unplayed episodes but it happens even if the whole season is unwatched or fully watched.

**Comment by FrostTorrents** [comment]
same issue as all above, running 0.15.0+ with Jellyfin 10.8.8

**Comment by ooobii** [comment]
Issue still persists with Amazon Fire Stick app v0.15.5, Jellyfin Server v10.8.9

**Comment by acreed1998** [comment]
Also using Amazon Fire Stick app v0.15.5, with Jellyfin Server v10.8.9. Interestingly found that if you stream to an external video player (used MX Player and I don't actually know if it works for others) instead of the ones native to the Jellyfin app then the repeating doesn't happen.

**Comment by GGProGaming** [comment]
I get this issue on the SECOND episode while shuffle playing a tv show. Chromecast running GoogleTV.

**Comment by klueman** [comment]
Same issue. It doesn't seem to have anything to do with how long the shuffle has been going, or the number of episodes in the playlist. It can happen on the 2nd episode or the 20th, I've yet to spot a pattern.

**Comment by SmaMan** [comment]
I’m running Android 0.15.9, server 10.8.10 on my Fire TV and it usually happens on the 3rd or 4th episode.

Hitting next will go to the next episode it’s picked out if it doesn’t advance on its own, but then it’ll go back to the repeat episode and then I’ll have to skip twice to get to the next shuffled episode, and so on…

**Comment by klueman** [comment]
I've also spotted the same pattern as @SmaMan. After it gets stuck on an episode, shuffle will work properly if you manually skip ahead to the next episode, and you can continue to manually skip each time, for as many times as you like, but even if you've manually skipped to the next episode 20 times, if you let that episode end, the autoplay will revert back to the "stuck" episode, and continue to loop it.

It's as if the shuffled playlist is working just fine, but an episode gets stuck in the "Autoplay Next" slot, and you have to manually skip ahead from that point forward to keep advancing the playlist.

**Comment by mikezila** [comment]
This is still happening to me. It happens both in shuffle and in just normal viewing. In both cases you can skip forward to the next episode, but it will just return to the "stuck" episode each time.

**Comment by sfescape** [comment]
I can add some more detail. From the Android TV app.

It appears that after a few shows the next show's preview and title come up, but at the end of the "watch now" timer it actually starts a program from earlier in the shuffle list.

If you hit the >| button it does actually proceed to the next show, but again if you let it go until the "watch now" timer expires it goes back to the earlier program that's looping.

**Comment by makotech222** [comment]
Looks like this might be fixed in latest 0.16 beta. The issue was in the MediaManager class, which would not advance the current media position if it was greater than the number of shows you have.

So if you are shuffling shows, and you have, say, 10 tv shows in your jellyfin library. Once you get to episode 10, it will no longer advance to the next episode.

I debugged this on 0.15 branch and found the bug. I fixed it, but realized in my PR that the file no longer exists on latest master branch.

**Comment by sfescape** [comment]
That doesn't match the behavior I see though. If I shuffle or even just play a playlist from the beginning it starts repeating after just a few shows (there are 30 shows in the playlist). So there may be additional circumstances which cause it to loop back to a prior spot in the list (or shuffled list).

**Comment by makotech222** [comment]
This is fixed in 0.16. Can be closed
