### ISSUE TITLE
Quick connect screen

### ISSUE THREAD

**Issue by vic1707** [jellyfin/jellyfin-androidtv#2383]
### Describe the feature you'd like

hi 👋 
The quick connect screen on the app is awesome and looks really great!

Unfortunately the image generated from media uses medias from all libraries and might show 18+ media/covers on a really big screen.
It happened to me today, thankfully I was alone 😓.

I don't know how it can be done but it would be really nice to be able to exclude some libraries from those used to generate this screen.

**Comment by nielsvanvelzen** [comment]
The server manages the splash screen and the app just uses it. So there's nothing we can change about it on our side. You can disable the splash screen in the server general section of the dashboard.

**Comment by vic1707** [comment]
Thx for the info !
