### ISSUE TITLE
Jellyfin not in Fire TV appstore

### ISSUE THREAD

**Issue by Fraxio** [jellyfin/jellyfin-androidtv#2386]
### Describe the bug

Jellyfin not in Fire TV appstore to be able to download

### Application version

0.14.5

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon fire TV Stick 4K Max

### Android version

Fire OS 7.6.1.4

### Jellyfin server version

10.8.6

**Comment by newton181** [comment]
Known issue #2377 

> Okay, Amazon says they've re-evaluated things. I'll check the compatibility listing, and as usual, they say up to 48 hours to see changes worldwide.

_Originally posted by @anthonylavado in https://github.com/jellyfin/jellyfin-androidtv/issues/2377#issuecomment-1371133381_
