### ISSUE TITLE
No way to configure what media is shown in the login page collage!

### ISSUE THREAD

**Issue by jedthe3rd** [jellyfin/jellyfin-androidtv#2390]
### Describe the bug

Android TV Login collage shows media from libraries that shouldn't be shown to all users or be public facing at all.

Steps:

1. Open Jellyfin Android TV app
2. Go to sign in page.
3. Select a users that isn't set to auto sign in.
4. Observe that any content for all libraries are used to generate the collage.

### Application version

0.15.1

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro

### Android version

Android 11

### Jellyfin server version

10.8.8

**Comment by thornbill** [comment]
The image is generated by the Jellyfin server and can be disabled in the admin dashboard for the server.

Closing this since it is not an Android TV issue.

**Comment by jedthe3rd** [comment]
Thanks, figured out why I was still seeing the splash screen even with it disabled. The android tv client cached it! Clearing the app cache fixed it.
