### ISSUE TITLE
`POST /Sessions/{sessionId}/Playing` only starts playing the first itemId parameter provided

### ISSUE THREAD

**Issue by HenkKalkwater** [jellyfin/jellyfin-androidtv#2394]
### Describe the bug

When controlling the Android TV app using another application, which in my case is Sailfin—the Jellyfin client for Sailfish OS which I'm developing—, the Android TV app plays only the first item when a request to the URL above has been made, ignoring the startIndex and the other items.

#### Observed behaviour
When wanting to play multiple items, Sailfin sends [a POST-request to `/Sessions/{sessionId}/Playing`](https://api.jellyfin.org/#tag/Session/operation/Play), with the list of items to play in the parameter `itemIds`. The `playCommand` and `startIndex` parameters are set as well.

The Android TV app in response only adds the first item from `itemIds` to the queue and starts playing it, ignoring the other item IDs and start index sent.

#### Expected behaviour
I expected the Android TV app to behave the same as the Jellyfin web client and as the API documentation describes: adding all the items from `itemIds` to the queue and start playing the item from `startIndex`.

### Logs

N/A

### Application version

commit caf85e56f1b9233bbc785fbb9c1ff2ead9215767

### Where did you install the app from?

None

### Device information

Raspberry Pi 4

### Android version

12, own build of https://github.com/android-rpi

### Jellyfin server version

10.8.5

**Comment by nielsvanvelzen** [comment]
Our current playback code doesn't support queuing multiple items so it only plays the first item. I've already implemented multi-queue in the playback rewrite (#1057) so this should be fixed when the rewrite is ready.
