### ISSUE TITLE
Audio night mode option can't be enabled on FireTV Stick 4k

### ISSUE THREAD

**Issue by nevado** [jellyfin/jellyfin-androidtv#2398]
### Describe the bug

After updating to 0.15.1 on FireTV Stick 4k, the new 'Audio night mode (experimental)' option is disabled (greyed out, and can't be selected) in the settings menu, and I can't see any obvious way to enable it.

Any suggestions please?

### Application version

0.15.1

### Where did you install the app from?

Amazon Appstore

### Device information

FireTV Stick 4k

### Android version

FireOS 6.2.9.4

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
Audio night mode is only supported on Android 9 and newer. FireOS 6 is based on Android 7.

**Comment by nevado** [comment]
Ahh makes sense! Thanks for explaining and all the great work on the app
