### ISSUE TITLE
Settings - Download & Install button

### ISSUE THREAD

**Issue by lenisko** [jellyfin/jellyfin-androidtv#2400]
### Describe the feature you'd like

Hey! 

It would be great to have a new option to `Download & Prompt to Install` the newest version of APK available.

This could save some time, as moving an APK file to TV is a bit of time-consuming.

**Comment by sambartik** [comment]
Not sure what you mean about Download & Prompt to Install, but you can install any APK remotely via adb from another device on LAN.

**Comment by lenisko** [comment]
I mean an option in menu which would execute a fetch of latest available APK and show prompt installation box. That way you could update APK without a need for additional tools nor machine.

**Comment by nielsvanvelzen** [comment]
Does your device not have the Google Play store / Amazon Appstore?

**Comment by lenisko** [comment]
It does, been thinking about support for beta revisions. But as I can see, recent ones are pushed as releases.

**Comment by nielsvanvelzen** [comment]
Beta versions are available on Google Play: https://jellyfin.org/posts/android-betas

**Comment by lenisko** [comment]
In this case, sorry for all confusion :) Thanks!
