### ISSUE TITLE
Won't connect on Fire Tv 4K

### ISSUE THREAD

**Issue by japamax** [jellyfin/jellyfin-androidtv#2402]
### Describe the bug

I use Jellyfin client on my tv with a firetv 4k stick and a 10.8.8 Jellyfin server 

with jellyfin-android-v2.5.0-beta : I connect and play without problems but the remote firetv is a real nightmare
and 
with jellyfin-androidtv-v0.15.2 : I CAN'T connect with users with empty passwords or with the 6 digit code. 

Can you synchronize client connection procedure with all other versions like jellyfin-android-v2.5.0 apk

Thanks

### Application version

0.15.2

### Where did you install the app from?

None

### Device information

Amazon FireTv 4K

### Android version

FireOS 6

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
> with jellyfin-android-v2.5.0-beta : I connect and play without problems but the remote firetv is a real nightmare

You're not supposed to use an app made for phones on a TV.

> with jellyfin-androidtv-v0.15.2 : I CAN'T connect with users with empty passwords or with the 6 digit code.

This doesn't really describe the issue. You say you can't connect yet you are able to login but the login fails. You say something about a 6 digit code but the app doesn't support pin login.

**Comment by japamax** [comment]
All my devices CAN connect to my Jelleyfin server
The only device that won't connect is the fireTv Stick 4K with jellyfin-androidtv

I installed  jellyfin-android-v2.5.0 to show that the issue is ONLY IN jellyfin-androidtv client with firetv Stick 4k
I installed   jellyfin-androidtv-v0.15.2 on phones and the connection works

On the firetv stick 4k, if the jellyfin-android-v2.5.0 can connect and not the jellyfin-androidtv,  
is because the connection code is different between the 2 clients.  It's that simple

I,ve no log for the moment but it's a 2/3 year issue

**Comment by japamax** [comment]
I justed test the  jellyfin-androidtv-v0.15.2-debug.apk 

jellyfin-androidtv-v0.15.2-debug.apk  connection WORKS
jellyfin-androidtv-v0.15.2-release.apk  connection DON'T WORKS

**Comment by nielsvanvelzen** [comment]
> I installed jellyfin-androidtv-v0.15.2 on phones and the connection works

Well this confirms there is no issue with the app but likely with your network setup. Please use our troubleshooting channels (Matrix/Reddit/Discord etc.) for that.

**Comment by japamax** [comment]
My ethernet setup network works on firetv with ALL APPS ON EARTH even  jellyfin-androidtv-debug and jellyfin-android except jellyfin-androidtv-release 
This is the reality


This is an 3 year issue :
https://www.reddit.com/r/jellyfin/comments/fywqxa/jellyfin_app_on_firestick_4k_is_unable_to_connect/

https://www.amazon.fr/Jellyfin-for-Fire-TV/product-reviews/B07TX7Z725/ref=cm_cr_arp_d_viewopt_kywd?reviewerType=all_reviews&filterByStar=critical&pageNumber=1&filterByKeyword=fire+tv+connect

https://www.amazon.fr/Jellyfin-for-Fire-TV/product-reviews/B07TX7Z725/ref=cm_cr_arp_d_viewopt_kywd?reviewerType=all_reviews&filterByStar=critical&pageNumber=1&filterByKeyword=fire++4k

Are you reading Reddit or forums like that ?


 
You remind me of an Amazon technician who argued with me that I had multiple email accounts when I only had one. after an hour of chat, he sent me his superior

Your overconfidence and disregard for an ultra-hard-to-fix bug and shoving it under the rug proves that this release will be constantly bugged for years and will eventually have security issues.

In your mind, the fact that the debug version is working and not the release, that doesn't bother you? You don't even have to look at the code. In a real world, your attitude would be considered unprofessional
And i won't do your job for you

**Comment by japamax** [comment]
A 20s debug show me that jellyfin-androidtv-debug and jellyfin-androidtv-release have not the same permissions and signature.

Are you serious ?
