### ISSUE TITLE
Special episodes shown in By Letter view

### ISSUE THREAD

**Issue by Finios** [jellyfin/jellyfin-androidtv#2403]
### Describe the bug

1. Activate "Smart Screen" in series library
2. Go to "By Letter"
3. \# is showing all episodes if their season and episode number is 0

![Jellyfin_By_Letter](https://user-images.githubusercontent.com/32433804/211621252-b7f32898-96e2-4acf-94b6-df7ce9eae71e.png)

![Jellyfin_Episode](https://user-images.githubusercontent.com/32433804/211621504-c18ce077-6e2a-4e26-8154-6c51f4d9ed03.png)

### Application version

0.15.1

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro (2017)

### Android version

Android Version 9.1.1(33.2.0.157)

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
Does this also happen on other clients (like the browser for example)?

**Comment by Finios** [comment]
As I see, it only is on Android TV App. 
If I sort my series by \# I only get the series starting with numbers on browser or Android App (Jellyfin + Findroid). On these clients they does not show the special episodes in series overview.
Is there an option to get the same "By Letter"-View on browser? If thats possible I will test it.

**Comment by Finios** [comment]
If I scroll a bit to the right, I will get shown all my other episodes of season 0 (S0E1, S0E2, ...) too.

If you open the 'by letter' section of a movie library I see an entry of the library folder jellyfin should index, containing all movies inside. E.g I have added the folders /mnt/movie/0-9, /mnt/movie/A, /mnt/movie/B, ... to my movie library and I see an entry 0-9 in /# in 'by letter'.

**Comment by tukilo** [comment]
As I understand it, does the # symbol represent any numerical content in the list?

I'm not 100% sure but in the class  "**ByLetterFragment**" line 15 it seems that it doesn't add the filter "**includeItemTypes**" in the query. When I do it returns only content that is numeric.

https://github.com/jellyfin/jellyfin-androidtv/blob/ca37eafb3dc93623fd72abe9e0d2c089c7d51d48/app/src/main/java/org/jellyfin/androidtv/ui/browsing/ByLetterFragment.kt#L15

`includeType?.let { includeItemTypes = arrayOf(it) }`

Could this solve the issue or am I missing something else/breaking something else? @nielsvanvelzen

**Comment by nielsvanvelzen** [comment]
I'm not sure but it makes sense to have the same parameters, jellyfin-web also sets the includeItemTypes for the request. I don't think it would break something else. Feel free to create a pull request!

**Comment by tukilo** [comment]
I thought the same thing but just to be sure
