### ISSUE TITLE
Sort by Date Added + Descending

### ISSUE THREAD

**Issue by DePingus** [jellyfin/jellyfin-androidtv#241]
Currently when you go to the Movies section and Sort by "Date Added" all the movies are displayed in ascending order (oldest added movies first). It would be much better if you could sort by descending instead (newest added movies first).

This would also be nice to do on the home screen. It seems that the "Latest Movies" section displays movies by premiere date and not date added to the server. Old movies I add never get displayed there.

**Comment by thornbill** [comment]
I completely agree that having a way to change the direction of the ordered items would be a nice feature to have.

I can't seem to replicate that behavior on the home screen. The order I see in the Android TV app matches what is present in the web interface for me. That said the home screen for Android TV has been updated lately so it more closely mirrors what you see in the web interface, so perhaps that change will fix the ordering you are seeing there.

**Comment by thornbill** [comment]
Seems we already have a ticket to track this. #154
