### ISSUE TITLE
Nvidia Shield Pro - Voice search no longer opens automatically on search

### ISSUE THREAD

**Issue by akesher123** [jellyfin/jellyfin-androidtv#2413]
### Describe the bug

1. Press search button
2. Observe that there is no automatic voice search (Shield Pro) or keyboard that shows up. You have to click the search bar for it to show

Previously a voice search would automatically begin on Shield when pressing search. This was actually rather annoying thanks to the loudness of the Android Mic activation sound, but it was more convenient. If this is an intentional design choice that's understandable, perhaps the keyboard should open automatically without an extra press if that's so.

### Application version

0.15.2

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
When the app doesn't have microphone permissions it doesn't show the voice search anymore. You can go to the Android settings -> Apps -> Jellyfin -> permissions and then enable the microphone permission.
