### ISSUE TITLE
Some items fail to playback with exoplayer

### ISSUE THREAD

**Issue by akesher123** [jellyfin/jellyfin-androidtv#2430]
### Describe the bug

1. Set exoplayer as default
2. Play item 
3. Observe

This item plays back fine when using LibVLC and can direct play fine using Jellyfin Media Player

Media info:

```Video
Title: Encoded by: *Removed name* - 1080p - HEVC - SDR
Codec: HEVC
Profile: Main 10
Level: 120
Resolution: 1434x1080
Aspect ratio: 4:3
Interlaced: No
Framerate: 23.976025
Bitrate: 5044 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p10le
Ref frames: 1


Audio
Title: English - AAC - Stereo
Language: eng
Codec: AAC
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 102 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No


Subtitle
Title: English - PGSSUB
Language: eng
Codec: PGSSUB
Default: No
Forced: No
External: No
```

### Logs

No errors exist in the server log.

Client logs:

```Playback error
--
com.google.android.exoplayer2.ExoPlaybackException: Source error
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:637)
at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:607)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:223)
at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: com.google.android.exoplayer2.ParserException: ContentCompAlgo 0 not supported
at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.integerElement(MatroskaExtractor.java:931)
at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor$InnerEbmlProcessor.integerElement(MatroskaExtractor.java:1952)
at com.google.android.exoplayer2.extractor.mkv.DefaultEbmlReader.read(DefaultEbmlReader.java:124)
at com.google.android.exoplayer2.extractor.mkv.MatroskaExtractor.read(MatroskaExtractor.java:512)
at com.google.android.exoplayer2.source.BundledExtractorsAdapter.read(BundledExtractorsAdapter.java:127)
at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1039)
at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:412)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
```

### Application version

0.15.2

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8.8 Linux (Unraid)

**Comment by zchtoy** [comment]
i found the same issue,but this  item plays back fine with ver v0.13.7 ,

**Comment by arjenanker** [comment]
I'm seeing similar things on my ShieldTV. Some things refuse to play in exoplayer, some things refuse to play in libVLC. This makes it unusable to me tbh. It needs to just work. The competition just works, I just switched over because they keep adding features nobody wants. But if I need to fiddle for every movie I want to watch....

**Comment by flan7** [comment]
Still effecting me on the latest version on an nvidia shield

**Comment by end2endzone** [comment]
I think I am experiencing the same issue but on a Huawei P20 Pro phone. Using latest version available from Google Play Store as of today (_Jellyfin Android 2.5.3_). There are no error in the server's logs. I see direct play and stop logs at 0ms. I do not know how to get client logs as the OP did. However, I am experiencing same as the OP: 
> This item plays back fine when using LibVLC and can direct play fine using Jellyfin Media Player.

My issue might be related to playing a file stream from an http request, specifically with ExoPlayer.
The file is OTA recording located on a local TVHeadEnd server. The player tries to play an URL such as http://username:password@tvheadend-ip-address:9981/dvrfile/357327252. Here is some things that I tried:
* It is not related to a security issue. I am able to manually copy/paste the URL to VLC (the android application) and the file plays fine using hardware acceleration.
* If I switch to an _External player_ and select _VLC Player_ for playback, the URL plays fine. The play fine with the _Web Player_ as well. It is only when the _Integrated player_ (ExoPlayer) is used that "Source error" error is displayed.
* If I manually copy the recording file to a local repository on the server, the file plays fine with the _Integrated player_.

I doubt this issue has something specific to the file format or codecs but here's the Media Info:
```
5e Rang-2023-09-18_20_002023-09-1820-00
Container: mpegts
Path: D:\jellyfin\local\5e Rang-2023-09-18_20_002023-09-1820-00.ts
Size: 440 MB

Video
Title: 720p MPEG2VIDEO SDR
Codec: MPEG2VIDEO
Profile: Main
Level: 4
Resolution: 1280x720
Aspect ratio: 16:9
Interlaced: No
Framerate: 59.94006
Bitrate: 18297 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1

Audio
Title: Fre - Dolby Digital - 5.1
Language: fre
Codec: AC3
Codec tag: AC-3
Layout: 5.1
Channels: 6 ch
Bitrate: 384 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Frm - Dolby Digital - Stereo
Language: frm
Codec: AC3
Codec tag: AC-3
Layout: stereo
Channels: 2 ch
Bitrate: 192 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No
```

**Comment by nielsvanvelzen** [comment]
> Jellyfin Android 2.5.3.

That's a different app. This repository is for the Android TV app, not the mobile one.

**Comment by mwt** [comment]
I have this issue on a Sony Bravia 4k VH21. None of my videos play in exoplayer so far.

**Comment by mwt** [comment]
Still an issue

**Comment by mwt** [comment]
Still an issue
