### ISSUE TITLE
It is necessary to provide a switch to turn off the background of the login screen

### ISSUE THREAD

**Issue by Hmilyhyun** [jellyfin/jellyfin-androidtv#2431]
### Describe the feature you'd like

Hello，
       Now on the TV client, the login screen for adding users has a background poster.
       It collects many posters together as a background display when there is no login yet. This includes many of my AV posters. This is not appropriate for people other than myself, and especially not for small children or family members watching TV together. So I hope the developer can provide a setting option to turn off the background display on the login screen. Thank you very much!

**Comment by nielsvanvelzen** [comment]
The server creates the splash screen and you can turn it off in the dashboard.
