### ISSUE TITLE
quick menu always closes

### ISSUE THREAD

**Issue by chr-zz** [jellyfin/jellyfin-androidtv#2436]
### Describe the bug

Hi,

For example, if you're browsing through movies and pressing the (burger menu button) on the remote, a quick menu will usually pop up where you can favorite the movie or select watch later.
this menu opens, but immediately closes again by itself.

this happens on the Firetv 4k, and the Firetv 4k MAX
Google says they are ( Android 7.1 & Android 9) devices.

Greetings

### Application version

0.15.2

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireTV Stick 4k & FireTV Stick 4k MAX

### Android version

Adroid 7.1 - FireOS 6.2.9.4 / Android 9 - FireOS 7.6.1.4

### Jellyfin server version

10.8.8

**Comment by nielsvanvelzen** [comment]
I can confirm this happens with the latest release, but I have no clue as to why it does that. Did you also experience this issue on older app versions?

**Comment by chr-zz** [comment]
Hi,

v0.14.5 definitely didn't have this problem. I didn't get the v0.15.0 from amazon at all. not even after more than a week. in the app store it went directly to v0.15.1, then 2 days later v0.15.2 was already out.

**Comment by nielsvanvelzen** [comment]
Thanks, I was able to figure out where the issue came from and fixed it. Menu's will work again in the next release!
