### ISSUE TITLE
Series poster not displayed in Android TV

### ISSUE THREAD

**Issue by ejalal** [jellyfin/jellyfin-androidtv#2447]
### Describe the bug

A couple of versions ago (both Jellyfin server and Android TV app), the Jellyfin Android TV App stopped showing series posters for new imported series.

Can't tell if it's coming from the App or the Server.
Older series imported prior to the "faulty" App or Server version still show the posters.
Tried resetting the App, clearing the cache... still behaving the same way (old series show poster, new ones no poster)

Jellyfin Web, and the regular Android App (Phone) work OK. It's only happening with Android TV

### Logs

Please help extract the logs

### Application version

0.15.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield 2017

### Android version

Android 9

### Jellyfin server version

10.8.9

**Comment by ejalal** [comment]
A similar instance of this issue is heppening with Kodi as well
[#342](https://github.com/jellyfin/jellyfin-kodi/issues/342)

**Comment by ejalal** [comment]
Well, I reinstalled jellyfin from scratch again, it's was better but not completely resolved, until I checked my adguard logs and found that it was blocking image.tmdb.org

I'll close this for now.

**Comment by hd-heller** [comment]
Hello,
I face exactly the same issue! Just set up jellyfin for android TV on a new Xiaomi Stick 4k with android TV 11, no adguard or anything else. Have exactly the same issues on the Amanzon fire Stick 4k. Standard android version does not show these issues (working on a tablet, tested on Xiaomi Stick 4k with android TV 11).
Thanks for reactivating!
