### ISSUE TITLE
An option for non-exclusive audio focus

### ISSUE THREAD

**Issue by charmarkk** [jellyfin/jellyfin-androidtv#2450]
### Describe the feature you'd like

I like to play Spotify in the background with visualizer type videos playing in the background a lot when cleaning etc., and it'd be super cool to be able to do that with my projector too. Some apps seem to have the option of NOT grabbing Android audio focus (e.g. S0undTV), so when YouTube or Spotify is playing something, S0undTV will play over it.

Is there a way to enable that as an option with Jellyfin too? It's the one thing I miss from Plex and basically all HTPC setups. It can kind of be worked around on a phone with Shizuku/rooting, but those options don't work so well with a Chromecast.

**Comment by BotBlake** [comment]
Thank you for your feature request and for sharing your use case with us. We understand the appeal of allowing audio playback without requesting audio focus, especially for scenarios involving simultaneous media consumption.

However, according to the [Android developer guidelines](https://developer.android.com/media/optimize/audio-focus?hl=en):
> "When your app needs to output audio, it should request audio focus."

While this is not a strict requirement, it is strongly recommended as a best practice to ensure a consistent and user-friendly audio experience. By requesting audio focus, apps help avoid conflicting or overlapping audio outputs, which can degrade the overall user experience across the Android ecosystem.

Given the importance of adhering to these guidelines for predictable behavior, we have decided not to implement this feature. We hope you understand our reasoning, and we’re grateful for your suggestion. Please don’t hesitate to share any further feedback or ideas!
