### ISSUE TITLE
Weird continue watching behaviour.

### ISSUE THREAD

**Issue by Darius82** [jellyfin/jellyfin-androidtv#2474]
### Describe the bug

Hi, this is my first bug report.

Several things happen in the main screen.

As you can see in the picture included Black Panther WFE appears twice. I have it only once in my library. When playing the left one it plays Black Panther 1.

It also happened with reno 911 and with Terminator 2. This one appearing up to 3 times. I did not check with those what file it would play. I will get more information and check again.

It happens in all my "Android TV" devices (Fire TV, Android TV 9 and Google TV). Web and android app  work as expected. 

![imagen](https://user-images.githubusercontent.com/16259888/216720841-f83e5d60-2dd9-4079-b42f-20de4f712fa9.png)

### Application version

0.15.11, 0.16 beta 2

### Where did you install the app from?

Sideloaded APK

### Device information

Amazon FireTV (2021), Google TV 4k. Philips TV Android TV 9

### Android version

Google TV 12, Android TV 9. Dunno FireTV Version

### Jellyfin server version

10.8.10

**Comment by Darkhost1999** [comment]
![20230413_101701.jpg](https://user-images.githubusercontent.com/60384196/231806097-1ca81dde-e892-4f83-bd0f-8238dd5f8869.jpg)

I get duplicates too and here is the steps to reproduce.
Watch a movie to the end that it'll remove itself from the continue watching list. Press back and see the 1st watched movie (furthest to the right) will become duplicated.
Exit the app entirely and Google Android TV Play Next category will display the movie you finished in play next without recognizing you just finished the movie.
OR
Watch a movie long enough to add it to the continue watching list and then continue watching your most recently watched continue watching movie from anywhere it is listed. Doesn't matter where.
When you exit in the middle of your movie again. Watch that it'll add to your continue watching list again as a duplicate BUT the progress bar on the bottom will be different. The 1 on the left (most recently played) will be accurate. The one on the right will be your 1st watch time's progress bar. Notice I said 1st. You can watch the movie 3, 4, 5 times. The 1 on the right is your 1st watched. The 1 on the left will be updated correctly every time.
Click on the duplicate (the image in the right with the 1st watched time progress bar) it'll say the correct resume time as what should be displayed in the screen before. Return to that screen before. The progress bar will fill itself out and will be accurate but the duplicate will remain and will now follow the same laws as before but with the resume playback time of the time you last clicked on that image.

Exit the app end it's background processing (aka force stop) then reopen the app and this will refresh the continue watching list and clear out all duplicates including will remove titles that wrongfully remain on the Google Android TV play next smart screen of the actual TV itself no relation to Jellyfin.

Aka this is just a memory issue. Solved by simply refreshing the loaded memory.

**Comment by Darkhost1999** [comment]
Can still get this issue marking a movie or show as watched and going back to the continue watching screen. Inside Jellyfin. This isn't the play next on the android TV itself. This is inside Jellyfin, shows and movies happen and it has to be because of a lack of clearing memory and refreshing I'm pretty confident in that.

**Comment by Darius82** [comment]
Same here, still happening.

Have one show/movie on "continue watching". End a movie and that show/movie will get duplicated in the list.

As Darkhost says if you exit and enter the app again it will display only one item as it should.

**Comment by lrduncan** [comment]
I can confirm this duplication on continue watching is still happening on 0.15.12 release. Basically the same behavior as the last comment by @Darius82 where you end an episode and whatever show was next to that one will be duplicated. Exiting and reopening the app fixes it.

**Comment by Darius82** [comment]
I have to say that in the 0.16 beta 5 version this does not happen anymore.

I'm waiting for the final release 😉

**Comment by lrduncan** [comment]
@Darius82 That's great news! Perhaps related to this issue here? https://github.com/jellyfin/jellyfin-androidtv/issues/3021 Hopefully this will be closed soon as well!

**Comment by Darius82** [comment]
> @Darius82 That's great news! Perhaps related to this issue here? #3021 Hopefully this will be closed soon as well!

You're right! it's related and as I can see it's been merged in  #3024 so I'm closing this issue and now we only have to wait for the final release.

My issue is/was the same as the ones reported in #3024 as you mentioned and also in #3051
