### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by illnesse** [jellyfin/jellyfin-androidtv#2475]
### Describe the bug

Click on search button in the top 
Enter any search string 
Hit enter on on-screen-keyboard
....
Nothing happens

Works fine on the web version

Has been broken forever

### Application version

0.15.3

### Where did you install the app from?

None

### Device information

Nvidia Shield Pro latest

### Android version

Android 11

### Jellyfin server version

10.9.0

**Comment by nielsvanvelzen** [comment]
I can't reproduce this issue with your provided steps, search has been working forever. We also don't support unstable server versions in the app.

**Comment by nielsvanvelzen** [comment]
Closing as stale (author did not reply with proper reproducible steps)

**Comment by gazhay** [comment]
Search works fine on a browser, but the android tv search has not worked in a long time.

Multiple fire Tvs, an nvidia shield and google chromecasts all just show blank pages after a search term is entered. 
Debug log shows nothing - no errors - the search doesn't even seem to happen.

Server is linux ubuntu, up-to-date.

**Comment by derterboy** [comment]
Same problem here. Working in Webversion and in AndroidApp.
I gave up using search on AndroidTV App...
Using Jellyfin 10.8.10 and tried the AndroidTV App on Shield and Fire 4K Stick.

**Comment by Zeusy123** [comment]
Same problems here firestick latest jellyfin app and latest jelly server.... search has never worked in the firestick app

**Comment by nielsvanvelzen** [comment]
No, the issue description is not useful at all (unable to reproduce) and when inquiring for details you replied with a 😄 and did not reply again. If you feel like providing additional information I'll re-open it.

**Comment by derterboy** [comment]
> 

Please tell us which additional information is needed. As someone else already stated the debug log shows nothing so I am out of ideas about which information you could need.

**Comment by gazhay** [comment]
Not sure why this is closed?

Perhaps you could issue a debug build for us android users with the issue that would yield some further information?

We can't magically produce debug information for things if they aren't in the logs.

**Comment by kelthor85** [comment]
> Same problem here. Working in Webversion and in AndroidApp. I gave up using search on AndroidTV App... Using Jellyfin 10.8.10 and tried the AndroidTV App on Shield and Fire 4K Stick.

Exactly the same for me. Search is fine on my phone, fine on the desktop app, but when I hit the magnifying glass on the shield, nothing. I tried two shields, same result. 
Android tv version 0.18.4 and server build 10.10.3 on win 10.
