### ISSUE TITLE
DV does not gets triggered by exoplayer

### ISSUE THREAD

**Issue by RoccoRakete** [jellyfin/jellyfin-androidtv#2481]
As described in the title.

Jellyfin log says Bitrate exceedes the limit. But there is no limit set. So it transcodes.

If I change the limit to 120mbit/s and change it back to Automatic, it works in 99% of the cases.

Using JustPlayer solves the problem, but exoplayer feels and works better. So I really don’t want to switch..

Disabling transcoding for my user on the server solves the problem too, but some of my clients need transcoding, so that isn’t a option.

Hardware is a Schield TV Pro 2019 with the jellyfin APK v0.15.3.

**Comment by Ge082** [comment]
On my side I can't play DV content on Jellyfin Android TV, it always falls back to HDR10, playing the same content on VLC or Plex triggers DV as expected. Maybe related to license cost ?

**Comment by Martin1134** [comment]
>Maybe related to license cost ?

I don't think so. I mean, it works... kinda... sometimes?!

**Comment by Martin1134** [comment]
https://user-images.githubusercontent.com/44879342/218270856-2f072353-f483-47df-aa43-0296eb4248c0.MOV

**Comment by Ge082** [comment]
Hmmmm, may I ask what hardware you use ?
I'm using Nvidia Shield 2019 pro with an LG OLED C2 2022 but it always falls back to HDR10 for some unknown reason

**Comment by Martin1134** [comment]
> Hmmmm, may I ask what hardware you use ?


Sure. Shield TV Pro 2019. 55" lg b2. 

Player is exoplayer. 

It sounds similar to the problem I'm facing, but mine falls back to SDR most of the times.
My temporary fix is to change the maximum allowed Bitrate to 120mbit/s, this fixes the issue in 99% of the cases. 

Using JustPlayer for AndroidTV fixes the issue entirely. But it doesn't work as well as exoplayer, doesn't look this good and isn't well integrated. So this isn't really an option for me to switch to it.
