### ISSUE TITLE
Return to the list of movies where you were.

### ISSUE THREAD

**Issue by Archontes** [jellyfin/jellyfin-androidtv#2487]
### Describe the feature you'd like

I have ~700 movies in my movies library. When I choose a movie from the list to read its description, then hit back, I am returned in the UI to the beginning of the list, instead of to the point in the list where the movie was.

The desired behavior would be for the UI to return to the movie list at the point where the list was departed from previously, with the previously selected movie highlighted.

**Comment by Tuckie** [comment]
Yes please! Same issue in my library of shows.

**Comment by tukilo** [comment]
I have tested it and it works fine for me, it appears in the position it should be when I go back to the list of films.
On which device does this happen?

**Comment by Darkmagister** [comment]
i'm having the same issue on my android tv i usually change the order from alphabetical to date added
android tv: 10, build: qtg3.200305.006.3934
app: 0.15.5

**Comment by Darkhost1999** [comment]
Works on my Android TV
TCL Model 50S434
TV+ OS Version V5.2.0
Jellyfin 0.15.6
Do you have any browsing customizations that may be causing this?

**Comment by Darkmagister** [comment]
i updated to 0.15.6 and now it seems to work correctly.

**Comment by FaNt4zMa** [comment]
I still experience this issue on Chromecast and Fire TV devices. Using the latest 0.15.6 app, app/user settings are default. Thanks!
