### ISSUE TITLE
Saving current music queue does nothing

### ISSUE THREAD

**Issue by silentTeee** [jellyfin/jellyfin-androidtv#2500]
### Describe the bug

1. Enter Music Library
2. Set up queue of songs to play
3. Enter queue interface
4. Select "Save as Playlist" icon (the floppy disk) and enter name.
5. Select "Done"
6. Back out to Music Page

### Expected Behavior
Newly created playlist shows up under "Playlists" row

### Actual Behavior
No new playlists show up. Tried backing out of the app and re-entering, as well as initiating playback to see what would happen, with no change.

### Application version

0.15.3 release

### Where did you install the app from?

Google Play

### Device information

Hisense HiSmartTV A4

### Android version

Android 9

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
Looks like this has been broken for a while now. We will remove the save functionality from the client for now.
