### ISSUE TITLE
Live TV Guide will reset back to beginning of list regardless of channel being viewed. 

### ISSUE THREAD

**Issue by junobomb** [jellyfin/jellyfin-androidtv#2501]
### Describe the bug

While watching Live TV on any channel, if guide is pulled up it will load and start list on beginning of list instead of starting guide on currently viewed channel.      
i.e. Watching channel 100, will pull up guide and guide will start list on channel 1 instead of current channel 100.   This occurs in both main guide and pull up guide. 

### Application version

0.15.3

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireStick 4K Max

### Android version

FireOS 7.6.2.4

### Jellyfin server version

Version: 10.8.9

**Comment by junobomb** [comment]
Bump

**Comment by junobomb** [comment]
Issue still occurs in latest v0.15.12 client.

**Comment by rrioux** [comment]
Confirmed bug is still present in v0.16.4.

**Comment by rrioux** [comment]
Confirmed bug is still present in v0.16.6.

**Comment by rrioux** [comment]
Confirmed bug is still present in v0.16.11.

Also, curious why this app doesn't use the same Web based sources as other JF apps? The consistency and stability would be real nice - and using the more widely developed/tested code base for the Web UI would make a lot of things easier.

**Comment by junobomb** [comment]
I agree the androidTV version of the app behaves quite differently within Live TV

**Comment by rrioux** [comment]
Fixed in 0.17.0!
