### ISSUE TITLE
Sign In Screen Artwork

### ISSUE THREAD

**Issue by seniorm0ment** [jellyfin/jellyfin-androidtv#2502]
The sign in screen where you put username and password in on Android TV shows a background with cover art from all the various films on the Jellyfin server.

Can there please be an option to disable certain libraries from showing films up there, or just set static art?
Maybe this is a css thing?

**Comment by nielsvanvelzen** [comment]
The server creates the splash screen and you can turn it off in the dashboard. The client just uses it and has no way to change it.

**Comment by seniorm0ment** [comment]
What is the option called to disable it?

**Comment by nielsvanvelzen** [comment]
Dashboard -> General -> "Enable the splash screen" (at the bottom of the page)
