### ISSUE TITLE
Unable to log in from Amazon Fire TV

### ISSUE THREAD

**Issue by AsamiImako** [jellyfin/jellyfin-androidtv#2503]
### Describe the bug

1. Open Jellyfin App on Fire TV
2. Use automatically-discovered server
3. Add user to server, client prompts for quick connect
4. Open Jellyfin on server, log in and go to quick connect menu as instructed
5. Input code and authorize

Expected result: Client is logged in

Actual result: Client outputs "Invalid username and/or password"

The same happens when using password login.

The server does appear to accept the login, as the following lines appear in the logs after the attempt(s):
`[2023-02-15 14:10:35.183 -05:00] [INF] [38] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "[USERNAME]" has succeeded.
[2023-02-15 14:10:35.184 -05:00] [INF] [38] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "[USERNAME]": 2/0
[2023-02-15 14:10:35.186 -05:00] [INF] [38] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: "[TOKEN]"
[2023-02-15 14:10:36.035 -05:00] [INF] [37] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "[USERNAME]" has succeeded.
[2023-02-15 14:10:36.036 -05:00] [INF] [37] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "[USERNAME]": 3/0
[2023-02-15 14:10:36.037 -05:00] [INF] [37] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: "[TOKEN]"
[2023-02-15 14:10:46.635 -05:00] [INF] [37] Jellyfin.Server.Implementations.Users.UserManager: Authentication request for "[USERNAME]" has succeeded.
[2023-02-15 14:10:46.636 -05:00] [INF] [37] Emby.Server.Implementations.Session.SessionManager: Current/Max sessions for user "[USERNAME]": 3/0
[2023-02-15 14:10:46.638 -05:00] [INF] [37] Emby.Server.Implementations.Session.SessionManager: Reissuing access token: "[TOKEN]"`
(Note that the username and tokens have been substituted. The tokens in this section were all identical as well)

### Application version

0.15.3

### Where did you install the app from?

Amazon Appstore

### Device information

Toshiba 50" FireTV Model 50LF711U20

### Android version

Fire OS 6.2.9.5

### Jellyfin server version

10.8.9

**Comment by itslukebtw** [comment]
Experiencing the same issue using an Android TV

**Comment by ACR-Jeff** [comment]
I have had this issue for a very long time.

**Comment by mikewesten** [comment]
Same. Every time I reset my Firestick, I have to create a brand new Jellyfin user account to log in with. The app rejects any and all prior-made accounts (including the usernames themselves, so no recycling of names, those have to be new as well). It's annoying. It takes a good chunk of time to re-make an account and set it all up. I never power off my Firestick because of this.

**Comment by nielsvanvelzen** [comment]
Please share **client** logs so we can figure out what goes wrong. Without logs we can't help.

**Comment by AsamiImako** [comment]
I cannot find any log files on any of the accessible portions of my FireTV's internal storage. Could you explain where or how they're recovered to share?

**Comment by nielsvanvelzen** [comment]
You'll need to use logcat to get the logs from a device: https://wiki.lineageos.org/how-to/logcat

**Comment by AsamiImako** [comment]
As best I can tell, this is what it seems to spit out as the error occurs:
`02-21 18:56:24.132  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: GET http://192.168.1.201:8096/Users/Public
02-21 18:56:24.177  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: GET http://192.168.1.201:8096/Users/Public
02-21 18:56:24.250  4671  4715 W OpenGLRenderer: Points are too far apart 4.000003
02-21 18:56:25.497  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: POST http://192.168.1.201:8096/Users/AuthenticateByName
02-21 18:56:25.618  4671  4676 I art     : Do full code cache collection, code=460KB, data=502KB
02-21 18:56:25.620  4671  4676 I art     : Starting a blocking GC JitCodeCache
02-21 18:56:25.621  4671  4676 I art     : After code cache collection, code=449KB, data=417KB
02-21 18:56:25.648  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: GET http://192.168.1.201:8096/QuickConnect/Initiate
02-21 18:56:30.705  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: GET http://192.168.1.201:8096/QuickConnect/Connect?secret=
02-21 18:56:35.745  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: GET http://192.168.1.201:8096/QuickConnect/Connect?secret=[SECRET_KEY]
02-21 18:56:40.773  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: GET http://192.168.1.201:8096/QuickConnect/Connect?secret=[SECRET_KEY]
02-21 18:56:45.802  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: GET http://192.168.1.201:8096/QuickConnect/Connect?secret=[SECRET_KEY]
02-21 18:56:45.831  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: POST http://192.168.1.201:8096/Users/AuthenticateWithQuickConnect
02-21 18:56:45.867  4671  4676 I art     : Do partial code cache collection, code=450KB, data=425KB
02-21 18:56:45.868  4671  4676 I art     : After code cache collection, code=450KB, data=425KB
02-21 18:56:45.868  4671  4676 I art     : Increasing code cache capacity to 2MB
02-21 18:59:22.042  4671  4671 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
02-21 18:59:22.042  4671  4671 W IInputConnectionWrapper: setSelection on inactive InputConnection
02-21 18:59:22.502  4671  4671 I org.jellyfin.sdk.api.client.KtorClient: POST http://192.168.1.201:8096/Users/AuthenticateByName`

I restricted this to the PID Jellyfin seemed to be using, as the actual full logcat dump is massive and trying to make sure it contains no sensitive info is a pain, if you can give more detailed instructions I'll gladly do my best to provide whatever info you need.

**Comment by AsamiImako** [comment]
Still broken as of 0.15.5

**Comment by seriouz** [comment]
Still broken on FireTV 0.15.9.

**Comment by seriouz** [comment]
Yesterday i tried again with the 
jellyfin-androidtv-_v0.15.10-release_ no success. **But** then i tried the [jellyfin-androidtv-v0.15.10-debug](https://github.com/jellyfin/jellyfin-androidtv/releases/download/v0.15.10/jellyfin-androidtv-v0.15.10-debug.apk)  release and this worked flawelessly on mit FireTV-Stick! For anyone who has problems, please check out the debug version.
@devs Any ideas what could be the probleme that the release version does not allow username/password logins nor quick-connect but the debug version has no problem?

**Comment by nielsvanvelzen** [comment]
The debug and release version use the exact same code but they install a separate apps so it might have worked because the app didn't have any data. Unfortunately I have yet to receive complete client logs to get an idea of what's happening.

**Comment by seriouz** [comment]
How can i activate logs on my FireTV-Stick download them and send them to you? Install ES-Explorer on the FireTV-Stick?

**Comment by pbranly** [comment]
Hi
I could fix the issue by creating a new user . So now I have 2 users in my server. 
one is working in all the systems except in the firetv
Another one dedicated for the firetv.

This is not a fix but a work around only
Phil

**Comment by rastacalavera** [comment]
Here is documentation on how to connect to the fire stick and put it in developer mode. I have experienced this at other people’s home but don’t have my own to test https://developer.amazon.com/docs/fire-tv/connecting-adb-to-device.html

**Comment by pravardhanreddy** [comment]
Hi. I am facing this issue for a couple of months now. Used to work before. Not sure what happened. I can help as much as I can to resolve this. I miss watching content on my tv. I posted in the other issue too #2830. I get `SSL handshake failed` error when trying to connect to my server. 

### Server Details
```
Server Version: 10.8.10
Docker Image: jellyfin/jellyfin:latest
sha256: b27de364af61892a0d4f2d51bd3f84d13a43a640854dc534cb33b14110529c8d
Hosting: Via Cloudflare tunnel
Security: TLS v1.3 enabled but the minimum TLS version is set to TLS V1.0
```

### Client Details
```
Device: Fire TV Stick 4K Max
S/W Version: Fire OS 7.6.4.6
App: jellyfin-androidtv 0.15.10 debug
```
[logcat.txt](https://github.com/jellyfin/jellyfin-androidtv/files/11944002/logcat.txt)

Logcat collected after attempting to login and I get the SSL error.

Please fix 🙏

**Comment by pravardhanreddy** [comment]
I did some more digging around about this issue and found this other similar issue #930 
The main problem, if I understood correctly, seems to be with android 7 not supporting some new encryptions.
[This](https://github.com/jellyfin/jellyfin-androidtv/issues/930#issuecomment-1435655227) comment provides a workaround for this problem. That won't work for me since I am using Cloudflare tunnels and I can't seem to set such preferences.
The weird part is that everything was working perfectly some time ago.

**Comment by thornbill** [comment]
Using cloudflare tunnels with Jellyfin likely violates cloudflare's terms of service so you will not find support for that here.

**Comment by pravardhanreddy** [comment]
Can't do much else when you are behind a CG-NAT. Hopefully this gets fixed. Thanks for this project.

**Comment by seriouz** [comment]
Did anyone test it with the [debug version app](https://github.com/jellyfin/jellyfin-androidtv/releases/download/v0.15.10/jellyfin-androidtv-v0.15.10-debug.apk)? I am still have no issues with using it daily and switching profiles. The non-debug app still has the issue.

**Comment by Pantar2205** [comment]
Is anyone able to confirm Amazon dongles are back working yet?

**Comment by kode54** [comment]
I can’t even get it to connect to my discovered server. Conversely, I can’t get Plex to connect to the same machine, either.

**Comment by Panpan255** [comment]
Same I’m running the 0.16.2 release and it says no matter what it can’t find my server  can I get some help I want to watch my shows from my fire stick
![image](https://github.com/jellyfin/jellyfin-androidtv/assets/105138162/0be783c0-7924-42e4-9fe7-12e75983acd9)

**Comment by kode54** [comment]
I should have dropped my comment from this, as the issue turned out to be one with getting anything on my LAN to connect to my desktop due to Tailscale subnet routing going awry and breaking the desktop's outgoing routes to the rest of the LAN, which should otherwise have been 100% direct.

**Comment by fungos** [comment]
Same issue with a generic android tv box. It automatically finds the server, but cannot log (via username nor quick connect).
