### ISSUE TITLE
question about transcoding

### ISSUE THREAD

**Issue by satstarter** [jellyfin/jellyfin-androidtv#2506]
### Describe the bug

play a video file with ass subtitles and exoplayer as player i know exoplayer cant play ass it needs transcoding
but transcoding no longer works in server version 10.8.9 ?

so please @nielsvanvelzen  or someone else of the team can you confirm this bug is known and there wil be a fix someday?
i have put this question on reddit on jellyfin for android and on jellyfin server on github i hope someone can or willing to give an answer on this because also 10bit video's on my tablet needs transcoding but after the update to 10.8.9 it seems the server dont transcode anymore

thanx in advance

### Application version

15.3

### Device information

everything

### Android version

android 13

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
The app does not currently support subtitles with the SSA and ASS formats like you said and requires transcoding to function properly. There are no known issues with that. I'm running 10.8.9 myself and the subtitles work fine for me.
