### ISSUE TITLE
Ability to customize default TV channel

### ISSUE THREAD

**Issue by OctoNezd** [jellyfin/jellyfin-androidtv#2513]
### Describe the feature you'd like

Google TV devices display only one channel from app, and dont provide any way to customize it. And by default, the Jellyfin channel just shows media libraries, at least on my TV:
![image](https://user-images.githubusercontent.com/15308404/219961627-52175e62-4bd1-4b75-a98a-7e4b98cbf8c8.png)
The option to change that to suggestions from library rather than libraries would be nice

**Comment by Pfuenzle** [comment]
How did you get this to show up? For me, nothing from jellyfin is showing on my homescreen

**Comment by OctoNezd** [comment]
Jellyfin channel shows up by default for me on my google tv by TCL on official google play, and shows me my collections. You may be running apps-only mode.

**Comment by OctoNezd** [comment]
Due to the fact that this cant be implemented because Google prefers to lock everything down and shove ads down user throats, I am closing this issue.
