### ISSUE TITLE
No transcoding of 4K media on 1080p device

### ISSUE THREAD

**Issue by avionics75** [jellyfin/jellyfin-androidtv#2516]
### Describe the bug

I have a Xiaomi Mi Stick HDMI dongle with the latest Jellyfin Client and Server installed.
This dongle is having a maximum resolution of 1080p.
Playing a 4K content through the Jellyfin AndroidTV app is throwing a player error as the app doesn't ask for a 1080p transcode ans tries to directplay the 4K content since my bandwith is fast enough.
The dongle is not powerfull enough to handle 4K content. The only solution is to force a content transcoding by lowering the maximum bandwith inside the client app.
Would it be possible to add an option in the Jellyfin client to force transcoding of a content based on the client device resolution ?
Thanks in advance !

### Media info of the file

```shell
4K content (mkv)
```

### Application version

0.15.3

### Device information

Xiaomi Mi Stick

### Android version

Android 8

### Jellyfin server version

10.8.9

**Comment by nextlooper42** [comment]
This bug also happen on **Chromecast with Google TV** (https://store.google.com/us/product/chromecast_google_tv . After playing file that is 4k in source it will try to play this same file on Chromecast - it should request transcode to 1080p since thats maximum supported resolution of device. Playback of 4k file will result in error toast every time.

I thought that device will report it capabilities to server and that will send compatible file to device, but that's not a case at all - but it works on Android Phone app. Can we add toggle to settings that will forced transcode for example to specific resolution?

**Comment by thornbill** [comment]
I was under the impression that most devices could handle downscaling on the device. Modern Fire TVs definitely do. Currently we only have an exception for older Fire TVs to explicitly request 1080p streams.

https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.kt#L41

**Comment by nextlooper42** [comment]
It seems like this is not always a case unfortunately. I tried multiple local players to downscale video but it seems there is no horsepower to do that on Chromecast with Google TV HD (Kodi tried, but it was extremely choppy).

Since this could occure on another devices as well, simple toggle in settings would be nice if there is no server-app handshare.

**Comment by avionics75** [comment]
It would be nice if the AndroidTV client could request a transcode from the server based on the actual resolution of display if it is not matching the video file resolution :)

**Comment by V4G4X** [comment]
I am having the exact same issue with my FireStick(non-4K).  
I have two queries related to the issue above. Please point me in the right direction/documentation if it exists.

1. Does transcoding only involve changing the audio/video codecs? And not downscaling the resolution? 
2. Is there any way to get playback info on the androidTV(Firestick) app?

**Comment by MichaelRUSF** [comment]
@avionics75 Can you try out the debug build and let me know if it's working? You'll need to download the artifact [here](https://github.com/jellyfin/jellyfin-androidtv/actions/runs/10640689852), unzip, and sideload the apk on your device.

**Comment by avionics75** [comment]
I haven’t had the opportunity to check yet as the device is used by a person located 9000km away from me, but i'll do my best as soon as possible.

On another websites like Geekbench or on the play store list, the device is designed by code name "MiTV-AESP0", I don't know if it makes a difference ...

**Comment by avionics75** [comment]
Hey, I've tested with your debug build and it seems to do the trick for most of the 4K content on my server, and the dashboard reporting that the media is transcoded because the resolution was not supported and and the codec video level was not supported either :)

Another weird issue but I don't know if this is related, the transcoding of 4K files doesn't happen at 100%. I mean that for some 4K content, the jellyfin android TV player hangs and after some time results in a  player error. I can see on on the server that the dashboard (10.9.10) reports that the file is completelly compatible and the the viewing time is increasing while nothing is played on the client.

**Comment by MetaImi** [comment]
I have the same issue with Apple Tv HD. Actually it is the 4th gen from 2016 with an iPhone 6 hardware. It is not powerful enough for 4k but I can’t force transcoding.

**Comment by Martiinii** [comment]
Hey! I have same issue with Xiaomi TV (not stick) that is 1080p only - the content isn't transcoded. I've tested it on few devices and it's properly transcoded on devices that don't support 4K. An option to select maximum resolution would be such a great addition (it already exists in web client under `Playback -> Maximum Allowed Video Transcoding Resolution`)
