### ISSUE TITLE
Next and previous buttons doesn't work

### ISSUE THREAD

**Issue by user112200** [jellyfin/jellyfin-androidtv#2521]
### Describe the bug

As title says next, prev buttons doesn't working on current version.

### Application version

0.15.3

### Where did you install the app from?

None

### Device information

Nvidia Shield pro 2017 and pro 2019

### Android version

Android 9.1

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
Please provide more detail so we can look into this issue. For me those buttons work fine.

**Comment by user112200** [comment]
Shield(2017 and 2019) plugged to LG Oled TV and tested on with both TV remote(LG magic remote via CEC) and shield remote. On the shield remote fast-forward and rewind buttons remapped to next, prev with "Button Remapper" app. Tv remote has next, prev buttons.

Everything works on plex but not on jellyfin. Nothing happens on screen as if no buttons were pressed.

Which logs should I upload here? Does TV app has a log file?

**Comment by gasimons** [comment]
Having same issue.  Remotely controlling music playing on app on Fire TV from PC  browser.
