### ISSUE TITLE
Add continue watching section to individual libraries suggestions view

### ISSUE THREAD

**Issue by d8f6** [jellyfin/jellyfin-androidtv#2527]
### Describe the bug

The "Continue Watching" section should be available when going into any library and enabling the option "Enable smart screen". Otherwise, when the bug https://github.com/jellyfin/jellyfin-androidtv/issues/2077 gets fixed a new bug will be introduced (you will not be able to continue watching a show in a library that is hidden from the main screen). 

### Application version

0.15.3

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield 2015

### Android version

LineageOS for microG [foster]

### Jellyfin server version

10.8.9

**Comment by almightiest** [comment]
I think I saw this as an enhancement request already. Did you search? Doesn't seem like a bug yet.

**Comment by nielsvanvelzen** [comment]
This is added in #2361 and will be available in the next big release (0.16).

**Comment by vortex91** [comment]
Display in home screen sections such as 'Latest Media' and 'Continue Watching optoin currnetly does not get adhered on home screen for android tv but does so on web/ios/android.  will this resolve this issue as well?
