### ISSUE TITLE
Respect subtitle selection settings, such as "Only forced," "Smart," etc.

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-androidtv#253]
We already have this set in web, and this syncs across devices, maybe we should sync to Android TV too, or make a specific client-side option for Android TV? /shrug

**Comment by nielsvanvelzen** [comment]
Although this option cannot be changed from the client, it should now (in 0.18) be respected as we always use the default subtitle track received from the server.
