### ISSUE TITLE
User configurable way to change over lay timeout

### ISSUE THREAD

**Issue by d8f6** [jellyfin/jellyfin-androidtv#2530]
### Describe the feature you'd like

Currently when playing a video the bottom overlay dissapears at three seconds and the bottom overlay at six seconds. I would like them to both be three seconds or have a way to change this behavior myself.

Edit: I am unsure of whether this is or should be considered a bug, or if this is the intended behavior.

**Comment by BotBlake** [comment]
Hi there.
could you add some additional information to this?
I am unsure wether this issue is still up to date or can be closed.

Kind regards.

**Comment by d8f6** [comment]
@BotBlake You can close any open issues I have here as I use version 0.16.6 of this app (I don't like transcoding everything and need libvlc to accomplish this).
