### ISSUE TITLE
Cannot fast forward while paused

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [jellyfin/jellyfin-androidtv#254]

**Comment by nielsvanvelzen** [comment]
Hi there! We've recently released a new version of Jellyfin and we think this issue is solved. Can you try it with the new version?

**Comment by ThatNerdyPikachu** [comment]
I will try this later today, thank you.

**Comment by pikanewghacc** [comment]
@nielsvanvelzen This has not been fixed in v0.11.1.

**Comment by nielsvanvelzen** [comment]
Thanks for checking, we will look into it

**Comment by ThatNerdyPikachu** [comment]
Will re-open if I experience this again, haven't tested much lately.
