### ISSUE TITLE
Theme background not applying

### ISSUE THREAD

**Issue by ericbeier** [jellyfin/jellyfin-androidtv#2541]
### Describe the bug

1. Go to Settings --> Customization --> App theme --> Classic Emerald.
2. Close and restart the app.
3. Background "moviebg.jpg" does not apply. Instead the background is black.

### Application version

0.15.3

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield Tv Pro (2021)

### Android version

Android 11

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
Thanks for the report, it should be fixed with #2542 and #2543 but I'm not sure if I can backport the fixes to 0.15.z.
