### ISSUE TITLE
Jellyfin Android TV in MI Box

### ISSUE THREAD

**Issue by servimo** [jellyfin/jellyfin-androidtv#2555]
### Describe the bug

I can't ear no sound when Jellyfin TV is playing this song and see no errors message.
If I install jellyfin not the TV apk it play and I can listen, but is not easy to manage the apk, because I need mouse to use it.
I can't found logs in the Android TV about the problem.
I think Its not only this song, but any flac files. I used this file as an example.
Jellyfin apk in my MI phone plays too. It plays in VLC and foobar2000 in Android.

### Logs

jellyfin está reproduzindo Keith Jarrett - Part I em Xiaomi MiBOX4C
hoje às 11:31
jellyfin está online em Xiaomi MiBOX4C
hoje às 11:30
Endereço IP: 192.168.0.4

### FFmpeg logs

Dont know wherer to find these logs

### Media info of the file

```shell
ECM) [24-48]/01 - Part I.flac
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
File size                                : 129 MiB
Duration                                 : 14 min 28 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 1 250 kb/s
Album                                    : Budapest Concert
Album/Performer                          : Keith Jarrett / Keith Jarrett
Track name                               : Part I
Track name/Position                      : 01
Track name/Total                         : 14
Performer                                : Keith Jarrett
Genre                                    : Jazz
Recorded date                            : 2020

Audio
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Duration                                 : 14 min 28 s
Bit rate mode                            : Variable
Bit rate                                 : 1 250 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Bit depth                                : 24 bits
Compression mode                         : Lossless
Stream size                              : 129 MiB (100%)
Writing library                          : libFLAC 1.3.2 (UTC 2017-01-01)
MD5 of the unencoded content             : 1320F9392212502957B9B92B2EE1BA21
```

### Application version

0.15.4 (latest)

### Device information

Xiaomi MiBOX4C

### Android version

Android Version Marshmallow (6.0.1)

### Jellyfin server version

10.8.9-1

**Comment by servimo** [comment]
Thanks! 
With Jellyfin for Android TV 0.15.8 I can confirm FLAC files now are working. I can hear the sound.

**Comment by nielsvanvelzen** [comment]
Good to hear!
