### ISSUE TITLE
Search - no turning back to other results

### ISSUE THREAD

**Issue by chr-zz** [jellyfin/jellyfin-androidtv#2561]
### Describe the bug

Hi,
since the new 0.15.4 version it is no longer possible to search something and return to other search results.
You are forced to enter a search term again. Tested on my 2 devices.
In version 0.15.3 the search went without any problems.

greetz

### Application version

0.15.4

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireTV Stick 4k & FireTV Stick 4k MAX

### Android version

Android 7.1 - 6.2.9.5  /  Android 9 - 7.6.2.4

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
I'm quite sure this issue also happened in 0.15.3. Anyway, it should be fixed in the next release. Thanks for the report!

**Comment by chr-zz** [comment]
in 0.15.3 I'm actually very sure..
it may be that the search results were not displayed in categories as they are now.
but i found my films and series and was able to navigate back.

anyway, thanks for fixing.
