### ISSUE TITLE
Player overlay discussion

### ISSUE THREAD

**Issue by Florianisme** [jellyfin/jellyfin-androidtv#257]
Moving to an issue to keep the PR #251 clean.

**Comment by Florianisme** [comment]
> Is there no button to switch to the next channel? Also, that three dot button doesn't seem to look that nice, isn't the material icon different than that?

_Originally posted by @dkanada in https://github.com/jellyfin/jellyfin-androidtv/pull/251#issuecomment-571118439_

No there is no button for that (yet).
Regarding the channel quick switcher button, I havent found a better icon but if you've got one let me know.

**Comment by dkanada** [comment]
How about [this](https://material.io/resources/icons/?icon=more_horiz&style=baseline) one?

**Comment by dkanada** [comment]
I also think the three dot button should probably be at the end if it just pulls up a menu.

**Comment by Florianisme** [comment]
No, it's not that type of a menu (like the menus on an Android phone when you click the three dot button in an app)
It's more like a pop up at the bottom, I'll post a screenshot when I get home.

**Comment by Florianisme** [comment]
This is what it looks like (ignore the small text overlap, that might've been there before)
![Screenshot_1578330475](https://user-images.githubusercontent.com/7106869/71835056-f8840380-30b0-11ea-8b66-bf2c2fac4780.png)
I've set up "Bloomberg" as an example on the right, it shows the stations name and current program

**Comment by Ullmie02** [comment]
I think adding the Logo of the current movie/tv series would look great

**Comment by Florianisme** [comment]
I think so aswell but @nielsvanvelzen was against it. I dont know, maybe we can have a poll or something :smile:.
Or the team members decide about it

**Comment by nielsvanvelzen** [comment]
**More customization preferences!!**

I find the poster annoying if it's as big as the current player. I do like the logo (top-right).

**Comment by Ullmie02** [comment]
I thought of top left because the clock is at the top right

**Comment by AndreasGB** [comment]
I would also prefer a customizable approach, the clock and user display should be optional as well imo

**Comment by thornbill** [comment]
Personally I don’t mind having the logo (it adds something visually I think), but I agree that in the current layout it was too large.

**Comment by Florianisme** [comment]
This is what it looks like in the new layout.. Its even bigger


![Screenshot_1578340136](https://user-images.githubusercontent.com/7106869/71844251-0d1ec680-30c6-11ea-9776-b0051169d3c2.png)

**Comment by nielsvanvelzen** [comment]
The current layout looks like this, I added very nicely made captions to clarify which image is the logo and which is the poster.

![image](https://user-images.githubusercontent.com/2305178/71844901-79e69080-30c7-11ea-934c-4784e9be872f.png)

The logo is not really a problem, it's in a location where subtitles normally wouldn't show and logos have transparent backgrounds.
The poster doesn't have a transparent background, is on the bottom of the screen (where subtitles with long lines could show) and is quite large.

In your latest screenshot it looks way too large for me. In my opinion the controls should assist while watching instead of obstructing the whole video.

**Comment by Florianisme** [comment]
Solid point! Yes I got confused with the logo and the poster. So my suggestion is that I'll remove the poster and the long description again and instead just add the logo.

**Comment by dkanada** [comment]
Aww I liked the new poster and description! Oh well, it's a huge improvement regardless.

**Comment by Florianisme** [comment]
This discussion screams for a lot more customization options
They'll go into another PR though
