### ISSUE TITLE
Delete

### ISSUE THREAD

**Issue by jmarco068** [jellyfin/jellyfin-androidtv#2574]
### Describe the feature you'd like

I really need the movie deletion function!

**Comment by jmarco068** [comment]
But other clients have this feature... I would be very grateful if you add. Thanks.

**Comment by nielsvanvelzen** [comment]
https://github.com/jellyfin/jellyfin-androidtv/discussions/2368

**Comment by jmarco068** [comment]
I understand everything. You're doing a good job. Thank you!
