### ISSUE TITLE
Cannot change external player once set

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#258]
This was reported via Reddit, the current implementation of opening videos in an external player does not allow for the selected app to be changed once set.

We should do one of the following:
1. Save the external player app as a Jellyfin app preference
2. Always prompt which app should be used

https://www.reddit.com/r/jellyfin/comments/cosuvl/jellyfin_androidtv_app_shield_how_to_change/

**Comment by smoothliquidation** [comment]
Is this still an issue, or is there a workaround?  I want to change the player on my setup and found this issue via Google.

**Comment by nielsvanvelzen** [comment]
Try opening your system settings -> apps -> select the default video app (e.g. VLC) -> "clear defaults". The next time you try to open an external player _should_ give you the option to chose it again.

**Comment by nielsvanvelzen** [comment]
In Android the default apps can be changed in the settings, this is not something we should deal with in-app.

**Comment by thornbill** [comment]
@nielsvanvelzen those settings are not available in Fire OS

**Comment by nielsvanvelzen** [comment]
In Fire OS from the launcher go to the gear icon (settings) then open "applications". Go to "manage installed applications" and find the current default video app. Use the "clear defaults" button and now the next time you try to open an external player it will ask again.

**Comment by superboo07** [comment]
it doesn't even ask me to set it to anything when I enable external players. 10/10
