### ISSUE TITLE
Grouped tv library not displaying all unwatched items

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#2584]
### Describe the bug

Have two tv library folders and merge them to group content automatically. Then view your library (default view) and toggle the filter to unplayed. Only 25 items will show up even though there are more than 25 unplayed items in the library.

If the libraries are ungrouped all works as expected. 

### Application version

0.15.4

### Where did you install the app from?

Google Play

### Device information

Sony Bravia 4k VH2

### Android version

Android TV OS 10

### Jellyfin server version

10.8.9

**Comment by yacoob** [comment]
This is still happening in 0.15.12 with server version 10.8.10. Confusingly enough, if you jump to a letter of alphabet that has >25 entries, they'll all be shown, and the selection counter in the bottom-right corner will show nonsensical position like `36/25`.

**Comment by nielsvanvelzen** [comment]
Is this issue reproducible with the web client? I don't see anything obviously wrong with the code and believe the issue is within the server.

**Comment by yacoob** [comment]
No, no other client seems to have this problem. It's only the android TV one here.

**Comment by MichaelRUSF** [comment]
Looks like this [issue](https://github.com/jellyfin/jellyfin/issues/8069) on the server might be related.

**Comment by X-static** [comment]
Same issue here. Have two movie libraries combined with at least 200 entries. On the Android tv/fire tv app only shows up to 35.

I'm running latest server and app versions.

**Comment by nielsvanvelzen** [comment]
[I've re-opened the server issue.](https://github.com/jellyfin/jellyfin/issues/10384#issuecomment-1946366417) Closing this one in favor of that one.
