### ISSUE TITLE
SSL Handshake fails on FireTV /Fire OS

### ISSUE THREAD

**Issue by Scorpionhunt** [jellyfin/jellyfin-androidtv#2588]
### Describe the bug

I encounter the problem that I can not connect to my Jellyfin server on the FireTV App. It displays the error message: https://jellyfin.mydomain.com SSL Handshake failed.

My setup: I have a Jellyfin server running on TrueNas Scale using the true-charts app and traefik with Let's Encrypt certificates. The FireTV Stick is on the same network as the server. 
Through the built-in web browser (FireTV OS), I can access the server via my domain without any problems.
Through Chrome and Firefox, as well as through Safari (on Windows and IOS), I can access the server too. 
Thus it seems that the only problem occurs with the FireTV App and has nothing to do with my server setup. Therefore I emptied the cash and completely reinstalled the Jellyfin App for FireTV, but I still face the same problem.

Thanks in advance for your help.

### Application version

0.15.4

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire TV Stick 4K Max

### Android version

FireOS 7.6.1.4 (25938402180)

### Jellyfin server version

10.8.9

**Comment by Scorpionhunt** [comment]
I made some further investigation and hope the information helps to narrow down the issue:

Firstly, I set up a new Jellyfin server instance on Truenas Scale using the True-Charts app, but this time without traefik, thus exposing port 8096. Using the local IP-Adress 192.168.x.x:8096 on the FireTV app works fine. 

Additionally, I tried using different kinds of Let's Encrypt certificates (always production environment), varying between ECC and RSA and different key lengths, but that doesn´t solve the issue. I checked each certificate with SSL-Labs, and all handshakes succeeded except for:

Chrome 69 / Win 7  R	Server sent fatal alert: handshake_failure
Firefox 62 / Win 7  	R	Server sent fatal alert: handshake_failure
OpenSSL 1.1.0k  	R	Server sent fatal alert: handshake_failure

Also SSL-Labs says that those certificates work only in browsers with SNI support. Solely TLS 1.3, but not TLS 1.2 is supported.

Furthermore, I tried using Firefox for FireTV (not supported) and the implemented Amazon Silk browser, and both worked completely fine.

I hope the provided information can help to narrow down the issue. Thank you very much for your effort and your help.

**Comment by nielsvanvelzen** [comment]
TLS 1.3 is only supported in Android 10 and newer. Fire OS 7 is based on Android 9.

**Comment by Scorpionhunt** [comment]
Thank you very much. 
I think that is the solution. Does that mean I have to wait until Amazon pushes an update for FireOS 8 on FireTV since this version is based on Android 11, which has, as you said, TLS 1.3 support?
Since this issue isn't related to Jellyfin then, but to Amazon, the report can be closed, right?
Again thank you very much!

**Comment by nielsvanvelzen** [comment]
I'd recommend enabling TLS 1.2 instead, you never know how long it will take Amazon to push an OS update. The issue can indeed be closed since we can't do anything about this issue in the app.

**Comment by wiffleman** [comment]
I'm actually facing the exact same issue. Interestingly enough, this is a new change for me - I was previously able to access my Jellyfin server using my domain name through the Fire TV app probably 4-5 months ago.

Has anything with respect to access / TLS etc changed with recent versions of Jellyfin?
