### ISSUE TITLE
Progress is not reported when playing a transcoded stream with libvlc 

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#259]
As noted [here](https://github.com/jellyfin/jellyfin-androidtv/pull/249#issuecomment-571881616), there are some issues with playback progress not being reported when a stream is transcoded and played with libvlc.

* Position reporting not updated
* Seek bar does not update on skipping

I suspect both of these are caused by the same root issue.

**Comment by Artiume** [comment]
Is this the issue you were talking about that my PR might fix?
