### ISSUE TITLE
Set the default video player option to "Automatically Choose" instead of Exoplayer.

### ISSUE THREAD

**Issue by IAmV0id** [jellyfin/jellyfin-androidtv#2597]
### Describe the feature you'd like

Right now, when you download the AndroidTV app, it comes with Exoplayer as the default video player. But this can be a problem when trying to play some media files, since they only work with LibVLC.

Having the default be "Automatically Choose" will be beneficial to less tech literate users, as they would likely not be aware of the video player setting or what it even does.

As far as I'm aware, the default did use to be automatic, but I'm pretty sure something changed in an update so Exoplayer is the default now.

**Comment by nielsvanvelzen** [comment]
We changed the default to ExoPlayer because the automatic detection did not work properly. We also don't encourage using the LibVLC implementation due to it's many bugs often causing crashes. So no, we won't be changing the default for now.
