### ISSUE TITLE
I cant compile 

### ISSUE THREAD

**Issue by Astate** [jellyfin/jellyfin-androidtv#26]
With my version of Android-Studio (3.2.1) i can't build APK. 
what version of Gradle is use ?

Configuration 'amazonCompile' is obsolete and has been replaced with 'amazonImplementation' and 'amazonApi'.
Configuration 'googleCompile' is obsolete and has been replaced with 'googleImplementation' and 'googleApi'.
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018.

**Comment by thornbill** [comment]
It looks like I am using Gradle 2.10 to build the app.

**Comment by Astate** [comment]
Gradle 2.10 = Dec 21, 2015 very old
Gradle 4.10.3 = Dec 05, 2018

I want to know how to build this app, because i want to play with this app code.

**Comment by Astate** [comment]
To use source with recent version of Android-Studio i need to modify :

I need to change gradle 2.10 to 3.3.0 in build.gradle of project: jellyfin-androidtv
`classpath 'com.android.tools.build:gradle:3.3.0'`

I need to change word 'compile' to 'implementation' and change buildToolsVersion in build.gradle Module: app
```
buildToolsVersion "28.0.3" 
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    amazonImplementation project(':exomedia-amazon')
    googleImplementation 'com.devbrackets.android:exomedia:2.5.6'
    implementation 'com.android.support:recyclerview-v7:23.1.1'
    implementation 'com.android.support:leanback-v17:23.1.1'
    implementation 'com.android.support:appcompat-v7:23.1.1'
    implementation 'com.mcxiaoke.volley:library:1.0.19'
    implementation 'com.squareup.picasso:picasso:2.3.2'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.google.code.gson:gson:2.5'
    implementation 'com.squareup.okhttp:okhttp:2.7.0'
    implementation 'com.squareup.okhttp:okhttp-urlconnection:2.7.0'
    implementation 'com.google.guava:guava:18.0'
    implementation 'com.flaviofaria:kenburnsview:1.0.6'
```

**Comment by krodelabestiole** [comment]
thanks a lot for these directives !

here is a very unofficial build for who might be interested :
[https://xunga.org/jellyfin-androidtv.apk](https://xunga.org/jellyfin-androidtv.apk)

**Comment by fagervan** [comment]
Can you help me?. I install android studio, clone the jellyfin-androidtv from github. What is the configuration of the project?
Android Gradle Plugin Version: xxxx
Gradle Version: xxxx
regards

**Comment by anthonylavado** [comment]
@fagervan Before going further, is there a particular need you have to compile it?

It’s not the easiest to install until we get it on the stores, but we have pre-compiled versions available on our Binary Repository. More info here:

https://jellyfin.readthedocs.io/en/latest/clients/#android

**Comment by fagervan** [comment]
> @fagervan Before going further, is there a particular need you have to compile it?
> 
> It’s not the easiest to install until we get it on the stores, but we have pre-compiled versions available on our Binary Repository. More info here:
> 
> https://jellyfin.readthedocs.io/en/latest/clients/#android

Thank you. it is only for learning.
Before I was a developer in other languages, but never for android. Greetings.

**Comment by thornbill** [comment]
The easiest way to build the app is probably to install Android Studio and run the build gradle task.

Alternatively, you could use the gradle wrapper script in the project root (`gradlew` or `gradlew.bat` depending on your operating system) and run `gradlew build`.

**Comment by fagervan** [comment]
> The easiest way to build the app is probably to install Android Studio and run the build gradle task.
> 
> Alternatively, you could use the gradle wrapper script in the project root (`gradlew` or `gradlew.bat` depending on your operating system) and run `gradlew build`.

Thank you. now if it works "gradlew.bat build bundleGoogle"
In addition to android_studio, I had to install oracle java8jdk. regards
