### ISSUE TITLE
Video transcodes with VobSub and PGS subtitles

### ISSUE THREAD

**Issue by branches78** [jellyfin/jellyfin-androidtv#2614]
### Describe the bug

VobSub and PGS subtitles are not playing directly, that is, video is transcoding without audio, logs are attached.

[log_20230322.log](https://github.com/jellyfin/jellyfin-androidtv/files/11045314/log_20230322.log)

[VobSub.log](https://github.com/jellyfin/jellyfin-androidtv/files/11045315/VobSub.log)

[PGS.log](https://github.com/jellyfin/jellyfin-androidtv/files/11045316/PGS.log)

### Application version

0.15.5

### Device information

Homatics Box R 4K Plus and Realme 4K Stick

### Android version

Both on Android 11, security patches november 2022 and january 2023

### Jellyfin server version

10.8.9

**Comment by branches78** [comment]
You should have not closed this ticket until I was able to test and report, although PGS subtitles now play directly without transcoding, I am getting playback errors when trying to play videos with VobSub subtitles, please check the attached log.

[VobSub.log.log](https://github.com/jellyfin/jellyfin-androidtv/files/11305568/VobSub.log.log)

Please reopen this ticket.

**Comment by nielsvanvelzen** [comment]
We did not add support for VobSub which is a different format from PGS, please open a separate issue for that.

**Comment by branches78** [comment]
> please open a separate issue for that.

Thank you for the clarification, I will open a new one at https://features.jellyfin.org/.

**Comment by branches78** [comment]
I just created one:

https://features.jellyfin.org/posts/2151/please-add-support-for-vobsub-subtitles
