### ISSUE TITLE
Cast/remotecontrol from mobile or webapp is not working

### ISSUE THREAD

**Issue by Nickbert7** [jellyfin/jellyfin-androidtv#262]
Currently it is not possible to cast to or remotecontrol the ATV client from the webinterface.

As fas as I know this happes via a websocket conenction.
Could the issue be located at the java api client where still the "old" path is used?

https://github.com/jellyfin/jellyfin-apiclient-java/blob/77ff4ee588b5b269ac40d0d5bc1231aa283516b9/library/src/main/java/org/jellyfin/apiclient/interaction/websocket/ApiWebSocket.java#L61

**Comment by thornbill** [comment]
That doesn’t _seem_ to be the issue. I have looked into this previously and the websocket connection does seem to be failing for some reason, but updating the url did not fix it in my testing.

**Comment by thornbill** [comment]
This should be fixed by https://github.com/jellyfin/jellyfin-apiclient-java/pull/39

**Comment by nielsvanvelzen** [comment]
I can confirm this is fixed
