### ISSUE TITLE
A Better Homescreen & Overall UI

### ISSUE THREAD

**Issue by iDoNtCaRe-69** [jellyfin/jellyfin-androidtv#2620]
### Describe the feature you'd like

Let's Start With Homescreen. We All Love How Netflix, Prime Video, Disney+ Hotstar Looks. A Big Fat Banner At Top & Everything Else Is Divided By Category. Maybe By Country, Language, Folder, Genre, Etc. I'm Not Saying Straight Up Copying How They Look, But Big Icons Are Necessary In Smart TVs. Plex Looks Quite Good In This Statement, Right?

That Part Also Covers Recommendation. But Again It's Self-Hosted So That Doesn't Matter Most. Not Gonna Lie, Jellyfin Is A Fantastic Project & Thanks To LibVLC Most Contents Are Playable. But That Android KitKat Era UI Breaks The Mood.

UI Inside Folders Is Actually Pretty With That Smart TV Thingy On. But Big Fat Banner + Baby Looking Stuff Looks Cute & Lovely. I'm Not Hopping To Happen This Kind Of Big UI Overhaul Anytime Soon. But A Slower Pace Will Just Make Most Of Us Switch To Other Streaming Services. 

I Hope This Helps & Btw This Might Be The Most Requested Feature. Like Everyone From Telegram Group Begging For This. Playback Issue Can Still Be Fixed By Simply Using A Different External Video Player. But UI Man, Anyway Thanks For Making Such A Wonderful Project. God Bless You!

**Comment by thornbill** [comment]
There is an existing feature request for ui improvements here: https://features.jellyfin.org/posts/906/updating-app-ui
