### ISSUE TITLE
The font size of the embedded subtitles in the video is too large.

### ISSUE THREAD

**Issue by baburam0007** [jellyfin/jellyfin-androidtv#2623]
### Describe the bug

The font size of the embedded subtitles in the video is too large.

### Application version

0.15.5

### Where did you install the app from?

Google Play

### Device information

Sony Android TV

### Android version

Android 9

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
Depending on the subtitle format you can change the font size in the app settings.
