### ISSUE TITLE
Unable to disable subtitles

### ISSUE THREAD

**Issue by UnDifferential** [jellyfin/jellyfin-androidtv#2631]
### Describe the bug

To Reproduce

1. Play any video with subtitles
2. Disable subtitle by choosing None option in menu (now subtitle disappears)
3. Wait till menu disappears, forward video by right button
4. Subtitles displays

Expected behavior
Subtitles should be disabled

Issue does not occur with LibVLC

This bug can be closed if  #724 is reopened.

### Application version

0.15.5 and all previous versions tested

### Device information

Nvidia Shield, Sony TV

### Android version

All

### Jellyfin server version

10.8.9 and all previous versions tested

**Comment by ashooner** [comment]
On FireTV v0.15.5, this bug goes away if the player is switched to libVLC (experimental), although that gave me a probably unrelated audio sync issue.

**Comment by Darkhost1999** [comment]
On TCL Model 50S434
TV+ OS v5.2.0 (no system updates available)
Jellyfin app version 0.15.6 release.
I can attest to a quick change to libvlc allowed me to disable subtitles. But, here's the thing it restarted my video AND when re-enabling the subtitles it says "burning in. Give us a minute" (or something similar) then the issue persists.
Libvlc does not resolve the issue for me. It just initially covered it up. It wouldn't be a concern of mine if subtitles respected auto crop.

**Comment by Darkhost1999** [comment]
Seems like it's intentional.
Every single movie I've dumped and enabled the English - DVDSUB needs redumped and to ONLY use the English - SUBRIP.
Using DVDSUB says Burning in give it a second. And you can't disable burned subtitles. They are burned into your video.

Please someone prove me wrong and suggest otherwise.
