### ISSUE TITLE
Smart screen issue

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#2645]
### Describe the bug

I have enabled smart screen view for my movies library, which works as expected. However, I can not go back to the default grid view by unselecting the option in the customize menu. I've uninstalled and reinstalled Jellyfin, but the movie library still opens up in the smart  screen view.  

Logs attached:
[Smart Sceen logcat.txt](https://github.com/jellyfin/jellyfin-androidtv/files/11162217/Smart.Sceen.logcat.txt)

### Application version

0.15.6 debug

### Where did you install the app from?

Sideloaded APK

### Device information

Sony Bravia 4k VH2

### Android version

Android TV OS 10

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
I've tried to reproduce but am unable to. When I enable the smart-screen and then open the library again from the home screen is shows as expected (just like you said). However, when doing the opposite (disabling the option) it will open the grid view directly again. Can you explain step by step which actions you take so I can try it again?

**Comment by MichaelRUSF** [comment]
I just figured out what was causing the issue. On my server, I have several movie library folders grouped together. Once I ungrouped the folders I was able to view the movies in grid view on the client, and the enable smart screen turns on and off as expected. 

If I group at least two movie folders then the client automatically shows the smart screen view (that’s why it was persisting after uninstalling and reinstalling), and the option cannot be disabled.

**Comment by nielsvanvelzen** [comment]
What do you mean by grouping multiple folders together?

**Comment by MichaelRUSF** [comment]
I have several library folders based on categories, e.g., family movies, Christmas movies, etc. On the server side, you can group folders together so they show up as one library: ‘Movies’, ‘Music’, or ‘Tv’.  This option is in the 'Home' menu in settings on the server.  

![Folders](https://user-images.githubusercontent.com/78215956/230618259-2903619c-ddb9-46af-b966-400d9f509660.png)

**Comment by ShaunFavell** [comment]
I am experiencing the same in JF on android (firestick) when viewing photos.

I placed it in smart screen mode to look, but it wont go back to grid view.

**Comment by smileBeda** [comment]
1. select smart screen
2. reopen library
3. settings cog is gone 
4. only by selecting „all items“ you can bring back the settings cog and then unselect smart screen 

What’s the opposite of „smart“? 
😆
