### ISSUE TITLE
The client cannot  switch audio track

### ISSUE THREAD

**Issue by ylu19870105** [jellyfin/jellyfin-androidtv#2648]
### Describe the bug

The client cannot  switch audio track when the mkv media has two or more audio tracks.
infuse and kodi (with  jellycon)  can switch audio tracks normally.

### Application version

0.15.0

### Where did you install the app from?

None

### Device information

Fire TV

### Android version

Andriod 9

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
Please use our media playback issue template and provide the requested details.

**Comment by ylu19870105** [comment]
> Please use our media playback issue template and provide the requested details.

**Comment by ylu19870105** [comment]
> Please use our media playback issue template and provide the requested details.

I have no idea about how to copy/view the log from andriod device.I just hope the app can replace kodi or infuse!

**Comment by Darkhost1999** [comment]
It's ok. Someone posted this issue
https://github.com/jellyfin/jellyfin-androidtv/issues/2655

You can subscribe to it and get notifications for it.

**Comment by ylu19870105** [comment]
> It's ok. Someone posted this issue #2655
> 
> You can subscribe to it and get notifications for it.

OK! I can close issue now.
