### ISSUE TITLE
Display in home screen sections such as 'Latest Media' and 'Continue Watching optoin does not adhere in android tv

### ISSUE THREAD

**Issue by vortex91** [jellyfin/jellyfin-androidtv#2677]
### Describe the bug

have media in library1 folder and also movie folder (hardlink or softlink or dupe)

1. go to settings in webui
2. click on home
3.  for each library there is optoin Display in home screen sections such as 'Latest Media' and 'Continue Watching' choose a specific library such as "library1" and uncheck the box.
4. click on save.

for webui/ios/android on home screen this library will be excluded for continue watching and latest media. 
for android TV you will get duplicate entries for media if media exists in library1 forlder and some other folder.

### Application version

0.15.6

### Where did you install the app from?

Amazon Appstore

### Device information

firestick 4k and regular firestick v1

### Android version

fire os 

### Jellyfin server version

10.8.9

**Comment by vortex91** [comment]
this might fix it but im not very good with the code yet.

override fun addToRowsAdapter(context: Context, cardPresenter: CardPresenter, rowsAdapter: MutableObjectAdapter<Row>) {
    // Get configuration (to find excluded items and unchecked folders)
    val configuration = userRepository.currentUser.value?.configuration

    // Create a list of views to include, excluding unchecked folders
    val latestItemsExcludes = configuration?.latestItemsExcludes.orEmpty().mapNotNull { it.toUUIDOrNull() }
    val views = runBlocking { userViewsRepository.views.first() }
        .filter { it.isFolder && configuration?.getFolderState(it.id)?.isChecked == true } // filter out unchecked folders
        .filterNot { it.collectionType in EXCLUDED_COLLECTION_TYPES || it.id in latestItemsExcludes }

    views.map { item ->
        // Create query and add it to a new row
        val query = LatestItemsQuery().apply {
            fields = arrayOf(
                ItemFields.PrimaryImageAspectRatio,
                ItemFields.Overview,
                ItemFields.ChildCount
            )
            imageTypeLimit = 1
            parentId = item.id.toString()
            groupItems = true
            limit = ITEM_LIMIT
        }

        val title = context.getString(R.string.lbl_latest_in, item.name)
        HomeFragmentBrowseRowDefRow(BrowseRowDef(title, query, arrayOf(ChangeTriggerType.LibraryUpdated)))
    }.forEach { row ->
        // Add row to adapter
        row.addToRowsAdapter(context, cardPresenter, rowsAdapter)
    }
}

**Comment by nielsvanvelzen** [comment]
I can't reproduce this issue. When I uncheck "Display in home screen sections such as 'Recently Added Media' and 'Continue Watching'" the items from that library won't show up in the next-up section anymore for me.

**Comment by vortex91** [comment]
bug is specific for android tv only.  it works on webui.  I can duplicate this at will on multiple devices with android TV client code base.  Android code base and webui code base are fine.

**Comment by vortex91** [comment]
maybe i was not clear.  the optoin is set in webUI and not android TV.  is android tv suppose to grab those options? or is this optoin somewhere else on android tv?

**Comment by vortex91** [comment]
This is fully reproducable with steps i mentioned above.  ALso this has been reported in past with no resolution.  My only other guess would be server side setup of what gets passed varries from 10.8.9 (what im running) vs what server your testing with.  If you like i can give you access to my server to test with.

**Comment by vortex91** [comment]
here is example side by side of webui vs android tv client
![example of bug](https://user-images.githubusercontent.com/29990624/235051443-534ef0a1-17a8-41e7-88b9-064cac58c5de.jpg)

and this is the settings.  notice movies are unchecked so they do not show up in webui but they do show up in android tv for continue watching
![settings](https://user-images.githubusercontent.com/29990624/235051674-455a089d-887f-4722-9e05-b33599859612.jpg)

**Comment by nielsvanvelzen** [comment]
Can you share all libraries you have and the complete paths for folders in them?

**Comment by vortex91** [comment]
this is from simple test setup with 1 movie library and 1 tv show library.
movies: C:\movies\ which has 1 movie. "C:\movies\Shazam! (2019) [imdbid-tt0448115] [tmdbid-287947].mp4"
tv shows:  C:\TV Shows with 1 show and 1 episode "C:\TV Shows\The Voice\Season 22\The Voice S22E14 The Knockouts, Part 2.nfo"

I disable the movies from showing up in continue watching as you can see in image above but they still do.

on my real enviroment i have Similar setup
/mnt/media/Movies for movies with 1000's of individual movie folders and movies within them
/mnt/media/TV Shows for tv shows with 100's of tv shows and sub folders for each show sub folder for each season then files
/mnt/media/Recommendations (hard links generated by script from excisting /mnt/media/Movies path) I hide this in setting not to show up in continue watching and latest but they all show up so i get dupe entries.

i have test enviroment setup so i can debug thing if you would like running android studio and android tv code.

**Comment by vortex91** [comment]
here are screen shots just in case
![library](https://user-images.githubusercontent.com/29990624/235334975-f1e2bd10-5208-485f-b11c-9213efae0875.jpg)
![movies](https://user-images.githubusercontent.com/29990624/235334988-b0de2471-4f85-42a1-acb9-ff651713b4f4.jpg)
![Tvshows](https://user-images.githubusercontent.com/29990624/235334990-8293ea6d-2286-48fa-bfff-a21bf95340df.jpg)

**Comment by nielsvanvelzen** [comment]
Thanks for the additional information. I am able to reproduce the issue now and found the bug that causes it. The fix is not that easy so I'm unsure if it will be backported to the current stable release of the app.

**Comment by vortex91** [comment]
I can confirm with my testing that issue is resolved in 15.8 for 99% of use cases for all sections. The only edge case is when Library content type on server is set to "mix of movies and shows"  this optoin expects subfolders to exist with content.  The dsplays on client GUI is subfolders first then when each subfolder selected its content.  This works as expected in all clients however on android TV client when unchecked the option to display in resume/latest/continue it still displays for "latest" in home screen (continue and next are hidden.) 

This is edge case and low priority from my point of view.  if the fix is easy then go ahead but dont waste a lot of time on it.

thank you for all your hard work.
