### ISSUE TITLE
Dolby Digital decoding to PCM fails

### ISSUE THREAD

**Issue by branches78** [jellyfin/jellyfin-androidtv#2707]
### Describe the bug

The Realme 4K stick is a Google TV device with Android 11, the device lacks a Dolby Audio license, which means, it doesn't sport a Dolby Digital nor Dolby Digital Plus decoding internally but it only supports passthrough of those codecs.

According to Aida64, the AC3 and EAC3 codecs are absent from the device.

The stick is also connected to a TV without Dolby Digital decoding on any of its HDMI ports, which means, the TV only supports PCM decoding.

The problem with Jellyfin is, it is unable to decode Dolby Digital to PCM and this leads to get an error message at the bottom of the screen stating that it was unable to play the media, too many errors is what it says in the end, however, Dolby Digital Plus gets decoded to PCM by Jellyfin on that device connected to the aforementioned TV.

The attached server log includes what I imagine is the playback error at the end of the text. There are no transcoding logs.

[Jellyfin Server Log.log](https://github.com/jellyfin/jellyfin-androidtv/files/11339284/Jellyfin.Server.Log.log)

### Application version

0.15.7

### Device information

Realme 4K Stick

### Android version

Android 11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
You can disable the AC3 and EAC3 codecs from the app settings with the "Bitstream Dolby Digital audio" option. This should make the server transcode the audio to a compatible format.

**Comment by branches78** [comment]
> You can disable the AC3 and EAC3 codecs from the app settings with the "Bitstream Dolby Digital audio" option

That option has always been grayed out, it can't be turned OFF, however, it shouldn't be necessary to turn it OFF because the idea is not to transcode the audio but to decode it, Dolby Digital Plus and Dolby TrueHD are currently getting decoded, all you have to do is to make the app to decode Dolby Digital as well.

I don't like to compare apps, but VLC, Nova Video Player and even Emby are able to decode Dolby Digital to PCM.

**Comment by branches78** [comment]
@nielsvanvelzen, I just found out that videos with Dolby Digital 2.0 play without sound, so this is definitely an issue that must be addressed, Dolby Digital 2.0 and Dolby Digital 5.1 streams should be decoded as PCM when a device without a Dolby Audio license (like mine) is connected to a TV with only PCM decoding by HDMI.

**Comment by branches78** [comment]
I see that they enabled the Dolby Digital option to be turned ON/OFF in version 0.15.8 but that is completely unnecessary and I'll explain why:

My Realme stick is connected directly to the AV receiver, which is connected directly to the TV to any of its HDMI inputs.

Realme stick ------> AV receiver -------> TV

when I want to watch something with the sound coming out the TV speakers, the AV receiver remains OFF but I enabled an option in the AV receiver to called "HDMI standby passthrough", which acts as an HDMI repeater but the EDID of the receiver is OFF, which means, the stick doesn't detect the capabilites of the receiver but only the ones in the TV.

When I want to watch something with the sound coming out of the receiver speakers, I just turn it ON, therefore, the stick detects the receiver's EDID, ignoring the TV one completely.

The thing is, everytime I want to watch something with Dolby Digital through the TV speakers, I will have to go to Jellyfin's settings and turn OFF the Dolby Digital option because the TV only has PCM decoding through its HDMI inputs, meanwhile, everytime I want to watch something with Dolby Digital through the AV receiver, I have to go again to Jellyfin's settings and turn ON the Dolby Digital option in order for the receiver to decode it.

All this is annoying, the idea is to have a "set a forget" option, where all audio codecs not supported by the sink device (in this case the TV) should be decoded **WITHOUT HAVING TO GO BACK AND FORTH** changing options, that's why I asked you to add Dolby Digital decoding (from 1.0 to 5.1) to PCM when the Dolby Digital option is ON and when the sink device doesn't support it, the same way it currently does with Dolby Digital Plus and Dolby TrueHD.

Thank you.

**Comment by branches78** [comment]
I see that they enabled the Dolby Digital option to be turned ON/OFF in version 0.15.8 but that is completely unnecessary and I'll explain why:

My Realme stick is connected directly to the AV receiver, which is connected directly to the TV to any of its HDMI inputs.

Realme stick ------> AV receiver -------> TV

when I want to watch something with the sound coming out the TV speakers, the AV receiver remains OFF but I enabled an option in the AV receiver called "HDMI standby passthrough", which acts as an HDMI repeater but the EDID of the receiver is OFF, which means, the stick doesn't detect the receiver's EDID but only the one in the TV.

When I want to watch something with the sound coming out of the receiver speakers, I just turn it ON, therefore, the stick detects the receiver's EDID, ignoring the TV one completely.

The thing is, everytime I want to watch something with Dolby Digital through the TV speakers, I will have to go to Jellyfin's settings and turn OFF the Dolby Digital option because the TV only has PCM decoding through its HDMI inputs, meanwhile, everytime I want to watch something with Dolby Digital through the AV receiver, I have to go again to Jellyfin's settings and turn ON the Dolby Digital option in order for the receiver to decode it.

All this is annoying, the idea is to have a "set a forget" option, where all audio codecs not supported by the sink device (in this case the TV) should be decoded WITHOUT HAVING TO GO BACK AND FORTH changing options, that's why I asked you to add Dolby Digital decoding (from 1.0 to 5.1) to PCM when the Dolby Digital option is ON and when the sink device doesn't support it, the same way it currently does with Dolby Digital Plus and Dolby TrueHD.

Speaking of Dolby TrueHD, they also need to add a separate option for this audio codec, that way we can choose between getting it passed through directly on supported devices, getting it transcoded to Dolby Digital or AAC on unsupported devices and getting it decoded as PCM to retain its lossless quality.

Thank you.

**Comment by branches78** [comment]
@nielsvanvelzen can you please make the app to decode it instead of transcode it?, I just realized it is transcoding Dolby Digital 2.0 or 5.1 to AAC, not good 👎

**Comment by branches78** [comment]
This is what the Dolby Digital option is currently doing:

![image](https://user-images.githubusercontent.com/87671962/235406327-d3566b87-8f80-40eb-bb31-bc41eef84185.png)

Please fix it! 🙏

**Comment by branches78** [comment]
This is what the Dolby Digital option is currently doing with a TV with only PCM decoding:

![image](https://user-images.githubusercontent.com/87671962/235406470-f793285b-badb-4d57-8b68-39cf101ea7dd.png)

Please fix it! 🙏

**Comment by branches78** [comment]
Basically, the Jellyfin app for Android TV doesn't have implemented the decoding of Dolby Digital to PCM because they either assumed that:

1) All LCD or LED televisions out there have a Dolby Digital decoding by HDMI which are not (at least not all old models)

or

2) All Android TV devices have a Dolby Audio license which takes care of the decodiing, the truth is, some scattered models don't have the license (like the Realme 4K Stick)

The only solution to this is to implement the decoding from within the app when it's been on use on a device without a Dolby Audio license.

**Comment by sosher** [comment]
Hi , I wanted to know if this issue is being addressed or not ?

**Comment by branches78** [comment]
Closing, they'll never fix this 😒
