### ISSUE TITLE
Expanded description view for show/movie/actor sometimes doesn't show top line(s)

### ISSUE THREAD

**Issue by SteveDinn** [jellyfin/jellyfin-androidtv#2708]
## Description
- Have a show/movie/actor with a description that is too big to fit into the text box on the main view for the show/movie/actor and is truncated.
- Click on the truncated description to see the full description.
- The full description is cut off such that the top line(s) are not visible and the view cannot be scrolled up to see them.

### Description for actor is truncated
![image](https://user-images.githubusercontent.com/3911507/234754482-a328561d-96fd-47db-aff6-be275e9ae112.png)

### Full description's top line(s) are not visible.
![image](https://user-images.githubusercontent.com/3911507/234754526-d6811b19-31c1-4526-b56f-3c25881ac893.png)

### Application version

0.15.7

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

12

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Thanks for the report, issue is fixed in the next patch release.
