### ISSUE TITLE
Some PGS subtitles are rendered incorrectly

### ISSUE THREAD

**Issue by Ge082** [jellyfin/jellyfin-androidtv#2725]
### Describe the bug

0.15.7 introduced the ability to direct play PGS subtitles (and thanks a lot, transcoding and burning PGS is taping a lot on the hardware)
However, there is a slight inconvenience, there is an issue rendering some PGS

Here is the result on other apps such as Plex or Kodi, the scene is the same, excluding the possibility of the subtitle track possibly being corrupted
![kodi](https://user-images.githubusercontent.com/76789478/235364876-1267a405-be4e-4450-a6b5-b3bee5189d38.png)

And now the same on Jellyfin
![JF](https://user-images.githubusercontent.com/76789478/235364890-afb44191-773e-4b90-9c5e-2e3ad710b0cc.png)

Media was direct playing, no transcoding whatsoever

### Application version

0.15.7, also applies on 0.15.8

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro (2019)

### Android version

Latest public release from Nvidia

### Jellyfin server version

10.8.10

**Comment by HayriGomer** [comment]
Have the exact same problem
