### ISSUE TITLE
Search does not cancel when typing slow

### ISSUE THREAD

**Issue by polson** [jellyfin/jellyfin-androidtv#2726]
### Describe the bug

1. Click search
2. Type a word like "Hello" slowly (ie 1 second between letters)

Observe that the search results are refreshed for every letter.  So the search results will be refreshed 5 times, even though we have fully typed out Hello.  This may not be a problem if the server is fast enough, but with a slow server the user will see the list update 5 times for each letter:

"H"
"He"
"Hel"
"Hell"
"Hello"

If the server takes a long time to respond, the user has to sit and wait for every one of these results to come back.

It would be better if the search call itself was cancelled each time a new letter is input.

This will not happen if the user types fast enough, because we are in fact debouncing input on the search box.  But if the user types slowly, this will become a problem.

I am willing to fix this myself and will put up a PR soon.

### Application version

0.15.8

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro

### Android version

Android 11

### Jellyfin server version

Any

**Comment by nielsvanvelzen** [comment]
Should be fixed in 0.16.
