### ISSUE TITLE
Empty extra "Continue Watching" section

### ISSUE THREAD

**Issue by TheHYPO35** [jellyfin/jellyfin-androidtv#2731]
### Describe the bug

My Firestick-based Jellyfin player just updated to 0.15.8 and there is now an extra heading of "Continue watching" with no content below the actual "Continue watching" which has shows.

I experimented with customizing my home screen layout, and the section under "Continue watching" is "continue listening" (I have no audio, so this section never shows up). When I change it to a different section, that section appears normally. When I change to "Continue reading" (I also don't use Jellyfin for books) the section disappears as it should.

So it appears to perhaps be an issue with "Continue listening" showing with a header of "Continue watching" and being visible even though the section is empty.

### Application version

0.15.8

### Where did you install the app from?

Amazon Appstore

### Device information

Firestick 4K Max (AFTKA)

### Android version

(unsure)

### Jellyfin server version

10.8.10

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [ ] External player (VLC, mpv, MX Player)

**Comment by nielsvanvelzen** [comment]
We've had a small bug slip into the 0.15.8 release that causes this behavior. It's already fixed in #2730 and will be released ASAP.
