### ISSUE TITLE
Remove accept-charset header

### ISSUE THREAD

**Issue by TheInverseKey** [jellyfin/jellyfin-androidtv#2732]
### Describe the bug

Certain WAFs are preventing traffic from the app due to the following header:

`accept-charset`

This header should be removed. 

[Mozilla Documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Charset)

### Logs

"data":"Restricted header detected: /accept-charset/"

### Application version

0.15

### Where did you install the app from?

Google Play

### Device information

Google TV

### Android version

Android 12

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
Where are those logs from? Which endpoint(s) give this issue? Why can't you whitelist that specific header? I don't believe this is an issue with the app / Jellyfin at all but the lack of detail doesn't help.

**Comment by nielsvanvelzen** [comment]
Closing as stale/wontfix.
