### ISSUE TITLE
{\an8} tag support for srt files

### ISSUE THREAD

**Issue by AlfredJKwack** [jellyfin/jellyfin-androidtv#2742]
### Describe the feature you'd like

Mirroring this feature request for the web player because I'm noticing this issue in the Roku app: https://github.com/jellyfin/jellyfin-web/issues/3727

tl;dr: captions that start with {\an8} should appear at the top but they are appearing at the bottom. If moving captions isn't easily doable, it would be nice to at least strip off the leading tag (and then any whitespace that was between the tag and the text).

It looks like it was fixed in https://github.com/jellyfin/jellyfin-roku/commit/1ee4ef8d12c60d599c17f8cb8227ab138177cbc8 recently if that's any inspiration.

**Comment by nielsvanvelzen** [comment]
Duplicate #1804
