### ISSUE TITLE
Subtitles have always a delay when resume a movie

### ISSUE THREAD

**Issue by lluisd** [jellyfin/jellyfin-androidtv#2752]
### Describe the bug

1. Play a movie some time or move the timeline forward.
2. Go back and Click 'Resume movie'.
3. Select a subtitle and the subtitle is shifted with a delay.
4. Click << buton only one time to go backwards and play again, subtitles now are not delayed. Sometimes this won't work and the only solution is to play from start, pause, select the subtitle, wait and then forward to the minute you want. So annoying...

### Application version

0.15.9

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon fire tv stick

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by sparky3387** [comment]
@nielsvanvelzen I have noticed this too, I did plan to investigate rewriting the whole exoplayer subtitle class as they did in Emby, but do you think this is related to existing code?

**Comment by viown** [comment]
Is there any kind of transcoding going on? I get this issue but only when the stream is transcoding.
I've noticed this issue occurring on other Jellyfin clients as well and I've confirmed that the source subtitles themselves are fine and are in sync when played in other players such as VLC or MPV.

[#8403](https://github.com/jellyfin/jellyfin/issues/8403)

**Comment by nielsvanvelzen** [comment]
I'm quite sure the syncing issues are a problem caused by our custom (but not that great) subtitle rendering. We will likely remove it with #2743, which I expect fixes the syncing issues.

**Comment by lluisd** [comment]
The problem still happens, do you  have any update? it's to annyoing, with my computer browser works as expected but when I watch on my fire stick TV is all the time shifted after some while

**Comment by nielsvanvelzen** [comment]
No I do not have any updates. The author of the linked PR did no make any change since my last message.

**Comment by jdenicola** [comment]
Device: Chromecast 4. 
Using: Official latest app from Play Store.
Server Version: 10.8.10 arm64 running on Raspberry Pi 4 from Docker repository (Using image: jellyfin/jellyfin)
I can confirm the bug. It's been happening for a couple months for me but I thought it was me.

As additional information, I tried with both transcoded and direct playback video files and both fail when clicking on "Continue from xx:xx" button on Chromecast 4 app.

**Comment by PhieF** [comment]
Always have sync issues on subs on Android TV: delay never works, and most of the time out of sync on the Android TV while it works on webUI

Device: Nexus Player
