### ISSUE TITLE
Custom Theming

### ISSUE THREAD

**Issue by Jpkribs** [jellyfin/jellyfin-androidtv#2765]
### Describe the feature you'd like

I know there are extensive UI changes happening behind the scenes so please let me know if this feature is irrelevant with those changes. 

It looks like themes are controlled based on XML files in the main/res/values/ folder. In those themes, there are color values that determine how each object color is set. I had some success creating a couple of my own themes but I was realizing it would probably make more sense to have a “Custom” theme enumeration. Once “Custom” is selected, it would use a theme_custom XML file. Those XML values would be tied to “@colors/custom_” variables that are set by the user from a color picker in the preferences > themes section. This way, instead of generating additional themes, it could be set dynamically based on user preference.

**Comment by nielsvanvelzen** [comment]
Those XML files are compiled together with the app. It's not possible to dynamically change their values. Proper theming support should be possible when the UI is migrated to use Jetpack compose.

**Comment by Jpkribs** [comment]
Ah! Gotcha, that makes sense. I'll close this out since this sounds like it's part of the greater UI changes.

Thanks for the reply!
