### ISSUE TITLE
Android TV / Incorrect PICTURE is displayed

### ISSUE THREAD

**Issue by GH0000000000** [jellyfin/jellyfin-androidtv#2767]
My Jellyfin Android TV Client ver 0.15.9 is not able to display selected picture after VIDEO playback. I try to display the picture number 32 of 66 but the Jellyfin always displays picture numer 1 (first one in the folder). The incorrect behaviour occures only after VIDEO playback. 

Usecase 1:
1. Open Jellyfin Android TV Client
2. Play some VIDEO (exoPlayer or VLC)
3. Display some PICTURE - ERR - always 1st picture in the folder is displayed

Usecase 2:
1. Open Jellyfin Android TV Client
2. Display PICTURE - selected one is displayed - OK
3. Play some VIDEO (exoPlayer or VLC)
4. Display some PICTURE - ERR - always 1st picture in the folder is displayed 
5. Exit Jellyfin Android TV Client (remove apk from memory)
6. Open Jellyfin Android TV Client
7. Display some PICTURE - selected one is displayed - OK

Please let me know what is going on, why selected PICTUREs are not displayed ?

**Comment by nielsvanvelzen** [comment]
I'm unable to reproduce this issue. When I play a video and then go to a picture library to open a picture all pictures show as expected.

**Comment by GH0000000000** [comment]
I am able to reproduce this error on my NVIDIA Shield TV. Please review this video https://www.youtube.com/watch?v=UTXTNfscvk0.

DETAIL of VIDEO
0:02 the picture in the center of screen is selected to open/view
0:03 open selected image in progress,, some artefact appears on screen (picture opened before test is on the screen a half of second)
0:04 the picture 1 is displayed instead of selected one
0:10 but still the picture in the center of screen is selected
0:11 only now is the first image selected
END

**Comment by nielsvanvelzen** [comment]
I'm still unable to reproduce the issue but have made some changes that might fix the issue. They should be available in the next version.

**Comment by GH0000000000** [comment]
Please let me know when "next version" will be available on Android TV. Still 0..15.9 version is available in my Google Play Store.

**Comment by nielsvanvelzen** [comment]
https://jellyfin.org/docs/general/faq#when-will-release-x-happen-when-will-feature-x-be-available
