### ISSUE TITLE
No 5.1 audio on chromecast

### ISSUE THREAD

**Issue by andreasc1** [jellyfin/jellyfin-androidtv#2768]
### Describe the bug

When playing videos with 5.1 audio on jellyfin app on google chromecast, the audio i get is always 2 channels. 
The same videos when played on Jellyfin app on my webos lg tv it has 5.1 audio passthrough properly.

### Application version

0.15.9

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

12

### Jellyfin server version

10.8.10

**Comment by thornbill** [comment]
The app downmixes to stereo by default on Chromecast with Google TV devices due to poor multichannel support. See https://github.com/jellyfin/jellyfin-androidtv/issues/1032

**Comment by andreasc1** [comment]
> The app downmixes to stereo by default on Chromecast with Google TV devices due to poor multichannel support. See #1032

thanks for that, i am wondering how was possible that Plex was able to passthrough and play the multichannel audio.

**Comment by andreasc1** [comment]
> You can try disabling the downmix setting. It might just work. We just don't have the ability to detect if a supported device is connected currently.

you mean the transcoding? tried it but still. i get 2.0 channels from jellyfin chromecast app and 5.1 from webos app.

**Comment by thornbill** [comment]
In the Android TV app settings there is a downmix audio option. That is the one I meant. Although it may not make a difference if you already tried disabling transcoding entirely.

**Comment by andreasc1** [comment]
> In the Android TV app settings there is a downmix audio option. That is the one I meant. Although it may not make a difference if you already tried disabling transcoding entirely.

thanks, that was it. although I had transoding disabled, disabled downmix from the settings solved the issue. now I get all 5.1 channels from GCCwGTV
