### ISSUE TITLE
Framerate matching not working FireTV

### ISSUE THREAD

**Issue by Staticznld** [jellyfin/jellyfin-androidtv#2769]
### Describe the bug

When playin a 4k file on my FireTV 4k max, with an 1080p monitor connected, frame rate matching is not working stays at 60fps.
When playing a 1080p file frame rate matching worked as it should.
In Kodi 20 a 4k file switches to the correct frame rate on my 1080p display. (just for the info)

### Application version

0.15.9

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon FireTV 4k max

### Android version

FireOS9 / Android 9

### Jellyfin server version

10.8.10

**Comment by nutzer145** [comment]
Still experiencing exact same bug.

Jellyfin Android TV 0.16.4 on fire TV Stick 4k
