### ISSUE TITLE
Message from server displays for a very short time

### ISSUE THREAD

**Issue by ChilledSlim** [jellyfin/jellyfin-androidtv#2782]
### Describe the bug

1. Send a message from the Jellyfin WebUI dashboard
2. View the message on the TV

the message displays for only a couple of seconds and disappears. It should display for a longer period of time, such as 20-30 seconds or based on a formula on the number of characters in the message to extend further for longer messages and maybe 15-20 seconds for short messages. 

### Application version

0.15.9

### Where did you install the app from?

Amazon Appstore

### Device information

Fire stick 4k

### Android version

Fire OS 7

### Jellyfin server version

10.8.10

**Comment by Killface1980** [comment]
Same here. In case of longer texts, they are almost impossible to read.

**Comment by daBernd** [comment]
Same here. I would like to have some configuration option to set a value for the duration, and maybe some text customization.

**Comment by nielsvanvelzen** [comment]
The displayed messages are using the systems provided "Toast" functionality and the length for that is not configurable by apps. It's working as intended.
