### ISSUE TITLE
Add folder image to now playing. 

### ISSUE THREAD

**Issue by servimo** [jellyfin/jellyfin-androidtv#2789]
### Describe the feature you'd like

When playing a song, the now playing should display the album cover.

**Comment by servimo** [comment]
I select an album from an artist and the album art is appearing, then when I play it the folder.jpg do not show in the screen of the played song. 
It's in jellyfin for Android TV.

**Comment by servimo** [comment]
I was using the wrong name for it, it was the screensaver. Sorry for this, the now playing with with all is buttons and info is ok.

**Comment by nielsvanvelzen** [comment]
The next release will feature a rewritten screensaver that does properly show the album art. So I'll go ahead and close this issue as fixed.
