### ISSUE TITLE
See next episode, change back language and subtitle

### ISSUE THREAD

**Issue by Copoto** [jellyfin/jellyfin-androidtv#2792]
### Describe the bug

Hi
When I watch an episode where I changed the language and the subtitle, if the next episode follow, jellyfin change back to the original laguage and subtitle.

Thanks

### Application version

0.15.9

### Device information

TCL Smart TV Pro

### Android version

Android 11

### Jellyfin server version

10.8.10

**Comment by stilobique** [comment]
The same goes for me, what I can give to help about this issue ?
If you have a documentation to check log or anything.
