### ISSUE TITLE
Stall when going to next episode, often followed by crash

### ISSUE THREAD

**Issue by AlexKalopsia** [jellyfin/jellyfin-androidtv#2800]
### Describe the bug

JF running on a Synology DS918+ 16Gb RAM. 

It's been some weeks now that the client goes in some form of total stall when the "Next episode" countdown ends, or when I manually try and make it go to the next episode. Media being played here is 1080p H264 SDR, with audio Dolby Digital+ 5.1

I can see from my desktop dashboard that the client is in Direct Play ("The source file is entirely compatible with this client, and the session is receiving the file without modifications.").

In general, _the few times when it works_, moving from one episode to the other is also incredibly slow, so I believe there might be something fishy happening.

![image](https://github.com/jellyfin/jellyfin-androidtv/assets/706110/f8adbe74-a96b-4201-8c1d-3008f2d3c779)

### Logs

Client crash: https://hastebin.com/share/kefotoxato.php
Server log: https://hastebin.com/share/kaqasasuqi.csharp

### Application version

0.15.9

### Where did you install the app from?

Sideloaded APK

### Device information

Amazon Fire Stick 4K Max

### Android version

Fire OS

### Jellyfin server version

10.8.10

**Comment by MattFryer** [comment]
I've been having this same issue for a while now. Both the fire TV app and side loaded android TV apps do the same. But the browser, mobile and webOS versions work perfectly. I've tried on various generations of fire TV stick including the latest 4K Max. If I force stop the app or wait until it crashes and open it again, its back to working perfectly although it normally loses a large portion of my progress through the episode. Happy to provide additional logs from my side if it will help with identifying the issue.

**Comment by nielsvanvelzen** [comment]
From the provided logs it looks like the server becomes unresponsive causing the app to crash. Some of the requests take a minute to respond, this is not good.
Not much I can do on the client side for this.

**Comment by AlexKalopsia** [comment]
For what is worth this also occurs when the media is in direct play and no transcoding is happening. I do get the feeling that the truth is somewhere in the middle, since I do detect very high drive utilization, but as @MattFryer above says I have no issue on other clients, so it's a bit unclear

**Comment by AlexKalopsia** [comment]
This is still happening, a bit unclear if @nielsvanvelzen latest reply suggest that it's smething that will be looked at?

**Comment by MattFryer** [comment]
> edit: it might help to use different drives for the Jellyfin data and the actual media. As these problems _probably_ arise from database read/writes.

@nielsvanvelzen I finally got around to moving the Jellyfin config to a USB pen drive I attached to my NAS to test this and it seems to have improved things drastically. Not just is it not longer crashing the android client constantly but the general performance of things like marking shows as complete seems to have improved. A rubbish old USB pen drive being so much better compared to a RAID5 NAS volume makes absolutely no sense to me however. My gut says there has to be something weird going on with Jellyfin for this to be the case as all other apps I have hosted on my NAS run like a dream with their data and media on the same RAID volume/pool.

**Comment by hundredfire** [comment]
I would like to know if there is any update on this? I have the same issue while running jellyfin on a separate drive than my media folders on a 2-bay synology NAS (they're set up as JBOD, no RAID)

**Comment by BJ24** [comment]
Hi,
I've been having this issue for more than a year I would guess. I am running docker on a Synology also. Run many other docker's and vms without issue. Wondering if anyone has explored this more.

**Comment by Zodsmar** [comment]
Hey, 

I have also been experiencing the same issue. 

https://www.reddit.com/r/jellyfin/comments/10fgzky/jellyfin_for_android_tv_freezes_and_ultimately/

My log is basically identical to this reddit post.

`Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from`
