### ISSUE TITLE
Where is the dimming effect for non-selected videos defined?

### ISSUE THREAD

**Issue by thousandlemons** [jellyfin/jellyfin-androidtv#2820]
### Describe the feature you'd like

When we browse videos in a library, the preview image of the currently selected video has full brightness, while other non-selected videos are slightly dimmed. Could you please help point me to the xml or kotlin file where this dimming effect is defined? I'm trying to build a customized app without the dimming effect. Many thanks!

**Comment by nielsvanvelzen** [comment]
Good to see you've figured it out. Please make sure to publish your changes publicly to comply with our license.

**Comment by nielsvanvelzen** [comment]
If it's only for personal use it's perfectly fine!
