### ISSUE TITLE
Version Selector - small annoyance - causes the cursor to drop one row

### ISSUE THREAD

**Issue by mikewesten** [jellyfin/jellyfin-androidtv#2821]
### Describe the bug

A small annoyance I just noticed with the recent v0.15.10 release.
Upon making a selection from the version selector's drop down menu,
it causes the active cursor to drop down one row onto the first item of the Cast/Crew section.

Ideally the cursor should remain fixed on the same row as the play button and the version selector button.

### Application version

v0.15.10

### Where did you install the app from?

Sideloaded APK

### Device information

Amazon Fire TV Stick 4k

### Android version

Fire OS 6.2.8.0 / Wolf Launcher v0.1.9-Wolf

### Jellyfin server version

v10.8.10

**Comment by mikewesten** [comment]
Upon testing a few other movie items I've discovered that this behavior is not consistent.
With some items, version selection causes the active cursor to move up a row, to the plot summary/description box.
In these cases, the common thread seems to be text descriptions which are long enough to include and require the expanded view option to read it all.

**Comment by nielsvanvelzen** [comment]
Already fixed in #2819
