### ISSUE TITLE
Jellyfin client for Android TV plays wrong version of film

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin-androidtv#2828]
### Describe the bug

I can't remember how I started to suspect this but here's how to reproduce:

- Choose a film, any film, create folder "film (2020)", and copy the film in. Name it "film (2020) - 1080P.mp4".
- Choose another film, copy it in the same folder and name it "film (2020) - 2160P.mp4".
- Observe Jellyfin for Android TV always play "film (2020) - 2160P.mp4", independent on what version of the film you select.
- The correct version is played on other clients.

### Application version

Latest

### Where did you install the app from?

None

### Device information

Android TV

### Android version

No idea

### Jellyfin server version

10.8.10

**Comment by mikewesten** [comment]
Same or similar issue here https://github.com/jellyfin/jellyfin-androidtv/issues/1521
