### ISSUE TITLE
LiveTV Guide Update Tick

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-androidtv#284]
The Guide doesn't automatically update to the new half hour block. This typically is not noticed after finishing a show, exiting it to find a new show and it leaves you in the original time slot.

**Comment by nielsvanvelzen** [comment]
I'm not that familiar with LiveTV but I'm assuming this is a feature request / enhancement to add dynamic updating to a certain screen.

**Comment by Artiume** [comment]
Can we move this to the jellyfin-web repository? I think it should be implemented there rather than here.

**Comment by thornbill** [comment]
Nope this is definitely an issue in the Android TV app. If it happens in both, then we should have separate tickets for each implementation. :smiley:

**Comment by Artiume** [comment]
Dang. I was hoping it fixing it upstream would fix it here as well

**Comment by MrChip53** [comment]
Is this still an issue? When working on the live tv code I definitely saw code blocks that SHOULD do exactly what you are wanting. It would force the live version of the guide to refresh upon opening every 30 minutes.

**Comment by MrChip53** [comment]
Just tested and this issue seems to be resolved.

**Comment by MrChip53** [comment]
@nielsvanvelzen @thornbill This was fixed in PR #569 and can be closed now.
