### ISSUE TITLE
[Feature] Auto turn on subtitles

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2840]
### Describe the feature you'd like

Option to auto turn on compatible subtitles and option to turn on subs that need to be transcoded

Not sure if this is any help

```
// Set the subtitle track to the first available track
val tracks = mediaPlayer.subtitleTracks
if (tracks.isNotEmpty()) {
    mediaPlayer.selectSubtitleTrack(tracks[0])
}
```

**Comment by nielsvanvelzen** [comment]
Personally I'm not working on new features for the current playback code but I do review pull requests for it. Improved subtitle selection and remembering it is one of the things I'd like to add eventually.

**Comment by nielsvanvelzen** [comment]
Although this option cannot be changed from the client, the app should now (in 0.18) respect the default subtitle selection from the server. Closing as solved.
