### ISSUE TITLE
TV show theme support

### ISSUE THREAD

**Issue by dasfuu** [jellyfin/jellyfin-androidtv#2872]
### Describe the feature you'd like

I would like to have support for the tv show theme on androidtv too.

Kinda related: Do you accept (bug) bounties?

**Comment by nielsvanvelzen** [comment]
Closing as a duplicate of #1150.

> Kinda related: Do you accept (bug) bounties?

No, but you can always [sponsor me](https://github.com/sponsors/nielsvanvelzen) if you appreciate my work on the app.
