### ISSUE TITLE
Android TV official app can't play SSA/ASS subtitles in Direct Play (there is no option to enable like in the Android app for mobiles)

### ISSUE THREAD

**Issue by raulpetru** [jellyfin/jellyfin-androidtv#2875]
### Describe the bug

The issue is that the video file will remux on official Android TV app and doesn't show subtitles. I get the same result on Android phone if I disable the "Allow SSA/ASS subtitles in direct play". But on Android TV in client settings there is no option to enable "Allow SSA/ASS subtitles in direct play".

Transcoding is off, and all videos I play are re-encoded with Handbrake in H264 with AAC in mkv container. So if the client is compatible the video should play in Direct Play. Worst case it will remux. But given that the mobile Android app can show SSA/ASS subtitles, is there a more technical reason behind why that setting is missing on Android TV?

Subtitles play well if external player is used (for example MX Player), but Exo player will remux and will not show subtitles.

### Media info of the file

```shell
General
Unique ID : 209830786305952452455496204121740007415 (0x9DDBF08074F133633075C5A441A1D7F7)
Complete name : Z:\Anime\Demon Slayer Kimetsu no Yaiba (2019)\Season 3[Subsplease] Kimetsu No Yaiba - Yuukaku-Hen - 01 (1080P) [E6815c78].mkv
Format : Matroska
Format version : Version 4
File size : 983 MiB
Duration : 46 min 51 s
Overall bit rate : 2 934 kb/s
Frame rate : 23.976 FPS
Encoded date : 2023-06-12 16:29:15 UTC
Writing application : HandBrake 1.6.1 2023012300
Writing library : Lavf59.27.100
ErrorDetectionType : Per level 1
Attachments : Roboto-Medium.ttf / Roboto-MediumItalic.ttf / arial.ttf / arialbd.ttf / comic.ttf / comicbd.ttf / times.ttf / timesbd.ttf / trebuc.ttf / trebucbd.ttf / verdana.ttf / verdanab.ttf

Video
ID : 1
Format : AVC
Format/Info : Advanced Video Codec
Format profile : Main@L4
Format settings : CABAC / 4 Ref Frames
Format settings, CABAC : Yes
Format settings, Reference frames : 4 frames
Codec ID : V_MPEG4/ISO/AVC
Duration : 46 min 51 s
Width : 1 920 pixels
Height : 1 080 pixels
Display aspect ratio : 16:9
Frame rate mode : Constant
Frame rate : 23.976 (24000/1001) FPS
Color space : YUV
Chroma subsampling : 4:2:0
Bit depth : 8 bits
Scan type : Progressive
Writing library : x264 core 164 r3100 ed0f7a6
Encoding settings : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=240 / keyint_min=24 / scenecut=40 / intra_refresh=0 / rc_lookahead=30 / rc=crf / mbtree=1 / crf=22.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=20000 / vbv_bufsize=25000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default : Yes
Forced : No
Color range : Limited
Color primaries : BT.709
Transfer characteristics : BT.709
Matrix coefficients : BT.709

Audio
ID : 2
Format : AAC LC
Format/Info : Advanced Audio Codec Low Complexity
Codec ID : A_AAC-2
Duration : 46 min 51 s
Channel(s) : 2 channels
Channel layout : L R
Sampling rate : 44.1 kHz
Frame rate : 43.066 FPS (1024 SPF)
Compression mode : Lossy
Delay relative to video : -23 ms
Title : Stereo
Language : Japanese
Default : Yes
Forced : No

Text
ID : 3
Format : ASS
Codec ID : S_TEXT/ASS
Codec ID/Info : Advanced Sub Station Alpha
Duration : 46 min 51 s
Compression mode : Lossless
Title : English subs
Language : English
Default : No
Forced : No
```

### Application version

0.15.11

### Device information

TV PHILIPS 43PUS7906,4K, HDR, 108 cm, UHD43PUS7906

### Android version

Android 11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
The Android TV app cannot display the SSA and ASS formats properly (our underlying video player does not have a complete implementation) so we decided to force transcoding in those cases.

Closing as not an issue/wontfix.

**Comment by raulpetru** [comment]
> The Android TV app cannot display the SSA and ASS formats properly (our underlying video player does not have a complete implementation) so we decided to force transcoding in those cases.
> 
> 
> 
> Closing as not an issue/wontfix.


Thanks four your answer!

Does this mean that the player will have more functions implemented in the future?

**Comment by nielsvanvelzen** [comment]
I'm hoping to add proper support for it eventually, but that will take some time.

**Comment by pikausp** [comment]
> I'm hoping to add proper support for it eventually, but that will take some time.

@nielsvanvelzen hello, is there any plan to expose ASS support as an opt-in feature? To my understanding Exo player now supports decent level of the specs (even if not the full specs).

**Comment by nielsvanvelzen** [comment]
> > I'm hoping to add proper support for it eventually, but that will take some time.
> 
> [@nielsvanvelzen](https://github.com/nielsvanvelzen) hello, is there any plan to expose ASS support as an opt-in feature? To my understanding Exo player now supports decent level of the specs (even if not the full specs).

Hi, the subtitle support within media3 for SSA/ASS is near non-existent. Yes it can show _some_ text but it doesn't support 99% of the format.
We've been working on adding proper rendering using libass but unfortunately the only working solution for that is riddled with performance issues and therefor we did not release the support with 0.19. With the current state it also doesn't seem to be likely for 0.20. You can try a development build via #5121.

**Comment by pikausp** [comment]
Thank you for the prompt response. I will install the version on weekend.

What are currently the best ways to help with the delivery of this feature? Test the PR build and report on how it performs? Bounty? Something else?

**Comment by nielsvanvelzen** [comment]
There is no need for testing as I'm already aware the performance is bad.
We need someone with experience in the Android NDK and C programming language who is willing to fix the performance issues in the used library (or create a new port of libass). I don't have the time for that myself.
