### ISSUE TITLE
Option to remove windows warniign about app being optimized for a TV/

### ISSUE THREAD

**Issue by EatedPantsu** [jellyfin/jellyfin-androidtv#2881]
### Describe the feature you'd like

As title says, add option to remove that window permanently.
Currently you can only click on it to dismiss it but on app restart it returns.
I am using Jellyfin TV app on non TV android as I modified to function as an hacked android box and it works excellent except minor issues like this.

![Screenshot_20230708_200419](https://github.com/jellyfin/jellyfin-androidtv/assets/29340377/a1307e34-8ef6-410b-8d70-0a79d5df5621)

**Comment by nielsvanvelzen** [comment]
This will be fixed in version 0.16. You can disable the message from the app preferences under "developer options". The app needs to be restarted after changing the preference.
