### ISSUE TITLE
After updating to v0.15.11 Intro Skipper stopped working

### ISSUE THREAD

**Issue by d8f6** [jellyfin/jellyfin-androidtv#2886]
### Describe the bug

After updating today to v0.15.11 the Intro Skipper plugin stopped working for me. I have the plugin set to Automatically skip intros and it has always worked before. After downgrading to v0.15.10 everything works as it should. I tried restarting the server and the app, but that did not work. I did not do a lot of testing, so if anyone else can verify this issue (or verify that intro skipper is working for them on v0.15.11) I would appreciate it. Okay, thanks.  

Edit: I was not sure whether to put this under bug or playback bug so I went with the latter. If this is in the incorrect section please let me know.

### Application version

v0.15.11

### Device information

Nvidia Shield 2015

### Android version

LineageOS for microG [foster] (android 11)

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
We do not support third party plugins. Please open an issue with the author.
