### ISSUE TITLE
Add ability to force subtitles to be burned into the video by the server

### ISSUE THREAD

**Issue by Reinachan** [jellyfin/jellyfin-androidtv#2903]
### Describe the feature you'd like

In the Jellyfin app for WebOS, there's an option to burn subtitles into the videostream with options for doing it for complex formats, simple formats, or all formats. I'd like the Android TV app to have this option too.

**Why?**
I'm mostly streaming anime, many of which have complex subtitles with lots of transforms and redraws and such. While the Android TV device I've got is powerful enough to render 4k video, it really chugs whenever a scene with complex subtitles show up. Sometimes it'll even crash. And this is straight up the hardware not being powerful enough as it has the same issues when playing back using VLC (MPV refuses to load HVEC with GPU decoding).

I previously had a similar issue (subtitles updated at a too low framerate) when streaming to an LG smart TV but solved it by forcing the server to burn the subtitles into the video.

Yes, this requires transcoding, but I'll gladly take a slightly worse image quality over the extreme framedrops I get from the subtitles being too heavy to render.

**Comment by Reinachan** [comment]
@VampiricAlien Subtitle format is ASS. An example would be MTBB's release of Oshi no Ko. The second episode starts off with a lot of text that results in major slowdowns on my hardware. Episode 6 also has a lot of scenes like that. I can't link to it for obvious reasons.

ExoPlayer converts the subtitle format to a basic one. This is not really what I want.

LibVLC renders the subtitles correctly, but has major slowdowns when subtitles gets more complex.

External VLC has the same issue as LibVLC.

External MPV doesn't support GPU decoding on my device and CPU decoding is too heavy.

> Your sever may not support HEVC or might not be setup.

It's not my server config as I can watch HEVC content on the device using LibVLC or VLC directly. I can also watch HEVC content on other devices that support HVEC decoding.

> Suggestion: next time the app crashes, check /web/index.html#!/log.html for the logs to paste here so the 'bug' can be fixed.

If it happens again, I will. It's been long enough since I watched something with demanding subtitles on the device, so I can't remember if it was Jellyfin or VLC that crashed. My point in writing that was moreso highlighting the need for an option to force burning in of subtitles, but I guess the performance problems should be good enough reason.

Again, I'd like to stress that the performance issues are a result of hardware not being powerful enough. And that's why I want the ability to force burning the subtitles into the video, like the standard Android app, the webapp, and the WebOS app lets you do.

![Screenshot_20230801-182029_Jellyfin_1](https://github.com/jellyfin/jellyfin-androidtv/assets/16106839/f74c5b8c-e01f-4692-8ee6-ec3d89512047)

**Comment by nielsvanvelzen** [comment]
The app will only try to render the subtitles client side when transcoding is disabled. This will result in the lagg (VLC) or text-only (ExoPlayer).

**Comment by Reinachan** [comment]
Whatever the underlying issue was that prevented the subs from being transcoded seem to have been fixed, so I'll close this.
