### ISSUE TITLE
How to delete media after watching?

### ISSUE THREAD

**Issue by BB-Forrest** [jellyfin/jellyfin-androidtv#2942]
### Describe the bug

I raised this as a feature request when it was taken out of v0.15.

I've signed up to the Beta Tester programme and new beta was downloaded onto my Sony Bravia TV.

Watched an episode of a TV series without issue (I like the screensaver kicking in when paused) but upon finishing watching there doesn't appear to be a way of deleting the media. If there is supposed to be another button it doesn't appear.

Is it dependant on a different server version?

Is it me being an idiot?

Or is there something missing?

Thanks for all the work - appreciated.

### Application version

v0.16.0-beta.1

### Where did you install the app from?

Google Play

### Device information

Sony Bravia TV KD-49XG9005

### Android version

Whatever the latest for that TV is - its firmware is up to date

### Jellyfin server version

10.8.10

**Comment by BB-Forrest** [comment]
That's great, set it in the app and it's there.

Thanks for your help.

**Comment by nielsvanvelzen** [comment]
> How do you sign up to be a beta tester on a Google TV (i.e. AndroidTV device)?

https://jellyfin.org/posts/android-betas as mentioned in all beta release notes

**Comment by brianjmurrell** [comment]
> https://jellyfin.org/posts/android-betas as mentioned in all beta release notes

Yeah, it doesn't really explain how to get the beta from the Play Store.  I could not find a way to do it on the Google TV UI.

I did find https://9to5google.com/2022/04/05/how-to-android-app-beta-play-store/ useful in enrolling my Google Play account in the Jellyfin Android TV channel on my Android phone, which then allowed me to update the app on the Google TV.

Hopefully that is helpful for anyone else who comes across this issue.
