### ISSUE TITLE
[0.16.0-beta.2] TV guide items are showing in recordings and programs

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#2963]
### Describe the bug

Since search was fixed from crashing, items are showing in recordings and programs section off the app.

The debug app isn't able to be updated (beta 1 > 2). Having to uninstall the app to install update, can this change? 

### Application version

0.16.0-beta.1

### Where did you install the app from?

Sideloaded APK

### Device information

SHIELD

### Android version

11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Can you explain the issue with some more detail? I don't understand what's going wrong from the current description.

**Comment by nielsvanvelzen** [comment]
Thanks for the explanation, turns out we cannot search recordings with the API and it will instead search everything. I've removed the recordings row for the next beta.
