### ISSUE TITLE
Banners and thumbnails fail to load required images

### ISSUE THREAD

**Issue by DoggoOfSpeed** [jellyfin/jellyfin-androidtv#2974]
### Describe the bug

Set the image type to thumbnail/banner in the media grid settings;
The resulting cards have the images from the Poster setting, just in a different aspect ratio;

### Application version

0.16 beta 2

### Where did you install the app from?

Sideloaded APK

### Device information

Reproducible both on an emulator and a Sony TV

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
This is working as intended. If there are no banner or thumb assets the app automatically uses the posters. The same behavior can be found in the web client.

**Comment by DoggoOfSpeed** [comment]
Right, but this should still be improved as currently the app grabs images with a much smaller resolution resulting in the banners looking incredibly blurry, unlike the webui.
