### ISSUE TITLE
Version 0.11 - Just recordings and settings shows up

### ISSUE THREAD

**Issue by Cesar-Pythian** [jellyfin/jellyfin-androidtv#298]
Just installed the new version (0.11) and in the start screen I just can see Recordings and Settings. If I search I can find my shows and movies so at least is seeing them.
I see this in the release notes:
> New home screen
> The newly made home screen now looks more or less the same as the webclient. It will display the sections you have chosen under your "Home" preferences.
> Note: changing sections is only available in the web version for now

but not sure why I need to setup, in the webclient and in the prev android tv version didn't have this issue.
This is what I see in the new version:
![IMG_20200205_160858](https://user-images.githubusercontent.com/40499713/73883797-909d1600-4832-11ea-8075-8906b605461d.jpg)

and in the prev version:

![IMG_20200205_160959](https://user-images.githubusercontent.com/40499713/73883825-9d216e80-4832-11ea-97d7-5373ea28fc57.jpg)

**Comment by thornbill** [comment]
This is definitely an issue with that feature. When the homescreen settings are changed from the default only the values that differ from the defaults are saved. Android TV is not handling this properly leading to the default rows being blank.

As a workaround you can either:
* Only use default settings for the home screen rows
* Change all rows so they are not the default value (This can be done by setting the first row to "None" and offsetting the other rows)

We are working on a fix now. Thanks!

**Comment by nielsvanvelzen** [comment]
Fixed in #299

**Comment by ThatNerdyPikachu** [comment]
@nielsvanvelzen Quick question, is there a way to see what the default values are for the rows in the settings? (``Only use default settings for the home screen rows``)

I know this is a closed issue, sorry :p

**Comment by nielsvanvelzen** [comment]
I can't look then up right now (not on a PC so can't look in the code) but you can try setting all options to something els, close the page and then go back to put all sections back to what they were.

This way you can be certain everything is set properly.

**Comment by ThatNerdyPikachu** [comment]
@nielsvanvelzen Cool, thank you. Is there an ETA for 0.11.1, or should I just build from master for now?

**Comment by nielsvanvelzen** [comment]
We have a few issues we want to fix before we release it. If everything goes smoothly the new version should be released in a few days.

**Comment by AndreasGB** [comment]
@ThatNerdyPikachu the default order seems to be
* My Media
* Continue Watching
* Continue Listening
* Live TV
* Next Up
* Latest Media
* None
