### ISSUE TITLE
TV Client

### ISSUE THREAD

**Issue by bosidiA** [jellyfin/jellyfin-androidtv#2987]
### Describe the bug

TV Client in the movie display (poster large) and sorting (add date), after modifying it, the next time you use it, it goes back to the default, and you can't save the settings.

### Application version

0.15.2

### Where did you install the app from?

Google Play

### Device information

Xiaomi MiBOX4

### Android version

android 9

### Jellyfin server version

10.8.10.1

**Comment by nielsvanvelzen** [comment]
It looks like you use an outdated version of the app. The latest versions is 0.15.12. Please update your app and let us know if the issue persists.

**Comment by bosidiA** [comment]
Ok, thanks.

**Comment by bosidiA** [comment]
Switched to version 0.15.12 and the problem persists.
Setting the order of arrangement (add date) poster (large) and portrait, and opening it the next day it went back to the default.
I need to reset it every time I open it

**Comment by bosidiA** [comment]
The settings were fine at first, and when you power down the TV and turn it back on, it goes back to default.

**Comment by nielsvanvelzen** [comment]
Can you explain with a bit more detail which specific settings are not working? Do you mean the library display settings?

**Comment by bosidiA** [comment]
This one is my problem, not the program's.
I restarted jellyfin server and the problem was solved.

这个是我的问题，不是程序的问题。
我重启了jellyfin server 问题就解决了

**Comment by nielsvanvelzen** [comment]
Glad to hear it's working now. I'll close the issue.
