### ISSUE TITLE
.aiff audio doesn't play

### ISSUE THREAD

**Issue by DoggoOfSpeed** [jellyfin/jellyfin-androidtv#2999]
### Describe the bug

Try to play audio in .aiff format.

It does not start.

### Application version

master

### Where did you install the app from?

None

### Device information

Emulator

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
The new music player backend only allows direct play right now. This is especially notable in an emulator that supports way less codecs compares to actual hardware running Android TV.
