### ISSUE TITLE
Next Up Not Supported?

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-androidtv#300]
From a [user comment](https://www.reddit.com/r/jellyfin/comments/ezgy3q/new_android_tv_release_v0110_improved_video/fgnage1) on Reddit:
>I've been looking forward to this release for the channels and up next support but neither of them are working. Any ideas?

>...The application Jellyfin is not showing as an application with channels available and in the Next Up menu it is not shown as an application that supports the Next Up channel.

**Comment by nielsvanvelzen** [comment]
I can confirm it isn't working properly. The "Play Next" section is populated by Jellyfin but I can't remove them.

Screenshots for reference:
![image](https://user-images.githubusercontent.com/2305178/73889980-2f486780-4871-11ea-9798-5d9130d5d123.png)
_This works properly_

![image](https://user-images.githubusercontent.com/2305178/73890012-42f3ce00-4871-11ea-8b8c-a32856386eeb.png)
_Jellyfin doesn't show for some reason_

**Comment by thornbill** [comment]
The current implementation only supports Android 8+ since older versions used a different API, so that may also be what users are experiencing.

**Comment by nielsvanvelzen** [comment]
There is actually a bug in Android that caused Jellyfin to not show up when choosing which apps may display in the "Play Next" panel. I fixed it by adding a "normal" channel (See #331).

As thornbill said, you need to have the newer leanback (android tv) interface for it to work. The behavior is a bit odd as the rows don't display in the background yet (we need a big refactor for that first). Only when you open the home screen (opening the app or going back from another screen) will update the rows for now.
