### ISSUE TITLE
语言系统错误

### ISSUE THREAD

**Issue by gongxianzhang** [jellyfin/jellyfin-androidtv#3008]
### Describe the bug

jellyfin服务器设置了中文，在手机三星打开jellyfin TV都是中文，安装包提取后装在投影仪当贝X3后打开界面是英文显示

### Logs

![当贝投影](https://github.com/jellyfin/jellyfin-androidtv/assets/68483527/d1e6c5cc-b904-4526-9b3e-3a6ad094d498)
![三星手机](https://github.com/jellyfin/jellyfin-androidtv/assets/68483527/b4eaeb6f-de7f-4d00-bf56-9a3af6ae6d20)

### Application version

0.15.12

### Where did you install the app from?

None

### Device information

dbx3

### Android version

手机安卓13  投影仪安卓11

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
> **Language system error**
> The jellyfin server is set in Chinese, in the cell phone Samsung open jellyfin TV are in Chinese, the installation package is extracted and installed in the projector Dangbei X3 after opening the interface is displayed in English!

The app uses the system language and falls back to English if there are no translations found. We do have Chinese translations so perhaps your system is not set to the correct locale?

**Comment by gongxianzhang** [comment]
> 

当贝设备时区是北京，就打开jellyfin里面的设置是英文

**Comment by nielsvanvelzen** [comment]
> When the time zone of the device is Beijing, open the jellyfin inside the settings are in English

The app uses the device language, not the device timezone, to determine the language. This is all handled by the system.

**Comment by HyskoaMorroh** [comment]
不晓得为何，安装了一直是英文，怎么调整默认中文和时区都不行
`  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5
    volumes:
      - /path/to/jellyfin/library:/config
      - /path/to/tvseries:/data/tvshows
      - /path/to/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
      `

**Comment by HyskoaMorroh** [comment]
<img width="2232" height="924" alt="Image" src="https://github.com/user-attachments/assets/03254f18-b99b-438a-9dc2-44b30f09975e" />

<img width="1998" height="1065" alt="Image" src="https://github.com/user-attachments/assets/6d673d16-77d0-405c-b9df-d31b67c2b69e" />

<img width="1770" height="1014" alt="Image" src="https://github.com/user-attachments/assets/f8a3340c-0747-451c-a7c2-650e894e3ca2" />
