### ISSUE TITLE
Deinterlacing/doubling frame rate without transcoding

### ISSUE THREAD

**Issue by ahrendt** [jellyfin/jellyfin-androidtv#3016]
### Describe the feature you'd like

To my surprise nobody seems to have a problem with Jellyfin, especially on Fire TV, not doubling the frame rate on interlaced content.
Plex and other players do it just fine - but as I want to use Jellyfin for watching TV it's just annoying to watch.
Anything that I'm missing here? Tried libvlc and ExoPlayer, both handling it the same way...

**Comment by nielsvanvelzen** [comment]
Please use the bug report template if you want to report a bug or use one of our [troubleshooting channels](https://jellyfin.org/contact/) for troubleshooting.
