### ISSUE TITLE
TV Show grid shows duplicate when a show is removed and filtered

### ISSUE THREAD

**Issue by ScottESanDiego** [jellyfin/jellyfin-androidtv#3021]
### Describe the bug

1. Set the TV Show filter to only show unwatched shows/seasons
2. Watch a TV Show where there is only one new episode
3. Observe that the last (aka, bottom-right) TV Show icon is now duplicated

For example, my grid of shows has "Foo" in the upper-left with 1 episode in it, a whole bunch of TV shows, and then "Bar" at the bottom-right of the grid.  When I finish watching "Foo", the TV Show disappears from the grid (correctly, because I have the display filtering only unwatched shows), but the grid keeps the same number of TV Shows listed.

It should shrink by one, but instead it shrinks by one (aka, removing "Foo"), but shows "Bar" and "Bar" as the last two.

### Application version

0.16.beta2

### Where did you install the app from?

Google Play

### Device information

NVIDIA Shield TV Pro

### Android version

10

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Thanks for the report, should be fixed in the next beta!
