### ISSUE TITLE
Flag to turn off "autoplay next episode"

### ISSUE THREAD

**Issue by burggraf** [jellyfin/jellyfin-androidtv#3031]
### Describe the feature you'd like

Currently there are the following two customization settings:

- Show next video info
- Next imer duration (0-30s)

I'd like to see a checkbox available to turn off the autoplay next episode feature entirely.  I never want to play the next episode, but want to just return to the menu at the end of an episode.

**Comment by BotBlake** [comment]
This feature is already implemented.

Go to 
Settings -> Playback -> Advanced -> "Play Next Episode automatically"

Kind Regards

**Comment by richardtorres314** [comment]
How would this be done for music? I would like to click on a song, have it play, and stop auto-playing the next track in the album. Unchecking the aforementioned checkbox does not seem to affect this functionality for music. Thanks in advance!
