### ISSUE TITLE
"Next up" section does not appear on home screen (intermittently)

### ISSUE THREAD

**Issue by burggraf** [jellyfin/jellyfin-androidtv#3032]
### Describe the bug

1. Customize your home screen to make "Next up" your "Home section 1"
2. Restart the app several times

Sometimes, and this is intermittent, the words "Next up" will appear at the top of the screen when the app starts up, and other sections will populate (Continue watching, My Media, Recently added in Shows, etc.) but after a while (15 seconds or so?) the words "Next up" will disappear and the Next up section never appears on the screen.  Other times, it will appear just fine.

Also, the "Next up" section is always an order of magnitude slower to populate than the other sections.

This happens on 0.16.0-beta.3 as well as the current release (0.15.x).

### Application version

0.16.0-beta.3

### Where did you install the app from?

Sideloaded APK

### Device information

ONN TV 4k

### Android version

Android TV v10

### Jellyfin server version

10.8.10

**Comment by burggraf** [comment]
Note:  the slowness of bringing up the "Next up" section appears to be universal with Jellyfin server.  It's the same for the web client, etc.

**Comment by nielsvanvelzen** [comment]
The app will always add the empty rows and then populate them, if no items are found the row is hidden.

There can be a few reasons why the row will hide, primarily when there is nothing to show but it could also be caused by a failed network request or timeout (I believe this part has a timeout of 30 seconds). You already said the next up part is slow so this is likely an issue on the server side and not on the client.

**Comment by burggraf** [comment]
Yeah, I'm assuming it's just timing out from the server, so this is most-likely related to Jellyfin Server.  It's slow on the service I subscribe to, and it's also slow on a local server I spun up on my LAN.  Should I report this on the server repo?

**Comment by nielsvanvelzen** [comment]
It would make more sense on the server repository although the issue might be caused by your setup at which point it might be better to try our troubleshoot forums/chat first

**Comment by burggraf** [comment]
I don't see anything I can adjust on my side for this -- plus like I said the behavior is the same for both my own server and those managed by other (more experienced) Jellyfish administrators.
