### ISSUE TITLE
android tv

### ISSUE THREAD

**Issue by emir1986** [jellyfin/jellyfin-androidtv#3037]
### Describe the bug

User access
Access to media library [YES]
Device Access [YES]

One network for example 3G/4G/ADSL
mobile application on the phone no problem, everything works
Android TV box (any) go to the application
We enter the IP address, the next step is to enter the login and password, we get to the server and it is empty, not a single cartoon, not a single movie, or anything

We haven’t changed anything, we connect to the home network 192,168,0,0
Jelly server 192,168,0,1
Mobile phone 192,168,0,2
TV box 192.168.0.3
Everything is super everything works

### Application version

all

### Where did you install the app from?

Google Play

### Device information

all

### Android version

all

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
Please provide the requested information instead of answering "all". Also, make sure to test with the latest version of Jellyfin first, we do not support 10.8.1 anymore.

**Comment by thornbill** [comment]
Making sure your issues have good titles is also pretty important.
