### ISSUE TITLE
The resume row items are duplicated when marking an item as played that was previously in the resume row 

### ISSUE THREAD

**Issue by JVT038** [jellyfin/jellyfin-androidtv#3051]
### Describe the bug

1. Have two or more items in the resume now row.
2. Go to one of the items
3. Mark one item as played
4. Go back to the home menu
5. See duplicated item

Screenshot:

![image](https://github.com/jellyfin/jellyfin-androidtv/assets/47184046/d7d73578-fddf-4468-861e-33da03cb579a)

### Application version

0.15.11

### Where did you install the app from?

Google Play

### Device information

Philips 49PUS6561  

### Android version

Android 8.0

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
This issue should be fixed in the next beta version (0.16.0-beta.4), see #3024 / #3021.
