### ISSUE TITLE
Family Filter for Android TV

### ISSUE THREAD

**Issue by vveed** [jellyfin/jellyfin-androidtv#3079]
Hello Contributors ,

can anyone please explain, why there are no Filters in the **AndroidTV App** but in the **Android App**? I have a Daughter and i cant Filter Media by FSK 0 - FSK 12 or Animation or Family or Year

All these Filters are avaible at the Android App but not on the AndroidTV app

Maybe iam wrong but i cant find the Filter

thank you!

**Comment by horizon1250** [comment]
This functionality is indeed not in the AndroidTV app, it is possible to sort by rating but not filter by rating. You have a temporary solution you could do until this enhancement is implemented

Create a new user and limit the parental rating via the dashboard (see picture)
![parental-controls](https://github.com/jellyfin/jellyfin-androidtv/assets/146419076/da6853c6-4d1c-47af-b4f7-65aa083f83bc)
