### ISSUE TITLE
Removing Live TV home section in settings does not remove live TV

### ISSUE THREAD

**Issue by akesher123** [jellyfin/jellyfin-androidtv#3087]
### Describe the bug

After toggling the setting off, the live TV section (not the single item in the libraries row) in the main menu still shows.

### Application version

16 beta 4

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
You might need to re-open the app for the change in home sections to take  effect.

**Comment by akesher123** [comment]
I had restarted it with no success but a clear cache fixed it.
