### ISSUE TITLE
Jellyfin mutes Android TV

### ISSUE THREAD

**Issue by Maltahl** [jellyfin/jellyfin-androidtv#309]
Everytime i finish an episode of a series the app somehow mutes my Android TV forcing me to click on volume up to reenable audio.

Does not happen other apps such as YouTube, Amazon Prime Video and Netflix.

Jellyfin 0.11 for Android TV on NVIDIA SHIELD TV 2019 running Android TV 9.0

**Comment by nielsvanvelzen** [comment]
A quick search shows that we have a function that can mute the device in [TvApp.java](https://github.com/jellyfin/jellyfin-androidtv/blob/ba3a95fc3d69435ecedf91ac9862b20d4b53b6a0/app/src/main/java/org/jellyfin/androidtv/TvApp.java#L208)

But it's only activated as a [command](https://github.com/jellyfin/jellyfin-androidtv/blob/25edae156340ccd8c6aa9606f479638ba6d7b52c/app/src/main/java/org/jellyfin/androidtv/eventhandling/TvApiEventListener.java#L62). So it can't do it on its own after finishing an episode afaik.

Will need some investigation to reproduce this and fix it.

**Comment by brando56894** [comment]
Was this already pushed out? I'm using 0.11.1 and this still happens for me.

**Comment by nielsvanvelzen** [comment]
No this will be released in 0.12.0

**Comment by kylehendricks** [comment]
(Just another piece of information in case #322 somehow doesn't fix the issue.)

I noticed when the muting does happen, it will sometimes just mute and sometimes quickly mute then unmute within a second.

**Comment by nielsvanvelzen** [comment]
As of #322 the app doesn't control volume at all so if sound is muted during playback it is caused by stutter or other issues. Please make a new issue if this happens again and give us additional information like the media information.

**Comment by RaymondSchnyder** [comment]
I compiled the newest master branch for myself (debug target) and i can confirm it works for me now. Thanks!

**Comment by saltolenin** [comment]
I don.t know, is it still actual, but in version 0.11.5 still muting audio.
Using on Nvidia Shield.

**Comment by RaymondSchnyder** [comment]
> I don.t know, is it still actual, but in version 0.11.5 still muting audio.
> Using on Nvidia Shield.

It happens less frequently but it still happens, yes.
And i use a shield too.

**Comment by saltolenin** [comment]
Then , just wouestion. When will be v 0.12 released. 

>  nielsvanvelzen moved this from To do to Done in v0.12.0 on 14 Feb 2020
Promised was year ago.

**Comment by RaymondSchnyder** [comment]
@saltolenin When its done. This is free software. The maintainers work on those projects in their freetime, unpaid.
If you need that release now, build it yourself, its not hard as dockerfiles are provided.

**Comment by bt90** [comment]
> 
> 
> As of #322 the app doesn't control volume at all so if sound is muted during playback it is caused by stutter or other issues. Please make a new issue if this happens again and give us additional information like the media information.

As requested: #881
