### ISSUE TITLE
Next Up screen list (still) misses episodes

### ISSUE THREAD

**Issue by zilexa** [jellyfin/jellyfin-androidtv#3094]
### Describe the bug

I have reported this probably over a year ago. Still facing this issue. 

1. Play a couple of episodes
2. Hope you are not affected by the bug that prevents you from seeing Next Up screen after an ep finishes (happens every now and then, maybe related to one of the 2 bugs listed below).
3. End up in Next Up screen.
4. Notice the missing episodes, makes no sense, since if you browse to the show itself you notice all episodes are available and the missing ones in the Next Up screen are unwatched.

Bug is clear in this screenshot:
![P_20231002_201121_BURST_001](https://github.com/jellyfin/jellyfin-androidtv/assets/3430004/47c12a0f-9a6a-42e1-86aa-7618bd8be070)

Hard prove episodes 8 and 9 should have been present in Next Up:
![P_20231002_201146](https://github.com/jellyfin/jellyfin-androidtv/assets/3430004/e224c0da-feac-4992-99db-4b9ce0b2bea3)

This issue exists for a long time (over a year) and might be related to the following issues that I also happen to experience since I started using Jellyfin AndroidTV:
- https://github.com/jellyfin/jellyfin-androidtv/issues/2827
- https://github.com/jellyfin/jellyfin-androidtv/issues/2706

### Application version

0.15.12

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11 (latest official ShieldTV version)

### Jellyfin server version

10.8.10

**Comment by zilexa** [comment]
If I binge watch a show like this sitcom, I don't realize if I don't pay a lot of attention that Jellyfin keeps skipping episodes. 
Without switching to Kodi I wouldn't have noticed this. 

But this issue exists for years, I experienced it when I started using Jellyfin for AndroidTV (Shield Pro) 3 years ago. 
I don't understand how others are using JF? Surely it must affect others?

**Comment by zilexa** [comment]
This video says it all. You can't rely on Jellyfin, watching TV shows!
https://streamable.com/ecl0vu

Please fix!

**Comment by nielsvanvelzen** [comment]
This is not an issue with the app. The app requests the "next up" items from the server and just displays them.

**Comment by zilexa** [comment]
Oh, I didn't know that, sorry. 
The web version of Jellyfin and the Android version show - below the Next Up item - a row of "More from Season 2", starting with the last watched item:

![Screenshot from 2023-10-11 21-22-27](https://github.com/jellyfin/jellyfin-androidtv/assets/3430004/4fd65c3d-c4cd-4c12-a1fa-fe7c09100249)

Is "Next Up" then not just supposed to be a single item? 
Perhaps it should not be list of items, because the server only responds with 1 item? 

I am just guessing here. 

How can we prevent watching episode 9, then 14 and so fort? Because that is really what is happening here..
If you do not watch a serial story, you don't notice it until you realize you finished the season a bit fast..

**Comment by nielsvanvelzen** [comment]
> The web version of Jellyfin and the Android version show - below the Next Up item - a row of "More from Season 2", starting with the last watched item:

Actually it shows all episodes but the row was automatically scrolled to show the items starting from the current one. It is different from the "next up" row that the Android TV app shows.

> Is "Next Up" then not just supposed to be a single item?

Next up is "all the episodes you haven't watched yet in order"

>  Perhaps it should not be list of items, because the server only responds with 1 item?

The server does respond with multiple items, which we show.

> How can we prevent watching episode 9, then 14 and so fort? Because that is really what is happening here..
> If you do not watch a serial story, you don't notice it until you realize you finished the season a bit fast..

Not sure, I don't see an issue in the client so it is likely a bug on the server side. You'll probably have a better chance creating an issue over there.

**Comment by zilexa** [comment]
Thanks I will do that! Feel free to close this one.
