### ISSUE TITLE
Question or bug: how are subtitles supposed to work?

### ISSUE THREAD

**Issue by zilexa** [jellyfin/jellyfin-androidtv#3095]
### Describe the bug

These are subtitles related questions that might be related to (independent) bugs. I am happy to create bug reports, but maybe it's simply my lack of knowledge hence first the questions. 
For me it makes Jellyfin not so usable, I cannot imagine I'm the only one, so probably it's my fault and that's why I can't call out a bug yet. 

I have always experienced lots of issues with subtitles. Currently (v0.15.12) it's a lot better already!! But a few things I notice (happy to create bug reports, just not sure if these are bugs):

1. When playing back old 4:3 episodes (like Will & Grace from 1998) on a modern 16:9 TV (MKV files with separate .SRT files), the subtitles appear very bold. They seem visually compressed. None of the subtitle settings are able to remedy this, whatever combination I choose, looks like it's due to the 4:3 playback because I don't have this issue with regular wide-screen material:
![P_20231002_202709](https://github.com/jellyfin/jellyfin-androidtv/assets/3430004/bf8f4b84-9dc1-4cd0-ace2-d243c601909a)

2. What does "subtitle stroke size" mean? I Googled a lot, nothing refers to that term. Nothing on the internet 🤷🏽‍♂️ I tested the lowest, mid and highest value with regular 16:9 MKV movies with SRT files that are visually perfect. It didn't have any effect. What is that option? Is it a bug that it has no effect whatever value I select?

3. When 1 subtitle is available: Why do I have to select the subtitle (instead of "None") in the playback screen 9 out of 10 times when only a single subtitle option is available? Why does it default to None? I couldn't find a setting in Server or in the AndroidTV app related to this. English is the default, always English. 

4. When multiple subtitle languages are available: It always seems to select English Forced, and doesn't show any subtitle at all. To overcome this, I select a different English subtitle (non-forced or the SDH version). If one of those does not exist, I simply am not able to view the video with subtitles. The default selected English Forced is never shown (forcing me back to Kodi with Jellyfin in addon mode where both Forced or any other option does display fine). Is this a bug or somehow a misconfiguration?

### Application version

0.15.12

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android 11

### Jellyfin server version

10.8.10

**Comment by Dnkhatri** [comment]
try the latest beta version. I know some work has been on how subtitles work but not sure if they fix your problems

https://github.com/jellyfin/jellyfin-androidtv/releases

**Comment by MichaelRUSF** [comment]
1. I can't reproduce, subtitles look normal on the 4:3 content that I have.  

2. A stroke is a thin outline around the text. See item [one](https://documentarycameras.com/10-ways-make-subtitle-styles-readable/). 

3. On the server web interface. Click on the account profile (indicated by the yellow circle on the screenshot), then choose subtitles to access subtitle settings. In your case, I would choose "Always Play" for subtitle mode. 

    ![Server subtitle](https://github.com/jellyfin/jellyfin-androidtv/assets/78215956/fa019b85-6660-47f6-be8a-ec31e82d9103)

4. To clarify, forced subtitles are only for foreign dialogue in a movie, e.g., you’re watching a movie in English with Spanish-speaking parts. The forced subtitles will only have dialogue for the Spanish parts and no other parts of the movie. Forced titles being selected as the default is the correct action, hence the forced flag. 

Note currently the way subtitles are implemented, the server extracts them on the fly from the video file when selected, unless you have external subs. This extraction on the fly is not the best solution. The bigger the file the longer the process and the more likely for the extraction to fail/timeout. This could be why forced subtitles are not showing, but once again if it did extract correctly, there would only be a few lines of dialogue throughout the video. 

The developer is working on replacing the current custom subtitle rendering method with one that does not need to extract the subtitle file from the source file before being played. But that may be a while, my best advice is to use external srt files and rename them to match the video file name with the appropriate [flags](https://jellyfin.org/docs/general/server/media/external-files/).

**Comment by zilexa** [comment]
Thank you, but your explanations do not explain at all what I wrote.

1. Great that it works for you. But how do you explain the screenshot? I do not have this issue when playing using Jellyfin addon with Kodi. So the issue is not the MKV/SRT. Also note, as I mentioned, these are MKV with SRT files. Not embedded or subs within MKV. Separate files. Same filename. 
2. As I said, it doesn't matter what value I select. There is no visual difference. No thin line that gets bolder or thinner.
3. It's already set to Always Play.. still, the situation I explained applies. 
4. What i experience is not about foreign language. It's just native English shows that I prefer to watch with English subtitles. So clearly there is some kind of bug here. Why would I want forced? I just always want to have subtitles. I don't always need to have the volume up to be able to follow dialogue. I don't live alone.

**Comment by MichaelRUSF** [comment]
Sorry, I can't help your situation, just providing some information. 
1. The quality of that screenshot is very compressed and has a lot of artifacts, so it's hard to tell how bad the subtitles look vs the quality of the photo. 
2. Weird, I can clearly see a difference if I change the values of the stroke setting. Once again works for me situation. 
3. It works most of the time, not always.
4. The force flag is typically used for foreign dialogue or something that needs clarification, I'm not saying you're watching something in another language. If it's in the file then there is usually some scene that needs further explanation. For example, if there is a scene where someone is using sign language, the force subtitle track will only have dialogue for that scene. While the regular subtitle file will have dialogue for every scene. Without that clarification, the scene would not make sense, hence why it is forced and will be displayed as the default option. There is a flag in the subtitle track that indicates if the track is forced or not, Jellyfin does not mark anything as forced.
