### ISSUE TITLE
Switching between HDR10 and HDR10+ is not seamless

### ISSUE THREAD

**Issue by branches78** [jellyfin/jellyfin-androidtv#3104]
### Describe the bug

When I play a regular HDR10 video, my TV (Samsung Q65C) displays the HDR logo at its banner and when I play an HDR10+ video I also see the HDR10+ logo at the TV banner, the problem is, the app gets stuck in HDR10+ so when I play a regular HDR10 again the app sends the video as HDR10+ so the TV banner shows that logo instead of the HDR10 one.

I have to reboot the device in order to fix this problem.

I'm not having the problem with other apps I've tested.

You can test three videos from this link:

https://drive.google.com/drive/folders/1dJLrS_1ECJm9jyK6zgOCjuX-Mk4C1AnJ?usp=drive_link

### Application version

v0.16.0-beta.4

### Device information

Homatics Box R 4K Plus

### Android version

Android 12

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment]
Does this issue also happen with 0.15?

**Comment by branches78** [comment]
Yes, I just checked on 0.15.12 and it's the same, but I really wonder if this is an issue of the TV, the device, the app or all together, I don't have a device with a different OS to test in order to isolate the one causing this.

**Comment by branches78** [comment]
So I tested this on two devices, the Homatics Box R 4K Plus with Android 12 and the Onn 2023 with Android 12 as well, on both I am able to reproduce the problem, the question that remains is, could this be a global issue in Android 12, an issue in the Jellyfin app or an issue of the TV?, it's hard to know unless you know the answer.

**Comment by nielsvanvelzen** [comment]
I just checked and we never explicitly set a color mode in the app. It could be our video player that causes it so can you check a few things:
1) What video player is set in the preferences?
2) Does the issue also happen when you switch to the other player, and is the behavior exactly the same?

**Comment by branches78** [comment]
Hello,

> What video player is set in the preferences?

I always use Exoplayer.

Does the issue also happen when you switch to the other player, and is the behavior exactly the same?

I was wrong when I said that it was happening only on Jellyfin when the truth is it is happening even on Prime Video, so, do you still think this is something missing in the app like the color mode you mentioned or could this be an issue with Android directly?

**Comment by nielsvanvelzen** [comment]
Likely an issue with the platform.
