### ISSUE TITLE
Crash when pull back the video progress bar

### ISSUE THREAD

**Issue by user0818** [jellyfin/jellyfin-androidtv#3106]
### Describe the bug

1. normally watch video
2. pull back the progress bar
3. boom !!!  app crash

### Logs

---
client: Jellyfin for Android TV
client_version: 0.16.0-beta.4
client_repository: https://github.com/jellyfin/jellyfin-androidtv
type: crash_report
format: markdown
---
### Logs

***Stack Trace***: 
```log
java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jellyfin.androidtv.ui.presentation.MyDetailsOverviewRowPresenter$ViewHolder.setInfoValue3(java.lang.String)' on a null object reference
	at org.jellyfin.androidtv.ui.itemdetail.FullDetailsFragment$4.run(FullDetailsFragment.java:339)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6669)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:866)

```  
***Logcat***: 
```log
uid=10039

```  

### App information

***App version***: `0.16.0-beta.4` (`160004`)  
***Package name***: `org.jellyfin.androidtv`  
***Build***: 
```json
{"BOARD":"pig_chivalrous","BOOTLOADER":"123456789","BRAND":"XGIMI","CPU_ABI":"armeabi-v7a","CPU_ABI2":"armeabi","DEVICE":"pig_chivalrous","DISPLAY":"PPR2.180905.006.A1","FINGERPRINT":"MediaTek\/m7642_db\/m7642:9\/PPR2.180905.006.A1\/xgimi06191805:user\/release-keys","HARDWARE":"m7642","HOST":"xgimi","ID":"PPR2.180905.006.A1","IS_DEBUGGABLE":false,"IS_EMULATOR":false,"MANUFACTURER":"XGIMI Technology Co.,Ltd","MODEL":"XGIMI TV","PERMISSIONS_REVIEW_REQUIRED":false,"PRODUCT":"Product_belle","RADIO":"unknown","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":[],"SUPPORTED_ABIS":["armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1687169131000,"TYPE":"user","UNKNOWN":"unknown","USER":"xgimi","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","FIRST_SDK_INT":28,"INCREMENTAL":"v2.2.27","PREVIEW_SDK_INT":0,"RELEASE":"9","RESOURCES_SDK_INT":28,"SDK":"28","SDK_INT":28,"SECURITY_PATCH":"2019-10-01"}}
```  
***Build config***: 
```json
{"APPLICATION_ID":"org.jellyfin.androidtv","BUILD_TYPE":"release","DEBUG":false,"DEVELOPMENT":false,"VERSION_CODE":160004,"VERSION_NAME":"0.16.0-beta.4"}
```  

### Device information

***Android version***: `9`  
***Device brand***: `XGIMI`  
***Device product***: `Product_belle`  
***Device model***: `XGIMI TV`  

### Crash information

***Start time***: `2023-10-06T22:54:39.638+08:00`  
***Crash time***: `2023-10-06T23:44:58.637+08:00`  

### Application version

0.16.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

XGIMI projector

### Android version

Android 9

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Are the logs you shared complete? Normally the logcat part should contain a lot more information. Can you also try and give some more detail. Does this happen for all media you playback or only specific media? What kind of media is it (e.g. specific container/codec)? etc.

**Comment by pkroeze** [comment]
I think I got the same issue. the crash log send to the Jellyfin server is attached below

[Log crash.txt](https://github.com/jellyfin/jellyfin-androidtv/files/14261655/Log.crash.txt)

**Comment by nielsvanvelzen** [comment]
> I think I got the same issue. the crash log send to the Jellyfin server is attached below
> 
> [Log crash.txt](https://github.com/jellyfin/jellyfin-androidtv/files/14261655/Log.crash.txt)

Make sure your preferred media player is set to "ExoPlayer" in the app settings.

**Comment by pkroeze** [comment]
It was set to automatic, changed it into ExoPlayer without any changes in behaviour.
It happens when a tv show has been viewed and when I don't want to wait for the credits to end, click th back button, the screen turns dark with eventually a crash as result. 

[Crash Log 2.txt](https://github.com/jellyfin/jellyfin-androidtv/files/14277516/Crash.Log.2.txt)

**Comment by nielsvanvelzen** [comment]
From the logs it appears that your server is unresponsive when you quit the video player and the app fails to update some information due to a timeout, after exactly 15 seconds it tries to update a user interface element which fails because the episode/movie information was never updated. This then crashes the app.

I think this is unrelated to the issue the author was having but I'm working on a change that will at least prevent the crash. The main issue is on your server though, as it doesn't respond to the app.
