### ISSUE TITLE
External subtitles not loaded while playing direct 

### ISSUE THREAD

**Issue by johndhzd** [jellyfin/jellyfin-androidtv#3107]
### Describe the bug

External subtitles not loaded while playing direct using client decoding,
There is an option on Android phone app, client setting>allow SSA/ASS subtitles while direct play, but no such option on Android TV app 

### Application version

0.15.2

### Device information

Sony 2022 65

### Android version

Android TV 10

### Jellyfin server version

10.8.2

**Comment by nielsvanvelzen** [comment]
You're using an old version of both the app and the server. I'd recommend updating both to the latest version first and then retry.
If the issue still occurs I'd ask you to share more information (like the media information) so we can help figure out a solution.

**Comment by johndhzd** [comment]
So I tried upgrade both client to latest: v0.15.12 and 10.8.11, issue still exists.

**Comment by johndhzd** [comment]
I am willing to share all necessary logs if I know how to retrieve them.
