### ISSUE TITLE
Subtitle issue on beta 4

### ISSUE THREAD

**Issue by 404erreur** [jellyfin/jellyfin-androidtv#3111]
### Describe the bug

Hello,

Many thanks for this amazing app :)
I have a small issue with subtitle loading (with workaround)

If I launch an serie episode with next button from the serie page, I get a message that says: Impossible to launch subtitle.
No issue if I launch the episode from whiched episode page.

I hope I'am understable :)

Regards
404

### Application version

0.16

### Where did you install the app from?

Sideloaded APK

### Device information

nividia shield pro

### Android version

android 13

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment]
Did this also happen in 0.15 or just 0.16? Does it happen for all media or just specific media? Movies or series? What codecs are used? Which format are the subtitles in?

**Comment by 404erreur** [comment]
on 0.16 beta 4, inside serie and for all tested episode

**Comment by Ritchie1108** [comment]
> Did this also happen in 0.15 or just 0.16? Does it happen for all media or just specific media? Movies or series? What codecs are used? Which format are the subtitles in?这种情况是在 0.15 中也发生过还是仅仅在 0.16 中发生过？是所有媒体都会发生这种情况还是仅特定媒体会发生这种情况？电影还是连续剧？使用什么编解码器？字幕是什么格式的？

it is also happen in 0.15
