### ISSUE TITLE
Refresh rate switching doesn't switch back to normal refresh rate

### ISSUE THREAD

**Issue by chasewinnings391** [jellyfin/jellyfin-androidtv#3114]
### Describe the bug

1. Enable refresh rate switching
2. Start playing a video with a low frame rate, e.g. 24 fps.
3. Jellyfin changes the refresh rate of the tv to 24hz, as is expected
4. Stop playing the video
5. Jellyfin doesn't change the refresh back to its normal refresh rate, which is 60hz in my case. This leads to a jerky UI

### Application version

0.16.0

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia shield pro (2019)

### Android version

Android 9

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment]
Thanks for the report, issue should be fixed in the next beta.
