### ISSUE TITLE
Items on Views Section of TV Show Library Home Screen Cannot Be Focused or Selected (i.e. can't select "All Items")

### ISSUE THREAD

**Issue by MovieWiz** [jellyfin/jellyfin-androidtv#3118]
### Describe the bug

1. Open a TV Show library from the app's home screen
2. Navigate to the bottom of the library's home screen by pressing down button on the remote.
3. Notice that you cannot Focus/Highlight/Select the items in the Views section at the bottom.  This includes "All Items", "Genres" and "By Letter"

The inability to select "All Items" really limits the ability to access the content of the library.  If I want to start watching a new show in the library, my only work around so far is to search for it from the app's home screen and access the show that way.

Hope this helps.  I'm definitely a Jellyfin superfan.

### Application version

v0.16.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

Fire TV Stick 4K

### Android version

Fire OS 6

### Jellyfin server version

10.8.11 on Windows 11

**Comment by nielsvanvelzen** [comment]
When you press the down button on the dpad nothing happens and the item in the item in the "recently added" row stays selected?

I've tested with both Android TV (API 28) and my Fire TV (Fire OS 7) and can't reproduce the issue. But both of those options are newer then Fire OS 6.

**Comment by MovieWiz** [comment]
This is a lot like a previous bug I reported about "Thank you" notification for testing the beta which appeared near the top of the app's home screen.  The bug was that the notification "button" could not be focused and thus there was no way to dismiss it.

This behaviour is the same.  The 3 buttons never get the focus -- the focus remains on the last thing before the Views section.  When I get to the bottom, and I move right, I hear the click sounds as I move right twice and then hear the clicks again as I move left twice.  So it's like the app knows where the focus should be.  It's just that the button never actually gets the focus which means you can't select it with the OK button (I tried).

**Comment by MovieWiz** [comment]
In #2298, the following attributes were added to the notification card (a Textview) and it looks like that was to help with older Android versions.

    android:focusable="true"
    android:focusableInTouchMode="true"

**Comment by MovieWiz** [comment]
Oh, by the way, I remember that I have FIre Stick Lite (which is Fire OS 7) and I tested with that.  Problem did not occur.  The buttons could be focused and selected.  So, looks like this is a Fire OS 6 issue.  Unfortunately, the Fire Stick 4K is still a very popular device.

**Comment by MovieWiz** [comment]
I've gone back to 0.15.12 since the 3 buttons work in the 0.15.xx versions - the buttons were changed from graphical buttons to text-based in 0.16.xx.  I'll keep an eye out for any new releases (beta or otherwise) to test it out.  If I can help with testing in any other way, let me know (for example if you want a specific build tested before going wide).  Unfortunately, I don't have the tools/skill to grab the code and build it myself.  Maybe someday ...

**Comment by nielsvanvelzen** [comment]
Thanks for the additional information. I had to find some time to get a new emulator up-and-running with an older Android version, which I just did. I could reproduce and fix the issue so it should work again in the next beta!

**Comment by MovieWiz** [comment]
I'm no expert but it looks like Android 8 changed the default of the "focusable" attribute for Views to true.  So I guess this is why that the attribute has to be specifically set to true if Android 7 support is wanted.

On a page outlining changes in Android 8, I found this 

> **View focus**
> 
> Clickable View objects are now also focusable by default. If you want a View object to be clickable but not focusable, set the android:focusable attribute to false in the layout XML file containing the View, or pass in false to setFocusable() in your app's UI logic.
> 
on this page:  https://developer.android.com/about/versions/oreo/android-8.0-changes

**Comment by nielsvanvelzen** [comment]
In reality there are a lot more changes to focus handling not documented. The focusable attribute was already set to true (the leanback library does that) but the problem in this case was that the focus was sent to the child view and the parent didn't get notified. A behavior change that was not documented.
