### ISSUE TITLE
Profile distinction.

### ISSUE THREAD

**Issue by Darius82** [jellyfin/jellyfin-androidtv#3119]
### Describe the feature you'd like

I have two accounts created for home. One for me and one for my daughter. It would be nice to have something like the nick on top when there are 2 accounts or more logged in in the system.

That way I can see who is logged in at a glance.

**Comment by nielsvanvelzen** [comment]
The app already remembers the signed in users and you can differentiate them by setting a profile picture in the web client.

**Comment by Darius82** [comment]
Well, didn't think of that TBH, but it will do. 

I still think the option to show the nick would be nice but I'm fine with the avatar.

Thanks.
