### ISSUE TITLE
Changing Languages Crashes App

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-androidtv#312]
From u/nibill1d on [Reddit](https://www.reddit.com/r/jellyfin/comments/ezgy3q/new_android_tv_release_v0110_improved_video/fgoos8f):

“Did this also fix the bug that when you change the language, at first it doesn't change anything and if you try again the whole app crashes?”

**Comment by thornbill** [comment]
I would assume this is changing audio language during playback, but it is not entirely clear. I asked for verification on Reddit, but if anyone here knows, feel free to comment below!

**Comment by thornbill** [comment]
Further details provided on [Reddit](https://www.reddit.com/r/jellyfin/comments/ezgy3q/new_android_tv_release_v0110_improved_video/fh77b0m/).

> so this is what I do and how I got the error (strangely, not always)
> 
> My content usually has German and English as languages to choose from and the default language is German. Firstly, I try to change the language while media is playing, nothing happens and still German selected. Then I pause, change language again and it either crashes or nothing happens again. Then I resume the media (language hasn't changed) and try to change language again and then crashes.
> 
> I do this a few times and if I'm lucky it works after two or three tries. Worst so far was me trying to change the language for maybe 15min, then I gave up haha
