### ISSUE TITLE
Dolby Vision ignored when using Bluetooth headphones

### ISSUE THREAD

**Issue by RubenTeixeira** [jellyfin/jellyfin-androidtv#3120]
### Describe the bug

1. Play Dolby Vision video with TV speakers
2. Works fine.
3. Exit playback.
4. Connect Bluetooth headphones.
5. Play Dolby vision video.
6. Purple/Green when dovi only, otherwise, fallback to HDR10
7. Exit playback.
8. Disconnect headphones.
9. Restart playback and works fine, even if connecting headphones in the middle of the video.

### Application version

0.16.0-beta.4 but same behaviors on current stable

### Device information

Sony A84J ATV

### Android version

Android 10

### Jellyfin server version

10.8.11

**Comment by innocentDE** [comment]
Same issue. Order of turning tv speakers on and and then Bluetooth does not matter in my case.
