### ISSUE TITLE
Unwatched filter slow to loat (>5sec per batch of 25 thumbnails)

### ISSUE THREAD

**Issue by meuter** [jellyfin/jellyfin-androidtv#3121]
### Describe the bug

- open app
- go to TV show library (>200 TV shows)
- filter by unwatch
- wait >5 secs for first batch of thumbnails to load
- scroll down to the end of first batch
- wait another >5 secons for second batch of thumbnails to load
- etc.
 
reopening the apps (hoping that this would be cached somehow) does not help

### Application version

0.15.12

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 

### Android version

Version: 11 / SHIELD Android TV SW Version: 9.1.1

### Jellyfin server version

Version: 10.8.11 / Operating System: Linux / Architecture: X64

**Comment by meuter** [comment]
I created this one following the recommendation in #3073 to use the provided template.

**Comment by nielsvanvelzen** [comment]
This is likely a server issue. Is the unwatched filter in the web interface also slow for you?

**Comment by meuter** [comment]
Since I maintly use jellyfin on my TV, I had not used the web UI much. But indeed, I just checked: activating the unwatched filter in the webui result in the same 5 seconds delay. I checked the docker logs, and I see this trace which seems to indicate that the server is slow to responds:

```
[15:02:01] [WRN] [39] Jellyfin.Server.Middleware.ResponseTimeMiddleware: Slow HTTP Response from https://<redacted>/Items/Resume?Limit=12&Recursive=true&Fields=PrimaryImageAspectRatio%2CBasicSyncInfo&ImageTypeLimit=1&EnableImageTypes=Primary%2CBackdrop%2CThumb&EnableTotalRecordCount=false&MediaTypes=Audio to <redacted> in 0:00:00.511674 with Status Code 200
```

I guess I'll open an issue on https://github.com/jellyfin/jellyfin then. Thanks!

**Comment by meuter** [comment]
For anyone stumbling on this issue this issue seems to be relevant: https://github.com/jellyfin/jellyfin/issues/9091
