### ISSUE TITLE
PLZ help

### ISSUE THREAD

**Issue by BlackDiamondtm** [jellyfin/jellyfin-androidtv#3125]
### Describe the bug

User access
Access to media library [YES]
Device Access [YES]

One network for example 3G/4G/ADSL
mobile application on the phone no problem, everything works
Android TV box (any) go to the application
We enter the IP address, the next step is to enter the login and password, we get to the server and it is empty, not a single cartoon, not a single movie, or anything

We haven’t changed anything, we connect to the home network 192,168,0,0
Jelly server 192,168,0,1
Mobile phone 192,168,0,2
TV box 192.168.0.3
Everything is super everything works

### Application version

0.14

### Where did you install the app from?

Google Play

### Device information

any

### Android version

android 

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Update the app to the latest version. 0.14 is way outdated and not supported anymore.

**Comment by BlackDiamondtm** [comment]
Nothing's changed.
