### ISSUE TITLE
Unable to Play Video with .ASS Subtitles

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-androidtv#313]
From u/PixelDew on [Reddit](https://www.reddit.com/r/jellyfin/comments/ezgy3q/new_android_tv_release_v0110_improved_video/fgstc8d/):

> Ever since the update, my devices don't play files on mpv correctly. I also get an error about duration and then it skips the file. Before the update i could use MPV as an external  player for .ASS subtitles and everything would work well! is there a workaround for this?

> On my firestick, after the update, the ui hasn't changed (not sure if its a problem) but i cant play anything using mpv, it gives me the error "The item didn't appear to play as long as its duration." If i attempt to let it automatically choose a player, it says "Player error encountered" a few times, then stops the playback due to too many error.
>
>On my android phone, The new UI is present, but it wont even let me use mpv as an external player, and if i use the default it plays the file alright.
>
>Overall, as i only use my firestick, this update has made most of my library unusable :/

**Comment by anthonylavado** [comment]
From u/linetrimmer (same thread):
> I’m having the same issue with files with .ass subtitles. Used to be able to use mx player, now it says can’t play this link. Exoplayer tried to play it but then says error and retries a couple times and exits. Reverting to 10.2 and everything’s fine

**Comment by anthonylavado** [comment]
From u/PixelDew (same thread):
Yep, after sideloading MPV again, sideloading the latest version of jellyfin, I finally tried the Nov 9th version and everything works again on the firestick! Thanks!

>I hope it's fixed in the upcoming update, because MPV seems like the only player that supports h.264 10 bit with .ASS subtitles. Looking forward to the UI update too! :)

**Comment by PixelDew121** [comment]
I only tested two files, so i can't say if .ASS subtitles are the reason behind this, but both of them work through MPV in the previous version, and the non 10 bit file works with the default player in the old version.
[File 1](https://pastebin.com/9Uc1QcAz)
[File 2](https://pastebin.com/NhXVszjS)

**Comment by linetrimmer** [comment]
It’s pretty much all of my anime files that I’m experiencing this issue with. The issue is present in 10 bit, 8 bit, h264, and hevc files, so the only constant that I’m seeing is the subtitles. 

When MX Player attempts to play the file, it loads for a few seconds before saying, “Can’t play this link.” The same file plays in MX Player with no issue in 10.2 and prior versions.

I’ve tested the files on 11.0 and 11.1, and the issue is present in both—reverting back to 10.2 is the only way the files will play.

**Comment by thornbill** [comment]
@nielsvanvelzen could this be caused by the change to the profile here? https://github.com/jellyfin/jellyfin-androidtv/pull/214

**Comment by nielsvanvelzen** [comment]
> @nielsvanvelzen could this be caused by the change to the profile here? #214

That PR actually fixed ASS and SSA playback for me by forcing transcoding/baking the subs in the server. ExoPlayer has some basic support for those subtitle formats (but no styling etc. so it will almost always break).

Now that I look at the PR I do however notice I changed the options from `getExternalProfile` which I now know is for external player. Reverting line 142 and 143 _might_ fix the issue.

**Comment by linetrimmer** [comment]
> Now that I look at the PR I do however notice I changed the options from `getExternalProfile` which I now know is for external player. Reverting line 142 and 143 _might_ fix the issue.

Making this change in the 11.2 build did fix it for me.

**Comment by AndreasGB** [comment]
Nice, do you want to submit the PR for it? :)

**Comment by linetrimmer** [comment]
Done! #395
