### ISSUE TITLE
Direct playing problems

### ISSUE THREAD

**Issue by Guru1-228** [jellyfin/jellyfin-androidtv#3147]
### Describe the bug

All information about problem here https://github.com/jellyfin/jellyfin/issues/10458#issue-1956788292 and here https://github.com/jellyfin/jellyfin/issues/10450#issue-1955826760

Direct playback doesn't work for me, but remixing works perfectly, I don't need re-encoding, but it plays some files directly
Please add the ability to choose to force playback through either remixing or transcoding, this would solve a huge number of problems not only for me, but also for many other users whose TV capabilities were incorrectly determined
*I don’t want automation to always decide for me how to play files
Maybe you can add forcing remuxing

### Application version

0.16.0-beta.5

### Where did you install the app from?

Google Play

### Device information

TCL 43P745

### Android version

Android TV 11 kernel 4.14.198+

### Jellyfin server version

10.8.11

**Comment by Guru1-228** [comment]
So what you think about it?

**Comment by nielsvanvelzen** [comment]
You've linked an open issue in the server repository so I'll close this one as a duplicate. Please don't open multiple issues as it doesn't help us with helping you.

**Comment by Guru1-228** [comment]
But it's not duplicate, in server's issue developer says me open issue in tv repo
