### ISSUE TITLE
Sorting not working on Zidoo Z9X (standard, not Pro)

### ISSUE THREAD

**Issue by martinstraka8282** [jellyfin/jellyfin-androidtv#3157]
### Describe the bug

1. Go to library of content (ie: Movies folder)
2. Click on sorting options and pick any one (ie: last played or date added)
3. Scroll down 4 or 5 pages and note movies in rows
4. If you change the sorting option, you will note that after row 4 or 5, the movies sort in the same order no matter what sorting option you select or how many times you change it. If you force close the app, it seems like you can get it to sort one category correctly the first time, then it goes back to the same behavior if another sorting option is selected.

Instead, I expect it to sort based on the option selected, like the date last played, alphabetical, etc. This same app on my Nvidia Shield does not display this behavior and does sort correctly. While you'll note that I am on beta firmware for the Zidoo Z9X, users on the latest 6.4.42 regular zidoo firmware confirmed the same behavior. Trying the newest Jellyfin Android TV beta firmware 0.16.5 did not solve the issue.

### Logs

N/A

### Application version

0.15.12

### Where did you install the app from?

Sideloaded APK

### Device information

Zidoo Z9X

### Android version

9.0

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment]
I'm not entirely sure what you're trying to report. Are you saying that sorting is just not working or only in some specific cases? Have you tried the latest 0.16 beta version?

> 6.4.62 beta (Also reported by users on 6.4.42 non beta)

Please specify the actual Android version

**Comment by martinstraka8282** [comment]
Sorry Niels, I mistakenly put my Zidoo firmware version in that slot. The android version is 9.0.

When navigating a library, the sorting is only working correctly for the first 4 or 5 rows of titles. It's completely broken after that. No matter what sorting option you select (alphabetical, date added, last played, etc.), it shows the same movies in the same order after those first few rows.

So, out of my movie library of 3500 titles, I can only sort the first 30 or so with the sorting options, and the rest all just appear in the same order after those, no matter what sorting option I select.

**Comment by MichaelRUSF** [comment]
I was able to reproduce this on the 0.16.5 beta; server version 10.8.11. First, you need to have a grouped movie library. Second, you have to view the movie library in a vertical grid direction. Third, you need to apply a sorting method, e.g., date added. Fourth, observe that the first 25 items will be sorted correctly, everything after that is displayed in alphabetical order. 

If the folder is ungrouped or if you change the grid direction to horizontal, then sorting works as expected. This seems to be related to [these](https://github.com/jellyfin/jellyfin/issues/7959) [issues.](https://github.com/jellyfin/jellyfin/issues/10384)

**Comment by nielsvanvelzen** [comment]
Grouped items are unfortunately broken on the server side, so there's nothing we can do on the client to fix that problem. Can you confirm if your library is also using grouped items @martinstraka8282?

**Comment by martinstraka8282** [comment]
@nielsvanvelzen Yes, numerous folders for each category (for unavoidable reasons I won't bore anyone with), and that does appear to be the issue. I was able to replicate the issue on my Nvidia Shield tonight as well, so I was incorrect that it was working fine on that device. Thanks for your help.
