### ISSUE TITLE
Allowing pre-rolls to run on TV shows

### ISSUE THREAD

**Issue by dheian** [jellyfin/jellyfin-androidtv#3167]
### Describe the feature you'd like

I'm using the new fork of the pre-roll plugin: https://github.com/BrianCArnold/jellyfin-plugin-intros

I've noticed that mobile Android Jellyfin app will display pre-rolls before the TV shows, but the Android TV app (I'm using the Chromecast with Google TV) will not. Is there a way the app can call the pre-roll plugin for TV shows? It's making the plugin call for movies just fine.

**Comment by nielsvanvelzen** [comment]
Duplicate #2787
