### ISSUE TITLE
BrowseGridFragment doesn't feel native to the app because of wrong scroll direction

### ISSUE THREAD

**Issue by rlsmntr** [jellyfin/jellyfin-androidtv#317]
For app continuity the media scrolling is wrong.  Web and phone currently scroll up and down while the Android TV app scrolls side to side.  most of the UI currently scrolls up and down so jumping into all content it should go up and down as opposed to side to side.

**Comment by AndreasGB** [comment]
Hi @rlsmntr, to which screen are you referring and could you elaborate please?

**Comment by rlsmntr** [comment]
Thanks for getting back to me! the two screens I am referencing are when you select for instance My Media >> Movies (or TV) >> ALL .  At that point the navigation pulls up all the movie posters and it goes into a grid view where you navigate left to right and only down 4 rows.  It doesn't feel like there is continuity between the app and the web/phone in this area.  I also opened up a few more ui enhancement requests that should bring the feeling close.

**Comment by AndreasGB** [comment]
Ah yes, this is an old screen we inherited. At some point it will very likely be replaced completely, but we are currently busy tackling another ugly screen which is the item details. If you are curious about progress there, feel free to check out #269.

I'll also adjust the title of this issue to reflect which screen is meant.
