### ISSUE TITLE
Installation fails on Google TV

### ISSUE THREAD

**Issue by crockpotveggies** [jellyfin/jellyfin-androidtv#3177]
### Describe the bug

1. Sony Bravia Google TV
2. Install Android TV app from Play Store
3. Download 100%
4. Install fails, even after restart and multiple attempts
5. 
![image](https://github.com/jellyfin/jellyfin-androidtv/assets/1445295/1548cc8c-b27d-4144-b858-240872336fbe)

### Logs

Unsure how to collect installation logs on this device, instructions welcome

### Application version

Latest

### Where did you install the app from?

Google Play

### Device information

Sony Bravia 4K VH2 KD-75X85J

### Android version

Android 10

### Jellyfin server version

10.18.12

**Comment by crockpotveggies** [comment]
```
➜  ~ adb install Downloads/jellyfin-androidtv-v0.15.12-debug.apk
Performing Streamed Install
adb: failed to install Downloads/jellyfin-androidtv-v0.15.12-debug.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
```

ADB got me a more descriptive installation error - insufficient space. Closing.

**Comment by jmatthewturner** [comment]
Thanks for reporting back with the answer! Had the same issue, same resolution.
