### ISSUE TITLE
Web version toggle

### ISSUE THREAD

**Issue by GrabbenD** [jellyfin/jellyfin-androidtv#3179]
### Describe the feature you'd like

Majority of new streaming devices (such as NVIDIA Shield) use Android TV as the operating system.
These devices can handle the web version of Jellyfin.
However, the app is currently hardcoded to use its own native design which severely limits the customization.

Allowing the client to use the web version would give greater customizability and a consistent UI experience since Jellyfin Server can serve a custom `--webdir` which the desktop clients can already utilize (such as Jellyfin Media Player on Linux).

**Comment by nielsvanvelzen** [comment]
There are no plans to use the web client on Android TV. Quoting myself from a [forum post](https://forum.jellyfin.org/t-androidtv-as-webapp):

> - We already have a fully native app that is actively being worked on
> - A lot of Android TV devices don't get frequent update and thus have outdated webviews making it hard to support
> - A lot of Android TV devices have low specifications making webapps slow
> - The video/audio player still needs to be implemented natively to avoid transcoding as much as possible, this component is also the one that needs the most work.
> - Eventually the mobile Android app will also be fully native

**Comment by nielsvanvelzen** [comment]
Install a web browser

**Comment by GrabbenD** [comment]
Codecs support is awful with web browsers 🙁 

Maybe it's more worthwhile to compile a app (like Flutter) with WebView? (Although I'm concerned that might introduce another issue with missing client settings which means the app wouldn't use the right media player (ExoPlayer) thus result in missing codecs?)
