### ISSUE TITLE
Option to skip the BrowseViewFragment when selecting a media library

### ISSUE THREAD

**Issue by rlsmntr** [jellyfin/jellyfin-androidtv#318]
Allow a setting to have media library take you to "all" instead of the middle screen where you scroll to the bottom and select all.

**Comment by AndreasGB** [comment]
Are you referring to this screen that you would like to skip?

![image](https://user-images.githubusercontent.com/8351447/74089430-6735f180-4aa1-11ea-8003-bcee9771fc5b.png)

**Comment by rlsmntr** [comment]
This option would skip that screen.  Instead of going My Media >> Movies (that screen) >> ALL it would jump to the Movies ALL screen.  Would apply to all media folders obviously movies,tv etc.  Thats currently how the web app functions along with the phone.  Which feels natural to me.  Current way kind of tosses the continue and watching twice at you.  once on the home screen and then once at that screen.

**Comment by AndreasGB** [comment]
Okay, thanks for clarifying. As said in the other issues I will adjust the title a bit.

**Comment by nielsvanvelzen** [comment]
Like @leocaseiro says, this feature already exists. Closing the issue.
