### ISSUE TITLE
Android Tv - Searching slow, often causes multiple pages to open, or crash

### ISSUE THREAD

**Issue by ryadre** [jellyfin/jellyfin-androidtv#3181]
### Describe the bug

Click in Movies
Click Search
Start typing
Page starts to flicker every few seconds as it is minimizing the amount of results
If you click the show you want too early it causes the page to refresh again, and again each time you click
Sometimes if you make it to the movie page you want, there is ghosting/overlays of multiple copies of the page you are looking at

I feel as though as it is trying to search and reduce the results after each letter you type causes some of the problem? Might be better to have to click the search button after you have finished typing which then starts the search?

### Application version

0.15.12

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019, 2017 and 2015

### Android version

Android 11

### Jellyfin server version

Latest stable

**Comment by nielsvanvelzen** [comment]
Does this also happen with the current beta for 0.16?

**Comment by ryadre** [comment]
> Does this also happen with the current beta for 0.16?

Installed v0.16.0-beta.5 and the search problem appears to be fixed thanks. Hopefully my Next Up continues to load, as I have been having issues with it loading up on both Android TV and Android phone app

**Comment by nielsvanvelzen** [comment]
Good to hear it's working now. Closing as fixed.
