### ISSUE TITLE
Abnormal stop of playback in live TV.

### ISSUE THREAD

**Issue by Ritchie1108** [jellyfin/jellyfin-androidtv#3186]
### Describe the bug

When I use Jellyfin to play live TV (m3u), any channel will stop playing and return to the channel list after about 5 minutes. There is no problem when I use the same playlist to play with IINA.

### Application version

v0.16.0-beta.5

### Device information

ccwgtv 4k

### Android version

android 12

### Jellyfin server version

10.8.9

**Comment by alxgarci** [comment]
Still happening on Android TV app after maybe 30 secs live tv channel playing in devices disappears and channel errors, working fine on Android phone an Web though.
