### ISSUE TITLE
System Screensaver Starts During Playback

### ISSUE THREAD

**Issue by bobobado** [jellyfin/jellyfin-androidtv#3193]
### Describe the bug

I disabled the Jellyfin screensaver to use the Shield TV Pro's system screensaver instead of the built-in Jellyfin option. Even when content is playing, the screensaver will activate at the system set 5 minute interval. Using the Jellyfin screensaver seems to resolve. I'd prefer to use the system setting as I have an OLED and the Jellyfin has static icons, time, etc. 

### Application version

v0.16.0-beta.5

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield TV Pro 2019

### Android version

Android TV version 9.1.1(33.2.0.157)

### Jellyfin server version

10.8.12

**Comment by nielsvanvelzen** [comment]
Did you change the preferred video player from ExoPlayer to something else?

**Comment by bobobado** [comment]
I am using the ExoPlayer

**Comment by nielsvanvelzen** [comment]
Thanks for the report. This will be fixed in 0.16.1.

**Comment by bobobado** [comment]
Thank you so much for all you do!

**Comment by bobobado** [comment]
Hello. I uninstalled the beta and upgraded to the latest stable version and this issue is persisting. Please let me know if you'd prefer I create a new bug ticket. 

Than you

**Comment by nielsvanvelzen** [comment]
Did you update to the latest development version? 10.6.1 is not released yet

**Comment by bobobado** [comment]
Well that would explain it. I really apologize for the confusion.

**Comment by bobobado** [comment]
Just wanted to say thanks! The new app with this fix works great!
