### ISSUE TITLE
Next Up Thumbnail Always Episode Even When Prefer Series Checked

### ISSUE THREAD

**Issue by linkRace** [jellyfin/jellyfin-androidtv#3195]
### Describe the bug

Go to Settings => Customization => Prefer Series Thumbnails
Next Up List uses Episode Thumbnail regardless
Not sure if this a bug or I'm just missing a setting somewhere.
I do see Show Next Up Without Thumbnail in Playback, but that seems to be for when you are finishing one episode going into another. I'd like it for the homescreen like it is on web/Windows
For what it's worth, I was on the latest stable before trying the beta and it was the same there as well.
**Android TV**
![20231130_155807](https://github.com/jellyfin/jellyfin-androidtv/assets/1369963/3b3d6999-3396-4cac-b11e-3e5615a6b9a1)

**Windows**
![image](https://github.com/jellyfin/jellyfin-androidtv/assets/1369963/8ef8a6d8-ad39-49a9-8ed1-931f2670b93c)

### Application version

0.16.0-beta5

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield Pro (2019)

### Android version

Android 11

### Jellyfin server version

10.8.5

**Comment by Aepx** [comment]
Just to add, seeing the same behavior on 0.16.0 from the app store and also on the web version.

**Comment by nielsvanvelzen** [comment]
The preference does not affect the "next up" row so it is working as intended.

**Comment by Aepx** [comment]
Maybe on the app, but the option on the web literally says "Use episode images in 'Next Up" and 'Continue Watching' sections.

**Comment by mattague** [comment]
As of Web Version `10.10.7 (f4b8aa0ed)` and Android TV Version `0.18.8` this works on the web but not on Android TV.
