### ISSUE TITLE
Jellyfin, Fire TV Sticks, Server Unavailable - "Unable to respond to udp request because the local ip address could not be determined."

### ISSUE THREAD

**Issue by evoelise** [jellyfin/jellyfin-androidtv#320]
I have been using Jellyfin 10.4.3 running on a Ubuntu 18.04 VM, viewing using browsers on couple of PCs and a couple of Fire TV sticks for over a year now with no problems.

But now, this week, the 2 Fire TV sticks have both stopped working, when I launch the fire stick Jellyfin app it asks me to select a server and I select the JellyFin server (the FireTV stick shows correct hostname and port) but this just comes back with the message "Server Unavailable".

When I do this I see the warning `[WRN] Unable to respond to udp request because the local ip address could not be determined.` in the JellyFin logs several times.

Using a browser from my PC to attach to the JellyFin server still works fine. I can see and ping the IP name and address on the JellyFin. I can ping the two Fire TV sticks. These are all on an internal network on the same subnet. 

The only change I have made recently was to move the media to an UNRAID server from a Windows File server. But I don't think this is the problem as I can still view all the media from the PC browser fine.

Things tried; restarting FireTVSticks, restarting JellyFin server, restarting VM, restarting ESX hypervisor host, restarting network switch, reinstalling JellyFin app on one of the FireTVSticks. None of this has worked.  

What would cause the `Unable to respond to udp request because the local ip address could not be determined.`? The Fire TV Stick can obviously be seen by the JellyFin server as it gets the UDP request, but why can't it determine its local IP?

**Comment by Artiume** [comment]
Would you mind upgrading to nightly to verify bug?

**Comment by evoelise** [comment]
> Would you mind upgrading to nightly to verify bug?

Do you mean upgrade JellyFin to nightly or JellyFin-Andriod client? I can do the former but if the later do you have instructions on how to upgrade the FireTV stick to a given release?

**Comment by evoelise** [comment]
Guessing you meant upgrading the JellyFin server to nightly.

I have done this but the FireTV sticks are still not working. However now the JellyFin server shows no log message at all when the FireTV sticks try to connect.

**Comment by Artiume** [comment]
Ok, with unraid, are you using docker?

**Comment by evoelise** [comment]
No, I have the JellyFin Server v10.4.3 running on a full Ubuntu 18.04 O/S.

It is just the media that resides on the Unraid server.

**Comment by Artiume** [comment]
In network settings, what network mode do you have? Set it to disabled

**Comment by evoelise** [comment]
I have it set to "Preferred but not required". I have set it to "Disabled" now but the FireTV sticks still can not see the server.

**Comment by Artiume** [comment]
You have to restart jellyfin to make the changes take effect

**Comment by evoelise** [comment]
After setting Secure Connection Mode to "Dsiabled" I have restarted the Jellyfin server, the FireTV stick and the JellyFin Andriod client. It is still not working.

**Comment by Artiume** [comment]
Hm... What about ipv6? Is there anything else in your network settings?

**Comment by evoelise** [comment]
What about IPv6 as far as I know it's not in use here, the FireTV sticks appear to only use IPv4? I have turned off IPv6 on the Jellyfin server just in case and restarted but it is still not working.

**Comment by Artiume** [comment]
remove the base url

**Comment by evoelise** [comment]
I have removed the base URL, it is still not working.

**Comment by Artiume** [comment]
@nielsvanvelzen @thornbill you guys have any ideas? I'm fresh out. Like 5 ideas ago 😅

**Comment by thornbill** [comment]
Did you restart the Jellyfin server after removing the base url? I believe any changes to the network settings require Jellyfin to be restarted to take affect. Having base url set does break the autodiscovery on 10.4.x because the server address returned does not include the base url.

**Comment by evoelise** [comment]
I did restart the server yes.

I created a new VM from a fresh Lubuntu 18.04 install, fully updated and reinstalled Jellyfin. Server discovery on the FireTV stick now works and I now see both servers. But now I'm stuck on the next part - when I select a server it the Android app asks me to "Select User" but there are no users to select.

**Comment by thornbill** [comment]
:+1: Thanks for confirming. I am glad you got it working although I am still curious what was causing your issue initially. I have not seen that error before.

As far as being able to view users, for improved security defaults the users are hidden by default. You can manually enter them in the app or change that setting in the server's admin dashboard. https://jellyfin.org/docs/general/server/users/adding-managing-users.html#additional-options

I am going to close this since your initial issue seems to be resolved, but feel free to continue the discussion or open a new issue if you continue to have questions or problems!

**Comment by mlaggner** [comment]
well, this security feature just cost me about 3 hrs of research on my FireTV stick. Would be at least helpful if there is a text field to enter user names per hand on the FireTV app... (android worked oob)

**Comment by nielsvanvelzen** [comment]
You can manually enter users, there is a very big button for that.

**Comment by mlaggner** [comment]
this is everything i get on the latest Jellyfin app from the Amazon store if there is not at least 1 user available which is not hidden:
![PXL_20210405_080005028](https://user-images.githubusercontent.com/1523778/113552298-42ca9c00-95f6-11eb-961b-ac5fe1fb04ba.jpg)

and if I choose the server which is provided from auto discovery, I only get "Server unavailable"
