### ISSUE TITLE
(Exoplayer) Wrong channel order for OPUS 5.1 / 7.1 audio tracks

### ISSUE THREAD

**Issue by johnmolina** [jellyfin/jellyfin-androidtv#3203]
### Describe the bug

See https://github.com/google/ExoPlayer/issues/8396

This bug affects all Android devices. To fix it Jellyfin Android / Jellyfin Android TV / Jellyfin Fire TV need an update to their Media3 / ExoPlayer components when the bugfix becomes available.

https://github.com/google/ExoPlayer/commit/f73bd6ee28bc4fd54fef76d33d15ab03744b3010

### Application version

0.15.12

### Device information

All Android based devices

### Android version

All

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
We will migrate to androidx.media3 in 0.17.

**Comment by nurunet** [comment]
I think I have this issue with Jellyfin on a Chromecast with Android TV. Exoplayer plays OPUS dialogue mainly on the front right speaker. LibVLC does not output any sound for the same file. MX Player (as external player) does seem to play OPUS correctly (or at least pass it on correctly to my AV-receiver).

Do I understand correctly that 0.17 should fix this? Until then I can use the WebOS app on my LG TV. That one handles it correctly too (but unfortunately doesn't like PGSUB subtitles).

**Comment by nurunet** [comment]
I just saw that I am on 0.16.4, which I now saw is supposed to have "Replace ExoPlayer with androidx.media3" backported.

My setup:
- LG OLED65BX6
- Denon AVR-X2800H w/ 5.1 speaker setup
- Chromecast w/ Google TV (connected to AVR)

I checked again. A file with OPUS 5.1 audio played only on the front left and right speakers, with all dialogue coming from the right side.

Then I switched off the TV (the Chromecast stays connected to power, so it is not really switched off) and - just after - realized I could check more detailed info of the audio stream on the AVR's overlay.

I restarted the TV, and suddenly sound was playing from the correct speakers. Unfortunately, the video playback was a bit "jerky", as if it froze for a tiny moment after every few frames.

I decided to reboot the Chromecast. Now, video playback looks good again, but audio is back to playing from the wrong channels.

This time, all speakers play something, but voice still seems to come (nearly?) exclusively from front right.

Should I open a new issue?

**Comment by MichaelRUSF** [comment]
The current release, 1.2.0, of Androidx Media3 does not contain the fix. It will be part of the next bugfix, 1.2.1, which has not been released yet.

**Comment by nurunet** [comment]
> It will be part of the next bugfix, 1.2.1, which has not been released yet.

Thank you.

**Comment by johnmolina** [comment]
Androidx Media3 1.2.1 with the fix for this bug has been released.

https://github.com/androidx/media/blob/release/RELEASENOTES.md
