### ISSUE TITLE
https with TLSv1.3 not working

### ISSUE THREAD

**Issue by LarsBel** [jellyfin/jellyfin-androidtv#3219]
### Describe the bug

Try to connect a Server that allows only TLSv1.3

The App does not connect to a jellyfin Linux Server behind an NGINX with TLSv1.3

It only reports "Handshake failed"

Changing the NGINX to allow also TLSv1.2, it works

### Application version

0.16

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Stick

### Android version

latest Fire OS 

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
Amazon doesn't support TLS 1.3. See #2588 / #777.
