### ISSUE TITLE
Playback Controls Enhancement 

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-androidtv#323]
Currently on the Fire Stick (not sure for other atv devices), if you click the center action button, it will pause the video stream. If you click left or right, it brings up the menu. 

Could we change it to where the center action button brings up the menu (so double click to pause), left and right respectively skip back and forward.

**Comment by nielsvanvelzen** [comment]
Did you test this with #251?

**Comment by Florianisme** [comment]
That isn't implemented in my PR I think. At least I haven't tried it yet

**Comment by nielsvanvelzen** [comment]
Hmm.. On my remote the left and right buttons on the dpad will seek the video while up & down show/hide the controls (in the old overlay).

I just looked at the code and there is literally a statement that disables that functionality for FireTV.. 

https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/CustomPlaybackOverlayFragment.java#L656

**Comment by Artiume** [comment]
> Did you test this with #251?

No, not yet. I haven't tested building the other clients yet, just the main web ui. What's the time line looking for 251 being implemented? I can hold back UI feedback if the current layout is deprecating soon.

> I just looked at the code and there is literally a statement that disables that functionality for FireTV.. 

Haha, why is that there? So I was looking at the rest of that code, L665, do you think that we should that pull from server instead of being hard-coded?

**Comment by nielsvanvelzen** [comment]
> What's the time line looking for 251 being implemented?

We're aiming to merge #251 very soon and release it in the next update (0.12) together with a lot of other UI updates.

>  I can hold back UI feedback if the current layout is deprecating soon.

Feel free to comment on the open PR's that contain screenshots

> Haha, why is that there?

¯\\_(ツ)_/¯

> So I was looking at the rest of that code, L665, do you think that we should that pull from server instead of being hard-coded?

What exactly do you want to pull from the server?

**Comment by Artiume** [comment]
I could've sworn there was a setting in the dashboard that allowed you to control it but I can't find it. it might be in AndroidTV that I'm thinking of. Default had skip back of 10 seconds and skip forward was 30 seconds.

**Comment by nielsvanvelzen** [comment]
I found it under "Playback" in the web client. Might be worth adding at some point, but that's a separate issue.

**Comment by Artiume** [comment]
Yeah could make it the global across everything and then allow you to customize the times for each device/device type. Just food for thought

**Comment by mueslimak3r** [comment]
should be fixed by:
#1291
#1207

**Comment by nielsvanvelzen** [comment]
Closing as fixed, please let us know if you're still experiencing this issue.
