### ISSUE TITLE
Display Timeout Never Occurs

### ISSUE THREAD

**Issue by rocket4321** [jellyfin/jellyfin-androidtv#3230]
### Describe the bug

Previously to jellyfin-androidtv.0.16 release, the app display would timeout after a long period of no user interaction. This allowed a TV to auto-turn off when no user input was received and the app discontinued any output video.

However, with 0.16, the display will never alter and will remain on indefinitely with no screensaver option enabled. With the screensaver, random images from the library are displayed, but the display still remains operational indefinitely.

Restore or allow a user option for display timeout to restore the display timeout functionality after no user interaction for an extended time period.

### Logs

N/A

### Application version

0.16.0

### Where did you install the app from?

Google Play

### Device information

NVidia Sheild

### Android version

Current

### Jellyfin server version

latest

**Comment by nielsvanvelzen** [comment]
It is not possible to have the screen dim automatically when using the in-app screensaver so you need to turn it off in the app preferences.

**Comment by rocket4321** [comment]
Yes, the screen does not timeout with the scrrensaver off (or on) in 0.16

**Comment by nielsvanvelzen** [comment]
Does that also happen in other apps? Have you tried re-opening the Jellyfin app?

**Comment by rocket4321** [comment]
I reboot the device, and now a timeout occured after about 15 min. I don't know why it never triggered all last night. Thanks so much for support, time, and all your excellent work. Closing issue.

**Comment by rocket4321** [comment]
This issue still occurs, and the display often will not auto dim on my device. If I exit the jellyfin app, the display will properly timeout. Otherwise, after playing a selected video in jellyfin, the display will remain on indefinitely and never turn off... unless I exit the jellyfin app.

**Comment by rocket4321** [comment]
Resolved in 16.1
