### ISSUE TITLE
Episodes not showing on android tv app

### ISSUE THREAD

**Issue by languagemaniac** [jellyfin/jellyfin-androidtv#3239]
### Describe the bug

1. create a "shows" library
2. add some episodes to it, mines are mkv files
3. perform a scan of the library
4. try and open the shows folder on the android tv app, there's nothing there in my case. Can only access the files through the "recently added in "shows" " row

In the web interface or regular android app, when I open the shows folder, I have to click on "episodes" to see them. Looks like I can't do that on android tv, there is no option.

### Application version

0.16.0

### Where did you install the app from?

Sideloaded APK

### Device information

Xiaomi mi box 4

### Android version

Android 9

### Jellyfin server version

10.8.13

**Comment by thornbill** [comment]
Sounds like you might not be following a supported folder structure: https://jellyfin.org/docs/general/server/media/shows

**Comment by languagemaniac** [comment]
> Sounds like you might not be following a supported folder structure: https://jellyfin.org/docs/general/server/media/shows

You are right. Didn't see that. Closing the issue now
