### ISSUE TITLE
Tries to load subtitles when It shouldn't. Errors out, then lets me select the subtitle track

### ISSUE THREAD

**Issue by languagemaniac** [jellyfin/jellyfin-androidtv#3240]
### Describe the bug

1. Add a tv show episode that has at least one subtitle track (don't know if it happens with movies, haven't tried)
2. Play it.
3. Try to check the subtitle track as soon as the show starts. Can you?

In my case it starts by saying "loading subtitles" although I can see that no subtitle track is selected (the track of "no subtitle" is checked). I try to select the subtitle track that I want, but it doesn't let me do that. I have to wait until it gives out an error basically saying it couldn't load the subtitles (can't remember the exact words) and then It does let me select the subtitle track, and displays it correctly.

### Application version

0.16.0

### Where did you install the app from?

Sideloaded APK

### Device information

Xiaomi mi box 4

### Android version

Android 9

### Jellyfin server version

10.8.13

**Comment by nwgat** [comment]
ive ran into this same issue, will try to get it to show up again, sometimes its randomly works

**Comment by languagemaniac** [comment]
I'm still experiencing this error, the bot closed the issue
