### ISSUE TITLE
Search function broken in 0.16.x Firestick 4K

### ISSUE THREAD

**Issue by DwayneGoddem** [jellyfin/jellyfin-androidtv#3242]
### Describe the bug

On the firestick since 0.16.0 when you do a search if you don't press the next button you cant select anything.
Before the update you could press the BACK button to exit the on screen keyboard and select a video.

But not now its quite frustrating.

### Application version

0.16.2

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Firestick 4k

### Android version

Firestick Android 

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
Thanks for the report, will be fixed in 0.16.3.
