### ISSUE TITLE
Music search and playback

### ISSUE THREAD

**Issue by yashaskm11** [jellyfin/jellyfin-androidtv#3243]
### Describe the bug

Searcing for `foo` , gives result `fooA` , `fooB`, ... ,`foobar` ,...., `foobarZ` .
selecting any track Ex. `foobar` adds the entire search results to queue and starts playback from the first track from the results ie., `fooA`
This seems to be happening only from 0.16.x version.

### Application version

0.16.1

### Device information

AFTV 4K (2018)

### Android version

Amazon Fire OS 6

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
Thanks for the report. This issue will be fixed in 0.16.3 where it will just play the single track you selected.
