### ISSUE TITLE
Collections display problem since the latest Android TV update version

### ISSUE THREAD

**Issue by Debouelesmorts** [jellyfin/jellyfin-androidtv#3251]
### Describe the bug

Greetings to all,

Since the latest Android TV version 0.16 update, I've noticed a display problem in the Collections library.

The different images specific to each collection are first displayed with a zoom effect on the image, which makes navigation ugly and unclear. If you scroll from bottom to top, the images return to normal display, but if you scroll again, the problem returns...and so on.

I've seen this problem on two different Nvidia Shield devices, with the latest Android TV update version 0.16.1 with the latest Server/Web Hotfix Release 10.8.13 installed on a dedicated Debian server in docker-compose.

The display parameters of the Collections library are as follows :

For Server/Web Hotfix Release 10.8.13.

Image type : Primary

For Android TV update version 0.16.1

Image size : Big

Image type : Miniature

Direction of grid : Vertical

### Application version

0.16.1

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield TV Pro (2019)

### Android version

Android 9.1.1 (33.2.0.157)

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
I'm not exactly sure what the bug is. When I open the collections view in the app it displays just fine for me. Can you be more specific what problem you encounter and how to reproduce it?

**Comment by leelouislinden** [comment]
i have the same issue with collections after the update to version 0.16.1. Im using a google chrome cast. My collections are in thumbnail view and appear to be zoomed in when i first open the collections folder. As i scroll through them they begin to correct themselves

**Comment by Debouelesmorts** [comment]
> I'm not exactly sure what the bug is. When I open the collections view in the app it displays just fine for me. Can you be more specific what problem you encounter and how to reproduce it?

Does the description of  @leelouislinden seem clearer to you ? As he describes it, the problem is the zoom effect on the images.

**Comment by MichaelRUSF** [comment]
I've noticed this bug too on 0.16.2 / 10.8.13 while browsing collections. 

![JPEG image (Small)](https://github.com/jellyfin/jellyfin-androidtv/assets/78215956/5a9b482e-ea27-446d-ad31-5e25486b1c8b)

Exiting the app and then going back causes the image to show normal. 

![JPEG image 2 (Small)](https://github.com/jellyfin/jellyfin-androidtv/assets/78215956/faa950be-8c4f-4560-8c3e-37fe66bf3fe7)

**Comment by nielsvanvelzen** [comment]
Should be fixed with 0.16.3, thanks for reporting!
