### ISSUE TITLE
Self updating apk 

### ISSUE THREAD

**Issue by d8f6** [jellyfin/jellyfin-androidtv#3255]
### Describe the feature you'd like

Hello, I think it would be helpful to be able to update jellyfin-androidtv from the app itself as oppposed to waiting for builds from f-droid or google play store. Currently I am just sideloading and updating that way due to the waiting time for builds on f-droid. This is not really a big deal for me, but I thought it may be a useful option to consider in the future for some users/use cases. 

Edit: After thinking on this a bit further, I have come to the conclusion that this is a bad idea and a feature that should not exist in an application that is functionally offline.

**Comment by Dnkhatri** [comment]
> ### Describe the feature you'd like
> Hello, I think it would be helpful to be able to update jellyfin-androidtv from the app itself as oppposed to waiting for builds from f-droid or google play store. Currently I am just sideloading and updating that way due to the waiting time for builds on f-droid. This is not really a big deal for me, but I thought it may be a useful option to consider in the future for some users/use cases.
> 
> Edit: After thinking on this a bit further, I have come to the conclusion that this is a bad idea and a feature that should not exist in an application that is functionally offline. Sideloading is not that hard.

I don't agree with you completely about it not being useful. Kodi has a plugin that allows you to download the latest nightly or beta or the latest release version from inside kodi. The ability to download such from inside the app would be good specially on devices that do not have fdroid or playstore

**Comment by nielsvanvelzen** [comment]
F-Droid these days is quite fast with their updates. While before they updated once a week it looks like they do it multiple times a week now (I don't have the specifics for it).

I want to create our own F-Droid repository at some point, so the updates are available the moment they are released. However, this is a low priority thing on my big list of stuff to do.
