### ISSUE TITLE
RTL Subtitles (Puncitions)

### ISSUE THREAD

**Issue by Obegg** [jellyfin/jellyfin-androidtv#3257]
### Describe the bug

1. Download subtitles that it's language is RTL such as Hebrew, here's an example of `.srt` subtitle:
```
1
00:00:16,975 --> 00:00:18,435
.את חייבת לספר לי

```
2. Play the video file with the RTL subtitles on the Google Chromecast device
3. Puncitions are shown LTR instead of RTL:
```
1
00:00:16,975 --> 00:00:18,435
את חייבת לספר לי.

```

Note: Plex has the same issue.

### Application version

0.16.1

### Where did you install the app from?

Google Play

### Device information

Google Chromecast 4K (GA01919-US)

### Android version

Android 12

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
I've made a possible fix but am unable to test it. Please try the app build from #3267.

To test:
- Go to the build artifacts (https://github.com/jellyfin/jellyfin-androidtv/actions/runs/7351258722?pr=3267)
- Scroll down and click on the "build-artifacts" link in the "Artifacts" section
- Unzip the file
- Sideload the .apk file to your device

It will install as separate app (Called Jellyfin Debug, with an orange logo)

**Comment by Shasoosh** [comment]
Are there any updates on this? 
I would appreciate it being addressed, similar to the resolution in https://github.com/jellyfin/jellyfin-web/pull/4895
