### ISSUE TITLE
Shuffle All only shuffles first season

### ISSUE THREAD

**Issue by spart0n654** [jellyfin/jellyfin-androidtv#3258]
### Describe the bug

I sleep to the big bang theory all seasons shuffled and just switched to jellyfin, the show and episodes are all named properly and in the library and sorted by season automatically but every time I hit shuffle all it will ONLY shuffle episodes from a single season and then completely stop playing anything. Is there a way to shuffle all episodes from the entire show and repeat them?
this behavior happens on the web browser jellyfin client on pc and on jellyfin for android tv

I added the log files that are present, not sure if they will help

### Logs

[FFmpeg.Remux-2023-12-25_12-52-35_1995c7b7f3d41857466a1264da92ec41_8dd06c8a.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767050/FFmpeg.Remux-2023-12-25_12-52-35_1995c7b7f3d41857466a1264da92ec41_8dd06c8a.log)
[FFmpeg.Remux-2023-12-25_12-52-40_bfc5280c87d4147153de670025c6eefc_5292aeb3.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767051/FFmpeg.Remux-2023-12-25_12-52-40_bfc5280c87d4147153de670025c6eefc_5292aeb3.log)
[FFmpeg.Remux-2023-12-25_12-52-41_ee9e9b03a652650b74e7e63c09e0825e_855a27f1.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767052/FFmpeg.Remux-2023-12-25_12-52-41_ee9e9b03a652650b74e7e63c09e0825e_855a27f1.log)
[FFmpeg.Remux-2023-12-25_12-52-43_6d0687f9fb42a0e906ed33d28d3daa5d_738ab924.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767053/FFmpeg.Remux-2023-12-25_12-52-43_6d0687f9fb42a0e906ed33d28d3daa5d_738ab924.log)
[FFmpeg.Remux-2023-12-25_12-52-44_edb6033d9af4b9709f330adde77f2c0f_bc8ee5e4.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767054/FFmpeg.Remux-2023-12-25_12-52-44_edb6033d9af4b9709f330adde77f2c0f_bc8ee5e4.log)
[FFmpeg.Remux-2023-12-25_12-52-45_c8859b19717b3a6a60c442ca58fb7793_a0631c0f.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767055/FFmpeg.Remux-2023-12-25_12-52-45_c8859b19717b3a6a60c442ca58fb7793_a0631c0f.log)
[FFmpeg.Remux-2023-12-25_12-52-46_d151c6e9e12cd2d1bf3b6b6e36e9ccd1_ba5c0060.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767056/FFmpeg.Remux-2023-12-25_12-52-46_d151c6e9e12cd2d1bf3b6b6e36e9ccd1_ba5c0060.log)
[FFmpeg.Remux-2023-12-25_12-52-47_259d67d89735822ce6616febfc1c5898_ed7d8fbd.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767057/FFmpeg.Remux-2023-12-25_12-52-47_259d67d89735822ce6616febfc1c5898_ed7d8fbd.log)
[FFmpeg.Remux-2023-12-25_12-52-48_41294a994a23181fa985c7056e768212_b62396b9.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767058/FFmpeg.Remux-2023-12-25_12-52-48_41294a994a23181fa985c7056e768212_b62396b9.log)
[FFmpeg.Remux-2023-12-25_12-52-49_dbd8b87c73cdd0f8aec231bb04f73314_9cf1e098.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767059/FFmpeg.Remux-2023-12-25_12-52-49_dbd8b87c73cdd0f8aec231bb04f73314_9cf1e098.log)
[FFmpeg.Remux-2023-12-25_12-52-50_7280f9548a688542edb8fd8e9f1013cd_7dc7d547.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767060/FFmpeg.Remux-2023-12-25_12-52-50_7280f9548a688542edb8fd8e9f1013cd_7dc7d547.log)
[FFmpeg.Remux-2023-12-25_12-52-51_a0c865f1e4ad424797b46b13f0485160_f3de0aa0.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767061/FFmpeg.Remux-2023-12-25_12-52-51_a0c865f1e4ad424797b46b13f0485160_f3de0aa0.log)
[FFmpeg.Remux-2023-12-25_12-52-52_db7567495841a247c1e8577a19a396c4_c20c9fb0.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767062/FFmpeg.Remux-2023-12-25_12-52-52_db7567495841a247c1e8577a19a396c4_c20c9fb0.log)
[FFmpeg.Remux-2023-12-25_12-52-53_1a3c413f90321dcdc04bf1d4d679cdba_e86af633.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767063/FFmpeg.Remux-2023-12-25_12-52-53_1a3c413f90321dcdc04bf1d4d679cdba_e86af633.log)
[FFmpeg.Remux-2023-12-25_12-52-54_18b1f595557d8110d78e43cddf1b61ba_6eabe80f.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767064/FFmpeg.Remux-2023-12-25_12-52-54_18b1f595557d8110d78e43cddf1b61ba_6eabe80f.log)
[FFmpeg.Remux-2023-12-25_12-52-55_abe0e178f15e7ad35b88a5d528308d3a_5b4d8fef.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767065/FFmpeg.Remux-2023-12-25_12-52-55_abe0e178f15e7ad35b88a5d528308d3a_5b4d8fef.log)
[FFmpeg.Remux-2023-12-25_12-52-56_f8fca0d3ca6c1f1831c459cf04fc6cfe_4176497d.log](https://github.com/jellyfin/jellyfin-androidtv/files/13767066/FFmpeg.Remux-2023-12-25_12-52-56_f8fca0d3ca6c1f1831c459cf04fc6cfe_4176497d.log)

### Application version

latest playstore version

### Where did you install the app from?

Google Play

### Device information

tivo android tv box

### Android version

12

### Jellyfin server version

latest stable for windows

**Comment by spart0n654** [comment]
I have found a workaround, put all 12 seasons of that show into a playlist and shuffle from there, then I'm curious as to why it says "Shuffle All" from the tv show screen when no specific season is selected but it will only shuffle from a single season?

**Comment by nielsvanvelzen** [comment]
This is likely a server issue. The app asks the server to provide all files to play and if only one season is returned that means the server somehow decided to not send back everything else.

**Comment by spart0n654** [comment]
This bug is still present but a workaround is using playlists instead of shows
