### ISSUE TITLE
Option to Enable "Tunneled Video Playback in ExoPlayer" to improve/enforce HDR and Performance.

### ISSUE THREAD

**Issue by nwgat** [jellyfin/jellyfin-androidtv#3261]
can't seem to find info if this is in jellyfin for android tv yet but would been useful if it was
https://medium.com/google-exoplayer/tunneled-video-playback-in-exoplayer-84f084a8094d

**Comment by nielsvanvelzen** [comment]
The app does not currently enable tunneling in ExoPlayer

**Comment by nielsvanvelzen** [comment]
Support for tunneling and audio offloading is added to the old playback engine in #3268. It will be available in 0.17 (either via the new or old playback code).
