### ISSUE TITLE
App ignores external playstate changes

### ISSUE THREAD

**Issue by jumoog** [jellyfin/jellyfin-androidtv#3263]
### Describe the bug

1.) Play a video
2.) Try stopping or pausing playback via Server Overview
3.) Nothing happens and HTTP Request shows no error 

or

1). Play a video
2.) Open the official Android app and connect to the TV session
3.) Try to stop or pause playback
4.) Nothing happens

### Application version

0.16.2

### Where did you install the app from?

Google Play

### Device information

Google Chromecast

### Android version

Android 12

### Jellyfin server version

10.8.13

**Comment by jumoog** [comment]
It stopped working after version 0.16.0.

**Comment by nielsvanvelzen** [comment]
Do you mean the remote control functionality? Did it stop working in 0.16.1?

**Comment by jumoog** [comment]
Yes I'll test all Versions

**Comment by nielsvanvelzen** [comment]
It's likely the problem that I fixed in #3253 for 0.16.3. As a workaround you can downgrade to 0.16.1.

**Comment by jumoog** [comment]
I've built the app from master and tried stopping or pausing playback from the server overview, but it still doesn't work. I'll see if I can find the problem.

**Comment by nielsvanvelzen** [comment]
The mentioned pull request is not merged yet

**Comment by nielsvanvelzen** [comment]
Awesome, thanks for testing! The fix will be released in 0.16.3, which will be released somewhere next week (likely the 2nd, 6th or 7th).
