### ISSUE TITLE
Adjustable skip time

### ISSUE THREAD

**Issue by schumi4** [jellyfin/jellyfin-androidtv#3276]
### Describe the feature you'd like

Being able to adjust the skip time for left and right clicking would be very beneficial in my opinion. Something like 5, 10, 20 seconds.
The current system with the fixed times does not really make sense.

**Comment by nielsvanvelzen** [comment]
You can already change the skip duration. It is not currently possible to do so within the app, but you can open Jellyfin in the browser and change "skip forward length" and "skip back length" in the playback settings.

**Comment by schumi4** [comment]
That changes the behaviour of the skip buttons, I'm talking about simply pressing the left or right button on the remote during playback, sorry I was a bit unclear there.

Doing this it always skips to the nearest :00 or :30 seconds, which is not very practical.

**Comment by nielsvanvelzen** [comment]
Thanks for clarifying. The user interface of the video player is largely managed by a third-party library right now and we have little control over its behavior. This is similar to #3154 (same cause).

**Comment by schumi4** [comment]
I see, very unlucky. Thanks for clarifying and the work you are putting into this project!
