### ISSUE TITLE
Version selection doesn't work

### ISSUE THREAD

**Issue by ryadre** [jellyfin/jellyfin-androidtv#3279]
### Describe the bug

Click version, select different version, checkmark is checked, press play, playback plays the same original version and not what has been selected 

### Application version

0.16.2

### Device information

Nvidia Shield Pro 2019, shield 2017 and shield 2015

### Android version

Latest version 

### Jellyfin server version

10.8.13

**Comment by thedudeabides79** [comment]
Seeing this on my devices too. Output file does not always track selected version. Also using nvidia shield 2019.
