### ISSUE TITLE
Won’t let you login on fire stick/ fire stick lite version 0.16.2

### ISSUE THREAD

**Issue by Panpan255** [jellyfin/jellyfin-androidtv#3283]
### Describe the bug

It won’t let you join the server says it can’t find the server 
![image](https://github.com/jellyfin/jellyfin-androidtv/assets/105138162/e047dd25-70ef-4dd4-bc39-ab3c0f8361f3)

### Application version

0.16.2

### Where did you install the app from?

Amazon Appstore

### Device information

Fire stick lite

### Android version

Fire OS 7.6.6.4

### Jellyfin server version

10.8.13

**Comment by MovieWiz** [comment]
This does not appear to be a generic issue.

I have a FireTV Stick Lite and I'm using the 0.16.2 version of the app.  I'm not having any problem logging in.  I'm specifying my jellyfin server by local IP address (192.168.###.###).  My server is also auto detected by the app.

Hopefully the OP can provide some additional info about how their situation/setup might be different.

**Comment by nielsvanvelzen** [comment]
This is not an app issue. Use our Discord/Matrix/Forum/others for troubleshooting.

https://jellyfin.org/contact
