### ISSUE TITLE
Jellyfin server is bombarded with upload_org.jellyfin.androidtv_0.16.2_*.log

### ISSUE THREAD

**Issue by jakanaka** [jellyfin/jellyfin-androidtv#3289]
### Describe the bug

Recently i am setting a lot of upload_org.jellyfin.androidtv_0.16.2_*.log error log files. in 24h, there are over 1000+ crash reports uploaded to my jellyfin server and all are of tv app. I really don't want any client crash log upload to my server. how do i prevent that?

### Application version

0.16.2

### Where did you install the app from?

Google Play

### Device information

Hi3751V352E_DMO

### Android version

9

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment]
Disable the crash reports if you don't want them. If you receive over 1000 of them in a single day you likely have more important things to look at though.
