### ISSUE TITLE
Live TV won't open on Chromecast (Volley Error)

### ISSUE THREAD

**Issue by DigitalMethBaba** [jellyfin/jellyfin-androidtv#3308]
### Describe the bug

Expected behavior:
1. Go to Jellyfin for Android TV on Chromecast. The media library displays after the app loads, including Live TV.
2. Click on Live TV. It shows all the channels from your M3U playlist.

Actual behavior:
1. Go to Jellyfin for Android TV on Chromecast. The media library displays after the app loads, including Live TV.
2. Click on Live TV. It shows a blank page and an error message saying "VolleyError com.android.volley.ServerError:"

I installed it from the Chromecast app library which probably only shows TV compatible apps from the Google Play Store. I'm not sure where or how to retrieve the log files. Sorry it's my second time reporting a bug on github.

### Application version

0.16.4

### Where did you install the app from?

None

### Device information

 Chromecast with Google TV (4K)

### Android version

Android TV 12

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
This error could mean a few things. Best is to check your server logs (dashboard->logs) to see if there is any errors when this happens in the client. I'd recommend using our troubleshooting channels first (see https://jellyfin.org/contact) as there are more people that can help figure out what is wrong over there.
