### ISSUE TITLE
jellyfin android tv client logout after some time

### ISSUE THREAD

**Issue by PhieF** [jellyfin/jellyfin-androidtv#3312]
### Describe the bug

I can't find a proper way to reproduce, perhaps when server has a problem, but after some time, sometimes months, client is logged out and I need to put my credentials and server address again (even if server is back, up and running)

### Application version

0.16.

### Where did you install the app from?

None

### Device information

Nexus PLayer

### Android version

Android 8

### Jellyfin server version

10.8.10

**Comment by nielsvanvelzen** [comment]
Jellyfin sessions have an infinite lifespan but they can be revoked. You've likely done of the following things:
- Wrongly login with another account on the same device (this clears ALL sessions for that device on the server)
- Removed the device from the Jellyfin dashboard
- Used the session cleaner plugin to automatically remove the session

It might also be possible that your device is removing app data, which is rare but does happen. Either way, this is not an issue with the app.

**Comment by PhieF** [comment]
@nielsvanvelzen I did none of that

**Comment by nielsvanvelzen** [comment]
Use one of our [contact channels](https://jellyfin.org/contact) (matrix/forum/discord) to troubleshoot issues with your setup.
