### ISSUE TITLE
Implement support for Jellyscrub plug-in or otherwise support using BIF files and JSON manifests to implement timeline scrubbing

### ISSUE THREAD

**Issue by stpettersens** [jellyfin/jellyfin-androidtv#3316]
### "Trickplay" thumbnails in timeline

There is a plugin called Jellyscrub which adds support to the Web client to generate thumbnails on the video timeline. It does this by generating BIF files and JSON manifest files:

https://github.com/nicknsy/jellyscrub

<img src="https://github.com/nicknsy/jellyscrub/raw/main/logo/jellyscrub-ios.jpg" width="500">

The thumbnails in the timeline are then supported in the Web client and the Android (non-TV) client.

My request is **not** to support the generation of the BIF and JSON manifests for timeline thumbnails, but to support the thumbnails generated via the Web client in the Android TV client.  Probably this should be done independently of the Jellyscrub plugin itself, but can rely on such a plugin in the Web client to generate the BIFs and JSON manifests that the Android TV client can use to provide the scrubbing.

Thanks.

**Comment by nielsvanvelzen** [comment]
Official Jellyfin clients do not support third-party plugins.

**Comment by woolmonkey** [comment]
Sure but the web client supports third party plugins.

**Comment by nielsvanvelzen** [comment]
No it does not

**Comment by woolmonkey** [comment]
Must be my imagination that I can load plugins. And they work in the web page.

**Comment by thornbill** [comment]
Copied from the Jellyscrub README:

> If your Jellyfin's web path is set, the plugin should automatically inject the companion client script into the "index.html" file of the web server directory. Otherwise, the line <script plugin="Jellyscrub" version="1.0.0.0" src="/Trickplay/ClientScript"></script> will have to be added at the end of the body tag manually right before </body>. If you have a base path set, change src="/Trickplay/ClientScript" to src="/YOUR_BASE_PATH/Trickplay/ClientScript".

It is **not** supported by web without making modifications to the built files... and we definitely do not provide any official support for doing that. 

Let's remember to be respectful though. Arguing with maintainers won't get you anywhere.

**Comment by stpettersens** [comment]
Niels means they are unsupported in that third-party plugins will not be be
acknowledged to officially work, not that they will not technically work.
The distinction being that Jellyfin does seems to ship with some official
plugins.

**Comment by stpettersens** [comment]
> Must be my imagination that I can load plugins. And they work in the web page.

This particular plug-in will work with the Android version, but not the TV version.
It think it is not *officially * supported by any official Jellyfin client because it is third-party,

**Comment by thornbill** [comment]
Fwiw official support for image previews has [been merged in the server](https://github.com/jellyfin/jellyfin/pull/9554) in unstable so that plugin will likely become obsolete in the 10.9.0 release.

**Comment by stpettersens** [comment]
Thanks

**Comment by JVT038** [comment]
Can this issue be reopened, because 10.9.0 has been released with a native trickplay feature. Therefore, I think this issue has become relevant again, because it's no longer a third-party plugin.
