### ISSUE TITLE
Can't connect using Jellyfin Android app but can using Brave browser.

### ISSUE THREAD

**Issue by Pedro-MC** [jellyfin/jellyfin-androidtv#3319]
### Describe the bug

Steps to reproduce:
1. Launch Jellyfin Android app.
2. Enter server name, or server IPv4, or server IPv6, or server HTTPS URL.
3. Click connect.
4. See messages indication connection failure with a bunch of URLs.
5. Connect using the Brave browser to https://server-name:8920/, it loads the Web UI.
6. Login to Jellyfin account.
7. Do stuff like browse libraries or play videos (it all works).

Other information:
- Jellyfin server running on Mageia 9, x86_64, as a restricted systemd service;
- DNLA is disabled;
- IPv6 is enable on Jellybin;
- Jellyfin is listening on :::8096, :::8920, and 0.0.0.0:7359 but only 8920/TCP is open on the firewall;
- have minidlna running on the same server machine but stopping minidlna changes nothing;
- self-signed certificate;
- can connect from the server itself and other systems (e.g. laptop, desktop) using the web UI on Firefox, both with https://IP:8920/ and https://server-name:8920/;
- nothing shows up on the server logs when I try to connect from the Jellyfin Android app.

### Application version

2.6.0

### Where did you install the app from?

Google Play

### Device information

Alcatel 3X

### Android version

Android 9

### Jellyfin server version

10.8.13

**Comment by thornbill** [comment]
This repo is for the Android **TV** app. It looks like your issue is with the mobile app.

**Comment by beankylla** [comment]
I have this exact issue with the androidTV app on a xiaomi mi tv
