### ISSUE TITLE
DV/HDR does not get tone mapped unless transcoding

### ISSUE THREAD

**Issue by Schaka** [jellyfin/jellyfin-androidtv#3323]
### Describe the bug

1. Have a HDR non-capable device (TV)
2. Have an Android player that may or may not be HDR capable (Fire TV, which can do HDR but reports no capabilities when using its UI to check if HDR content can be displayed)
3. Play DV or HDR content
4. See colors being washed out
5. Force transcoding
6. Observe colors now getting tone mapped correctly, but at very low bitrate (because transcode needed to be forced)

### Application version

0.16.4

### Device information

Fire TV 4k Max (1st gen)

### Android version

Whatever is applicable to that Fire TV when fully updated

### Jellyfin server version

10.8.13

**Comment by Schaka** [comment]
Issue still persists

**Comment by Schaka** [comment]
Nothing changed as far as I can tell, but I switched devices and don't care anymore

**Comment by ocervell** [comment]
Please re-open, the issue still exists !!
