### ISSUE TITLE
What is the point of 120 Mbps stream limit ?

### ISSUE THREAD

**Issue by GH0000000000** [jellyfin/jellyfin-androidtv#3335]
### Describe the bug

My some videos H.264 or HEVC exceed 120 Mbps bitstream limit so I can see bugs/artefacts/problems playing them by Jellyfin from NAS, the Android Jellyfin example error message "Player error, trying again... "

I did TEST 1 like this on my NVIDIA Shield PRO 2019. I moved my HEVC 400 Mbps video into shield local drive and used local Android video player to run the video. The HEVC 400 Mbps video was properly played by NIDIA Shield with no issues. Very interesing. 

So, I did TEST 2 on my PC/RTX GPU. I used local PC video player but the video file HEVC 400 Mbps was still on local NAS, so video was streamed from NAS by local network to PC. The HEVC 400 Mbps video was properly played by PC with no issues, bitstream was between 500-300 Mbps (reported by Windows task manager). Very interesing too.

My conclusions:
TEST 1, NVIDIA Shield PRO 2019 is able to play properly HEVC 400 Mbps videos
TEST 2, My NAS and local network are able to deliver bitstream above 500 Mbps

The question is:
Why Jellifin (Android and PC version too) is not able to play properly HEVC 120+ Mbps videos although:
1. Local NAS is able to deliver requested bitstream
2. Local network is able to stream upto 1 Gbps
3. NVIDIA Shield is able to play HEVC 400 Mbps videos (and maybe 400+ Mbps, not tested)
4. PC is able to play HEVC 400 Mbps videos (and maybe 400+ Mbps, not tested)

What is the point of 120 Mbps stream limit in local network ?

### Logs

Android Jellyfin error "Player error, trying again... " (0.16.4 version)
PC Jellyfin does not display error message, app freezes (1.9.1 version)

### FFmpeg logs

```shell
No data
```

### Media info of the file

```shell
HEVC 400 Mbps
```

### Application version

Android 0.16.4

### Device information

NVIDIA Shield PRO 2019

### Android version

9.1.1(33.2.0.157)

### Jellyfin server version

10.8.13.r1 ASUSTOR

**Comment by nielsvanvelzen** [comment]
The bitrate selection limits were copied from jellyfin-web the last time we updated it (a few years back) and we've never had any request to increase it. If your media exceeds the set limit it will transcode.

**Comment by GH0000000000** [comment]
The "limit parameter" should be defined according to user needs, we have 4090 GPUs and 10G home networks now.
It is an artificial limit that has no justification in today's times.

**Comment by nielsvanvelzen** [comment]
I've just checked and the maximum selectable bitrate in jellyfin-web is still 120Mbps so I have no intention to change it for the app.

Closing as wontfix

**Comment by GH0000000000** [comment]
Yes, 3 fixes are needed:

1. 120 Mbps CAP / video bitrate must be customizable according to user needs, the max 120 Mbps bitrate cap has no sense

2. VIDEO TRANSCODING / using Jellyfin NAS 10.8.13.r1 and 120+ Mbps bitstream on Android TV (Jellyfin 0.16.4) error is generated "Player error, trying again... ". The bug should be fixed.

3. VIDEO TRANSCODING / using Jellyfin NAS 10.8.13.r1 and 120+ Mbps bitstream on PC (Jellyfin 1.9.1) error is generated, the app freezes. The bug should be fixed.
