### ISSUE TITLE
Enable to play current video format (when try to play in external app)

### ISSUE THREAD

**Issue by Set27** [jellyfin/jellyfin-androidtv#3349]
### Describe the bug

All translated from Russian language (I don't find when I can switch Jellyfin to English on android tv), in English it can be different
1. Open Jellyfin
2. Select **any** movie
3. Play
4. Play using external app

And now I don't see any selector for apps (as usual), I just see gray screen and toast notification "unable to play current video format"

### Logs

I don't find any related logs (seems is not created while error)

### Application version

0.16.4

### Where did you install the app from?

Google Play

### Device information

sony bravia kdl-43w808c

### Android version

Android 7

### Jellyfin server version

Chrome Jellyfin Web 10.8.13

**Comment by Set27** [comment]
Also, I can definitely say, that is not local network problem, cuz my second TV works well

**Comment by nielsvanvelzen** [comment]
Jellyfin starts the video player configured as default in your system. If your chosen video player doesn't work you can set a different one from the system settings (how to do this differs per manufacturer).

**Comment by Set27** [comment]
@nielsvanvelzen What you mean by default player? I don't have any default player.
When I play video in other app I see pop up with choose (Mx player, VLC, Vimu), in JellyFin app I don't have this pop up

**Comment by MichaelRUSF** [comment]
This seems like it's an issue with your device, not jellyfin. Try uninstalling all your video player apps including jellyfin, then reinstall them. This [post](https://xdaforums.com/t/default-video-app-settings-missing-in-my-android-7-now-solved.3558464/) for reference.

**Comment by Set27** [comment]
@MichaelRUSF In other application choosing external video player works fine

**Comment by SnelsSM** [comment]
The same problem is in version 0.16.7.
Sometimes the error occurs with any external player.
After unloading jellyfin from RAM, everything works fine (sometimes not).
