### ISSUE TITLE
certains mp3 file are played beyond their length  

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin-androidtv#3358]
### Describe the bug

Playing music files from androidtv version, some tunes get a long blank time after the music stop.
In such case, on the screen the progress bar is complete and the time increase in the negative time :) (see picture)

![IMG20240208180231](https://github.com/jellyfin/jellyfin-androidtv/assets/8579/8814fc56-2626-441c-9050-7cc3ebb21c00)

android Web does not have such issue, neither Android application do. My local player rhythmbox does not have any issue.

I saw that the tagging application I use (eyeD3) reports length information that could explain the problem
```
➜  eyeD3 02.\ The\ Kills\ -\ New\ York.mp3 
02. The Kills - New York.mp3                                            [ 5.46 MB ]
-------------------------------------------------------------------------------------------------
Time: 23:36	MPEG1, Layer III	    [ 32 kb/s @ 44100 Hz - Joint stereo ]
^^^^^^^^^^^
```

### Application version

0.16.4

### Where did you install the app from?

Google Play

### Device information

freebox pop fiber box (SoC 4 x Cortex-A53 Amlogic S905X2)

### Android version

Android (version unknown atm)

### Jellyfin server version

10.8.13

**Comment by bmillemathias** [comment]
(sorry if this information is not helpful)

ffplay reports the correct duration but issues a warning about it
```
ffplay 02.\ The\ Kills\ -\ New\ York.mp3 
...
[mp3 @ 0x7f59b4000c80] Estimating duration from bitrate, this may be inaccurate
...
  Duration: 00:04:31.52, start: 0.000000, bitrate: 168 kb/s
  Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 166 kb/s
```

**Comment by nielsvanvelzen** [comment]
Is the audio file played directly or does it remux/transcode? (you can check in the Jellyfin dashboard)

**Comment by bmillemathias** [comment]
> Is the audio file played directly or does it remux/transcode? (you can check in the Jellyfin dashboard)

Sorry I did not find where I could find this.it on the web UI or in the android application.

Thanks
