### ISSUE TITLE
Jellyfin launches when playing with an other app Tivimate

### ISSUE THREAD

**Issue by spyjo** [jellyfin/jellyfin-androidtv#3364]
### Describe the bug

Sometimes when I start to watch a channel or replay in Tivimate, Jellyfin launches above it. It is not every time, so I don't have a proper manner to repeat this bug. It seems to catch sometimes an event from the player in Tivimate at the start of playing.

### Application version

0.16.4

### Where did you install the app from?

Google Play

### Device information

Sony Bravia KD55XH95

### Android version

Android 9

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
It is unlikely caused by the Jellyfin app. It is not possible in Android to suddenly make your own app appear. This can only happen when something else requests the app to open (in technical terms: via intents/receivers). Unless you can provide the steps to reproduce this problem I can't help you.

**Comment by spyjo** [comment]
@nielsvanvelzen Thank you for your answer. It's strange because Tivimate last update is march 2023, and I have this bug since some weeks only, so it can probably only come from a recent Jellyfin update.

**Comment by lwilli1026** [comment]
> ### Describe the bug
> Sometimes when I start to watch a channel or replay in Tivimate, Jellyfin launches above it. It is not every time, so I don't have a proper manner to repeat this bug. It seems to catch sometimes an event from the player in Tivimate at the start of playing.
> 
> ### Logs
> _No response_
> 
> ### Application version
> 0.16.4
> 
> ### Where did you install the app from?
> Google Play
> 
> ### Device information
> Sony Bravia KD55XH95
> 
> ### Android version
> Android 9
> 
> ### Jellyfin server version
> 10.8.13

I've had this same issuse...I'll be watching a channel in tivimate and when I try to change to a different channel Jellyfin launches out of nowhere.
