### ISSUE TITLE
Please release Jellyfin with media3 version 1.2.1 to fix long time Android OPUS and VORBIS channel layout bug (e.g. where the centre channel plays on the right channel)

### ISSUE THREAD

**Issue by channeladam** [jellyfin/jellyfin-androidtv#3365]
### Describe the bug

The latest media3 (release v1.2.1 on 17 January 2024 - https://github.com/androidx/media/releases/tag/1.2.1) finally apparently fixes the annoying 3 year old bug with the OPUS and VORBIS channel layouts being wrong for 3, 5, 6, 7 and 8 channels (https://github.com/google/ExoPlayer/issues/8396).

@nielsvanvelzen I see that 4 days ago you committed an update to version 1.2.1 (https://github.com/jellyfin/jellyfin-androidtv/commit/60eac66d90d4e07664f2d3511d354ba8e523bf3f) - thank you!! And thank you for the media3 change too!!

I don't know what the release and testing schedule or procedure is for Jellyfin AndroidTV, but if there isn't a release planned any time soon, perhaps could I please humbly encourage one to be planned - in order to fix this long time Android issue!  :)

Thank you very very much!

### Application version

0.16.4

### Device information

FireTV Max

### Android version

Fire OS

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
The pull request for the media3 1.2.1 update (#3352) is labelled with "Backportable". This label means it is likely to get backported to the next release (in the case of this update it definitely will be). Originally I planned to release 0.16.5 this weekend but I was not able to find the time to prepare it yet. Most likely in the coming week.

**Comment by nielsvanvelzen** [comment]
[v0.16.5](https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.16.5)

**Comment by channeladam** [comment]
That fixed it - thank you @nielsvanvelzen !!!
