### ISSUE TITLE
Show end time in new player design

### ISSUE THREAD

**Issue by BeecherNetworks** [jellyfin/jellyfin-androidtv#337]
The new player design does not properly show the time at which the currently playing media will end. The previous player did have this feature.

(edited by @nielsvanvelzen)

------

**Original issue:**
I'm sure "seek bar" is incorrect, but for the life of me I can't think what it should be called.

Minor bug, there's no space between "Ends" and the end time, as per the image:

![ends](https://user-images.githubusercontent.com/179583/74482086-c897ff00-4eab-11ea-9836-8e3926b5b1e8.jpg)

I've searched the source and I think the var is **lbl_ends**, and I think the problem is in [app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java](https://github.com/jellyfin/jellyfin-androidtv/blob/d1a3282cd553c98caa25767b699ecfcd66fd293c/app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java) on line 529, as compared to [app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java](https://github.com/jellyfin/jellyfin-androidtv/blob/25edae156340ccd8c6aa9606f479638ba6d7b52c/app/src/main/java/org/jellyfin/androidtv/util/InfoLayoutHelper.java) which does have a space on line 205. Different functions, but they seem to perform much the same task.

One other question so I can file another small bug: what are the little chiclets that appear on the same screen called, the ones with the media attributes like 1080, AAC, etc?

**Comment by thornbill** [comment]
It looks like those are called “block text” in the source. I would call them tags or something similar lol.

**Comment by nielsvanvelzen** [comment]
The video player was redesigned and does not currently show the timestamps.

PS: Those attributes are called "chips" if we follow material design naming. They are custom made however but that's the name used in new code I made.

**Comment by BeecherNetworks** [comment]
> The video player was redesigned and does not currently show the timestamps.
> 
Oh please, say it ain't so!? The times are incredibly useful, particularly for kids!

> PS: Those attributes are called "chips" if we follow material design naming. They are custom made however but that's the name used in new code I made.

Thanks, I'll open another Issue about that.

**Comment by nielsvanvelzen** [comment]
It currently looks like this:
![image](https://user-images.githubusercontent.com/2305178/74532265-0e49db80-4f2f-11ea-8293-07c1ade04baf.png)

So it does show the current timestamp and the duration but it does not display when it will end. I agree we should look at adding this back (I've used it a lot too in the past).

**Comment by thornbill** [comment]
> Oh please, say it ain't so!? The times are incredibly useful, particularly for kids!

Hah I find it useful for the exact same reason!

**Comment by nielsvanvelzen** [comment]
@Florianisme are you willing to look into this or should I do it?

**Comment by Florianisme** [comment]
I already looked into it but didn't find a solution yet so maybe you can have a look aswell.

**Comment by BeecherNetworks** [comment]
> It currently looks like this:
> ![image](https://user-images.githubusercontent.com/2305178/74532265-0e49db80-4f2f-11ea-8293-07c1ade04baf.png)

Is this in master, or I has my app just not updated yet? I'd be very disappointed if it went like that, it's exactly how Plex used to be, which is confusing and unhelpful for kids (and adults that need to tell them how much more they can watch!). Can I ask why it's changing?

If there's anything I can do to help with the Ends issue, just let me know. I thought I had it tracked down myself, but clearly not. :)

**Comment by AndreasGB** [comment]
Yes, this is the redesign in master that is currently being worked on by @Florianisme. 

Is it only the lack of an end time or is there more you would change to make it less confusing?

**Comment by BeecherNetworks** [comment]
Apologies, I forgot about this. The end time would certainly be a major loss, but in general it's incredibly minimalist compared to the current setup, is that by design? I don't know why you'd take all of that useful information off the screen.

**Comment by BeecherNetworks** [comment]
This is what I'm comparing against, in case I'm missing something. Nvidia Shield.

![info-far](https://user-images.githubusercontent.com/179583/75449904-c337bb80-5965-11ea-9398-226e50392552.jpg)

**Comment by dannycool87** [comment]
> This is what I'm comparing against, in case I'm missing something. Nvidia Shield.
> 
> ![info-far](https://user-images.githubusercontent.com/179583/75449904-c337bb80-5965-11ea-9398-226e50392552.jpg)
> 
> Seems like an awful lot of useful information is being removed.

I’m agree with him, I like to have the poster and the button for the audio and CC setting in this bar, can be little bit smaller if it’s a concern, but I would like to keep it if it’s possible. Like he said, look to much like Plex that is too simplistic in my mind.

**Comment by frode** [comment]
Hopefully they also fix the alignment of the content like "Ends 11:09 pm" with the space in there 👍🏼 
Noticed the code is: 
`return getString(R.string.lbl_ends) + android.text.format.DateFormat.getTimeFormat(this).format(new Date(endTimeTicks));`
And could be 
`return getString(R.string.lbl_ends) + " " + android.text.format.DateFormat.getTimeFormat(this).format(new Date(endTimeTicks)); `💯

**Comment by nielsvanvelzen** [comment]
Yeah that alignment is really annoying, definitely something that will be fixed when we re-add it.

**Comment by nielsvanvelzen** [comment]
Fixed in #616
