### ISSUE TITLE
The app creates channels every time it is started for the first time

### ISSUE THREAD

**Issue by pcurz** [jellyfin/jellyfin-androidtv#3381]
### Describe the bug

1. Start app and login
2. Check if channels are there in launcher
3. Wipe app data and do all steps again, and there will be duplicated channels

### Application version

0.16.5

### Where did you install the app from?

Google Play

### Device information

x96q

### Android version

Android 10

### Jellyfin server version

10.8.13

**Comment by pcurz** [comment]
> Are you using a third-party launcher or the stock Android TV one?

Stock Android TV One

**Comment by nielsvanvelzen** [comment]
Hmm weird, I'm not able to reproduce the issue and the code clearly clears any existing data before adding new ones. So duplicate channels shouldn't be possible.

**Comment by pcurz** [comment]
So my launcher is not the official one, I'll see what I can do
