### ISSUE TITLE
Option to ignore selfsigned TSL certificate

### ISSUE THREAD

**Issue by NextBlaubeere** [jellyfin/jellyfin-androidtv#3385]
### Describe the feature you'd like

Hello,

I run jellyfin behind a https proxy. It is internally only without access to the internet so I am only able to use self-signed certificates.
Is there a way to use the jellyfin android-tv app in such a case, without opting for http instead of https?

An option for that, when adding a server, would be great!

**Comment by nielsvanvelzen** [comment]
If you're using self-signed certificates you need to make sure they are installed on the device. The way to do this varies per Android flavor. We will **not** add a way to ignore SSL errors to the app.

**Comment by gclawes** [comment]
It's not possible to add trusted CAs to most Android TV devices like it is on standard Android.
