### ISSUE TITLE
Google Android TV using incorrect icon

### ISSUE THREAD

**Issue by dinki** [jellyfin/jellyfin-androidtv#34]
The icon being used for JF on Android TV appears to be a banner when it should be just the fin/triangle icon.  Here's what it looks like on my Xiaomi Mibox 3:

![image](https://user-images.githubusercontent.com/2521542/52314568-dd78b300-2978-11e9-8f8f-f520dde17418.png)

and this is how Emby's icon looks:
![image](https://user-images.githubusercontent.com/2521542/52314556-c4700200-2978-11e9-8585-86cb7e97e314.png)

**Comment by anthonylavado** [comment]
@thornbill remember to just tag us over at UX if you need any assets :-)

**Comment by grafixeyehero** [comment]
@thornbill i think this relating with a missing icon512
