### ISSUE TITLE
Music Queue does not Advance

### ISSUE THREAD

**Issue by GuestJim** [jellyfin/jellyfin-androidtv#3402]
### Describe the bug

If I start a music playlist or play an album, the first track will be played but Jellyfin does not advance to the second. If I have repeat enabled, it will repeat just the first track. This occurs whether I control the Amazon Fire Stick by its remote or use Jellyfin remote control.

I am not sure when exactly this started, as I do not always play music this way, but I believe this misbehavior started within the past few months.

### Application version

0.16.5

### Where did you install the app from?

Amazon Appstore

### Device information

Amazon Fire Stick 4K 

### Android version

Fire OS 6.7.0.1

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
So when you play music only a single track plays and it then just stops? Can you manually go to the next track?

**Comment by GuestJim** [comment]
Yes, that is correct, I can manually select the next track to play and it will, but playback would just stop if I did nothing.
Before submitting this reply I decided to test and confirm the behavior, and it seems a good thing I did because things have changed. What I reported did happen, but it seems the Fire Stick restarting has fixed some of it. More specifically, the stick was not responding so I had to unplug it to restart, and since then it has been advancing to the next track. During my previous round of testing, before opening the ticket, I tried stopping Jellyfin and clearing the cache on the stick, but the issue persisted.
However, with my continued testing, seeing if I can get it to break again, I did discover some more issues. I've not been able to get it to break as I had reported though, which is truly annoying.
First is the Repeat button is apparently now doing Repeat One instead of Repeat All as it had been. For one thing it will loop the current track but also if you turned on Repeat (All) previously, the Back button would be enabled, so you can skip back to the end of the queue. As I said above, the playback stopped before, so I was not confusing this with the originally reported behavior.
Second is the counter is not advancing, so despite it moving to track two, it will still say 1 of 29, or whatever the total is. It is showing the correct track title.
Third is I decided to test with another device being a remote control. I know this is a little broken at the moment, because if you try to start a playlist or album from the remote control, only the first track is sent, but sometimes forget or want to use a separate device to control instead of the Fire Stick's remote. Anyway, despite having a different device set to control, I cannot set Jellyfin to repeat from the device; the button is disabled even if I turned on Repeat directly on the Fire Stick.
(By the way, I have been assuming that issue of sending a playlist to the stick sends just the first track is known, but if it isn't I'll open a ticket for it.)
