### ISSUE TITLE
Request to change the default Android TV audio output setting to "Downmix to Stereo"

### ISSUE THREAD

**Issue by nathansmeal** [jellyfin/jellyfin-androidtv#3418]
### Describe the bug

1. Use a TV that only supports stereo audio
2. Download the Android TV Jellyfin app
3. Try to play surround sound capable media
4. Find that playback will not work unless the Audio Output setting is set to "Downmix to Stereo"

The same media will play correctly on the Jellyfin media player. I propose a change to the default setting to make it easier on the people unfamiliar with technology. Power users are able to change the settings to enable surround sound, instead of the other way around.

An alternative solution could be to implement an "auto" feature for detecting audio channels, similar to the android app, however I suspect this hasn't been done for good reason.

Disclaimer: this has really only been tested on the FireOS app. However I believe that this affects the android TV app as a whole.

### Application version

0.16.6

### Where did you install the app from?

None

### Device information

N/A

### Android version

Fire OS

### Jellyfin server version

10.8.13

**Comment by MichaelRUSF** [comment]
This would have a negative effect on most users. In that, downing mixing would mean that all surround sound media would unnecessarily be transcoded by default. There would likely be just as many, probably more, "nontechnical" users who would not know why their surround sound audio is being transcoded and why they are only getting stereo audio.  

Also, as far as I  know, this is not the default behavior of any other Jellyfin client.
