### ISSUE TITLE
The "Set audio/subtitle track based on previous item" setting does not work

### ISSUE THREAD

**Issue by dotleon** [jellyfin/jellyfin-androidtv#3424]
### Describe the bug

1. Have "Set audio track based on previous item" setting turned on in the web client
2. Start watching a series episode
3. change audio track
4. the next episode changes back to the preferred audio track, instead of remembering the previous one

This feature works in the web client.

### Application version

0.16.6

### Device information

Nvidia Shield Pro

### Android version

Android 11

### Jellyfin server version

10.8.11

**Comment by nielsvanvelzen** [comment]
Not a bug, we don't support this setting.

**Comment by mo-st** [comment]
Hi, I think this would be cool feature.
Do you think @nielsvanvelzen this would be possible for me to implement? I am a beginner in open source contributions and not yet familiar with this codebase but if you think it's generally feasible, I would be willing to give it a try with a PR. Thanks for your time and effort!

**Comment by nielsvanvelzen** [comment]
@mo-st I think #3754 already implements this but it is unfinished
