### ISSUE TITLE
Add DLNA player to possible players

### ISSUE THREAD

**Issue by ullmannJan** [jellyfin/jellyfin-androidtv#3426]
### Describe the feature you'd like

I think it is a great feature of jellyfin to stream movies to a TV via DLNA from other instances in the same network. The Jellyfin TV app does not have a feature to simply start a movie via DLNA on itself. The reason why this is useful is that the TV then uses its proprietary video player to show the movie. Which often has integrated frame interpolation and other nice features. However, this proprietary player can often not be chosen when selecting an "external player". 

Therefore I am suggesting the implementation of another player type "Play via DLNA" that simply opens the DLNA stream of the movie directly on the TV. This way one can browse the amazing looking library on the TV and then play the movie via DLNA on the TV. Currently this is only possible when browsing the library on an external App (Jellyfin Android App, etc.) or from the Web Interface and then stream to the TV.
I guess there need to be some checks in place to make sure the TV and the jellyfin server support DLNA. But these should already be present in the Android Jellyfin App somewhere.

Nevertheless, I think this is a useful and enhancing feature.

**Comment by nielsvanvelzen** [comment]
No this is out of scope for the app. The TV app can be remote controlled, but will never be the controller itself. If you want to use DLNA, use DLNA.
