### ISSUE TITLE
Display Message is not available

### ISSUE THREAD

**Issue by chadkouse** [jellyfin/jellyfin-androidtv#3428]
### Describe the bug

1. launch the jellyfin client for android tv on your device
2. Open the jellyfin web app on your browser
3. Go to the admin dashboard
4. Observe the Android TV client in the active devices list

Expected: Button to allow sending a message to the client (like the iOS client and web client)
Actual: No button

All I can think is that it's not reporting it's capabilities properly?  Looking at the web code I see:
```
btnCssClass = session.ServerId && session.SupportedCommands.indexOf('DisplayMessage') !== -1 && session.DeviceId !== ServerConnections.deviceId() ? '' : ' hide';
```

I can verify sending messages to iOS or Browser clients works

### Logs

The only bit of logging that even seems relevant is:
```
03-04 22:41:00.936  2036 11797 D org.jellyfin.sdk.api.sockets.SocketInstance: Reconnect requested
03-04 22:41:00.936  2036 11797 I org.jellyfin.sdk.api.sockets.SocketInstance: Reconnecting
03-04 22:41:00.936  2036 11797 D org.jellyfin.sdk.api.sockets.helper.ReconnectHelper: Notified about reconnect, attempts=15
03-04 22:41:00.937  2036 11797 I org.jellyfin.sdk.api.sockets.SocketInstance: Cancelling reconnect because baseUrl is null
```

### Application version

0.16.6

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

Android TV OS Version 12

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
The 4 lines of shared logs indicate the app is not signed in. There's no way to send messages to an unauthenticated device.

**Comment by chadkouse** [comment]
So whatever is causing this bug doesn't exist if I build and run the code from source (a71c2c8cb) - so I'll assume the next public release will have the fix :shrug:

**Comment by chadkouse** [comment]
Ok after testing and thinking I must be losing my mind I've determined that this only works _sometimes_. I havent figured out yet why that is but my hunch is that the websocket is losing connection and not reconnecting because when it works it works consistently.  I'm going to continue debugging.

**Comment by chadkouse** [comment]
I believe this is related to #3461

**Comment by chadkouse** [comment]
Closing in favor of #3461
