### ISSUE TITLE
Fire TV Stick 4k Max (2nd gen) AV1 Playback not working for all media

### ISSUE THREAD

**Issue by The-Randalorian** [jellyfin/jellyfin-androidtv#3432]
### Describe the bug

Many AV1 videos will attempt to direct play on a Fire TV Stick 4k Max (2nd gen), but will never start. This Fire TV stick should support this format according to the spec sheet (supports up to level 5.1/13, and most of my content is 5.0/12 or lower).

I have encountered this issue with 100% of the 4k videos I have tried, ~50% of the 1080p videos I tried, and 0% of the 480p videos I tried. I have found no rhyme or reason why some 1080p videos work and others don't. The media info included is for a 4k video that doesn't play. If you want additional media info, please let me know.

I tested on two different Fire TV sticks, one outside and one inside my local network, and both had the same issues with the same videos. I also tested libvlc, which solved the problem for 1080p, but was too laggy for 4k playback.

I've found two workarounds: 

* Force transcoding to HEVC via bitrate limit. This works but I have to manually change it frequently so it is as high as possible (to not lose quality) while still being lower than the content bitrate. This workaround also causes the server to tone map everything to SDR, which is not ideal.
* Side-load Kodi and use JellyCon (the Jellyfin for Kodi plugin seemed broken when I tried it due to a Kodi database update). This is a much more manual and difficult to set up process, but it does give me HDR and 4k.

### Media info of the file

```shell
Alita- Battle Angel (2019)
Container: mkv
Path: /media/Movies/Alita- Battle Angel (2019)/Alita- Battle Angel (2019).mkv
Size: 12860 MB

Video
Title: 4K AV1 HDR
Codec: AV1
Profile: Main
Level: 12
Resolution: 3840x1608
Aspect ratio: 2.40:1
Interlaced: No
Framerate: 23.976025
Bitrate: 14742 kbps
Bit depth: 10 bit
Video range: HDR
Video range type: HDR10
Color space: bt2020nc
Color transfer: smpte2084
Color primaries: bt2020
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: Surround 7.1 - Eng - TRUEHD - Default
Language: eng
Codec: TRUEHD
Layout: 7.1
Channels: 8 ch
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: Yes
Forced: No
External: No

Audio
Title: Surround 5.1 - Eng - Dolby Digital - Default
Language: eng
Codec: AC3
Layout: 5.1
Channels: 6 ch
Bitrate: 640 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

Audio
Title: Stereo - Eng - DTS-HD MA
Language: eng
Codec: DTS
Profile: DTS-HD MA
Layout: stereo
Channels: 2 ch
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: No
Forced: No
External: No

Audio
Title: Stereo - Eng - DTS
Language: eng
Codec: DTS
Profile: DTS
Layout: stereo
Channels: 2 ch
Bitrate: 1536 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Surround 5.1 - Eng - Dolby Digital
Language: eng
Codec: AC3
Layout: 5.1
Channels: 6 ch
Bitrate: 448 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: Eng - PGSSUB
Language: eng
Codec: PGSSUB
Default: No
Forced: No
External: No
```

### Application version

0.16.6

### Device information

Amazon Fire TV Stick 4k Max (2nd gen) [AFTKRT]

### Android version

Fire OS 8.1.0.3

### Jellyfin server version

10.8.13

Edit: Added additional tests and workaround information.

**Comment by RBetting77** [comment]
> Amazon Fire TV Stick 4k Max (2nd gen) [AFTKRT], firmware FireOS 8.1.2.5. Same problem, I have installed the App from Amazon AppStore, and many .mkv movies in h265, it is not possible to play them, however with my previous Amazon Fire TV Stick 4k Max (1nd gen) [AFTKA] firmware FireOS 7.6.8.5, it plays them without problems.

As Jellyfin uses ExoPlayer on Android by default.
For support, you can find the ExoPlayer project here: https://github.com/androidx/media

**Comment by sixerstyle** [comment]
Same here, Amazon Fire TV Stick 4k Max (2nd gen)  doesnt play AV1 Videos
