### ISSUE TITLE
Moving the Trailer button

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#3450]
### Describe the feature you'd like

Currently the trailer button is hidden behind the ... menu when going into a new TV Show 
![Screenshot 2024-03-16 at 12 41 45](https://github.com/jellyfin/jellyfin-androidtv/assets/69896780/28869299-c190-4b0b-ac33-a0f1ebe85d18)
Yet once fully watched the Play Next Up button gets removed and the trailer button is displayed.
![Screenshot 2024-03-16 at 12 41 33](https://github.com/jellyfin/jellyfin-androidtv/assets/69896780/c1192112-47c2-412b-aa70-3dd92712a6bc)

I found that many users don't know that the trailer of a series is available under the ... menu. Is it not possible to move it ?

Also what is the purpose of the "Shuffle all" button in a TV series?

**Comment by oddstr13** [comment]
Some people have explicitly requested the shuffle all feature for series.
They usually utilize it for background noise kinda thing from shows they've already watched, while doing other things.

Personally, I'd hide the shuffle all button in the context menu *too*, as "most people" are not interested in that feature (and I think the same can be said for trailers).

*Ideally* this would be fully customizable (as a user setting), but that sounds like a hassle to implement and maintain.

**Comment by ShakeSp33r** [comment]
Agree, would also hide the shuffle button

**Comment by nielsvanvelzen** [comment]
It makes sense to re-order these buttons a bit. The source for them is in `FullDetailsFragment.java` if anyone is willing to pick this up. Be aware that changing those buttons affects all item types.

**Comment by ameetmaurya** [comment]
hey @nielsvanvelzen ,I am new contributor here and I did like to work on this issue.Please assign this to me.
