### ISSUE TITLE
trailer button - fire stick 

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-androidtv#346]
Hello,

Could you implement the trailer button for the amazon fire stick like you did for the web ?

Regards,

Kevni

**Comment by nielsvanvelzen** [comment]
Hi there, we're actively working on revamping the "details screen" (as we call it). Local trailers will be added and we're looking into adding external trailers (the ones that play via YouTube).

**Comment by AndreasGB** [comment]
By the way, local trailers should work in the current release version already. If you have downloaded trailers and added them to a `trailers` subfolder in the folder of your movie, the button should appear.

**Comment by thornbill** [comment]
Duplicate of #71
