### ISSUE TITLE
Status of Jellyfin 10.9 support

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-androidtv#3467]
This issue will be updated with the status for Jellyfin 10.9. Additional updates will be posted in comments, subscribe to this issue to receive updates.

# Current status: Jellyfin 10.9 is **compatible** starting from 0.16.8

You can try and use the app but there might still be small problems when your server is using Jellyfin 10.9. If you encounter any issues, please report them so we can make sure the app is working correctly. Optionally downgrade back to 10.8.13 and restore a backup.

**Please refrain from commenting on this issue, open a separate issue to report problems not listed here.**

**Comment by nielsvanvelzen** [comment]
Started work on updating the SDK in jellyfin/jellyfin-sdk-kotlin#888. This is the code that talks with the Jellyfin API and needs to be updated for each Jellyfin release. 10.9 being as big as it is this will take some time, the initial changes are not sufficient nor ready for a release.

At the same time I'm analyzing the API changes to find any backward-compatible breaking changes. These will need to be fixed in the server. This way all current installs of the apps can still work with 10.9.

**Comment by nielsvanvelzen** [comment]
It is not possible to login with the current unstable build right now. I've found the issue causing this and it made a [bugfix](https://github.com/jellyfin/jellyfin/pull/11232) for the server. It should be included with the next unstable build.

**Comment by nielsvanvelzen** [comment]
It is not possible to use media with lyrics right now. Trying to play such media may fail or crash the app. Some other functionality that retrieves item lists (like browsing/searching/system integration) may also stop working.

It is also possible the app might crash/fail to show TV series with the newly added "unreleased" status. The likelihood of this happening is low as none of our metadata plugins currently provide this status.

I'm working on a solution for both of these problems. This solution is most likely going to be an update of our SDK and a (patch-)release of the app.

**Comment by nielsvanvelzen** [comment]
We still have many moving parts in the server and the API changes are not 100% ready yet. I'm waiting until we can freeze the API state before releasing the patched versions of our SDK and app to fix the previously mentioned issues (lyrics and "unreleased" potentially crashing the app in some cases).

The login issue is now fully fixed, but due to some build issues in our packaging repositories this fix is not available for all platforms (yet).

**Comment by nielsvanvelzen** [comment]
I've just tagged [v0.16.8](https://github.com/jellyfin/jellyfin-androidtv/releases/tag/v0.16.8) which fixes playback & browsing on 10.9 (issues mentioned in previous comments). With this the app should be fully compatible with 10.9! If any issues arise (especially crashes) please create an issue to let me know.

The v0.16.8 version should be available in the stores within the next few days.

**Comment by nielsvanvelzen** [comment]
Unfortunately Google (wrongfully) rejected the app update. We've solved the issue but they require a new app update (can't republish 0.16.8).

I've decided to skip 0.16.8 for on the Google Play store for now instead of creating another release just for Google.

**Comment by tundrablasen** [comment]
good morning all

@nielsvanvelzen where will you announce if we can safely update to 10.9.x of jellyfin server? Im staying on 10.8.3 because I have seen that there are still some fixes to do and my family is depended on the android tv client (I myself use Kodi due to the subtitles failed loading saga).

should we check this thread here when its closed? thanks for the heads up and have a good day

**Comment by nielsvanvelzen** [comment]
The app has been fully compatible with 10.9 since April 9th (so before the stable release). All app stores currently offer a 10.9 compatible version.

I've kept this issue open to announce when the app will drop 10.8 support. I'll repeat this line from the starting post for everyone that did not read: **Please refrain from commenting on this issue, open a separate issue to report problems not listed here.**

**Comment by nielsvanvelzen** [comment]
The first beta for version 0.17 is now publishing with a requirement on Jellyfin 10.9.0 or newer. This finalizes this issue.
