### ISSUE TITLE
Subtitles can be delivered when using MX Player

### ISSUE THREAD

**Issue by chuwza** [jellyfin/jellyfin-androidtv#3469]
### Describe the feature you'd like

Hi, Jellyfin on mobile phones can pass subtitles to MX Player when using the MX Player player.

However, Jellyfin on Android TV does not support this feature, which prevents it from playing properly with MX Player.

Can this feature be supported?

**Comment by nielsvanvelzen** [comment]
We already pass the subtitles to external players. If they don't show it you'll have to report it to them.
