### ISSUE TITLE
trailer playback on youtube doesn't return to movie page on jellyfin

### ISSUE THREAD

**Issue by d03j** [jellyfin/jellyfin-androidtv#3476]
### Describe the bug

1. go to a movie
2. click on play trailer
3. TV opens trailer on youtube
4. after trailer ends pressing remote's back button takes you back to jellyfin's start (login) screen

Ideally it would return to the movie's page, like it does when using a web browser.

### Application version

0.16.7

### Device information

MTC BAUHN Android TV

### Android version

Android 9 kernel 4.9.118+

### Jellyfin server version

10.8.13 linux x64

**Comment by nielsvanvelzen** [comment]
YouTube decided to trap you in their app. Nothing we can do about that. Report it to Google.

**Comment by d03j** [comment]
so, no way to play it in app or at least ensure that when returning to the jellyfin app, we return to the page/film that called youtube?

**Comment by decodedencoder** [comment]
This is still an issue. If you exit the YouTube app, it should land you back to the Jellyfin movie page you were on. The issue is that Jellyfin appears to be shutting down when we click the trailer button and YouTube opens up. Can we prevent the Jellyfin app from closing upon trailer launch?
