### ISSUE TITLE
Some controls stop working on Android TV app

### ISSUE THREAD

**Issue by sudofox** [jellyfin/jellyfin-androidtv#3489]
### Describe the bug

I'm not sure what causes this and I don't have a lot of extra information. I have a Hisense 4K TV and the latest Google Play version of the app. 

https://github.com/jellyfin/jellyfin-androidtv/assets/3847441/4c5b3480-716f-436f-84f6-8d3a43fd9261

### Application version

jellyfin-androidtv0.16.7 release

### Device information

Hisense SmartTV 4K

### Android version

Android 10

### Jellyfin server version

Unknown, latest

**Comment by acidmanifesto** [comment]
In my case every time I try to seek/fast fwd and rewind back it just restarts the video from the beginning. Resuming from a previous point just restarts the video as well.

I do not have this issue in browser or the android mobile app

**Comment by nielsvanvelzen** [comment]
This behavior is definitely strange, I've never seen this happen before. Does this happen for all playback, or just specific files?

**Comment by sudofox** [comment]
It doesn't occur consistently, but when it does I often have to do a full close/reboot to resolve things. Doesn't seem to be tied to any particular content that I can discern as yet

**Comment by acidmanifesto** [comment]
> It doesn't occur consistently, but when it does I often have to do a full close/reboot to resolve things. Doesn't seem to be tied to any particular content that I can discern as yet

Sorta of the same but also I been noticing issues with av1 encodes with restarts not correcting the av1 encoder specifically.
