### ISSUE TITLE
[Issue]: Local  "Strm"  files can't be played on the jellyfin TV clients (android),but in the browser(like edge) can play strm file

### ISSUE THREAD

**Issue by newrookie001** [jellyfin/jellyfin-androidtv#3496]
### Describe the bug

i have some movie is strm file type，i can see the movie in the pc browser (use Transcoding),and sometimes also can be palyed in the android  phone (sometime can't be played about same file）。But  it's not be played on the TV client。
so please update or fix the jellyfin tv client to smoother suppourt the strm file  

### Application version

0.14.0

### Where did you install the app from?

None

### Device information

Hisense

### Android version

Android 

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
Perhaps you should update both your server (to 10.8.3) and the app (to 10.16.7) first.

**Comment by nielsvanvelzen** [comment]
Thanks for confirming the issue on the latest versions. From those logs it looks like the problem is in the server (the ffprobe appears to fail) so not much I can do about it on the client side.
