### ISSUE TITLE
Unable to use voice search with Nvidia Shield TV.

### ISSUE THREAD

**Issue by smidley** [jellyfin/jellyfin-androidtv#35]
When using the search functionality, I get prompted to allow Jellyfin to record audio.  After allowing this, I'm not able to use the voice search functionality.  Tried the big search button as well as the small magnifying glass button at the top of a section, both don't work with voice search using the nvidia shield remote.

**Comment by smidley** [comment]
Using server version 10.0.2.0
Using Android TV App dated Jan 29 2019.

**Comment by nielsvanvelzen** [comment]
Are you still experiencing this issue?

**Comment by smidley** [comment]
I no longer have a way to test this.  I’ve moved from the shield to the Apple TV.
