### ISSUE TITLE
Fast forward and rewind buttons no longer work with new player overlay

### ISSUE THREAD

**Issue by thornbill** [jellyfin/jellyfin-androidtv#351]
It seems the fast forward and rewind buttons on Fire TV remotes no longer work after the player overlay redesign.

**Comment by nielsvanvelzen** [comment]
Related:
- #308 
- #254

Might be the same issue although those reports are from before 0.12

**Comment by MrLemur** [comment]
After building master today, I can confirm I am seeing the same issue.

Cannot rewind or fast forward via Fire TV remote or by pressing right on the seek bar. Same if I try via CEC remote.
