### ISSUE TITLE
Next Up items on homescreen not updating position

### ISSUE THREAD

**Issue by fice-t** [jellyfin/jellyfin-androidtv#3525]
### Describe the bug

1. Watch to completion a TV episode in Jellyfin (so the homescreen item is of type `WATCH_NEXT_TYPE_NEXT`).
2. Watch to completion an episode in another app (for example, Prime Videos), so that the homescreen item is shown before the Jellyfin item.
3. Watch to completion the next episode of the series in Step 1.
4. The item position is not updated, whereas items of other services would be updated.

I understand that Jellyfin takes some time to update the homescreen items, but even when the item is updated the position stays the same.

I believe this is due to items of type `WATCH_NEXT_TYPE_NEXT` [having engagement time set to item.dateCreated](https://github.com/jellyfin/jellyfin-androidtv/blob/940d41322ee5981d31ef064084cc665cf952b269/app/src/main/java/org/jellyfin/androidtv/integration/LeanbackChannelWorker.kt#L439).

FWIW, looking at [a Google sample app](https://github.com/android/tv-samples/blob/125b6ac49c3b47cc9cd9a380e40ec49816f63571/ReferenceAppKotlin/app/src/main/java/com/android/tv/reference/watchnext/WatchNextHelper.kt#L87), the engagement time is always set to the current time (though that also seems incorrect). The official docs aren't clear for this case, unfortunately, as [the description here](https://developer.android.com/reference/kotlin/androidx/tvprovider/media/tv/TvContractCompat.WatchNextPrograms#COLUMN_LAST_ENGAGEMENT_TIME_UTC_MILLIS()) states "the date of the last episode watched", but [the description here](https://developer.android.com/training/tv/discovery/watch-next-programs) is "The time the user or app last engaged with the program".

I would argue the 2nd description makes more sense, and the 1st a documentation bug. Perhaps it was meant to be "the date the last episode was watched"?

### Application version

0.16.7

### Where did you install the app from?

Google Play

### Device information

Proprietary ATV Box

### Android version

Android 10

### Jellyfin server version

10.8.13

**Comment by Cebrain** [comment]
I think there is already an issue
https://github.com/jellyfin/jellyfin-androidtv/issues/3139

**Comment by nielsvanvelzen** [comment]
It is not trivial to retrieve the timestamp of when the previous episode was watched. As such we're using the timestamp from when the episode was added to Jellyfin instead.
