### ISSUE TITLE
black screen on playback end

### ISSUE THREAD

**Issue by reitenth** [jellyfin/jellyfin-androidtv#3533]
### Describe the bug

i watch and episode and it hangs on playback end to a black screen, never taking me back to home unless i manually do it. i have tried lib and exoplayer and they both have the issue. 

### Application version

0.16.10

### Where did you install the app from?

Google Play

### Device information

nvidia shield pro 2017

### Android version

android 11

### Jellyfin server version

10.8.13

**Comment by reitenth** [comment]
So a little testing, it only happens on my profile, not a second profile I made

**Comment by nielsvanvelzen** [comment]
Please head to our forum or chat rooms for troubleshooting help: https://jellyfin.org/contact
