### ISSUE TITLE
Subtitle and Audio don't sync via server

### ISSUE THREAD

**Issue by youland** [jellyfin/jellyfin-androidtv#3534]
### Describe the bug

1,Docker install Jellyfin latest.
2,TV install Jellyfin-TV latest.
3,Server--setting--Subtitle--Subtitle language preference----Chinese.Server--setting--Audio--Audio preference----Chinese
4,The series is subtitle in Japanese,English,Chinese and Audio in Japanese and Chinese.
5,When playing on TV, Japanese and Japanese are displayed by default.

### Application version

0.16.0

### Where did you install the app from?

None

### Device information

Sony 65x91

### Android version

Andriod 10

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
You are 10 versions behind. Please update the app.

**Comment by youland** [comment]
Sorry,update infomation.
I always installed jellyfin-androidtv-v0.16.10-release.apk on TV.
