### ISSUE TITLE
Jellyfin 0.16.10 not working on Android TV 11

### ISSUE THREAD

**Issue by harmangrewal80** [jellyfin/jellyfin-androidtv#3535]
### Describe the bug

1. Open Jellyfin on Android TV OS 11, model HA90, projector firmware v103
2. The folder structure does not display properly 
3. None of the Videos play at all
4. Only showing "Continue Watching" section and not displaying any folders under "My Media"
5. Was working before the latest Jellyfin update and this exact jellyfin version works fine on Amazon Fire OS

### Application version

0.16.10

### Where did you install the app from?

Google Play

### Device information

EPSON HA90

### Android version

Android TV OS 11, Kernel 5.4.242

### Jellyfin server version

10.8.9

**Comment by nielsvanvelzen** [comment]
We have not introduced any changes related to browsing in the last few updates. Please head to our forum or chat rooms for troubleshooting help: https://jellyfin.org/contact
