### ISSUE TITLE
add Jellyfin as Youtube option

### ISSUE THREAD

**Issue by jumoog** [jellyfin/jellyfin-androidtv#3539]
### Describe the feature you'd like

I noticed that if I hold down the YouTube button on my Google Chrome Cast remote, I can select a YouTube app. It would be nice if it was possible to select Jellyfin here. It would be a super quick way to access Jellyfin.

**Comment by nielsvanvelzen** [comment]
You mean to remap a button on your remote to open the Jellyfin app? That's out-of-scope for our app, there are third party ones that allow you to do that though.
