### ISSUE TITLE
Quick connect code displayed in reverse on rtl languages

### ISSUE THREAD

**Issue by sheepster1** [jellyfin/jellyfin-androidtv#3552]
### Describe the bug

1. Android language is set to Hebrew (I am guessing this applied to other rtl languages too)
2. Use quick connect to log in. 
3. The code that is shown `xxx yyy` doesn't work when entering on the phone (set to english, but i didn't test it on hebrew too). 
4. If you try to enter the code in reverse (`yyy xxx`), it does work.

### Application version

0.16.10

### Where did you install the app from?

Google Play

### Device information

chromecast and a sony tv that runs android tv

### Android version

12

### Jellyfin server version

10.8.13

**Comment by sheepster1** [comment]
Looked into the code a little, And I am guessing this issue is caused [here](https://github.com/jellyfin/jellyfin-androidtv/blob/e596cf80a00803e5ccd2e5ca64555670cf56426a/app/src/main/java/org/jellyfin/androidtv/ui/startup/fragment/UserLoginQuickConnectFragment.kt#L92) when we are adding a space. When the app is displaying it in RTL, it gets flipped, since its a single text box.

To solve this, I think we could replace the separator char to `,` or `-`. Another option will be to separate the 2 parts of the code into 2 different elements that will not be affected by RTL.

WDYT?

**Comment by nielsvanvelzen** [comment]
Do I understand correctly that the code "123 456" would show up as "456 123"? We could probably force it to display as LTR to fix that and keep the whitespace.

**Comment by sheepster1** [comment]
@nielsvanvelzen yes, you understand correctly.
That sounds like a good option too

**Comment by nielsvanvelzen** [comment]
Thanks for the report, I was able to reproduce the issue and fix it for the next release!

**Comment by sheepster1** [comment]
Thank you!
