### ISSUE TITLE
App shows sensitive screenshots on add user page before login has occured.

### ISSUE THREAD

**Issue by esmorun** [jellyfin/jellyfin-androidtv#3561]
### Describe the bug

1. Do a fresh install of the Jellyfin Android TV app (or remove server from the cogwheel menu).
2. Enter your Jellyfin server address.
3. Press add user.

The app will now show you a background image with a bunch of screenshots from the content on the server. I consider this a privacy breach, the app should not show any content before a user has signed in. In its current form, anyone can get a sneak peek at content from libraries that are supposed to have restricted access.

### Application version

0.16.10

### Where did you install the app from?

Google Play

### Device information

Doesn't matter

### Android version

Doesn't matter

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
Not a client issue, you enabled the splash screen yourself in the server settings.

**Comment by esmorun** [comment]
> Not a client issue, you enabled the splash screen yourself in the server settings.

Thanks for clearing that up 👍. I never enabled such a thing myself though, it was enabled for me during an update without my knowledge.
