### ISSUE TITLE
Option for preferred login method

### ISSUE THREAD

**Issue by ChristopherBull** [jellyfin/jellyfin-androidtv#3568]
### Describe the feature you'd like

Accounts with a password (or especially a PIN) can be quicker to login with these credentials rather than the Quick Connect method. This is especially true for users who do not have access to a Jellyfin mobile app.

I would prefer certain accounts be able to default to PIN/password Auth screens.

**Comment by nielsvanvelzen** [comment]
The pin feature is removed in Jellyfin 10.9 as it has since been replaced with QuickConnect. We will always prefer QuickConnect when available on the server. If you want to always enter a password you can disable QuickConnect completely in the dashboard.
