### ISSUE TITLE
TV doesn't support music lyrics

### ISSUE THREAD

**Issue by bosidiA** [jellyfin/jellyfin-androidtv#3571]
### Describe the feature you'd like

Why doesn't the TV support music lyrics
Cell phone web page can display lyrics normally

**Comment by bosidiA** [comment]
It's been a long time waiting for the 10.9 release
It was a bit of a letdown to find out that the TV didn't support music lyrics

**Comment by nielsvanvelzen** [comment]
#2988

**Comment by bosidiA** [comment]
Yes, today updated 10.9.1 mobile and web lyrics work fine, but unfortunately Android TV 0.16.10 doesn't support music lyrics yet, keep looking forward to it ....
Thank you very much!
