### ISSUE TITLE
Allow changing seek duration

### ISSUE THREAD

**Issue by PythonCoderAS** [jellyfin/jellyfin-androidtv#3583]
### Describe the feature you'd like

I would like to be able to change the seek amount to 10 seconds (or another custom value). 30 seconds is too large of a time for seeking, especially if I’m trying to skip intros or a recap.

**Comment by tydog98** [comment]
Another thing to consider could possibly be variable seeking depending on how many times the button is pressed. I have a Kodi add on that does like 10 seconds for 1 tap, 30 for 2, and 1 minute for 3. Pretty convenient.

**Comment by Migs3** [comment]
#3547

**Comment by iluvatyr** [comment]
Absolutely agree with this!

**Comment by peripi** [comment]
Im using jellyfin to analyze football games, 30 seconds is way to long. Configurable or multi-press would solve the issue.

**Comment by ravisairockey** [comment]
any solutions yet?

**Comment by tydog98** [comment]
> any solutions yet?

It's been implemented

**Comment by nielsvanvelzen** [comment]
Closing as fixed
