### ISSUE TITLE
Next up screen doesn't work with external players

### ISSUE THREAD

**Issue by sjiawjbssj** [jellyfin/jellyfin-androidtv#3604]
### Describe the bug

When watching TV Shows after the episode ends the external player selection dialog is shown immediately even though I have activated the next up screen in the settings.

### Application version

0.16.10

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro (2017)

### Android version

Android 9

### Jellyfin server version

10.8.13

**Comment by nielsvanvelzen** [comment]
The next up screen is not used for the external player. This intended behavior.

**Comment by nielsvanvelzen** [comment]
The code paths for in-app playback and external playback are completely different. It takes a lot of effort to maintain a feature we'd rather drop.

Closing as wontfix.
