### ISSUE TITLE
DV content not getting transcoded for client that doesn't support DV

### ISSUE THREAD

**Issue by morkyy** [jellyfin/jellyfin-androidtv#3608]
### Describe the bug

When playing content that should otherwise direct play, on a TV that doesn't support DV, this doesn't trigger a transcode.

Tested on both Chromecast with Google TV and Nvidia shield on app version 0.16.10 and jellyfin version 10.8.13.

TV does not support DV but all DV content direct plays resulting in green/purple colours. 

When forcing transcode by lowering quality content get properly tonemapped.

Instead of direct playing, content should transcode if it's DV and plays on a client that doesn't support DV. 

### Application version

0.16.1p

### Device information

Nvidia shield pro and Chromecast with Google tv

### Android version

Latest 

### Jellyfin server version

10.8.13

**Comment by Zachwang007** [comment]
yes it's true

**Comment by Simsala91** [comment]
Having a very similar issue, though instead of getting wrong colors it just shows a black screen with audio playing normally.

Devices: Xiaomi Box S (2nd Gen) connected to a Samsung TV. Both devices don't support DV, yet it plays it directly resulting in black screen. When playing the same movie from a browser, it gets transcoded properly, so the server itself is capable of transcoding.

Jellyfin Server version 10.9.6

**Comment by tianiue** [comment]
Encounter the same problem

> Having a very similar issue, though instead of getting wrong colors it just shows a black screen with audio playing normally.
> 
> Devices: Xiaomi Box S (2nd Gen) connected to a Samsung TV. Both devices don't support DV, yet it plays it directly resulting in black screen. When playing the same movie from a browser, it gets transcoded properly, so the server itself is capable of transcoding.
> 
> Jellyfin Server version 10.9.6

遇到问题类似设备启动时快速开启应用播放视频，部分视频可以转码，色彩正常，退出应用再次打开出现黑屏有声音
Device start quickly open the application to play video, part of the transcoding, color is normal, exit the application again open black screen sound

**Comment by tianiue** [comment]
> Having a very similar issue, though instead of getting wrong colors it just shows a black screen with audio playing normally.
> 
> Devices: Xiaomi Box S (2nd Gen) connected to a Samsung TV. Both devices don't support DV, yet it plays it directly resulting in black screen. When playing the same movie from a browser, it gets transcoded properly, so the server itself is capable of transcoding.
> 
> Jellyfin Server version 10.9.6

Encounter problems similar When the device starts, quickly open the app and play the video. Some videos can be transcoded, and the color is normal. Exit the app and play the video again, and there black screen with audio playing normally.
