### ISSUE TITLE
UI Images in all menus not loading on Nvidia Shield Pro using releases newer than 0.15.12 

### ISSUE THREAD

**Issue by Mister-Odd** [jellyfin/jellyfin-androidtv#3609]
### Describe the bug

I've tried the latest and 16.0+ and a couple of 16 betas. 

In version 0.16 beta x to the latest, on two different Shield Pros, all thumbnails, actor images, posters, etc. do not load. The blurred version of them "flash" like they are going to load (can slow down animations in the shield's dev options to watch it), but the blurred images do not load either. Placeholders and folders are loaded instead (in the theme's color). Icons (gear, user, etc.) do load normally. 
I have enable/disabled every jellyfin UI option in the app. I have upgraded the server to 10.9.3 - without success. I have factory reset one of the Shields, using default settings and same result. I have disabled/enable related shield apps/settings. I have installed Nvidia's developer rooted ISO - no change (and major PITA). 
Android TV home screen recommendations, have the same place-holder/no image issue.

All other functions of the app work great. Titles, actor names, playback, etc - no issues.

There are so many changes in 0.16 it's impossible for me to track it to a single change (as a Linux script-kiddie I wouldn't even know where to begin).

My shot in the dark wild guesses?

Android TV 11 vs Android 14 SDK ?
blurHashPainter composable not loading fast enough?
LibraryDreamService  hates me?

I'm chilling on 0.15.12 and happy to have my images back. 

Let me know if you want me to test anything - but remember, script kiddie here, you'll have to hold my hand and tell me I'm a good boy the whole time.

~Cheers!

### Application version

.0.16.10

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android TV 11 - 9.1.1(33.2.0157) Shield TV SW 

### Jellyfin server version

10.9.3

**Comment by nielsvanvelzen** [comment]
You'll need to use logcat to get the logs from a device: https://wiki.lineageos.org/how-to/logcat. Make sure to reproduce the issue just before getting the logs.

**Comment by Mister-Odd** [comment]
Making sure I understand.. 

On the Nvidia Shield after the images don't show on an new install of 0.16.x, run command:

`adb logcat -d > logcat.txt`

Question - Where would I run that command on the shield? I can hook up a keyboard, but I haven't noticed a shell or prompt to run a command on. .. or maybe it's run on the Jellyfin LXC (Linux container) server???

**Comment by nielsvanvelzen** [comment]
No you need to connect to the Android device from your computer using adb, then use the adb logcat command.

**Comment by Mister-Odd** [comment]
Ah yes - that makes sense!

I'm currently in the middle of a NixOS learning curve on my laptop and, it's going to be a bit before I'm able to get those logs for you. I may try later today, to get the Shield to talk to Nix, but tomorrow is more likely.

I assumed that this would be a wide spread issue on the Shields. Am I the only person seeing this? Do you think Android TV ver. 11 is the issue ? I do have a WAF on the LAN.. I guess it could be interfering, I'll check it's logs too!

**Comment by pascalwei** [comment]
> I assumed that this would be a wide spread issue on the Shields. Am I the only person seeing this? Do you think Android TV ver. 11 is the issue ? I do have a WAF on the LAN.. I guess it could be interfering, I'll check it's logs too!

I'm on v0.16.11 and don't experience the issue you describe on my Shield Pro. You may try to visit the demo server to see if it's an issue with your self-hosted server:

https://demo.jellyfin.org/stable

A while ago I had some issues with a CSP for Jellyfin in the reverse proxy. That's another thing you could look into if you got a CSP configured. That should be visible in the logs though.

**Comment by nielsvanvelzen** [comment]
The issue is most likely caused by some misconfiguration in a firewall/reverse proxy. We previously saw this issue when connecting to your server via an ipv6 address but that has been fixed since we switched to a different (maintained) image library.

**Comment by Mister-Odd** [comment]
It is in fact addressed to go though a local NGINX reverse proxy (no CSP filters set for that link - but good to know!).. websock supported in the proxy settings. Nice catch @pascalwei - glad to know it's working yours too!

I guess it could be the LAN side (nothing is hosted to the WAN), IPS or WAF getting `drop` happy on folder images.. odd that it's okay with everything else (Icons/Video .16+, everything on .15.12) though?

Across all my tests, not once did I try the direct IPv4 address. I'll give it a shot in the morning!

**Comment by Mister-Odd** [comment]
Okay - I didn't wait until morning..

All images work great on .16.11 without a reverse proxy in the way.. That's all I changed, dropped the fqdn and used the direct ip and "poof" working fine.

I'll have to look deeper into it all in morning. 

Thank you @nielsvanvelzen and @pascalwei  - fine work!
