### ISSUE TITLE
Grey bar appears at top of the screen when opening menu during playback

### ISSUE THREAD

**Issue by S-North** [jellyfin/jellyfin-androidtv#3622]
### Describe the bug

1. start playing a film/show
2. open a menu e.g. subtitles or bitrate
3. grey bar appears at top of the screen and remains until backing out to the film details page.

The grey bar disapears if I back out to the details page (stop playing the film) then resume. But it returns the moment I open a menu again.
This is really disruptive for fims with subtitles that need to be turned on or off (there is no way to set this on the details page like in jellyfin-web), and the film/show has an aspect ratio that uses the top of the screen e.g. 4:3.

### Application version

0.16.11

### Where did you install the app from?

Sideloaded APK

### Device information

A95x F3

### Android version

Android 9

### Jellyfin server version

10.9.2

**Comment by nielsvanvelzen** [comment]
Would it be possible to share a screenshot of this issue? I've never heard of the menus causing such a problem

**Comment by S-North** [comment]
Sure
Before opening a menu
![Uploading 2024-05-30-11-49-43-136.jpg…]()

After opening a menu
![2024-05-30-11-50-11-509](https://github.com/jellyfin/jellyfin-androidtv/assets/8228899/5069e698-8fdb-42ad-bb36-7a04d3053982)

I don't get this on the standard android app, only this androidtv.

**Comment by nielsvanvelzen** [comment]
I have no idea what may cause this issue. It feels like an issue with the operating system that comes with your specific device. Are you able to try the app on a different device?

**Comment by nielsvanvelzen** [comment]
Does it happen with all videos or just specific ones?

**Comment by S-North** [comment]
All videos
