### ISSUE TITLE
Minor transparency bug since latest update (0.16.11) on Fire stick 4K 

### ISSUE THREAD

**Issue by ExpatUK** [jellyfin/jellyfin-androidtv#3628]
### Describe the bug

1. Play any TV series
2. Notice the banner in the top left no longer displays transparency, but has a black infill.
3. From my limited testing, this doesn't seem to affect Movies(?!)
4. Bridgerton was very noticeable.

### Application version

0.16.11

### Device information

Fire TV Stick 4K (1st Generation)

### Android version

FireOS

### Jellyfin server version

10.9.3

**Comment by nielsvanvelzen** [comment]
Did you verify the image does indeed have a transparent background?

**Comment by ExpatUK** [comment]
I did indeed. It seems limited to all TV shows - doesn't affect films. Same images work fine in other clients, web player, etc. It also shows whilst browsing more info for a specific series - not just in the player.

**Comment by ExpatUK** [comment]
This issu
