### ISSUE TITLE
The automatic sign in function does not work

### ISSUE THREAD

**Issue by yangtao9808** [jellyfin/jellyfin-androidtv#3631]
### Describe the bug

The automatic sign in function does not work, and the app always logs in with the user who logged in last time, rather than the set user.

### Application version

0.16.11

### Where did you install the app from?

None

### Device information

SONY TV x60j

### Android version

android 10

### Jellyfin server version

10.9.3

**Comment by nielsvanvelzen** [comment]
Make sure to **close** the app. If you press the home icon on the remote the app is not closed but put to the background instead, meaning the app does not have to sign-in again when you open it because it is already open.

**Comment by yangtao9808** [comment]
I’m sure I’ve close the app. The last well-working version is 0.15.11.  This function has been invalid since 0.16.0. I have test this function on different TVs.发自我的 iPhone在 2024年6月1日，16:54，Niels van Velzen ***@***.***> 写道：﻿
Make sure to close the app. If you press the home icon on the remote the app is not closed but put to the background instead, meaning the app does not have to sign-in again when you open it because it is already open.

**Comment by yangtao9808** [comment]
In the latest version 0.17.6, this issue has not been fixed yet.

**Comment by nielsvanvelzen** [comment]
I'm unable to reproduce the issue and you're the only reporter of it so it does feel like something is wrong with your configuration. I'd recommend using our troubleshooting channels over at Matrix/Discord to figure out what's going wrong: https://jellyfin.org/contact
