### ISSUE TITLE
login screen, hide/show last time connected

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-androidtv#364]
Hello devs :)

Is it possible to add a feature from the login screen ?
hide or show last time connected
![IMG_20200227_001500](https://user-images.githubusercontent.com/58141187/75397501-4e2d9d00-58f7-11ea-91a7-9b7cb2cfe91c.jpg)

Regards,

le lama malgache

**Comment by thornbill** [comment]
Just to be clear, you want a setting to hide the last connected time? Should this only apply to the Android TV app or all clients?

**Comment by lelamamalgache** [comment]
Hey @thornbill  :)

For the context, i have my jellyfin server on my home and my friends and me using the fire tv stick as device.

On jellyfin web, "last time connected" is OFF
On jellyfin android mobile, "last time connected" is OFF
On jellyfin android fire tv stick "last time connected" is ON

i don't want to share my last time connected if i watch a tv show until 3am, you know what i mean.

to reply to your request, all clients have by default the last time connected is off  except the fire tv stick, so i would like to desactive the last time connected to the fire stick.

i don't know if you want to disable "the last time connected" on  the fire tv stick  or maybye implement an option to the jellyfin server to enable or disable  and apply this setting on all clients devices ...

![Screenshot_20200227-164855](https://user-images.githubusercontent.com/58141187/75461046-7f06e400-5982-11ea-8e26-60842314d510.jpg)
<img width="756" alt="Jellyfinweblogin" src="https://user-images.githubusercontent.com/58141187/75461179-abbafb80-5982-11ea-921c-80582e47ac14.png">

**Comment by thornbill** [comment]
We are planning on redesigning the login flow for the next major release. I think we should just remove that since it's not displayed on other clients.

**Comment by lelamamalgache** [comment]
OK nice !

thanks

**Comment by thornbill** [comment]
The last login time is no longer displayed on the redesigned login screen. :tada:
