### ISSUE TITLE
Server / User Selection design suggestion

### ISSUE THREAD

**Issue by Jenjen1324** [jellyfin/jellyfin-androidtv#367]
Hi, I was looking through the issues regarding the login and server selection screen and wanted to suggest some designs for both of these. I see there is a consensus that the current one is confusing (for me too).

In my use case, I have multiple servers with vastly different media on them. The optimal would of course be that there would be a unified view of all media but my understanding is that it's technically not feasible at the time to do that. So the alternative is the allow quicker switching between servers while using the app.

I don't think the standard [browse view](https://designguidelines.withgoogle.com/android-tv/tv-apps/browse-view.html) is very good for this component and it might be more intuitive to make it a bit like the Netflix user chooser but have two rows instead. The top row would be to select a server like a selection element and the second row updates according to the available users for that server. Clicking OK (center dpad) or down would put the cursor down to the user selection. On app start it's probably smart to always put the cursor to the last selected user.  
Additionally, the last item in each row is always an "add" action for server or user.  
I could draw up a quick mockup if it's unclear.

This could also remove the need for the auto login (mentioned in #223) since opening the last logged in is just one click away from start.

Further on, I'm not quite sure how many other Media apps like this structure the login, but the small *separate* modals for username/password are a bit janky in my opinion. Perhaps opening an activity/fragment with bot username and password where the credentials get verified on this page solves some other problems. Wrong credentials don't have to be reentered from scratch and integrating #255 (show password button) should also be easier.

---

On a side note, I'm not sure where the discussion on this topic internally is and if someone is already working on the login screen but I have some experience working with TV Apps and would gladly volunteer some work (albeit my time is pretty limited). I'd probably fix #364 in the process if it's not too hard.

**Comment by thornbill** [comment]
:wave: hi @Jenjen1324,

Thanks for reaching out!

I have already started working on redesigning the login screens. What we were planning was similar to what you suggest. We are going to move everything to a single screen with a vertical list of servers with rows of users. We had a hastily drawn mock of this at one point that I could dig up if you're curious. I hope to make some significant progress on this over the weekend though.

That said we are always welcome to new contributions. Feel free to join us on [Matrix](https://matrix.to/#/+jellyfin:matrix.org) for discussions. We have a specific [room there](https://matrix.to/#/#jellyfin-dev-android:matrix.org) for Android and Android TV development.

I am going to close out this issue, but feel free to continue the discussion here or join us on chat!
