### ISSUE TITLE
Display show/movie title logos instead of plain text on screen saver

### ISSUE THREAD

**Issue by anthonymag** [jellyfin/jellyfin-androidtv#3679]
### Describe the feature you'd like

Currently, the screen saver cycles through shows and movies, and shows the title as text in the bottom corner.

It would be a nice, "official" look if the plain title text for the displayed media could be replaced with the same title logo that displays on the media's page and on the pause screen.

**Comment by nielsvanvelzen** [comment]
Related roadmap item: https://github.com/orgs/jellyfin/projects/47?pane=issue&itemId=59266775
