### ISSUE TITLE
SSL Handshake Failed on Fire TV 0.16.11 release

### ISSUE THREAD

**Issue by coolhand72** [jellyfin/jellyfin-androidtv#3686]
### Describe the bug

I've been running jellyfin on numerous Fire TV sticks both locally and remotely for over six months with no issue.  Renewed my Jellyfin domain's godaddy ssl certificate.  The service connects using the built-in reverse proxy on a Synology NAS.  Nearly two dozen other services are working as usual using that same reverse proxy server.  I ran the domain on ssllabs.com and the certificate received an A+ rating.  The server is configured to accept both TLS 1.2 and 1.3 versions.  The jellyfin service runs perfectly fine on other tested devices, including computer web browsers and apple iphone & ipad as well as the firetv web browser itself.  Testing the FireTV using the local http protocol works fine, but this is not satisfactory given the I have remote users.  Rebooted the FireTV several times, even deleted the app and reinstalled to no avail.  Any suggestions you have would be appreciated.  Let me know if you need any additional information or have any suggestions on further troubleshooting.

### Application version

0.16.11

### Where did you install the app from?

None

### Device information

Fire TV Stick 4K Max and other versions as well

### Android version

Fire OS

### Jellyfin server version

10.9.6

**Comment by nielsvanvelzen** [comment]
You can use our [chat or forum](https://jellyfin.org/contact) to help with troubleshooting network issues.

**Comment by coolhand72** [comment]
[SOLUTION](https://forum.jellyfin.org/t-solved-ssl-handshake-failed-on-fire-tv)
