### ISSUE TITLE
Duplicate entries in "continue watching" and "next up" (FireTV Stick 4K)

### ISSUE THREAD

**Issue by ger-douggy** [jellyfin/jellyfin-androidtv#3690]
### Describe the bug

Hi,

1. Open Jellyfin on Fire TV Stick 4K.
2. If i stop payback of a video, it shows the same entry in "continue watching" (Fortsetzen) and "next up" (Als Nächstes).
3. If i complete an episode, there is the correct next episode on "next up".
4. e.g. on my Jellyfin App (Pixel 8, Android 14) everything works fine.

![jelly1](https://github.com/jellyfin/jellyfin-androidtv/assets/173366292/11a567ed-10b8-458d-a246-452c2548bb09)
![jelly2](https://github.com/jellyfin/jellyfin-androidtv/assets/173366292/693631f2-0ad9-490c-8a34-72902a53168a)

### Application version

0.16.11

### Where did you install the app from?

Amazon Appstore

### Device information

Fire TV Stick 4K (1st Gen)

### Android version

Fire OS 6.7.0.4 (NS6704/5281)

### Jellyfin server version

10.9.6

**Comment by nielsvanvelzen** [comment]
Already fixed for 0.17

**Comment by ger-douggy** [comment]
Great to hear. Thanks for your work.
