### ISSUE TITLE
Build Type 'debug' contains custom resource values, but the feature is disabled.

### ISSUE THREAD

**Issue by PhynixP** [jellyfin/jellyfin-androidtv#3700]
### Describe the bug

Hey when i compile this app, i became this error:

Build Type 'debug' contains custom resource values, but the feature is disabled.

I hope anyone can help me.

### Application version

newest

### Where did you install the app from?

Amazon Appstore

### Device information

FireTV

### Android version

Android 9

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Where exactly do you get this error? Can you be a bit more specific?
