### ISSUE TITLE
Make the 'screensaver' display title names rather than filenames

### ISSUE THREAD

**Issue by ExpatUK** [jellyfin/jellyfin-androidtv#3702]
### Describe the feature you'd like

For the vast majority of my library these display wonderfully and beautifully with the fanart backgrounds, however more often than not - especially with new additions to the library, this will display the filenames (inc. release groups and format) and I think this would be much cleaner with just the media title names.

**Comment by nielsvanvelzen** [comment]
It already does that. If filenames show up that means the title in your metadata is not properly set.
