### ISSUE TITLE
Dashboard - active devices - missing/add buttons

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-androidtv#371]
Hello devs  :)

Could you add more buttons like the jellyfin web ? (pause, stop, send message)

![jellyfin-web-chrome](https://user-images.githubusercontent.com/58141187/75725138-2156fc80-5ce0-11ea-8c49-b26465bd1f51.jpg)

Below other android devices

jellyfin android phone
![jellyfin-android-mobile](https://user-images.githubusercontent.com/58141187/75725203-43e91580-5ce0-11ea-861b-a7c3a1ad4afe.jpg)

jellyfin android fire tv 4K
![jellyfin-android-firetv](https://user-images.githubusercontent.com/58141187/75725343-90ccec00-5ce0-11ea-83e3-51334643845c.jpg)

**Comment by thornbill** [comment]
This will be fixed in the next release by https://github.com/jellyfin/jellyfin-apiclient-java/pull/39
