### ISSUE TITLE
[0.17.0 beta-1] Bug in Home page while playing music

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#3714]
### Describe the bug

Now playing  for music has two rows on home page that repeats. 
Music --> Favourites --> Play all --> Home (via new button) or by pressing back

### Application version

0.17.0

### Where did you install the app from?

Sideloaded APK

### Device information

NS

### Android version

11

### Jellyfin server version

10.9.7

**Comment by SodaWithoutSparkles** [comment]
Unable to reproduce. 

- Server: 10.9.7
- Client: Jellyfin TV 0.17.0-beta.1
- Device: Android TV
- Source: Sideload release APK

**Comment by SodaWithoutSparkles** [comment]
That's unrelated to this issue.

**Comment by nielsvanvelzen** [comment]
So what you're saying is that whenever music is playing there are 2 "now playing" rows on the home screen?

**Comment by nielsvanvelzen** [comment]
Did it happen just once or can you reliably reproduce the issue?

**Comment by nielsvanvelzen** [comment]
Although I haven't been able to reproduce the problem, it might be fixed with #3715. Can you try sideloading the build from that PR and see if it works?

**Comment by nielsvanvelzen** [comment]
If you scroll down you can click on "build-artifacts" to download a zip with the apk in it.
