### ISSUE TITLE
Media tags cut off

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#3721]
### Describe the bug

This only happens some on media and it started happening before 0.17.0.
![Screenshot from 2024-07-05 09-36-02](https://github.com/jellyfin/jellyfin-androidtv/assets/115914075/d769344b-e070-4735-88ea-edeeac6a756e)
I have also notice that  the stereo tag can get cut off and  display like [] instead of [stereo] this appears to happen when the epsoide has a rating and date with only 5 of the 6 tags showing.

### Logs

N/A

### Application version

0.17.0

### Where did you install the app from?

Sideloaded APK

### Device information

NS

### Android version

android 11

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Should be "fixed" with #3724 by shrinking another part of the row.
