### ISSUE TITLE
cannot restart play video from where I left in "choose each time video player" mode

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin-androidtv#3727]
### Describe the bug

Set the video player to "ask each time" (or whatever it is called in english)
Start to play a video
Stop and browse your medias
Go back to the video you were playing initialliy and click "Start at xx:xx" 

The media starts playing from the beginning

### Application version

0.16.11

### Where did you install the app from?

Google Play

### Device information

freebox pop fiber box (SoC 4 x Cortex-A53 Amlogic S905X2)

### Android version

Don't know

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Does this also happen when you explicitly set a video player?

**Comment by bmillemathias** [comment]
> Does this also happen when you explicitly set a video player?

nope, sorry I forgot to mention it works fine in this case.

**Comment by nielsvanvelzen** [comment]
Ok thanks for confirming. This should no longer be an issue with 0.17 then.
