### ISSUE TITLE
Backdrop surrounds played film and Next Up box in jellyfin-androidtv-v0.17.0-beta.2-debug

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin-androidtv#3728]
### Describe the bug

Take a film that has two versions and a backdrop
"film (2000) - 1080P.mp4"
"film (2000) - 2160P.mp4"
"backdrop.jpg"

When "film (2000) - 1080P.mp4" is selected (button Version), then played, an intro is not played but the film works great.
When "film (2000) - 2160P.mp4" is selected (button Version), then played, the intro plays, you get a Next Up box in the bottom right corner (Cancel, Watch Now with a progress bar), and for some films the backdrop stays while watching the film.

### Logs

Need to figure out how to do this

### FFmpeg logs

```shell
Need to figure out how to do this
```

### Application version

0.17.0-beta.2

### Device information

Android TV

### Android version

11

### Jellyfin server version

10.9.7

**Comment by ThomasPGH** [comment]
When I disable displaying backdrops the background around the film stays in Jellyfin's background colour which I guess should be black.

**Comment by nielsvanvelzen** [comment]
Fixed for the next beta, thanks for reporting!
