### ISSUE TITLE
App browser

### ISSUE THREAD

**Issue by Globe51** [jellyfin/jellyfin-androidtv#3736]
![Screenshot 2024-07-10 104527](https://github.com/jellyfin/jellyfin-androidtv/assets/12443541/642e988b-028c-4f80-bde7-7fdbf365dd7c)

As somebody who has a big distaste for the built in android TV launcher, I am always looking for ways to avoid it whenever possible.

To that end, I have created a "My apps" feature which allows users to launch other apps directly from within Jellyfin.  The change consists of:

1 new Kotlin file
1 new layout xml file
1 new line in HomeRowsFragment.kt

It's very basic right now; the entries aren't styled properly, and there's no way to sort or hide apps. There is a boolean variable that can be changed at build time to switch the feature on and off, but I haven't added anything in the settings to enable the user to turn the feature on or off.

If you want to integrate into the main project then let me know.

**Comment by nielsvanvelzen** [comment]
Seems like a cool concept but it doesn't fit the scope of a Jellyfin client. If you don't want to use the default launcher on Android TV there are a whole lot of third-party launchers [like my unfinished one](https://github.com/nielsvanvelzen/tv-launcher).

**Comment by Globe51** [comment]
Thanks for your comments.

Obviously I'm aware that there are alternative launchers already available, indeed I already have one installed. It just seems like such a waste of an application when all the functionality it needs could be added into a much smaller, neater footprint inside another app.

Anyway, that's the beauty of open source.
