### ISSUE TITLE
Is it possible to add lyrics display on the TV side

### ISSUE THREAD

**Issue by bosidiA** [jellyfin/jellyfin-androidtv#3742]
### Describe the feature you'd like

![QQ_1720771439515](https://github.com/user-attachments/assets/155f355c-9eb6-4af2-9e15-ae7fa23f3bca)

**Comment by bosidiA** [comment]
![QQ_1720771439515 拷贝](https://github.com/user-attachments/assets/ab14534a-1d2f-44f5-b688-85fc93b3e272)
Request a lyrics display on your TV

**Comment by nielsvanvelzen** [comment]
Lyric support is planned and already in progress.

**Comment by bosidiA** [comment]
Thank you for all you do.
jellyfin will get better and better.
