### ISSUE TITLE
Jellyfin registered as Chromecast app after exiting

### ISSUE THREAD

**Issue by Sidelity** [jellyfin/jellyfin-androidtv#3747]
### Describe the bug

In Home Assistant I can see what's being played on my Nvidia Shield through the Google Cast integration. All other apps I've tested (Plex, YouTube, SmartTube, SVT Play, mpv) registers as the current Chromecast app when starting playing, then unregisters when you stop playing.

Jellyfin however seems to stay registered as the current Chromecast app after the playback has stopped, and even as you exit the app. This is what the Chromecast reports as being active even after exiting the app:

![Screenshot of Home Assistant](https://github.com/user-attachments/assets/99cd1e7c-d55d-41fb-a821-fd0b6effef8f)

You need to manually kill Jellyfin from running in the background for it to unregister. If you don't, Chromecast will continue to report Jellyfin as the active app (even when you start playing videos in another app). In my case, this prevents Home Assistant from seeing what's being played and breaks my automations.

Steps to reproduce:
1. Start playing media in Jellyfin on a device with built-in Chromecast (such as Nvidia Shield)
2. Stop playing media, and exit the app
3. Read out what's being played on Chromecast. (I use the Google Cast integration in Home Assistant, but I'm sure you can use other tools as well)

### Application version

0.16.11

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield TV 2017

### Android version

Android 11

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
The Android TV app is not a cast receiver and does not implement/use the proprietary cast SDK so I don't see how this is an issue on the app side.

**Comment by Sidelity** [comment]
Gotcha. Even though Jellyfin doesn't use the cast SDK, is it possible that Chromcast picks up on any playing media? And in that case, is Jellyfin doing something in the background that the other media apps aren't? Seeing as manually killing the Jellyfin app solves the issue.

**Comment by nielsvanvelzen** [comment]
The app does implement media sessions for music (video will come later) but that has nothing to do with casting, and as far as I know that is only picked up by the Android TV integration in Home Assistant.
