### ISSUE TITLE
https://github.com/jumoog/intro-skipper   is the newly maintained skip intro / credits. can we add support to the androidtv app

### ISSUE THREAD

**Issue by gaming09** [jellyfin/jellyfin-androidtv#3768]
### Describe the feature you'd like

https://github.com/jumoog/intro-skipper   is the newly maintained skip intro / credits. can we add support to the androidtv app to display on the native player

**Comment by thornbill** [comment]
We don't support third party plugins in official apps.

**Comment by xawoger** [comment]
Official server has this functionality can we add it in the client?

**Comment by thornbill** [comment]
[Yes](https://github.com/jellyfin/jellyfin-androidtv/pull/4052)
