### ISSUE TITLE
Change what libraries to grab thumbnails from for the login screen

### ISSUE THREAD

**Issue by SmaMan** [jellyfin/jellyfin-androidtv#3769]
### Describe the feature you'd like

Hi! The new-ish login screen is a neat feature, however, it's pulling some thumbnails from libraries that I would, ahem, rather it didn't pull from. 

Perhaps a way to specify which library or libraries are *safe* to do so server side would work?

**Comment by nielsvanvelzen** [comment]
The server generates this image, not the app.
