### ISSUE TITLE
v0.17.0-beta.4 Two questions

### ISSUE THREAD

**Issue by tianiue** [jellyfin/jellyfin-androidtv#3771]
### Describe the bug

1.Audio settings direct, mixed mode prompts player error
2.Dolby Vision video playback has black screen and sound. After playing on the 16.11 version website and mobile phone, the TV continues to play and transcode normally

### Application version

v0.17.0-beta.4 

### Device information

Himedia

### Android version

Android 7.0

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Please create separate issues and provide the requested information like reproduction steps, media details, logs and other relevant information.
