### ISSUE TITLE
v0.17.0-beta4 controls glitch after play

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#3772]
### Describe the bug

Play episode of TV show. after episode stop the Play & Watched button duplicates
![Untitled](https://github.com/user-attachments/assets/60ab61f5-ad8c-49cf-9a24-4cc6baba9a4e)

### Logs

No log

### Application version

0.17.0-beta 4

### Where did you install the app from?

Sideloaded APK

### Device information

Skyworth Android TV

### Android version

Android 9

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Thanks for reporting, should be fixed in the next release!
