### ISSUE TITLE
Jellyfin on firetv 4k

### ISSUE THREAD

**Issue by Josamisi** [jellyfin/jellyfin-androidtv#3775]
### Describe the bug

Hi there, 

On my firetv 4k jellyfin client simply after some time dont save the server info and login, keep asking me server ip and credentials.

Server version: 10.9.7

Tested apks: 
0.17.0-beta.4 debug
Default version downloaded by firetv os 0.16.11

Anyone have somekind of workaroind this issue?

Thank you in advance.

### Application version

0.16.11

### Device information

Firetv 4k

### Android version

Fire os 7

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Please use our forum or troubleshooting chat mentioned on the [contact page](https://jellyfin.org/contact) for help with networking issues.
