### ISSUE TITLE
Theme songs not playing on FireTV 4K Max

### ISSUE THREAD

**Issue by FritLP** [jellyfin/jellyfin-androidtv#3777]
### Describe the bug

Im using theme songs on my Jellyfin Server, on the normal clients did it work but on the FireTV App nothing is playing.
[theme.zip](https://github.com/user-attachments/files/16323620/theme.zip)

### Media info of the file

```shell
I added a example file at the description.
```

### Application version

0.16.11

### Device information

FireTV Stick 4K Max 2nd Gen

### Android version

FireOS 8.1.1.1

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Duplicate of #1150
