### ISSUE TITLE
extra content does not appear

### ISSUE THREAD

**Issue by eppesuig** [jellyfin/jellyfin-androidtv#3778]
### Describe the bug

I renamed a TV show according to to https://jellyfin.org/docs/general/server/media/shows/ this way:
```Shows
└── Series Name (2010)
    ├── Season 01
    │   ├── Series Name S01E01.mkv
    │   ├── Series Name S01E02.mkv
    │   ├── featurettes
    │   │   └── Some Featurette.mkv
    │   └── interviews
    │       └── Interview with the Director.mp4
    ├── Season 02
    │   ├── Series Name S02E01.mkv
    │   ├── Series Name S02E02.mkv
    │   └── behind the scenes
    │       └── Behind the Scenes.mp4
    └── extras
        └── Fantastic Extra.mkv
```
and now, I see the whole content using the web client.

When using the jellyfin androidtv app on a TV, I do not see listed the extras at all in the series main page.
I.e., I see the series title, the seasons list, the actors list, then nothing more.

Does this client show the extras differently than the web client?

Thank you,
Giuseppe

### Application version

0.16.11

### Where did you install the app from?

Google Play

### Device information

TCL

### Android version

Android 12

### Jellyfin server version

10.9.7+deb12

**Comment by nielsvanvelzen** [comment]
The display of specials for series and seasons is added in 0.17. Update to the beta version or wait for the stable release.

**Comment by eppesuig** [comment]
Thank you very much for this clarification. I'll wait for the new stable release.
