### ISSUE TITLE
v0.17.0-beta.4 - Playback Fails (too many errors message) If Bluetooth Headphones are connected to Fire Stick 4K (1st gen)

### ISSUE THREAD

**Issue by MovieWiz** [jellyfin/jellyfin-androidtv#3787]
### Describe the bug

This is a strange one and I'm sorry that I don't have time for more complete info -- heading out of town.  Figured some info about a problem with the beta is better than no info.

1) Start playback of any video while bluetooth headphones are connected to the Fire Stick 4K (1st gen).
2) Playback fails

There is no problem if sound is going to the TV (i.e. no bluetooth).

Similarly, if I connect bluetooth headphones after playback has started, playback immediately fails.

Tried with all combinations of Direct/Stereo sound and Bitstream AC3 on/off.  Result was always the same.

I imagine this happens with other Fire Stick devices as well.

Problem did not happen with v0.16.11.

### Application version

v0.17.0-beta.4

### Device information

Fire Stick 4K (1st gen)

### Android version

Fire OS 6

### Jellyfin server version

10.9.8

**Comment by nielsvanvelzen** [comment]
This should be fixed via #3786 which will be in the next release.
