### ISSUE TITLE
Missing Guide Data

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-androidtv#3791]
### Describe the bug

My timezone is MDT (UTC-7)
Server is located in EDT (UTC-5), and guide data is in EDT.

AndroidTV:
![screen](https://github.com/user-attachments/assets/9c740568-fcfa-4d9a-80ff-865e9acb4f9d)

Web:
![image](https://github.com/user-attachments/assets/1a363283-792c-4de3-8091-78375d0ec85f)

This episode airs at 9:15am, but is listed as 3:15pm

AndroidTV:
![screen_mummy](https://github.com/user-attachments/assets/c5c4cd32-8754-474b-aaf5-4e8a42441905)

Web:
![image](https://github.com/user-attachments/assets/abbe742c-6327-4d53-a2d2-f461272ccf21)

### Application version

v0.17.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield 2019 (tube)

### Android version

11

### Jellyfin server version

10.9.8

**Comment by nielsvanvelzen** [comment]
Confirmed fixed via SDK changes. Will release a new SDK version later (before 0.17 stable at least).
