### ISSUE TITLE
Letter View Clobbers # with A

### ISSUE THREAD

**Issue by KinaKai** [jellyfin/jellyfin-androidtv#3796]
### Describe the bug

0.17 contains a regression. When viewing a Jellyfin library in the application using the “By Letter” view, titles that start with non-alphabetical characters (#) no longer appear, instead, the # row duplicates the A row.

### Application version

v0.17.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

Nvidia Shield TV (2019)

### Android version

Android 9

### Jellyfin server version

10.9.8

**Comment by nielsvanvelzen** [comment]
Thanks for the report - this was a small copy-paste mistake. Fixed for the next beta!
