### ISSUE TITLE
playback speed change on 0.17beta4 is not working

### ISSUE THREAD

**Issue by Zachwang007** [jellyfin/jellyfin-androidtv#3798]
### Describe the bug

playback speed change on 0.17beta4 is not working

i try lots of videos none of them can change the playback speed

### Application version

0.17beta4

### Device information

xiaomi TV s65 pro 

### Android version

android 11 

### Jellyfin server version

10.9.8

**Comment by nielsvanvelzen** [comment]
I'm unable to reproduce this issue. Do the exact same files allow for playback speed changes with 0.16.11?

**Comment by Zachwang007** [comment]
> I'm unable to reproduce this issue. Do the exact same files allow for playback speed changes with 0.16.11?

i try it on  0.16.11

**Comment by Zachwang007** [comment]
on 0.16.11 same ,not working. palyback speed didn't change

**Comment by sorinsky** [comment]
I had this issue in 0.17beta3, reverting to stable 0.16.11 solved it. Chromecast with Google TV HD.

**Comment by Kuphi** [comment]
@Zachwang007 how did you try to fix it? In 0.17.4, this bug still exists on Fire TV Stick 4k Max.
There's also another current bug report:
https://github.com/jellyfin/jellyfin-androidtv/issues/3881
