### ISSUE TITLE
AV1 ExoPlayer Playback Broken in Jellyfin

### ISSUE THREAD

**Issue by trumblejoe** [jellyfin/jellyfin-androidtv#3815]
### Describe the bug

AV1 playback in Jellyfin is broken; AV1 playback works with Plex, MX Player, & Just Player; the fact it works in Plex leads me to believe it's not a problem with ExoPlayer. In Jellyfin, AV1 starts to play but video freezes frame by frame while audio works as expected. Fixing AV1 playback is a key need for proper support & external players all have issues with subtitles, usability annoyances, or playback tracking failures.

I believe in app/src/main/java/org/jellyfin/androidtv/util/profile/MediaCodecCapabilitiesTest.kt that in the following functions,

	fun supportsAV1(): Boolean = Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q &&
		hasCodecForMime(MediaFormat.MIMETYPE_VIDEO_AV1)

	fun supportsAV1Main10(): Boolean = Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q &&
		hasDecoder(
			MediaFormat.MIMETYPE_VIDEO_AV1,
			CodecProfileLevel.AV1ProfileMain10,
			CodecProfileLevel.AV1Level5
		)

that MediaFormat.MIMETYPE_VIDEO_AV1 should be plural, MediaFormat.MIMETYPES_VIDEO_AV1.

### Application version

0.14.0

### Device information

Amazon Fire TV Stick MAX 4k

### Android version

Android 9, Fire TV 7

### Jellyfin server version

10.9

**Comment by nielsvanvelzen** [comment]
Please try with the latest version (0.16/0.17-beta.5) instead of a years old version.

**Comment by trumblejoe** [comment]
I'm on 16.11. Last update May 28th, 2024. Typo, it was late for me last
night.

**Comment by nielsvanvelzen** [comment]
The app detects AV1 support on devices and your device should not support it (needs at least Android 10). The app will thus try to transcode, if the screen stays black this is likely because you've disabled transcoding for the jellyfin user.

**Comment by trumblejoe** [comment]
It doesn't start black, it starts at the first frame frozen, audio plays
normally. There is something wrong with the apps av1 support detection.

I'm on FireOS 8.1.1.1
FIRE TV Stick 4kax 2nd Gen
