### ISSUE TITLE
Add more options for home sections

### ISSUE THREAD

**Issue by nigiriemoji** [jellyfin/jellyfin-androidtv#3819]
### Describe the feature you'd like

I only have a movie and tv library on Jellyfin. On the great android tv app, there are some sections like Next Up, Continue Watching, Recently Added Media, and My media. Recently added media for each movies and TV is nice but the discoverability aspect of the home page of jellyfin-androidtv is limited. I use v0.16.11

Please consider adding more home sections to the options such as:

1. Random display. Just have a row for each movies and TV and display random content from each. Have the randomized items change at a customizable time or I suppose per each app load.
2. Genres. Adds more variety to the android tv home page. Hopefully can be customizable and be able to hide certain Genres since a large movie library will have tens of Genres.

**Comment by nielsvanvelzen** [comment]
The home sections are the same as in other clients. Support for new home sections should start by adding them to the server. So the feature requests should go to features.jellyfin.org.

Once a new section is added to the server we'll add the support to the app.
