### ISSUE TITLE
[0.17.0] live TV guide blank

### ISSUE THREAD

**Issue by VampiricAlien** [jellyfin/jellyfin-androidtv#3823]
### Describe the bug

Click on live tv, guide doesn't load, Was working in beta 5.

### Logs

`3405  3405 D NavigationRepositoryImpl: Navigating to Fragment(fragment=class org.jellyfin.androidtv.ui.livetv.LiveTvGuideFragment (Kotlin reflection is not available), arguments=Bundle[{}]) (via navigate function)`

`procName:org.jellyfin.androidtv 2 callback:android.view.Choreographer$FrameDisplayEventReceiver,target:android.view.Choreographer$FrameHandler $ latencyTime:24,WallTime:314 android.os.MessageQueue.nativePollOnce:-2,android.os.MessageQueue.next:335,android.os.Looper.loop:200,android.app.ActivityThread.main:7848,java.lang.reflect.Method.invoke:-2,com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run:592,com.android.internal.os.ZygoteInit.main:1192, allocWait:-1,ionwait:-1,dstate:-1,sched:-1,iowait:-1`

### Application version

0.17.0

### Where did you install the app from?

Sideloaded APK

### Device information

NS

### Android version

ATV 11

### Jellyfin server version

10.9.8

**Comment by nielsvanvelzen** [comment]
0.17.0 and 0.17.0-beta.5 are the exact same code so this is most likely a server issue.
