### ISSUE TITLE
[0.17] Selecting Bitrate/Quality crashes the application

### ISSUE THREAD

**Issue by rcv11x** [jellyfin/jellyfin-androidtv#3841]
### Describe the bug

I just updated the App and it seems that everything works fine and looks great but... when you are watching a movie/series and you press the button to change the bitrate/quality the application crashes as you can see in the video, also attached the log

By the way I just noticed that the playback is slow and stops (in my case I was watching the last of us and after 1 minute of playback it stopped) yesterday it didn't happen with 0.16.9.
### Logs

[upload_org.jellyfin.androidtv_0.17.0.txt](https://github.com/user-attachments/files/16502503/upload_org.jellyfin.androidtv_0.17.0.txt)

Video:

https://github.com/user-attachments/assets/1ee455df-d30d-4e65-9eaf-8753899a2d5d

### Application version

0.17.0

### Where did you install the app from?

Google Play

### Device information

SONY KD-43X90L (BRAVIA 4K VH22)

### Android version

Android 10

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
Crash should be fixed for the next release. As a workaround you can do a one-time change of the "max streaming bitrate" option in preferences -> playback -> advanced.
