### ISSUE TITLE
[Feedback] Series status badges colors hard to read

### ISSUE THREAD

**Issue by JPVenson** [jellyfin/jellyfin-androidtv#3852]
### Describe the bug

Feedback for 0.14.0

After loading the latest version i noticed that the new Combination of foreground/background colors for the status badges on a series (red in picture) are hard to read from any distance on my TV. It gets unreadable from 3m on my TV if the background image also shows similar red background.

![IMG_20240807_130735](https://github.com/user-attachments/assets/261f297b-fce3-4966-beef-a5b42ec2b06a)

### Application version

0.14.0

### Where did you install the app from?

Google Play

### Device information

Samsung TV

### Android version

Android for TV

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
Thanks for reporting, I've made some changes (as discussed on Matrix) that will be inbcluded with the next release. For screenshots see the pull request linked above.
