### ISSUE TITLE
Live TV not working on 0.17.1

### ISSUE THREAD

**Issue by bigworm** [jellyfin/jellyfin-androidtv#3860]
### Describe the bug

Go to Guide or Channels
Select channel to play
Screen remains black (however, time counter for playing channel is active via Dashboard)

Occurs on Nvidia Shield Pro and Nvidia Shield.

Live TV works normally via web or android app.

### Logs

I don't think there are relevant logs, it shows playback as normal.

### Application version

0.17.1

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro

### Android version

Android 11

### Jellyfin server version

10.9.9

sounds similar to https://github.com/jellyfin/jellyfin-androidtv/issues/3813

**Comment by bigworm** [comment]
Can confirm changing the Advanced Playback settings and direct stream and instead using transcode when necessary.as mentioned in https://github.com/jellyfin/jellyfin-androidtv/issues/3853#issuecomment-2273882231 allows it to work.

Is this expected behavior?

**Comment by nielsvanvelzen** [comment]
Please provide media info when you report playback issues.

**Comment by bigworm** [comment]
Stream #0:0[0x100]: Video: h264 (Main) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], Closed Captions, 59.94 fps, 59.94 tbr, 90k tbn
  Stream #0:1[0x101]: Audio: aac (HE-AAC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 96 kb/s

**Comment by nielsvanvelzen** [comment]
Ok so the codecs are fine and should work on all devices. So the live TV stream most likely requires the server to request it. In this case you need to make sure the "Direct stream live TV" checkbox is unchecked in the advanced playback settings.

**Comment by bigworm** [comment]
The reason I submitted it as a bug is because unchecking "Direct stream live TV" was not required in the past.

**Comment by nielsvanvelzen** [comment]
Because it most likely transcoded for another reason, now that the app is more capable is thought it could direct play. Closing as this is not an issue.
