### ISSUE TITLE
Next up when one of the Intro plugins is installed

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin-androidtv#3864]
### Describe the bug

I'm actually not sure if this is intentional or a bug but it's new to 0.17.x. 0.16.x didn't do this.

- Install Local Intros or Intros
- Set up an intro
- Now, every time after the intro is played a "Next Up" dialog shows up for a few seconds

### Logs

Every film

### Application version

0.17 but also happened with the betas

### Where did you install the app from?

Google Play

### Device information

TCL TV

### Android version

No idea

### Jellyfin server version

10.9.7

**Comment by ThomasPGH** [comment]
I just remembered that I mentioned this in an earlier issue but it seems it got overlooked as the main issue there was the background frame.
https://github.com/jellyfin/jellyfin-androidtv/issues/3728
I also have to admit that I may not have tested this enough back then to recognise a pattern because an intro is not always played when a film has two or more versions.

**Comment by nielsvanvelzen** [comment]
Thanks for the report, should be fixed in the next release!

**Comment by ThomasPGH** [comment]
Thanks for fixing.
