### ISSUE TITLE
Playback errors at start of chapter in 0.17.1

### ISSUE THREAD

**Issue by entropicdrifter** [jellyfin/jellyfin-androidtv#3865]
### Describe the bug

Play a video with chapters at the boundaries of the intro/commercial break/ending theme. Playback crashes back to the Jellyfin episode details screen when it reaches the beginning of the intro theme. Restarting playback from the start and skipping to the chapter it crashed at, playback works fine until the end of the intro (start of the next chapter), at which point it crashes again back to the episode details. 

Confirmed the episode plays fine on Jellyfin Media Player (on my PC) and Kodi (on the same device where I saw the crash in the JF ATV app), so it's neither the file nor the server causing the issue. This also didn't happen in 0.17.0 or any of its beta versions, from what I can tell

### Logs

No crash logs on the server

### FFmpeg logs

```shell
Video was Direct Playing, no ffmpeg logs
```

### Media info of the file

```shell
Video
Title: Presented By EMBER - 1080p - HEVC - SDR
Codec: HEVC
Profile: Main 10
Level: 120
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 4009 kbps
Bit depth: 10 bit
Video range: SDR
Video range type: SDR
Pixel format: yuv420p10le
Ref frames: 1

Audio
Title: English - AAC - Stereo - Default
Language: eng
Codec: AAC
Profile: LC
Layout: stereo
Channels: 2 ch
Bitrate: 125 kbps
Sample rate: 48000 Hz
Default: Yes
Forced: No
External: No

I used that audio track and no subtitles, so that's all that's relevant
```

### Application version

0.17.1

### Device information

Nvidia Shield TV (2019)

### Android version

Shield Experience 9.1.1

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
Please share the app crash logs.

**Comment by entropicdrifter** [comment]
There are none. The server has no separate log for the AndroidTV crash. The app simply shows a brief error message about a player error and returns to the episode details screen. The web interface just shows the regular daily logs and ffmpeg logs from times videos were transcoded. In these cases, I ensured the videos were direct-playing (in one case, direct streaming), and after the video playback crashed there was no log in the webapp the way there usually is if the ATV app crashes.

**Comment by nielsvanvelzen** [comment]
> The app simply shows a brief error message about a player error and returns to the episode details screen.

That's **not** a crash. Just a playback error.

**Comment by entropicdrifter** [comment]
Alright, well I'm seeing a lot of playback errors that retry a few times before giving up in files that worked fine before the 0.17.1 update. It's still a bug, no?

**Comment by entropicdrifter** [comment]
Some additional info: I haven't been able to recreate this issue with any videos encoded in AVC, just HEVC, and so far just 1080p 10-bit SDR HEVC videos, and only when direct playing or direct streaming. If the video is transcoded, the playback error doesn't occur

**Comment by entropicdrifter** [comment]
I've confirmed this bug exists on my Sony Bravia with Google TV, as well, so it's not Shield-specific

**Comment by entropicdrifter** [comment]
Just noting that these playback errors still exist on the 0.17.3 version

**Comment by entropicdrifter** [comment]
Well, since 0.17.4 the videos now transcode when they hit these playback errors, so I'll go ahead and close this as my server transcodes just fine.
