### ISSUE TITLE
Media Tags Fail to Update When Switching Media for Multiple Versions 

### ISSUE THREAD

**Issue by MichaelRUSF** [jellyfin/jellyfin-androidtv#3869]
### Describe the bug

After rewriting BaseItemInfoRow using Compose, multiple version media tags no longer update when switching media. They only display information for the first item shown and do not refresh. This was working correctly with the previous InfoLayoutHelper.

### Application version

.17.1

### Where did you install the app from?

Sideloaded APK

### Device information

Fire tv stick 4k 2nd Gen 2023

### Android version

Android 11

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
Thanks, fioxed for next release
