### ISSUE TITLE
Refresh rate switching stays on after playback stops, causing jittery navigation on home screen

### ISSUE THREAD

**Issue by mardeyar** [jellyfin/jellyfin-androidtv#3870]
### Describe the bug

1. Enable refresh rate switching from settings
2. Play a media file from the library
3. Stop playback and go to the homescreen
4. Navigation is now super jittery, appears refresh rate doesn't go back to what it was

### Application version

17.1

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2019

### Android version

Android 9

### Jellyfin server version

10.9.8

**Comment by nielsvanvelzen** [comment]
Thanks for reporting. Fixed in the next release!
