### ISSUE TITLE
Jellyfin stopped working on my projector(which uses android for TV)

### ISSUE THREAD

**Issue by Belutak** [jellyfin/jellyfin-androidtv#3876]
### Describe the bug

I just come  back from vacation and everything worked with no problems(at least on my TV - i will not mention what disaster app for windows become since i bypass that by using browser).
When i try to connecto to my jellyfin server from my TV(actually projector with android) i get message:
`Unable to connect to server, tried the following addresses - my-jf-ip`
`Server uses version 10.8.8 which is not supported`

OK, so i went i updated my jf server, and restarted everyting, even entire PC eventually
when i do command:
`jellyfin --version `
i get: 
`Jellyfin.Server 10.9.9.0`

but my tv still shows same error.
App on TV has version:
`jellyfin-androidtv 0.17.1 release`

In jellyfin logs there is nothing related to this problem. In apache logs there is nothing related to this problem.

I deleted the app on tv to clean cache and everything but it did not help. Any ideas what to try? Can we please have one stable version and somehow chose if we want to experiment so i dont have to constantly fix jellyfin app for my family and myself.

Everything works from my other devices and from browser from those devices but for some reason it stopped working junst on android TV

### Logs

there is nothing in logs related to this

### Application version

0.17.1

### Where did you install the app from?

Google Play

### Device information

Epson EF12

### Android version

Android 

### Jellyfin server version

10.9.9.0

**Comment by nielsvanvelzen** [comment]
The recent 0.17 version requires Jellyfin 10.9 or newer. If you don't want to have the app update you should disable auto-updating in the Google Play store.

When you connect to a server the app checks whether the version is compatible. If it is not it will show an connection error. It will cache this result for give minutes before it tries again, to avoid spamming the server with connection attempts. So just wait a few minutes and try again.

For further assistance with troubleshooting you can use our chat/forums listed at https://jellyfin.org/contact.
