### ISSUE TITLE
AndroidTV Client incompatible with newest server release

### ISSUE THREAD

**Issue by coding-lemur** [jellyfin/jellyfin-androidtv#3877]
**Describe the bug**

I use Jellyfin 10.0.9.9 on serverside. Now I starting the Jellyfin client on Chromecast (Version jellyfin-androidtv 0.17.1 release) an it shows an error message, that the server use 10.0.8.12 and is not supported by the client. Please update to Jellyfin 10.0.9.8 or newer. It's not possible to use the app. I run the latest updates on my Jellyfin Docker. Definitely It is 10.0.9.9 running on the server. 

**To Reproduce**

1. Install Jellyfin androidtv 0.17.1 on Chromecast
2. Run 1.0.9.9 on serverside
3. Start the app on Chromecast: The message will shown in a red box on the top. 

**Expected behavior**

It should possibly to use the client with this server version. 

**Logs**

**Screenshots**

**System (please complete the following information):**

-   OS: official Docker Image 
-   Browser: - 
-   Jellyfin version: 10.0.9.9
-   Cast Receiver version: Stable
-   Cast client: Jellyfin androidtv 0.17.1

**Additional context**

**Comment by nielsvanvelzen** [comment]
The recent 0.17 version requires Jellyfin 10.9 or newer. If you don't want to have the app update you should disable auto-updating in the Google Play store.

When you connect to a server the app checks whether the version is compatible. If it is not it will show an connection error. It will cache this result for give minutes before it tries again, to avoid spamming the server with connection attempts. So just wait a few minutes and try again.

For further assistance with troubleshooting you can use our chat/forums listed at https://jellyfin.org/contact.
