### ISSUE TITLE
Additional Home Section Options

### ISSUE THREAD

**Issue by nigiriemoji** [jellyfin/jellyfin-androidtv#3887]
### Describe the feature you'd like

I feel like the home page needs more sections to be added to them. There should be more 

Current State:
- Recently added media
- My media
- My media (small)
- Continue watching
- Continue listening
- Continue reading
- Active recordings
- Next up
- Live TV
- None

Perhaps some of these Home Section options is viable:
Movies:
- Views > Suggested from smart screen menu has an existing section such as "Because you watched MovieName1"
- Home section for 1 Genre for all movies, random display (I suppose this could be repeated and allow for multiple genres to be displayed but still random?)
- Random home section to display movies in random order, all genres

TV Shows:
- Views > Genres from smart screen menu has existing sections displaying various genres. Perhaps the home section for home screen would be to display 1 random genre from this tv category. The smart screen section seems to display by alphabetical currently. An option for random would be nice. (I suppose this could be repeated and allow for multiple genres to be displayed but still random?)
- Random home section to display any tv series in random order

**Comment by thornbill** [comment]
Home screen sections are not app specific.

Related feature request: https://features.jellyfin.org/posts/1986/new-or-improved-home-secreen-sections
