### ISSUE TITLE
The initial "PLEASE SIGN-IN" Screen shows posters/thumbs of videos that the User DOES NOT have access to

### ISSUE THREAD

**Issue by advarksauce** [jellyfin/jellyfin-androidtv#3889]
### Describe the bug

1. Create X-Rated Library and General Movies Library.
2. USER1 has access only to General Movies Library.
3. Open Jellyfin AndroidTV
4.  Under "Who's Watching", Click USER1, or Click +Add Account
6. LOG-IN Background Screen shows Thumbnails/Posters/fanart from X-Rated Library when not even logged in and when that user doesn't even have access to that library.

### Application version

0.17.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro 2015

### Android version

Android 11

### Jellyfin server version

10.9.9

**Comment by thornbill** [comment]
This is a server feature that is disabled by default.

Admin Dashboard > General settings > Enable the slash screen
