### ISSUE TITLE
Subtitles offset option disappeared 

### ISSUE THREAD

**Issue by thor9898** [jellyfin/jellyfin-androidtv#3895]
### Describe the bug

On the player there is no subtitles offset option anymore

### Application version

0.17.3

### Where did you install the app from?

Google Play Store

### Device information

Mi Box S (2nd Gen)

### Android version

Android 11

### Jellyfin server version

10.9.9

**Comment by noahvogt** [comment]
See [this comment on the same issue](https://github.com/jellyfin/jellyfin-androidtv/issues/3858#issuecomment-2276289213). I would recommend to close this issue yourself @thor9898.
