### ISSUE TITLE
Unable to load builtin subtitles after 0.17 update

### ISSUE THREAD

**Issue by adarshv90** [jellyfin/jellyfin-androidtv#3899]
### Describe the bug

I have my server running on a Raspberyr Pi 4B. The media source is Google Drive mounted using Rclone. Most of my media are `h265` `mkv` files.

Built-in subtitles fail to load on the Android TV client. When I select any of the built-in subtitles, it says `Loading subtitles...` and after a while, it fails and displays a toast saying `Unable to load subtitles`. If I extract the subtitles out and include them as `srt` files in the folder, it loads correctly. Only an issue when loading built-in subtitles

Before the recent 0.17 update, I had the option to switch players to LibVLC. It used to work with that (though, no subtitle styling). But with the new update, I don't see an option to use LibVLC player.

Please fix this issue with the builtin player or provide an option to switch to LibVLC

### Application version

0.17.0

### Device information

Hisense HiSmartTV A4

### Android version

Android 9

### Jellyfin server version

10.9.2

**Comment by tundrablasen** [comment]
i have the exact same issue with 0.17.3

**Comment by podopie** [comment]
Is there a pull request or branch to follow?

I don't know if this is helpful, but what I've noticed is that the selector is inaccurate. On one film, if I select English PGSSUB, I get the error, but if I select French PGSSUB, it loads the English subtitles. I've tested on the web client and the web client does this accurately (english PGSSUB loads english, French PGSSUB loads French).

**Comment by tundrablasen** [comment]
0.17.4 did not fix this bug. @adarshv90 

Still takes half a minute nor sometimes a whole minute to load a subtitle. Often subtitles loading fails totally

**Comment by gbals001** [comment]
Think this is the fix - coming in 0.18.0 (when that is, i dont know) - https://github.com/jellyfin/jellyfin-androidtv/pull/3825

**Comment by tundrablasen** [comment]
> Think this is the fix - coming in 0.18.0 (when that is, i dont know) - #3825

thanks for pointing in the direction where we can track progress. I guess we going to wait for 0.18 then.

**Comment by Hello-World-Traveler** [comment]
I think this still could be an issue on 0.18 beta, I am having issues trying to get subs to load on movie. (4k HDR HEVC)
@nielsvanvelzen

**Comment by nielsvanvelzen** [comment]
Subtitle handling was completely rewritten in 0.18 and now supports embedded subtitles without extracting them server side. You'll need to install the beta version **that is not released on Google Play yet**. If you still encounter issues with subtitles open a new issue with sufficient details so I can reproduce the problem.
