### ISSUE TITLE
Add back the ability to select libvlc as a player / add a player with subtitles offset capabilities

### ISSUE THREAD

**Issue by itsZeebo** [jellyfin/jellyfin-androidtv#3901]
### Describe the feature you'd like

Ever since the latest few version there is no longer ability to select the player (or change to libvlc) to be able to sync subtitles manually via offset.

I looked around the new playback settings and couldn't find a way to do it.

It's a feature that used to exist but seems to have disappeared ever since the playback settings changes.

**Comment by itsZeebo** [comment]
Thanks for the quick feedback @nielsvanvelzen 

What if I took a crack at it? 
I saw the guy who originally implemented the libvlc integration has made a comment that subtitles sync for external subs should be quite simple to add to ExoPlayer

**Comment by nielsvanvelzen** [comment]
Adding LibVLC back to the old playback code will not happen. I would accept a pull request that adds subtitle offset.

**Comment by itsZeebo** [comment]
Fair enough @nielsvanvelzen, since I'm new to the repo - is there some sort of a maintainers guide to get more familiar with the code? 

If you were to implement such a change, which areas of the code would need changing? 
Can you help me understand which areas I'd need to focus on?

Thank you!

**Comment by nielsvanvelzen** [comment]
Most of the legacy playback code is in https://github.com/jellyfin/jellyfin-androidtv/tree/master/app/src/main/java/org/jellyfin/androidtv/ui/playback. You can look at the libvlc removal commit to retrieve the UI part of the subtitle offset implementation.
