### ISSUE TITLE
Add to favorites button doesn't do anything for Music albums

### ISSUE THREAD

**Issue by StefanBS** [jellyfin/jellyfin-androidtv#3905]
### Describe the bug

1. Open a Music album
2. Click on add to favorites button
3. Nothng happens

### Application version

0.17.3

### Where did you install the app from?

Google Play

### Device information

Sony TV

### Android version

Android 10

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
It's working fine for me. Please provide more detail.

**Comment by StefanBS** [comment]
I'm sorry, just checked and it's only failing for Music media.

This has been broken for me since 0.17 beta releases. Went back to 0.16 stable and it worked again, but now that 0.17 stable is released it's still broken

**Comment by nielsvanvelzen** [comment]
Ah found it, thanks for the additional details. Will be fixed in the next release!
