### ISSUE TITLE
Playback using external player not triggering playback events like PlaybackStopped

### ISSUE THREAD

**Issue by atraholt** [jellyfin/jellyfin-androidtv#3911]
### Describe the bug

Using an external app for playback, events used by plugins to detect playback events are not firing, even though progress tracking appears to be working, seeing as finished episodes or movies do get marked as watched. Problem lies in events relied on by plugins. External player in use is mpv-android, I have no tried others.

Events like user data changing are working and plugins using those to detect playback events are operating as expected, such as Shokofin.
An example of a plugin where these events are not being triggered is https://github.com/vosmiic/jellyfin-ani-sync/, assuming the line involved is https://github.com/vosmiic/jellyfin-ani-sync/blob/c25d680816ba13f0042df8ff1732ddd9642037c5/jellyfin-ani-sync/SessionServerEntry.cs#L51.
Said plugin's events are firing and observable in logs when using web player directly or through webplayer-connected clients like jellyfin-mpv-shim.

### Application version

0.17.3

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield TV Pro (2019)

### Android version

Android 11

### Jellyfin server version

10.9.9

**Comment by nielsvanvelzen** [comment]
There is no reliable way to do this since you're using an an external player. We only know when we start the external player and sometimes when they close. We have no idea how far you've watched, if the stream is paused etc.

Closing as wontfix (not possible).
