### ISSUE TITLE
Add back "choose player" option

### ISSUE THREAD

**Issue by sheharyarn** [jellyfin/jellyfin-androidtv#3937]
### Describe the feature you'd like

Jellyfin for AndroidTV had the "choose player" option that was removed in https://github.com/jellyfin/jellyfin-androidtv/pull/3663 without any reason provided. The default player used by the app has quite a few issues including subtitle sync, failure to load subs, weird playback issues with some videos, etc.

Can we have that option again?

**Comment by DanDon** [comment]
bump bump bump!!

Why this has been removed is crazy. I use the built in player so that the skip intro plugin works but the built in player does not play DTS properly and outputs in PCM.

This needs to be added back in, I've had to download the old apk and install it to get actual functionality back to the app.

**Comment by nielsvanvelzen** [comment]
No. This option was not respected in most places that initiate playback and with the removal of LibVLC it doesn't make much sense anymore.

**Comment by sheharyarn** [comment]
I guess the question then becomes why remove LibVLC? Was there a discussion or planning as to why it was removed?

If you can link to it that would be very helpful for us to understand the reasoning since (anecdotally) the playback experience with vlc on all Jellyfin Android/Google TVs and devices used by me/friends/family was much better.

**Comment by nielsvanvelzen** [comment]
Experimental & developer options can be removed at any time. Don't rely on them. All details about the removal of LibVLC as video engine can be found in the relevant pull request (which is also linked in the changelogs) #3639.
