### ISSUE TITLE
Subtitle ASS don't works

### ISSUE THREAD

**Issue by luke6464** [jellyfin/jellyfin-androidtv#3946]
### Describe the bug

1.238 / 5.000
From the new version of the APP 0.17.4 all videos with subtitles in ASS format are no longer played and the player crashes.
Given that I have already read several posts on the subject and it is clear that you have removed support for ASS subtitles and you have also removed the ability to change the Player in the APP. Without wanting to criticize your work but it seems absurd to me that you continue to update the APP sacrificing very important previous features ... the ASS subtitle format is a modern format and even superior to SRT and more than 50% of the Films are based on this format so it is absurd that a new version of the APP is released that sacrifices a fundamental and not obsolete feature! ... The first rule of software engineering is that things that work well are not touched until they become truly obsolete! ... improving the APP with new trivial features sacrificing the old ones that are still useful, important and working is a very wrong choice! ...
Forgive the outburst but after the last update of your APP I find the Jellyfin Server practically unusable for more than 50% of the contents! ... are you sure that users want these things? ...
Thanks

### Logs

No need!

### FFmpeg logs

```shell
No need!
```

### Media info of the file

```shell
No need!
```

### Application version

0.17.4

### Device information

Chromecast Google TV

### Android version

Android 11

### Jellyfin server version

10.9.7

**Comment by nielsvanvelzen** [comment]
Thanks for sharing your thoughts. Closing as this is not an issue. For further information about these changes please consider using the search feature and reading changelogs.

**Comment by luke6464** [comment]
Sorry but I was expecting at least a suggestion on how to solve the problem instead of closing the topic.
Thanks

**Comment by nielsvanvelzen** [comment]
For assistance with troubleshooting you can use our chat/forums listed at https://jellyfin.org/contact.

**Comment by luke6464** [comment]
Ok. So I ran a series of tests that confirm that the APP Jellyfin for Android TV 0.17.4 actually has a BUG because the player crashes before requesting the Jellyfin Server to send the transcoding. I hope that the following information can be of help to the programmers of the Jellyfin ATV Player.
Here are the reasons that prove the aforementioned BUG ...
I tried to use on my Android Smartphone "Jellyfin for Android" (not AndroidTV) with the same films that crash with the Jellyfin AndroidTV Player 0.17.4 ... the Player integrated in Jellyfin on the Smartphone (derived from ExoPlayer), although not compatible with the ASS and VobSub formats, correctly requests the Jellyfin Server to send the transcoding and everything works without overloading the Raspberry which perfectly manages the transcoding of the video with the ASS and VobSub subtitles !! ...
When I try to use the Jellyfin for Android TV 0.17.4 APP Player (in Google Chromecast) on the same movies it crashes at startup if Forced ASS subtitles are set or if I manually activate ASS or VobSub subtitles and the player does not request the server to send the transcoding!
All this clearly shows that Jellyfin for Android TV 0.17.4 has a BUG that crashes the Player without requesting the transcoding to the server!
Can you verify the above and fix the BUG? ...
Thanks
