### ISSUE TITLE
Incorrect handling of HEVC 10-bit on Fire TV (2nd gen)

### ISSUE THREAD

**Issue by ppp7032** [jellyfin/jellyfin-androidtv#3952]
### Describe the bug

The 2nd gen Fire TV stick supports decoding of 8-bit HEVC but not 10-bit. The client is not aware of this and attempts to direct stream 8-bit **and** 10-bit HEVC. This works in the former case but leads to "Player error encountered. Retrying..." and eventually "Giving up" messages. 

Potential Solutions:
- Add an exception for this device to force transcoding to 8-bit HEVC or 8-bit AVC.
- As a more general solution, the app could try forcing transcoding if direct play did not succeed.

### Application version

0.17.4

### Device information

Amazon Fire TV Stick (gen 2)

### Android version

Fire OS 5

### Jellyfin server version

10.9.10

**Comment by patrickdk77** [comment]
I believe this is the same problem I have been having with HEVC h.265 videos, they just would not play, and would give up after a few minutes on my rk3566 running android tv v11.

I looks like all the videos that wont play are hevc in 10bit mode.

**Comment by ppp7032** [comment]
Only now noticing there is already a commit that claims to fix this: fe05b82b952aed525529c2bd0a1b631a45650518. I'll compile the main branch and sideload it to check. If it does, may I suggest a new release be made ASAP as this is a pretty major bugfix.

**Comment by ppp7032** [comment]
Can confirm the aforementioned commit fixes this issue for me. Again, please do make a release including this fix soon.
