### ISSUE TITLE
Nvidia Shield app shows wrong airdates

### ISSUE THREAD

**Issue by williamthrilliam** [jellyfin/jellyfin-androidtv#3968]
### Describe the bug

Same bug as #3190 but on the Nvidia shield. The android app shows that the date is a date previous to the actual recording. The web app and the server report the correct date. 

### Application version

0.17.4

### Where did you install the app from?

Google Play

### Device information

Nvidia Shield Pro

### Android version

Shield Android TV SW Version 9.2.0(22.2.0.201)

### Jellyfin server version

10.9.10

**Comment by nielsvanvelzen** [comment]
Closing as duplicate of #4245
