### ISSUE TITLE
LiveTV doesnt transcode after 0.16.11

### ISSUE THREAD

**Issue by FritLP** [jellyfin/jellyfin-androidtv#3973]
### Describe the bug

My problem is that I have LiveTV integrated on my server and if I use a version after 0.16.11, it is not transcoded, so it is not really smooth. I am currently still using 0.16.11, where I have set the LibVLV player everywhere and activated transcoding, so everything works without any problems. I have tested all versions up to 0.17.5, but it doesn't improve anywhere.

### Application version

0.16.11

### Where did you install the app from?

Sideloaded APK

### Device information

Amazon FireTV Stick 4K Max Gen. 2

### Android version

FireOS  8.1.1.6 

### Jellyfin server version

10.9.8

**Comment by nielsvanvelzen** [comment]
First, I would recommend updating your server to **at least** 10.9.10 as that version includes some changes that may fix the problem.

If that still doesn't work, please verify that you've disabled the "Direct stream live TV" option in the advanced playback preferences of the app.

**Comment by mircolino** [comment]
I have the same issue. With the latest Jellyfin version 10.9.11 and app version 0.17.x I can no longer playback a LiveTV M3U tuner shuch as the following:

```
#EXTM3U

#
# CNN
#
#EXTINF:-1 tvg-chno="1" tvg-id="CNN.us" tvg-logo="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/512px-CNN.svg.png" group-title="News",CNN
https://turnerlive.warnermediacdn.com/hls/live/586495/cnngo/cnn_slate/VIDEO_0_3564000.m3u8

#
# BBC News
#
#EXTINF:-1 tvg-chno="2" tvg-id="BBCNews.uk" tvg-logo="https://i.imgur.com/rPzH88J.png" group-title="News",BBC News
https://vs-hls-push-ww-live.akamaized.net/x=4/i=urn:bbc:pips:service:bbc_news_channel_hd/mobile_wifi_main_sd_abr_v2.m3u8

#
# AlJazeera
#
#EXTINF:-1 tvg-chno="3" tvg-id="AlJazeeraEnglish.qa" tvg-logo="https://upload.wikimedia.org/wikipedia/en/thumb/f/f2/Aljazeera_eng.svg/512px-Aljazeera_eng.svg.png" group-title="News",AlJazeera
https://live-hls-web-aje.getaj.net/AJE/index.m3u8
```

With app version 0.16.x everything is working fine.

**Comment by FritLP** [comment]
The direct Play is deactivated 💁🏼‍♂️

**Comment by mircolino** [comment]
> please verify that you've disabled the "Direct stream live TV" option in the advanced playback preferences of the app

Thank you! In my case this fixed the issue.

**Comment by xydone** [comment]
Can replicate with Direct Play disabled. Client error is an "Attempt to invoke interface method 'int java.util.Collection.size()' on a null object reference". 
Client ver: 0.17.5
Server ver: 10.9.10

**Comment by FritLP** [comment]
@nielsvanvelzen Any Idea?
