### ISSUE TITLE
Subtitles lack accuracy

### ISSUE THREAD

**Issue by Codling** [jellyfin/jellyfin-androidtv#3977]
### Describe the bug

Hello,

The subtitles lack precision, there are no blanks between two subtitles, and often the subtitles don't respect the CPS.
Personally, I think this is detrimental to viewing.

Can you please improve on this point?

### Logs

None.

### FFmpeg logs

```shell
None.
```

### Media info of the file

```shell
None.
```

### Application version

0.17.5

### Device information

NVIDIA Shield TV Pro (2019)

### Android version

Android 11

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
Use different subtitles with better timing.

**Comment by Codling** [comment]
I resynchronize the subtitles myself and I can assure you that they are fully in sync:

![Sans titre](https://github.com/user-attachments/assets/21782f4a-c55b-4395-a04b-d5cf1a47f4d9)

The problem is Jellyfin. With an external player (mpv, for example), the problem doesn't occur.
