### ISSUE TITLE
Ability to delete media disabled in FireTV if Allow Media Deletion From->All Libraries is not selected.  Individual library selection has no effect.

### ISSUE THREAD

**Issue by kstunger** [jellyfin/jellyfin-androidtv#398]
Please see screen shots here:
https://imgur.com/a/OWHNdrF

Delete does not appear under 'Other Options' unless "All libraries" is selected.

**Comment by dkanada** [comment]
back to atv you go

**Comment by nielsvanvelzen** [comment]
Item delete functionality is removed in 0.15 so this issue is no longer relevant.
