### ISSUE TITLE
0.17.5 is still not on the Amazon App Store

### ISSUE THREAD

**Issue by ppp7032** [jellyfin/jellyfin-androidtv#3999]
### Describe the bug

Title. It's been a week and I'm still using a debug build installed on my Firestick via adb. Sideloading the release build from github is not practical as for some reason the app does not then appear in My Applications, and has to be launched by going into Settings->All Applications.

This release is very important for me as prior to it, playback of 10-bit AVC failed rather than being transcoded to a compatible codec.

### Application version

0.17.4

### Where did you install the app from?

None

### Device information

Fire TV Stick (2nd gen)

### Android version

Fire OS 5

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
All releases go through 3 phases:

1. Internal Google Play beta
2. Public Google Play beta (slow rollout)
3. Public release on Google Play & Amazon Appstore

We're currently on phase 3 with a slow rollout, about 90% of all users should have the update right now and we'll move to 100% shortly.

**Comment by ppp7032** [comment]
Ahh I see thank you for the swift clarifying response.
