### ISSUE TITLE
not transcoding hevc main10 videos on firetv basic stick

### ISSUE THREAD

**Issue by cipitaua** [jellyfin/jellyfin-androidtv#4006]
### Describe the bug

hevc main10 videos are not transcoded and therefore they cannot be played on the firetv. 

Related to bug https://github.com/jellyfin/jellyfin-androidtv/issues/3952

Also, internal player always fails with any video, had to use external player (mxplayer).

The server is on a Synology NAS (DSM 7.2.1),  native package (no docker) from SynoCommunity.

### Logs

[Log1.txt](https://github.com/user-attachments/files/17055510/Log1.txt)

### Application version

0.17.5

### Where did you install the app from?

Sideloaded APK

### Device information

Amazon FireTV Stick Basic Edition

### Android version

current Fire OS

### Jellyfin server version

10.9.7-15

**Comment by nielsvanvelzen** [comment]
Please use the playback issue template for playback issues. Also make sure to test on the latest Jellyfin server version. We only support the most recent release.
