### ISSUE TITLE
internal player not working on firetv basic stick

### ISSUE THREAD

**Issue by cipitaua** [jellyfin/jellyfin-androidtv#4016]
### Describe the bug

Internal player always fails with any video, works with external player (mxplayer).

It tries to start a few times and then it stops.

The server is on a Synology NAS (DSM 7.2.1), docker from SynoCommunity.

### Logs

could not find any log

### Media info of the file

any video gives the same error

### Application version

0.17.5

### Device information

Amazon FireTV Stick Basic Edition

### Android version

Fire OS latest

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
Please head to our forum or chat rooms for troubleshooting help: https://jellyfin.org/contact
