### ISSUE TITLE
Remote TV philips

### ISSUE THREAD

**Issue by Danielcot38** [jellyfin/jellyfin-androidtv#4026]
### Describe the bug

Hello, I use Jellyfin android TV on a Philips OLED with ambilight and since version 0.17.5, when I watch a movie and I press the ambilight button on the remote control to activate the ambilight, the movie goes back to the beginning automatically, I went back to version 0.17.4 and I no longer have the problem.
If you have a solution or an explanation...?

Daniel

### Application version

0.17.5

### Where did you install the app from?

Google Play

### Device information

Philips  55.OLED.707/12

### Android version

Android 11

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
Thanks for the report. There was a small problem with a change in 0.17.1 causing the app to reset when you go to a different app and back. This is what happens with the ambilight button on your device.

It should be fixed in the next release!

**Comment by Danielcot38** [comment]
hi, thanks for the explanation but the problem appeared with version 0.17.5, I didn't have this problem before even with version 0.17.1. But if the problem will be solved with the next version, so much the better... Daniel

**Comment by nielsvanvelzen** [comment]
Sorry that was a typo, I meant 0.17.5!

**Comment by Danielcot38** [comment]
ok, thanks anyway for answering my question. have a good evening
