### ISSUE TITLE
SD Video Plays in Bottom Left Quarter of TV

### ISSUE THREAD

**Issue by hkdd** [jellyfin/jellyfin-androidtv#405]
I am guessing this is some kind of scaling issue, but I have some SD content that, when it is played via an Amazon Fire Stick, only takes up the bottom 1/4 or so of the TV screen.  Works fine via the web player on desktop PC.  I have tried rebooting the Fire stick but the behavior persists.  Most content plays correctly, I don't have a lot of SD content to test with, HD content seems fine and takes up the full screen.

**Comment by Bidley** [comment]
I had this same issue, I forced Exoplayer and it played correctly afterwards.

**Comment by hkdd** [comment]
That fixed it for me as well, thanks.  For anyone else looking you can change the player in the Jellyfin settings on the Android TV app.

**Comment by alex9099** [comment]
Can confirm, Exoplayer plays the videos without a problem (haven't yet played a video till the end, but the scaling problem seems to be gone)

**Comment by thornbill** [comment]
This should be fixed by https://github.com/jellyfin/jellyfin-androidtv/pull/604
