### ISSUE TITLE
mkv format video playback without sound

### ISSUE THREAD

**Issue by remiliyaScarlet** [jellyfin/jellyfin-androidtv#4059]
### Describe the bug

mkv format video playback without sound，
another jellyfin-web and jellyfin-android playback with sound

### Application version

0.17.6

### Device information

xiaomi

### Android version

xiaomi os

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
MKV files work fine. Closing as lacking information (trivial questions like media info have been ignored).
