### ISSUE TITLE
not supported when connect jellyfin server 10.8.12

### ISSUE THREAD

**Issue by gh503** [jellyfin/jellyfin-androidtv#4060]
### Describe the bug

versions info:
AndroidTV 0.17.6 release apk
TV info: TCL 75V8E pro

jellyfin server 10.8.12 

Scene Description:
1.installed tv client app from git hub release success.
2.opened app success.
3.failed to connect my land jellyfin server
with error message:
not supported since my server version 10.8.12

### Application version

0.17.6

### Where did you install the app from?

None

### Device information

tcl 75v8e pro

### Android version

tcl 75v8e pro

### Jellyfin server version

10.8.12

**Comment by nielsvanvelzen** [comment]
This is correct behavior. Update your server.
