### ISSUE TITLE
Posters/Covers in media library have different sizes -> FireTV 4K since update to server version 10.9.11 or app update 0.17.6

### ISSUE THREAD

**Issue by RonnyB1978** [jellyfin/jellyfin-androidtv#4070]
### Describe the bug

Since the update auf Server Version 10.9.11 and Client App on FireTV 0.17.6 we have in the app of the FireTV the problem, that at scrolling through the library, the covers/posters have different sizes. The problem exist only on FireTV.

In the browser, Windows client and on mobile devices the covers/posters are displayed correctly.

Delete the cache of the app doesn't works.
![1728717482492](https://github.com/user-attachments/assets/03361b32-781b-4ddf-8e8e-1df3246bee12)
![1728717482539](https://github.com/user-attachments/assets/da05efd1-f056-4e56-8cd8-f28e43b09987)
![1728717482565](https://github.com/user-attachments/assets/41b00e43-31f6-4e1c-8c6f-8c4e6411758e)

### Application version

0.17.6 FireTV app

### Where did you install the app from?

Amazon Appstore

### Device information

FireTV Stick 4K

### Android version

current updates installed

### Jellyfin server version

10.9.11 on Proxmox

**Comment by nielsvanvelzen** [comment]
This issue is already fixed for the next release (#4062 / #4065). Thanks for reporting!
