### ISSUE TITLE
Play next episode not working on 0.17.7

### ISSUE THREAD

**Issue by SamEvansTurner** [jellyfin/jellyfin-androidtv#4089]
### Describe the bug

Since the 0.17.7 update, the play next episode feature doesn't seem to work at all for me on a Chromecast with Google TV. At the end of an episode, it just returns to the menu.

I have tried reinstalling the app, turning the setting off and on again, and changing the refresh rate switching settings and up next duration settings, to no avail.

I had a look at the logs but I couldn't find any useful information, and there is no crash log. Ffmpeg exits successfully, and the server log just states that the client has stopped playback.

This feature works perfectly on 0.17.6.

### Application version

0.17.7

### Where did you install the app from?

Google Play

### Device information

Google chromecast with Google TV

### Android version

Default, unknown

### Jellyfin server version

10.9.11

**Comment by visualblind** [comment]
> Thanks for the report, this issue somehow slipped through my testing. A new release with a fix is publishing now!

@nielsvanvelzen It's amazing how fast you were able to fix this bug for the Android TV version, while if you look at jellyfin-android open issues it seems they're still dealing with it (or do you support that app also?).
The only problem I had is that 0.17.8 didn't get pushed automatically (had to uninstall/reinstall on Fire TV stick).

**Comment by nielsvanvelzen** [comment]
I'm still the project lead for both the Android mobile and TV apps, but I don't work on the mobile app itself. Only around for releases.

Both Amazon and Google reviewed the 0.17.7 release within a few hours, for 0.17.8 they took a bit longer. Amazon published it only yesterday so that might be why it didn't update automatically for you.
