### ISSUE TITLE
Series auto start of next Episode not working any longer

### ISSUE THREAD

**Issue by MarcoJ-CID** [jellyfin/jellyfin-androidtv#4092]
### Describe the bug

Out of nowhere the automatic start while watching a Series on my Amazon 4K Stick isn't working any longer. I have to start each eposide manually. Kinda annoying. On Web Version everything is working fine. So seems to be an Issue with Android TV App version 0.17.7.

### Application version

0.17.7

### Device information

Fire TV Stick 4K (2024)

### Android version

FireOS 8

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
Duplicate #4089
