### ISSUE TITLE
Autoplay of next episode no longer working

### ISSUE THREAD

**Issue by MrMcDaddy** [jellyfin/jellyfin-androidtv#4096]
### Describe the bug

Since version 0.17.7, auto play on serieses does no longer work. There is a "next episode" button in the player, but when the episode finishes, the regular "next up" popup does not appear.
Instead, Jellyfin gets me back to the info screen of the episode I just watched.

I know it has been working flawlessly before, so this is probably a regression.

Here is a video:
https://github.com/user-attachments/assets/476a9459-888d-4e67-adb8-2467f2d56a1d

And here is the according setting:
![20241019_175938](https://github.com/user-attachments/assets/03a6357e-67a5-4f1d-a0cb-bcef7e89cb11)

### Application version

0.17.7

### Where did you install the app from?

Google Play

### Device information

NVIDIA Shield

### Android version

Android 11

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
Duplicate #4089
