### ISSUE TITLE
Affichage media page d'accueil

### ISSUE THREAD

**Issue by Danielcot38** [jellyfin/jellyfin-androidtv#4097]
### Describe the bug

I have a persistent bug on the Android TV version, when I want to configure the home page including the media in small mode, it doesn't work, it stays in normal media mode, it only works on the Android version for smartphones.
Actually, I would like to have the same media display 
(screenshot) on Android TV.

![Screenshot_20241020-115107~2](https://github.com/user-attachments/assets/082cbcc0-f7fa-4bf5-b3a6-36b6998be945)

### Application version

0.17.8

### Where did you install the app from?

Sideloaded APK

### Device information

TV Philips 55oled707

### Android version

Android 11

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
The TV app does not implement the small variant for the library row in 0.17.z.

**Comment by Danielcot38** [comment]
ah, too bad but since it was offered directly on the Android TV application, I thought it was a bug...
