### ISSUE TITLE
Play Next Episode automatically doesn't work

### ISSUE THREAD

**Issue by ger-douggy** [jellyfin/jellyfin-androidtv#4101]
### Describe the bug

I've tested on two FireTV sticks, but in both Jellyfin apps the automatic play next episode doesn't work, even if it's enabled in settings.
When an episode ends i'm on the episode roaster.

### Application version

0.17.7

### Where did you install the app from?

Amazon Appstore

### Device information

FireTV 4k Max / FireTV 4k

### Android version

FireOS 8.1.1.9 / FireOS 6.7.0.6

### Jellyfin server version

10.9.11

**Comment by Gokuguy123** [comment]
Same issue here. 3 4K Firesticks, all giving the same result. Regardless of what was chosen, Jellyfin only plays 1 episode before going back to choose another.

**Comment by nielsvanvelzen** [comment]
Duplicate #4089

**Comment by ger-douggy** [comment]
Aww .. i don't looked for closed issues.
Sorry.
