### ISSUE TITLE
Android TV Sort by Premier Date sorts in descending order

### ISSUE THREAD

**Issue by CubsWin1** [jellyfin/jellyfin-androidtv#4106]
### Describe the bug

Setting the sort options on a folder to "Premier Date" sorts the videos in descending order with the most recent date first.
This is unlike sorting by Name, which sorts in ascending order alphabetically.

Is it possible to change the default sort behavior for Premier Date to sort Ascending, or add an option to choose whether to sort Ascending or Descending?

### Application version

0.17.8

### Where did you install the app from?

Google Play

### Device information

Sony X800H TV

### Android version

Android 10

### Jellyfin server version

10.9.11

**Comment by nielsvanvelzen** [comment]
The premier date sort option does indeed order from newest to oldest. This is intended behavior and not a bug. There is currently no option to change this, a feature request for that was made in #154.

**Comment by wuhi** [comment]
But what is with the last seen option?
Here it sorts from oldest to newest.
A descending order would be great here.
To list the last seen shows first
