### ISSUE TITLE
is there a reason it's smushed onto 3 lines? 

### ISSUE THREAD

**Issue by iwatch-x** [jellyfin/jellyfin-androidtv#411]
Hi folks

is there a reason it's smushed onto 3 lines? this is on android tv on my shield :
![91606456_838912433260805_746066850453913600_n](https://user-images.githubusercontent.com/62252807/77958624-987ab300-72d5-11ea-95e3-24a115e9f936.jpg)

and this is on zoomplayer on my windows pc same time frame with Zoom Player :
![zoom](https://user-images.githubusercontent.com/62252807/77959041-45553000-72d6-11ea-8361-74c8d20e76d4.jpg) 

**the subs are external .srt**

**Comment by thornbill** [comment]
I think this will be fixed by #396 in the next release.
