### ISSUE TITLE
Feature Request:  Save user information

### ISSUE THREAD

**Issue by uchagani** [jellyfin/jellyfin-androidtv#413]
It would be great if we could save user information so that we can switch profiles easily.  Currently only one user can be logged in automatically.  Once a user enters his details, perhaps we can show a "remember me" option to save a user's information so switching profiles is doesn't require re-entering information.

**Comment by dkanada** [comment]
I can confirm the API client allows this, so it's not impossible.

**Comment by kylehendricks** [comment]
I just spent a few hours migrating from plex to jellyfin.  Was about to start the "beta test" with the wife and realized we couldn't change profiles without re-entering our passwords.  Definitely a deal killer for right now.

I may take a stab at this if it isn't too difficult.

**Comment by AndreasGB** [comment]
Be aware that @thornbill is currently rewriting the login flow, so it may be advisable to coordinate this with him.

**Comment by thornbill** [comment]
Yeah I am working on some pretty massive changes to how authentication works in the app so I would recommend holding off on this for now.

**Comment by kylehendricks** [comment]
Curious what everyone's thoughts are on this.  Seems like for an Android TV app, it should be fine to leave all accounts signed in by default?

@thornbill any chance this feature could get worked into your rewrite if everybody is aligned with how this should work?

**Comment by uchagani** [comment]
I think there definitely should be an option to "keep me logged in".  then anyone that doesn't want their passwords saved can choose not to click that checkbox.

**Comment by nielsvanvelzen** [comment]
Storing the password isn't necessary to keep a user logged in. We can just store the access token given by the server.

**Comment by Terror-Gene** [comment]
Any update on this?
Just got a Shield TV & realised I’m still stuck with kodi for the multiuser experience (individual or multiuser logins) Was looking forward to the Jellyfin experience :p

**Comment by nielsvanvelzen** [comment]
We're working on a complete rewrite of the login flow for the next update.

**Comment by nielsvanvelzen** [comment]
This is now possible in the (upcoming) 0.12 release.
