### ISSUE TITLE
List of now playing music uses Album artist instead of Artist

### ISSUE THREAD

**Issue by markalex2209** [jellyfin/jellyfin-androidtv#4139]
### Describe the bug

1. Play a song from album with [Various Artists](https://musicbrainz.org/artist/89ad4ac3-39f7-470e-963a-56509c546377) specified as Album artist, for example soundtrack for game or movie.
2. Go to Now playing section.

Songs there are shown with Album artist and Title. But seeing Various artists there is not particularly useful.
For albums with present Album artist this behaviour only skips featured participants.

I'd expect this list showing Artist/Artists instead, similarly to how it is done in the list of recordings inside album.

### Application version

0.17.8

### Where did you install the app from?

Google Play

### Device information

Xiaomi TV Box S

### Android version

Android TV OS 11

### Jellyfin server version

10.10.0

**Comment by nielsvanvelzen** [comment]
Thanks for the report. I've made some changes and artist images should will now be considered before album artists. The change will be in 0.18.

**Comment by markalex2209** [comment]
Hi @nielsvanvelzen ,
I meant name of the artist in text, not image. Sorry if I wasn't clear.

Here's an image of what I am talking about
![Image](https://github.com/user-attachments/assets/cbffeecd-a40e-4e58-9b43-e477ca4af8a9)

**Comment by nielsvanvelzen** [comment]
Thanks for clarifying, I've now also made changes to the displayed names.

**Comment by markalex2209** [comment]
Thank you so much!)
