### ISSUE TITLE
"Last Played" Sort Not Working for TV Series

### ISSUE THREAD

**Issue by johnpc** [jellyfin/jellyfin-androidtv#4151]
### Describe the bug

1. Go to TV Series "All items" view
2. In the top bar settings, switch the sort from A-Z by name to "Last Played"
3. I expect to see my most recently played TV shows at the top of the list
4. Instead, the sort order is not related to when the show was last played.

### Application version

2.6.2

### Where did you install the app from?

Google Play

### Device information

Google Home ChromeCast

### Android version

Not sure

### Jellyfin server version

10.10.0

**Comment by nielsvanvelzen** [comment]
> 2.6.2

Issues for the mobile app should be reported in the jellyfin/jellyfin-android repository. This is the repository for the Android **TV** app.

**Comment by johnpc** [comment]
My mistake, this _does_ affect the android tv app - I do not use the mobile app. My actual version is `v0.17.2`. I do not have permissions to reopen, so I will copy/paste this to a new issue.
