### ISSUE TITLE
Use the Media Segments API to support Skipping Intros

### ISSUE THREAD

**Issue by johnpc** [jellyfin/jellyfin-androidtv#4155]
See discussion https://github.com/jellyfin/jellyfin-androidtv/discussions/3793

Jellyfin 10.10 added a Media Segments API that allows parts of a video to be marked as special (Intro, Credits, etc.).

When an intro is playing, a "Skip Intro" button should be displayed similar to the current "Next Episode" button at the end of an episode.

Currently in 10.10 web, this button is hidden by default. However, in 10.10.1 this button will be https://github.com/jellyfin/jellyfin-web/pull/6266.

More information on the specific implementation in web is in https://github.com/jellyfin/jellyfin-web/pull/6196. Some specifics:

* Only show for segments with duration of 3 seconds or more
* Auto-hide after 8 seconds
* Skipping does nothing if there is only 1 second left in the segment (just like the normal skip action)

**Comment by nielsvanvelzen** [comment]
Media segments are already implemented, the linked pull requests in jellyfin-web use it as a reference.
