### ISSUE TITLE
"Last Played" Sort Not Working for TV Series

### ISSUE THREAD

**Issue by johnpc** [jellyfin/jellyfin-androidtv#4160]
### Describe the bug

This ticket is created to reopen https://github.com/jellyfin/jellyfin-androidtv/issues/4151#event-15096001719, which is still an issue.

1. Go to TV Series "All items" view
2. In the top bar settings, switch the sort from A-Z by name to "Last Played"
3. I expect to see my most recently played TV shows at the top of the list
4. Instead, the sort order is not related to when the show was last played.

### Application version

0.17.2

### Where did you install the app from?

Google Play

### Device information

Google Home ChromeCast

### Android version

Not sure

### Jellyfin server version

10.10.0

**Comment by Hello-World-Traveler** [comment]
v0.17.9 is the latest, you're running 0.17.2.

**Comment by johnpc** [comment]
Thanks! I updated to 0.17.8 (for some reason my chrome cast does not think there's a newer update than that). However the behavior is the same as my ticket. So unless this was fixed in the latest patch (it doesn't look like it based on the change log?), I believe it is still an issue.

**Comment by nielsvanvelzen** [comment]
Does this issue also happen when you use the "Date played" sorting in the web client?

**Comment by Hello-World-Traveler** [comment]
Can confirm this and web client does the same until you select Descending.

**Comment by johnpc** [comment]
I _think_ it works on the web client. Ascending is meaningless because many of the shows I have never watched, so I think it's a multi-way tie that isn't helpful. But in web, descending does show everything in the correct order, where the android tv app does not (by the way, the roku app also has this problem - I cut them a separate ticket. But their incorrect order matches the android tv incorrect order)

**Comment by nielsvanvelzen** [comment]
I've found the culprit, the sorting worked fine for everything except TV Shows because that needs to be done slightly differently. I've implemented that now and it will be available in the next 0.18 beta. Thanks for reporting!
