### ISSUE TITLE
AndroidTV app complains of "low storage" after live tv playback of several hours

### ISSUE THREAD

**Issue by samwathegreat** [jellyfin/jellyfin-androidtv#417]
I'm noticing that after a 2-3+ hours of watching live tv, my fire tv stick will complain that it is almost out of storage and suggests that I remove apps.

![image](https://user-images.githubusercontent.com/4813336/78376783-ce04f200-759c-11ea-950a-5505d1160a9b.png)

The thing is -- Jellyfin is the ONLY app installed on my Fire TV stick.  And if I select the remove apps button, the only one I can remove (that isn't built-in) is Jellyfin itself!

If I hit "not now", I can start watching live tv again without issue, and the fire tv doesn't appear to have full storage.

I'm wondering if there is some sort of buffer on the fire tv that is getting filled up and causing this issue.  It seems like the moment this pop-up happens, since it interrupts the live tv stream, I'm guessing that Jellyfin app clears whatever is eating up all of the storage?

Any advice?  Let me know if I can help by providing more info.

Thanks in advance.

**Comment by samwathegreat** [comment]
This is happening on the newest NON-4K fire tv stick.

**Comment by bbalz** [comment]
I get the same issue with Shield TV (2019 - Tube).  

With subtitle heavy movies it'll transcode versus direct play and after an hour or so it'll eat the storage up and be unplayable.  I have to stop and then just resume where it left off and continue that for each 45-60 minutes.

**Comment by nielsvanvelzen** [comment]
A new version (0.11.3) was released that should fix this issue. Please let us know if the issue persists.

**Comment by bbalz** [comment]
> A new version (0.11.3) was released that should fix this issue. Please let us know if the issue persists.

I watched a few films that required some transcoding due to subtitles and I no longer receive the low storage error.   Thanks for fixing this! 

Thank you and everyone else for your efforts on this project!
