### ISSUE TITLE
Add back setting to set a more precise font size

### ISSUE THREAD

**Issue by laurentlbm** [jellyfin/jellyfin-androidtv#4173]
### Describe the feature you'd like

The new beta (0.18.0-beta.1) changed how subtitles are rendered. Unfortunately, it also removed the option to specify a font size (10-38), replacing it with relative sizes (very small, small, normal, large, very large). I use a projector, so my display is pretty large, and I find `Normal` to be too big, and `Small` too small... 

In fact, I can see that [`Small` is set to be half the size of `Normal`](https://github.com/nielsvanvelzen/jellyfin-androidtv/blob/e1867b23e71ad627e2cc5747a163df40fd30b4be/app/src/main/java/org/jellyfin/androidtv/ui/preference/screen/PlaybackPreferencesScreen.kt#L133). That's a pretty big jump in between values. Could a more granular scale be offered?

**Comment by nielsvanvelzen** [comment]
Some subtitle formats allow customization of the text size, therefor we longer have an "absolute" size and instead use fractional sizing. I've opted to use a list of options instead of a slider because it's more intuitive (the slider control is not great for this type of value). The possible options for this list are copied from Android itself: https://cs.android.com/android/platform/superproject/main/+/main:packages/apps/Settings/res/values/arrays.xml;l=712-728;drc=5484c1e2136559a7c83b79049dc7dc6a5a68123b

**Comment by laurentlbm** [comment]
I understand. The font size of captions has been a frequent annoyance for me in other apps that also use Android's default scale. I guess I'm very superficial and care too much about the appearance of subtitles! I'll probably get used to it; it was just a shock going from 0.17 to 0.18. 

FYI, out of curiosity I looked at how some other streaming apps handle sizes:
- Netflix offers 3 sizes: Small, Medium and Large. Medium looks to me a little bit smaller than Jellyfin's normal. Small is 0.5x medium and large is 2x medium.
- Disney+ uses Android's settings (Accessibility > Captions), so sizing is similar to Jellyfin.
- Nebula has no options. Size seems to be the same as Jellyfin's normal.
- SmartTube allows the user to select a font size scale from a list going from 0.1x to 2x in 0.1x increments. Great for customizability, but maybe not for usability!

**Comment by nielsvanvelzen** [comment]
I've made some changes and used the behavior of SmartTube as basis. You can now set the text size with a slider going from 25% up to 250% with increments of 25%. This allows for all previous values but adds a bit more variety, 75% would be between what previously was small (50%) and normal (100%).

![Image](https://github.com/user-attachments/assets/bbb5420d-8849-4aa1-bbde-a934418b343d)

Thanks for the feedback!

**Comment by laurentlbm** [comment]
That's amazing, thank you very much! I'm certain that 75% will be perfect for me, in SmartTube I have it set to 0.7x.
