### ISSUE TITLE
Playback continues even after exiting the app

### ISSUE THREAD

**Issue by itsrn** [jellyfin/jellyfin-androidtv#4174]
### Describe the bug

1. Go to any media on the server and start playing it.
3. Stop the playback, go back to the home of jellyfin app.
4. Exit the jellyfin app and open another app.
5. The playback continues (somehow).
6. Return after some time to the jellyfin app.
7. Continue to watch the media.
8. The playback isn't saved from the part where I actually exited the player before.

For example, I stopped the Avengers: Endgame movie playback at about an hour and a half, but when looking at the dashboard after some time it seems like it continues: ![Image](https://github.com/user-attachments/assets/f2e96f68-6a38-498a-aeed-e9d751706360)

I'm using the normal video player that exists in the app (which is ExoPlayer, if I'm not wrong), not any external ones.

Before using the new beta version, this issue didn't occur at all (I used the latest stable version before it).

I've also tried to limit the background apps on the devices I tried this on, but this didn't seem to help. I've also tried to stop it from the stop button in the dashboard or pause it, but pressing on those buttons don't do anything and the playback just continues.

### Application version

0.18.0-beta.1

### Device information

Xiaomi TV Box S 2nd Gen. Tested also on HOT Streamer

### Android version

Android 9

### Jellyfin server version

10.10.1

**Comment by nielsvanvelzen** [comment]
Does this also happen in the second beta?

**Comment by itsrn** [comment]
After installing the new beta and restarting the server it seems like the problem has been resolved.
