### ISSUE TITLE
TrickPlay Scroll Lag (beta)

### ISSUE THREAD

**Issue by BotBlake** [jellyfin/jellyfin-androidtv#4179]
### Describe the bug

When using the experimental Trickplay implementation from 0.18.0-beta.2, you will notice that there is a lot of load time for the individual frames.
So much in fact, that it can take multiple secconds for the Client to catch up again. 
![Image](https://github.com/user-attachments/assets/94ce4b9d-a854-4312-9803-c6217980f8f2)

You easily notice this when Scrubbing through the media a bit faster, or just holding down on the remote for a while.

I am aware this is an experimental implementation, and that the images do need to get loaded (which takes some time)

However in this state, to me, this feature isnt helpful: As I mostly use trickplay to Quickly find a Scene that I am searching for. Having to wait for the Client to catch up doesnt help here. 

### Application version

0.18.0-beta.2

### Where did you install the app from?

None

### Device information

Chromecast with Google TV HD

### Android version

12

### Jellyfin server version

10.10.1

**Comment by nielsvanvelzen** [comment]
The video scrubbing previews are an experimental feature and support is provided. Closing as wontfix.
