### ISSUE TITLE
PGS Subtitles Not Being Used

### ISSUE THREAD

**Issue by The-Randalorian** [jellyfin/jellyfin-androidtv#4182]
### Describe the bug

1. Play media that has PGS subtitles.
2. Select a subtitle track from the dropdown

Subtitles should now appear, but they do not. Other subtitle formats (like DVDSUB) do not seem affected.

### Media info of the file

Episode S01E33
Container: mkv
Path: /media/Anime/Inuyasha (2000)/Season 01/Episode S01E33.mkv
Size: 1682 MB

Video
Title: 1080p AV1 SDR
Codec: AV1
AVC: No
Profile: Main
Level: 8
Resolution: 1440x1080
Aspect ratio: 4:3
Anamorphic: No
Interlaced: No
Framerate: 23.976025
Bitrate: 9605 kbps
Bit depth: 8 bit
Video range: SDR
Video range type: SDR
Color space: bt709
Color transfer: bt709
Color primaries: bt709
Pixel format: yuv420p
Ref frames: 1

Audio
Title: Stereo - English - DTS-HD MA - Default
Language: eng
Codec: DTS
AVC: No
Profile: DTS-HD MA
Layout: stereo
Channels: 2 ch
Sample rate: 48000 Hz
Bit depth: 16 bit
Default: Yes
Forced: No
External: No

Audio
Title: Stereo - English - DTS
Language: eng
Codec: DTS
AVC: No
Profile: DTS
Layout: stereo
Channels: 2 ch
Bitrate: 1536 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Audio
Title: Stereo - Japanese - DTS-HD MA
Language: jpn
Codec: DTS
AVC: No
Profile: DTS-HD MA
Layout: stereo
Channels: 2 ch
Sample rate: 48000 Hz
Bit depth: 16 bit
Default: No
Forced: No
External: No

Audio
Title: Stereo - Japanese - DTS
Language: jpn
Codec: DTS
AVC: No
Profile: DTS
Layout: stereo
Channels: 2 ch
Bitrate: 1536 kbps
Sample rate: 48000 Hz
Default: No
Forced: No
External: No

Subtitle
Title: English - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

Subtitle
Title: English - PGSSUB
Language: eng
Codec: PGSSUB
AVC: No
Resolution: 1920x1080
Default: No
Forced: No
External: No

### Application version

0.18.0-beta.2

### Device information

Amazon Fire TV Stick 4k MAX (AFTKA)

### Android version

FireOS 8.1.1.9

### Jellyfin server version

10.10.1

**Comment by sheharyarn** [comment]
Can confirm that this has been happening since the most recent update. PGSUBs fail to load.

**Comment by Hello-World-Traveler** [comment]
> Can confirm that this has been happening since the most recent update. PGSUBs fail to load.

@sheharyarn Are you also using FireOS?

**Comment by nielsvanvelzen** [comment]
Is the video transcoding when this issue happens or does it also happen when direct playing?

**Comment by nielsvanvelzen** [comment]
Feels like this and #4183 are the same issue so I'll close this one in favor of the other one.

**Comment by The-Randalorian** [comment]
A final comment to answer your question/comment.

> Is the video transcoding when this issue happens or does it also happen when direct playing?

Transcoding. I do not have the the bandwidth to try direct playback at the moment (server is in my house, while I'm at college).

> Feels like this and [#4183](https://github.com/jellyfin/jellyfin-androidtv/issues/4183) are the same issue so I'll close this one in favor of the other one.

They definitely feel related, though the specific symptoms are different. I should note my files are all embedded PGS, no external subs like that issue details. I'll watch that issue and either ask this issue be reopened or make a new issue if the fix for that issue doesn't fix PGS.

**Comment by nielsvanvelzen** [comment]
Should be fixed now with #4201
