### ISSUE TITLE
Configure the amount of time the skip button is visible

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-androidtv#4187]
### Describe the feature you'd like

Right now the skip button is only shown briefly at the start of the intro and outro. 

Allowing users to configure this time to be longer or shorter would be nice. For me it's short, the skip button tends to disappear before I get to hit it.

**Comment by nielsvanvelzen** [comment]
There are currently no plans to add a preference for this. Once the new player design is implemented the skip button will always become visible in the controls-overlay, but for now it will only be visible for 8 seconds.

**Comment by viggy96** [comment]
Always visible in the overlay? Do you mean only during the intro/outro, or during the entire video?

**Comment by woolmonkey** [comment]
So it well become visable when contorls are available good. 8 seconds is sometimes not long enough.

**Comment by johnpc** [comment]
@nielsvanvelzen why limit it to 8 seconds? I feel like I always just miss it, and it's so unobtrusive in the ui. 

I created https://github.com/jellyfin/jellyfin-androidtv/pull/4519 to add the setting. It'd be a huge QoL improvement for many!
