### ISSUE TITLE
"The setup of this server has not been completed. Open Jellyfin in a web browser to finish setup before signing in."

### ISSUE THREAD

**Issue by alimbada** [jellyfin/jellyfin-androidtv#4198]
### Describe the bug

I see this notice on the server/user choice screen when opening the Jellyfin Android TV app. I've tried clearing the app's cache and data and setup the server/users again from scratch but I still see it. 
![Image](https://github.com/user-attachments/assets/7b059948-f6d2-4ca3-83df-70c743a9e504)

I don't see this issue on any other clients (web, iOS, Windows). It doesn't impact the app's functionality; I can still use it but it's annoying to see the banner each time the app is opened.

### Application version

0.17.9

### Where did you install the app from?

Google Play

### Device information

Chromecast with Google TV

### Android version

12

### Jellyfin server version

10.10.1

**Comment by alimbada** [comment]
I cloned the repo and debugged the app. This seems to be caused by `IsStartupWizardCompleted` being set to `false` in the Jellyfin server's `config/system.xml` for some reason even though there's no evidence of this being communicated to the user in the admin dashboard in any of the other clients.

However, the behaviour here is inconsistent with the other clients which seem to ignore this property and don't display a big red 🚨danger sign🚨. The Android TV client should match this behaviour.

**Comment by nielsvanvelzen** [comment]
Closing as user error/wontfix. Your server indicates that the setup is not completed and the client notifies you about that because normally you wouldn't be able to connect without a complete setup.
