### ISSUE TITLE
Pillarboxing grey on firestick

### ISSUE THREAD

**Issue by eli3090** [jellyfin/jellyfin-androidtv#4199]
### Describe the bug

The bars (letterboxing) during playback is grey rather than black. The same videos don't have this issue on desktop or phone app.
![Image](https://github.com/user-attachments/assets/ab4b6e49-96e2-4be9-9aa6-2f72d6fd3b3a)

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.17.9

### Device information

amazon firestick v1

### Android version

Fire OS 5.2.9.5

### Jellyfin server version

10.10.0

**Comment by nielsvanvelzen** [comment]
Please use our [forums](https://forum.jellyfin.org/) or chat to troubleshoot issues. Can't do much without any specifics.
