### ISSUE TITLE
Cannot seek forward or backward using external player

### ISSUE THREAD

**Issue by AlecHex** [jellyfin/jellyfin-androidtv#420]
When playing anything on my android box using an external player, VLC and MX Player, both of these do not allow me to seek the movie forward, with the end time being 0:00 like the movie is live. 
Has anyone fixed this?

**Comment by partytoni** [comment]
I have the same problem. I cannot play 4k x265 content on my fire tv 4k max using nor the internal players nor mx player nor vlc.
