### ISSUE TITLE
Lyrics can be hard to read

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-androidtv#4207]
### Describe the feature you'd like

May want to wait for other feedback but I find the lyrics hard to read when layered over album artwork and artist background

![Image](https://github.com/user-attachments/assets/0a460b4d-48b1-4ce0-ae93-e3e81c679926)

**Comment by nielsvanvelzen** [comment]
I didn't have any backdrops while testing, the backdrop is not supposed to be behind the album cover. It should have the app background color behind it, which would make this text much more readable.
