### ISSUE TITLE
Song playback queue numbering not updated

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-androidtv#4213]
### Describe the bug

1. Queue album of songs
2. See 1 of x
3. Progress through album
4. Still see 1 of x

Song 1 of 10
![Image](https://github.com/user-attachments/assets/6bb7e275-d3f0-4dd3-824a-a1dbb125cc07)

Song 2 of 10
![Image](https://github.com/user-attachments/assets/532eae1f-2142-441e-89cb-e4f6c18d0794)

Song 7 of 10

![Image](https://github.com/user-attachments/assets/c7a56704-b4e5-4976-92ff-04fa19f77a33)

Count after adding another album to queue (8 of 40)
![Image](https://github.com/user-attachments/assets/4a348045-5898-4c65-9197-9f8747cc3e06)

### Application version

0.18.0-beta.3

### Where did you install the app from?

Sideloaded APK

### Device information

Dune HD Premiere 4k Pro

### Android version

Android 11

### Jellyfin server version

10.10.1

**Comment by nielsvanvelzen** [comment]
Yup
