### ISSUE TITLE
Option to 'Always' burn-in subtitles on AndroidTV Client

### ISSUE THREAD

**Issue by andries230** [jellyfin/jellyfin-androidtv#4229]
### Describe the feature you'd like

On the Web or iOS client, I can go to **_Settings > Subtitles > Burn-in subtitles_**, and set it to **_'Always'_**. This is a perfect solution for the subtitles that getting out of Sync after seeking (on all client-types). 

However, the AndroidTV app doesn't have this option in the settings menu so it just renders my SRT's like usual.

Would it be possible to implement this feature in the AndroidTV web client?

in case this isn't possible:
A server-wide setting that forces subtitle burn-in would also be fine.

**Comment by nielsvanvelzen** [comment]
There are not plans to add such an option. The client will request bake-in or transform subtitles when they can't otherwise be shown and as such forcing it won't change anything.

**Comment by andries230** [comment]
Well, it will 'change' a lot actually.. Burned-in subtitles are a lot more stable than the regular ones (in terms of syncing after seeking), and gives the server-owner more control over the styling and position of the subtitles.

**Comment by andries230** [comment]
I currently run the latest version of Jellyfin server and all of the clients. On ALL of those clients (Web-UI on Chrome, iOS and AndroidTV), I experience syncing problems after seeking through video (fast forward or backwards). This happens on all video's, and I am only using SRT's. 

However, it is not very consistent. Sometimes, it happens after the first fast forward, and sometimes it only happens after a lot of seeking.

Users with similar experience:
- (recent) https://forum.jellyfin.org/t-subtitles-out-of-sync
- (some time ago) https://www.reddit.com/r/jellyfin/comments/10p6v1j/subtitles_constantly_fall_out_of_sync/

**Comment by nielsvanvelzen** [comment]
Are you using the beta version of the app? The 0.18 version is _not_ released as stable yet.

**Comment by andries230** [comment]
No, but like I said, I have this problem on every client (Web in Chrome, iOS and AndroidTV).
