### ISSUE TITLE
Subtitle selection not remembered between episodes

### ISSUE THREAD

**Issue by Deckerz** [jellyfin/jellyfin-androidtv#4230]
### Describe the bug

If you have a tv series that has 2 subtitle tracks, and both are the same language it forgets which one you were using on episode swap.

e.g:

Episode A: Subtitle Track 1 and Subtitle Track 2
Episode B: Subtitle Track 1 and Subtitle Track 2

If you watch Episode A on Subtitle Track 2 and then the tv auto plays Episode B it forgets that you were on Subtitle Track 2 and reverts to Subtitle Track 1.

I would expect switching episode to keep subtitle track the same providing the names match perfectly, which in my case they do.

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.17.9

### Device information

Song Bravia Android TV

### Android version

Android 10

### Jellyfin server version

10.10.0

**Comment by nielsvanvelzen** [comment]
Not a bug, the server determines which subtitle the client should play by default and it does not support changing a track for multiple items within a parent (e.g. all episodes in a tv series).

**Comment by Deckerz** [comment]
If it's a not a bug why is this supported on the normal android version of the app? It works fine on web client, android phone app and desktop app from my testing. It only doesn't work on android TV.
