### ISSUE TITLE
Self signed TLS didn't work on android tv app

### ISSUE THREAD

**Issue by LordArrin** [jellyfin/jellyfin-androidtv#4231]
### Describe the bug

On all my phones (Android 11-14) i install my own root.crt in user keychain, and all works as charm. But on my TVs (Android 9-12) I do the same, but Android TV app doesn't connect with error. Even when I install Android TV version of app on my phone, I've got the same error. 

Can provide any logs or further data if required.

### Logs

![Image](https://github.com/user-attachments/assets/1b35601f-b3c6-424e-9ad5-b8940eda5390)

### Application version

0.17.9

### Where did you install the app from?

Sideloaded APK

### Device information

Transpeed H618T

### Android version

Android 12 for TV

### Jellyfin server version

10.10.2

**Comment by LordArrin** [comment]
Same error on latest beta (0.18 beta 4)

**Comment by nielsvanvelzen** [comment]
Please use our forums/troubleshooting chat for networking issues. The app does support user certificates installed in the OS but you may have forgotten to add intermediate certificates or some other configuration mistake.

https://jellyfin.org/contact

**Comment by gclawes** [comment]
Android TV doesn't permit user certificates at the OS level
