### ISSUE TITLE
Questions about using the just player

### ISSUE THREAD

**Issue by y610372901** [jellyfin/jellyfin-androidtv#4239]
### Describe the bug

When using just player to automatically play the next episode, it prompts that there is no player.![Image](https://github.com/user-attachments/assets/dba668ed-943a-47cb-8a6b-8a7d381c4629)

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.17.9

### Device information

Sony x9500h

### Android version

Android TV 10

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
While I can't read the screenshot, I'll assume this is the "no video player app" installed warning. This shows when you don't have any app installed that can play videos. Not an issue with the app.

**Comment by y610372901** [comment]
I installed the player(just player).It will only prompt when you jump to the next episode after the playback.
