### ISSUE TITLE
Trickplay thumbnails not showing when using "Play next up"

### ISSUE THREAD

**Issue by marinierb** [jellyfin/jellyfin-androidtv#4240]
### Describe the bug

I have Trickplay enabled on my "Shows" library and it is set to store the thumbnails next to media. I can see the jpegs on the disk. All is well there.

On playback, Trickplay works, except when I launch using "Play next up".

So:

1. WORKS when using "Play all" from the series screen
2. WORKS when using "Play" from the episode screen
3. DOES NOT WORK when using "Play next up" from the series screen

Behaves consistently with multiple shows.

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

v0.18.0-beta.4-debug

### Device information

EBOX TV device (Sagemcom DIW387)

### Android version

Android 9

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
Do you have the "Play next episode automatically" option enabled in the playback preferences of the app? If not, can you enable it and see if that fixes the issue?

**Comment by marinierb** [comment]
Yes. If I turn on  "Play next episode automatically", trickplay works.

**Comment by nielsvanvelzen** [comment]
Thanks for confirming, it should be fixed in the release version for 0.18. Let me know if the issue still occurs once updated!

**Comment by ScottESanDiego** [comment]
Aha that was the problem I was having too @marinierb .  I didn't even catch that it was the "Play up next" causing the failure, since that's 99% of how we trigger watching something.  Thanks for figuring it out!
