### ISSUE TITLE
Frame rate matching still happens when "Never" is selected

### ISSUE THREAD

**Issue by branches78** [jellyfin/jellyfin-androidtv#4242]
### Describe the bug

When the frame rate option is turned ON with the "escalate to device" option and the "Never" option is selected in the match content frame rate screen of Android 12 and Android 14 for TV, the app still match the frame rate and that shouldn't happen.

No app should match the frame rate when the "Never" option is selected, period.

The "Never" option clearly states at the bottom right of the screen the following message: "Even if the app requests it, your device will NEVER try to match its output to the original frame rate of the content you're watching"

Please, fix that.

Thank you.

### Application version

v0.18.0-beta.4

### Where did you install the app from?

Sideloaded APK

### Device information

Homatics Box R 4K Plus and the Google TV Streamer

### Android version

Android 12 and Android 14

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
Refresh rate switching can be configured in the app preferences. The system-wide setting is not currently used.
