### ISSUE TITLE
Online trailers working through web client, but not Android TV or Fire TV

### ISSUE THREAD

**Issue by razor1973** [jellyfin/jellyfin-androidtv#425]
When I browse my library through my computer's web browser, I see trailers on movies (online trailers, since I don't have a local trailer file for those), but when I use the Jellyfin app on my Fire TV or NVIDIA SHIELD TV, there's no trailer for these same movies. I assume this isn't by design, so I am reporting it as a potential bug.

**Comment by nielsvanvelzen** [comment]
This was added in #345 and will be available in the next version! 🎉

**Comment by razor1973** [comment]
Thank you.
