### ISSUE TITLE
Switching video audio tracks in the TV version causes the player to crash

### ISSUE THREAD

**Issue by nianqingnet** [jellyfin/jellyfin-androidtv#4264]
### Describe the feature you'd like

When the TV version clicks buttons such as switching audio tracks, the player immediately crashes. Open the toggle monorail normally in PC browser. The server version on the NAS is 10.10.3.
BTW, can the music file type and music video type be set to play continuously?

**Comment by Zachwang007** [comment]
i have same problem with you
