### ISSUE TITLE
External player playback doesn't work

### ISSUE THREAD

**Issue by cswrd** [jellyfin/jellyfin-androidtv#4274]
### Describe the bug

**Steps**:
1. precondition: external player option enabled
2. start any movie
3. **problem**: the monitor becomes and keeps being black w/o sound, i.e. nothing happens
4. pressing back button does work (no app crash)

**Workaround**:
1. disable the external player option
2. start any movie just for some seconds
3. exit the movie (back button)
4. enable the external player option
5. start any movie (doesn't need to be the one from step 2)
6. playback with the external player now does work (once)
7. once because pressing the back button will now cause the app to crash.

This happens with 0.18.0 and 0.18.1. 0.17.9 works just fine.

Unfortunately, I don't see any of the logs in my server which are asked for, even though logging is enabled everywhere.

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.18.1

### Device information

Zidoo Z9X 8K

### Android version

Android 11

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
There haven't been any changes related to how the external video player is started so without more detail (most importantly, app logs) I can't do much. My best guess would be it's an issue with the video player you're trying to use just not working. Have you tried playing different files or using a different external app?

**Comment by nielsvanvelzen** [comment]
Fellow team member @TimGels was able to reproduce the issue and was able to test a fix. Issue is solved with the next 0.18.2 release.

**Comment by cswrd** [comment]
Fix confirmed with v0.18.2. Thank you
