### ISSUE TITLE
Skip Popup timer

### ISSUE THREAD

**Issue by ShakeSp33r** [jellyfin/jellyfin-androidtv#4278]
### Describe the feature you'd like

Option where we can change the duration that the popup is visible on screen, including the entire time for the intro/outro. 

Sometimes you just miss the current popup.

**Comment by nielsvanvelzen** [comment]
There are no plans to make this configurable

**Comment by Hello-World-Traveler** [comment]
@nielsvanvelzen Can the default "option" when set to ask, say on screen unit finished? If outro is set to ask, the button stays on screen until the program/movie ends? if not can it be 60 seconds longer?

**Comment by nielsvanvelzen** [comment]
No, the popup only shows shortly to not be an annoyance while watching if you don't want to skip.

**Comment by brianjmurrell** [comment]
Except that it's even more of an annoyance if you happen to miss the very few seconds that it's displayed and have to sit through (sometimes quite a few) minutes of intro.

Even if not configurable, can it be extended?  It's really quite brief as it is now.

**Comment by dymara** [comment]
@nielsvanvelzen Is there a chance you could reconsider adding this improvement? Android TV client already has option to configure "Ask To Skip" behavior per each category (as described here -> https://github.com/intro-skipper/intro-skipper/wiki/Jellyfin-Skip-Options).

I was thinking about adding another setting like "Skip Button Visibility" with just 2 dropdown options to choose:
- "Auto-hide" - selected by default, no change as per current behavior
- "Always visible" - when chosen - the skip button should be shown during entire segment length and disappear once segment finishes

This seems like a small change to implement and would be extremely very useful to many people :) Current length of the button display is too short, I often fail to press it on time when I am looking for my remote once the intro starts playing.
