### ISSUE TITLE
Add dependency injection

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-androidtv#429]
We all know what a mess the current codebase is. One way to make it more maintainable is by using Dependency Injection. This is common practice for most Android applications.
My suggestion is to start adding it in 0.13.x for all new code or recently touched code (details screen / authentication screens).

The library that we will use should support the following:
 - Kotlin first
 - Java supported (for our legacy code)
 - Android support

This issue is meant to decide on which library to use.

**Comment by nielsvanvelzen** [comment]
Personally I have worked with both [Kodein DI] and [Koin]. The second is more popular and supports "modules" which I really like. Therefore I like to suggest using Koin.

[Koin]: https://insert-koin.io/
[Kodein DI]: https://kodein.org/di/

**Comment by cromefire** [comment]
I'd go with Koin, it's really simple, so just can't do anything wrong

**Comment by tukilo** [comment]
Is there any progress on this?

**Comment by nielsvanvelzen** [comment]
It's planned for 0.13

**Comment by tukilo** [comment]
> It's planned for 0.13

Yes, I get that but I meant if there is any progress pushed in some branch to check it out

**Comment by nielsvanvelzen** [comment]
Nope, we're working on 0.12 right now so nothing happend yet

**Comment by nielsvanvelzen** [comment]
Initial implementation was added in #560
