### ISSUE TITLE
Lyrics are not synchronized during song playback on Android TV

### ISSUE THREAD

**Issue by joaofcribeiro** [jellyfin/jellyfin-androidtv#4292]
### Describe the bug

**Version**: Jellyfin for Android TV 0.18.2  (also reproducible in 0.18.0 and 0.18.1)

**Platform:**

    Device: Chromecast with Google TV (4K)
   OS: Android TV 12

    Security Patch Level: September 1, 2024
    Kernel Version: 4.9.269
    Android TV OS Build: STTL.240812.006.N1.12570082

**Steps to Reproduce:**

    Open Jellyfin for Android TV (v0.18.2).
    Play a song that includes synced lyrics.
    Observe the lyrics display.

**Expected Behavior:**
      The lyrics should scroll or synchronize in time with the song playback.

**Actual Behavior:**
      The lyrics are loaded but freeze and remain static throughout the song.

**Additional Information:**

    The issue occurs consistently on Android TV across versions 0.18.0, 0.18.1, and 0.18.2.
    Verified on Jellyfin Web, where the lyrics are correctly synchronized, suggesting the issue is specific to Android TV.
    Audio playback functions normally—only the lyrics display is affected.

**Logs/Debug Info:**
     Screenshots and prints showing the issue are attached for reference .
     Apologies, I am unsure how to extract logs for this bug. If instructions are provided, I will gladly update the report with the necessary details.

**PS: Thanks for your great work!!!**

### Logs

![Image](https://github.com/user-attachments/assets/ecc6b30e-442e-4649-b0f4-ba61d0de5152)
![Image](https://github.com/user-attachments/assets/aa00664e-9eac-4d33-b46c-4ad0b4ec29ad)
![Image](https://github.com/user-attachments/assets/4eccde25-6383-4cee-8d25-e9416897c336)
![Image](https://github.com/user-attachments/assets/a2ca8a23-7cbf-4469-a6a3-0c88bbaa0d23)
![Image](https://github.com/user-attachments/assets/75393c8b-004e-4ab7-8f06-6bb2a3472d22)

### Application version

0.18.2

### Where did you install the app from?

Sideloaded APK

### Device information

Chromecast with Google TV (4K)

### Android version

Android TV 12

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
If I understand it correctly, you're saying that **all** lyrics will always be "stuck" at the top (no movement at all) while they do have proper timestamps?

When you pause/play the music, does that correct the lyric positions?

**Comment by joaofcribeiro** [comment]
> If I understand it correctly, you're saying that **all** lyrics will always be "stuck" at the top (no movement at all) while they do have proper timestamps?
> 
Yes, that's it. 
I think that it's  a platform specific issue because I've installed the same  version on my tablet and the lyrics sync correctly. 


> When you pause/play the music, does that correct the lyric positions?

(I cannot test it today, only monday) , but I think that does not solve the problem. 
Although, when moving to the screensaver, it shows the lyrics on the correct position, but then it gets stuck there.

**Comment by joaofcribeiro** [comment]
Hi @nielsvanvelzen 
> When you pause/play the music, does that correct the lyric positions?

I've checked again and you were right. When I pause the lyrics get to the correct position and highlight the correct sentence, but then it gets stuck there.

**Comment by nielsvanvelzen** [comment]
Ok thanks for checking. That would mean that animations are not working for some reason. I haven't found any reason why they wouldn't though, I did not find any documentation about animations getting disabled so I'll have to investigate some more.

**Comment by joaofcribeiro** [comment]
Hi @nielsvanvelzen 

I've found the problem.

The animations where disable o the device under developer options. 
Enabling it didn't solve immediately the problem but after disabling the developer options and a restart everything is working. 

Thanks for you help. 

![Image](https://github.com/user-attachments/assets/8a9d2747-25d2-482e-a299-b5774e6855dc)

**Comment by nielsvanvelzen** [comment]
Good to hear you figured it out. I believe it's only possible to disable animations using the developer settings so I don't think we'll need to figure out a way to keep this functionality working with animations disabled.
