### ISSUE TITLE
Toggle Auto Update

### ISSUE THREAD

**Issue by leachuk** [jellyfin/jellyfin-androidtv#4295]
### Describe the feature you'd like

The app recently auto updated to the latest version 0.18.2, which broke compatability with the Jellyfin server version I was running.

This had the unintended consequence of making my wife very unhappy as I was down the pub at the time, and unable to provide the usual IT support, while she was at home with a very angry 7 year old who was unable to enjoy the planned movie night.

May I humbly request that the app update be set behind a toggle option. I'm assuming it currently auto updates, as this is what appears to have happened. I couldn't see an existing option to control this in the settings.  I would much prefer to miss out on some of the latest features and bug fixes for a temporary amount of time than incur the wrath of a grumpy 7 year old and wife. Also, having to provide emergency tech support while hung over the next morning was less than ideal.

Thank you for the continued awesome work on the Android App

**Comment by nielsvanvelzen** [comment]
The app does not have any update capabilities of itself. The way the app is updated depends on your installation method. Most common is installing using the app store on your device (Google Play or Amazon Appstore), these stores will automatically update apps by default. You can change this from within the store app (although for Google Play this can only be set for all apps, on the Amazon store I'm not sure). An alternative would be to manually sideload the app, which requires you to manually do this again for each app update. This is however not the easiest task to do on televisions.

The recent 0.18 update requires a newer Jellyfin server version compared to the previous version. To prevent the exact situation you ended up with (app updates but server is behind so you can no longer use it) the app has shown a persistent warning on the home screen about updating the server starting with version 10.7.9 released on November 2th. This warning functionality is **always** used when an upcoming app version will require a newer server version.

Closing as wontfix (updates are not managed by the app).

**Comment by leachuk** [comment]
Thank you. This provides me with all the information I needed to know where to control the auto update behaviour.
