### ISSUE TITLE
Trying to transcode .ass drives jellyfin-android TV 0.18.2 crazy

### ISSUE THREAD

**Issue by rekom** [jellyfin/jellyfin-androidtv#4304]
### Describe the bug

It took me hours to figure out the bug. After trying to play a video with an embedded .ass subtitle file, Jellyfin-AndroidTV didn’t crash but wouldn’t play the file either. At first, I thought it was an issue with the H.265 10-bit file, so I tried another one—an H.264 file that had always worked perfectly. Same problem: the file wouldn’t start.

I suspected my server was the issue. I stopped and restarted it, but everything was working perfectly on my other devices. I then uninstalled version 0.18.2 of Jellyfin-AndroidTV and reinstalled it. Initially, I could play my files again. However, as soon as I tried the file with the .ass subtitle again, the problem reappeared: it wouldn’t play, and suddenly none of my other files would either (H.264, H.265, transcoded or not). Occasionally, some files would play randomly, but the behavior was inconsistent.

I tried using an external player (VLC), and it worked without any issues. This led me to conclude that .ass subtitles seem to cause significant issues with Jellyfin-AndroidTV. Interestingly, the same file works flawlessly when played through the web player or on my iOS device using Swiftfin.

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.18.2

### Device information

Xiaomi  MiTV-MSSP3

### Android version

Android 11

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
The app requests the server to bake in the subtitles (transcode) as it does not support ASS natively. This may introduce additional load on the server.
You haven't specified any of the requested information (like ffmpeg logs) so figuring out what goes wrong will be hard, I'd expect this to not be a bug with the app but with your setup. As such I'd recommend using our troubleshooting channels (chat/forum) to fix the issue.

**Comment by rekom** [comment]
It seems it's a ffmpeg regression : https://github.com/jellyfin/jellyfin-ffmpeg/issues/506#issuecomment-2500033779
https://github.com/jellyfin/jellyfin-web/issues/6299
And i didn't add the log as there'es no log. ffmpeg transcode but nothing happens. Anyway, it seems it will be fixed https://github.com/jellyfin/jellyfin-ffmpeg/pull/509
