### ISSUE TITLE
1 out of 3 Fire TV's cannot connect to server

### ISSUE THREAD

**Issue by BriMan83** [jellyfin/jellyfin-androidtv#4309]
### Describe the bug

Jellyfind server version 10.10.3 running on a Raspberry Pi 4
3 Fire TV's are running JellyFin app version jellyfin-androidtv 0.18.2 release

On two of them, it discovers the server fine, let's me log in, and everything works perfectly, but the last one seems to be unable to find the server.  It doesn't show up under Discovered Server, and when I try typing in the IP address (both with and without the port), it gives me the "unable to connect to server, tried the following address", and then lists http and https connections it tried to the IP address.  I've tried uninstalling the app, clearing the cache, rebooting the server, nothing seems to allow this one TV to connect when the other two connect just fine.  Any suggestions?

### Application version

0.18.2

### Where did you install the app from?

Amazon Appstore

### Device information

Hisense U6 4K UHD - Fire TV (2022)

### Android version

Fire OS 7.6.8.5

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
Please use our forum/chat for troubleshooting network issues.
