### ISSUE TITLE
Version 0.18.x using external players (Just Player), external subtitles doesn't work

### ISSUE THREAD

**Issue by vttc08** [jellyfin/jellyfin-androidtv#4310]
### Describe the bug

After Google Play auto updating Jellyfin for Android TV to v0.18.2, when I play any movies from my library which has external subtitles files alongside the media, these subtitles do not show up in Just Player, an external player which worked flawlessly with Jellyfin Android TV before.

Here are the steps I followed
1. Open Jellyfin for Android TV app, which has the option "Use External Players"
2. Find anything to play, in this example, I used The Wild Robot movie, mediainfo from API attached below. It contains external subtitles and is detected normally in the WebUI and Android phone app.
3. Click play to choose Just Player
4. In Just Players subtitle selection, only the subtitles inside the video file appears, external `.srt` subtitles do not appear
5. Uninstall Jellyfin for Android TV
6. Download version 0.17.9 from Github and manually install it
7. Configure server and preferences 
8. Play the same video in Just Player, observe the external subtitles appear in subtitle selection.

My folder/file layouts are as such
```
Root folder (1234)/
--- movie.mkv
--- movie.en.srt
--- movie.zh.中英文字幕.srt
```

Screenshots
Version 0.18.2/1/0 external Chinese subtitles do not appear in subtitle selection of Just Player
![Image](https://github.com/user-attachments/assets/c5014327-188d-41b9-8a6f-25e9ab2bf9ac)
Version 0.17.9 external Chinese subtitles work flawlessly in Just Player
![Image](https://github.com/user-attachments/assets/01522de9-b6f0-45e4-9199-98af31edbf2d)

I expect in the latest version of Jellyfin, when using Just Player as external player, it should behave as the same way as it was in 0.17.9, which is the ability to choose external subtitles. I've tried downgrading Just Player first, that did not fix my problem. This indicates the problem is not Just Player but with Jellyfin. I've used Just Player [v0.170](https://github.com/moneytoo/Player/releases/tag/v0.170) for all the testings to keep it consistent. I've tested all non-beta versions from 0.18.2 to 0.17.9 and 0.17.9 is the latest version that do not give my problems. I suspect [this PR](https://github.com/jellyfin/jellyfin-androidtv/pull/4094) which is mentioned in release note of 0.18.0 may be the cause of external subtitle problems.

Jellyfin server logs (from the time of testing different versions):
[jellyfin.log](https://github.com/user-attachments/files/18160298/jellyfin.log)

MediaInfo from Jellyfin API `/Items/{itemID}`
[response_1734410146755.json](https://github.com/user-attachments/files/18160308/response_1734410146755.json)

Please let me know if I need to provide other logs to resolve this issue.

### Application version

0.18.x

### Where did you install the app from?

Google Play

### Device information

Homatics Box R 4K Plus

### Android version

Android 12

### Jellyfin server version

10.10.2

**Comment by nielsvanvelzen** [comment]
Thanks for the report, due to a bug all external subtitles were filtered out so they didn't get send to the external player. Fixed for 0.18.3!
