### ISSUE TITLE
Repeat song does not work

### ISSUE THREAD

**Issue by Jeff9000** [jellyfin/jellyfin-androidtv#4328]
### Describe the bug

1. In Music select an album or a song and Play. In the controls (previous, pause/play, next, repeat) select repeat until it turns red.
2. The song will continue to play, but when it ends it does not repeat playing the same song again.
3. The app gets a little buggy from that point on where basically you need to exit Jellyfin to play that song again.

This does not happen in the previous version of 0.17.9

### FFmpeg logs

```shell

```

### Media info of the file

```shell

```

### Application version

0.18.2

### Device information

Google Google Streamer

### Android version

Android TV 14

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
Thanks for reporting. I have a fix in the work. The second issue (play button not working after the item stopped playing) is already fixed, the other one (repeat not working) I have a fix for that I'm not satisfied with yet. Both fixes will be included in the next release!
