### ISSUE TITLE
The layout of the browsing grid is abnormal.

### ISSUE THREAD

**Issue by rickwzq** [jellyfin/jellyfin-androidtv#4332]
### Describe the bug

[jellyfin-tv-layout-issue.mp4](http://vp.rickw.cn/jellyfin-tv-layout-issue.mp4)

The first row of the grid is misaligned.

The first column can navigate up and down normally through the remote control.
The navigation in the second column is abnormal.

### Application version

0.18.2

### Where did you install the app from?

None

### Device information

Xiaomi MiTV-ASTP0

### Android version

MiTV OS 2.7.1886

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
Can you reupload the video to a different site? I can't seem to connect to the current one.

**Comment by rickwzq** [comment]
> Can you reupload the video to a different site? I can't seem to connect to the current one.

[wetransfer-jellyfin-tv-layout-issue.mp4](https://wetransfer.com/downloads/51d4f38acb24ff685a8c201fc8ab5ae920241222100200/ea71ce0a42d980f42e03abaa02b1b9e220241222100310/3dcf96?t_exp=1735120920&t_lsid=a9346e1d-8d8d-4df0-a18c-cff30611d54a&t_network=email&t_rid=ZW1haWx8Njc2N2UzOWIzYjQ1MTBjYmM4NWU1ZWM1&t_s=download_link&t_ts=1734861790&utm_campaign=TRN_TDL_01&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_01)

[filetransfer-jellyfin-tv-layout-issue.mp4](https://filetransfer.io/data-package/FapVw5Pl#link)

**Comment by nielsvanvelzen** [comment]
Thanks for the reupload, I was able to see the video now. It looks like your using a mixed videos or home video library type. These libraries don't have a strict size for the images defined so the app will display them dynamically, this means that not all items will have the same size and the grid will be somewhat off.
You can change the library options in the app (gear icon) and play with the image type/grid direction options and see if that improves the layout for your use-case.

Closing as not-a-bug.

**Comment by rickwzq** [comment]
> Thanks for the reupload, I was able to see the video now. It looks like your using a mixed videos or home video library type. These libraries don't have a strict size for the images defined so the app will display them dynamically, this means that not all items will have the same size and the grid will be somewhat off. You can change the library options in the app (gear icon) and play with the image type/grid direction options and see if that improves the layout for your use-case.
> 
> Closing as not-a-bug.

When using the remote control for operation, the posters in the grid are randomly misplaced.
The size of the poster images is the same.

[poster-misaligned.mp4](https://filetransfer.io/data-package/lEBQLweN#link)

**Comment by nielsvanvelzen** [comment]
That is, although not great, how it is supposed to work. Will most likely change once we rewrite the browsing part of the app.
