### ISSUE TITLE
Jellyfin is utterly unstable and unusable on FireStick 4K

### ISSUE THREAD

**Issue by AnharHussainMiah** [jellyfin/jellyfin-androidtv#4343]
### Describe the bug

I've upgraded to the latest version `0.18.2` and the issues that I've had since `0.15.0` _still_ haven't gone away. If anything it has gotten _worse_ on each release.

I don't know what the underlying issue is, but at very specific points, the video playback will either crash, a which point Jellyfin will take multiple attempts to play the file, in some cases it succeeds and in some cases it will stop saying something like "crashed too many times" or something similar.

Other times, the video will freeze but the audio will continue.

I'm not doing any transcoding, but NONE of these videos are taxing, as they're all 1080P mp4 files.

I've used multiple combination of settings, _NOTHING_ works, same videos crashes or pauses _(always at the exact same points)_, on pretty much most of the videos.

Now here is he kicker:

When I use the FireStick's **Silk** browser (Firefox engine underneath IIRC), then _everything_ just works, no freezes, no glitches, no random crashes.

Of course the experience isn't _as_ good, mainly the navigation (it's a browser with a cursor), however it's _almost_ tolerable.

At this point, I don't understand why the FireStick Client doesn't just embed browser view, slap some keyboard (D-Pad) navigation and call it day, that way it would _actually_ REDUCE the number of codebases to maintain.

Question is, why does the Web client work flawlessly on the _same_ device yet the "native" client is so shockingly bad?

I'm pretty much out of options:

* Kodi, amazing performance, but nobody has the time nor patience to set all that up
* Emby (yeah I know it's how I found out about JellyFin): already moved to JellyFin so I don't want to go back to Emby
* Plex: too much junk, I hate it and I think you need to pay to get most of what you get out of the box in JellyFin.
* JellyFin: almost perfect, except when using the "native" FireStick client, it's gotten worse and now pretty much unusable
* MrMC: It's a Kodi fork?
* what else?

There really isn't anything else, I _really, really_ want the Native FireStick client to _just work_ nothing is worse then having your video glitch over and over, or randomly freeze etc.

I don't _want_ to use the web version, **BUT** it's the _only_ client that consistently _just works_

But as already mentioned, the web client _doesn't_ have any notion of the FireStick D-Pad. IF D-Pad navigation could be added to the Web client, and then a native app with a Web View was created, that would actually solve so many issues as it would be "good enough", the main thing is flawless media playback, I mean if a media player can't do that, then it pretty much is pointless! 

### Application version

0.18.2

### Where did you install the app from?

Sideloaded APK

### Device information

FireStick 4K

### Android version

Fire OS 7

### Jellyfin server version

10.8.3

**Comment by thornbill** [comment]
If you are having issues with crashes during playback, complete the playback issue template and **provide media information and logs**.
