### ISSUE TITLE
海报墙下面不显示影片名字

### ISSUE THREAD

**Issue by jiujiu2017** [jellyfin/jellyfin-androidtv#4353]
### Describe the bug

海报墙下面不显示影片名字[](url)

### Application version

0.18.3

### Where did you install the app from?

None

### Device information

tv

### Android version

1

### Jellyfin server version

10.8.1

**Comment by nielsvanvelzen** [comment]
> The name of the movie is not displayed under the poster wall

Not a bug, duplicate of #654
