### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-androidtv#436]
We should add issue templates so users actually post logs / media information in their issues. This will help us to reproduce issues.

I think we can base the templates on the ones in the server repository.

**Comment by thornbill** [comment]
One thing to keep in mind is that logs can be challenging to retrieve from the app since it requires installing the Android SDK, enabling debugging, etc. That said I agree having a template would be a great improvement!
