### ISSUE TITLE
Not updating to 0.18.3 on Chromecast AndroidTV 4K

### ISSUE THREAD

**Issue by JohnnyDrama** [jellyfin/jellyfin-androidtv#4361]
### Describe the bug

Play store on my Chromecast with AndroidTV is not offering the latest update (0.18.3). Also tried sideloading the apk but it won't install. Is this something you expect or is it something that can be fixed? My Chromecast is uptodate (OS AndroidTV 12, build STTL.240812.006.N1.12570082)

### Application version

0.18.3

### Where did you install the app from?

Sideloaded APK

### Device information

Chromecast AndroidTV 4K

### Android version

AndroidTV 12

### Jellyfin server version

10.10.3

**Comment by nielsvanvelzen** [comment]
The app installs from the Amazon and Google stores have different signatures and thus cannot be interchanged with the versions signed by us (the Jellyfin team). If you want to switch between a release from us or one of those two stores you'll need to uninstall the app first. Be aware that the stores will then no longer automatically update the app.

The recent 0.18.3 release was tagged only 3 days ago and with the holiday season it takes longer for the store teams to review & approve. Additionally we use slow rollouts and thus you probably don't receive the update yet unless you're a Google Play beta user.
