### ISSUE TITLE
Very big subtitles that never changes even if you change the size settings

### ISSUE THREAD

**Issue by tayhr** [jellyfin/jellyfin-androidtv#437]
No matter what size I set in the server, I think that the subtitle size is always 'larger' by default.

Jellyfin Version: 10.5.4:stable
Operating System: Windows 10
Architecture: X64
Installed Plugins: Open subtitles, MusicBrainz, AudioDB
Base URL: none
Storage: Local
Client: Mi Box, Android Version 6

My configs:
Preferred subtitle language: Any Language
Subtitle mode: Default
Burn subtitles: Auto
Text size: Normal
Font: Default
Drop shadow: Drop shadow

Subtitle type: external .SRT

**Comment by nielsvanvelzen** [comment]
The app does not use the users preferences for subtitles. Marking this as enhancement.

**Comment by tayhr** [comment]
Is there any possibility to decrease the subtitle size? It is very large and sometimes occupies a very large space on the screen

**Comment by thornbill** [comment]
Yes. Some improvements are already in the queue for the next major release! https://github.com/jellyfin/jellyfin-androidtv/pull/396

**Comment by Cloneg** [comment]
Android tv still has big subtitles and no option to change. 1080p video. Default video player. Chromecast with GoogleTV.

**Comment by thornbill** [comment]
Yes we are aware. The next release (0.12) has not shipped yet.

**Comment by DemirG** [comment]
> Yes we are aware. The next release (0.12) has not shipped yet.

Hi, what is the estimated date of release for 0.12?

**Comment by DemirG** [comment]
> Yes we are aware. The next release (0.12) has not shipped yet.

I see that the subtitles are changed to a smaller font in the new beta. Thank you very much for the work! Looks better now.

**Comment by 2pandaemonium2** [comment]
I just switched from Plex to Jellyfinn, and still cannot figure out why it's such a big deal to just add a feature to change the font on the device you're watching it. I mean there are so many features but subtitles are a pig part of watching movies. The GUI looks great and even the metadata algorithm works great. If this subtitle feature could be added it can really be a competitor to PLEX. Please consider that guys. thx!

**Comment by nielsvanvelzen** [comment]
> to change the font 

This issue isn't even about changing fonts

**Comment by 2pandaemonium2** [comment]
> > to change the font
> 
> This issue isn't even about changing fonts

i know, i meant font/subtitle size

**Comment by 2pandaemonium2** [comment]
> > to change the font
> 
> This issue isn't even about changing fonts

any hope there will soon be the option of changing the subtitle size? :)

**Comment by nielsvanvelzen** [comment]
No need for to reply two times. Changing subtitle styling is definitely something we'd like to add but it will probably be after #1057.

**Comment by 2pandaemonium2** [comment]
is that really a huge problem now for you that I replied two times? I just asked something i hadn't asked before. anyways..

**Comment by a1ad** [comment]
Ah yes, i too find the subs way too big. But i always have some black background behind the subtitles! Its the one thing holding me back.

**Comment by dcrypt11** [comment]
Same issue here

**Comment by a1ad** [comment]
> Same issue here

It's solved since four years :-)

**Comment by dcrypt11** [comment]
> > Same issue here
> 
> It's solved since four years :-)

And yet I have big subtitles in the center of my iphone 13 mini and my ipad m1 screens

**Comment by nielsvanvelzen** [comment]
How do you use an Android tv app on your iPad and iphone?
