### ISSUE TITLE
Pause with transcode

### ISSUE THREAD

**Issue by EVOTk** [jellyfin/jellyfin-androidtv#439]
OS: Docker on Synology ( DSM 6.2.2-6 )
Jellyfin Version: 10.5.4
Hardware settings & device: VAAPI (I5-8600k)
Jellyfin AndroidTV : 0.11.3

When I transcode, if I pause the reading (2min approximately), when I restart the reading, after approximately 1min, the film stops and I return to the page of description of the film!

The bug reoccurs every time, on Android TV or Android TV for Fire Stick.
This does not happen if I play the film (in transcoding) from Firefox 75 or the Android application (smartphone) for example.

In the logs, we see that during the pause, the process is "killed" (Killing transcoding) but is not resumed when resuming reading!

The problem was already present in the previous version of AndroidTV.

> [2020-04-17 02:41:27.628 +02:00] [INF] [128] App: Transcoding kill timer stopped for JobId "d4a40590434b409d8281a0ca506c33e7" PlaySessionId "a8a8a06e0ddd469e98c2f1e729644d57". Killing transcoding
[2020-04-17 02:41:27.628 +02:00] [INF] [128] App: Stopping ffmpeg process with q command for "/config/data/transcodes/a01d1fd7d268f5c8346d61a752a81867.mkv"
[2020-04-17 02:41:27.655 +02:00] [INF] [128] MediaBrowser.Api.Playback.Progressive.VideoService: FFMpeg exited with code 0
[2020-04-17 02:41:27.655 +02:00] [INF] [128] App: Deleting partial stream file(s)    ###"/config/data/transcodes/a01d1fd7d268f5c8346d61a752a81867.mkv"

Sorry for my english, don't hesitate to ask me for more details if necessary.

----------------

**After several tests:**
The problem seems to be present only from an external connection ( via ngnix reverse proxy ) and transcode only in Android TV App and Fire Stick App. ( no problem with firefox for example ).

**Local :** 
No Problem

**Remote Connection HTTP :** 
No Problem

**Remote Connection HTTPS :** 
Windows / Firefox 75 > OK
Xiaomi Box 3 / Android TV > NOK
Fire Stick / Android TV > NOK
Jellyfin Plugin for Kodi > OK

**Comment by EVOTk** [comment]
OS: Docker on Synology ( DSM 6.2.3 )
Jellyfin Version: 10.5.5

the problem is still here :(

**Comment by EVOTk** [comment]
I noticed that if I resume a video which had been interrupted, for example at minute 20 out of 50, while on Andoid TV the reading goes well on the dashboard, the stream is indicated to have started at 0 minute.
And therefore once the last 30 minutes of the episode seen, it is not marked as seen. (because for him I am only watched from minute 0 to 30 and not 20 to 50)

**Comment by EVOTk** [comment]
OS: Docker on Synology ( DSM 6.2.3-2 )
Jellyfin Version: 10.6.2
Jellyfin AndroidTV : 0.11.4


the problem is still here :(

**Comment by EVOTk** [comment]
OS: Docker on Synology ( DSM 6.2.3-2 )
Jellyfin Server Version: 10.6.2
Jellyfin AndroidTV : 0.11.4

the problem is still here :(

**Comment by thisis-mental** [comment]
I confirm having the same behavior on Android TV only.

**Comment by EVOTk** [comment]
OS: Docker on Synology ( DSM 6.2.3-3 )
Jellyfin Server Version: 10.7.0
Jellyfin AndroidTV : 0.11.4

the problem is still here :(

**Comment by EVOTk** [comment]
OS: Docker on Synology ( DSM 6.2.3-3 )
Jellyfin Server Version: 10.7.0
Jellyfin AndroidTV : 0.11.5

The problem is solved !
Thanks
