### ISSUE TITLE
Add media_session_state (homeassistant.io)

### ISSUE THREAD

**Issue by D34DC3N73R** [jellyfin/jellyfin-androidtv#441]
I like to use an automation with home assistant that dims my lights when media is playing, and brightens them on pause/standby. Since there is no standard API to determine the playback state, the AndroidTV package in home assistant uses adb to poll the client and reads 3 properties to best determine the device play state; `audio_state`, `wake_lock_size`, and `media_session_state`. 

On most apps, (netflix, plex, etc) both wake_lock_size and media_session_state differ when the app is paused, playing, or idle. Unfortunately, the only property that changes in Jellyfin is wake_lock_size. This not only means, out of the box, jellyfin doesn't work with the standard playback state reporting, but it also isn't reliable even when using custom state detection rules. Even with custom rules in place, wake_lock_size can sometimes change during playback, triggering the automation to brighten the lights while media is still playing.

Jellyfin
```
org.jellyfin.androidtv
standby
'audio_state': 'paused', 'wake_lock_size': 1, 'media_session_state': None
paused
'audio_state': 'paused', 'wake_lock_size': 1, 'media_session_state': None
playing
'audio_state': 'paused', 'wake_lock_size': 3, 'media_session_state': None
```

Plex
```
com.plexapp.android
standby
'audio_state': 'paused', 'wake_lock_size': 1, 'media_session_state': None
paused
'audio_state': 'paused', 'wake_lock_size': 1, 'media_session_state': 2
playing
'audio_state': 'paused', 'wake_lock_size': 3, 'media_session_state': 3
```

Netflix
```
com.netflix.ninja
standby
'audio_state': 'paused', 'wake_lock_size': 0, 'media_session_state': 1
paused
'audio_state': 'paused', 'wake_lock_size': 0, 'media_session_state': 2
playing
'audio_state': 'paused', 'wake_lock_size': 2, 'media_session_state': 3
```

Would integrating media_session_state into the Jellyfin AndroidTV app be something you guys would consider?

**Comment by nielsvanvelzen** [comment]
In 0.13 the plan is to rewrite the playback part of the app and media session support will be added. For now it's possible to query the Jellyfin server for playback state of the app. You could probably make a plugin to forward this information to homeassistant.

**Comment by dkanada** [comment]
cc @joshuaboniface who I think knows about this

**Comment by D34DC3N73R** [comment]
While a plugin for jellyfin is feasible, I'd much prefer to have a native integration so I don't need a bunch of duplicate conditional automations. Thanks for the info. Looking forward to 0.13!

**Comment by dkanada** [comment]
That's a good reason in my book. I do recall someone mentioning the Emby plugin was almost a drop-in replacement for Jellyfin, shame no one has picked that up yet.

**Comment by nielsvanvelzen** [comment]
In 0.16 we have support for media sessions when playing music/audiobooks. This will be extended to video playback later.
