### ISSUE TITLE
Configurable Skip length

### ISSUE THREAD

**Issue by eupherium** [jellyfin/jellyfin-androidtv#460]
**Describe the feature you'd like**	
On the web client it is possible to set the Skip forward and Skip back length, however the Android TV client does not support this. The skip length is seems to be hardcoded for 30/10 respectively.

I would suggest either respect the settings from the web client or have a separate setting for this on the Android TV client.

**Additional context**	
I am using version 0.11.3 and I am impressed with the recent improvements.

**Comment by MrChip53** [comment]
Is this just for when pushing rewind and fast forward buttons?

**Comment by levihb** [comment]
Huh? Mine seems to be limited to +/- 30s in both directions? Is there a way I can change it to 10s?

**Comment by nielsvanvelzen** [comment]
You can change the forward/backward lengths from the web interface. Go to settings -> playback. It's not possible right now to change these from within the app, but it does use those values.

**Comment by flakpyro** [comment]
Using the Jellfin app on a Nvidia Shield it appears configuring the skip length via the payback page does not trasfer over to the app. The skip length changes in the browser but the android apps values stay the same.

**Comment by tump13b** [comment]
> Looks like it's hardcoded here: https://github.com/jellyfin/jellyfin-androidtv/blob/2de77f5719a847936d974503c648f73552342cc8/app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.java - it'd be awesome if this was configurable

Up until a month or two ago my google tv app would match whatever was configured on my PC. And then out of nowhere it's stuck at 30s/30s. A dev on reddit said that it was hardcoded. Why would this change be made?

**Comment by Victoare** [comment]
> Looks like it's hardcoded here: https://github.com/jellyfin/jellyfin-androidtv/blob/2de77f5719a847936d974503c648f73552342cc8/app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.java - it'd be awesome if this was configurable

Ohh, and i thought that something with my setup is wonky. This is a very strange behaviour for me that that is skip to the nearest 30sec position. It will skip back to 10:30 from 10:31 and also from 10:59.

I hope it will someday change something like in kodi where we could configure the skip time in sequence (like the first press is 5 sec, the second is 10, the third is 30), or if it not possible to be this sophisticated, then to be configured to skip given secs and not to the nearest divider.

**Comment by tump13b** [comment]
> > Looks like it's hardcoded here: https://github.com/jellyfin/jellyfin-androidtv/blob/2de77f5719a847936d974503c648f73552342cc8/app/src/main/java/org/jellyfin/androidtv/ui/playback/overlay/CustomSeekProvider.java - it'd be awesome if this was configurable
> 
> Ohh, and i thought that something with my setup is wonky. This is a very strange behaviour for me that that is skip to the nearest 30sec position. It will skip back to 10:30 from 10:31 and also from 10:59.

Mine does the same thing.

> 
> I hope it will someday change something like in kodi where we could configure the skip time in sequence (like the first press is 5 sec, the second is 10, the third is 30), or if it not possible to be this sophisticated, then to be configured to skip given secs and not to the nearest divider.

Has yours always acted like this? Mine didn't until recently. Why would this be changed? And how hard would it be to change back? I really don't understand this. I appreciate jellfin and the work the devs do greatly, but this is such a massive issue as I often need to rewind slightly.

**Comment by Victoare** [comment]
> Has yours always acted like this? Mine didn't until recently. Why would this be changed? And how hard would it be to change back? I really don't understand this. I appreciate jellfin and the work the devs do greatly, but this is such a massive issue as I often need to rewind slightly.

In that specific file, the code is last modified 3 year ago, so it is probably worked like this since the beginning.
Also there is a playback rewrite project ( https://github.com/jellyfin/jellyfin-androidtv/issues/1057 ) running for quite some time actively.

**Comment by tump13b** [comment]
> You can change the forward/backward lengths from the web interface. Go to settings -> playback. It's not possible right now to change these from within the app, but it does use those values.

Solution: 
If you change it in the web interface like suggested in the quote above, then these are the values that will be used when you press on the forward skip/backward skip buttons on the android tv interface. What doesn't change is if you just press left and right on your remote. You have to make sure the icons are selected and then press select. Otherwise it will always be 30 seconds.

**Comment by Recursiivio** [comment]
Please make it adjustable from decimals 0.5 to 30.0 seconds, 5 seconds is far too lengthy of a time as lowest value. Customizable please.

**Comment by benrtd** [comment]
> 
> Solution: If you change it in the web interface like suggested in the quote above, then these are the values that will be used when you press on the forward skip/backward skip buttons on the android tv interface. What doesn't change is if you just press left and right on your remote. You have to make sure the icons are selected and then press select. Otherwise it will always be 30 seconds.

Thank you x1000 for this tip. I've been using the back/forward directional buttons and have been going crazy. The other buttons were there the whole time. Thank you!

**Comment by tump13b** [comment]
> > Solution: If you change it in the web interface like suggested in the quote above, then these are the values that will be used when you press on the forward skip/backward skip buttons on the android tv interface. What doesn't change is if you just press left and right on your remote. You have to make sure the icons are selected and then press select. Otherwise it will always be 30 seconds.
> 
> Thank you x1000 for this tip. I've been using the back/forward directional buttons and have been going crazy. The other buttons were there the whole time. Thank you!

Happy that it helped somebody!

And just to clarify one of my previous comments where I said that it worked fine and then all of a sudden didn't work fine - I think I may have originally been doing it with the on screen buttons correctly, and then not used jellyfin in a while and completely forgotten about it and gone to just using the remote left/right instead.
