### ISSUE TITLE
Playback position lost on screen saver

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin-androidtv#464]
If playback is paused and the unit is left until the screen saver kicks in, it is often impossible to resume playback, and it looses the position you were at.

Can recreate

Device: Fire TV Stick, Version: 0.11.3

**Comment by samwathegreat** [comment]
Confirmed.  It happened to me today.  I only had live tv paused for a very short time, then I saw the screensaver kick on.  When I tried to unpause, it took me back to the guide.  I didn't get to see the end of my show and it was disappointing (LOL).

**Comment by Qiangong2** [comment]
Can confirm, this happens on my xiaomi mi box
