### ISSUE TITLE
"Device Storage Is Very Low"

### ISSUE THREAD

**Issue by grravity** [jellyfin/jellyfin-androidtv#472]
**Describe the bug**
I assume this is some kind of caching issue, and is very random and does it only on rare occasions I find, but it just happened again which is why I am creating this issue. Both on my Xiamoi Mi Box and Nvidia Shield TV I receive pop-ups saying the device is low on storage. I believe it is talking about internal space on the media player, not the device I am streaming from, as the players only have a bit under 20gb internal (before any apps loaded, which aren't alot so there's still AT LEAST a solid 10gb, or should be), so I assume this is cache filling up while playing. My host is not near full so that shouldn't be the issue. 

The notification would be ok if it popped up once, but for example I was watching Tron Legacy, and it popped op, then disappeared, then a few minutes later popped up again, then disappeared, then popped back up. To my knowledge, I've been through every setting so unless it's some niche developer setting I missed, then there is no way (to my knowledge) to turn that pop-up off. 

Now I'm not sure if caching improvements could be made, or what which is why I am creating this issue. But I'm not sure if it is normal for it to be filling up this much while playing? Just to give a reference, the movie I was playing tonight has it's specs listed below:

**Video**
Title: 1080P H264
Codec: H264
AVC: Yes
Profile: High
Level: 41
Resolution: 1920x1080
Aspect ratio: 16:9
Interlaced: No
Framerate: 23.976025
Bitrate: 30009 kbps
Bit depth: 8 bit
Pixel format: yuv420p
Ref frames: 1
NAL4

**Audio**
Title: Eng DTS 7.1 Default
Language: eng
Codec: DTS
Profile: DTS-HD MA
Layout: 7.1
Channels: 8 ch
Sample rate: 48000 Hz
Bit depth: 24 bit
Default: Yes

**Subtitle** --(DISABLED DURING THE MOVIE)--
Title: ENG - Default
Language: eng
Codec: PGSSUB
Default: Yes
Forced: No
External: No

**System (please complete the following information):**
 - Latest Android TV available on Nvidia Shield TV 1st Gen (I turned everything off and am not sure off hand, remind me to grab this when you reply if it is of true importance, sorry.)
 - Jellyfin server version: [e.g. 10.5.4]

**Comment by thornbill** [comment]
This should have been fixed in the latest release (0.11.3). See #417.

If you are still seeing this on the current release feel free to reopen.

**Comment by grravity** [comment]
>See #417.

Ah, my bad, I searched for an issue before making this, but I guess I only searched for open issues.
 
> This should have been fixed in the latest release (0.11.3). 
> If you are still seeing this on the current release feel free to reopen.

Has this release been pushed  to the play store yet? I believe I just checked for updates a few days ago and nothing was there, I could possibly be on the latest. I will check tomorrow and update.

**Comment by thornbill** [comment]
It should be available in the play store. You can also check the current version in the app settings.

**Comment by grravity** [comment]
Yes my bad, there was an update. Not sure why I didn't recieve it before. If I encounter future issues I'll reopen
