### ISSUE TITLE
Next episode with subtitles from previous

### ISSUE THREAD

**Issue by joaovitoriasilva** [jellyfin/jellyfin-androidtv#477]
When seeing multiple episodes, imagine just finished the first episode and the second one starts automatically, the second episode uses the subtitles from the first episode. If I set the subtitles to off and then to ENG again, then it uses the correct subtitles.

**Comment by AndreasGB** [comment]
Hi there, this seems to be a duplicate of #108, so I'll close this for now. If that is incorrect, feel free to reopen :)
