### ISSUE TITLE
Support Leanback on any android box

### ISSUE THREAD

**Issue by gabriellluz** [jellyfin/jellyfin-androidtv#48]
Hi there.

I remember using Emby for Android TV on my Android TV Box and there was no Leanback because my android box is not "certified" by Google. Plex android app has a leanback mode setting, you just have to enable it. VLC media player also has that option.

It's really important if you guys create an option called "Enable Leanback theme" inside Jellyfin app so that we don't need a Fire TV or a Mi Box or an Nvidia Shield device.

**Comment by bfayers** [comment]
I know this isn't a fix internal to our app, but it may still be useful for some people with these cheap Android boxes.

https://forum.freaktab.com/forum/development-area/rom-hacks-and-mods-development/602282-tutorial-how-to-get-the-ultimate-android-tv-experience-on-r-box-pro

If the box is rooted, you can get leanback.

**Comment by gabriellluz** [comment]
That tutorial doesn't work with my box. It's outdated.

**Comment by gabriellluz** [comment]
Thanks anyway, my friend.

**Comment by gabriellluz** [comment]
A suggestion would to enable Leanback on the first run. When you first run Jellyfin for Android TV, it'll show you a screen that connects to your Jellyfin server and lets you enable leanback mode at the same time.

**Comment by thornbill** [comment]
Are there specific pages in the application that do not display as expected? I installed the apk on an Android phone to try and replicate this, but most of the navigation within the app seems to use the leanback theme. I did notice the sign in pages and settings page did not however.

**Comment by gabriellluz** [comment]
My android box is not working anymore so I can't test it again. Probably something changed because it was clearly not leanback and I had to use a mouse in order to control it.

**Comment by PitekTerbang** [comment]
ATV OS
https://youtu.be/1WzhKcwg7TA

**Comment by gabriellluz** [comment]
> ATV OS
> https://youtu.be/1WzhKcwg7TA

Sorry, that won't solve the problem. I'm talking about the end-user, not a special one.
In that case, you want the person to change build data in order to make it leanback.

**Comment by thornbill** [comment]
I am going to close this for now, but if you have any issues in the future, feel free to re-open or create a new issue! Thanks!
