### ISSUE TITLE
Version selection missing

### ISSUE THREAD

**Issue by tinect** [jellyfin/jellyfin-androidtv#484]
**Describe the feature you'd like**	
I habe some movies in different versions (related https://jellyfin.org/docs/general/server/media/movies.html#multiple-versions-of-a-movie). But just the last version is shown and played in the app. I wish there wojld be a selection like in web, too.

**Additional context**	
Having 2160P and 1080P, 1080P will always be played.

**Comment by thornbill** [comment]
Thanks for the feedback! This is being tracked by #173.
