### ISSUE TITLE
Fire TV Stick 4k transcoding HEVC

### ISSUE THREAD

**Issue by stefanrybacki** [jellyfin/jellyfin-androidtv#485]
On Fire TV Stick 4K video files encoded using HEVC are transcoding even though the stick can handle HEVC natively just fine.

**Comment by AndreasGB** [comment]
Hi @stefanrybacki,

thank you for the report. The current playback code we inherited is a mess and will be rewritten in 0.13, which will almost certainly resolve this as well, but this is still a ways off. 

In the meantime if the transcoding overloads your server, you could pre-transcode your media files.

**Comment by greymda** [comment]
is there any ETA on 0.13?

**Comment by nielsvanvelzen** [comment]
There is no ETA on 0,13. We are currently working towards 0.12 (which doesn't have an ETA either)
