### ISSUE TITLE
Firecube running FireOS 7.2.1.2 search not working 

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#489]
Hi using the latest release Jellyfin android TV apk on firecube search not working but fine on 4k firestick

**Comment by nielsvanvelzen** [comment]
Can you explain what is not working? If you search for something and wait a few seconds, does nothing come up? Or can you not open the search screen?

**Comment by tomaswl1** [comment]
Cannot open the search screen

**Comment by nielsvanvelzen** [comment]
I've searched in the crash reports but I can't find any crashes for the search screen. Do you have crash reporting turned on?

**Comment by tomaswl1** [comment]
It was denied permissions causing the issue mate it never crashed the app it just wouldn't do anything upon clicking search but upon accepting permissions after a reinstall it's working mate apologies i must of denied first time round

**Comment by nielsvanvelzen** [comment]
So by permissions, do you mean the permissions to use the microphone?

**Comment by tomaswl1** [comment]
yes mate if denied it wont open search
