### ISSUE TITLE
high-pitched sound and inaudible on liveTV

### ISSUE THREAD

**Issue by Astate** [jellyfin/jellyfin-androidtv#50]
I have sound problem with https://repo.jellyfin.org/releases/client/androidtv/jellyfin-androidtv_amazon-release_beta3.apk.

The sound problem its like high-pitched sound

I use Firestick 4k.
The sound are very better with JellyfinCon kodi Addon (its clone of EmbyCon addon).
The image alose better with kodi  then androidtv app.

**Comment by thornbill** [comment]
We just released a version of the app (beta 4) which includes an update to the base version of the app. These changes resolved a lot of the playback issues that I was seeing in my testing. Please test the latest release and let us know if your playback issues are also resolved. Thanks!

**Comment by Astate** [comment]
Now with beta 4, i have black screen on live tv

**Comment by AndreasGB** [comment]
Hi @Astate, is this still an issue you experience on the current version?

If we don't hear back from you in the next two weeks I'll go ahead and close this issue. You can of course re-open it at any time if the problem persists :)

**Comment by MrChip53** [comment]
@thornbill @nielsvanvelzen Can we close this issue? They did not respond and I have not noticed any such issues in my entire time using Jellyfin on both Nvidia Shield and FireTV

**Comment by nielsvanvelzen** [comment]
I'll close this one since we already asked the author and didn't get any reply. Feel free to re-open or re-create if the issue still happens.
