### ISSUE TITLE
hardcoded texts

### ISSUE THREAD

**Issue by tinect** [jellyfin/jellyfin-androidtv#507]
**Describe the bug**
There is a few hardcoded text for dialogues in code. Please create keys for translations.
Here are the one I found within "setmessage". Maybe you find some others in usages of "Utils.showToast" or "Toast.makeText"

- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java#L97
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/ExternalPlayerActivity.java#L132
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/util/Utils.java#L210-L211
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java#L660-L661
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/details/ItemListActivity.java#L678-L679
~~https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/details/FullDetailsActivity.java#L795~~
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java#L282
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/PlaybackController.java#L301
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/playback/MediaManager.java#L336
- https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/livetv/LiveTvGuideActivity.java#L371-L372

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**

**Additional context**

**Comment by nielsvanvelzen** [comment]
FullDetailsActivity.java will be removed soon (replaced by our new details screen) so if anyone likes to work on this issue, ignore that particular file.

**Comment by PalAditya** [comment]
Hi, it seems this issue is still open, so could I work on it?
Also, would it involve changing only the files mentioned in the issue or the entire codebase?

**Comment by nielsvanvelzen** [comment]
Hi @PalAditya, feel free to work on this issue! The files mentioned in the post are a good start but the codebase did change since this issue was created so there might be more places with hardcoded strings. I think that Android Studio has tools to help find those.
