### ISSUE TITLE
Feature Request: Direct Play support Opus (audio) surround sound format

### ISSUE THREAD

**Issue by RandomNinjaAtk** [jellyfin/jellyfin-androidtv#509]
**Describe the feature you'd like**	
Direct Play support Opus (audio) surround sound format

**Additional context**	
Using a Nvidia ShieldTV, Opus will not direct play for surround sound. Opus does direct play for Music though...

**Comment by RandomNinjaAtk** [comment]
Also note, I have tested that Plex can play it back without transcoding, but that may not be an Apples to Apples comparison.

**Comment by nielsvanvelzen** [comment]
This should be fixed now, let us know if the issue still persists in the latest version (0.14).
