### ISSUE TITLE
crashed and went to next episode

### ISSUE THREAD

**Issue by lelamamalgache** [jellyfin/jellyfin-androidtv#511]
Hello, 30 secondes before the end of the tv show, the tv show crahed and he decided to jump automaticly to the next episode. 

tv show : "/video/Series/V (2009)/S2/02x01.mkv"
time crashed 00:47 

**System (please complete the following information):**
 - Android TV or Fire TV version: android tv
 - Device manufacturer: Amazon
 - Device model: firestick 4K
 - Jellyfin server version:10.5.5
 - docker : lsio-letsencrypt, lsio-jellyfin
 - https hairpin on my router for my lan network

[jellyfin.txt](https://github.com/jellyfin/jellyfin-androidtv/files/4777379/jellyfin.txt)
[transcode.txt](https://github.com/jellyfin/jellyfin-androidtv/files/4777381/transcode.txt)
[firestick4K.txt](https://github.com/jellyfin/jellyfin-androidtv/files/4777382/firestick4K.txt)  adb logcat > firestick4K.txt

**Comment by AndreasGB** [comment]
Hi there, 

this might be normal behavior unrelated to the crash, as playback that is stopped close to the end of an episode is considered as having finished the item by the server.

As a workaround, you can disable that behavior in the server settings under playback -> resume -> maximum resume percentage.

As a permanent solution, there might be a need for the server to be able to differentiate between crash and legitimate playback termination. I'm not sure if that is currently possible, maybe a server person could chime in? @jellyfin/backend
