### ISSUE TITLE
Option to disable menu items

### ISSUE THREAD

**Issue by dpickles** [jellyfin/jellyfin-androidtv#512]
Is it possible to get an option to disable menu items which are not in use? 

Currently I don't use the "Live TV" feature and I doubt I will in the future. I would love to be able to hide this so that it's not an option and create a more person flow to the ui.

Thanks

**Comment by nielsvanvelzen** [comment]
You can re-order what sections appear on your homepage using the web version of Jellyfin. It's currently not possible to change these sections inside of the tv app.

**Comment by dpickles** [comment]
Oh great. I tested this last night and it seems to solve my problem.
Would be great to see this included within the app at a later date. 

Thanks
