### ISSUE TITLE
Some eac3 audio has no sound, and the jellyfin Android client can play it normally

### ISSUE THREAD

**Issue by 3137695831** [jellyfin/jellyfin-androidtv#515]
Some eac3 audio has no sound, and the jellyfin Android client can play it normally
jellyfin-androidtv_release_0.11.3.apk

**Comment by nielsvanvelzen** [comment]
Hi, I noticed this issue does not use one of our issue templates. We provide these templates to get the information necessary in order to help. I will close this issue but I encourage you to recreate it using the template so we can help.
