### ISSUE TITLE
Move selection to "Resume From" after video is backed out

### ISSUE THREAD

**Issue by MrChip53** [jellyfin/jellyfin-androidtv#518]
**Describe the feature you'd like**	

Automatically move the selector to "Resume From" after the user backs out of a video and the video screen loads back up.

This is only an issue if the movie is started from "Play".

If I leave a video paused too long my Shield TV will back out of it and sometimes without realizing I hit Play and lose my spot.

**Comment by MurrayGroves** [comment]
Bump, this is really annoying.

**Comment by MrChip53** [comment]
I've looked through the code on this issue and didn't see a reason for it happening. Also, when I play a video and back out it works fine now. When does this happen to you? I believe my original issue with it was, pause video, leave do something, come back and nividia is on screen saver, wake up off screensave -> focused on Play and not Resume From.

Is that the same as you are experiencing? or is your situation different?

**Comment by MurrayGroves** [comment]
Sorry for late response, didn't see your comment. Responding anyway incase this issue is ever worked on. On my FireTV Stick, if playback is paused long enough for the screensaver to appear, Jellyfin goes back to the show menu. The selection is play rather than resume, meaning if your just quickly hit continue, you lose your progress.

**Comment by nielsvanvelzen** [comment]
Screensavers shouldn't be able to show up in the videoplayer, I'm wondering why that happens

**Comment by MrChip53** [comment]
> Screensavers shouldn't be able to show up in the videoplayer, I'm wondering why that happens

Screensavers showing up in video I think is a symptom of jellyfin not always reporting the correct play state. I forgot where I saw that though and unfortunately don't remember anymore about it to explain better.

**Comment by MrChip53** [comment]
> Sorry for late response, didn't see your comment. Responding anyway incase this issue is ever worked on. On my FireTV Stick, if playback is paused long enough for the screensaver to appear, Jellyfin goes back to the show menu. The selection is play rather than resume, meaning if your just quickly hit continue, you lose your progress.

Ok, this is the same thing exact thing I was experiencing.

**Comment by mueslimak3r** [comment]
possibly fixed by #1320

**Comment by nielsvanvelzen** [comment]
This should be fixed now, let us know if the issue still persists in the latest version (0.14).
