### ISSUE TITLE
can't use another port #

### ISSUE THREAD

**Issue by sbcrumb** [jellyfin/jellyfin-androidtv#52]
Running jellyfin through a proxy so https://jellyfin.domainname.com:443 then forwards to the default port.
but in the app I can't tell it to use 443 even with adding it at the end of the url. however I can in the android phone app give it a port number.

**Comment by thornbill** [comment]
Thanks for the report! I'm closing this because it sounds like a duplicate of #36.

**Comment by sbcrumb** [comment]
Thanks sorry didn't see that one.
