### ISSUE TITLE
Remove left gray menu bar

### ISSUE THREAD

**Issue by dannycool87** [jellyfin/jellyfin-androidtv#522]
Hi,
This is more a request that an issue...
The left gray menu bar is a old way to make a app on AndroidTV that make, in my opinion, relatively « ugly » presentation and had no really utility’s. Can you redesign it without this bar? The app itself is on a really good way, but this bar ... dismantled the rest of the layout. Thank you very much!

**Comment by nielsvanvelzen** [comment]
It's actually the recommended way to make apps by Google but I agree that is isn't useful.

**Comment by thornbill** [comment]
The last time I looked at removing this it broke the app. It seems there is some dependency between the search functionality and the sidebar in the leanback library.

**Comment by dannycool87** [comment]
Maybe, the Emby app had made this change 6 months ago, and the transition seem to be relatively easy, in the way that I had use the first beta when this change was made and I never noticed this kind of problems. I really think that this change made the screen so much more sharp, if you can look for that, it’s would be cool. Thank you!

**Comment by dannycool87** [comment]
Hi @nielsvanvelzen , Is there a chance to see this in the relook branch .12?

Also, I was wondering if you have a screenshot of the home page to give us an overview, which needs some love, mainly on the layout and size of the items displayed.  Also, I was wondering if it will be possible to deactivate the "cardview" to only see the poster and the title without "box"?  I know it's not the same outcome, I'm willing to open another ticket if you think it's a good idea and she hasn't been named.  Thank you very much for the work done, you are doing well!

**Comment by nielsvanvelzen** [comment]
I don't think so. The home screen should get a refactor at some point and this issue will certainly be a part of it.

**Comment by thornbill** [comment]
Removed in https://github.com/jellyfin/jellyfin-androidtv/pull/717 🎉

**Comment by dankell66** [comment]
Hello Support Team,
Why on gods green earth would you have removed the side bar feature in v0.12.0?
Very bad move indeed ...removing this feature also removes MANY further features which include Genre search to name a few.
Why would you do such a BAD move....when the majority welcomed the side bar.
Please could you make sure to reencorporate this feature back ASAP Please.
I am sure you can add a setting for the minority whom do not like this feature.
You have broken a perfectly Great app for a very small minority .

Best Regards,
Dankell
