### ISSUE TITLE
subtitles wont load after upgrade to 10.6

### ISSUE THREAD

**Issue by greymda** [jellyfin/jellyfin-androidtv#523]
prior upgrading it was hit or miss feature, meaning to load subtitles one had to multiple times select a sub and after n-th try it would load.

after upgrade to 10.6 even this way subtitles are not loading.

client: Amazon FireTV Stick 4K.
if anything would be needed, just ask.

**Comment by nielsvanvelzen** [comment]
Some information that is needed (that the issue template asks for):
- What kind of subtitles? (SRT, SSA, ASS etc)
- What kind of video container? (MKV, MP4, Or maybe external subtitle files?)

**Comment by brianclinkenbeard** [comment]
This occurs for me on MKV files with embedded text (i.e. SRT) subtitles.

**Comment by brianclinkenbeard** [comment]
This issue still occurs for me on the latest version.
