### ISSUE TITLE
Install problems androidtv

### ISSUE THREAD

**Issue by riddertommie** [jellyfin/jellyfin-androidtv#527]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Android TV or Fire TV version: [e.g. Android 9 or Fire OS 7]
 - Device manufacturer: [e.g. Amazon, Nvidia, Sony]
 - Device model: [e.g. Fire TV Stick (2nd Gen) or Shield TV]
 - Jellyfin server version: [e.g. 10.5.4]

**Additional context**

what the bug is. -->

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Android TV or Fire TV version: [e.g. Android 9 or Fire OS 7]
 - Device manufacturer: [e.g. Amazon, Nvidia, Sony]
 - Device model: [e.g. Fire TV Stick (2nd Gen) or Shield TV]
 - Jellyfin server version: [e.g. 10.5.4]

**Additional context**

**Comment by AndreasGB** [comment]
Hi there,

can you please fill in the template instead of leaving it blank? Feel free to re-open once you have done that :)

Cheers

**Comment by riddertommie** [comment]
Sorry, Gremlins i think. 

will do it again.
