### ISSUE TITLE
Install problems androidtv 

### ISSUE THREAD

**Issue by riddertommie** [jellyfin/jellyfin-androidtv#528]
**Describe the bug**

Tried to install on my Philips 934/12 (androidtv) and this goes on multiple things wrong.

First its impossible to press OK if you are filling in the the server info. Workaround for me is, press back/esc and then press ok. but first you have to fill in the info otherwise it will not work. (this can be of course the tv)

After that he asked for which user you wat to select, butt there are no users presented to select form.

so a cant end the configuration 

**To Reproduce**

1. download the app from the store
2. install
3. configure

**Expected behavior**
The ability to press ok after filling in the server info and after that the ability to choice a user from 'a' list.

**Logs**
don't know how to get a log from the app. help?

**Screenshots**

**System (please complete the following information):**
 - Android TV Android 9
 - Device manufacturer: Philips (now known by TPVision)
 - Device model: 934/12
 - Jellyfin server version: 10.6 (docker)

**Additional context**

**Comment by AndreasGB** [comment]
Hi there,

the sign in process is currently bad UI which we inherited and that is in the process of being rewritten.

A workaround to not being able to press okay is using the Android TV Remote app to enter the server address.

For your second problem: Users are hidden by default and you either need to mark them as visible in your server settings or need to enter their name manually (there should be an option to do that in the second row after you connected to a server)

The next problem you will probably encounter is that per default you need to authenticate with your password each time you open the app. You can change that in the settings and after that you should be good to go.

Cheers

**Comment by thornbill** [comment]
Related to #167.
