### ISSUE TITLE
Anroidtv home channels

### ISSUE THREAD

**Issue by Uzzer-dev** [jellyfin/jellyfin-androidtv#529]
**Anroidtv home channels**	

The latest versions of android tv have channels on the home screen. Channels allow you to see new content in apps without launching them. For example, the channel "nvidia games" at the bottom of the screenshot. I think it will be useful for users if this feature appears in your app

![Image of atvhome](https://i.playground.ru/p/0jN_NSdvnMThCi3KzQGYwg.png)

**Comment by thornbill** [comment]
I don’t recall if this has landed in a release yet, but we already have support for channels in the master branch! 🎉
