### ISSUE TITLE
Playlists library image truncated on Firestick 0.11.3 client

### ISSUE THREAD

**Issue by FazeThree71** [jellyfin/jellyfin-androidtv#530]
**Describe the bug**
On the Firestick client, the Playlists image is truncated 

**To Reproduce**
1. Log in 
2. Scroll to Playlists
3. Observe image 

**Expected behavior**
Playlists should show the image in the same width as the libraries (and should show any custom images uploaded to all users) 

**Screenshots**
![IMG_20200726_102633](https://user-images.githubusercontent.com/68828016/88490169-3e29f000-cf5f-11ea-8a91-55bb0ce08a87.jpg)

**System (please complete the following information):**
 - Fire TV version: 6.2.7.1 (NS6271/2495) (Fire TV 6231058.1) 
 - Device manufacturer: Amazon
 - Device model: Fire TV Stick 4k
 - Jellyfin server version: 10.6.0. Raspberry Pi 3B+ running Buster

**Comment by nielsvanvelzen** [comment]
I think this requires this line:

https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java#L162

To set the aspect ratio to 19:9. But it might break other parts of the application that expect the playlist button as 4:3.

**Comment by MrChip53** [comment]
> I think this requires this line:
> 
> https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/ui/presentation/CardPresenter.java#L162
> 
> To set the aspect ratio to 19:9. But it might break other parts of the application that expect the playlist button as 4:3.

What other parts of the app would expect it as 4:3? Can this be rolled in with the Live TV tile fix we did?

**Comment by nielsvanvelzen** [comment]
> What other parts of the app would expect it as 4:3?

No idea, probably some weird place you won't expect it. I don't have any playlists either so I'm unable to test it.

**Comment by FazeThree71** [comment]
@MrChip53 This is still present in 0.11.4. I assume 49fd2ce is in that version.

**Comment by nielsvanvelzen** [comment]
No that commit is not in 0.11.4 but we will add it to 0.11.5 (if we do another release)
