### ISSUE TITLE
Cloudflare proxy support

### ISSUE THREAD

**Issue by diet-peach** [jellyfin/jellyfin-androidtv#531]
As described in a previous issue of mine, #526, it seems that the Android TV client is not able to connect remotely to a Jellyfin server through Cloudflare's proxy service. Every other client that I've tested (web, Android, iOS) is able to connect just fine. I'm not entirely sure what the root of this discrepancy is, but using Cloudflare's proxy is a security measure that's important to me, and if it's possible to add support for it to the Android TV client, that'd be fantastic.

**Comment by MrChip53** [comment]
Cloudflare proxy works fine for me. What is your port config and are you using a reverse proxy?

**Comment by MrChip53** [comment]
@diet-peach have you seen my comment above? Is this still an issue for you?

**Comment by MrChip53** [comment]
@thornbill @nielsvanvelzen I'd also request this issue to be closed. Cloudflare tunneling works for me. I assume this is a server side config issue and not Android TV related. Also, no response.
