### ISSUE TITLE
Player 0.11.x on Amazon FireTV Stick randomly rewind

### ISSUE THREAD

**Issue by francescobaiocchi** [jellyfin/jellyfin-androidtv#532]
I have last version of Jellyfin server (10.6.0) and player on Amazon FireTV Stick (0.11.3 as far as I can see).
While viewing a video player rewinds of some minutes (sometime, rarely, restarts the video). It happens in a completely random way, I could not figure out any reason for this.
It happens with different videos, different format (avi, mkv), it happens randomly.
Below you find the detail about the last video where I experienced the issue.

Westworld.Dove.Tutto.E.Concesso.1x01.L.Originale.ITA.ENG.DLMux.XviD-Pir8
Contenitoreavi
PercorsoM:\My\Video\Serie TV\Westworld\S01\Westworld.Dove.Tutto.E.Concesso.1x01.L.Originale.ITA.ENG.DLMux.XviD-Pir8.avi
Dimensione767 MB
Video
TitleSD MPEG4
CodecMPEG4
Tag codecXVID
ProfiloAdvanced Simple Profile
Livello5
Risoluzione656x368
Formato16:9
InterlacciatoNo
Framerate23.976044
Bitrate1237 kbps
Formato Pixelyuv420p
Ref frame1
Audio
TitleMP3 stereo
CodecMP3
disposizionestereo
Canali2 ch
Bitrate123 kbps
Frequenza di campione48000 Hz
PredefinitoNo

**Comment by wilmardo** [comment]
This might be a duplicate of #400
