### ISSUE TITLE
Jellyfin loads the subtitle from wrong episode after going to the next one.

### ISSUE THREAD

**Issue by ixanx** [jellyfin/jellyfin-androidtv#535]
Android TV based on Android7.1
Steps to reproduce:

- > Open Jellyfin app
- > Select a TV Show
- > Select an episode, press play
- > Select the subtitle, everything is going fine for now. After the episode ended, let it automatically go to the next one.
- > The next episode loads the same subtitle as the previous episode, so I have to go back and select the new episode alone.

**Comment by thornbill** [comment]
Duplicate of #108.
