### ISSUE TITLE
Cannot change audio track on Android TV

### ISSUE THREAD

**Issue by hariseldon99** [jellyfin/jellyfin-androidtv#548]
**Server System :**
 - OS: Ubuntu 18.04. No docker
 - Jellyfin Version: 10.6.2
 - Hardware settings & device: VAAPI on Intel i3-2310M
 - Reverse proxy: None
 - Other hardware notes: None
 
**Client System :**
 - Device: Sony Bravia KD-43X7500F
 - OS:  Android
 - Client: Android
 - Client and Browser Version: 0.11.4

Basically exactly the same as this problem:
https://www.reddit.com/r/jellyfin/comments/ggzpsi/cannot_change_audio_track_on_android_tv/

Happens with any media that has multiple audio tracks. Trying to change the track causes Jellyfin client to crash and reload

jellyfin logs: http://paste.ubuntu.com/p/gGXRrfTHdV/
ffmpeg logs: http://paste.ubuntu.com/p/WrHGJFHxWN/

**Comment by william-roy** [comment]
I can also confirm this is a problem and acts the same as described in the reddit post—changing audio on a paused video does nothing, changing it on a playing video sometimes works and sometimes crashes. I've only tested it with multi-language .MKV files, and rewinding/fast-forwarding those same files also seems to work sporadically.

**Comment by Boggart** [comment]
This happens to me on a FireTV powered TV when using VLC as the backend, changing audio tracks is an instant crash while on ExoPlayer it won't change tracks unless playing.

**Comment by SonicPotions** [comment]
it seems all inputs are ignored while paused. I cant ff and rw when paused. it mostly works when playing, although I had every rewind or fast forward resetting the episode to 0:00 as well. even when not paused, audio track changes are sometimes ignored and the change has to be made multiple times until it is accepted. (fire TV 4K + unraid/docker server)

**Comment by carjimsar** [comment]
I solved it. It was enough enabling the "Audio Bitstream DTS" option in client configuration. It wa  said that compatible hardware is needed to make use of it, but I guess the Mi TV Stick is because it shows the DTS logo on boot.

**Comment by cbfrank** [comment]
I tried enable "Audio Bitstream DTS" but seems doesn't work for me. the only way for me is to change audio track while playing
