### ISSUE TITLE
transcode when webui and kodi with embycon does not

### ISSUE THREAD

**Issue by frankyifei** [jellyfin/jellyfin-androidtv#55]
at first I noticed the server was transcoding on a normal mp4 file. I checked the difference of the two files, the only difference is the original audio codec mp4a-40-2 and the new codec id A-AAC-2. They are both AAC LC format, so it is not necessary. Then I noticed it also transcodes codec A-AAC-2 and 10-2, I have no idea why because they are all AAC.
I tried webui and embycon and they do not trigger transcoding for all these files. It seems the reason for transcoding is mainly audio, is there any way that I get around it ?

**Comment by thornbill** [comment]
We just released a version of the app (beta 4) which includes an update to the base version of the app. These changes resolved a lot of the playback issues that I was seeing in my testing. Please test the latest release and let us know if your playback issues are also resolved. Thanks!

**Comment by frankyifei** [comment]
This beta4 fixed the AAC transcoding. Now the movies that trigger transcoding include audio format like Opus, DTS and Dolby Digital. Opus is support by android plantform natively, it should not trigger transcode. Because my movies are mostly H264 and H265, both are well supported, so I have not found them being transcoded. Will DTS and Dolby Digital be supported by the client?

**Comment by cvium** [comment]
Android does not support Dolby Digital and DTS out of the box iirc. You'll need an external player for that like VLC.

**Comment by thornbill** [comment]
What device are you using? The playback profiles used to determine what needs transcoding vary by device.

**Comment by frankyifei** [comment]
I'm on an TCL android TV. beta4 fixed the issue for me. the last version transcode some AAC audio for me which is annoying.
How can I set external player?
