### ISSUE TITLE
Connecting to an IPv6 address crashes the client.

### ISSUE THREAD

**Issue by BaronGreenback** [jellyfin/jellyfin-androidtv#553]
Testing https://github.com/jellyfin/jellyfin/pull/3994.

On attempting to access an item the client closes down. (Amazon FireTv)

E/ACRA    (28284): ACRA caught a RuntimeException for org.jellyfin.androidtv
E/ACRA    (28284): java.lang.RuntimeException: An error occured while executing doInBackground()
E/ACRA    (28284): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/ACRA    (28284): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/ACRA    (28284): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/ACRA    (28284): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/ACRA    (28284): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/ACRA    (28284): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/ACRA    (28284): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/ACRA    (28284): 	at java.lang.Thread.run(Thread.java:818)
E/ACRA    (28284): Caused by: java.lang.IllegalArgumentException: unexpected host: fd23:184f:2029::5d2:6fe0:84aa:15b6
E/ACRA    (28284): 	at com.squareup.okhttp.HttpUrl$Builder.host(HttpUrl.java:705)
E/ACRA    (28284): 	at com.squareup.okhttp.Address.<init>(Address.java:57)
E/ACRA    (28284): 	at com.squareup.okhttp.internal.http.HttpEngine.createAddress(HttpEngine.java:985)
E/ACRA    (28284): 	at com.squareup.okhttp.internal.http.HttpEngine.<init>(HttpEngine.java:182)
E/ACRA    (28284): 	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:377)
E/ACRA    (28284): 	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:324)
E/ACRA    (28284): 	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:392)
E/ACRA    (28284): 	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:527)
E/ACRA    (28284): 	at com.squareup.picasso.OkHttpDownloader.load(OkHttpDownloader.java:105)
E/ACRA    (28284): 	at com.squareup.picasso.NetworkBitmapHunter.decode(NetworkBitmapHunter.java:46)
E/ACRA    (28284): 	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:144)
E/ACRA    (28284): 	at com.squareup.picasso.RequestCreator.get(RequestCreator.java:280)
E/ACRA    (28284): 	at org.jellyfin.androidtv.details.FullDetailsActivity$BuildDorTask.doInBackground(FullDetailsActivity.java:433)
E/ACRA    (28284): 	at org.jellyfin.androidtv.details.FullDetailsActivity$BuildDorTask.doInBackground(FullDetailsActivity.java:381)
E/ACRA    (28284): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/ACRA    (28284): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/ACRA    (28284): 	... 4 more

**Comment by nielsvanvelzen** [comment]
It looks like our image library (Picasso in this case) can't connect to your ipv6 address while the apiclient apparently can. Can you try it with the latest version of the Android TV app? We fully removed Picasso and replaced it with Glide.

**Comment by BaronGreenback** [comment]
Will give it a go - is there a precompiled version - or do i have to learn how to make apk's?

**Comment by nielsvanvelzen** [comment]
You can download it from Azure, the latest right now is [here](https://dev.azure.com/jellyfin-project/jellyfin/_build/results?buildId=13083&view=artifacts&type=publishedArtifacts)

**Comment by BaronGreenback** [comment]
At last i've got the code on the firestick (adb issues).

Starting up - i notice that it doesn't autodetect the server.
When it comes to the server/username/password - no matter what i enter it always comes back with an invalid username/password. It then sits at the JF rolling bark. 

Will do some more digging and let you know.
