### ISSUE TITLE
Can't browse Movies by categories

### ISSUE THREAD

**Issue by ikus060** [jellyfin/jellyfin-androidtv#554]
**Describe the bug**
Since 0.11.4, Opening the movies section from the home scren jump directly to the movies list that display all the movies from A-Z without a change to see the suggestion or the categories.

**To Reproduce**
Open jellyfin
1. Display the home screen
2. Select the "Movies" card

**Expected behavior**
Display the movies view showing the latest movies.
Card to display categories, etc.

**System (please complete the following information):**
 - Android TV or Fire TV version:Fire OS
 - Device manufacturer: Amazon
 - Device model:  Fire TV Stick 
 - Jellyfin server version:  0.11.4

**Additional context**
This problem happen recently without notice. Might be related to recent upgrade.

**Comment by nielsvanvelzen** [comment]
On the top of the screen is a gear icon. After pressing it you can change the "Default View" from "Grid View" to "Smart Screen". This will enable the screen you expect.

**Comment by ikus060** [comment]
Will take a look. I'm curious about why the interface is so different compare to web browser one.

**Comment by nielsvanvelzen** [comment]
It's a separate code base maintained by different people. We're also still working on changing a lot of old code from the Emby fork.

**Comment by ikus060** [comment]
Thanks, Closing
