### ISSUE TITLE
Jellyfin local playback from Android TV (shield) always transcodes

### ISSUE THREAD

**Issue by smidley** [jellyfin/jellyfin-androidtv#555]
**Describe the bug**
I have a local Jellyfin server (Windows server), and an Nvidia shield running the latest Jellyfin app. Whenever I playback a video, it transcodes instead of direct plays. The reason for transcode on the server is “AudioCodecNotSupported”. 

**To Reproduce**
1. Select any file on Jellyfin for AndroidTV
2. Use server dashboard to monitor playback method.
3. See that the file is transcoding due to AudioCodecNotSupported.

**Expected behavior**
Files should use directplay.

**System (please complete the following information):**
 - Android TV or Fire TV version: AndroidTV 0.1.4
 - Device manufacturer: Nvidia
 - Device model: Shield TV (2nd Gen)
 - Jellyfin server version: 10.6.4

**Additional context**
I have tried switching the player settings from "auto" to libVLC and ExoPlayer, and I still get the same result - Transcoding because AudioCodecNotSupported.

If I install VLC for Android, and use that as an External Player, every file direct plays fine.

**Comment by EraYaN** [comment]
Similar problem here, same device same symptoms. Not sure how and why.

**Comment by jbl0ggs** [comment]
I can't get any video to play with Jellyfin on Android TV (v9 on Sony TV). Tried the individual player and also External Player, having MX Player installed but that didn't work either. With ExoPlayer I get "Player error encountered". Any other selection it just goes into endless circling loading. Are there any external players that are known to work?

**Comment by smidley** [comment]
> I can't get any video to play with Jellyfin on Android TV (v9 on Sony TV). Tried the individual player and also External Player, having MX Player installed but that didn't work either. With ExoPlayer I get "Player error encountered". Any other selection it just goes into endless circling loading. Are there any external players that are known to work?

The only way I got this to work was with VLC installed. And that as the external player.

**Comment by smidley** [comment]
Update - I got direct playback to work if I uncheck the playback option for the user that says "Allow video playback that requires transcoding", but leave the option checked that says "Allow audio playback that requires transcoding".  This works even without using an external player like VLC.

**Comment by ya-v-uz** [comment]
This issue seems to be persisting in Jellyfin server version: 10.7.7 and android tv app version: 0.13.2
The solution suggested by the original author below solved my issue also, but I agree that this is not an elegant solution as I now have to change my settings every time I need transcoding, or use switch between two accounts constantly. 

> Update - I got direct playback to work if I uncheck the playback option for the user that says "Allow video playback that requires transcoding", but leave the option checked that says "Allow audio playback that requires transcoding". This works even without using an external player like VLC. Regardless of this "workaround", Jellyfin should be able to figure out CORRECTLY if it can play back a file without having to transcode it. I shouldn't have to force it to NOT transcode every file. Since I have to set it this way, it's not using any algorithm in order to determine things like file type/size or bandwidth required.

**Comment by ajoshuasmith** [comment]
I also just encountered this issue on the latest version.

**Comment by dangreen** [comment]
Still valid issue
