### ISSUE TITLE
external trailers for master branch?

### ISSUE THREAD

**Issue by huudafakk** [jellyfin/jellyfin-androidtv#580]
Hi there,

is there a chance to merge the #397 PR into the master branch? It's only a question, it works nice on the item-details-redesign branch, but there are other things missing..

Thanks for the fantastic job anyway, you guys are great.

BR

**Comment by nielsvanvelzen** [comment]
No, it will be in the master branch at some point after we finish the redesign. We won't backport it to a screen that will be removed soon.
