### ISSUE TITLE
Main Menu Movie Cards IMDB Ratings Instead of Rotten

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#584]
Hi guys just a little suggestion don't no who agrees but on the main title cards for movies you have a rotten/fresh tomato image noticed it doesn't pull the rotten rating for most movies i have added but going into a movie i have noticed every single movie as a IMDB rating could you maybe get rid of the rotten rating on main movie menu cards and maybe add the IMDB rating instead with a little IMDB logo at side of rating no worries if not and thanks for all the hard work u have put into the app already its coming along nicely

**Comment by nextlooper42** [comment]
Not to say that Rotter is accurate for US only most times, and is missing anything not english. Completely irrelevant in EU, or global scale. Maybe option to pick provider would be much better.

Or at least give us option to hide rotten rating.

**Comment by thornbill** [comment]
Setting added in https://github.com/jellyfin/jellyfin-androidtv/pull/630
