### ISSUE TITLE
Firestick 4k Playback issues

### ISSUE THREAD

**Issue by barfunkle** [jellyfin/jellyfin-androidtv#590]
Jellyfin Server 10.6.4 on Mac
Firestick 4k play back device.

Notice couple of problems that I have not noticed while watching on computer or standard FireStick.

Problem 1:
Watching live TV works fine, but when a commercial happens sometime the audio and video are way out of sync.  Minutes.  The screen does stop but then restores.  Have to exit back into TV guide to get things working correctly again.

Problem 2:
Watching live TV works fine, but when a commercial happens, after the commercial is played the audio and video pick ups way back to scenes that we already watched 10-15 minutes ago.   Very possible it could be picking up 2 commercials back.  Have to exit back into the TV guide to get things working again.

I only have one Firestick 4k.  This might also only happen when watching a movie verses a series.

**Comment by barfunkle** [comment]
Looking at the logs(JellyFin GUI).  I have a bunch of ffmpeg-transcode0[hex number].txt  None have today's date.  Date and time are set correctly on the machine.

None have today's date; I recreated the issue so I had some time stamps.

The only log with a current time stamp is log_date.log

**Comment by barfunkle** [comment]
Update.  
Quick test today.  It only seems to happen with standard quality on a 4k Firestick.  Tested today with HD channel with 4k firestick and went through at least 2 commercial breaks without interruption.  Changed non HD channel of the same channel and it failed at first commercial break.

**Comment by Artiume** [comment]
What sort of live tv set-up do you have? I'm guessing an hdhomerun since iptv shouldnt provide a difference between show and commercial

**Comment by barfunkle** [comment]
Correct HDhomeRunPrime

    On Sunday, October 18, 2020, 6:12:17 PM EDT, artiume <notifications@github.com> wrote:  
 
 


What sort of live tv set-up do you have? I'm guessing an hdhomerun since iptv shouldnt provide a difference between show and commercial

**Comment by jcdick1** [comment]
I was reading through some threads regarding IPTV (Pluto streams specifically) for use in Kodi, and there's apparently an issue with #EXT-X-DISCONTINUITY tags in the stream and a lack of support for them in ffmpeg.  Could this be the problem with the LiveTV playback?  Unless the JF ffmpeg is already patched for it, perhaps.

**Comment by Artiume** [comment]
could you link where you found that

**Comment by jcdick1** [comment]
https://forums.whirlpool.net.au/archive/9nk7ly73

If you scroll through the posts, it's down in the late May 2020 timeframe.

**Comment by barfunkle** [comment]
I am not sure what you are asking.
I was the one that posted the issue.  



    On Wednesday, December 9, 2020, 4:36:05 PM EST, artiume <notifications@github.com> wrote:  
 
 


could you link where you found that

**Comment by Artiume** [comment]
I was asking @jcdick1

**Comment by jcdick1** [comment]
I think I'll toss the DISCONTINUITY tag issue over into the Jellyfin server issues, as well, to see if we can't get it on a wider radar.

**Comment by barfunkle** [comment]
Stood up another JellyFin server on W10 Workstation, and JF version 10.7.0 to see if I can reproduce the issue.  Still using Firesticks as my primary end point.  During stream of live TV(HD Homerun) things work good then all of a sudden, usually where there is a scene break, commercial, new show, etc, I find myself watching the TV show I watched in the past.  Can be a show that was on previously, 20 minutes ago.  I partially caught it.  The server shows the active device bouncing from -1:57:00 to 0:03/0:00 and keeps doing it although the TV screen does progress forward.  Starting the stream on another device is real time.  Stopping the playback and restarting clears the issue.  Format: MKV H264 AC3

Also noticed if I allow the old programming to play through, go through a commercial JF plays like I am playing back from a DVR recording.  Minute play looks normal.  Of course I am no longer live.

Hopefully this make sense.

**Comment by joshstubble** [comment]
I think I found a little hack to solve the live tv loop problem for fire tv. 

In the Jellyfin settings of Fire TV make sure you have direct stream live tv on and `'try to connect to VLC if possible'` clicked as well under that. 

You need to obviously download VLC. 

Next, you need to go to jellyfin dashboard>users. Open each user that has an android tv and click `force transcode remote files`. 

This should force your fire stick to use VLC player and have jellyfin transcribe the audio correctly. 

Since doing this I have not seen live tv skip. If anything the picture looks better (VLC is goated for video quality). 

I'll update if I experience any looping.

**Comment by barfunkle** [comment]
Thank you.  I will give it a try and post back.

    On Thursday, March 4, 2021, 11:30:11 PM EST, joshstubble ***@***.***> wrote:  
 
 


I think I found a little hack to solve the live tv loop problem for fire tv.

In the Jellyfin settings of Fire TV make sure you have direct stream live tv on and 'try to connect to VLC if possible' clicked as well under that.

You need to obviously download VLC.

Next, you need to go to jellyfin dashboard>users. Open each user that has an android tv and click force transcode remote files.

This should force your fire stick to use VLC player and have jellyfin transcribe the audio correctly.

Since doing this I have not seen live tv skip. If anything the picture looks better (VLC is goated for video quality).

I'll update if I experience any looping.

**Comment by joshstubble** [comment]
Sounds good let me know. Me and all my family members that use fire stick have had zero playback issues since doing this. >  Thank you.  I will give it a try and post back.
>

**Comment by barfunkle** [comment]
Had a little time to play with it yesterday.
Kept getting streaming errors. and I just would keep looping trying to start live tv.
VLC was installed, rebooted both the JF server and the Firestick.  

Will try again tonight.


    On Monday, March 15, 2021, 11:20:35 PM EDT, joshstubble ***@***.***> wrote:  
 
 


Sounds good let me know. Me and all my family members that use fire stick have had zero playback issues since doing this. > Thank you.  I will give it a try and post back.

On Thursday, March 4, 2021, 11:30:11 PM EST, joshstubble ***@***.***> wrote:  

I think I found a little hack to solve the live tv loop problem for fire tv.

In the Jellyfin settings of Fire TV make sure you have direct stream live tv on and 'try to connect to VLC if possible' clicked as well under that.

You need to obviously download VLC.

Next, you need to go to jellyfin dashboard>users. Open each user that has an android tv and click force transcode remote files.

This should force your fire stick to use VLC player and have jellyfin transcribe the audio correctly.

Since doing this I have not seen live tv skip. If anything the picture looks better (VLC is goated for video quality).

I'll update if I experience any looping.

**Comment by joshstubble** [comment]
>  Had a little time to play with it yesterday.
> Kept getting streaming errors. and I just would keep looping trying to start live tv.
> VLC was installed, rebooted both the JF server and the Firestick.  
> 
> Will try again tonight.
> 
> 
>     On Monday, March 15, 2021, 11:20:35 PM EDT, joshstubble ***@***.***> wrote:  
>  
>  
> 
> 
> Sounds good let me know. Me and all my family members that use fire stick have had zero playback issues since doing this. > Thank you.  I will give it a try and post back.
> 
> On Thursday, March 4, 2021, 11:30:11 PM EST, joshstubble ***@***.***> wrote:  
> 
> I think I found a little hack to solve the live tv loop problem for fire tv.
> 
> In the Jellyfin settings of Fire TV make sure you have direct stream live tv on and 'try to connect to VLC if possible' clicked as well under that.
> 
> You need to obviously download VLC.
> 
> Next, you need to go to jellyfin dashboard>users. Open each user that has an android tv and click force transcode remote files.
> 
> This should force your fire stick to use VLC player and have jellyfin transcribe the audio correctly.
> 
> Since doing this I have not seen live tv skip. If anything the picture looks better (VLC is goated for video quality).
> 
> I'll update if I experience any looping.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>   

Don't forget you need to go to jellyfin server dashboard > user > {user using firestick > and click force transcode remote stream

**Comment by barfunkle** [comment]
Farted around with it.  My inability to stream was on multiple devices to include 2 Firesticks, and Web.  Reload did not fix the issue.  Ended up finding somewhere someone else had a similar problem and updating to 10.7.0RC4 fixed it.  Never had any issues with the version I was running, but did install RC4 and all problems with not streaming video is gone.  Will revert to your solution and let you know what happens.


    On Wednesday, March 17, 2021, 12:34:59 AM EDT, joshstubble ***@***.***> wrote:  
 
 



Had a little time to play with it yesterday.
Kept getting streaming errors. and I just would keep looping trying to start live tv.
VLC was installed, rebooted both the JF server and the Firestick. 

Will try again tonight.
On Monday, March 15, 2021, 11:20:35 PM EDT, joshstubble ***@***.***> wrote:  

Sounds good let me know. Me and all my family members that use fire stick have had zero playback issues since doing this. > Thank you.  I will give it a try and post back.

On Thursday, March 4, 2021, 11:30:11 PM EST, joshstubble @.***> wrote:

I think I found a little hack to solve the live tv loop problem for fire tv.

In the Jellyfin settings of Fire TV make sure you have direct stream live tv on and 'try to connect to VLC if possible' clicked as well under that.

You need to obviously download VLC.

Next, you need to go to jellyfin dashboard>users. Open each user that has an android tv and click force transcode remote files.

This should force your fire stick to use VLC player and have jellyfin transcribe the audio correctly.

Since doing this I have not seen live tv skip. If anything the picture looks better (VLC is goated for video quality).

I'll update if I experience any looping.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


Don't forget you need to go to jellyfin server dashboard > user > {user using firestick > and click force transcode remote stream
