### ISSUE TITLE
no playback of any video on nvidia shield tv

### ISSUE THREAD

**Issue by NextBlaubeere** [jellyfin/jellyfin-androidtv#595]
- [x] Playback in webinterface DOES WORK
- [x] Playback with external app (via jellyfin) DOES WORK
- [x] changing audio-downmix option in the settings does NOT solve the issue

**Description**
Hello everyone!

Unfortunately, I am not able to playback any of my videos. 
When I use ExoPlayer i get a "Player error encountered" toast three times and i get back to the screen where I can press the play-button. If libVLC is selected i go to an endless loading screen. Both logs are attached.

**Logs**
[logcat_Automatic.(ExoPlayer).txt](https://github.com/jellyfin/jellyfin-androidtv/files/5359816/logcat_Automatic.ExoPlayer.txt)
[logcat_libVLC.txt](https://github.com/jellyfin/jellyfin-androidtv/files/5359817/logcat_libVLC.txt)

**System (please complete the following information):**
 - _Android TV or Fire TV version:_ Android 9 (Latest Security Update: 5th July 2020)
 - _Device manufacturer:_ Nvidia
 - _Device model:_ Shield TV Pro 2019
 - _Jellyfin server version:_ 10.6.4

**Additional context**
I did not attach any mediainfo because I have not found a file that worked.

**Comment by nielsvanvelzen** [comment]
Is transcoding enabled on your server?

**Comment by NextBlaubeere** [comment]
> Is transcoding enabled on your server?

Yes, i used Intel Quick Sync on Linux. I now turned it off and it does work! Thank you.

Would you be so kind and could go a little bit deeper into the issue with hardware accelerated transcoding?

**Comment by nielsvanvelzen** [comment]
The Android TV is still using some old methods to play videos and it has a lot of bugs. We're working towards a complete rewrite of the code for playing music and videos but until that's done a lot of issues like this can happen.

**Comment by NextBlaubeere** [comment]
allright thanks for clarification. 👍

**Comment by jbl0ggs** [comment]
I have MX Player and had set the Jellyfin to use External Player but still did not work. Is a list of external players that work?

**Comment by nielsvanvelzen** [comment]
Some users have found android-mpv to work quite well. Only downside is it's not available in the Play Store on Android TV so you need to sideload it.

**Comment by NextBlaubeere** [comment]
I used VLC.

Am 16. Oktober 2020 02:35:44 schrieb jbl0ggs <notifications@github.com>:
