### ISSUE TITLE
Play from chapter sometimes doesn't work

### ISSUE THREAD

**Issue by crobibero** [jellyfin/jellyfin-androidtv#596]
**Describe the bug**
Attempt to play media starting from chapter sometimes starts from beginning.

**To Reproduce**

1. Play media from chapter
2. See error 

**Expected behavior**

Playback should start from selected time

**Logs**

[jellyfin_10.6.4_androidtv_playback.log](https://github.com/jellyfin/jellyfin-androidtv/files/5374497/jellyfin_10.6.4_androidtv_playback.log)

**System (please complete the following information):**
 - Android TV or Fire TV version: 8.2.0(32.6.345.1)
 - Device manufacturer: Nvidia
 - Device model: Shield
 - Jellyfin server version: 10.6.4

Possibly related:
```
10-13 16:16:04.754 24651 22709 I Jellyfin-AndroidTV: Received web socket message: RefreshProgress
10-13 16:16:04.841 24651 22704 E Volley  : [20372] HttpHeaderParser.parseDateAsEpoch: Unable to parse dateStr: 0, falling back to 0
10-13 16:16:04.841 24651 22704 E Volley  : java.text.ParseException: Unparseable date: "0"
10-13 16:16:04.841 24651 22704 E Volley  : 	at java.text.DateFormat.parse(DateFormat.java:362)
10-13 16:16:04.841 24651 22704 E Volley  : 	at com.android.volley.toolbox.HttpHeaderParser.parseDateAsEpoch(HttpHeaderParser.java:135)
10-13 16:16:04.841 24651 22704 E Volley  : 	at com.android.volley.toolbox.HttpHeaderParser.parseCacheHeaders(HttpHeaderParser.java:97)
10-13 16:16:04.841 24651 22704 E Volley  : 	at com.android.volley.toolbox.StringRequest.parseNetworkResponse(StringRequest.java:98)
10-13 16:16:04.841 24651 22704 E Volley  : 	at org.jellyfin.apiclient.interaction.VolleyStringRequest.parseNetworkResponse(VolleyStringRequest.java:88)
10-13 16:16:04.841 24651 22704 E Volley  : 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:143)
10-13 16:16:04.841 24651 22704 E Volley  : 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
10-13 16:16:04.841 24651 22704 E Volley  : 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
```

**Comment by crobibero** [comment]
Just had my episode restart midway without pausing, looks to be the same issue

[jellyfin_10.6.4_androidtv_playback_restart.log](https://github.com/jellyfin/jellyfin-androidtv/files/5375528/jellyfin_10.6.4_androidtv_playback_restart.log)

**Comment by nielsvanvelzen** [comment]
The issue in your main post is normal. It happens all the time due too Volley, that will be fixed with the new apiclient.

**Comment by crobibero** [comment]
Was just an assumption, hopefully the full logcat has the real playback issue logged?

**Comment by nielsvanvelzen** [comment]
I can't find any useful logging statements suggesting an issue. There's no exceptions either. It might be some try-catch that doesn't log or something similar.
