### ISSUE TITLE
AndroidTV doesn't respect all User Home Settings

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-androidtv#600]
I noticed that the continue watching section differs between web and atv. The youtube video (the green one) shouldn't be on the continue watching section. ATV does properly ignore the youtube section on the homepage so it appears to be limited to the Continue Watching section.

![Screenshot_20201018-175111_Jellyfin](https://user-images.githubusercontent.com/20715731/96386713-f46e3180-116a-11eb-8596-82f74707ce6d.jpg)

![Screenshot_20201018-175146_Jellyfin](https://user-images.githubusercontent.com/20715731/96386715-fafca900-116a-11eb-849c-7d5eb8db3f7f.jpg)

![Screenshot_20201018-175225_Jellyfin](https://user-images.githubusercontent.com/20715731/96386720-ffc15d00-116a-11eb-80cc-488ff6ca9f31.jpg)

**Comment by sourpatched** [comment]
A lot has change, give 0.14.0 a go :)
