### ISSUE TITLE
Audiobooks BaseItem Support Failure

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-androidtv#601]
I don't recall audiobooks ever being supported so I'm not sure if it's a regression or just never implemented.

![Screenshot_20201017-060916_Jellyfin](https://user-images.githubusercontent.com/20715731/96418942-738e5480-11c1-11eb-943f-6f3361d6313d.jpg)

**Comment by nielsvanvelzen** [comment]
This issue is caused by the (old) apiclient not being aware of AudioBook (the enum constant is mising, just like the toast says). It should work when we upgrade to the new apiclient.

**Comment by vilebloomfps** [comment]
I have the same issue on my FireTV Stick. Any updates?

**Comment by nielsvanvelzen** [comment]
No
