### ISSUE TITLE
[Feature Request] Add ability to turn off Clock

### ISSUE THREAD

**Issue by Artiume** [jellyfin/jellyfin-androidtv#605]
**Describe the feature you'd like**	
	
Make a toggle-able option to disable the clock on the home screen.

**Comment by htpcBeginner** [comment]
@Artiume thanks for opening this request. Bit of additional information, Plex has this. Emby does not. Really helpful for people who do not want to see time at night due to sleep issues. 

I am going to open a similar request fo the Roku client.

**Comment by nielsvanvelzen** [comment]
Added in #631
