### ISSUE TITLE
Reinsert user every restart

### ISSUE THREAD

**Issue by PietroMB** [jellyfin/jellyfin-androidtv#607]
**Describe the bug**
Every time I open Jellyfin on my Android TV (xiaomi stick), it ask me to reinsert my user and password manually.

**System (please complete the following information):**
 - Android TV 
 - Device manufacturer: Xiaomi
 - Device model: Tv Stick 1080p
 - Jellyfin server version: last

**Comment by gabriellluz** [comment]
The same was happening to me. Then I found a setting that allows me to auto login.
Try going to settings and find the option. It works for me.

**Comment by PietroMB** [comment]
It's worked, thx!
