### ISSUE TITLE
Google TV dont recorgnized login credentials

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin-androidtv#610]
**Describe the bug**
I Set up yesterday my New Chrome ast with Google TV and loged in Into my jellyfin Server with my long User password. When i startet today the app i had to login New Again... My login credentials dont Get saved... 

**To Reproduce**
1. Manual login in to Your server
2. Turn of the TV for a few hours
3. Start it Again and try to go Into the app

**Expected behavior**
I thought that my User got saved and i dont have to login Again like at the Browser... 

**System (please complete the following information):**
 - Android TV, android 10
 - Device manufacturer: Google
 - Device model: Chrome ast with Google tv
 - Jellyfin server version: [e.g. 10.5.4]

**Comment by nielsvanvelzen** [comment]
You need to open the app settings and enable the remember function.
