### ISSUE TITLE
Media is constantly played using the wrong sound track

### ISSUE THREAD

**Issue by bmillemathias** [jellyfin/jellyfin-androidtv#619]
**Describe the bug**
I wanted to view a movie which has 2 sound tracks (french and english) in french and whatever track I select in the android tv UI the movie plays in english.
When I play the same movie from my browser the movie is played in french.

**To Reproduce**

Not sure I have a 100% reproducble procedure.

**Expected behavior**
Be able to play the sound track I want.

**Logs**
I did not spot any particular error related to this problem on the server 

**Screenshots**

some media information (sorry In french)
![image](https://user-images.githubusercontent.com/8579/98723004-120d7000-2392-11eb-98d3-22cadd50f96e.png)

Audio info
```
    Stream #0:1(fre): Audio: dts (DTS), 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
    Metadata:
      title           : VFF DTS @754kbps
      BPS             : 768000
      BPS-eng         : 768000
      DURATION        : 02:05:55.584000000
      DURATION-eng    : 02:05:55.584000000
      NUMBER_OF_FRAMES: 708336
      NUMBER_OF_FRAMES-eng: 708336
      NUMBER_OF_BYTES : 725336064
      NUMBER_OF_BYTES-eng: 725336064
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-04-28 17:40:44
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-04-28 17:40:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
    Stream #0:2(eng): Audio: aac (LC), 48000 Hz, stereo, fltp
    Metadata:
      title           : VOA AAC 2.0 @128kb
      BPS             : 127913
      BPS-eng         : 127913
      DURATION        : 02:05:55.605000000
      DURATION-eng    : 02:05:55.605000000
      NUMBER_OF_FRAMES: 354169
      NUMBER_OF_FRAMES-eng: 354169
      NUMBER_OF_BYTES : 120808057
      NUMBER_OF_BYTES-eng: 120808057
      _STATISTICS_WRITING_APP: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_APP-eng: mkvmerge v7.8.0 ('River Man') 64bit built on Mar 27 2015 16:31:37
      _STATISTICS_WRITING_DATE_UTC: 2015-04-28 17:40:44
      _STATISTICS_WRITING_DATE_UTC-eng: 2015-04-28 17:40:44
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
```

**System (please complete the following information):**
 - Android TV or Fire TV version: Android but don't know the type, it's installed on my set top box provided by my ISP
 - Device manufacturer: Free (free.fr French ISP)
 - Device model: freebox Pop
 - Jellyfin server version: 10.6.4
 - Jellyfin server version: 0.11.4

**Additional context**

If you need some logs that may contain info please ask.

**Comment by Stampede10343** [comment]
I have seen this same issue, or very similar. I believe its happened mostly on MKV files, where you go to change the track and it will not be able to change to the English track from whatever language its on, same video in Plex plays correctly right away. But picking either of the visible tracks in Jellyfin causes the same incorrect track to play.

**Comment by SonicPotions** [comment]
I have this issue sometimes. I select the other audio track and it just won't switch. then after multiple tries it suddenly works. other times it works directly (same tv show) also it does not remember the setting. if I pause the movie and the screensaver kicks in, the movie resumes with the original audio track again. but once it worked once, it seems to work consistently afterwards to switch the track. (fire TV 4k + docker server)

**Comment by avicarpio** [comment]
I also have this problem. It's really difficult to change the voice language in every anime chapter.

**Comment by BBreeziN** [comment]
I've seen this also on my NVIDIA shield. The file I was trying to play had a default regular sound track and an extra director's commentary track. When I clicked play in Jellyfin, it started playing the directors commentary, and to get it to play the main audio track, I had to select the director's commentary track.

I tried to repeat it again on the same file, and now the issue is not occurring.

**Comment by linetrimmer** [comment]
This is still an issue when using ExoPlayer. libVLC doesn't have the same problem for me, but other issues with libVLC (specifically that playback consistently freezes after 4 minutes) prevent that from being a viable option for me :/

In my experience, this happens when the default audio track is DTS-HD with a secondary AC3 audio track. With this combination, ExoPlayer always chooses to play the second track, but unfortunately in these cases the second track is director/cast commentary.

**Comment by alexdelprete** [comment]
I'm using jellyfin on Shield TV Pro and I'm not able to choose the audio track while playing. Is this a bug being addressed?

I was evaluating moving from Plex to Jellyfin, I prefer Jellyfin for many aspects, but I noticed a lot of issues on the client side, with NVIDIA Shields specifically (I have one in every room).

Hope these basic issues will be solved...can't move from Plex until I can't even reproduce an mkv file.

**Comment by DexLuther** [comment]
I'm also having this issue. Pretty much as described.

**Comment by MariioCL** [comment]
Same problem here :(

**Comment by bmillemathias** [comment]
as orginal reporter of the bug, the problem vanished since I started using version 0.12.
I don't know if I should close the bug or not.
they are "me too" comments but there is no enough details to say if this is the same bug or not

**Comment by Stampede10343** [comment]
Could #1732 have fixed this issue? I can't recall seeing it in a while, but that issue appears to potentially fix this issue?

**Comment by GamerBene19** [comment]
I do seem to experience the same bug. When a movie is directly played to Jellyfin ("jellyfin-androidtv 0.13.6 release" (installed today)) my FireTV-Stick (3rd Gen; model no. "AFTSSS") the audio track selection does not work as intended.
I do have a movie containing three audio tracks as follows (as presented by Jellyfin):
1. 5.1 English 
2. 5.1 German
3. Stereo English (audio commentary)

When the file is directly played the resulting audio tracks are as follows:
1. 5.1 English (option 1 from above)
2. 5.1 English (same as previous option)
3. 5.1 German (option 2. from above)
> Note the absence of the third option from above (the audio commentary)

The issue does not seem to occur when the movie is being transcoded (in my case when I do select subtitles as they have to be burned in).

I can provide more information if needed.

**Comment by dombalaz** [comment]
Issue still observed on LG TV. Movie has three audio tracks: first is TrueHD Atmos 7.1, second is AC3 5.1 and third AC3 2.0. When playing the movie and selecting first track the second is actually played, when selecting second the third is played and when selecting the last no audio is coming out.
After trying some other movies it seems like this is happening only on the ones that have first audio track TrueHD Atmos. Anyone noticed something similar? Is there a fix for this? Is there something to debug further?
