### ISSUE TITLE
HEVC Support

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin-androidtv#62]
I just started using Jellyfin looking for Plex alternatives and so far is working great the only caveat at the moment is that is not playing HEVC without transcoding (I have a Nvidia Shield).
Is this a known limitation or maybe something wrong with my video files or setup?

**Comment by thornbill** [comment]
We just released a version of the app (beta 4) which includes an update to the base version of the app. These changes resolved a lot of the playback issues that I was seeing in my testing. It looks like we _should_ be supporting HEVC on the Shield, so please test the latest version and let us know how it goes.

**Comment by frankyifei** [comment]
I tried HEVC and is working for me using beta 4. I found my problem is audio. The last version will transcode audio like AAC for no reason, beta 4 fixed this. But it still transcodes DTS and  dolby digital audio now.

**Comment by cesalo** [comment]
Perfect @thornbill .. no transcoding (hevc 10 bits + 5.1 AAC) I also noticed some other improvements to the UI of the app, it looks great.
Thanks a lot for the quick turnaround.

**Comment by thornbill** [comment]
Great! A community member found a more recent version of the source we're based on updating that pulled in a bunch of fixes it seems. :smile: 

Fixed by #58

**Comment by gabriellluz** [comment]
How is the status of playing HEVC files on 0.11.4 version?
To me, I can't play HEVC properly. I have a TX9 with 4Gb RAM, ARM Cortex A53 with 4 cores @1,49Ghz each.
 What am I doing wrong?

**Comment by gbakeman** [comment]
I'm not sure if the TX9 supports HEVC? I'm looking at its product page and it doesn't explicitly say HEVC or H.265 if the supported formats. I used to be under the impression that the SHIELD 2017 didn't have H.265 support, but I was able to direct stream it with the 11.5 client. I wonder if I can update the Wiki?
