### ISSUE TITLE
Info row is missing resolution and audio codec in browsing fragment

### ISSUE THREAD

**Issue by ne0phyte** [jellyfin/jellyfin-androidtv#633]
**Describe the bug**
When browsing items, the resolution and audio codec (e.g. "4K" "DTS") are not fetched when selecting an item.

Once you go to the item detail the resolution and codec show up.
Going back then shows the info in browse as well (I suppose it gets cached).

**To Reproduce**
1. Open any library
2. Change selection between items (that you haven't opened the details of yet)
3. The info row underneath the title updates but does not show resolution & audio codec
4. Open an items details
5. Item detail shows resolution & audio codec in the info row
6. Go back to browse
7. The info row for that item updates and now shows resolution & audio codec

**Expected behavior**
When browsing, the resolution and audio codec for the selected item should be loaded and displayed in the info row.

**Screenshots**
No resolution & audio codec:
![jelly1](https://user-images.githubusercontent.com/1471525/99205842-04088680-27ba-11eb-8fcc-7a443e51a916.jpg)
After opening the item details once and going back:
![jelly3](https://user-images.githubusercontent.com/1471525/99205873-184c8380-27ba-11eb-8b11-e9df22f1c3bf.jpg)

**System (please complete the following information):**
 - Android TV 10 (Android SDK Emulator) with latest master
 - Fire TV Stick 4K with Amazon Store 0.11.4
 - Jellyfin server version: 10.6.4

**Comment by thornbill** [comment]
Fixed by #634
