### ISSUE TITLE
can't hover properly over menu selection

### ISSUE THREAD

**Issue by robertwynter** [jellyfin/jellyfin-androidtv#638]
**Describe the bug**

when installed on android tv boxes Egreat A10 or HiMedia Q10 pro and trying to hover over any selection. I'm unable to determine where I am. There's no highlighted section or popup or highlighted border. The most I can do is change the display option to TV which helps however, the options are huge and I'm unable to scroll to select
**To Reproduce**

1. Go to '.mai  menu'
2. Click on try to hover/click on anything in the menu but there's no way to know where you are in the menu
3. Scroll down to '.when display option is set to TV..' You can see hover options and popup but can scroll
4. there are no error messages

**Expected behavior**

I expect to be able to see what I'm selecting either by a highlighted section or a popup on hover
**Logs**

**Screenshots**
No screenshots because it wouldn't show anything in the menu.

**System (please complete the following information):**
 - HidMedia Q10 - Android is version 5.1 'Lollipop'
  - egreat h10 android version 7
 - Jellyfin server version:10.6.4

**Additional context**

**Comment by nielsvanvelzen** [comment]
Do you mean hovering with a mouse? Because we do not support that.

**Comment by robertwynter** [comment]
sorry, nope. Hover is the best way I could explain it. when I arrow up/down I don't see where I'm at or going. there's no indications as to where I am on the screen. Like when you hover over a section it pops out and/or highlights. nothing is happeing

**Comment by nielsvanvelzen** [comment]
Hmm weird, and when you talk about the "main menu" do you mean the home screen with all rows displaying latest series/movies etc?

**Comment by robertwynter** [comment]
Yes, that’s correct. I even did a reset to factory settings on the Himedia box to whip out and start from scratch and it's still the same thing. The only way it works is if I change the display to TV but then the menu's massive and I can't arrow down to see the other sections.

**Comment by nielsvanvelzen** [comment]
Can you provide a screenshot/video so I can better understand the problem?

**Comment by robertwynter** [comment]
ok, very odd. Last night when I factory reset the himedia it still was not showing the cursor. Now it is showing as you can see in the screenshots. However, It's defaulted and Locked on TV in the display. I can select the dropdown options for anything in the display option. FOR example, I click TV Mode or themes and no dropdown comes up. So I can't switch it to auto. Which isn't so bag at least I can maneuver through the menu now. I also went to my great since I did the same thing to it and yup I can now maneuver through the menu. However, on both boxes when I try to play a show, JF freezes. It just shows the backdrop image of whatever movie/show you select and stays there. I've let it stay for at least 15 minutes now just to see if it starts to play the movie but nothing. Checked my Shield and all good there playing the movies
![display option](https://user-images.githubusercontent.com/6217191/99573712-6c1ac080-29a4-11eb-9e8f-8f549444caf2.jpg)
![menu](https://user-images.githubusercontent.com/6217191/99573715-6d4bed80-29a4-11eb-8db9-c96b9fc8a367.jpg)
![display option 2](https://user-images.githubusercontent.com/6217191/99573718-6de48400-29a4-11eb-8288-bd0fa87e19eb.jpg)

**Comment by nielsvanvelzen** [comment]
You're using the wrong app. You need to install the Android TV app, not the Android app.

https://play.google.com/store/apps/details?id=org.jellyfin.androidtv

**Comment by robertwynter** [comment]
Ah, well that explains it, a tiple ID-10_T error. LMAO. Ok let me switch that and try again.

**Comment by robertwynter** [comment]
ok, I'm using the correct one now and it's working as it should be. Sorry for the confusion :)
