### ISSUE TITLE
Support Subtitle offset to fix delays

### ISSUE THREAD

**Issue by dorsany** [jellyfin/jellyfin-androidtv#640]
**Describe the feature you'd like**	
	
Support Subtitle offset to fix delays in `android tv`, like you have for the `android` app.

**Additional context**	

This ability ia missing in the android tv, which cab ease the user to fix subtitle synchronization when a delay exist

From `android` app:
![Screenshot_20201120-180216~2](https://user-images.githubusercontent.com/36127093/99821510-d1181700-2b5a-11eb-8828-e819f8c0ea4a.png)

**Comment by Norin-Radd** [comment]
+1
