### ISSUE TITLE
TV Guide settings not being persisted

### ISSUE THREAD

**Issue by ggowins** [jellyfin/jellyfin-androidtv#641]
**Describe the bug**
The settings for the Live TV guide are not being persisted

**To Reproduce**
1. Go to the Live TV Guide
2. Click on the Gear icon
3. Make changes (in my case, Sort by Channel list, and check all the labels)
4. After making the change, the list is sorted by Channel, but after viewing several channels, it changes to using Last Viewed as the sort

**Expected behavior**
The saved settings should be used until changed.  In the browser client on my PC, the sort order stays by Channel

**System (please complete the following information):**
 - Fire TV version: FireOS 6.2.7.6
 - Device manufacturer: Amazon
 - Device model: FireTV Cube 4k
 - Jellyfin server version: 10.6.4
-  Jellyfin client version: 0.11.4

**Comment by MrChip53** [comment]
This has been fixed in the dev builds so will be fixed with the next official release!

**Comment by nielsvanvelzen** [comment]
Reference: #577
