### ISSUE TITLE
Jellyfin doesn't implement a channel properly in Android TV

### ISSUE THREAD

**Issue by razor1973** [jellyfin/jellyfin-androidtv#646]
**Describe the bug**
Jellyfin doesn't appear in the channels list in "Customize channels" so that it can be toggled on and off from appearing on the home page and so that you can include/exclude it from the Play Next section. Instead, it's forced in the Play Next section as long as you have it installed and connected to a server with media. And it doesn't appear in the channels below (like Netflix, Play Music, Pandora, etc.)

**To Reproduce**
1. Go Home
2. Scroll all the way to the bottom and select "Customize channels"
3. Look for Jellyfin.... Not there.
4. Press "Play Next", which allows you to select which channels are shown in the Play Next section.
5. Look for Jellyfin... Not there.
6. Go back home and down to the Play Next section.
7. Jellyfin media appears there when it shouldn't.

**Expected behavior**
Jellyfin should appear in the channels list in "Customize channels" so that it can be toggled on and off from appearing on the home page and so that you can include/exclude it from the Play Next section.

**Logs**

**Screenshots**
![A - Android Version](https://user-images.githubusercontent.com/956623/101227978-c8016c80-3667-11eb-90b8-2f48d9b7b98c.png)
![B - Jellyfin Client Version](https://user-images.githubusercontent.com/956623/101227980-c89a0300-3667-11eb-9882-050ea57b4198.png)
![C - No Jellyfin Channel to Toggle from Home](https://user-images.githubusercontent.com/956623/101227981-c9329980-3667-11eb-8dc7-049d2d7c6930.png)
![D - No Jellyfin Channel to Toggle from Play Next](https://user-images.githubusercontent.com/956623/101227982-c9cb3000-3667-11eb-90d9-727dc963c41d.png)
![E - Jellyfin Media in Play Next](https://user-images.githubusercontent.com/956623/101227983-ca63c680-3667-11eb-951a-6bb24835472a.png)

**System (please complete the following information):**
 - App version: 0.11.4
 - Android version: 9
 - Device manufacturer and model: Nvidia SHIELD TV
 - Jellyfin server version: 10.6.4 (Windows)
 - The type of video player implementation used: N/A

**Additional context**

**Comment by Maxr1998** [comment]
This issue applies to the TV app, so I transferred it to the right location.

**Comment by nielsvanvelzen** [comment]
This is an issue in Android that occurs when an app doesn't provide channels and only provides data for the "next up" section. Since we've added channels in the next update it's already fixed.

**Comment by razor1973** [comment]
That's great news. Is it 0.11.5? Because I don't see any issue in that project that resembles what I am describing. :(

Thank you for what you guys do!

**Comment by nielsvanvelzen** [comment]
Since it's a feature it will be in 0.12

**Comment by razor1973** [comment]
I assume it's [this one](https://github.com/jellyfin/jellyfin-androidtv/pull/331). Thanks!

**Comment by nielsvanvelzen** [comment]
Yup that's the one that fixes this issue. I will close it for now since it's fixed.

**Comment by razor1973** [comment]
Wonderful.
