### ISSUE TITLE
Update internal exoplayer to get MKV DV support

### ISSUE THREAD

**Issue by misterbit-pro** [jellyfin/jellyfin-androidtv#647]
Hello,

some time ago Dobly Vision got officaly supported by Exoplayer when playing a mkv made with MakeMKV 1.15.3 or higher on a SHIELD TV Pro 2019.

You can look into the pull request here:
[]()https://github.com/google/ExoPlayer/pull/7667

It would be great if the integrated Exopkayer could be updated so MKV Dolby Vision playback gets supported.

Plex also includes the new exoplayer in their beta Android TV app.

**Comment by nielsvanvelzen** [comment]
We're waiting for amazon to update their fork

**Comment by misterbit-pro** [comment]
Oh ok. Thanks for letting me now. I think i will close this in the meantime.

**Comment by nielsvanvelzen** [comment]
I took a closer look and the PR you mentioned from ExoPlayer is already in the version we use right now (since it's from July). It will be in the next release of the app.
