### ISSUE TITLE
Can't connect to server behind HAproxy from fireTV app but web and android apps work fine

### ISSUE THREAD

**Issue by mikef0** [jellyfin/jellyfin-androidtv#649]
**SETUP:**
I'm running Jellyfin 10.6.4 server in an LXC Ubuntu 20.04 container (Also tested 10.6.4 on native Debian 10 server with same results).
I am running HAproxy package on a separate pfSense box to function as a simple HTTP reverse proxy which provides a shared SSL frontend using a wildcard letsencrypt certificate and the setup works fine on numerous backends.

I have followed the Jellyfin HAproxy reference below without any success.
https://jellyfin.org/docs/general/networking/haproxy.html

HAproxy config is shown at the bottom to keep things easy to read.

**ISSUE:**
I had been accessing my Jellyfin server via reverse proxy without issue behind NGINX for quite some time. After migrating over to HAproxy, I can still access the server with 100% functionality from any web browser both within and outside my local network.

When trying to manually add my server in the Amazon FireTV app and trying to connect, I IMMEDIATELY get a "server unavailable" error. I have tried entering the hostname as follows
https://jellyfin.mydomain.net
https://jellyfin.mydomain.net:443
jellyfin.mydomain.net:443
jellyfin.mydomain.net
jellyfin.mydomain.net:443/jellyfin
jellyfin.mydomain.net/jellyfin

I don't see any attempts to connect in the Jellyfin server log when trying from the fireTV app. HAproxy front end log doesn't seem to show any connection attempts when trying from the fireTV app.

In order to debug, I have taken down HAproxy and brought back up my NGINX reverse proxy and Jellyfin works immediately without issue from the FireTV app.

**HAPROXY CONFIG**
frontend HTTPS_Shared-merged
	bind			MYIP:443 name MYIP:443   ssl crt-list /var/etc/haproxy/HTTPS_Shared.crt_list alpn h2,http/1.1 
	mode			http
	log				global
	option			socket-stats
	option			log-separate-errors
	option			httplog
	option			http-keep-alive
	option			forwardfor
	acl https ssl_fc
	http-request set-header		X-Forwarded-Proto http if !https
	http-request set-header		X-Forwarded-Proto https if https
	timeout client		30000
	option httplog
	acl			aclcrt_HTTPS_Shared	var(txn.txnhost) -m reg -i ^my.domain(:([0-9]){1,5})?$
	acl			aclcrt_HTTPS_Shared	var(txn.txnhost) -m reg -i ^([^\.]*)\.my.domain(:([0-9]){1,5})?$
	acl			Jellyfin	var(txn.txnhost) -m sub -i jellyfin
	http-request set-var(txn.txnhost) hdr(host)
	use_backend Jellyfin_ipvANY  if  Jellyfin 

backend Jellyfin_ipvANY
	mode			http
	id			118
	log			global
	timeout connect		30000
	timeout server		30000
	retries			3
	http-request set-header X-Forwarded-Port 443 
	http-request add-header X-Forwarded-Proto https if { ssl_fc } 
	server			Jellyfin 192.168.60.108:8096 id 119 check inter 1000  

Any help would be greatly appreciated
Thanks!

**Comment by ggogel** [comment]
I remember that I had weird issues with this app too after switching from nginx to haproxy. I'm also running mine on pfSense. I wonder how you access the configuration like that. I only know the web-interface and the main pfSense configuration xml.

I remember fixing this with choosing the expression "host starts with" rather then host matches, because this app is using some kind of non-standard format in the host field of the header. I can't remember if I found this solution myself or if it was a reddit thread or something. Anyway, try to change your regex by removing the "$" for example or simply give the "host starts with" expression a shot. I'm pretty sure this will fix it.
