### ISSUE TITLE
Publish 0.11.5 to Google/Amazon store

### ISSUE THREAD

**Issue by edouardkleinhans** [jellyfin/jellyfin-androidtv#653]
**Describe the feature you'd like**	
Do you plan to publish 0.11.5 to different store ?

**Comment by nielsvanvelzen** [comment]
What other stores would you want to see the app on?

**Comment by edouardkleinhans** [comment]
I'm using firetv, so if it could be on amazon store...

**Comment by nielsvanvelzen** [comment]
We already release on that store.
