### ISSUE TITLE
HEVC 4k in Firestick v1

### ISSUE THREAD

**Issue by ManuLinares** [jellyfin/jellyfin-androidtv#658]
- [X] Issue does not happen in the browser (jellyfin-web)

Mediainfo: https://pastebin.com/xqQPSrbu

Logs: https://pastebin.com/j9j2R4jh

Fire TV (  ro.build.version.fireos : [5.2.7.8]  )
Fire TV Stick (1st Gen)
Jellyfin server 10.7.7

My firestick is 1080p but jellyfin server doesn't change the resolution, it sends in original ressolution 3840x1600, unless I lower the bitrate in android app settings.

attached pics of my TV.
.
![001](https://user-images.githubusercontent.com/3720020/102703623-ff6b3e00-424f-11eb-8134-9658ac1ec71a.jpg)
![002](https://user-images.githubusercontent.com/3720020/102703625-009c6b00-4250-11eb-91ec-5339cd4b1ac8.jpg)
![003](https://user-images.githubusercontent.com/3720020/102703626-009c6b00-4250-11eb-9b2d-6fc593a5a498.jpg)
![004](https://user-images.githubusercontent.com/3720020/102703627-01350180-4250-11eb-9442-6141c34327b5.jpg)
![005](https://user-images.githubusercontent.com/3720020/102703628-01cd9800-4250-11eb-8627-710102030d30.jpg)
![006](https://user-images.githubusercontent.com/3720020/102703629-02662e80-4250-11eb-90e3-67d9593e1d94.jpg)

**Comment by ManuLinares** [comment]
It's still happening in the latest beta. I have to put the bitrate on 10mbps on the settings.

Isn't there a way that the app detects my 1080p max resolution and asks the jellyfin server for a *proper* resolution?

**Comment by ManuLinares** [comment]
It's still happening in the latest beta. I have to put the bitrate on 10mbps on the settings.

Isn't there a way that the app detects my 1080p max resolution and asks the jellyfin server for a proper resolution?

**Comment by ManuLinares** [comment]
Isn't there a way to limit the resolution to 1080p other that lowering the max bitrate to a ludicrous low number?

**Comment by thornbill** [comment]
It should already be downscaling to 1080 on that device if you are on the latest version of the app.

https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/util/DeviceUtils.java#L48

Can you confirm the model name of the device? It should be shown at the bottom of the settings panel in the Jellyfin app.

This does require 10.7.7 as previous versions had broken support for setting a maximum video size.

**Comment by ManuLinares** [comment]
Still doing it.

Server: **10.7.7**
App: **0.12.3** release
**Firestick v1 (AFTM)**

[Server log](https://pastebin.com/huNkSvk0)
[ffmpeg log](https://pastebin.com/LET0ejwY)

[Video showing everything](https://github.com/jellyfin/jellyfin-androidtv/files/7556093/VID_20211117_124856_2.m4v.zip)
[Video Mirror](https://drive.google.com/file/d/1_uz9QVOspOT-c_gjDC8BZufMuXNjbbIE/view?usp=sharing)

**Comment by ManuLinares** [comment]
This issue is still happening. Using latest CI build.
Jellyfin Server  10.7.7.

Client doesn't send the correct maximum widht and height, in firestick v1 is 1920x1080 so 4k movies still doesn't play. Still using an ffmpeg wrapper
[ffmpeg.txt](https://github.com/jellyfin/jellyfin-androidtv/files/8328314/ffmpeg.txt)
.
