### ISSUE TITLE
"SD" videos play in a bounding box

### ISSUE THREAD

**Issue by ivanlunardi** [jellyfin/jellyfin-androidtv#665]
**Describe the bug**
On 4k android tv the wrong  aspect ratio of "sd" videos 

**To Reproduce**
try to play a video mpeg4 with a low resolution ( like 624x272 )

the video will play in a little rectangle ( bottom left ) 

**Expected behavior**
a full screen video

**System (please complete the following information):**
 - Android TV version: [ Android 9 ]
 - Device manufacturer: [ Sony]
 - Jellyfin server version: [10.6.4]

**Comment by hi427893** [comment]
This bug only happens when **Preferred media player** is set to **Automatically choose**. **ExoPlayer** and **ibVLC** perform as expected.

**Comment by nielsvanvelzen** [comment]
I think we fixed this exact issue already and it should be available in 0.11.5
