### ISSUE TITLE
Dolby Vision with latest exoplayer

### ISSUE THREAD

**Issue by raver2046** [jellyfin/jellyfin-androidtv#667]
Please can you update the player with latest exoplayer ?
I would be great to have Dolby Vision working.

Ref here : https://github.com/google/ExoPlayer/pull/7667

**Comment by nielsvanvelzen** [comment]
We will update ExoPlayer when Amazon releases an updated version of their port.

**Comment by raver2046** [comment]
Hello, 
Can we have exoplayer Amazon port and exoplayer stock ?
