### ISSUE TITLE
Remote play of music requires manual interaction on target (FireTV)

### ISSUE THREAD

**Issue by ngnglro** [jellyfin/jellyfin-androidtv#668]
**Describe the bug**
Remote control / mirroring from browser requires manual interaction on target device when trying to play music ("do you really want to replace the current playlist?"). 

**To Reproduce**
Open Jellyfin App on FireTV. Open Jellyfin webinterface in a browser on your PC. On the PC/webinterface choose the firetv as target for remoteplay. Play any album or track from your music library. The song will not play, instead on the firetv a popup will appear, asking me if I want to add the song(s) to the current playlist or replace the playlist.

**Expected behavior**
The songs should play without manual intervention on the firetv. It works as expected for video files.

**Logs**
no logs applicable as far as I can tell

**Screenshots**
If unclear or not reproducable I can take a photo of the dialogue screen on the TV (dont know how to screenshot on the firetv).

**System (please complete the following information):**
 - Android TV or Fire TV version: Fire OS 5.2.7.4
 - Device manufacturer: Amazon 
 - Device model: Fire TV 1st Generation (not stick)
 - Jellyfin server version: 10.6.4

**Additional context**
-

**Comment by SonicPotions** [comment]
can confirm... happens when trying to play music on the TV from the mobile app, too.

**Comment by nielsvanvelzen** [comment]
Already fixed in #447
