### ISSUE TITLE
does not support external subtitles while using external player

### ISSUE THREAD

**Issue by frankyifei** [jellyfin/jellyfin-androidtv#67]
external srts cannot be found by external players, I tried kodi and mx player.  If I set subtitles option to always play subtitles, the external player will fail to load and the internal player will trigger a transcode to embedded the subtitle into the video. Embycon with kodi works with external subtitles well and not transcoding and I dont know why. I attached my log, at [09:03:32] I played a video with embycon and then I switched to jellyfin client and played the same video and another video with external player, both failed to load.
[jellyfin.log.txt](https://github.com/jellyfin/jellyfin-androidtv/files/2943686/jellyfin.log.txt)
Edit: The videos I tested played without transcoding via internal or external player if I disable subtitles in subtitle option.

**Comment by chain710** [comment]
same issue in latest version

**Comment by bartlomiejborzucki** [comment]
same issue in latest version

**Comment by e68862230** [comment]
It's a serious problem and still happening at latest version...

And it's funny to find that external subtitles can indicate after choosing subtitles and playing it on other playform...The subtitles is just  burned into the video...

**Comment by chicungunya** [comment]
Hi guys, did someone find the solutin? Thanks!

**Comment by nielsvanvelzen** [comment]
External subtitles are not supported when using an external player.

**Comment by sunrisela** [comment]
This issue is still happening in 0.12.3 version. Jellyfin for Android (not TV) client works fine when using an external player (like mx player), which identified whether internal or external subtitles, maybe be you could refer to its implementation.

**Comment by chicungunya** [comment]
> Jellyfin for Android (not TV) client works fine when using an external player (like mx player), which identified whether internal or external subtitles, maybe be you could refer to its implementation.

So if I install Jellyfin (not Android tv version) it will work?
Thanks

**Comment by chicungunya** [comment]
> External subtitles are not supported when using an external player.

Is it considered for a new feature or it's technically impossible? Thanks!

**Comment by nielsvanvelzen** [comment]
It's technically possible, our mobile app does it too. But the way to do it is a bit of a hack. There is no standard way to send additional information (like extra subtitles) with a video to an external app, same as receiving information back (playback progress).

**Comment by shenwii** [comment]
Using ffmpeg to add subtitles into the stream, but not changing the encoding I don't know if this is possible.

```
ffmpeg -i xxxx.mkv -i xxxx.ass -c:v copy -c:a copy -c:s mov_text out.mkv

PS: This command is not tested
```

**Comment by hhhien2903** [comment]
> It's technically possible, our mobile app does it too. But the way to do it is a bit of a hack. There is no standard way to send additional information (like extra subtitles) with a video to an external app, same as receiving information back (playback progress).

So does Android TV app can do it? Thanks

**Comment by DukemonZhn** [comment]
same issue in latest version

**Comment by RealGreenDragon** [comment]
Same issue in v0.15.3 (specifically with VLC external app).

**Comment by mquan86** [comment]
It is still an issue, please reopen it.
