### ISSUE TITLE
Feature Request: Option to Disable Live TV Tab

### ISSUE THREAD

**Issue by aaronson2012** [jellyfin/jellyfin-androidtv#670]
**Describe the feature you'd like**	
I would like to be able to disable the Live TV tab on the home screen.	

**Additional context**	
I have no interest in TV and would like to not have to scroll past the Live TV tab to get to my library.

**Comment by nielsvanvelzen** [comment]
You can disable the live tv feature in the server

**Comment by aaronson2012** [comment]
> 
> 
> You can disable the live tv feature in the server

Oh, alright thanks!
