### ISSUE TITLE
delayed change in Background image in full details screen movie or tv series

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#674]
Hi as the title says when you go into a movie and the full details screen shows theres a background image for that movie but if you then go into another movie full detail screen the background from the previous movie still shows for a few seconds before changing like its delayed

**Comment by nielsvanvelzen** [comment]
This is actually intended behavior, the "new" background is still loading so it keeps showing the previous background.

**Comment by tomaswl1** [comment]
ah no worries wasn't sure if was intended abit annoying sometimes but nothing major thanks for clarifying

**Comment by nielsvanvelzen** [comment]
I'm actually working on some changes for the "background manager" which manages the backgrounds. I'll see if I can find a way to make this behavior better.

**Comment by tomaswl1** [comment]
Nice 1 that would be great thank you

**Comment by viggy96** [comment]
@nielsvanvelzen On a somewhat related note, the background oftentimes interferes with the text on screen, making episode and series titles hard to read. I believe that this could be remedied by either darkening the background image, or maybe adding a drop shadow around all text. I think that darkening the background image would be easiest and probably more consistent.

**Comment by nielsvanvelzen** [comment]
My PR (#703) already darkens the background because I noticed the same issue!
