### ISSUE TITLE
Sorted by "Date Added" in Movie not the same as Web UI

### ISSUE THREAD

**Issue by billyinferno** [jellyfin/jellyfin-androidtv#675]
**Describe the bug**
When sorted by "Date Added" selected in movie, the result of the sort is not the same as the one in Web UI.

**To Reproduce**
1. Open movie library
2. Click on sort
3. Select "Date Added"

**Expected behavior**
Sort result should be the same Sort By Date Added (Descending) in Web UI.

**System (please complete the following information):**
 - Android TV (using 0.11.5 version)
 - Device manufacturer: Xiaomi Mi TV 4
 - Jellyfin server version: 10.6.4

**Comment by nielsvanvelzen** [comment]
Both jf-web (10.7~RC2) and ATV (master) sort with "DateCreated,SortName" for "Date Added". What difference do you see?

**Comment by nielsvanvelzen** [comment]
It was changed in #442 but not backported to the 0.11 release, my bad. It's fixed in the next release! :)

**Comment by billyinferno** [comment]
Yeah, rebuild latest source and test in emulator seems like the sort was fixed, thanks will wait for the next release, meanwhile, I'll try to use my own build.
