### ISSUE TITLE
Movie rollback

### ISSUE THREAD

**Issue by Nosirus** [jellyfin/jellyfin-androidtv#68]
I try to use Jellyfin and remove from Emby, but at each movie, after a while, it goes back to the beginning and when I advance in the video manually the volume is loud for a few seconds.

I use the Xiaomi Mi Box 3, no problem with Emby app and Kodi

**Comment by thornbill** [comment]
Thanks for the report! Could you provide some information about what format and codec the media is using?

**Comment by Nosirus** [comment]
I can not confirm for other formats, but most often my movies are in mkv h264 aac

**Comment by Artiume** [comment]
I'm experiencing a similar issue on my Fire Stick 4K. Every once in a while, the movie will skip back about 8 minutes, the timestamp shows the correct time but won't match the video/audio. If I stop the movie and replay, it'll continue to play normally. I am not experiencing the Loud Audio issue and if I am far enough into the video, it will send it back a couple minutes (not necessarily back to the beginning). The behavior feels as though the player is reusing old temp transcoded files. 

**Stats for Nerds Screenshots** Via browser
Playback Info
Player:
Html Video Player
Play method:
Transcode
Protocol:
https
Stream type:
HLS
Video Info
Player dimensions:
1920x937
Video resolution:
1920x910
Transcoding Info
Video codec:
H264
Audio codec:
MP3
Bitrate:
124.4 Mbps
Transcoding progress:
100.0%
Original Media Info
Container:
mkv
Bitrate:
1.7 Mbps
Video codec:
HEVC Main 10
Video bitrate:
1.7 Mbps
Audio codec:
EAC3
Audio channels:
6
Audio sample rate:
48000 Hz 

**Server System (please complete the following information):**
 - OS: Ubuntu 18.04
 - Jellyfin Version: Docker, 10.4.1
 - Hardware settings & device: Software transcoding with dual Intel X5670
 - Reverse proxy: traefik
 - Other hardware notes: N/A

**Client System (please complete the following information):**
 - Device: Fire Stick 4K
 - OS: Fire OS
 - Client: Jellyfin App
 - Client Version: 0.10.2a



Unrelated issues that I can create new tickets if needed. On the app's main screen and any folders, no metadata is shown on the client. If I click on a video and focus on it, metadata is shown. Only main menu and subsequent menu's are having this issue. 

https://hub.docker.com/r/jellyfin/jellyfin documentation links are old, they link back to https://jellyfin.readthedocs.io
