### ISSUE TITLE
Option to disable annoying questions with External Players 

### ISSUE THREAD

**Issue by pamidur** [jellyfin/jellyfin-androidtv#691]
**Describe the feature you'd like**	
While using external player the UX is heavily impacted by annoying popups:
- Every time episode is finished, popup "Play next?" appears, though in settings there is option dedicated for "Queuing next episode"
- Every time episode is interrupted earlier there is a question "Mark as played?", though the jellyfin knows how much of the episode was played, and it doesn't ask questions for built-in players

I assume there is a reason behind those popups - debug probably. It would be great - to have an option to disable those

**Additional context**	
https://github.com/jellyfin/jellyfin-androidtv/blob/ccb47ab9afd6610eec98ca698203ad103eead2e4/app/src/main/java/org/jellyfin/androidtv/ui/playback/ExternalPlayerActivity.java#L187
```java
if (mItemsToPlay.size() > 0) {
            //Must confirm moving to the next item or there is no way to stop playback of all the items
            new AlertDialog.Builder(this)
                    .setTitle("Next up is "+mItemsToPlay.get(mCurrentNdx).getName())
```

**Comment by ohhai-kthxbai** [comment]
Please do prioritse this. Using external players is essential as the default player has so many playback/fwd/rew issues and this bug is making that difficult. Thank you!
