### ISSUE TITLE
more display options in media views

### ISSUE THREAD

**Issue by Sveninndh** [jellyfin/jellyfin-androidtv#694]
Please, expand the display options of the media views:
1.) Leave some space horizontally and vertically between the thumbnails, regardless of whether they are films, videos or photos.
2.) Please scroll not only horizontally but vertically, i.e. either only vertically or adjustable.
3.) It must be possible to display a label under the thumbnails, e.g. file name, folder name or film name.

As a template, please have a look at how this is done in the normal Android Jellyfin app. Maybe it's a matter of taste, but for my needs it is much better solved there. Unfortunately, this app cannot be operated with the remote control on Android TV.

**Comment by nielsvanvelzen** [comment]
Next version adds an (experimental) option for 2 (vertical/horizontal toggle).

**Comment by Sveninndh** [comment]
> 
> 
> Next version adds an (experimental) option for 2 (vertical/horizontal toggle).

I'll test it out as soon as it's there.
Is it possible to download and test a beta apk somewhere now?

However, this would still not be usable for my application (presentation of private photo and video galleries) without the display of captions under the thumbnails.

**Comment by kryptonking** [comment]
Will the new vertical/horizontal view options apply to the view inside a collection as well? For example, if I have a collection with 50 items or something, it sucks having to scroll all the way to the right in a single row.

**Comment by nielsvanvelzen** [comment]
I don't use collections so I'm not sure, but I think it works.

More information in #475 and #317. Closing this issue for now.
