### ISSUE TITLE
Unable to identify server locally when media server is behind VPN 

### ISSUE THREAD

**Issue by wjunker** [jellyfin/jellyfin-androidtv#695]
**Describe the bug**
Unable to identify server locally when media server is behind VPN. The Andrid app does not have this problem. The Jellyfin can be found by typing in the IP manually, but that is very cumbersome with a TV remote

**To Reproduce**

1. Setup a server with a VPN client and Jellyfin.
2. Activate the VPN client.
3. Open the Jellyfin app and it won't automatically resolve the local Jellyfin server

**Expected behavior**

I expect the Android TV App to find the local server as the Android App does without problems

**Logs**

Please specify if needed, I will try to provide them :).

**Screenshots**

Just stuck at the server screen.

**System (please complete the following information):**
 - Android TV 8.0
 - Sony Smart TV

**Comment by steve956** [comment]
I have exactly the same behaviour as @wjunker  with:

Server: Win 10 Pro. 
VPN: PIA or Nord - same behaviour.
Client; 4k Firestick with standard Fire App

Works if IP address entered manually, but this will not persist between sessions.
Standard Roku store app works on my Roku stick with VPN running on server

**Comment by wjunker** [comment]
> I have exactly the same behaviour as @wjunker with:
> 
> Server: Win 10 Pro.
> VPN: PIA or Nord - same behaviour.
> Client; 4k Firestick with standard Fire App
> 
> Works if IP address entered manually, but this will not persist between sessions.
> Standard Roku store app works on my Roku stick with VPN running on server

Did you find a solution? I have not managed to. Entering manually is a pain with a remoate :D

**Comment by steve956** [comment]
> > I have exactly the same behaviour as @wjunker with:
> > Server: Win 10 Pro.
> > VPN: PIA or Nord - same behaviour.
> > Client; 4k Firestick with standard Fire App
> > Works if IP address entered manually, but this will not persist between sessions.
> > Standard Roku store app works on my Roku stick with VPN running on server
> 
> Did you find a solution? I have not managed to. Entering manually is a pain with a remoate :D

No I'm afraid not. Just carried on using Plex which was set up on all my devices before. Shame I'd prefer JF :(

**Comment by LeviSnoot** [comment]
Adding to the bunch here.

I can't even connect locally temporarily. Plex works just fine in the same scenario.

Server: Windows 10 Pro, Jellyfin 10.7.2
VPN: ExpressVPN
Clients: NVIDIA Shield TV (2015): Kodi for Jellyfin, Jellyfin Android TV App
iPhone X: Safari for iOS, Jellyfin iOS app
Extra: Using Caddy as a reverse proxy but works fine to connect to the local IP range when not connected through VPN.
