### ISSUE TITLE
App cannot resolve server if the server is started after 

### ISSUE THREAD

**Issue by wjunker** [jellyfin/jellyfin-androidtv#696]
**Describe the bug**
If you don't have your Jellyfin server running 24/7, but only turn it on when needed, I experience that the Android TV App can't resolve the local Jellyfin server unless I forcestop the app and wait a bit.

**To Reproduce**

1. Turn on your tv and start Jellyfin
2. Turn on your Jellyfin server
3. Wait or try and close the app and relaunch it
4. See that the Jellyfin server can't be resolved.

**Expected behavior**

Like the Android App I would expect that the client can resolve (or periodically check?) for servers to come up when you are present in the server view. 
**Logs**

If needed please shout, and I will try to provide them.

**System (please complete the following information):**
 - Android TV 8.0
 - Sony Smart TV

**Comment by acl1704** [comment]
Experienced this today while troubleshooting nvidia drivers. Restarting the android tv host didn't fix the issue.

**Comment by nielsvanvelzen** [comment]
Current workaround is to start your server before opening the app. When starting the app before the server is started you need to wait a bit (around 60 seconds) before restarting it.

**Comment by wjunker** [comment]
@nielsvanvelzen with the newest build of Android TV + server, it hasn't occured. I'll close the bug.
