### ISSUE TITLE
Cant change Audio language while Video is in pause 

### ISSUE THREAD

**Issue by Xyz00777** [jellyfin/jellyfin-androidtv#698]
**Describe the bug**
Cant change the Audio language while Video is not running

**To Reproduce**

1. Start any Kind of video
2. Pause the video
3. Try to change Audio language

**Expected behavior**
Audio language should change to the language i selected while Video is paused

**System (please complete the following information):**
 - chromecast with Google tv

If you need any more Information let me know. 
Greetings :)

**Comment by notarobot63** [comment]
Hello, 
Same here on Shield TV. When I switch language it does not appear to be selected (the box is not checked and cannot be checked).

**Comment by brandonssmith** [comment]
I have the same issue on mine. Fire tv box, version 0.11.5.

**Comment by nielsvanvelzen** [comment]
Fixed in #896
