### ISSUE TITLE
Movie / TVShow Trailer link

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin-androidtv#71]
Not sure if this is an issue or just an enhancement, in the beta 4 apk the option to watch the trailer is not present for Movies or TV-Shows like in the android app or in browser.

**Comment by vbaros** [comment]
Can we have this in the next release? I see it is removed from v0.13.

**Comment by vertigoelectric** [comment]
The JF app on my Sony Android TV does not have a button for playing trailers.  Does this issue address that, or is this something different?

**Comment by fmchris10** [comment]
It would be nice to have the trailer function back in the app (if its true that it's been removed in prior versions). Perhpas in the settings, have an option to disable them for those who don't wish to see the feature.

**Comment by Ky-0** [comment]
How do I enable or see trailers in the app then @nielsvanvelzen ?

I see them in the web gui but not the android tv app and have no idea how I can enable this?

**Comment by nielsvanvelzen** [comment]
The app shows all local trailers on the details screen.

**Comment by Ky-0** [comment]
So you basically have to download the trailers and include them in your libary then? If that is the case, how's best to sort them, for example I just have the folders 'Movies' + 'TV Shows'

**Comment by nielsvanvelzen** [comment]
Yes, you can look at docs.jellyfin.org to find out how to organize the files.

**Comment by Ky-0** [comment]
Yep, found it. Thanks mate.

For anyone else interested, here is the link:
https://jellyfin.org/docs/general/server/media/movies.html

**Comment by Ky-0** [comment]
@nielsvanvelzen - Have you noticed since updating JF to V10.8.0 local trailers have stopped working? They no longer show up in the JF Android TV app or load in the web, I will do further testing later but it was working until I updated.

**Comment by nielsvanvelzen** [comment]
They sti work for me, it might be an issue or change in the folder scanning in the server.

**Comment by Ky-0** [comment]
> They sti work for me, it might be an issue or change in the folder scanning in the server.

Hmmm, I'll have a look. I have them all in the same folder just with the appendix "_trailer".
