### ISSUE TITLE
Passwordless Login

### ISSUE THREAD

**Issue by frdbonif** [jellyfin/jellyfin-androidtv#716]
**Describe the feature you'd like**	
When a user has PIN login enabled on the local network but with no PIN set, the user should be logged in without any further interaction when selected from the login screen.

**Additional context**	
Currently, with D-Pad PIN entry and Local authentication via PIN, a user with a blank PIN still has to confirm their pin by holding the centre button for one second.

**Comment by afraazali** [comment]
I tested this on a debug release and it works properly. I’ve set my PIN to an empty value and I’m not prompted to enter a PIN.

**Comment by nielsvanvelzen** [comment]
The current debug release doesn't support PIN login at all

**Comment by afraazali** [comment]
Oh, makes sense why it doesn’t ask for my PIN then. Haha.

**Comment by sourpatched** [comment]
@frdbonif v0.14.0 support Quick connect (code base login) https://jellyfin.org/posts/android-tv-14/

**Comment by nielsvanvelzen** [comment]
Quick Connect replaces the pin login feature. Closing as completed.
