### ISSUE TITLE
How to play 4k locally using Nvidia Shield Pro with Jellyfin

### ISSUE THREAD

**Issue by robertwynter** [jellyfin/jellyfin-androidtv#723]
**Describe the bug**

I'm running a gigabit network, speedtest.net usually between 500 - 800 mpbs
Cat 8 cables running from the server, Modem, Switch and Router
Server is DSM
DS3615xs
DSM 6.1.7-15284
INTEL Core i3-4130
Total Physical Memory - 32 GB
files size and formats (TS, MKV, ISO) 40 - 80 GB

It shows direct play. Here are my settings for shield and JF. let me know please if you have anything different I can try:

Shield Android;

https://imgur.com/YaJQ5ga

https://imgur.com/HOhDOJF

https://imgur.com/yoAZB94

https://imgur.com/vEihy9D

Jellyfin;

https://imgur.com/JnVjgHe

https://imgur.com/eKuKCEH

https://imgur.com/dIyZRsM

https://imgur.com/H60oZ8z

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Android TV or Fire TV version: [e.g. Android 9 or Fire OS 7]
 - Device manufacturer: [e.g. Amazon, Nvidia, Sony]
 - Device model: [e.g. Fire TV Stick (2nd Gen) or Shield TV]
 - Jellyfin server version: [e.g. 10.5.4]

**Additional context**

**Comment by BonzTM** [comment]
I ended up creating a 2nd in-home user for all my Shield TVs and turning off transcoding on the server-side.  Just as an FYI for a workaround.

**Comment by jedthe3rd** [comment]
Make sure Max Stream Bitrate in the Android TV Client is set to the max value (120Mbits/sec, not auto). This seemed to get it to always pick the version of the media with the highest quality. I have 1080p version of almost all my 4K movies and it is kind of random of what it chooses to display as the quality of the movie in the movie info screen, but when you play it, it will pick the highest quality option that fits in the Max Stream Bitrate.
