### ISSUE TITLE
Unable to disable subtitles

### ISSUE THREAD

**Issue by kokare-darshan** [jellyfin/jellyfin-androidtv#724]
**Describe the bug**

**To Reproduce**

1. Play any video with subtitles
2.  Disable subtitle by choosing None option in menu (now subtitle disappears)
3. Wait till menu disappears, forward video by right button
4. Subtitles displays

**Expected behavior**
Subtitles should be disabled

**Logs**

**Screenshots**

**System (please complete the following information):**
 - MI box tv
 - MI XIAOMI

**Additional context**

**Comment by arantes555** [comment]
There is the same problem if you change the selected subtitle, or enable subtitle when none was enabled by default

**Comment by kokare-darshan** [comment]
I suppose, yes.

**Comment by thantik** [comment]
I'm getting what I believe is a variation of this on the 0.11.5 that's on Amazon's FireTV store.  If I watch an anime with English subtitles, then hit the next button so I'm watching the next episode -- english subtitles will continue to be selected, but as soon as I forward the playback (usually to skip intro scene) the subtitles get deselected and set back to none.

Additionally, default subtitles don't seem to be selected automatically.  It's really getting on my nerves, and I'm probably just going to switch back to plex in the meantime.

**Comment by thantik** [comment]
This issue seems to have been resolved for me with the newest FireTV client - which I understand is a downstream version of the AndroidTV client.

**Comment by UnDifferential** [comment]
This bug is still present for me on a Sony Android TV.

**Comment by jn-hrt** [comment]
> 

I am also seeing this issue on my Sony Android TV
Bravia 4K GB ATV3
Jellyfin-Androidv 0.14.0 release

**Comment by fireduck64** [comment]
I have experienced this problem on FireTV just now.

In my case, selecting any subtitle other than None works, but when selecting None the option does not seem to change. If I go back into subtitle selection it shows the previously selected option.

**Comment by bweavemcu** [comment]
Same issue for me on nvidia shield android tv, jellyfin-androidtv 0.14.5 release. If I turn on subtitles, it transcodes to burn them in, then when I try to turn them back off by selecting "none" it doesn't take effect. Restarting the app doesn't fix it and it only affects that one show.

**Comment by TikoyX** [comment]
Still a problem on mac on the newest version (downloaded today december 26th)

**Comment by TikoyX** [comment]
I have the same issue except they never disappear. I cannot toggle them off again

**Comment by NiciTheNici** [comment]
I am experiencing the same problem. The subtitle option "none" doesnt get selected when I click it. The video does freeze for a few seconds though.

This issue might have something to do with ExoPlayer, the default way to watch videos on my chromecast jellyfin app, I dont know enough to say for sure.

```
jellyfin-androidtv: 0.15.3
jellyfin/jellyfin docker: 10.8.9
```

Please consider reopening this issue.

**Comment by piiot** [comment]
This issue is also present for me 0.15.5 nvidia shield, exoplayer. Jellyfin 10.8.9

**Comment by mprentice** [comment]
This happens specifically on x265 videos. Never on H264 (that I've seen).
