### ISSUE TITLE
Max bitrate= auto not working in Fire stick tv

### ISSUE THREAD

**Issue by Bandid0** [jellyfin/jellyfin-androidtv#736]
**Describe the bug**
 In settings of the client android tv maximum bit rate selected = auto, the movies in 4k for a 1080 tv do not play, it is necessary to select the bitrate manually, You have to see to what bitrate the mkv is encoded and put it in the configuration manually.

**To Reproduce**

**Expected behavior**

**Logs**
[log_20210320 - copia.log](https://github.com/jellyfin/jellyfin-androidtv/files/6176158/log_20210320.-.copia.log)

**System (please complete the following information):**
 -  Windows 10 x64
 - Clients: Fire Stick TV
 - Jellyfin Version: 10.7.0
 - Playback: Transcode
 - Storage: local

**Comment by ManuLinares** [comment]
Related to bug 

https://github.com/jellyfin/jellyfin-androidtv/issues/658#issue-771495737

**Comment by zeus86** [comment]
Thanks for reporting this bug, I just could not nail down, why my firetv-stick won't play any 4k movies, limiting the maximum bitrate to 15mbps seems to solve the problem for me.
