### ISSUE TITLE
Extended login retention time

### ISSUE THREAD

**Issue by libra1010** [jellyfin/jellyfin-androidtv#754]
At present, the longest holding time is 24 hours. Is it considered to increase it to 1 month, 
because it is mainly for internal use

**Comment by nielsvanvelzen** [comment]
I'm not sure what you mean. Logins don't expire unless the session is removed in the server's dashboard.

**Comment by thornbill** [comment]
I'm going to close this, but if you can provide some additional information, we can reopen.
