### ISSUE TITLE
Search by letters does not work on Fire TV Stick 4K

### ISSUE THREAD

**Issue by Bandid0** [jellyfin/jellyfin-androidtv#755]
**Describe the bug**
Search by letters does not work on Fire TV 4K the list of letters is displayed but there is no cursor that moves through them.
I also have a Fire TV Stick (3rd generation) and that one works correctly.

**Screenshots**

![1614943763397](https://user-images.githubusercontent.com/79402382/110110116-a7ec6100-7dae-11eb-80c1-33c6ed09ac78.jpg)

**System (please complete the following information):**
 - Fire TV 
 - Amazon
 - Device model: Fire TV Stick 4K
 - Jellyfin server version: 10.8.0

**Comment by nielsvanvelzen** [comment]
Did you press the down button to go to the letters?

**Comment by Bandid0** [comment]
yes

**Comment by linetrimmer** [comment]
Also getting this on a Fire TV Stick (2nd Gen) on both 11.5 and master builds. The letters pop down but after that the only remote button that does anything is the back button to dismiss the list of letters

**Comment by nielsvanvelzen** [comment]
I'm unfortunately unable to reproduce on my Philips TV and the emulator. This might be a Fire TV specific issue.

**Comment by MrChip53** [comment]
Can confirm its definitely a FireTV issue.

> Also getting this on a Fire TV Stick (2nd Gen) on both 11.5 and master builds. The letters pop down but after that the only remote button that does anything is the back button to dismiss the list of letters

This is the exact behavior. Its like the letter list never gains focus and you cant shift focus to the list.
