### ISSUE TITLE
Add option for disabling Live TV feature

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-androidtv#763]
**Describe the feature you'd like**	
Add an option in the app settings to disable Live TV for those who don't use this feature. I don't use it, so this extra row on the main screen of the app is useless space for me. 

**Additional context**	
This could be rolled into a broader feature of allowing customisation of the rows on the Jellyfin TV app home screen.

**Comment by linetrimmer** [comment]
The Android TV home screen rows follow the order set on web. If you remove Live TV as a home screen section on web (user icon in top right corner -> Home), it should disappear on the Android TV app home screen.

**Comment by viggy96** [comment]
@linetrimmer Ah I see. Upgrading to 10.7.0 must have changed that setting silently... Anyway, that worked.
