### ISSUE TITLE
Android TV app doesnt support tls1.3

### ISSUE THREAD

**Issue by Joly0** [jellyfin/jellyfin-androidtv#777]
**Describe the bug**
I cant connect to my home jellyfin server, as it is using tls1.3 and that seems to be an issue (atleast i think so, as the same problem was with emby already)

**System (please complete the following information):**
 - OS: Unraid/Slackware
 - Virtualization: Docker
 - Clients: FireTV, Nvidia Shield
 - Browser: Android TV App
 - Jellyfin Version: 10.7.0
 - Playback: -
 - Installed Plugins: -
 - Reverse Proxy: Cloudflare -> Nginx -> jellyfin
 - Base URL: -
 - Networking: NAT
 - Storage: local

**To Reproduce**
1. Enable tls1.3 in nginx or cloudflare
2. Download Jellyfin TV app on FireTV or Shield
3. Try to connect to server with external url

**Expected behavior**
No problem connecting to server

**Logs**
none

**Screenshots**
none

**Additional context**
I cant tell 100% sure, if this is because of tls1.3, but the emby app has/had similar problems and there are quite a few forum entries that raise that problem on their side and most of the time its because the emby android tv app doesnt support tls1.3

**Comment by arantes555** [comment]
I believe I am hitting the same problem, but the weird thing is that it only seems to happen when the server is on 10.7. I just updated from 10.6, and my Android TV app stopped working. In my case, it's the Jellyfin package for cloudron.io

**Comment by Joly0** [comment]
I cant tell exactly the version, both devices are running. 
The Shield TV is the 2019 version which should be running Android 9, atleast it indicates something like that in the device settings. For the fire tv stick i have no clue and cant find any information as amazon uses an os based on android but changes the naming scheme giving no direc tindication for the underlying os version. 
Same goes for nvidia, but as i said, there is an info setting that might indicate its running android 9/pie

**Comment by Joly0** [comment]
Btw changing to tlsv1.2 in cloudflare immidiatly solves the problem, although i would prefer to use 1.3

**Comment by nielsvanvelzen** [comment]
TLS 1.3 is supported in Android 10 and newer so if you're shield is running Android 9 it won't work.

**Comment by Joly0** [comment]
Hm, i just wanted to be sure, as on the emby forums there were people with similar problems but that seems to got solved when emby got updated to .net core 3.1 adding support vor tls 1.3.

Still thank, than i have to wait for a major os upgrade on those devices (though i bet those wont come soon)

**Comment by DarrienG** [comment]
Ah this is a shame. That means all Amazon Fire Sticks can't connect to anything using strictly TLS 1.3.
