### ISSUE TITLE
No audio on bluray remux direct streams

### ISSUE THREAD

**Issue by hawkinspaul** [jellyfin/jellyfin-androidtv#781]
**Describe the bug**
When I play a bluray remux, the audio doesn't work at all. It also skips around and lags.

**To Reproduce**
Play a bluray remux movie or tv show

**Expected behavior**
A proper stream

**Logs**
So I looked through these logs and didn't see any errors, but I may have missed something. 
https://pastebin.com/hwamu43V

**System (please complete the following information):**
 - Android TV or Fire TV version: Fire TV stick 2020 version
 - Device manufacturer: Amazon
 - Device model: 
 - Jellyfin server version: 10.7.0

**Comment by NebelNidas** [comment]
I also have this issue with some of my files. For me, enabling Stereo Downmixing in the settings solved it. Could it be that your issue is related to #142?

**Comment by hawkinspaul** [comment]
Interesting -- I'll give that a shot thank you. Is that in the Jellyfin settings or in the fire tv app settings?

**Comment by NebelNidas** [comment]
It's in the settings of your FireTV-Jellyfin app.

**Comment by hawkinspaul** [comment]
This fixed it for me. Thank you :)
