### ISSUE TITLE
All content triggers HDR on display, even if it’s not HDR content

### ISSUE THREAD

**Issue by afraazali** [jellyfin/jellyfin-androidtv#782]
**Describe the bug**
All videos are triggering HDR on my tv. This happens with any video regardless of if it’s HDR or not.

**To Reproduce**

1. Play any video
2. Check your display to see that HDR is triggered

**Expected behavior**
It’s expected that HDR is only triggered on my TV when playing media with HDR. SDR content should not trigger HDR on my tv.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Android TV - Shield version 8.2.2
 - Device manufacturer: NVidia
 - Device model: Shield TV
 - Jellyfin server version: 10.7

**Additional context**

**Comment by linetrimmer** [comment]
Related https://github.com/jellyfin/jellyfin-androidtv/issues/49#issuecomment-793237576

**Comment by afraazali** [comment]
A benefit of HDR being triggered on the display is that it is correctly triggering Dolby Vision on my tv when playing Dolby Vision content.

**Comment by afraazali** [comment]
After removing that line, content that isn't in HDR is not triggering HDR on the TV. Content that is HDR still triggers HDR on the TV.

**Comment by reacocard** [comment]
Removing that line causes HDR to never activate for me, not even on HDR content.

**Comment by reacocard** [comment]
I'm guessing that instead of a static value, jellyfin needs to set it depending on the content. this looks like the right function: https://developer.android.com/reference/android/view/Window#setColorMode(int)
