### ISSUE TITLE
Cast music to DLNA/Chromecast

### ISSUE THREAD

**Issue by cromatox** [jellyfin/jellyfin-androidtv#788]
It would be great if I could use the app only as a remote control to play my music on a DLNA renderer or a Chromecast device. 
 
A configurable default music playback renderer in the options could be also a great option. The Android upsampling stuff is not a good way to play the music in the best possible way. I own more expensive hardware that manages this task much better.

**Comment by nielsvanvelzen** [comment]
There are no plans to use the TV app as a remote control. For those use-cases you'll need to use the mobile app.
