### ISSUE TITLE
Can't use external player with music videos or mixed content

### ISSUE THREAD

**Issue by Degrian** [jellyfin/jellyfin-androidtv#789]
**Describe the bug**
On my Android TV on Shield Pro external player didn't work with music videos or files in mixed content type library. With music video file app calls exoplayer and then inscription "Player error encountered. Will re-try..." appears. With video in mixed content appears inscription "No player. It doesn't appear you have a video capable app installed", but i have VLC and MX player installed. Files in movie or TV show libraries play fine in VLC.

**To Reproduce**
Set "External app" as "Preferred media player" in the options and play a file from music video or mixed content type libraries.

**Expected behavior**
External player should be used (VLC etc.)

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: Nvidia
 - Device model: Shield TV Pro
 - Jellyfin server version: 10.7.1

**Comment by Degrian** [comment]
These errors appears also if i choose Exoplayer as media player. If i choose Libvlc or auto setting video just doesn't load.

**Comment by suyash192** [comment]
Facing the same issue. An explanation for whether it's a bug or intentional would be appreciated.
