### ISSUE TITLE
search is inconsistient

### ISSUE THREAD

**Issue by steelersfan7** [jellyfin/jellyfin-androidtv#790]
**Describe the bug**
When using the latest stable and development version on sheld, google tv with chromecast and firestick, the search does not ork

**To Reproduce**

1. Go to the search in the top left corner
2.  Go to the text bar.
3. Type in a show and ht the search button on the on screen keyboard
4. nothing pops up

**Expected behavior**
I would expect that it either lazy loads, or the search button triggers the search function consistiently.

**Logs**
I do not know how to get logs on android tv, but with some guidelines, I could retrieve them.

**Screenshots**
I can send screen shots if necessarry, but as of now, its just a background with a search bar, with words in the search bar, and nothing showing up.

**System (please complete the following information
 - Android TV or Fire TV version: [e.g. Android 10 and latstt Fire OS ]
 - Device manufacturer: [Amazon, Nvidia, google]
 - Device model: [e.g. Fire TV Stick 4k and nvidia shield 2019 and new google tv with chromecast]
 - Jellyfin server version: [11.5 and 0.0.0 dev

**Additional context**
On the shield, it seemed like when using voice search it would trigger the search,  I can't replicate this on the google tv or firestick

**Comment by steelersfan7** [comment]
still exists

**Comment by bill-mcgonigle** [comment]
Search works for me on the web client but I get zero results on a FireTV.

Currently running 20230308.6-unstable  - pretty sure it was working several months ago.
