### ISSUE TITLE
Non-MP4 web links (in STRM file) do not work correctly

### ISSUE THREAD

**Issue by ddurdle** [jellyfin/jellyfin-androidtv#794]
**Describe the bug**
When accessing a STRM file that contains a MP4 file via the Android TV client, playback is correct and seeking is supported.  I can see the client is talking to the web server hosting the STRM file to seek within it (with content-range requests, handling 206 response codes, etc)

When accessing a STRM file that contains a MKV file via the Android TV client, the player is not properly seeking within the file.  It only makes a single request to the destination without any content-ranges.  Thus, if the file has it's header information at the end of the file, playback won't start until the entire file is downloaded to the player.  Likewise, because the player is not behaving correctly, fast forward and seeking is not supported.  It never makes the correct content-range requests and, thus, doesn't invoke 206 response codes from the web server.

With the same MKV files, playback via jellyfin-ffmpeg transcoding, via android tv with external player, via KODI, via web, etc, all correctly handle the stream and request the appropriate content-ranges to seek within the file to correctly playback the file.  I can see on the server side 206 response codes being delivered back to the client.  Thus, fast forward and seeking work as expected.

**To Reproduce**

1. Create a simple ngnix site hosting 1 sample MP4 and 1 sample MKV file.  Create a STRM for each of these files and map these STRM files to a library in JF.
2. Click on the MP4 file in the Android TV app.  You will see on the server side ngnix log that the communication to the ngnix is following the expected behaviour with content-ranges and corresponding 206 responses.
3. Click on the MKV file in the Android TV app.  You will see on the server side ngnix log that the communication to the ngnix is NOT following the expected behaviour.  There are no content-ranges in the requests and corresponding are only 200 responses.  Therefore, FF and seeking are not supported, and MKV files that contain the media header information at the end of the file will not start playback until the entire file has downloaded to the player.

**Expected behavior**
With the same MKV files, playback via jellyfin-ffmpeg transcoding, via android tv with external player, via KODI, via web, etc, all correctly handle the stream and request the appropriate content-ranges to seek within the file to correctly playback the file.  I can see on the server side 206 response codes being delivered back to the client.  Thus, fast forward and seeking work as expected.

**Logs**
n/a

**Screenshots**
n/a

**System (please complete the following information):**
 - Android TV or Fire TV version: Fire 4k TV stick 11.5
 - Device manufacturer: Amazon
 - Device model: Fire 4k TV stick
 - Jellyfin server version: 10.7.1

**Additional context**
n/a

**Comment by nielsvanvelzen** [comment]
I'm not familiar with strm files but this looks like an issue with the current playback code in general. You could try changing the preferred video player to either LibVLC or ExoPlayer and see if that solves the issue.

**Comment by ddurdle** [comment]
I will try libVLC.  I think it’s using ATV/ExoPlayer by default, as this is
where I see the playback calls being made from when looking at the ngnix
logs.

**Comment by ddurdle** [comment]
Seems libvlc always forces transcode regardless of the media.  Always complains about the framerate. 


The media is being converted into a format that is compatible with the device that is playing the media.
Framerate: 270fps

4.0 Mbps MKV H264 AAC


Reason for transcoding:
RefFramesNotSupported

**Comment by ddurdle** [comment]
When using libvlc, If I disable the "video encoding" option in the user profile, the transcoding goes to direct streaming with reason being the audio channels is not supported.  The video is AAC.  If I disable all the transcoding options, the video plays back without issue, including with audio, and it's requesting content-ranges. 

So to recap:

With ExoPlayer, it does not falsely think it needs to transcode, but it only properly streams with MP4 STRM files.

With libvlc, it tries to transcode for invalid reasons, but properly streams with all file types.
