### ISSUE TITLE
Player interface pops up twice while movie is loading to play

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#800]
When starting a movie of large size and it takes a little longer to start playing the player interface appears as it should but then disappears a few seconds later then when the movie actually starts playing it reappears again for a few seconds

what id expect it to do it start movie it pops up and stays shown until movie starts playing then disappears

its nothing major but its annoying

Using latest master

device Nvidia shield

thanks

**Comment by nielsvanvelzen** [comment]
This is not easy to fix with the current playback code so it will probably not be fixed until the playback rewrite is ready.
