### ISSUE TITLE
All Items view issues

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#805]
Couple issues ive noticed in this section 

1. When in the all item view and you click a movie but then decide i dont want that movie and press back the all item view it goes back to start not the item you was just viewing so u have to scroll back to were u was

2. When in the all item view and scrolling across every so often the screen will go dim like it doing something refreshing the screen and at bottom were its doing a count up it would do the dim and say 1 at bottom

This is latest master on shield

**Comment by thornbill** [comment]
This seems like a regression on master.
