### ISSUE TITLE
Latest TV Shows doesn't show on home screen, but Latest Movies does

### ISSUE THREAD

**Issue by ragoneone** [jellyfin/jellyfin-androidtv#81]
Latest TV Shows doesn't show on home screen, but Latest Movies does.  This is only on the Android TV app.  The standard Android app shows Latest TV on my phone and the wen interface shows it too.  When I use the Android TV app on my Nvidia Shield, it doesn't appear.

**Comment by choakem** [comment]
This is probably the biggest issue I have right now with androidtv. Not bad considering how hound the apk is...

**Comment by thornbill** [comment]
Something similar to this method for getting the latest movies will need to be added.

See https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/browsing/HomeFragment.java#L234-L242

**Comment by thornbill** [comment]
Fixed by #201
