### ISSUE TITLE
Playback controls show end time in 12h time format instead of 24h

### ISSUE THREAD

**Issue by MrCrowley2** [jellyfin/jellyfin-androidtv#819]
**Describe the bug**
Using the 0.12 debug build from a few days ago the end time in the playback controls shows the time in 12h time format, everywhere else i get the time in 24h format

**To Reproduce**
1. play a tv show
2. Click on a button to show the transport controls
3. time in the upper right corner shows "endet um 10:30 nachm."
4. time in the shows info before playback shows the proper "endet um 22:30"

**Expected behavior**
use 24h time format

**Screen shots**
![timeTransport](https://user-images.githubusercontent.com/46450631/114518753-f8719c80-9c3f-11eb-8208-cb85d8546b41.jpg)

**System (please complete the following information):**
 - Fire TV 4k latest version
 - Amazon
 - Fire Stick 4k
 - Jellyfin server version: 10.7.2
 - debug build app from a few days ago

**Comment by Dawidooox** [comment]
I also experience the same problem on Fire TV Stick 4K, despite the fact that in system settings 24h time format is enabled. The client app version is 0.18.4
