### ISSUE TITLE
'Up Next' countdown goes into negative time

### ISSUE THREAD

**Issue by makotech222** [jellyfin/jellyfin-androidtv#828]
**Describe the bug**
While using shuffle to play a tv show series, the Up Next bar will show a countdown until the next episode starts. Occasionally, the time will go past 0, and go into negative numbers. This state will continue counting down until user intervention. 

**To Reproduce**
1. Enable shuffle play on a tv series
2. Randomly, the Up Next countdown will go into negative numbers.

**Expected behavior**
The Up Next countdown properly transitions to the next show.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - Nvidia Shield 4K
 - Jellyfin server version: 10.7.0

**Additional context**
Seems an easy fix for the countdown, do a Math.Max(0, countdown).

**Comment by nielsvanvelzen** [comment]
app version?

**Comment by makotech222** [comment]
Sorry, 0.11.5

**Comment by nielsvanvelzen** [comment]
Should be fixed in 0.12 👍
