### ISSUE TITLE
"Logging off due to inactivity" popup spam after timeout

### ISSUE THREAD

**Issue by gbakeman** [jellyfin/jellyfin-androidtv#838]
**Describe the bug**
If left running in the background, like by sleeping the device or switching to another app, Jellyfin will begin spamming the screen with a popup/toast saying "Logging off due to inactivity" after the auto logout period and require the app to be removed from memory in order to get the messages to stop.

**To Reproduce**
1. Open app
2. Switch to a different app
3. After timeout, popups begin

**Expected behavior**
I don't think this popup notification is necessary to begin with, but I'd also like an option to disable the auto logout since I only use one account.

**System (please complete the following information):**
 - Android TV or Fire TV version: Shield 2017 Android 9
 - App 11.5
 - Device manufacturer: Nvidia
 - Jellyfin server version: 10.6.4

**Comment by nielsvanvelzen** [comment]
This feature is removed in 0.12.
