### ISSUE TITLE
Migrate from JCenter to Maven Central

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-androidtv#839]
This is the Android TV version of the SDK issue. We need to migrate from JCenter/Bintray to 100% Maven Central + Google Maven.

## Copied from jellyfin/jellyfin-sdk-kotlin#176:

Unfortunately JCenter is closing in a few months. We need to publish the apiclient somewhere else before this happens. Additionally all our Java based projects (the Android apps) need to switch to different repositories for all dependencies.

I think our best bet is to wait a bit and see what other projects in the java ecosystem do before we act.

See the jfrog blog article for some more information:

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by nielsvanvelzen** [comment]
Removing the JCenter repository in the current master branch gives the following issues:

- Jellyfin apiclient - The SDK is on Maven Central, the old apiclient is not. To fix: migrate or (temporary) use jitpack
- Koin - Next version of Koin is already available on Maven Cental as beta, the old one is not. To fix: update Koin.
- ExoPlayer Amazon fork - The project is mostly dead and unmaintained, it's not likely it will be pushed to Maven Central as Amazon needs to change the package for it. To fix: switch to official Google ExoPlayer.

It might be possible to fix these issues for the 0.12 release but it's a relatively low priority for now.

**Comment by nielsvanvelzen** [comment]
Apparently Koin 2.x is available on Maven Central too, it wasn't the last time I checked. I will switch Koin asap.

**Comment by ManuLinares** [comment]
> Removing the JCenter repository in the current master branch gives the following issues:
> 
>     * Jellyfin apiclient - The SDK is on Maven Central, the old apiclient is not. To fix: migrate or (temporary) use jitpack
> 
>     * ~Koin - Next version of Koin is already available on Maven Cental as beta, the old one is not. To fix: update Koin.~ #840
> 
>     * ~ExoPlayer Amazon fork - The project is mostly dead and unmaintained, it's not likely it will be pushed to Maven Central as Amazon needs to change the package for it. To fix: switch to official Google ExoPlayer.~ #843
> 
> 
> It might be possible to fix these issues for the 0.12 release but it's a relatively low priority for now.

jitpack can't be used, https://jitpack.io/com/github/jellyfin/jellyfin-sdk-kotlin/v0.7.9/build.log

**Comment by nielsvanvelzen** [comment]
If it's necessary I can fix the build issues for a 0.7.10 release 👍

**Comment by nielsvanvelzen** [comment]
0.7.10 was released to fix the build issues and #956 will update the app to use it.
