### ISSUE TITLE
Endless Connecting To Last Server Session

### ISSUE THREAD

**Issue by tomaswl1** [jellyfin/jellyfin-androidtv#841]
If a server is offline or if you have to reinstall jellfin server when you open jellyfin android tvapp and it trys connecting to last session it just sticks on the splash loading screen and never changes and only way to fix issue is clearing data in app to get back to the selection server screen

is it possible to maybe implement some kind of fallback if fails to connect to a server to the server screen so can at least manage server to remove if as issues

latest master build
latest jellyfin server version
device Nvidia Shield

Thank you

**Comment by nielsvanvelzen** [comment]
The master branch is not ready for production use. I'm already aware of some issues during startup. You need to force close the app in your system settings to fix this issue.

**Comment by tomaswl1** [comment]
sorry was just highlighting the issue i understand its not full release was just trying to help wasn't aware you was already aware i checked issues before posting

**Comment by nielsvanvelzen** [comment]
No problem, I didn't make an issue for it. I'll work on it after #818 is merged.
