### ISSUE TITLE
Possible to have SMB built into the jellyfin app? Would be able to ditch Kodi.

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [jellyfin/jellyfin-androidtv#845]
**Describe the feature you'd like**	
Possible to have SMB build into the jellyfin app? Would be able to ditch Kodi, as kodi is a little sluggish on the shield.

**Comment by nielsvanvelzen** [comment]
The app only supports Jellyfin servers and will not support anything else.

**Comment by Cookie-Monster-Coder** [comment]
> The app only supports Jellyfin servers and will not support anything else.

I might not have explained it right. Jellyfin already has ability to add a network path (SMB, NFS) in the Libraries section. This is already used by the Jellyfin Kodi addon, so instead of playing the Jellyfin content from the server and using resources it can directly play from the SMB share.

**Comment by nielsvanvelzen** [comment]
There is no intent to support that either. The app will always play the media via the server. The server can choose to read it from SMB or whatever but the client ALWAYS plays via the API of the server.
