### ISSUE TITLE
Invalid Password/Login

### ISSUE THREAD

**Issue by upal212** [jellyfin/jellyfin-androidtv#85]
Hello,
Whenever I am trying to connect through my Android TV the authentication shows as Login/Password as invalid. But it works absolutely fine with the normal Android software running on my phone.

This is the log from the server side:
Authentication request for upal has been denied.

**Comment by thornbill** [comment]
What server version are you running?

**Comment by upal212** [comment]
It is the latest Prerelease 10.3.0-rc1 on Windows x64.

**Comment by thornbill** [comment]
There were some changes to how authentication works in 10.3 that resulted in the previous beta releases for Android TV being unable to login. We should be releasing a new apk soon that fixes this issue.

**Comment by upal212** [comment]
Thank you for the update 👍

**Comment by joshuaboniface** [comment]
The beta5 should fix this - please test it and let us know!

**Comment by anandcu3** [comment]
This has resurfaced for me on Windows Server, Jellyfin Version : 10.3.0.0 and the latest beta5 apk for the firestick.

**Comment by anthonylavado** [comment]
@anandcu3 Please try upgrading to the latest version (10.3.5 at time of writing) and let us know if you still have any issues.
