### ISSUE TITLE
Possibility to jump ahead/back in media by holding left/right arrow

### ISSUE THREAD

**Issue by Johan1976** [jellyfin/jellyfin-androidtv#86]
Possibility to jump ahead/back in media by holding left/right arrow (not same as fast-forward). Showing progress bar. 
Jumping should appear in larger steps so you easily can skip forward an hour in a movie.

**Comment by upal212** [comment]
+1 to this.

**Comment by sanezilla** [comment]
Jumping with left/right arrows is great for skipping commercials if it is 10 seconds per click. The rewind and fast forward buttons should be used for larger steps.

**Comment by shanke0303** [comment]
needed, useful

**Comment by MrChip53** [comment]
This has been added. Will be in the next update.
