### ISSUE TITLE
Can you provide an installation package that does not rely on GMS?

### ISSUE THREAD

**Issue by gjy3035** [jellyfin/jellyfin-androidtv#860]
Jellyfin will crash after logging in. I suspect that GMS is not installed on the TV. 
Can you provide an installation package that does not rely on GMS?

**Comment by nielsvanvelzen** [comment]
You can find the releases on one of these pages, we don't use GMS:

- https://github.com/jellyfin/jellyfin-androidtv/releases
- https://repo.jellyfin.org/releases/client/androidtv/

**Comment by gjy3035** [comment]
Thanks a lot!
