### ISSUE TITLE
Seeking in Exoplayer not working on Transcoded media

### ISSUE THREAD

**Issue by ManuLinares** [jellyfin/jellyfin-androidtv#863]
Jellyfin App, Master branch.

New method of seeking in Exoplayer not working on Transcoded media. Works on direct-play media.

I think this PR #581  introduced the problem. Maybe revert?

**To Reproduce**
1- Open any media that the server transcodes to mkv on jellyfin app.
2- Try to seek by pressing >> or << on remote (one time click or continuous button down).

**Expected behavior**
I expect on 1 click on remote >> or continuous pressing down button, media to seek properly.
On app v0.11.5 , the seeking by 30 seconds increment works on direct-play and transcoded files.

**System**
Firestick (1st Gen), Fire OS 5
Jellyfin server: v10.7.5

**Comment by leocaseiro** [comment]
Related to #308?

**Comment by leocaseiro** [comment]
Related to #308 ?

**Comment by ManuLinares** [comment]
Maybe, but I'm sure when adding the FF and Rewind logic in PR #581, didn't consider that player needs to "stop" for mkv. MKV being transcoded media. So it has another path, logic in [seek method here ](https://github.com/jellyfin/jellyfin-androidtv/blob/master/app/src/main/java/org/jellyfin/androidtv/ui/playback/PlaybackController.java#L835) that wasn't modified.

I am still not that familiar with the code to confidently upload a PR, until then I'm brute-force programming so bad. Help needed.
