### ISSUE TITLE
Users of the app can't authorize on JF server

### ISSUE THREAD

**Issue by WWWesten** [jellyfin/jellyfin-androidtv#87]
Users of the Anroid TV app (release 3 & 4) can't authorize on JF server (10.3.0.0 RC2). May be it is caused by pr https://github.com/jellyfin/jellyfin/pull/870.

**Comment by thornbill** [comment]
Hey @WWWesten this is a known issue at the moment. There is a fix in place we just need to release a new beta build for Android TV. I'm going to close this as it is being tracked in #85.
