### ISSUE TITLE
Jellyfin mutes device at start of video playback

### ISSUE THREAD

**Issue by bt90** [jellyfin/jellyfin-androidtv#881]
**Describe the bug**
If i start a video jellyfin mutes my device and i get a visible `Muted` indicator. Once i hit volume up+down the device is unmuted again and audio plays fine. I've yet to investigate this further but i think the overlay is displayed by my AVR.

**Setup**
Nvidia Shield TV 2019 Pro `---- HDMI---->` Panasonic AVR `--- HDMI --->` LG C9 TV

**To Reproduce**
I'm not sure if it's related to codecs but all tested video files had a DTS track for which passthrough is configured in the Shield settings.

**Expected behavior**
Don't mute the device :)

**System:**
 - Android TV version: 9
 - Device manufacturer: Nvidia
 - Device model: Shield TV 2019 Pro
 - Jellyfin server version: 10.7.5

**Additional context**
Probably related to #309 

According to #322 all muting features should have been removed but i found these lines:

https://github.com/jellyfin/jellyfin-androidtv/blob/2b6973b8d608c886d9ad084293a3de516fa5eb17/app/src/main/java/org/jellyfin/androidtv/auth/ApiBinder.kt#L70-L72

**Comment by bt90** [comment]
Disabling the DTS audio bitstream setting doesn't change this behavior.

The muting seems to happen erratically. I can start the same video multiple times and sometimes it starts muted, sometimes it doesn't. The muting also tends to occur if i stop the playback pressing the back button.

**Comment by nielsvanvelzen** [comment]
The linked code is only to report capabilities to the server, it doesn't call any of the Android API's. Can you provide logs from when the mute happens? It might give us an indicator in why it happens.

Also important to know is which player backend you're using (auto, exoplayer, libvlc or external), and did you try with another player?

**Comment by bt90** [comment]
I'm currently using the ExoPlayer but i can try a different one and gather logs.

**Comment by bt90** [comment]
Also happens with libVLC. How do i gather logs?

**Comment by nielsvanvelzen** [comment]
https://wiki.lineageos.org/how-to/logcat / https://stackoverflow.com/questions/39834242/sony-bravia-android-tv-how-to-enable-retrieve-adb-logcat-logs

**Comment by bt90** [comment]
I captured a log. In this case the video started fine but Jellyfin muted the device as i stopped the playback using the back button.

[logcat.log](https://github.com/jellyfin/jellyfin-androidtv/files/6471583/logcat.log)

**Comment by bt90** [comment]
And here's a second log where i keep starting and aborting the playback of a video causing the device to switch back and forth from unmuted to muted.

[logcat.log](https://github.com/jellyfin/jellyfin-androidtv/files/6471615/logcat.log)

**Comment by bt90** [comment]
Still happens
