### ISSUE TITLE
Combined search Artist/Album/Title

### ISSUE THREAD

**Issue by Norde** [jellyfin/jellyfin-androidtv#886]
The current search engine takes into account Artist name, Album title and Song title but separately.

For example, i'm looking for "SongY from the AlbumZ of ArtistX":
- Typing "ArtistX AlbumZ", "ArtistX SongY" or even ""ArtistX AlbumZ SongY" will not return any results
- I can only use "SongY", "AlbumZ" or "ArtistX" (separately), resulting in a lack of precision and/or a time consuming search.

Would it be possible to allow combined research?

**Comment by nielsvanvelzen** [comment]
We're limited by the search API in the server. Right now it does not support such an feature. If you'd like more advanced search please create a feature request at https://features.jellyfin.org.

**Comment by Norde** [comment]
My apologies, I had myself requested this feature 9month ago ^^ '

https://features.jellyfin.org/posts/783/advanced-music-search
