### ISSUE TITLE
Android TV unable to log in

### ISSUE THREAD

**Issue by groenator** [jellyfin/jellyfin-androidtv#90]
Hi,

I have upgraded jellyfin to the latest server version, 10.3.1, and also installed the latest android TV beta 5 version.

After installing and adding the jellyfin hostname, a new screen opens and ask's to select the user 
I would like to log in. In this instance I have one user on my server that doesn't have a password configured. I select the user to log in, an error pops out; invalid user name and password. 

This is happening since I update the apk to beta5. 

I have tried with android mobile and web interface, both of them dont have this issue.

I also capture a screenshot and a video. If you guys want me to share the video or photo, please let me know.

Regards,

**Comment by groenator** [comment]
![20190423_221154](https://user-images.githubusercontent.com/5445030/56616251-d88cdc80-6614-11e9-82bd-dfabe647cda5.jpg)

**Comment by groenator** [comment]
No idea why the photo is upside down.

**Comment by oddstr13** [comment]
Also reported on Reddit, links for reference;
 * https://www.reddit.com/r/jellyfin/comments/bgb763/jellyfin_1031_released/ellrfwh/
 * https://www.reddit.com/r/jellyfin/comments/bgb763/jellyfin_1031_released/elkb5yk/

**Comment by groenator** [comment]
Thanks!

**Comment by thornbill** [comment]
This should be fixed in server version 10.3.2.

**Comment by groenator** [comment]
Thanks!
