### ISSUE TITLE
Library icons/images too squished horizontally

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin-androidtv#91]
I decided to use some custom images (https://shaefurr.wixsite.com/fanart) for my Libraries instead of the automatic ones and all was perfect in the browser and in the android app:

![image](https://user-images.githubusercontent.com/16859916/56704437-181dfc00-66db-11e9-85e7-a52ee263550c.png)

but in my tv it looks like this:

![image](https://user-images.githubusercontent.com/16859916/56704464-34219d80-66db-11e9-94f7-e7661e96eca9.png)

Not sure if this is a bug or is by design but it would be great if this could be fixed/adjusted in the android tv app.

**Comment by thornbill** [comment]
This should be fixed now.
