### ISSUE TITLE
Lost Context Menu

### ISSUE THREAD

**Issue by Anthael** [jellyfin/jellyfin-androidtv#916]
The context menu ( left hand side menu ) is not accessible or visible on Philips One TV.

**To Reproduce**
1. Open application 
2. Move around on each corner but the the menu doesn't appears anymore

**Expected behavior**
Bind a command from control to force the menu display 

**System (please complete the following information):**
 - Android TV or Fire TV version: Android TV running android pie 9
 - Device manufacturer: Philips
 - Device model: The One 
 - Jellyfin server version: Debug version from master branch ( 25/05/2021 )

**Additional context**

**Comment by nielsvanvelzen** [comment]
Do you mean the navigation on the left to go to a certain row? That's removed.
