### ISSUE TITLE
Video with MP2 has no sound

### ISSUE THREAD

**Issue by cesalo** [jellyfin/jellyfin-androidtv#92]
Same video plays ok (normal sound) in VLC, Plex, etc.
Complete codec is:
**Media Info**
**Video**
Title 1080P H264
Codec H264
AVC Yes
Profile High
Level 42
Resolution 1920x1080
Aspect ratio 16:9
Interlaced No
Framerate 50
Bitrate 6612 kbps
Bit depth 8 bit
Pixel format yuv420p
Ref frames 1
NAL 4
**Audio**
TitleEng MP2 stereo Default
Languageeng
Codec MP2
Layout stereo
Channels 2 ch
Bitrate 256 kbps
Sample rate 48000 Hz
Default Yes
Container mkv

**Comment by ptasznikarium** [comment]
I have the same issue

**Comment by VladlenO** [comment]
Same problem

**Comment by lazi3b0y** [comment]
Same issue here

**Comment by thornbill** [comment]
Instead of adding "me too" comments on a closed 4 year old issue, please open a new issue and fill out all the requested information in the current version of the issue template.
