### ISSUE TITLE
Themes Songs @ TV-Shows?

### ISSUE THREAD

**Issue by bashinator** [jellyfin/jellyfin-androidtv#931]
hi Mates, 

Could someone fix the Issue, that we can't Play Theme-Songs @Nvidia Shield or Amazon Fire Stick?
The theme.mp3 is in the "Show" Folder.

@ Browser, you can Select under "Settings, that Themes Sounds should be played.." But @Android Stuff not.

Could someone bring that Future on next Realease?
We will prefer that :)

Regards

**Comment by nielsvanvelzen** [comment]
Hi, I noticed this issue does not use one of our issue templates. We provide these templates to get the information necessary in order to help. I will close this issue but I encourage you to recreate it using the template so we can help.
