### ISSUE TITLE
Playback issue regarding hevc and subtitles 

### ISSUE THREAD

**Issue by Anan5a** [jellyfin/jellyfin-androidtv#933]
**Checks**
- [x ] Issue does not happen in the browser (jellyfin-web)

**Media Info of the file**

**Logs**

**FFmpeg Logs**

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: Xiaomi 
 - Device model: MI Tv Stick
 - Jellyfin server version: 10.8.0

**Additional context**

The issue is when choosing libVLC on the app jellyfin can direct stream the hevc file without any transcoding. Which is expected. But the subtitles are not shown (ass codec) 
When choosing exo player the subtitle will play but it forces transcoding. Which is undesirable, it degrades the quality and pressure the server needlessly. 

Also It's not possible to Switch chapter and skip too long. The video will start to play from beginning 00:00

Is there any solution for this?

**Comment by reconman** [comment]
Try disabling adapting the refresh rate, Exo has no transcoding for me anymore.
