### ISSUE TITLE
how to get the log file

### ISSUE THREAD

**Issue by zqhong** [jellyfin/jellyfin-androidtv#934]
After launching jellyfin-android-tv, my device crashes.
I would like to know how to get the log file?

**System (please complete the following information):**
 - Android TV: Android 9
 - Jellyfin server version: 10.7.5

**Comment by nielsvanvelzen** [comment]
https://developer.android.com/studio/command-line/logcat

https://www.xda-developers.com/how-to-take-logs-in-android/

(next time please ask these kinds of questions in our chats instead of creating a GitHub issue)
