### ISSUE TITLE
Sony Bravia - HRD grey bars persist

### ISSUE THREAD

**Issue by gammy69er** [jellyfin/jellyfin-androidtv#937]
Issue regarding Grey bars in HDR playback persists for me.

I know it was supposed to have been fixed in "Use transparent background in video player #369" - and was supposed to have been folded into main branch since 0.11.2(ish).  I figuered maybe it got missed and I may have to do my own build.

Checked through the code of the fix - and comparing it to current code - I can see the fix appears to be in place.

Is possible that the OLED's handle things different to the LCD's tested during the last issues... being Sony and all.

the Issue DOES NOT occur on content that is 3480 x 2160 - as it has no "blank" areas.  

**Checks**
- [ ] Issue does not happen in the browser (jellyfin-web) - Not Complete - no transcode as Jellyfin is on a weak NAS and I have turned it off.
- [ ] Checked with Kodi for Android TV (Sony) - via Jellycon - and with Videotape on Windows - no issues
- [ ] Checked with Sony Media Player - via UPNP - no issues
- [ ] Checked on Jellyfin for Android TV - Mi Box 3 - no issues

**Media Info of the file**

<fileinfo>
    <streamdetails>
      <video>
        <codec>hevc</codec>
        <micodec>hevc</micodec>
        <bitrate>16370022</bitrate>
        <width>3840</width>
        <height>1606</height>
        <aspect>2.40:1</aspect>
        <aspectratio>2.40:1</aspectratio>
        <framerate>23.976025</framerate>
        <scantype>progressive</scantype>
        <default>True</default>
        <forced>False</forced>
        <duration>143</duration>
        <durationinseconds>8590</durationinseconds>
      </video>
      <audio>
        <codec>dts</codec>
        <micodec>dts</micodec>
        <bitrate>3830086</bitrate>
        <language>eng</language>
        <scantype>progressive</scantype>
        <channels>6</channels>
        <samplingrate>48000</samplingrate>
        <default>True</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>224000</bitrate>
        <language>eng</language>
        <scantype>progressive</scantype>
        <channels>2</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>
      <audio>
        <codec>ac3</codec>
        <micodec>ac3</micodec>
        <bitrate>224000</bitrate>
        <language>eng</language>
        <scantype>progressive</scantype>
        <channels>2</channels>
        <samplingrate>48000</samplingrate>
        <default>False</default>
        <forced>False</forced>
      </audio>

**Logs**
playback is not impared - Just colours

**FFmpeg Logs**
Can dig them up on request (will need someone to tell me where to dig) - but have set no transcode on the User in question - As NAS is poor and all devices I have are capable of Playback

**System (please complete the following information):**
 - Android TV 9 - Build : BRAVIA_ATK3_4K_PA-user 9 PTT1.190515.001.s38 671401 release-keys
 - Device manufacturer: Sony
 - Device model: KD-65A8G - OLED
 - Jellyfin server version: 10.7.5 - Via Docker on Synology NAS - jellyfin/jellyfin container (presuming official Jellyfin)

**Additional context**
I Like to use the Sony TV Android TV, saves me an HDMI, and is well intergrated into Live TV streaming services.  The Buggest issue is obviously with how it handles Apps.  Used Jellyfin on Mi Box 3 before I got the TV and loved it.  Moved to the TV fo the Benefit of having it all integrated... but hasn't worked out quite like that - as I have to App hop to get Content to run without issues.
Probably would have called it a day if Jellyfin saw the Sony Media player as an external option - but all other players lack something somewhere - Due to Sony.
Am happy to give any information I can - and can attempt builds to test if required.

**Comment by viggy96** [comment]
Typo in your issue title.

**Comment by gammy69er** [comment]
Yeah, have somewhat given up on this. Jellyfin works fantastic on MiBox3, so is definitely not a developer issue... F#£&ing Sony... 
Playback on Sony internal player via upnp is fine, for the most part.
Have noticed also the playback on REALLY high bitrate files is trash, have some 20+ GB SDR files, around 45 mins, and the TV playback is choppy at times (appears to buffer) and moving to WiFi did not help (AC @ 650+ mbps vs 100mbps ethernet - as playback was exceeding 125mbps at times).  MiBox3 doesn't have ethernet, and plays back these flawlessly (less the intro - presuming high motion and lots of colours), so suspect weak CPU performance on the TV.
At this stage, would probably recommend putting a hold/close on this issue, as others have mentioned, other Sony TV's don't appear to have the issue, and with a Google TV update expected in the next 6 months or so, is probably not worth chasing.  Maybe at that time it'll be fixed and apps will render @ 4k... With any luck.

Anywho, cheers for the hard work, beyond my H/W issues and the occasional crash when paused and then sleeping, Jellyfin for AndroidTV is top notch. Keep it up.

**Comment by viggy96** [comment]
Have you tried manually setting the streaming bitrate on the Android TV app? The default of "auto" doesn't appear to work correctly. I manually set it to 120 Mbps, the highest manual setting.

**Comment by viggy96** [comment]
I have this issue on the latest version 16 beta 2.

Not sure what made this issue reappear.

**Comment by viggy96** [comment]
Paging @nielsvanvelzen

**Comment by nielsvanvelzen** [comment]
No need to ping, please create a new issue.
