### ISSUE TITLE
App doesn't remember login

### ISSUE THREAD

**Issue by ddurdle** [jellyfin/jellyfin-androidtv#95]
The app doesn't remember to automatically log in even though it is checked in Settings.

**Comment by ddurdle** [comment]
are you sure this was fixed?  Someone pulled together the latest github code on 5/16 and that version still had the login every time error.

**Comment by anthonylavado** [comment]
cc @thornbill?

**Comment by ddurdle** [comment]
It's fixed.  confirmed

**Comment by skug67** [comment]
Is there any chance of pushing out a version with this fix to the repo?  I tried building myself but I'm a noob, and the resulting package wouldn't install on my TV.

Thanks in advance.
