### ISSUE TITLE
Pause screen with no gui

### ISSUE THREAD

**Issue by Unimeron** [jellyfin/jellyfin-androidtv#96]
As suggested on Reddit here's an issue.

When pausing playback there should be an option to hide the gui. By this the still image can be seen without obstructions to read subtitles, that are part of the picture, or other things shown.

This can work the same way as in the FireTv Prime Video App: button play/pause pauses the playback and brings up the gui as normal. Now pressing down or back (not sure atm) hides the gui an the full screen picture is shown.

**Comment by mueslimak3r** [comment]
seems to be fixed at least since 0.12

**Comment by nielsvanvelzen** [comment]
Closing as fixed, please let us know if you're still experiencing this issue.
