### ISSUE TITLE
Dolby Vision

### ISSUE THREAD

**Issue by hamburglar2160** [jellyfin/jellyfin-androidtv#987]
Dolby Vision Profile 7 appears to be the only Dolby Vision profile supported on master branch right now. I don't have any idea if this is a problem involving Exoplayer, Jellyfin, or the ATV client. Video samples with different DV profiles are available here https://www.makemkv.com/download/dvtest/ and among these videos only p7_MELand p7_FEL will play for me.

relevant logs:
EnablePlaybackRemuxing: False EnableVideoPlaybackTranscoding: False EnableAudioPlaybackTranscoding: True
Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-libVLC", Path: "/P4 LG Dolby Trailer 4K Demo/P4_LG_Dolby_Trailer_4K_Demo.mkv", isEligibleForDirectPlay: True, isEligibleForDirectStream: True
Jellyfin.Api.Helpers.MediaInfoHelper: Profile: "AndroidTV-libVLC", No video direct play profiles found for "/P4 LG Dolby Trailer 4K Demo/P4_LG_Dolby_Trailer_4K_Demo.mkv" with codec "hevc"

Jellyfin 10.7.6
Chromecast w/ Google TV

**Comment by nielsvanvelzen** [comment]
Hi, I noticed this issue does not use one of our issue templates. We provide these templates to get the information necessary in order to help. I will close this issue but I encourage you to recreate it using the template so we can help.
