### ISSUE TITLE
libVLC player crashing during playback

### ISSUE THREAD

**Issue by viggy96** [jellyfin/jellyfin-androidtv#989]
**Describe the bug**

libVLC player crashes during playback. I've noticed it during playback of files with H.264 video codec, with ASS subtitles.

**To Reproduce**

1. Set player choice to "auto"
2. Play file with SSA/ASS subtitles 
3. Profit

**Expected behavior**

Playback occurs smoothly without incident.

**Logs**

[jellyfin-android.log](https://github.com/jellyfin/jellyfin-androidtv/files/6743063/jellyfin-android.log)

**System (please complete the following information):**
 - Android TV or Fire TV version: Android 9
 - Device manufacturer: Sony
 - Device model: X900F
 - Jellyfin server version: 10.7.6

EDIT: Log attached above.

**Comment by viggy96** [comment]
This still occurs on the 12.x beta.

**Comment by viggy96** [comment]
I've found this issue on files without SSA/ASS subtitles as well.
[jellyfin-androidtv.log](https://github.com/jellyfin/jellyfin-androidtv/files/7272376/jellyfin-androidtv.log)
[jellyfin-androidtv2.log](https://github.com/jellyfin/jellyfin-androidtv/files/7272377/jellyfin-androidtv2.log)

**Comment by nielsvanvelzen** [comment]
I see this exception in your logs, I don't  think it's the cause of the crash though.

```
10-01 22:38:38.161 30707 30707 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void org.jellyfin.androidtv.ui.playback.IPlaybackOverlayFragment.updateDisplay()' on a null object reference
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.playback.PlaybackController.startItem(PlaybackController.java:634)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.playback.PlaybackController.access$200(PlaybackController.java:61)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.androidtv.ui.playback.PlaybackController$6$1.onError(PlaybackController.java:573)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.Response.onError(Response.java:32)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.SerializedResponse.onResponse(SerializedResponse.java:41)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.SerializedResponse.onResponse(SerializedResponse.java:6)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.ApiClientRequestListener.onResponse(ApiClientRequestListener.java:21)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.ApiClientRequestListener.onResponse(ApiClientRequestListener.java:5)
10-01 22:38:38.161 30707 30707 E AndroidRuntime: 	at org.jellyfin.apiclient.interaction.VolleyResponseListener.onResponse(VolleyResponseListener.java:22)
```

**Comment by viggy96** [comment]
It might be the source of the issue. In the above logs, the app didn't exactly crash, but it froze up, and video output went black. I was unable to go back as well. After I pressed back on my remote, the TV made navigation sounds suggesting that I was navigating the episode info screen for the given episode I was watching, but the app was still displaying a blank black player. Going to the Android home screen and coming back to Jellyfin was ineffective. I still still stuck at a blank player. I was forced to force stop the app. This doesn't happen if I manually select ExoPlayer for playback.

**Comment by nielsvanvelzen** [comment]
I made #1174 that adds nullability checks to prevent that exception.

**Comment by viggy96** [comment]
I have tried a build with your changes locally, but I still get libVLC crashing. However, this time it is just libVLC that crashes, and after about 10 seconds, I get kicked out to the Jellyfin app home screen, instead of the whole Jellyfin app locking up.

Here is another log:
[jellyfin-androidtv3.log](https://github.com/jellyfin/jellyfin-androidtv/files/7274242/jellyfin-androidtv3.log)

**Comment by nielsvanvelzen** [comment]
Good to hear the PR improves at least something. Unfortunately I don't see anything weird in your latest logs.

**Comment by viggy96** [comment]
This time libVLC froze when I tried to seek forward. 
Something interesting in the log here:
```
10-03 16:30:44.325 14957 17305 E NdkMediaCodec: sf error code: -38
10-03 16:30:44.325 14957 17305 W VLC     : [88d94930/4399] libvlc decoder: AMediaCodec.dequeueOutputBuffer failed
10-03 16:30:44.325 14957 14957 D PlaybackController: Play called with pos: 2125359 and sub index: -1
```
[jellyfin-androidtv4.log](https://github.com/jellyfin/jellyfin-androidtv/files/7274490/jellyfin-androidtv4.log)

**Comment by viggy96** [comment]
I see the same `NdkMediaCodec: sf error code: -38` in my previous log.
