### ISSUE TITLE
TV Guide - channels are missing the highlighted bar when browsing or selecting them

### ISSUE THREAD

**Issue by groenator** [jellyfin/jellyfin-androidtv#99]
I am using the latest beta version. When I go to the TV guide and browse, the channels are not showing the highlighted bar as it should be. Also, after selecting a channel the pop-up menu has a transparent background. 

Here's a link from a short video that I took.

https://giphy.com/gifs/1gT0h4GkvOBtPlAaLJ/html5

**Comment by cesalo** [comment]
Same here. This change will make the Live TV experience much greater.

**Comment by groenator** [comment]
Awesome, I look forward. Any idea when it will be implemented?

**Comment by thornbill** [comment]
We generally don’t have timelines since we’re all volunteers working on Jellyfin as time allows. I did start looking into this and hopefully we can get it fixed in the next beta whenever that lands. 😄

**Comment by groenator** [comment]
Great! Thanks for the feedback. 🥳
