### ISSUE TITLE
(master) Images with no blurhash are stretched on initial load

### ISSUE THREAD

**Issue by linetrimmer** [jellyfin/jellyfin-androidtv#992]
**Describe the bug**
Some images are being stretched rather than doing a proper centerCrop. I first noticed this with cast images (see screenshots), but after adding the backdrop fallback for thumbnails in #991, I noticed it happens there too. In both cases, the images are initially stretched, but they're sometimes fixed if you scroll the row so the images go off screen and then come back. 

I'm not sure what about not having a blurhash would cause this, but both cast images and backdrops don't load blurhashes and they're the only two image types affected for me. I tried completely skipping the blurhash loading in `updateCardViewImage()` in `CardPresenter`, and rather than fix the issue it made the issue apply to every image in my library. 

**To Reproduce**

1. Go to a series or movie
2. Look at the cast images
3. They're stretched
4. Scroll the cast row so the stretched images go off screen a decent amount, then scroll back
5. They're not stretched anymore

**Expected behavior**
Proper centerCrop effect for all images the first time they appear on screen

**Logs**
N/A

**Screenshots**
![stretched](https://user-images.githubusercontent.com/46704654/124088486-f807c700-da20-11eb-9963-d037a299c02b.png)
![normal](https://user-images.githubusercontent.com/46704654/124088492-f9d18a80-da20-11eb-9983-b4999d570ef2.png)
The images after Jesse L. Martin weren't scrolled far enough off screen to be fixed since the row isn't long enough.

**System (please complete the following information):**
 - Android TV or Fire TV version: Master
 - Device: Emulator
 - Jellyfin server version: 10.7.6

**Comment by nielsvanvelzen** [comment]
I can confirm this issue happens on my Android 8 television and my API 22 emulator. Can't reproduce on Android 9 shield and API 30 emulator.
